### ISSUE TITLE
Ubuntu - integration

### ISSUE THREAD

**Issue by landsman** [avocode/avocode#1001]
Hi,

how can i install Avocode for full-system integration? I mean "Development" menu, icon to desktop etc.

Thanks

**Comment by jakubzitny** [comment]
Hi @Studioartcz, thanks for your question. Currently, we have no packages or installers for Linux distributions. This is in our TODO list and we're planning to improve the whole Linux experience in coming months. We'll definitely let you know when we release a Ubuntu package.

For now, you can customize and use `avocode.desktop.in` file which is bundled in the .zip archive when you download Avocode for Linux. I believe you can use `desktop-file-install` command to install it in Ubuntu. (#835)

**Comment by Studioartcz** [comment]
https://github.com/unindented/electron-installer-debian

**Comment by Studioartcz** [comment]
@jakubzitny 

> landsman@thinkpad:~/software/Avocode-linux-x64$ cp avocode.desktop /usr/share/applications/
> cp: cannot stat 'avocode.desktop': No such file or directory
> landsman@thinkpad:~/software/Avocode-linux-x64$

**Comment by jakubzitny** [comment]
@Studioartcz The file in `Avocode-linux-x64` is called `avocode.desktop.in`. You also have to edit the contents based on the location of your app.

I'll do my best to include the `.deb` installer into next release ;)

**Comment by Studioartcz** [comment]
@jakubzitny This can be better to use (name can be install.sh):

#!/bin/sh

BASEDIR=$(pwd)
FILE="~/.local/share/applications/avocode.desktop"

/bin/cat <<EOM >$FILE
[Desktop Entry]
Name=Avocode
Comment=The bridge between designers and developers
GenericName=Design Inspector
Exec=$BASEDIR/Avocode
Icon=$BASEDIR/avocode.png
Type=Application
Categories=GNOME;GTK;Utility;Development;
MimeType=text/plain;

**Comment by jakubzitny** [comment]
Thanks @Studioartcz. Definitely, something like this might work. I hope it works for you right now.

We will be working on overal enhancement of the Linux experience. Actually, we have already started in several internal things. We will be adding packages that support auto updates and more.

Stay tuned and don't hesitate to contact us if you have any more questions 😉

**Comment by behuti** [comment]
Where can I get the *.deb file to install it on ubuntu x64?

**Comment by vojtatranta** [comment]
@behuti nowhere. So far, we just provide `.zip` file

**Comment by jakubzitny** [comment]
Hey guys, we've added `apt` repository a while ago, so I am closing this issue.

Ubuntu and other Debian-like distros should be able to install Avocode easily. Detailed info on how to add the repository, install and update is at [help.avocode.com](https://help.avocode.com/app-settings/installing-avocode-on-linux). We also have a [repo in AUR](https://aur.archlinux.org/packages/avocode/) for Arch Linux.

**Comment by landsman** [comment]
Good job, I'll test it

**Comment by evanre** [comment]
@jakubzitny Hello, could you please update outdated Avocode version on Aur? This "New version available" splash screen appears every 5 minutes. That's make me crazy :)

Thank you!

**Comment by jakubzitny** [comment]
Sorry that is a mistake it was not released yet. I will do it by Monday.

**Comment by jakubzitny** [comment]
For now, you can download latest Avocode zip for Linux from avocode.com/download and update manually.
