### ISSUE TITLE
Not uploading the image

### ISSUE THREAD

**Issue by amitgarg91** [avocode/avocode#1003]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.2
Source UID: 81944
```
Error: ENOENT: no such file or directory, open '/Users/Tais/.avocode/userdata/81944/documents/10e27ffc52324ea29a5faec6a337722a/images/resources.tar.gz'
    at Error (native)
```

**Comment by connor-bean** [comment]
Hey @amitgarg91 -

Can you try downloading our most recent version (2.8.4) to see if this solves the problem? It looks like you're currently using 2.8.2. 

You can download it for your Mac [here](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.8.4/avocode-app-mac-2.8.4.zip).

Please let me know if it works or not.

Thanks!
Connor, Avocode Support
