### ISSUE TITLE
Processing of file stuck at 95% in app, while plugin upload of same file is fine

### ISSUE THREAD

**Issue by maxklass** [avocode/avocode#1009]
Thank you for work, using your software for about half a year. Today I first encounter issue, which I would like you to see:

Symptoms of issue is similar to:
https://github.com/avocode/avocode/issues/843
https://github.com/avocode/avocode/issues/692

Uploading psd file through avocode app on windows, it is stuck on "processed 95%" for couple of hours. Preview is visible for some time. Tried reuploading, restarting. Here is link to file if it helps https://manager.avocode.com/view/b60cc30bebd845c4b4c08540cd882006/
(as of writing it, it doesn't load preview anymore) After some time design is marked as "failed" in app (red background with offer to send bug report).

When uploading the same file through photoshop plugin, it gives warning about exporting smart object and then successfully upload and processes the design. (https://manager.avocode.com/view/f5dc05d8ba854ad7830768488e421450/)

I expected both app and plugin to behave identical, or at least app to provide error info or recommendation about what should I do, if processing take more then 10 minutes.

Platform - windows 8 64 bit
Avocode app - 2.8.4
Plugin - 2.3.3

If you need more information, please, let me know, and thank you again for avocode.

**Comment by connor-bean** [comment]
Hello @maxklass -

We apologize for the inconvenience.

Avocode servers experienced unexpectedly heavy load over the past few days, that why the processing took that long (or didn't work at all) for some of our users.

We've already took the steps necessary to tackle the situation, so the processing should work just fine now.

Could you please try it again?

Let me know!
Best regards,
Connor, Avocode Support

**Comment by maxklass** [comment]
Yes, I had uploaded same files couple of times through app, no problems this time, files processed in reasonable time.

**Comment by connor-bean** [comment]
Great. Thanks for letting us know. Once again, we apologize for any frustration this caused.

Thanks,
Connor, Avocode Support
