### ISSUE TITLE
Reporting issue in project design area in app doesn't work correctly

### ISSUE THREAD

**Issue by maxklass** [avocode/avocode#1010]
When I click on "send us a bug report" in project designs section (see screenshot below) avocode open chrome window with empty address bar and no page loaded. I expected it to behave similar to menu in toolbar Help -> Report issue which is open new chrome tab (not window) and loads page "https://github.com/avocode/avocode/issues"

Windows 64 bit app 2.8.4

<img width="960" alt="report_error" src="https://cloud.githubusercontent.com/assets/1101590/17295100/2b2ce93a-5803-11e6-878e-be0da0a0217e.png">

**Comment by petrbrzek** [comment]
Thanks for your suggestion. I've changed that.

**Comment by petrbrzek** [comment]
Changed in 2.9.0
