### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by adiberda** [avocode/avocode#1015]
hi i keep getting "connection erre when requesting csrf token please check your connection"
what can i do? cuse i have connection/

**Comment by petrbrzek** [comment]
Thanks for reporting this issue. What version of Avocode are you usign? Do you have any proxy settings enabled?

**Comment by connor-bean** [comment]
Hey @adiberda -

In case you are behind a proxy, here is a guide to properly set it up in Avocode:

https://avocode.zendesk.com/hc/en-us/articles/203402352-How-to-use-a-proxy-server

Also, this another article may help - those are domains we are using and which may be needed to be whitelisted on your side if you are under restrictive proxy or firewall:

https://avocode.zendesk.com/hc/en-us/articles/205022361-Used-domains-to-whitelist

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @adiberda -

Did it help to whitelist Avocode on your proxy?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Closing ticket due to inactivity. Please reopen if you still have this problem after you've checked your proxy settings.

Thanks!
Connor, Avocode Support
