### ISSUE TITLE
export ico, when color overlay on parent "group" in psd

### ISSUE THREAD

**Issue by filestealer** [avocode/avocode#1016]
Hello!
Have problem. Desiner add some icons to group in photoshop. Then add effect to group - color overlay.
Icons turn yellow from red. In Avocode i see yellow icons. When i push "export" button, in "Export assets" i see yellow icon. But when export, i have red png icon.

**Comment by vojtatranta** [comment]
Hi!
This looks like a bug in export. Can you please share with us that particular .psd / sketchfile at team@avocode.com?
It would be easier for us to debug it.

**Comment by filestealer** [comment]
Sended

**Comment by vojtatranta** [comment]
@filestealer thank you so much!

**Comment by vojtatranta** [comment]
@filestealer Hi, so basically it is not a bug, but it is more like a bad UX.
If you export the whole group the effect will be applied. But if you export individual layer the effect of the parent group won't be applied.

We know about it and we are going to fix it.

Until then please export individual icon shapes and change color fill in the .svg or use slice tool to export icon as a bitmap with the correct color.
