### ISSUE TITLE
Export image in mask - Avocode + Sketch

### ISSUE THREAD

**Issue by morcegon** [avocode/avocode#1018]
I have this masked image:

![captura de tela 2016-08-04 as 14 23 40](https://cloud.githubusercontent.com/assets/31614/17411535/13b8159c-5a4f-11e6-99b3-36a697d34231.png)

![captura de tela 2016-08-04 as 14 24 21](https://cloud.githubusercontent.com/assets/31614/17411558/2d0dd554-5a4f-11e6-814b-d746ac93c4d1.png)

When I try to export, the preview looks nice

![captura de tela 2016-08-04 as 14 25 09](https://cloud.githubusercontent.com/assets/31614/17411586/477ed3c0-5a4f-11e6-8602-d28da1088a3f.png)

The dimensions looks right to (in this case a perfect square 170x170 px), but the exported file is wrong

![captura de tela 2016-08-04 as 14 34 35](https://cloud.githubusercontent.com/assets/31614/17411946/97c75a4a-5a50-11e6-951a-7a0cf1f1803d.png)

Is not the image in the mask, there are an background area.
I think this is a bug.

I'm using the 2.9.1 version of Avode and Sketch 39.1.

**Comment by connor-bean** [comment]
Hey @morcegon -

Can you send us this design to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by morcegon** [comment]
Sended.

**Comment by connor-bean** [comment]
Hey @morcegon -

Thanks for sending over the file. I have passed it along to my dev team. They will respond here when they have more information.

Connor, Avocode Support

**Comment by miguelnavarro89** [comment]
What? 😱 More than a month went by and none solution yet? Please at least give some information, and apologies, it's just annoying!

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

Thanks for your patience on this.

Connor, Avocode Support
