### ISSUE TITLE
Wrong different hex color code

### ISSUE THREAD

**Issue by fernandodamaso** [avocode/avocode#1019]
on this layout (and some others), when i select a shape, that has a background color, it gives me the hex code of that shape, but, when i use the color picker to sample that color, it gives me a different hex color code. As you can see on the print screen. The color picker should have the exact hex color code than the background-color of the shape. 

The background-color provided, seems to be slightly more pale (less satureted) than the color picker.

![screenshot_2](https://cloud.githubusercontent.com/assets/4246135/17412853/3ddfe308-5a55-11e6-9d3e-bbcaf06263c7.png)

**Comment by vojtatranta** [comment]
Hi,
that seems odd. Can you share with us that .psd at team@avocode.com? Thanks.

**Comment by fernandodamaso** [comment]
Sure, i'l send the email to team@avocode.com, you can get it here also tough
https://we.tl/ROlJ3Oumcv

**Comment by fernandodamaso** [comment]
here is the PSD requested from the following issue
https://github.com/avocode/avocode/issues/1019#issuecomment-238229795

https://we.tl/ROlJ3Oumcv

Em seg, 8 de ago de 2016 às 10:09, vojtatranta <notifications@github.com>
escreveu:

**Comment by vojtatranta** [comment]
Sorry @fernandodamaso,
I cannot find a state of that document when menu is expanded, can you give me some hint what should I show or not? 

Have you sent us correct psd?

Thanks

**Comment by fernandodamaso** [comment]
I don't really understand what you just said rs regarding a state of
document when menu is expanded rs. It's the index of a website, on avocode
it gives two different #hex colors, when selecting trough the colorpicker
or using the background color on the shape objects.

Anyway, i'm just reporting the bug ^^

o/

Em seg, 8 de ago de 2016 às 11:34, vojtatranta <notifications@github.com>
escreveu:

**Comment by vojtatranta** [comment]
I have your design opened in Avocode now and I don't see the menu and the images you clipped on the screenshot you sent us.

Nevermind, I see that "greenish" color which is as background of "TELEFONE" is different in Color Picker and in the Code panel. According to Photoshop it seems that Code Panel color is the right one - 
``` css
background-color: #429990;
```

That is a bug and we fix it, thank you for your time and report!

**Comment by petrbrzek** [comment]
@fernandodamaso This is happening when a Photoshop document is saved in a different "Color profile" than "sRGB". I'm not sure if we can do something about this. Every major browser would display it differently. If you can please tell your designer to change the color profile to "sRGB".

![color_settings_and_untitled-1___100___rectangle_2__rgb_8_windows___](https://cloud.githubusercontent.com/assets/879564/18035479/e967a6e8-6d56-11e6-8abc-e6d1926789e2.png)

**Comment by fernandodamaso** [comment]
Will do, thanks man =)

**Comment by mwq27** [comment]
This is still happening with a Sketch file and Avocode 2.16.2.  Is anyone still seeing this issue other than my team?

**Comment by bolekkerous** [comment]
Hey, @mwq27 -
please send us the problematic design to team@avocode.com so we can investigate the problem properly.

This problem is usually caused by color profiles in Sketch - it's a really complex issue which we're not able to solve on our side with the current technology.

However we're already working on a new rendering technology which should also solve this problem in the end. We aim to release it at the beginning of 2018.
