### ISSUE TITLE
Allow variables to be project specific

### ISSUE THREAD

**Issue by matthojo** [avocode/avocode#102]
**Description:** At the moment variables work great, however having to set them on each design is a little tedious. It would be great if there was a way to 'share' with other designs within the same project.
**Expected result:** Variables can be shared across designs within a project.
**Actual result:** Variables are scoped to each design.

**Comment by patrikholcak** [comment]
Thanks for the suggestion. It’s kinda obvious it should work this way. :)

**Comment by matthojo** [comment]
As a bonus feature to variables, it would be nice to have a button to 'Create variable and add another', instead of having to initiate the modal after each entry.

I can add this as a separate issue on here if you would like me to.

**Comment by rychlis** [comment]
Avocode 1.1.0 now has project-wide variables.

The 'Create variable and add another' button is a good idea, we will add it to our timeline. I've created a separate suggestion on uservoice for that: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7120778-add-create-variable-and-add-another-button
