### ISSUE TITLE
Download metadata

### ISSUE THREAD

**Issue by Ksernik** [avocode/avocode#1024]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 24303
```
TypeError: Cannot read property 'get' of undefined
    at e._loadRevisionData (file:///C:/Users/K/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:9:31241)
    at file:///C:/Users/K/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:9:30329
    at Immediate._onImmediate (file:///C:/Users/K/AppData/Local/avocode/app-2.8.4/resources/app.asar/dist/avocode.min.js:13:17516)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by vojtatranta** [comment]
Hi @Ksernik,
is it happening again and again?
Is it just one design or more of them?

**Comment by Ksernik** [comment]
Hi =)
yes, it was repeated several times.. in different designs.
some of them loaded , and some do not

**Comment by Ksernik** [comment]
By the way , sorry for my bad english

**Comment by vojtatranta** [comment]
No problem.
It seems that it might have been caused by update. You may try to delete your `C:/Users/K/.avocode/state.json` file and let app to sync everything again.

It might help.

**Comment by vojtatranta** [comment]
And of course!!!

Update your app! In the `Help` menu click `Check for updates` or restart your app to check for updates! Current version is `2.9.1` you are running `2.8.4`

**Comment by Ksernik** [comment]
when I click on the "Check for updates"- nothing happens..
I will try to update from avocode.com
thanks for the answer =)

**Comment by vojtatranta** [comment]
Well that button should change to eg. `Downloading an update...`.

If an update is available. And it takes a while to download it. 

We will add a graphical notification there.

**Comment by Ksernik** [comment]
I installed a new version. (2.9.1)
but those designs , which I tried to open the first time , is now highlighted in red
"This design failed processing and cannot be opened.... if problem persists, please contact us at team@avocod.com"
by the way, in the new version was notification "no update available" =)

**Comment by vojtatranta** [comment]
@Ksernik have you tried to delete your `state.json` as I wrote?

Strange. Do you use proxy or something?

**Comment by Ksernik** [comment]
Yes , I deleted this file before installing the new version..
No , there are no firewalls or proxy

**Comment by vojtatranta** [comment]
And what is your location?

**Comment by Ksernik** [comment]
Unfortunately - Russian Federation X-D

**Comment by vojtatranta** [comment]
We haven't heard any complaints about updates from Russia. And we have lots of customers there.

Let us know if another won't pop up. We release updates every two weeks.

**Comment by Ksernik** [comment]
well , if the situation changes , I will write here =)

thanks again

**Comment by vojtatranta** [comment]
thanks

**Comment by Ksernik** [comment]
well.. after the designer re- loaded models, error disappeared =)
