### ISSUE TITLE
Avocode is exporting images in a wrong size

### ISSUE THREAD

**Issue by miguelnavarro89** [avocode/avocode#1025]
Hey hey Team,

Have found a bug apparently:
I was exporting a set of images and suddenly found a horrible result, they were exported using a weird extra space around.

This is happening whether using PNG or JPEG, or whatever.
Please see the screenshots and try to replicate the issue, if you need more info
or details please let me know.

Hope to see it fixed very soon!
Thank you.

**Technical specifications:**
- OS X El Capitan Version 10.11.6 (15G31)
- Avocode Latest version today Aug 7, 2016
- Avocode Sketch Plugin V. 3.8
- Sketch Version 39 (31667)
  ![pasted_image_8_7_16__23_58](https://cloud.githubusercontent.com/assets/6646268/17469682/135f6056-5cfb-11e6-811c-1040c77571c2.png)

![pasted_image_8_8_16__00_00](https://cloud.githubusercontent.com/assets/6646268/17469738/adbbfce0-5cfb-11e6-94c6-553a1f9e67b2.png)
![pasted_image_8_8_16__00_02](https://cloud.githubusercontent.com/assets/6646268/17469740/b0c65c78-5cfb-11e6-93a5-e64346d4533f.png)

**Comment by connor-bean** [comment]
Hey, @miguelnavarro89 -

Can you send us the design to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by vojtatranta** [comment]
@miguelnavarro89 Hi,
exactly as @connor-bean says. We need that particular design.

It seems as a problem with clipping masks and final composition of all the layers is buggy.

And thank you sooo much for an outstanding bug report. I wish all the reports were the same.

**Comment by miguelnavarro89** [comment]
This is the file:
[@miguelnavarro89-design-issue-avocode.sketch.zip](https://github.com/avocode/avocode/files/407459/miguelnavarro89-design-issue-avocode.sketch.zip)

**Comment by bolekkerous** [comment]
This should be already fixed in the newer versions of Avocode app.

You can always download the latest version here:
https://manager.avocode.com/downloads/

If you still experience this problem or any other problem, please create a new issue or comment here.
