### ISSUE TITLE
SVG Export from PSD

### ISSUE THREAD

**Issue by Viktor-K** [avocode/avocode#1029]
I try to export one layer of my PSD file as SVG, the result is different from the original. The transparency inside of shapes is filled. I'm not found any options about this during export or in preferences menu.  Example:

**Before**
![screen shot 2016-08-09 at 09 49 41](https://cloud.githubusercontent.com/assets/5895397/17508739/ba00523c-5e16-11e6-98eb-8b4f8b2fd45b.png)

**After**
![screen shot 2016-08-09 at 09 50 00](https://cloud.githubusercontent.com/assets/5895397/17508738/b9fa7b50-5e16-11e6-82da-b667b134f5bd.png)

Operating System : OS X El Capitan 10.11.4
Avocode Version : 2.9.1 Trial version

**Comment by vojtatranta** [comment]
Hi,
can you send us this problematic psd at team@avocode.com?

Is this box shape in a group? If so, try to export whole group, this might be caused by an effect on the whole group.

**Comment by vojtatranta** [comment]
Hi @Viktor-K ,
e-mail came our rendering team is on it!

**Comment by connor-bean** [comment]
Hey @Viktor-K -

How was the design created (was it imported from Illustrator or something similar)?

Thanks,
Connor, Avocode Support

**Comment by bolekkerous** [comment]
Unfortunately, the vector layer is imported from Illustrator to the PSD, which is something we do not support yet.

If you want us to support Illustrator, please upvote it on our UserVoice:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992611-illustrator-support

Best regards,
Bolek, Avocode Team

**Comment by rychlis** [comment]
We have been able to support these layers better, the export works fine now in the latest Avocode
