### ISSUE TITLE
SVG export of smart object fails

### ISSUE THREAD

**Issue by martindrzka** [avocode/avocode#103]
When i try export vector smart object, error notification pop up "Your avocode as gone bad". Same notion bug on exporting 2 objects (shape layer and text layer - i would expect one SVG file).

**Comment by petrbrzek** [comment]
Could you share us the problematic design to support@avocode.com? (Ideally through Avocode manager.)

**Comment by kirillkostko** [comment]
Import smart object in SVG file convert vector in raster even when I open smart object in new tab.

**Comment by lolmaus** [comment]
Whenever i doubleclick a vector smart object, Avocode immediately crashes.

Here's what appears in console:

> [1368:0318/193556:ERROR:browser_main_loop.cc(207)] GLib-GObject: invalid uninstantiatable type '(null)' in cast to 'GObject'
> 
> (avocode:1368): GLib-GObject-CRITICAL **: g_object_get_data: assertion 'G_IS_OBJECT (object)' failed
> Segmentation fault (core dumped)

I'm on Kubuntu 14.10 x64.

I've shared a problematic file for support@avocode.com (”Promo page new” in project Hello Baby).

**Comment by tomashanacek** [comment]
Fixed in Avocode 2.0.0
