### ISSUE TITLE
Incorrect PNG/JPEG/SVG/Base64 export

### ISSUE THREAD

**Issue by lobzenko** [avocode/avocode#1033]
Hi, i'm trying to export some icons (contains many small figures) Windows 10 x64

![image](https://cloud.githubusercontent.com/assets/2557329/17565849/3df50298-5f63-11e6-8039-54421cace300.png)

and what i get 

![house](https://cloud.githubusercontent.com/assets/2557329/17565865/53cc6cfa-5f63-11e6-8b64-527c1205a090.png)

wrong size and uncomplete. This behavior works not for all figures.

**Comment by vojtatranta** [comment]
Hi Michail,
we are sorry to hear this.

It is strange that this icon looks like this even though it is exported as bitmap.
So far I can just recommend you to use slice tool to get the right icon.

And most importantly. We need that problematic PSD in order to fix it. Can you please send it to team@avocode.com?

**Comment by lobzenko** [comment]
Thx for response.

Its Sketch export from Mac for frontend developer on Windows.

I didnt have source file : (

some details: i added some nearest elements, like this
![image](https://cloud.githubusercontent.com/assets/2557329/17567697/a0f6c636-5f6a-11e6-9947-c82457e74d92.png)
export works fine.

**Comment by vojtatranta** [comment]
Oh, that's pity. Can you at least tell us the name of that design and email you use to log into Avocode.

**Comment by lobzenko** [comment]
ok, send to email

**Comment by lobzenko** [comment]
Try it on notebook and export to PNG works! 

While i found one error 

![12-layers](https://cloud.githubusercontent.com/assets/2557329/17580504/4544ae7a-5fc9-11e6-9da5-b24c397a46f9.png)

original 
![image](https://cloud.githubusercontent.com/assets/2557329/17580515/64e5a388-5fc9-11e6-87d8-ab927d4d31b9.png)

Same system Windows 10 x64

**Comment by vojtatranta** [comment]
We got that email and we are going to examine it, thanks!

**Comment by kkrebs** [comment]
Hi,
I think I have a similar problem exporting from Avocode. The problem always occurs when I want to export several layers. The layer merge changes the position of every single image. Using slice is a workaround, but often troublesome because I have to hide all layers I don't want to export.

**Comment by TiloNN** [comment]
The same here:
On merging multiple layers, the alignment is lost. 

It seems a crop process is done for each layer **before** merging. 
After that they are aligned top left and merged.

**Comment by TiloNN** [comment]
Updated my error report.

I know, the slice tool works and merging by photoshop or sketch (before uploading) will help too.
But that would be a big lost of comfort.

**Comment by connor-bean** [comment]
Hey, @TiloNN @kkrebs -

Would you be able to send us the problematic design to team@avocode.com? Please mention Ticket 1033 somewhere in your email so I can connect it back to this ticket.

This would really help my rendering team try to troubleshoot this bug.

Thanks,
Connor, Avocode Support

**Comment by TiloNN** [comment]
Hey,
I sended you a mail, but you will find all material I've got in this ticket attached.

Thanks for hunting down that bug.

**Comment by connor-bean** [comment]
Hey @TiloNN @kkrebs -

Our rendering team was able to fix this bug for our 2.11 release which will be happening soon (hopefully no later than next week).

Please let us know of any other questions.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

You can download the update at https://avocode.com/news.html

Thanks for your patience on this.

Connor, Avocode Support

**Comment by TiloNN** [comment]
Was fixed for 2.11
With 2.11.1 it's broken again.
I'm not amused.
Can't even export a single layer any more.
Is it possible to install an old version?
Of course not, isn't it?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
