### ISSUE TITLE
Sketch import is blank

### ISSUE THREAD

**Issue by angeliquejw** [avocode/avocode#1034]
The designer has uploaded the Sketch file using the plugin, but when either of us open the Avocode app to view the project, we can see the names and outlines of the individual layers, but the actual work area is blank (screenshot:  [http://angeliqueweger.com/temp/avocode-bug.jpg](http://angeliqueweger.com/temp/avocode-bug.jpg)).

**Comment by buveur** [comment]
I have the same issue.

http://imgur.com/a/zVesF

I'm the designer, uploaded file around 10 minutes ago.

**Comment by buveur** [comment]
@angeliquejw i've solved it.

just tell your designer to close & re-open sketch app.

he must have updated the plugin to 3.8.0 version. and when you update plugins in sketch - you have to restart it.

**Comment by angeliquejw** [comment]
Man, I wanted the solution to be that simple @buveur. We both restarted Sketch and Avocode, reuploaded and synced the file, same blank work area.

**Comment by buveur** [comment]
@angeliquejw  make sure you see the correct version of the plugin in the top right corner: http://prntscr.com/c4g2p9

good luck finding your solution)

**Comment by angeliquejw** [comment]
Bravo, @buveur. Once he got the correct version of the plugin, things are working as expected. Thank you so much for your assistance!

**Comment by vojtatranta** [comment]
Thank you @angeliquejw.

This was a bug in our Sketch Plugin. If you update you the Avocode Sketch plugin and then upload designs again it should work.
