### ISSUE TITLE
Sketch Symbols appear as bitmaps

### ISSUE THREAD

**Issue by shiienurm** [avocode/avocode#1038]
![screen shot 2016-08-12 at 16 54 58](https://cloud.githubusercontent.com/assets/1461997/17624496/8745b352-60ad-11e6-860b-feb8508a03a8.png)

Plz fix this!

**Comment by shiienurm** [comment]
#https://github.com/avocode/avocode/issues/845

**Comment by connor-bean** [comment]
Hey, @shiienurm -

We definitely understand the need for a fix on this. We're currently looking into it and will hopefully have a fix soon.

I will close this out as we are tracking it in #845.

Thanks,
Connor, Avocode Support
