### ISSUE TITLE
GUI Components break when the program runs

### ISSUE THREAD

**Issue by vitaliikovalov** [avocode/avocode#1039]
![2016-08-12_1659](https://cloud.githubusercontent.com/assets/8245785/17624969/9042397e-60af-11e6-9228-699b5142507a.png)
![2016-08-12_1700](https://cloud.githubusercontent.com/assets/8245785/17624968/9040e4b6-60af-11e6-8d3b-7af32eba4c8f.png)

**Comment by vitaliikovalov** [comment]
http://screencast.com/t/7VzjnXJIUFU

**Comment by code-yo** [comment]
Have same issue, too.
https://monosnap.com/file/lxiPo1IaswMolRNEY7vdBn36pawxPb

**Comment by vojtatranta** [comment]
Hi,
thank you for this report. What OS do you have?

It is quite strange that we have not encountered such error yet.

**Comment by vitaliikovalov** [comment]
Win 10 x64 pro

**Comment by vojtatranta** [comment]
@vitaliikovalov thanks, do you have an AMD graphics card?

**Comment by vitaliikovalov** [comment]
AMD Radeon(TM) R7 Graphics

**Comment by vojtatranta** [comment]
Aha, we know about bugs in Electron on AMD cards.

I'll take a look.

**Comment by vojtatranta** [comment]
@vitaliikovalov alright, so no issues with AMDs graphic cards are reported in newer versions of Electron.

There is a thread that recommends AMD drivers update. We will also update Electron version, but I don't think that it will help and you cannot expect it in the next release (in th next 2 days).

**Comment by vitaliikovalov** [comment]
http://screencast.com/t/1ZEduiFWZ

**Comment by vojtatranta** [comment]
@vitaliikovalov oh, that's bad. I can just recommend you to google Electron issues whether there is someone with similar problem or create new issue and report your graphics card and driver.

**Comment by ZhiyanOlexandr** [comment]
Hi,
I have the same problem. I have installed the latest drivers, but issue is still there.

![image](https://cloud.githubusercontent.com/assets/8911089/17668161/b3cbe512-6310-11e6-868f-7ae45b8c470b.png)

**Comment by ZhiyanOlexandr** [comment]
![image](https://cloud.githubusercontent.com/assets/8911089/17668318/57ae8e78-6311-11e6-9401-50c7bf2130be.png)

![image](https://cloud.githubusercontent.com/assets/8911089/17668321/5bf95b7a-6311-11e6-9fb3-46fe23752a96.png)

**Comment by vitaliikovalov** [comment]
https://github.com/avocode/avocode/issues/1044

**Comment by vojtatranta** [comment]
@ZhiyanOlexandr Aháá, so it worked in previous versions, right?

Give me a sec, I will create a test build for you with disabled GPU rasterization, maybe that help!

**Comment by vojtatranta** [comment]
I gonna send you older version of Avocode: http://media.avocode.com/download/avocode-app/2.8.4/avocode-app-windows-x64-2.8.4.exe

There is still GPR rasterization off - can you please try whether it works with this version? Thanks.

**Comment by code-yo** [comment]
Unfortunately it's doesn't work.
Issue is still apear.
https://monosnap.com/file/WsXAm8wzGjFCrplb0vQXnAh4HwSI7V

**Comment by ZhiyanOlexandr** [comment]
Hi,
@vojtatranta, I have installed 2.8.4, but program still doesn't work correctly. When I resize window (or cursor over), sometimes it draws all information (only, if something happen with window).

**Comment by ZhiyanOlexandr** [comment]
http://screencast.com/t/LMjSCH86aVal

**Comment by vojtatranta** [comment]
@ZhiyanOlexandr ou, my bad. I sent you wrong version.

It should have been `2.8.1`: http://media.avocode.com/download/avocode-app/2.8.1/avocode-app-windows-x64-2.8.1.exe

Can you try this one?

Sorry again.

**Comment by ZhiyanOlexandr** [comment]
its work! Thanks.

**Comment by vojtatranta** [comment]
@ZhiyanOlexandr great!

So we turn off GPU rasterization in the next release `2.10.0`. It should land tomorrow. Sorry for the troubles.

**Comment by damienwebdev** [comment]
Having the same issue, I'm assuming I just wait for 2.10.0

**Comment by vojtatranta** [comment]
@damienwebdev you can use `2.8.4` until then: http://media.avocode.com/download/avocode-app/2.8.1/avocode-app-windows-x64-2.8.1.exe

`2.10.0` should land pretty soon (in a week or so, maybe sooner)
