### ISSUE TITLE
The design is processed OK, but it won't open in the Avocode app

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#104]
The issue might be caused by having multiple big rectangular shapes outside of the canvas like this: https://www.dropbox.com/s/dzf8o527t2ylw0v/Screenshot%202015-01-26%2019.25.16.png?dl=0

After removing these shapes, everything worked fine.

**Comment by kupcza** [comment]
If you need PSD, please tell me e-mail where to send it.
