### ISSUE TITLE
Can't upload design

### ISSUE THREAD

**Issue by sakralbar** [avocode/avocode#1041]
Everytime stop at 80%
No errors in terminal.
Avocode-linux-x64 2.9.1
![1471274204733](https://cloud.githubusercontent.com/assets/11180735/17668991/9303ab5e-6314-11e6-807d-77586d326b49.jpg)

**Comment by sakralbar** [comment]
![1471277311960](https://cloud.githubusercontent.com/assets/11180735/17670657/bbd2f6fa-631b-11e6-9cef-96cad714fee9.jpg)

**Comment by connor-bean** [comment]
Hey @sakralbar -

Would you be able to send us this design to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by sakralbar** [comment]
Send link to the design to team@avocode.com

**Comment by connor-bean** [comment]
Hey, @sakralbar -

Can you try resending this design? In the subject line could you include Ticket 1041?

Thanks,
Connor, Avocode Support

**Comment by sakralbar** [comment]
Hey, connor-bean.
Yes, I resend email with subject Ticket 1041.
Here is link to download [design](https://yadi.sk/i/XjWiQB3vuFnxb) too.

**Comment by connor-bean** [comment]
Hey @sakralbar -

Thanks I see the email now. I appreciate you resending this to us.

Connor, Avocode Support

**Comment by sakralbar** [comment]
Hello. I apologize for the long silence. All right now, thank you.
