### ISSUE TITLE
Avocode is braking after install

### ISSUE THREAD

**Issue by FranBarbadev** [avocode/avocode#1044]
Hi, I have Avocode installed on my laptop version 2.8.4. and it works great, but on my PC I installed version 2.9.1. and it's breaking all the time. 
At first it loads broken, then when i hover some things they appear, and then when I hover them again they break up again.
Screenshots in attachment.
Please can you resolve this or give me instructions what should i install? Maybe some visual C missing or something similar?
Thanks
![avocode braking](https://cloud.githubusercontent.com/assets/21042090/17671691/9fdabfda-6318-11e6-9c57-504607fea086.png)
![avocode braking 2](https://cloud.githubusercontent.com/assets/21042090/17671758/f03d779c-6318-11e6-8d4c-92f89510a10b.png)

**Comment by FranBarbadev** [comment]
And this is kind of urgent, so if you can't think of any solution fast, can you please send mi 2.8.4 install? Thanks

**Comment by vitaliikovalov** [comment]
https://github.com/avocode/avocode/issues/1039

**Comment by vojtatranta** [comment]
Here is link with Avocode installer `2.8.4` http://media.avocode.com/download/avocode-app/2.8.4/avocode-app-windows-x64-2.8.4.exe

GPU rasterization is off here. Can you please try whether it works with this version? Thanks.

**Comment by connor-bean** [comment]
Hey @FranBarbadev -

Here is link with Avocode installer 2.8.4 http://media.avocode.com/download/avocode-app/2.8.4/avocode-app-windows-x64-2.8.4.exe

GPU rasterization is off here. Can you please try whether it works with this version? We will be fixing the GPU rasterization in our 2.10.0 release
