### ISSUE TITLE
Font style

### ISSUE THREAD

**Issue by markst** [avocode/avocode#1045]
Font styles do not appear correctly

**Comment by markst** [comment]
#1042

**Comment by connor-bean** [comment]
Closing this out and we will track it in #1042

**Comment by connor-bean** [comment]
@markst - Can you send us screenshots?

What version of Avocode are you running? and what OS?

**Comment by markst** [comment]
@connor-bean version 2.9.1. This always been an issue with Avocode & not specific to a version. 
![image](https://cloud.githubusercontent.com/assets/274318/17776358/1b47a358-6554-11e6-8d59-d7e0f7b83004.png)

**Comment by markst** [comment]
Any update on this?

**Comment by jakubzitny** [comment]
Hey @markst, do you mean that there is missing `font-style` property or is there anything actually incorrect?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
