### ISSUE TITLE
Layer sizes vs. styles size

### ISSUE THREAD

**Issue by landsman** [avocode/avocode#1046]
![image](https://cloud.githubusercontent.com/assets/3184228/17679129/656051ae-633a-11e6-8333-8b21d7148fd0.png)

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
