### ISSUE TITLE
Blend modes in Sketch

### ISSUE THREAD

**Issue by plusmoi** [avocode/avocode#105]
Looks like the blend modes aren't working with Sketch in the Avocode app. Lets say I want a developer to integrate an image made of two overlapping visuals set with a multiply blending mode?

Thanks

**Comment by petrbrzek** [comment]
We are working on a 'slice' tool that will solve this issue. We're going to release it in two weeks.

**Comment by rychlis** [comment]
Avocode 1.1.0 with slice tool has been now released
