### ISSUE TITLE
Dropdown choices invisible in the settings screen

### ISSUE THREAD

**Issue by vrozkovec** [avocode/avocode#1053]
Hi, 
in my settings screen, I cannot see other choices in the dropdown menu.

![screenshot at 2016-08-18 18 38 46](https://cloud.githubusercontent.com/assets/135681/17782516/2567a980-6574-11e6-8c88-484fbb3c6242.png)

Linux Mint 17.3 Rosa, Mate edition

**Comment by jakubzitny** [comment]
Hi @vrozkovec, thanks for the report.

Is this happening even after you restart the app? We've been fixing this several times already but it keeps reappearing in various flavors of Linux 😄

**Comment by vrozkovec** [comment]
Yes, tried to re-download the app, but it is still there. Restarted the app and the computer to no avail.

**Comment by jakubzitny** [comment]
Thanks, we'll have another look into it and keep you updated. 😃

**Comment by jakubzitny** [comment]
Hi @vrozkovec, we've installed Mint 17.3 Mate and we're not able to reproduce this behavior, the dropdowns look as they should. Is there any chance you're having any custom theme applied? If not, would you be willing to send us your hardware specs? CPU, RAM, graphics card and driver used could help.

Thanks.

**Comment by jakubzitny** [comment]
This might be similar to #1057.

**Comment by jakubzitny** [comment]
Hi @vrozkovec, can you please update to latest version and check if this is still happening? You can download it from [manager.avocode.com/downloads](http://manager.avocode.com/downloads/).

**Comment by vrozkovec** [comment]
Hi @jakubzitny, my theme is Mint-X-Brown
For other info please see attached files. 
My system hasn't been reinstalled for around a year and I plan installing Linux Mint 18 soon, so this error may as well disappear.

[cpuinfo.txt](https://github.com/avocode/avocode/files/441373/cpuinfo.txt)
[lshw.txt](https://github.com/avocode/avocode/files/441376/lshw.txt)
[glxinfo.txt](https://github.com/avocode/avocode/files/441379/glxinfo.txt)
[lspci.txt](https://github.com/avocode/avocode/files/441382/lspci.txt)
[lspci_vga.txt](https://github.com/avocode/avocode/files/441380/lspci_vga.txt)
![screenshot at 2016-08-28 23 20 25](https://cloud.githubusercontent.com/assets/135681/18036851/0790fea2-6d76-11e6-99e3-e849fabe33a8.png)

**Comment by vrozkovec** [comment]
Changing theme does not help, changing to fglrx driver fixed the problem, but makes the system unusable due to strange artefacts appearing on multi monitor set-up.

**Comment by vrozkovec** [comment]
Fixed in the last version. Thanks.

**Comment by petrbrzek** [comment]
Awesome.
