### ISSUE TITLE
Layers Palette keeps opening on its own

### ISSUE THREAD

**Issue by tbirrell** [avocode/avocode#1054]
Every few minutes or so the layer palette will open and obscure a portion of my design. I then have to close it manually. When I'm doing this 100 times a day, the unnecessary micro interactions add up.

**Comment by connor-bean** [comment]
Hey @tbirrell -

We apologize for any frustration. Could you let us know what OS you're running and what version of Avocode?

Also - screenshots would help if possible.

Thanks,
Connor, Avocode Support

**Comment by tbirrell** [comment]
I'm on Ubuntu 16.04 with Avocode 2.9.1

The first screenshot is what it looks like with the palette open. When I close it (second ss), it does not render the bit of the design that was hidden off the right side. But this missing sections isn't a problem when I manually toggle the palette (third ss) as opposed to the bug toggling it.

![test_w_pal](https://cloud.githubusercontent.com/assets/17275888/17861147/8c32a42e-6855-11e6-9731-8df34d0941a8.png)
![test_after_pal](https://cloud.githubusercontent.com/assets/17275888/17861145/8c307d52-6855-11e6-8b6b-58041fbcda8f.png)
![test_wo_error](https://cloud.githubusercontent.com/assets/17275888/17861146/8c310196-6855-11e6-8fcc-e2c6278180f7.png)

**Comment by jakubzitny** [comment]
Thanks for the details @tbirrell. We know about this and we've been fixing it several times already. Unfortunately, there are still some cases where we have no idea why is it happening. In your case it might be another issue related to Linux and graphics drivers. We'll be releasing modified graphics config in next version - that might help with this. In the meantime, would you be willing to send us your cpu/ram and graphics card/drivers info here or to team@avocode.com? It might help us locate the problem better. 😃

**Comment by blcarson** [comment]
Happening on OS X 10.11.5 as well.

**Comment by jakubzitny** [comment]
Thanks @blcarson, good to know. This is actually a bug, we'll be working on a fix for one of the next releases.

**Comment by bolekkerous** [comment]
This should hopefully be fixed in the latest version of Avocode.

I'll close this issue - if somebody is still experiencing the issue even with the latest version, please comment here or open a new issue.
