### ISSUE TITLE
Opening a layout freezes on "Loading metadata..."

### ISSUE THREAD

**Issue by JayCarney** [avocode/avocode#1055]
I left the app open with "Loading metadata..." running for around 30min just to make sure it wasn't just a time thing.

This issue only seems to be happening on a specific project uploaded with the Sketch plugin.

One of the Avocode Helper processes seems to spike to 100% CPU usage and stays around 80% once "Loading metadata" starts (there seems to be a second Avocode Helper process sitting at 0% CPU usage, and a third sitting around 8%) 

I'm happy to send any information you need to have a look at the specific project to help debug

I've got the designer flattening all the vectors used as background images to see if that helps (there's a bunch of small paths used as on backgrounds that I figure might just be too much for the app to handle)

```
OSX Version: 10.11.13
Avocode App Version: 2.9.1
Sketch Version : 39.1 (31720)
Sync Plugin Version: 3.8.0
```
## Update

Flattening all the background images on sections and converting the large number of small vectors into a single raster image seems to be a successful workaround for the problem

**Comment by petrbrzek** [comment]
Thanks for reporting the issue. Glad you found the workaround. Would it be possible to send me the original source file to petr [at] avocode.com?

**Comment by vojtatranta** [comment]
@JayCarney I will close this issue due to inactivity, reopen if this trouble persists
