### ISSUE TITLE
Avocode crash

### ISSUE THREAD

**Issue by pusyak** [avocode/avocode#1056]
IMPORTANT: Please try to describe how did it happen.

Don't know how it happened ;c
Just try upload together 11psd files.

-----
App v.2.8.2
Source UID: 85144
```
Error: ENOENT: no such file or directory, open '/home/andrewa/.avocode/userdata/85144/documents/b8827231dc3647dda3a5d196e42126bb/images/resources.tar.gz'
    at Error (native)
```

**Comment by jakubzitny** [comment]
Hi @pusyak, thanks for letting us know. We've noticed you're using old version of Avocode. Please download the newest one — `2.9.1` from [manager.avocode.com/downloads](http://manager.avocode.com/downloads/) and let us know if you have this or any other problems with it.

I'll close this issue for now.
