### ISSUE TITLE
Many graphical artifacts, Windows 10 + Radeon

### ISSUE THREAD

**Issue by lobzenko** [avocode/avocode#1057]
Hello, after drivers update Radeon R9 200 Series shows avocode problems. Programm interface looks with spaces and lags, example

![image](https://cloud.githubusercontent.com/assets/2557329/17833358/1e286fe2-6745-11e6-946c-d5a959010041.png)
project manager

![image](https://cloud.githubusercontent.com/assets/2557329/17833317/3a5938d2-6744-11e6-9de3-34675270b590.png)
no left and right menus when obejct was selected, if mouse cursor hover  on right column its repainting.

Many screen blinks when scrolling.

![image](https://cloud.githubusercontent.com/assets/2557329/17833333/8d7a981c-6744-11e6-90b4-ad4075ab1038.png)
preferences menu

I tried downgrade the video drivers and run Avocode like Win 7, Win 8 and previos versions. No results.

Any solutions?

**Comment by lobzenko** [comment]
Downgrate to 15.300.1025.1001 29.11.2015 drivers
lags is over, export and other in test

**Comment by connor-bean** [comment]
Hey @lobzenko -

Can you try reverting to 2.8.1 instead?

You can download it [here](http://media.avocode.com/download/avocode-app/2.8.1/avocode-app-windows-x64-2.8.1.exe). 

Please let me know the result once you've reverted to the previous version.

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Hey @lobzenko, thanks for the info you provided. We're having two similar problems, possibly related to graphic cards (#1053). We'll be releasing improved graphics configuration in `10.11` and we'll update you here.

Are you able to run Avocode correctly right now? Don't hesitate to ping us if you have any more issues or problems. 😉

**Comment by evgenybinboro** [comment]
Hello, any updates about it.
Our company can't work because of this issue

**Comment by jakubzitny** [comment]
Hi @evgenybinboro, are you experiencing the same as @lobzenko? Do you have Windows and similar graphics card? We'll be releasing new version of Avocode today or tomorrow and I hope it will fix the problems you guys have.

If you have different issues with Avocode can you please give us more info? 

I'll update you here with a link to a release when it's ready.

**Comment by FranBarbadev** [comment]
Hi,

I have same problem, I downgraded to 2.8.4. and problem still persist,

my configuration: 

Operating System
Windows 10 Professional ‎(X64)‎

Processor
AMD FX-8300 clocked at 3.30 GHz

Motherboard
ASUSTeK Computer INC. M5A78L-M LX3 Rev X.0x

Memory
16 GB total memory type DDR3 to 937.46 MHz

Graphics card
AMD Radeon (TM) R7 360 Series
DirectX version installed: 11.0
Core clock: 300 MHz
Memory clock: 1.50 GHz

Multimedia cards
Advanced Micro Devices, Inc. [AMD/ATI] SBx00 Azalia (Intel HDA)
Advanced Micro Devices, Inc. [AMD/ATI] Tobago HDMI Audio [Radeon R7 360 / R9 360 OEM]

Screen(s)
Manufacturer: AOC International (USA) Ltd.
Maximum resolution: 1920 x 1080
Screen size: 23.1" (51 cm x 29 cm)

Installed version 2.8.1. and i got this error:

App v.2.8.1
Source UID: 81920
```
TypeError: Cannot read property 'settings' of undefined
    at t.getVariables (file:///C:/Users/getbestweb/AppData/Local/avocode/app-2.8.1/resources/app.asar/dist/avocode.min.js:2:14038)
    at t.processLayers (file:///C:/Users/getbestweb/AppData/Local/avocode/app-2.8.1/resources/app.asar/dist/avocode.min.js:2:14774)
    at t._processSelectedLayers (file:///C:/Users/getbestweb/AppData/Local/avocode/app-2.8.1/resources/app.asar/dist/avocode.min.js:31:20165)
    at t._handleSelectionChange (file:///C:/Users/getbestweb/AppData/Local/avocode/app-2.8.1/resources/app.asar/dist/avocode.min.js:31:19497)
    at t.<anonymous> (file:///C:/Users/getbestweb/AppData/Local/avocode/app-2.8.1/resources/app.asar/dist/avocode.min.js:31:16054)
    at emitNone (events.js:91:20)
    at t.emit (events.js:185:7)
    at t.emitChange (file:///C:/Users/getbestweb/AppData/Local/avocode/app-2.8.1/resources/app.asar/dist/avocode.min.js:16:1275)
    at t._handleDerivationChange (file:///C:/Users/getbestweb/AppData/L

Look, I paid for this and it doesn't work, I don't want my money back because it works great on my laptop dell inspiron 5737, but now I have to drive one hour to my office and back to get my laptop to work on my project, so please make it work.

You really have great app here, it is only one I know off that can open sketch files on windows, and extractor is way better then project parfeit was.

If we forget this issue, your product is great :)

**Comment by FranBarbadev** [comment]
Ok, version 2.10. seems to work great. Thank you :)

**Comment by AlexanderPlaksenko** [comment]
Just disable GPU  --disable-gpu
Many program on Electron has this bug.

**Comment by jakubzitny** [comment]
Hey guys, we've released new version of Avocode on Friday. It seems to be fixing the problem with graphics for some people. Yes @AlexanderPlaksenko, the problem was with Electron's graphics acceleration.

@evgenybinboro, @lobzenko can you please update to `2.10` and confirm that everything works correctly? I am going to close this issue for now. Feel free to open a new one if you have any more problems. 😉
