### ISSUE TITLE
I kinda dont like the way my license in shown in avocode manager.

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#106]
https://www.dropbox.com/s/zkekx1926vm5dc8/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-01-29%2005.30.57.png?dl=0
get rid of that.

**Comment by rychlis** [comment]
Thanks for the report, that's not supposed to be there. We are going to fix this asap

**Comment by rychlis** [comment]
It was only happening if you deleted a trialing organization. We've just deployed a new version of manager, so it should be fixed now
