### ISSUE TITLE
Black screen after downloading metadata

### ISSUE THREAD

**Issue by KarthikaBaskar** [avocode/avocode#1063]
I use Avocode 2.9.1.
I am able to see different project folder, inside able to see different screens with all the elements. When I go in the details I see a black screen.
Please can you help understand why this happens.

**Comment by connor-bean** [comment]
Hey @KarthikaBaskar -

Can you send us a screenshot of what you see?

Thanks,
Connor, Avocode Support

**Comment by petrbrzek** [comment]
@KarthikaBaskar Try to update the app to 2.10.0 version. We disabled the GPU rasterization that caused problems to some of our users.

**Comment by KarthikaBaskar** [comment]
It worked  @petrbrzek thanks.
