### ISSUE TITLE
Processing Failed

### ISSUE THREAD

**Issue by jcjvm** [avocode/avocode#1065]
After leaving 14 comments on a design I can no longer open the file because of an error. I would like to know if your commenting system is stable? If it's not then I will find another way to communicate with my team, but I don't want to keep trying and trying only to keep running into errors.

Thank you.

- Josh

![screen shot 2016-08-24 at 3 30 07 pm](https://cloud.githubusercontent.com/assets/6078371/17932321/bb44a800-6a0f-11e6-9508-3cd70d8766df.png)

**Comment by connor-bean** [comment]
Hey @jcjvm -

Could you send us the problematic design to team@avocode.com? Is this happening on all of your designs or just a specific one?

What version of Avocode are you running? And what OS?

Thanks,
Connor, Avocode Support

**Comment by jcjvm** [comment]
Hi Connor -

Thanks for the quick response. The problem seems to have solved itself. But
for what it's worth I'll paint the whole picture for you. I'm using Avocode
2.9.1. I'm running Mac OS 10.11.6. I only entered comments on 1 design and
that is the design that had the error. The other files were fine.

This is how I solved it. I simply went back to Sketch and resynced the
artboard. The comments stayed intact throughout the processing error and
resyncing.

Thanks again for reaching out to me.

- Josh

**Comment by connor-bean** [comment]
Hey, @jcjvm -

Thanks for the recreation steps. I will keep this in our documentation for when we have other users report the same problem.

We definitely apologize for any frustration this caused but I'm glad it's working now.

Please let us know of any other questions.

Thanks,
Connor, Avocode Support
