### ISSUE TITLE
Sort by always switches back to Last modified

### ISSUE THREAD

**Issue by n0rule5** [avocode/avocode#1066]
After I change **Sort by** to **Name**, it will switch back to **Last modified** all by itself when I go in and out of projects, but not all the time.

If I switch to **Name**, quit, and open again, it will default back to **Last modified**.

I have a lot of projects and this switheroo makes it super annoying to find projects because the ordering is always different and not what I expected. Surely it's supposed to stay on the one I picked?

Avocode 2.9.1 on OSX 10.11.6

**Comment by connor-bean** [comment]
Hey @n0rule5 -

Is it possible that you are seeing different views for "projects view" and for "project detail view?" 

If you could possibly send us screenshots, that may help us here.

Thanks,
Connor, Avocode Support

**Comment by n0rule5** [comment]
I'm referring to the **All Projects** view:
![image](https://cloud.githubusercontent.com/assets/1464003/18010948/dfad2c40-6b80-11e6-833e-8d896f604b60.png)

This is the one that keeps switching back to **Last modified** by itself.

When I go into a specific project, however, I have the **Sort by** set to **Category** and it stays, which is what I expect.

**Comment by petrbrzek** [comment]
@n0rule5 I'm not able to reproduce it. Is it only happening when "syncing" text is visible?

**Comment by n0rule5** [comment]
I just updated to 2.10.0 and it's still happening. I just did some more testing:
- switch to **Sort by name**, close the app, open again: **Sort by** will switch back to **Last modified**.
- switch to **Sort by name**, go into a project, open a design, close the design, go back to **All projects**: **Sort by** will switch back to **Last modified**.

Let me know if you can reproduce it following these steps.

**Comment by kubiqsk** [comment]
Same problem HERE... it's really annoying, because when I'm done with some design then I rename it (add XX at the beginning so it should be on the end) but it always sorts designs different as alphabetically - my preference

**Comment by n0rule5** [comment]
Actually, I've since discovered that it will also do this while it is syncing... le sigh.

**Comment by vojtatranta** [comment]
GL3022

**Comment by vojtatranta** [comment]
I think this is not happening anymore, right? Please reopen, if I'm wrong
