### ISSUE TITLE
Code panel instant copy of multiple lines

### ISSUE THREAD

**Issue by mehdiraized** [avocode/avocode#1068]
please fix

**Comment by orhar** [comment]
same here - please fix

**Comment by petrbrzek** [comment]
@mehdiraized @orhar Thanks for reporting the issue but I don't understand what you mean by "click attr in css". Can you elaborate a bit more on this? Screenshots are welcome. :camera:

**Comment by orhar** [comment]
When you click on an element and then click on the right under "CODE" (where the CSS is displayed), 
The click on the text does not auto-copies the rules as it used to. Instead the text is just selected

**Comment by petrbrzek** [comment]
@orhar Thanks for clarifying. Some of our users wanted to select code by mouse without copying whole lines, so we changed it. But you can still copy a line by clicking on a line number.

![code](https://cloud.githubusercontent.com/assets/879564/18026730/fc4108d8-6c50-11e6-82d7-a9442c2f2728.gif)

**Comment by orhar** [comment]
Thank you for the quick response.
If I want to copy multiple lines at once (as I used to) - it is not possible?
I can copy only one line at a time.

**Comment by mehdiraized** [comment]
@petrbrzek 
tnx
I can't copy multiple line

**Comment by petrbrzek** [comment]
Not possible not. Is it something you would like to have? We can put it back.

**Comment by mehdiraized** [comment]
@petrbrzek yes i like

**Comment by orhar** [comment]
of course!
99% of the time I copy multiple lines.
In addition - if it was possible to hide/define a specific attribute not to show it would be great.
e.g when I copy text I don't like to copy the font-family (I erase it manually every time)
[see pic]
![image](https://cloud.githubusercontent.com/assets/7655339/18026856/f00268f4-6c5b-11e6-9754-6d5966be67f9.png)

**Comment by vojtatranta** [comment]
@orhar well, now you can just select lines you want to copy and ctrl+c to copy them.

**Comment by orhar** [comment]
@vojtatranta 
from a productivity standpoint the auto-copy is great.
if you could enable this behavior in the settings I believe it would be beneficial to a large amount of users.

Thank you.

**Comment by petrbrzek** [comment]
@orhar We're working on new templates where it would be possible to re-order or hide/show specific property.

**Comment by edDimensi** [comment]
Give plz link on old version, i want too multi select lines.

**Comment by fernandodamaso** [comment]
please, where can i download the previous version of avocode, not being able to select multiple lines , this was one of the reasons i use avocode, the ability to quickly select only the lines that i wanted from the code. With speed and precision, not, one line by one line, this slow down the coding proccess a lot

**Comment by fernandodamaso** [comment]
Jesus, not being able to select multiple lines is really breaking my workflow hahah

**Comment by jakubzitny** [comment]
@fernandodamaso @edDimensi You guys know that you can select multiple lines similarly as you'd do it in regular textarea, right? You dont have to do it line by line. Just drag your mouse from top left corner of the "Code" panel to bottom right and press `cmd+c` or `ctrl+c` and there you go.

![multilinecopy](https://cloud.githubusercontent.com/assets/3315662/18054200/28162160-6e03-11e6-935f-fae848977d3b.gif)

**Comment by orhar** [comment]
@jakubzitny 
Yes.  I've learned from a Youtube video about CTRL+C feature. looks cool.
And now seriously - the CTRL+C stage is redundant and is a waste of time. The only reason for me to highlight the text is to copy it...

**Comment by fernandodamaso** [comment]
I do understand that, and that does not help.

If i want the line 1, 3, 5, i would have to select the line 1 to 5, and then manually delete the 2 and 4, this is a break in the workflow, the previous versions, were much more agile, since i could manually select each line of my interest. This is why avocode is the best coding app in my opinion, cause i din't need to keep deleting lines and changing the css code.
With the previous versions, i could have a tailor made css code specially designed to what i needed, instead of a bunch of css information regarding an element, and then remove manually the information i dont need.

**Comment by fernandodamaso** [comment]
please. where can i download a previous version?

**Comment by jakubzitny** [comment]
Allright guys, we understand, we'll keep this in mind for next releases 😉 

Links are coming..

**Comment by connor-bean** [comment]
You can download 2.9.1 here:

[Mac](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.9.1/avocode-app-mac-2.9.1.zip)

[Windows 64](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.9.1/avocode-app-windows-x64-zip-2.9.1.zip)

[Linux 64](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.9.1/avocode-app-linux-2.9.1.zip)

[Linux 32](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.9.1/avocode-app-linux-ia32-2.9.1.zip)

**Comment by fernandodamaso** [comment]
Thanks <3 this helps a lot, luv u guys hehehehehe

**Comment by davidfregoli** [comment]
Just updated to the latest Mac stable and this still isn't working right:
I understand that sometimes you may wanna highlight in the middle of a property to copy just a bit and that's fine, but if I highlight from middle and then drag on to multiple lines the full lines should be copied over, nobody will ever want to copy something like: `#172c4d;
font-family: Signika;
font-size: 2.625rem;
font-weight:`

**Comment by oxananana** [comment]
oh, guys, when you fixed this issue? it's very brakes work. i use old version now.  pleeeeeeeeeeeeeeease, return copy of multiple lines

**Comment by vojtatranta** [comment]
Huh, did not noticed that this is still an issue.

So now you can just do following:
1. got o app Preferences, to the Code section (`cmd/ctrl + ,`)
![snimek obrazovky 2017-05-15 v 12 22 02](https://cloud.githubusercontent.com/assets/4154045/26053464/3184d6ec-3969-11e7-9cd8-4706492c8d57.png)
2. You can a) disable css properties you don't want to appear in code panel or b) you can move with by holding handle on the right and moving it down - this is how you change order of css properties in the code panel
3. No you can open your design and click and hold on the line number and drag your mouse over other line numbers (still holding left mouse button) and lines will be copied accordingly when you release left mouse button
4. Enjoy!

This should solve all the problems you had. You can move css properties you dont use to the bottom and just copy lines you use by eg. moving them closer together.
