### ISSUE TITLE
svg export without viewBox

### ISSUE THREAD

**Issue by ROBsoer** [avocode/avocode#1074]
svg icons have been exported without viewBox attribute

**Comment by connor-bean** [comment]
Hello @ROBsoer -

We do not currently support this feature. Could you please tell us the use case for having an SVG icon to be exported with the viewBox attribute?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
We will add this to our internal tracking system and it will hopefully be ready in our next release of our rendering library.

Thanks,
Connor, Avocode Support

**Comment by name-k** [comment]
+1, suffering from adding it manually every time

**Comment by name-k** [comment]
btw you do not need to wait for any changes of rendering library to fix it, because you already export `width` and `height` and position will most likely be equal to `0 0` all the time

**Comment by jankuca** [comment]
@name-k Yes but our rendering library is what generates the SVG code.

**Comment by name-k** [comment]
What I mean is you can do a quick fix (of course if you want to), while waiting for a new release of rendering library could be much longer.

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

You can download the update at https://avocode.com/news.html

Thanks for your patience on this.

Connor, Avocode Support

**Comment by ROBsoer** [comment]
Great! Thank you so much!
