### ISSUE TITLE
Importing files from sketch results in empty elements

### ISSUE THREAD

**Issue by thisiscraig** [avocode/avocode#1075]
We are importing some sketch files, and Avocode is recognising all the elements, but they are empty. So I'm just seeing a blank preview for every one I click on.

**Comment by connor-bean** [comment]
Hey @thisiscraig -

Could you post some screenshots of what you're seeing?

Thanks,
Connor, Avocode Support

**Comment by thisiscraig** [comment]
![df-screenshot](https://cloud.githubusercontent.com/assets/20278118/18092131/08830082-6ec3-11e6-927e-eda9bf7bbb39.jpg)

**Comment by connor-bean** [comment]
Hey @thisiscraig -

Are you using the latest Sketch plugin (3.8 version)?

If so, please uninstall the plugin, quit Sketch and install the plugin again. After you sync the design again with the new version (it's needed to resync it to see the difference), it should work just fine.

Let me know whether it works!
Best regards,
Connor, Avocode Team

**Comment by thisiscraig** [comment]
It was down to an out dated plugin.
Thanks for that

**Comment by jakubzitny** [comment]
Glad to hear that @thisiscraig. Let us know if you have any other problems or questions regarding Avocode.
