### ISSUE TITLE
Changed behavior of copying lines with the mouse

### ISSUE THREAD

**Issue by vrozkovec** [avocode/avocode#1078]
In previous version, it was possible to click on a line or two and lines were automatically copied to the clipboard. In current version - 2.10.0@Linux 64bit - you have to either copy all lines, or use a keyboard shortcut.

**Comment by jakubzitny** [comment]
Hi @vrozkovec, thanks for the issue. We're already discussing this in #1068, so I'll close this one.

Since you're not the only one who doesn't like this, we'll think about bringing the old functionality in one of the next releases.

Stay tuned 😉
