### ISSUE TITLE
Different sizes in style inspector and layer info window

### ISSUE THREAD

**Issue by vrozkovec** [avocode/avocode#1079]
See attached screenshot (250px is correct):
![sizes](https://cloud.githubusercontent.com/assets/135681/18104357/17a7f97c-6efb-11e6-899a-62575ea9f4a3.png)

**Comment by jakubzitny** [comment]
Thanks again man. We're already fixing this bug, however, we're still not sure about all the cases it is happening. Could you send us the original PSD to team@avocode.com if possible? Please mention number #1079 in the email too.

Thanks a lot for using Avocode and for all issues you're reporting 😉

**Comment by vrozkovec** [comment]
Sent!

**Comment by jakubzitny** [comment]
Thanks, we'll let you know when we have more info 😉

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

You can download the update at https://avocode.com/news.html

Thanks for your patience on this.

Connor, Avocode Support
