### ISSUE TITLE
Photoshop Plugin keeps crashing

### ISSUE THREAD

**Issue by emloeb90** [avocode/avocode#108]
![screen shot 2015-01-29 at 4 13 40 pm](https://cloud.githubusercontent.com/assets/10763893/5966399/f1c496c6-a7d1-11e4-8537-a8b48c51fc33.png)
I keep getting the attached error every time I try to sync a file to avocode from my photoshop plugin. It worked before I updated the plugin to 1.0.1.

Thanks!

**Comment by marekhrabe** [comment]
Hi, can you please send me logs so I can see the exact error? 

You can find the log location here: https://github.com/adobe-photoshop/generator-core/wiki/Generator-Log-Locations. Please sent the one that ends with `_latest`
