### ISSUE TITLE
the images failed  in another computer

### ISSUE THREAD

**Issue by guestOfGithub** [avocode/avocode#1080]
The images  can  be   update to the server but  i open  avocode  in anohter computer ,the images is
error
![image](https://cloud.githubusercontent.com/assets/7136250/18113276/022cb9be-6f61-11e6-94e1-97763c446967.png)

**Comment by bolekkerous** [comment]
This shouldn't be happening in the latest versions of Avocode app.

You can always download the latest version here:
https://manager.avocode.com/downloads/

If you still experience this problem or any other problem, please create a new issue or comment here. We would need some more info to properly investigate the problem.
