### ISSUE TITLE
Project Manager does not remember scroll position

### ISSUE THREAD

**Issue by jpeldes** [avocode/avocode#1082]
Just updated to Release 2.10.0

When I scroll down in Project Manager to open several mocks, I have to scroll back down again after opening a mock.

**Comment by connor-bean** [comment]
Hey @jpeldes -

This feature was removed in 2.10 to improve performance. If we get more people who want this feature back, we will look into adding it again.

Please let me know of any other questions.

Thanks,
Connor, Avocode Support

**Comment by bolekkerous** [comment]
Hey - 
I belive this should work for a while already.

If you click on the breadcrumbs from the design, it should remember the previous position.

However if you want to open multiple designs in new tabs, please use the CMD/CTRL + doubleclick to do that.

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
