### ISSUE TITLE
problem with fonts

### ISSUE THREAD

**Issue by shectermen** [avocode/avocode#1083]
Good day, with the latest update in some places began to appear bad fonts in Russian, with each new load applications see a new font

**Comment by bolekkerous** [comment]
Hello!
Could you please send us a screenshot of the issue with the problematic design to team@avocode.com, so we can investigate the issue properly?

Thanks,
Bolek, Avocode Team

**Comment by shectermen** [comment]
I'm sorry for not having replied was on vacation, just checked, with the latest update and upgrade the OS avaсode problem persists, thank you very much))

>Пятница,  9 сентября 2016, 12:08 +03:00 от Bolek <notifications@github.com>:
>
>Hello!
>Could you please send us a screenshot of the issue with the problematic design to  team@avocode.com , so we can investigate the issue properly?
>Thanks,
>Bolek, Avocode Team
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Сергей Алпеев
salpeev@mail.ru
