### ISSUE TITLE
Cannot import files from Sketch (no document open)

### ISSUE THREAD

**Issue by xenongattz** [avocode/avocode#1084]
I can't import my Sketch-design:
https://yadi.sk/i/4pV_fqfUugdc7
This is what Sketch plugin tells me.

Sketch version is 39.1

**Comment by connor-bean** [comment]
Hey, @xenongattz -

Could you send us a screenshot of the error you're receiving? The link you sent doesn't work.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @xenongattz -

Could you send us a screenshot of the error you're receiving? The link you sent doesn't work.

Thanks,
Connor, Avocode Support

**Comment by xenongattz** [comment]
Here the screenshot: https://yadi.sk/i/Nl1bDZBUvCsC8

Thanks for answer!

**Comment by xenongattz** [comment]
Problem gone when updated to Avocode Sketch Plugin v3.9
