### ISSUE TITLE
font-size avocode:6px, photoshop: 50px

### ISSUE THREAD

**Issue by filestealer** [avocode/avocode#1087]
Hello! Have problem with font-size and line-height.
In avocode:
font-family: 'ubuntu';
font-size: 6px;
font-weight: 400;
line-height: 7px;

in Photoshop 
font-size 50px;
line-height: 60px

will send file to team@avocode.com.

**Comment by connor-bean** [comment]
Hey @filestealer -

We received your file. Thanks for sending it over.

Connor, Avocode Support

**Comment by bolekkerous** [comment]
This should be already fixed now for quite some time.

Please let us know if you encounter any problem!
