### ISSUE TITLE
Add ability to approve popup message by pressing enter

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#109]
https://www.dropbox.com/s/h6n3u8ratsa0fbx/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-01-29%2023.23.24.png?dl=0

**Comment by petrbrzek** [comment]
It's quite dangerous in this case. I don't know.

**Comment by petrbrzek** [comment]
We've discussed in our team and think it's not a good idea. I'm closing this issue.
