### ISSUE TITLE
The app doesn't display elements on mockup

### ISSUE THREAD

**Issue by lexod** [avocode/avocode#1093]
GIVEN: I'm a user
AND: I have a few mockups 
AND: Previews are displayed correctly
WHEN: I open a mockup
THEN: Mockup with elements and details are displayed.

ACTUALY: Mockup is opened
AND: Elements are invisible 

Issue was reproduced on Windows10, Ubuntu16 and OS X EI Capitan
![image](https://cloud.githubusercontent.com/assets/5664192/18367695/68b55cce-75ea-11e6-9a04-607904e41d2e.png)

**Comment by connor-bean** [comment]
Hey, @lexod -

How are you importing these designs into Avocode? Are you using the Sketch plugin?

Thanks,
Connor, Avocode Support

**Comment by lexod** [comment]
Thank you guys, reinstalled sketch plug in and it works correctly.
