### ISSUE TITLE
exporting

### ISSUE THREAD

**Issue by Camik10** [avocode/avocode#1097]
As of the latest release (2.10.1) when exporting (PNG,SVG & JPG) the graphic is only exporting in an approx. square (1x1) proportion regardless of what proportion the graphic or image is in the file.
So we're trying to export a 4x3 proportioned image and it's exporting as a 1x1 square with extra white space on the bottom.

**Comment by rodnem** [comment]
When exporting (in my case png) the object is not in the viewbox.
There is like a translational movement
![dragon](https://cloud.githubusercontent.com/assets/6350513/18514081/658cb3ee-7a90-11e6-8bbd-63156d12b444.png)

**Comment by connor-bean** [comment]
Hey @Camik10 and @rodnem -

Could you both send us your problematic designs to team@avocode.com? This will really help my rendering team troubleshoot what's going on here.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

Thanks for your patience on this.

Connor, Avocode Support
