### ISSUE TITLE
v2.10.1 Is there any way to hide top bar?

### ISSUE THREAD

**Issue by ciases** [avocode/avocode#1099]
This new top bar is very large and useless imho. How can I disable/hide/remove it? Thanks.
[top bar image](http://i.imgur.com/e4c8Jj1.png)

**Comment by petrbrzek** [comment]
@ciases Yeah, I think we can add an option to hide the tool bar.

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

You can download the update at https://avocode.com/news.html

Thanks for your patience on this.

Connor, Avocode Support
