### ISSUE TITLE
Doesn't show line-height and letter spacing font properties in css

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#11]
line-height and letter spacing would be good.
also, would be great to see cmd+c to copy text, when layer is selected

**Comment by marekhrabe** [comment]
This is on our todo list - we want line-height, too. Stay tuned, we will let you know when it's ready

**Comment by rychlis** [comment]
line-height is now implemented in Avocode. I've created a new idea in user voice for letter spacing: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7024976-show-letter-spacing-in-photoshop-documents

**Comment by tyler-barnes** [comment]
@rychlis any updates on this? It's been two years but this still doesn't seem to be part of avocode.
