### ISSUE TITLE
Avocode does not take border of an smart object in count when measuring

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#110]
There are small issues I have noticed with the accuracy of the distance between objects. If a smart shape has a border, Avocode is unable to take that border into account.

Screenshot: https://upx.cz/5m0t1bglyzd9fnh8syt1wgljnkke9ql6nen5wgbj?PhotoshopSpaceSample.jpg
Screenshot: https://upx.cz/yyghzrrcbewi61f6xnvkiaawqxcschabtfx58aea?AvocodeSpaceSample.jpg

**Comment by marekhrabe** [comment]
There are usecases for measuring with layer styles (including border/stroke). We might make that configurable someday. I create a feature request for that, you can vote here: http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/10335606-measure-tool-should-work-with-and-without-layer-st
