### ISSUE TITLE
v2.10.1 Cannot copy several lines from CODE section

### ISSUE THREAD

**Issue by ciases** [avocode/avocode#1104]
Hello there!
I've notice that I can't copy several lines of code from 'CODE' section in v.2.10.1.
[code section image](http://i.imgur.com/RcIBjim.png)
There are only two options: copy one line or copy all. Is there any way to copy 2-3 lines of code?
Thanks.

**Comment by connor-bean** [comment]
Hey @ciases -

We are looking into fixing this in a future release as many customers have wanted this feature back (as seen in #1068).

I'm going to close this out as we are tracking it in 1068.

Thanks,
Connor, Avocode Support
