### ISSUE TITLE
Plugin Consistently Crashes Sketch

### ISSUE THREAD

**Issue by Chrisedmo** [avocode/avocode#111]
Hi guys I was really excited to see sketch support. However overtime i have used the plugin, I get the syncing part and then it crashes my app every time.

I even tried just saving 2 artboards to a new file to see if that helped, and it still crashed.

:-(

**Comment by tomashanacek** [comment]
Hi, thank you for reporting the issue. Could you share us the problematic design to team[at]avocode.com?

**Comment by tomashanacek** [comment]
Hi, problem is fixed in new version.
https://manager.avocode.com/downloads/

**Comment by MatthijsZw** [comment]
2.0.2 plugin still gives me issues syncing!
