### ISSUE TITLE
Folder navigation very slow

### ISSUE THREAD

**Issue by giulianok** [avocode/avocode#1111]
The navigation is very very slow in the latest version. When I'm navigating through folders it takes a lot to reflect the changes, it just freeze. Same problem when I open the preferences for example.

I didn't have this problem before and my computer has power (macbook pro 15 i7 16gb ram and SSD)

**Comment by connor-bean** [comment]
Hey @giulianok -

Could you shoot us an email to team@avocode.com with the email address you use for Avocode?

Thanks,
Connor, Avocode Support

**Comment by pierre521** [comment]
I've the same problem.

**Comment by vojtatranta** [comment]
@pierre521 but in newer version is it fast again, right? If not please comment, I'll reopen it.
