### ISSUE TITLE
Provide ability to hide the toolbar

### ISSUE THREAD

**Issue by Mo-** [avocode/avocode#1112]
Workspace size from version to version is getting smaller.
Please, give the option to remove from top of the screen tools, that are accessible through keyboard shortcuts (for laptops vertical space is critical)
you made a thick breadcrumbs, add "Share" button( which is necessary (?) of 0.1% for all time).
on the left there is a ton of space for tools icons

Just on the right side also became huge It is not possible to change the size of the elements and you have all the time to turn up - down

I am sorry for my English, I hope I was able to convey my meaning.
Thanks!

**Comment by petrbrzek** [comment]
Thanks for your opinion. We'll add keyboard shortcut for this case in the next release.

**Comment by petrbrzek** [comment]
Dup of #1099
