### ISSUE TITLE
Feature request: Option to hide synced symbols

### ISSUE THREAD

**Issue by n0rule5** [avocode/avocode#1113]
First of all, thanks for implementing a much-needed feature to open symbols in a design. It would've been nicer if the objects were placed in place for easier measurements in context, but regardless it's a good step forward. Here's hoping it will be further enhanced in the future. ;)

However, my projects are now littered with dozens (pretty soon hundreds) of symbols. This makes it really hard to browse for a design that I actually want to view and open. Sorting by category helps, but it's still a huge pile of stuff to scroll through.

Can we get a simple checkbox next to the **Sort by** dropdown to filter out/hide synced symbols? Or better yet, a dropdown for **View** to select **Show all**, **Designs only**, **Symbols only**?

**Comment by jakubzitny** [comment]
Hi there, there is a new UI for Sketch files in latest Avocode `2.15.0`. Symbols are displayed in a separate page now, so the mess with dozens of symbols should be resolved. The other part, where you can inspect the symbols within the design is on it's way and should land in a release in few weeks.

You can download the latest version from [avocode.com/download](https://avocode.com/downlad) or use auto-update to install it. Please give it a try and let us know if you have any more issues.
