### ISSUE TITLE
Masked images of a Sketch files are evidently not being exported properly 😠

### ISSUE THREAD

**Issue by miguelnavarro89** [avocode/avocode#1114]
Again, it comes alive an old issue.
I actually feel annoyed with this type of bugs which are supposed to be a basic feature.
<img width="930" alt="pasted_image_9_16_16__11_39_am" src="https://cloud.githubusercontent.com/assets/6646268/18593942/4a9ac958-7c03-11e6-888f-bf9308490061.png">
[Babywise-2.sketch.zip](https://github.com/avocode/avocode/files/477312/Babywise-2.sketch.zip)

**Comment by connor-bean** [comment]
Hey @miguelnavarro89 -

We are tracking this in #1018 so I will close this one here. Could you send us the design file to team@avocode.com?

Thanks,
Connor, Avocode Support
