### ISSUE TITLE
Avocode is not recognising gradient colors in a text (of a sketch file)

### ISSUE THREAD

**Issue by miguelnavarro89** [avocode/avocode#1115]
Sketch Version 39.1 (31720)
Mac OSX El capitan 10.11.6 (15G31)
Avocode Release 2.10.1 – Sep. 5, 2016

![pasted_image_9_16_16__2_27_pm](https://cloud.githubusercontent.com/assets/6646268/18598738/0f5dc3f6-7c1a-11e6-81d6-9ab8674b1381.png)

**Comment by connor-bean** [comment]
Hey, @miguelnavarro89 -

Would you be able to send us the original design file to team@avocode.com so my rendering team could use it to troubleshoot?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @miguelnavarro89 -

The product team took a more in-depth look at this and they determined this is an enhancement. Please add this feature request to our UserVoice forum [here](https://avocode.uservoice.com/forums/277080-feature-voting).

Thanks,
Connor, Avocode Support
