### ISSUE TITLE
App freezes when trying to start up

### ISSUE THREAD

**Issue by BotanikRock** [avocode/avocode#1116]
http://joxi.ru/Y2LYgJXsn6W4oA

I launch it, and app 'freeze' in this state.

OS: Windows 10 64-bit

ps: sry, for broken english :)

**Comment by petrbrzek** [comment]
That's weird. Could you please help us to identify the bug with the following process?

1. Right-click on the Avocode icon
2. Click on Properties
3. Leave only `Avocode.exe` in Target text field
4. Add flags `Avocode.exe --dev-tools` (--disable-gpu is not important for this case)
5. Try to launch Avocode
6. Send us a screenshot of the console

<img width="477" alt="windows" src="https://cloud.githubusercontent.com/assets/879564/16581977/86fa4738-42ac-11e6-9c4b-8500f7e27369.png">

**Comment by connor-bean** [comment]
Hey @BotanikRock -

Were you able to follow Petr's process above?

Thanks,
Connor, Avocode Support

**Comment by BotanikRock** [comment]
@connor-bean @petrbrzek Im sorry im making you wait so much time.

@petrbrzek ive added those flags, as you ask, but nothing extra rly happens, no console show up: http://joxi.ru/nAyxE4qSXxVMJ2.

**Comment by petrbrzek** [comment]
@BotanikRock Did you remove the `Updater.exe` from the Target text input? There should be only the path to your app and the flag `--dev-tools`.

**Comment by BotanikRock** [comment]
@petrbrzek that's my target field
C:\Users\miroshnikov#ap\AppData\Local\avocode\app-2.10.1\Avocode.exe --dev-tools

**Comment by jakubzitny** [comment]
@BotanikRock can you please try it like this `Avocode.exe -- --dev-tools` to display the console?

**Comment by Cactusx09** [comment]
This problem happened to me.
I tried different flags like `-- --dev-tools` and `--dev-tools` but nohing happens, console don't run.
![image](https://cloud.githubusercontent.com/assets/9021479/21356637/1224017a-c6db-11e6-8d48-ab23b3e4dee8.png)

Problem: when i start Avocode it's launch 3 processes in background, but nothing happens.
![image](https://cloud.githubusercontent.com/assets/9021479/21356750/63460cba-c6db-11e6-8867-0b364cbe2dce.png)

**Comment by connor-bean** [comment]
Hey @Cactusx09 -

Can you check to see if this is now working for you in 2.12.1? Please let us know your results.

Thanks,
Connor, Avocode Support

**Comment by Cactusx09** [comment]
hi, @connor-bean, problem solved  in 2.12.1! Thnx
