### ISSUE TITLE
PSD loading stops by 95%

### ISSUE THREAD

**Issue by 25RBazookas** [avocode/avocode#1120]
#941 Still not resolved.

**Comment by 25RBazookas** [comment]
Workaround: close and restart Avocode

**Comment by jakubzitny** [comment]
Hi @25RBazookas, this is happening from time to time, that's true. Thanks for bringing it up.

We're currently reimplementing the upload process from the grounds up so this should be resolved in one of the next releases. Let's keep this open untill we can 100% confirm it's not happening anymore.

**Comment by 25RBazookas** [comment]
@jakubzitny thanks for the quick response. It's indeed handy to let him open so that other people know that this still is an issue.

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

You can download the update at https://avocode.com/news.html

Thanks for your patience on this.

Connor, Avocode Support
