### ISSUE TITLE
SVG export 2 layers together

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1121]
Hi,

If i want export  two layers together as svg export is done but there some wierd issue.

![image](https://cloud.githubusercontent.com/assets/6084353/18714041/c4c3b13a-8014-11e6-86cd-efbb48fdd237.png)
 separately is ok 

![image](https://cloud.githubusercontent.com/assets/6084353/18714204/4762e16a-8015-11e6-9685-4ee4856bfa38.png)

Thx, I can also send you psd with that layers

Osx  EL Caplation 10.11.6

**Comment by connor-bean** [comment]
Hey @vAhyThe -

Can you send us the PSD to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by vAhyThe** [comment]
already sent

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
