### ISSUE TITLE
Add the ability to change password in the web manager account settings

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#1123]
Hello,
Silly question, but how to change user password on avocode.com?

**Comment by connor-bean** [comment]
Hey, @VaclovasV -

When you login to the manager, you can click the link "Forgot Password" and it will allow you to reset your password.

Please see the screenshot below:

![screen shot 2016-09-22 at 10 56 04 am](https://cloud.githubusercontent.com/assets/17878371/18742210/417cd32a-80b3-11e6-917c-f9f7faed88fb.png)

Please let me know of any other questions!

Thanks,
Connor, Avocode Support

**Comment by vojtatranta** [comment]
@VaclovasV Also in the app while login there's a `Forgot password` link on the top right from the `password` field

**Comment by VaclovasV** [comment]
heh, tricky way to change it :D maybe you can add it to account management?

**Comment by vojtatranta** [comment]
@VaclovasV we will add it into Account settings in the app in circa in `2.14.0`.

**Comment by vojtatranta** [comment]
Deployed!
