### ISSUE TITLE
Improvement - copy on single click

### ISSUE THREAD

**Issue by vrozkovec** [avocode/avocode#1127]
It could be useful if you could distinguish between single click vs click and select text in style panel.
This way, you could click only the value or property and the item you clicked on would be copied in a similar fashion that you now click on the line numbers.
It could improve workflow a lot, no need to select the value and press Ctrl+C.

**Comment by connor-bean** [comment]
We just released 2.11 so I'm closing this out. Please let us know if this problem persists.

You can download the update at https://avocode.com/news.html

Thanks for your patience on this.

Connor, Avocode Support
