### ISSUE TITLE
Processing Failed

### ISSUE THREAD

**Issue by ThomasUnwin** [avocode/avocode#1133]
Hi there,

I'm trying to access some uploaded sketch files in the project design page and am getting 'processing failed' message inside a red box.

I've seen another previous user (jcjvd) had the same issue - but his resolution doesn't work for me as i no longer have access to the mac i used to upload the designs in the first place and it doesn't seem possible to upload a sketch file from a windows computer in to Avocode (as there is no sketch app for windows).

At present i can't access any of my designs to work on.

Just to clarify, I do have the sketch file saved on my windows computer, but i can't select it to re-upload in to avocode (and drag and drop doesn't work without a sketch sync app which i can't seem to find for windows), which means i have no way of solving this 'processing failed' error.

Thanks in advance for help...

**Comment by connor-bean** [comment]
Hey @ThomasUnwin -

Could you send us the design to team@avocode.com? Please mention this ticket in your email.

Thanks,
Connor, Avocode Support
