### ISSUE TITLE
Wrong opacity value

### ISSUE THREAD

**Issue by PixelT** [avocode/avocode#1136]
In avocode 2.11

In **code** panel I have:
```
box-shadow: 0 0 21px rgba(0, 0, 0, 0.14);
```

In **layer** panel I have:
```
OPACITY: 14.000000000000002%
```

**Comment by bolekkerous** [comment]
Hello!
Could you please share the design with us at team@avocode.com, so we can investigate it properly?

Thanks!
Best regards,
Bolek, Avocode Team

**Comment by jakubzitny** [comment]
Hi @PixelT, can you please check if this is still happening in `2.11.1`?

**Comment by PixelT** [comment]
In 2.11.1 seems to be OK. Thanks!
