### ISSUE TITLE
Multiselect

### ISSUE THREAD

**Issue by salexpro** [avocode/avocode#1139]
Add please multiselect to code section. It was useful thing in older versions of Avocode. When I hold Cmd or Shift I got a necessary lines.
![image](https://cloud.githubusercontent.com/assets/4237964/19004156/2454e8b8-875d-11e6-88f0-d6ee96f7627a.png)

**Comment by jakubzitny** [comment]
Hi @salexpro, we have already got a lot of complaints about this change and we'll include the old behaviour in one of the next releases of Avocode.

We're already tracking this issue in #1068 so I'll close this one. Look there for more information and updates.
