### ISSUE TITLE
Doesn't copying Base64

### ISSUE THREAD

**Issue by salexpro** [avocode/avocode#1141]
In slice mode I tried to copy base64 and it generate to me transparent image
![image](https://cloud.githubusercontent.com/assets/4237964/19014541/42dbc676-87f8-11e6-9fce-1cec9b2651bf.png)

**Comment by jakubzitny** [comment]
Hi @salexpro, thanks for reporting this. I can confirm the problem with base64 slice export. We'll try to fix this for next release and we'll let you know here when it's ready.

Feel free to let us know if you have any other problems or questions about Avocode.

**Comment by jakubzitny** [comment]
Hi, this has been fixed in `2.11.1` so I'm going to close this issue.

Feel free to reopen if you still have problems with this or anything else 😉
