### ISSUE TITLE
Can't launch your product on mac sierra

### ISSUE THREAD

**Issue by integrativeideas** [avocode/avocode#1147]
IMPORTANT: Please try to describe how did it happen.

---

App v. `2.11.0`
Source UID: null

```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @integrativeideas, is there any chance you have more info about your problem so we can help? We're testing and using Avocode `2.11` on macOS Sierra and everything seems to be working fine as before.

Have you tried downloading Avocode again? Have you tried moving it to `/Applications` or another location? What is the problem exactly? Can you send us a screenshot of when the launching freezes?

Thanks.

**Comment by integrativeideas** [comment]
Attached are screen shoots of what is happening. The unexpected error pops up every time I launch the app. Some of our other devs are having the same issue and are on old versions of OS, but they are able to login. When I try to login I get the token error as shown in the second error message.

![screen shot 2016-10-05 at 7 55 43 am](https://cloud.githubusercontent.com/assets/1491224/19113950/84162614-8ad1-11e6-82ce-a589455b2ed6.png)
![screen shot 2016-10-05 at 7 56 03 am](https://cloud.githubusercontent.com/assets/1491224/19113951/84247c8c-8ad1-11e6-8b29-978d57d1ac6a.png)

**Comment by petrbrzek** [comment]
@integrativeideas Do you use some sort of firewall or proxy?

**Comment by integrativeideas** [comment]
I'm sure our IT does. Is there anything that can be done to adjust the config?

**Comment by petrbrzek** [comment]
Yeah, but let's try this first.

1. Open you terminal app
2. Launch Avocode app with this command `open -a /YOUR_PATH_TO_APP/Avocode.app   --args -- --dev-tools `

It's going to launch Avocode with devtools. It should help us a lot if you could send us a screenshot of the console and also stack trace of the error if any. Thanks a lot.

**Comment by integrativeideas** [comment]
still getting the error

**Comment by integrativeideas** [comment]
Here are the two errors from the console:

console.js:26 URL http://manager.avocode.com/api/update/avocode-app/mac?version=2.11.0 did not return update information

raven.js:290 Uncaught [object Object]wrapped @ raven.js:290

**Comment by petrbrzek** [comment]
@integrativeideas Thanks. Can you ping me on petr[at]avocode.com? I need to know some information that should not be publicly available.

**Comment by integrativeideas** [comment]
It returns nothing

**Comment by connor-bean** [comment]
Hey, @integrativeideas -

Could you email us at team@avocode.com instead, then? I will pass along the information to Petr. Please mention this ticket in the subject.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @integrativeideas -

Could you email us at team@avocode.com instead, then? I will pass along the information to Petr. Please mention this ticket in the subject.

Thanks,
Connor, Avocode Support
