### ISSUE TITLE
Not able to upload two Sketch's files that have folders starting with the number '01'

### ISSUE THREAD

**Issue by fapires** [avocode/avocode#1148]
1. create a new project folder 
2. upload two Sketch's files where both have a folder starting with the number '01' (in my case they are: '01_home_(grid_image_view_one_photo)' and '01_post_page')
3. Avocode can't upload both folders. It always overwrites the last uploaded folder over the last one. But when I open the Avocode Sync 3.9 for Sketch, for both Sketch's files, the folders are checked as uploaded, but on Avocode app, only the last folder uploaded is shown.

**Comment by fapires** [comment]
Other important information about that issue:
1. When I upload the first Sketch file inside the project folder, it creates the list section, on Avocode, with the name of the sketch file uploaded and add the screens (folders) below the section
2. But when I upload the second Sketch file, it doesn't create the new list section, with the second Sketch file name, instead, the plugin adds the second Sketch's file screens (folders) below the list section of the first Sketch file.

**Comment by petrbrzek** [comment]
Thanks for reporting the issue. Isn't it possible that you upload the second design as a revision of the first design? Otherwise, it would be helpful if you could share me those two Sketch files to petr[at]avocode.com.

**Comment by fapires** [comment]
Hey, I think I can't be uploading the second design as a revision because they have different names.
Unfortunately, I can't share the Sketch files with you. :/
Could you reproduce that issue?

**Comment by jakubzitny** [comment]
Hi @fapires, we've recently released Avocode 2.14.4 with our new Sketch plugin. I tried to reproduce this issue with it and I had no problems. I think we can close this out.

Please download the latest Avocode and the new plugin will be automatically installed for you. Let us know if you have any more issues with it.
