### ISSUE TITLE
Exporting visible layers only inside a group

### ISSUE THREAD

**Issue by p-boiko** [avocode/avocode#1150]
Hi.

Can't figure out how to export only visible layers: http://screencloud.net/v/r349
Here on the screenshot I put the resulting image in red, yellow rectangles are pointing to the settings, which, I suppose, should help me hide text layers from export tool...

Am I doing something wrong?

**Comment by jakubzitny** [comment]
Hi @p-boiko, this is a known bug we currently have in Avocode, thanks for reporting it though. When you have hidden layers in a group, everything gets exported, not just visible layers. We're working on a fix and it will be ready for `2.11.1` or `2.12.0`.

If you need a temporary workaround for now, you can deselect the group and select only layers you want to export.

We'll let you know in this issue when we fix this, feel free to let us know if you have any more problems.

**Comment by p-boiko** [comment]
Thanks. Didn't found the issue, so sorry for duplication

**Comment by p-boiko** [comment]
Fixed in 2.11.1
And the latter also is much faster for me :)
Thanks guys.

S pozdravem,
Pavlo
