### ISSUE TITLE
No sync with avocode 3.9

### ISSUE THREAD

**Issue by podpole** [avocode/avocode#1151]
[problem-avocode.zip](https://github.com/avocode/avocode/files/511390/problem-avocode.zip)

**Comment by bolekkerous** [comment]
Hello, podpole!
Could you please send us the problematic design to team@avocode.com, so we can investigate what causes the problem?

Thanks!
Best regards,
Bolek, Avocode Team

**Comment by vatns** [comment]
I had the same issue, even after updating both Sketch and Avocode plugins to .41
need help asap. " 2 artboards failed to sync."

**Comment by bolekkerous** [comment]
This shouldn't happen anymore with the latest versions of the Avocode app and the Sketch plugin.

You can always download the latest versions here:
https://manager.avocode.com/downloads/

If you still experience this problem or any other problem, please create a new issue or comment here.
