### ISSUE TITLE
designs will not upload after the new update to the program

### ISSUE THREAD

**Issue by dpwebco** [avocode/avocode#1152]
the app will not let me upload designs 👎

**Comment by jakubzitny** [comment]
Hi there, @dpwebco, could you please give us more details on this? Does the app start uploading or not at all? Are you using the latest 2.11 or 2.11.1 beta already? What system are you using? Can you send some screenshots so we can see what's happening?

**Comment by petrbrzek** [comment]
@dpwebco We need more info. Can you help us with that?

**Comment by connor-bean** [comment]
@dpwebco We need more info. Can you help us with that?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
