### ISSUE TITLE
Add ability to disable opacity on layer

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#1153]
Sometimes designers make icons opaque in the design to show disabled/hovered/etc state
i have to manually make item visible in photoshop(disable opacity on layer)
it would be really great if avocode had some shortcut to do that

**Comment by bolekkerous** [comment]
Hey there!
Thanks for the suggestion - we'll probably add an option to hide/show layer effects on layers in the future. Opacity could be a part of that.

We would ask you to add it to our UserVoice, where other users can vote for your idea too.

http://avocode.uservoice.com/forums/277080-feature-voting

Thanks!
Bolek, Avocode Team

**Comment by vojtatranta** [comment]
@Lukavyi probably better way to do it is to make multiple layers with such state.

**Comment by jakubzitny** [comment]
Closing with respect to #1126.
