### ISSUE TITLE
Desktop app - error during uploading mutiple files

### ISSUE THREAD

**Issue by kure-** [avocode/avocode#1154]
While uploading mutiple .PSD files (8) on Windows desktop app, there were multiple PSDs marked with red "error ... send us a bug report". Certainly, something like half has finished uploading and processing and then the rest errorneous PSD files continued with uploading and processing.
This may lead users to cancel the process of uploading and re-doing the process again.

**Comment by jakubzitny** [comment]
Hi @kure-, thanks for reporting this. Did the ones with error eventually finish correctly and you can open them or not?

I am looking into the problem now so we can fix it for `2.11.1`.

**Comment by kure-** [comment]
they are still being processed right now, but I can confirm, that 2 of the errorneous PSDs has finished uploading & processing.
I think it might be also network related error, since it has completely consumed all of it :)
Maybe some queue while uploading multiple files would help.

**Comment by jakubzitny** [comment]
This is definitely a bug in the app. I think restarting the app should help, and if any of the designs are not there or still failed, please re-upload them again.

I am working on a fix right now so this does not happen again.

Btw, there should be an upload queue at the bottom of the app, but in this case the errors probably stopped the upload even though the files might have been still uploading.

**Comment by kure-** [comment]
cool thanks, excellent client service btw. 👍

**Comment by vojtatranta** [comment]
@kure- you are welcome Kuře ;-)

Say hello to Vojta, Darja and Lukáš!

**Comment by jakubzitny** [comment]
Fix for this issue has been released with `2.11.1` yesterday so I am going to close this issue. Feel free to reopen if it happens again. 😉 

Thanks againg for report.
