### ISSUE TITLE
Crashing on medium large files

### ISSUE THREAD

**Issue by zariaxs** [avocode/avocode#1155]
Hi there, 
The plugin crashes when trying to export my Sketch artboard. Please advice

**Comment by bolekkerous** [comment]
Hello, zariaxs!
Could you please provide some more information about the issue?

What exactly does crashing means? Does it actually crash, or does it show error? If so, some screenshots would help.

Another thing that would help a lot is if you could send us the problematic design to team@avocode.com so we can investigate it properly.

Thanks,
Bolek, Avocode Team

**Comment by connor-bean** [comment]
Hello, zariaxs!
Could you please provide some more information about the issue?

What exactly does crashing means? Does it actually crash, or does it show error? If so, some screenshots would help.

Another thing that would help a lot is if you could send us the problematic design to team@avocode.com so we can investigate it properly.

Thanks,
Bolek, Avocode Team

**Comment by connor-bean** [comment]
Please comment if you can provide more information on this issue.

Thanks,
Connor, Avocode Support
