### ISSUE TITLE
Hide cmd window when Avocode is running

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#116]
If I close it manually, Avocode closes as well. It's annoying to have two taskbar entries for a single program.

![image](https://cloud.githubusercontent.com/assets/1693651/6020091/62e5fa8e-abb0-11e4-90f0-1468c512d057.png)

**Comment by rychlis** [comment]
You can open avocode directly using atom.exe to avoid opening the cmd window completely. We will have a windows installer later that will create a proper link without the cmd window

**Comment by VPenkov** [comment]
This seems to be fixed now.
