### ISSUE TITLE
Sketch Plugin doesn't update the page's name on Avocode app

### ISSUE THREAD

**Issue by fapires** [avocode/avocode#1162]
When I change a page's name, in a Sketch file, and update it through the Avocode's Sketch plugin, it only updates the folders, but not the page's name.
See the screenshot sequences below:
1. The initial page's name is 'Workflow'
   ![screen shot 2016-10-11 at 16 07 57](https://cloud.githubusercontent.com/assets/8724228/19284750/90993fd8-8fcd-11e6-8d48-4e666644d2b3.png)
2. Page's name changed to '[loop]_curated_content
   ![screen shot 2016-10-11 at 16 08 33](https://cloud.githubusercontent.com/assets/8724228/19284780/ac6eea96-8fcd-11e6-87e8-dcf45896c269.png)
3. The page's name on the plugin is the new one
   ![screen shot 2016-10-11 at 16 09 24](https://cloud.githubusercontent.com/assets/8724228/19284822/d5959578-8fcd-11e6-81df-39c0661087aa.png)
4. But when I sync the project on Avocode app, it is still showing the old page's name ('Workflow')
   ![screen shot 2016-10-11 at 16 10 22](https://cloud.githubusercontent.com/assets/8724228/19284833/e6673f32-8fcd-11e6-8e4a-a81fba19f3c1.png)

It doesn't matter what I do, it is never updated.
I already tried to delete the project and upload it again, but the app can's get the new page's name.

Thanks

**Comment by jakubzitny** [comment]
Hi, this should be fixed in latest Avocode `2.16.1`, please update and let us know if you have any more problems or feature requests :wink:.
