### ISSUE TITLE
Cannot download PSD on Windows 10 32-bit

### ISSUE THREAD

**Issue by VitalyBesk** [avocode/avocode#1164]
`IMPORTANT:` Please try to describe how did the crash happen.

App v. `2.11.1`

Hello. I'm triyng to download PSD (190mb) but I can not. 
http://prnt.sc/csl52p
http://prnt.sc/csl07q

**Comment by vojtatranta** [comment]
@VitalyBesk I suppose you have 64bit version of Windows, right?

Can you send us this problematic psd at team@avocode.com? Thanks

**Comment by connor-bean** [comment]
Hey @VitalyBesk -

I received your PSD. Thanks for sending this over. I have passed it along to Vojta and the dev team... we will respond here in this thread once we have more information.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @VitalyBesk -

You can download the 64bit version of Avocode for Windows [here](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.11.1/avocode-app-windows-x64-2.11.1.exe).

Please let me know if you continue to have this problem once you've switched to the 64bit version.

Thanks,
Connor, Avocode Support
