### ISSUE TITLE
Crashes download

### ISSUE THREAD

**Issue by AlexLvov** [avocode/avocode#1166]
At the beginning of avocode to hang loading images on 99%. 
http://prntscr.com/cwjtol
If the file is 26 mb, it is loaded properly. If 33 mb - freezes

Windows 8.1-64
Avocode 2.9.1 / Avocode 2.11.1

**Comment by connor-bean** [comment]
Hey @AlexLvov -

Would you be able to send us the design file to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by AlexLvov** [comment]
Hey
Well, I'll send, but I have a global problem. Files larger 26 MB are not loaded.

**Comment by jakubzitny** [comment]
@AlexLvov thanks for reporting this. So this was happening in `2.9.1` already, right? Are you using any proxy server?

**Comment by connor-bean** [comment]
Hey @AlexLvov -

Would it be possible to try using Avocode on a different operating system than Windows? 

Please let us know if you're able to try uploading the same design when you're using Linux or Mac.

Thanks,
Connor, Avocode Support

**Comment by AlexLvov** [comment]
Hey
The problem was in both versions.
Proxy server not using.
I do not use Linux/Mac.
I connected to the other line and the problem of Internet disappeared. Can a weak channel to be causing the problem?

**Comment by vojtatranta** [comment]
@AlexLvov it looks more like problem with OS/Hardware, but if it now works, it's okay.

Clsoing
