### ISSUE TITLE
App crashes while opening a new downloaded PSD file (3 times)

### ISSUE THREAD

**Issue by anastasiauz** [avocode/avocode#1167]
App v. `2.11.1` on Ubuntu 12.04 32bit. App freezes after psd loading. With the new file it happens always (I failed to open it). Before I loaded 2 psd files successfully.

**Comment by connor-bean** [comment]
Hey @anastasiauz -

What OS are you running? And could you send us the PSD to team@avocode.com?

Thanks,
Connor, Avocode Support
