### ISSUE TITLE
open PSD and the app crashed

### ISSUE THREAD

**Issue by juliette2082** [avocode/avocode#1168]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.11.1`

**Comment by connor-bean** [comment]
Hey @juliette2082 -

Can you explain a little more what you were doing when this crash happened?

Furthermore, what OS are you running?

Thanks,
Connor, Avocode Support

**Comment by juliette2082** [comment]
Hi, this happens only if i try to open one psd file i dont know what happens but it crashed avocode. if it help i can recive this file, on others files all ok -- Zaiceva Julia89827175638skype: juliette2082   23.10.2016, 00:32, "Connor" <notifications@github.com>:Hey @juliette2082 -Can you explain a little more what you were doing when this crash happened?Furthermore, what OS are you running?Thanks,Connor, Avocode Support—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by connor-bean** [comment]
Hey, @juliette2082 -

How large was the file you were trying to upload? 

Thanks,
Connor, Avocode Support
