### ISSUE TITLE
Start Avocode maximized

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#117]
For people like me on laptops, these overlaps are pretty annoying.
Also, nothing happens when I change the shortcut to run the program maximized.
![image](https://cloud.githubusercontent.com/assets/1693651/6020098/814b514a-abb0-11e4-85c8-7c8418f999b7.png)

**Comment by marekhrabe** [comment]
The window on screenshot is maximized. I guess you are suggesting running in fullscreen so no window title and Taskbar will be present. I will add this to our internal bug tracking system, it might be an easy thing to add

**Comment by VPenkov** [comment]
It's equal to my screen's dimensions but it's not maximized. If I have a translucent/transparent taskbar, Avocode's window border would be underneath it.
