### ISSUE TITLE
SVG export size of svg

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1172]
Hi guys!

Can somehow be removed from export svg code this parts ?? 
`<title>Combined Shape</title><desc>Created with Avocode.</desc>`
Because i always remove this to have smaller size.

Second question. Can i somewhere change setting of exported code.
i mean like `d="M317 1333C317 1329.13401 320.13401` setting only for to digits
`d="M317 1333C317 1329.13 320.13` this also reduce size of svg image.

Thanks!

**Comment by jakubzitny** [comment]
Hi @vAhyThe, we've added SVGO optimization for all SVG exports a while ago, the titles should be removed automatically and numbers should be rounded to two digits as well. There is another bunch of optimization options that are happening by default. You can disable Export optimization in `Help -> Troubleshooting` menu.

I am closing this issue, we might add a possibility to configure separate optimization options in the future. If you need it badly now, I suggest exporting without the optimization and then use [svgomg](https://jakearchibald.github.io/svgomg/) yourself. I think the default config should be sufficient for most of the use cases.
