### ISSUE TITLE
Complete crash, blue screen, netio.sys on windows 8.1

### ISSUE THREAD

**Issue by AndriusZid** [avocode/avocode#1173]
Hi,

I have issue using Avocode, because every time when i start application, after few minutes my Windows 8.1 goes to blue screen and crash with this error: SYSTEM_SERVICE_EXCEPTION (Netio.SYS)
I have searched in Microsoft forums for solution, but found nothing. When I don't use Avocode my systems works fine. I use version 2.11.1

![2016-10-25 17 30 17](https://cloud.githubusercontent.com/assets/8049177/19691141/e40dde8a-9adb-11e6-84cc-a4eb73b34ae0.jpg)

**Comment by connor-bean** [comment]
Hey @AndriusZid 

Were you experiencing this when you were using an older version of Avocode? If it worked in a previous version, I could send you an older version of our application to use instead. 

Please let me know of any questions.

Thanks,
Connor, Avocode Support

**Comment by AndriusZid** [comment]
Hi @connor-bean 

It crashed only with 2.11.1. With older versions it never happened.
I would like to try with older version, because now I'm just avoiding to open Avocode at all.

Thanks

**Comment by connor-bean** [comment]
Hey @AndriusZid -

Here's the link for Windows [version 2.11](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.11.0/avocode-app-windows-zip-2.11.0.zip)

And here's the link for Windows [version 2.10](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.10.1/avocode-app-windows-zip-2.10.1.zip)

Please let me know if one of these two versions works better for you.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @AndriusZid -

Were you still seeing this error when you switched to 2.11 or 2.10?

Thanks,
Connor, Avocode Support

**Comment by AndriusZid** [comment]
Hi @connor-bean ,

Unfortunately yes. I'm thinking this might be my computer issue. Still not found solution to this :/

Thanks

**Comment by AndriusZid** [comment]
After upgrading to version **2.12.6** issue is not reproduced anymore.
