### ISSUE TITLE
can't upload file in application 0%

### ISSUE THREAD

**Issue by comrade-tea** [avocode/avocode#1174]
I can upload layout from site, but can't from application
can't upload file in application 0% ver 2.11.1

**Comment by connor-bean** [comment]
Hey, @comrade-tea -

Could you send us the problematic design file to team@avocode.com? Could you also let us know which OS you're running?

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Hey @comrade-tea, thanks for reporting this. We need more info to be able to help. Are you using any proxies or do you have any unusual internet connection? Was this happening in older versions of Avocode or did you just start using it?

**Comment by comrade-tea** [comment]
Oh, nevermind, I guess it's just network problems.
I don't use any proxies and got usual connection. Everything was fine and then the provider has become blunt. At home everything is working properly.
Thanks for the quick response, and sorry for the unnecessary anxiety.

**Comment by jakubzitny** [comment]
Thanks man, feel free to let us know if you have any more problems.
