### ISSUE TITLE
Can't login to Avocode

### ISSUE THREAD

**Issue by jhaiwho** [avocode/avocode#1177]
I can't login to both browser login and software.. It keeps giving me 504 error on software and 500 on browser: http://prntscr.com/czubwy. Is there any way to resolve this?

**Comment by NSLS** [comment]
+1 Having the same issue. Seems like the server went down

**Comment by miguelmich** [comment]
Same here, I need to use the avocode urgently!

**Comment by GuBonjour** [comment]
+1 

same issue.  504 on software and 500 on browser.

Our font-end engineers ,designers and PM use Avocode for collaboration.

BTW.
Is there any possible to provide a version(with a business licence)  hosted on a private server,which may likely avoid network problems.

**Comment by trosenbauer39** [comment]
+1 here too. Same errors on browser and mac desktop app. I've contacted support - I recommend everyone do the same so we get their attention. I need to get designs delivered asap.

**Comment by silviaRe** [comment]
Same here. Can't login anywhere. 
Error:
504: Internal Server Error.

Please fix it fast.

**Comment by iberdinsky-skilld** [comment]
Guys! Don't block my working friday! I need to go home earlier:) Fix login

**Comment by tieroneco** [comment]
Same here Can't login in App and Web.

**Comment by ifynk** [comment]
+1 
502: Internal Server Error

**Comment by Skadelig** [comment]
+1

**Comment by connor-bean** [comment]
Hey, thanks for reaching out.

We definitely apologize for any inconveniece this caused as we had our servers go down on Friday. Everything should be up and running ok now and we have been working internally to avoid this problem in the future.

Please let us know of any questions.

Thanks,
Connor, Avocode Support
