### ISSUE TITLE
403 When viewing my design

### ISSUE THREAD

**Issue by aarr0n** [avocode/avocode#118]
I've exported my 2 designs from Sketch into a new project.

Although I can see them listed, when I try and navigate through to them (/view route), the preview.jpg returns a 403.

Any ideas?

**Comment by PavelGavlik** [comment]
Hi,
could you please try to sync the design(s) again? If it doesn't work, then send us the .sketch files to team@avocode.com and we'll look into it.

**Comment by aarr0n** [comment]
Resync'ing worked - thanks!
