### ISSUE TITLE
can't export to svg

### ISSUE THREAD

**Issue by sajkun** [avocode/avocode#1182]
I'm not able to convert any layer to svg. Svg button is grey and not active.

**Comment by connor-bean** [comment]
Hey @sajkun -

Are you sure that the layers you're trying to select are not a text layer or a raster image? Furthermore, if the layer is a vector with unsupported effects (Bevel or Emboss), then Avocode will not be able to render it correctly.

Could you send us the problematic design to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by sajkun** [comment]
U're right the problem was with template, not with avocode

2016-11-08 13:01 GMT+03:00 Connor <notifications@github.com>:
