### ISSUE TITLE
EPS rasterized in psd and no export SVG possible

### ISSUE THREAD

**Issue by pierre521** [avocode/avocode#1184]
I've EPS vectoriel image in my psd. And I can't export it on SVG. The layer is automatically rasterized. There is a solution to not convert EPS in rasterized image ?

**Comment by connor-bean** [comment]
Hey @pierre521 -

EPS is not currently supported in Avocode. If you would like to see this feature added to our platform, I will ask that you add this to our UserVoice forum [here](https://avocode.uservoice.com/forums/277080-feature-voting). 

We use UserVoice to plan new features, and we prioritize based on popularity, so please make sure you upvote for it as well as adding your use case.

Please let me know of any other questions.

Thanks,
Connor, Avocode Support
