### ISSUE TITLE
Letter-spacing is not supported ?

### ISSUE THREAD

**Issue by pierre521** [avocode/avocode#1185]
Hi guys,
I really love Avocode. I've just a probleme with letter spacing. It doesn't appears in CSS Code on avocode (in psd file). Is it possible to add this feature ?

**Comment by connor-bean** [comment]
Hey, @pierre521 -

We are currently working on this feature and it will hopefully be implemented relatively soon. I saw your ticket to team@avocode.com and it looks like Bolek responded there too. I am just posting this here to make sure the answer is tied to this Github ticket as well.

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
-> #793.

**Comment by bolekkerous** [comment]
Letter-spacing property for Photoshop documents should now be available on the web app (https://app.avocode.com/) for all newly uploaded designs into the web app.

It's coming to the desktop app as well in upcoming update, which should be released in 1-2 weeks.
