### ISSUE TITLE
Problems with uploading design in Ubuntu 16.04

### ISSUE THREAD

**Issue by MindTwisted** [avocode/avocode#1186]
Hello. I have a problem with uploading a PSD design into Avocode on Ubuntu 16.04 OS. I can't upload design with desktop app and with web app. The only way I can upload design is with dropbox. 
Besides I can easily upload files to other web services as google files or dropbox.

I have tested different PSD files, everything is the same. On desktop app it freezes on 1% and with web app it freezes on 0%.

**Comment by Steingate** [comment]
Same problem here on Archlinux

**Comment by connor-bean** [comment]
Hey @MindTwisted and @Steingate -

Could you try it again now? As of now, it looks like this could have been a problem with a server. Please let me know the result once you try again.

Thanks,
Connor, Avocode Support

**Comment by MindTwisted** [comment]
Hi. Just tried and everything is the same .. I choose psd file and upload process freezes on 0-1%, both desktop and web app.

**Comment by connor-bean** [comment]
Hey @MindTwisted -

Are you using a proxy? Have you had other problems with your connection as well? What country are you from?

Thanks,
Connor, Avocode Support

**Comment by MindTwisted** [comment]
I'm from Ukraine and I don't use proxy. I have no problems with other web services, I can easily download files to dropbox and then upload files to avocode from dropbox.
I have tested Avocode from another laptop with win7, tested it with this laptop with win10 and everything was just fine.

**Comment by Steingate** [comment]
Not working in the application, but working with the website.

From France without Proxy

**Comment by MindTwisted** [comment]
It seems like everything work fine now. Thank you a lot!
