### ISSUE TITLE
Hello, for some reason, you can not delete the sketch layouts

### ISSUE THREAD

**Issue by shectermen** [avocode/avocode#1187]
from PSD has a delete button, there is no sketch

**Comment by connor-bean** [comment]
Hey @shectermen -

Would you be able to provide us with screenshots or screencast of what you're seeing? We would need more information from you to accurately troubleshoot this problem.

Thanks,
Connor, Avocode Support

**Comment by shectermen** [comment]
only rename


>Четверг, 10 ноября 2016, 12:49 +03:00 от Connor <notifications@github.com>:
>
>Hey  @shectermen -
>Would you be able to provide us with screenshots or screencast of what you're seeing? We would need more information from you to accurately troubleshoot this problem.
>Thanks,
>Connor, Avocode Support
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Сергей Алпеев
salpeev@mail.ru

**Comment by bolekkerous** [comment]
Hello, @shectermen!
unfortunately, deleting Sketch designs in the web application currently is not possible. The reason is that the web application runs on a different engine and is quite outdated - that's why we're already working on a way to make the web app the same as the desktop app. Once we're finished with that, everything possible in the desktop app will be possible in the web app.

Meanwhile, you should be able to delete the Sketch design in your desktop app.

Hope it helps!
Best regards,
Bolek, Avocode Team

**Comment by shectermen** [comment]
but in the Desktop version also no delete button, Mac OS


>Четверг, 10 ноября 2016, 14:42 +03:00 от Bolek <notifications@github.com>:
>
>Hello,  @shectermen !
>unfortunately, deleting Sketch designs in the web application currently is not possible. The reason is that the web application runs on a different engine and is quite outdated - that's why we're already working on a way to make the web app the same as the desktop app. Once we're finished with that, everything possible in the desktop app will be possible in the web app.
>Meanwhile, you should be able to delete the Sketch design in your desktop app.
>Hope it helps!
>Best regards,
>Bolek, Avocode Team
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Сергей Алпеев
salpeev@mail.ru

**Comment by bolekkerous** [comment]
Oh, in that case it's probably a bug - could you please tell us what version of Avocode and OSX are you using?

It should look like this after you click the cog on the design tile:
<img width="135" alt="screenshot 2016-11-10 13 03 54" src="https://cloud.githubusercontent.com/assets/16084852/20176062/38897b6a-a746-11e6-8b5f-6906fa797531.png">  

Could you send us a screenshot of what are you seeing?

Thanks,
Bolek, Avocode Team

**Comment by shectermen** [comment]
The latest version of avaсode, Mac Os Captain, I have this button in PSD but do not have a sketch


>Четверг, 10 ноября 2016, 15:04 +03:00 от Bolek <notifications@github.com>:
>
>Oh, in that case it's probably a bug - could you please tell us what version of Avocode and OSX are you using?
>It should look like this after you click the cog on the design tile:
>Could you send us a screenshot of what are you seeing?
>Thanks,
>Bolek, Avocode Team
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Сергей Алпеев
salpeev@mail.ru

**Comment by bolekkerous** [comment]
Hey, @shectermen -
are you still not able to delete Sketch designs in the Desktop app?

Could you send us a screenshot if so?

**Comment by jakubzitny** [comment]
Right now you should be able to delete separate Sketch artboards. In `2.15.0` we'll be adding different view for Sketch files with ability to delete everything as well. I think we can close this issue, right?

**Comment by shectermen** [comment]
yes , thank you
