### ISSUE TITLE
Synced Sketch symbols don's show up in right project

### ISSUE THREAD

**Issue by JackZwanenburg** [avocode/avocode#1188]
When syncing artboards in Sketch to project B, some items show up in project A in Avocode. 

When finished uploading, the Avocode sync plugin confirms that the affected artboards are synced to project B, but won't show up there. 

The Sketch file used for project B might have been a copy from the Sketch file that was used for project A. In both projects the artboards have different names.

Using: Sketch plugin 3.9 / Sketch 40.3 / macOS Sierra.

**Comment by connor-bean** [comment]
Hey, @JackZwanenburg -

Thanks for reaching out. This sounds like a known bug to us. Here's a link to our [known bugs](https://github.com/avocode/avocode/blob/master/sketch-plugin.md#known-bugs).

If you duplicate an already-synced document (or artboard) to a new document it will still sync to the original design. You can fix this by syncing to a different project or by running [custom workaround script](https://github.com/avocode/avocode/blob/master/sync-as-new-design.md) 

Please let me know if this custom script helps solve this problem you're seeing.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @JackZwanenburg -

Did the custom script help solve this problem?

Thanks,
Connor, Avocode Support

**Comment by JackZwanenburg** [comment]
Hi,

Yes, it solved the problem. thanks a lot!

​Best​
,
Jack

*Jack Zwanenburg*
Senior Interaction Designer | NEP The Netherlands

+31 (0) 642 6063 35
jack.zwanenburg@nepworldwide.nl
nl.linkedin.com/in/jackzwa
www.nepworldwide.nl

*Superior Service & Lasting Relationships*
Integrity | One Team | Innovative | Passion

CONFIDENTIALITY NOTICE & DISCLAIMER:
This e-mail may contain confidential, proprietary, or privileged
information. If you are not the intended recipient please contact the
sender by reply e-mail and destroy all copies of the original message.

2016-11-16 12:50 GMT+01:00 Connor <notifications@github.com>:
