### ISSUE TITLE
Settings Export image path prefix

### ISSUE THREAD

**Issue by mjohnson24** [avocode/avocode#119]
I have tried using ../img/ and i also tried using /img/ and still it only puts the images in the root folder where the project export path is set.

**Comment by VPenkov** [comment]
I can confirm that, doesn't work for me as well.
Using the Windows version.

**Comment by marekhrabe** [comment]
Maybe the settings aren't clear. This is how it works - imagine this is your project structure:

![screen shot 2015-02-04 at 14 43 43](https://cloud.githubusercontent.com/assets/156676/6041405/60753c16-ac7c-11e4-8820-5bf3a9d9755d.png)

And these will be your settings:

![screen shot 2015-02-04 at 14 47 44](https://cloud.githubusercontent.com/assets/156676/6041453/d8268922-ac7c-11e4-8e66-2679b0d5dc0e.png)

The second option doesn't change the export path from first field, it is just hint for our code generator so you can get relevant code for exported asset (notice `../images/` that was appended, so it works correctly relative to css folder)

![screen shot 2015-02-04 at 14 49 40](https://cloud.githubusercontent.com/assets/156676/6041475/1c0f892c-ac7d-11e4-8da4-72f34c547f2b.png)

I created our internal issue and we will discuss this and maybe come up with better system or minimally better labels for that settings fields. Thanks for the report, I'll keep you posted :)

**Comment by mjohnson24** [comment]
Thanks for the info. I like the product so far but having to fumble through half the stuff in the app kinda sucks when there isn't videos or documentation to explain it. I know its a new product but videos or documentation would be great explaining all the features or even a future tutorial going through and actual project would be cool.

**Comment by petrbrzek** [comment]
Thanks for your opinion. Could you let us know which parts are the most unintelligible for you? So we can make videos and stuff for them first.

**Comment by mjohnson24** [comment]
Umm well most of it i kinda got it figured out to an extent. The few things id start with is the settings area, explaining what each setting does. Some of it is self explanatory but some isnt really understandable as to what it does or suppose to do. the code area kinda self explanatory, you just copy the code into a css file and change the selector names to what you want. The variables part took me a bit cause there really isnt much on it and me not knowing much about less and sass i really had to fumble through it to figure out what to do with it. As far as export is concerned you kinda already hit on that and hopefully explain that a little more.

I think really its the basic functions and what things do and means on the right side and the settings area. I will say that the DesignersGuides and My Guides one of em is working and one isnt i dont think. My Photoshop file had guides in it and in Avocode it shows all the guides on the left side jumbled up together.

**Comment by mjohnson24** [comment]
But the one thing im just kinda needing to know is i like the product but what advantages does your product have over the builtin stuff in the new version of Photoshop like the generator part and all the css stuff they built into photoshop? I know theres alot of work that goes into apps and there was obviously alot of work that goes into yalls but im just trying to weigh the difference between using photoshops that comes with it or paying the $20/month for yalls.

**Comment by petrbrzek** [comment]
Ok, we'll definitely prepare videos about Variables, Settings and Guides. 

I think [this blogpost](https://medium.com/@helloiamvu/5-things-you-will-love-about-avocode-e84699fd0321) explains a lot of what you asked.
