### ISSUE TITLE
Crashed while exporting layers into png

### ISSUE THREAD

**Issue by p-boiko** [avocode/avocode#1190]
IMPORTANT: Please try to describe how did it happen.

Application crashed trying to export 3 layers into .png

-----
App v. `2.11.1`
Avocode UID: 78965
```
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/path_to/Avocode-linux-x64/resources/app.asar/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
    at Object.findDOMNode (/path_to/Avocode-linux-x64/resources/app.asar/node_modules/react/lib/findDOMNode.js:45:205)
    at t.a._focusElement (file:///path_to/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:8:25008)
    at Immediate.<anonymous> (file:///path_to/Avocode-linux-x64/resources/app.asar/dist/avocode.min.js:8:26731)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by connor-bean** [comment]
Hey, @p-boiko -

Would you be able to send us the problematic design to team@avocode.com and reference this ticket in your email? Would you also be able to tell us a little more about what happened when this crash happened?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey, @p-boiko -

Would you be able to send us the problematic design to team@avocode.com and reference this ticket in your email? Would you also be able to tell us a little more about what happened when this crash happened?

Thanks,
Connor, Avocode Support

**Comment by p-boiko** [comment]
Hi!
    Thank you for your attention. Here is the
        design (one of a number of similar ones):
        https://www.dropbox.com/s/s72pj64eks8nqu7/BO_D_I_Site%20GB.psd?dl=0
      
    I tryed to extract combined layers for
        page background: https://screencloud.net/v/sFNp when Avocode
        crashed.
      
    Our designer extracted the layers for me in Photoshop, thus it's
      not an urgent matter. Still the bug is there and could happen
      again on next projects.
    
    My machine is Debian Unstable amd64
        
        Thank you!
    Kind regards.
        Pavlo.
      
    On 16.11.16 13:49, Connor wrote:
    
    
      Hey, @p-boiko
        -
      Would you be able to send us the problematic design to team@avocode.com
        and reference this ticket in your email? Would you also be able
        to tell us a little more about what happened when this crash
        happened?
      Thanks,
        Connor, Avocode Support
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/avocode/avocode","title":"avocode/avocode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/avocode/avocode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@connor-bean in #1190: Hey, @p-boiko -\r\n\r\nWould you be able to send us the problematic design to team@avocode.com and reference this ticket in your email? Would you also be able to tell us a little more about what happened when this crash happened?\r\n\r\nThanks,\r\nConnor, Avocode Support"}],"action":{"name":"View Issue","url":"https://github.com/avocode/avocode/issues/1190#issuecomment-260927066"}}}

**Comment by jakubzitny** [comment]
Hey @p-boiko, is this still happenig to you in latest Avocode, please?

**Comment by p-boiko** [comment]
Hi @jakubzitny 
No problem with 2.14.6
