### ISSUE TITLE
Sketch 41 and Avocode sync 3.9

### ISSUE THREAD

**Issue by krzaknet** [avocode/avocode#1191]
After update to newest version of Sketch (41) -> Avocode sync 3.9 plugin doesn't sync with avocode.

**Comment by connor-bean** [comment]
Hey @krzaknet -

We have updated our plugin to work with Sketch 41. Please try again now. If need be, you can download the latest version of the plugin [here](manager.avocode.com/downloads).

Please let me know of any other questions!

Thanks,
Connor, Avocode Support
