### ISSUE TITLE
Sync error with new version

### ISSUE THREAD

**Issue by jfguerra** [avocode/avocode#1193]
Hi I'm getting a strange error since I updated sketch to 41 version... 
<img width="760" alt="638be0a327ab4f2641bd943c2a59bae7" src="https://cloud.githubusercontent.com/assets/19912134/20212896/974c5de0-a7fd-11e6-878b-d07a1777842b.png">

It only happens to me?

**Comment by connor-bean** [comment]
Hey, @jfguerra -

Can you confirm that you are using the most recent version of our Sketch plugin? You can download it [here](manager.avocode.com/downloads).

Thanks,
Connor, Avocode Support

**Comment by jfguerra** [comment]
Hi Connor,

Yup, I confirm.
![avocode 41](https://cloud.githubusercontent.com/assets/19912134/20213185/37c4dc10-a7ff-11e6-9278-53574c5f1f7c.png)

**Comment by tomrantala** [comment]
I'm getting this also.

![screenshot 2016-11-11 16 16 17](https://cloud.githubusercontent.com/assets/15328334/20219101/67330fc2-a830-11e6-9ec3-4f7acef68dd5.png)

Upto date Sketch and Avocode Sync plugin. Mac OS version 10.11.6

**Comment by miqqqo** [comment]
Same problem here!

**Comment by bolekkerous** [comment]
Hello, guys!
Are you sure that after you open the plugin, there's the 41.0.0 displayed in the top right corner?
<img width="207" alt="screenshot 2016-11-11 16 05 13" src="https://cloud.githubusercontent.com/assets/16084852/20219241/cdde313c-a828-11e6-9c39-108699bc0db0.png">

It may be possible that the plugin did not update correctly. You can try quitting and reopening Sketch and if it doesn't help, reinstalling it completely should help. You can download the plugin here:
https://github.com/avocode/avocode/blob/master/sketch-plugin.md

If even the uninstall doesn't help, please send us log files (you can find a guide here):
https://github.com/avocode/avocode/blob/master/sketch-plugin.md#reporting-bugs

Hope it helps!
Best regards,
Bolek, Avocode Team

**Comment by jfguerra** [comment]
SOLVED! yes you are right, the version that was in that modal was not the latest one.

However as I showed you in "Plugins" menu item said me that I have "Avocode Sync 41" already. Another thing is when you download and you try to replace the old plugin just by clicking here 
<img width="433" alt="47dffcca7e1238f623afa814232a6ff6" src="https://cloud.githubusercontent.com/assets/19912134/20221632/f9599878-a829-11e6-83b4-ff8ea482772d.png">, never update effectively, I need to remove manually the old plugin and install the new one (as I did this time).

**Comment by connor-bean** [comment]
Hey @tomrantala and @miqqqo -

Did this work for you as well?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @tomrantala and @miqqqo -

Did this work for you as well?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Please comment on this ticket if you can provide more feedback.

Thanks!
Connor, Avocode Support
