### ISSUE TITLE
Problems with exporting images

### ISSUE THREAD

**Issue by sajkun** [avocode/avocode#1194]
In latest version when i want to export any image in jpeg, 
very offen i have chosen 2 options in popup window.
Chosed to export in png and in jpeg scaled 0.5 How can I turn this preselection off?

**Comment by jakubzitny** [comment]
Hi @sajkun, thanks for this report. Can you confirm that you're really using the latest version `2.12.0` and be a bit more specific about your problem? What platform is your project in? Is is web, iOS or Android?

The 0.5x/1x/2x scale in export modal is how you want your assets to be exported with respect to the design "scale". Design scale is set in Design Settings or in bottom right corner of the app. When your design is `1x` your assets should be exported by default in 1x. When you click `+` to add new export (in png), you should get `2x`, then `3x` and so on. Is this where you're getting 0.5 and you don't want that?
