### ISSUE TITLE
All of a sudden - nothing is working!

### ISSUE THREAD

**Issue by oriharel** [avocode/avocode#1195]
I get all red boxes with "What's Wrong?" and "The design failed processing and cannot be opened...".

What do I do???

**Comment by connor-bean** [comment]
Hey @oriharel -

Could you provide us with more information? What OS are you running? What version of Avocode? Are you using a plugin to upload the designs or are you importing them directly through the drag and drop feature? 

Could you also send us one of the problematic designs to team@avocode.com? 

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @oriharel -

Could you provide us with more information? What OS are you running? What version of Avocode? Are you using a plugin to upload the designs or are you importing them directly through the drag and drop feature?

Could you also send us one of the problematic designs to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Please comment on this ticket if you can provide more information. 

Thanks,
Connor, Avocode Support
