### ISSUE TITLE
Documents not Loading

### ISSUE THREAD

**Issue by msechea** [avocode/avocode#1197]
I am unable to view PSDs or PNGs when uploaded. Previously uploaded documents open up but not new ones. 

I'm using Avocode v2.11.1 and macOS Sierra. 
<img width="564" alt="screen shot 2016-11-16 at 9 39 22 am" src="https://cloud.githubusercontent.com/assets/23504174/20353581/f733a696-abe0-11e6-9eb4-dc05e7860490.png">
<img width="526" alt="screen shot 2016-11-16 at 9 39 15 am" src="https://cloud.githubusercontent.com/assets/23504174/20353580/f72ca922-abe0-11e6-8f0a-93f7a7118f97.png">

**Comment by connor-bean** [comment]
Hey @msechea -

Thanks for the report with the screenshots. I have a few questions for you to try and get more information for my dev team to troubleshoot:

Are you behind some sort of proxy?
Is this happening to multiple designs or just this specific one? If multiple designs, how many?
How big is this design/are these designs?
Did you experience this same issue on other versions prior to 2.11.1?

Thanks!
Connor, Avocode Support

**Comment by msechea** [comment]
Hi Connor, 

When connected to the work wifi, the documents do not load. When tethering from a cell connection from a phone they do. Please let me know what I can do.

**Comment by vojtatranta** [comment]
@msechea so it seems that your wifi is behind some proxy, isn't it?

There is a settings in preferences where you can specify your proxy server.

**Comment by connor-bean** [comment]
Hey @msechea -

Is your wifi behind some sort of proxy? Please see Vojta's comment above.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @msechea -

Is your wifi behind some sort of proxy? Please see Vojta's comment above.

Thanks,
Connor, Avocode Support
