### ISSUE TITLE
Exporting images from a masked group = blank images

### ISSUE THREAD

**Issue by kennethknudsen** [avocode/avocode#1198]
Same issue as [#1183](https://github.com/avocode/avocode/issues/1183)

Made a new document and placed images inside of a masked group. But when i try to export the image it's blank? if i remove the mask, the images are exported perfectly. 

- Sketch Version 41 (35326)
- Sketch Avocode plugin 41.0.0
- Avocode osx client 2.11.1
- MacOS 10.12 (16A323)

**Comment by connor-bean** [comment]
Hey @kennethknudsen -

Thanks for the report. Would you be able to send us the problematic design to team@avocode.com? 

Thanks,
Connor, Avocode Support

**Comment by kennethknudsen** [comment]
An email with the design is sent

**Comment by connor-bean** [comment]
Hey @kennethknudsen -

I just saw it in my inbox. Thanks for sending this over... I will pass it along to my dev team and we will continue talking via this thread once we have more information.

Have a great weekend,
Connor, Avocode Support

**Comment by kuzvac** [comment]
I also have this problem :( If i try to export image without mask, i get only blank image.
@connor-bean also, if i try to export group with image and hidden mask, exported image have  a hidden mask. 
![screenshot at 05 19-46-59](https://cloud.githubusercontent.com/assets/3762118/20889212/ecfd9054-bb23-11e6-9fd7-bc8e38440c66.png)

**Comment by connor-bean** [comment]
Hey @kuzvac -

Could you send us the file to team@avocode.com?

Have a great weekend,
Connor, Avocode Support

**Comment by kuzvac** [comment]
@connor-bean hmmm, issue with "export group with image and hidden mask" is resolved in 2.12.0-community-beta.2 :) 👍 

But export image without mask is still getting blank image. 
I send you design later.

**Comment by connor-bean** [comment]
Hey @kuzvac -

Could you try resending us the design to team@avocode.com? Please reference this ticket in your email.

Thanks,
Connor, Avocode Support

**Comment by kuzvac** [comment]
Hi @connor-bean just send sketch file to you.

**Comment by singlow** [comment]
I am having this issue. First noticed it using 2.11.1 and I still see it in 2.12.1. Design was created in Sketch and when I export the masked image, the masked layer is completely missing. The preview is correct.

Before the 2.12.1 update, I was able to export the parent layer and have it work, but now it is invisible whether I export the image layer, mask layer or parent layer.

**Comment by connor-bean** [comment]
Hey @singlow -

Can you send us your problematic design to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @singlow -

Can you send us your problematic design to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by jurjens** [comment]
I'm not sure if this is exactly the same problem, but in version 2.12.6 I still get blank images when trying to export a layer group with vectors/paths. The preview pane shows it just right though

**Comment by hiroshikuncr** [comment]
I have the same issue like jurjens, i'm ussing 2.12.6

**Comment by aminecmi** [comment]
Same problem here.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
