### ISSUE TITLE
Avacode crashed!

### ISSUE THREAD

**Issue by GenrihMD** [avocode/avocode#1199]
IMPORTANT: Please try to describe how did the crash happen.

I try to open design, but it does not download. A few minutes later Avacode crashed! And it repeats again and again... =((

**Comment by connor-bean** [comment]
Hey @GenrihMD -

How was the design synced? Did you use a plugin? Or did you drag and drop it right into Avocode?

Furthermore, can you see the design in the web manager (manager.avocode.com)? 

Finally, are you behind some sort of proxy?

Thanks,
Connor, Avocode Support

**Comment by GenrihMD** [comment]
Hey!

1. Use a plugin.
2. Can see.
3. No.

Thanx =)

**Comment by connor-bean** [comment]
Hey @GenrihMD -

Can you possibly try to re-sync it one more time from the plugin?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Please comment in this ticket if you can re-sync it one more time from the plugin.

Thanks,
Connor, Avocode Support
