### ISSUE TITLE
SVG export issues

### ISSUE THREAD

**Issue by Vargentum** [avocode/avocode#120]
When I'm exporting svg, there are some changes between avocode and photoshop output.
Avocode exported files are 2 times lighter, but:
1. some icons corrupted when used inside font
2. some icons had decreased detalization.  

I've attached link to sample: https://www.dropbox.com/s/orcft7rhh5qcizp/avocode-svg-export-sample.psd?dl=0

Social icons (except facebook icon) describe issue 1.
Icon placed inside button, describes issue 2.

You can convert this icons to font via https://github.com/sapegin/grunt-webfont, or http://fontastic.me/

**Comment by rychlis** [comment]
This should be fixed for several weeks now. You will need to use the latest extension and re-sync your design or re-upload the PSD again (drag&drop to app/web manager), the older extension wasn't exporting all needed vector data properly.

Let me know if you still experience this issue, we will re-open it in that case
