### ISSUE TITLE
Avocode - crash when rendering image data

### ISSUE THREAD

**Issue by phuongwd** [avocode/avocode#1200]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.11.1`

This issue happened when rendering image data

**Comment by vojtatranta** [comment]
Can you send us the PSD you are trying to render? Or Sketch? At team@avocode.com

**Comment by vojtatranta** [comment]
@phuongwd can you not at least slice the part that is not exportable and send us just this particular part for inspection?

What OS do you run?

**Comment by phuongwd** [comment]
@vojtatranta Sorry, I can not because the design is private.
OS: Windows 10 Enterprise.

**Comment by phuongwd** [comment]
@vojtatranta  Right!

**Comment by vojtatranta** [comment]
@phuongwd that's odd. We've had issues with `32bit` version of Windows. It was not able to allocate the amount of RAM needed to render the image. Do you have enough RAM, 4 gigs at least?

And by a crash, you mean that you get the dialog that says that app crashes with button that leads you to new issues here on github, right?

It is quite difficult for us to debug this issue without the design that crashes, you know.

**Comment by connor-bean** [comment]
@phuongwd that's odd. We've had issues with 32bit version of Windows. It was not able to allocate the amount of RAM needed to render the image. Do you have enough RAM, 4 gigs at least?

And by a crash, you mean that you get the dialog that says that app crashes with button that leads you to new issues here on github, right?

It is quite difficult for us to debug this issue without the design that crashes, you know.
