### ISSUE TITLE
Feature request: add letter spacing to regognized styles

### ISSUE THREAD

**Issue by VadimZhiltsov** [avocode/avocode#1203]
Currently letter spacing isn't shown in css styles block.

I speak about property:
https://developer.mozilla.org/en/docs/Web/CSS/letter-spacing

**Comment by jakubzitny** [comment]
Hi @VadimZhiltsov, we're currently supporting `letter-spacing` only for Sketch designs. We're already working on this feature for PS and it will be released in one of the next versions of Avocode, probably in the beginning of the next year.

We're already tracking this in #793, so I am closing this issue.

**Comment by bolekkerous** [comment]
Letter-spacing property for Photoshop documents should now be available on the web app (https://app.avocode.com/) for all newly uploaded designs into the web app.

It's coming to the desktop app as well in upcoming update, which should be released in 1-2 weeks.
