### ISSUE TITLE
Font size in .psd isn't the same as font size in Avocode

### ISSUE THREAD

**Issue by kasimier** [avocode/avocode#1208]
The font size in the .psd is 16px. The font size in Avocode is 20px.

I am using Avocode 2.11.1 on Windows 10 (x64).

**Comment by vojtatranta** [comment]
@kasimier hi,
thank you for this report.

Can you send us this proplematic `.psd` at team@avocode.com?

Thanks!

**Comment by kasimier** [comment]
Hello @vojtatranta ,

I've send the file through wetransfer.com as it was too big to send through my normal e-mail client.

**Comment by vojtatranta** [comment]
@kasimier no problem, thank you!

**Comment by vojtatranta** [comment]
@kasimier I have the PSD, which text do you think is wrong size? Can you send me a screenshot of the layer which seems to be wrong? Thanks

**Comment by kasimier** [comment]
Well this is painful... The design company has been changing all the font-sizes from 16px to 20px in the v2 .psd without telling us... I guess this isn't a bug at all, Avocode even helped me with my own shortcomings in the end... Thank you very much for your time, I hope it wasn't a big inconvenience.

**Comment by vojtatranta** [comment]
@kasimier I am glad to help!

Good luck with the coding and happy avocoding! PS big Avocode update is comming soon!
