### ISSUE TITLE
"Color Value" Variables disable inspector

### ISSUE THREAD

**Issue by richardarosenthal** [avocode/avocode#121]
Perhaps there is just something I'm not understanding, but when I tried to create a variable with the "color value" checkbox marked, the inspector no longer pulled up the styling information for any of the elements that contained that color.  Unchecking "color value" solved this problem and everything worked fine.  I don't know what the expected result is exactly, but I know that most likely *isn't* it.  

I believe the piece I'm working on to reproduce it is a sketch file.  Restarting, etc. does nothing to solve the problem.

I'm running under windows.

**Comment by petrbrzek** [comment]
Interesting. Do you think it's possible to send us an animated gif or a video for clarification? Thanks.

**Comment by richardarosenthal** [comment]
Well... I'll see what I can do - there are some NDA's to consider, and I'll have to ask the client.

What is the intended behavior of the "color value" checkbox?

**Comment by petrbrzek** [comment]
Let me show it to you:

![var](https://cloud.githubusercontent.com/assets/879564/6047609/16a3d71c-acab-11e4-838b-66b10a54cf41.gif)

So when you checked the checkbox we are 100% sure it's a color and can provide you useful language functions such as `fade-out`.

**Comment by richardarosenthal** [comment]
Ah I know what your bug is now.  If the variable name starts with a $ (which I was doing, not realizing that the type of css was a setting), the system seems to error out.

**Comment by petrbrzek** [comment]
Great! We'll look at it.

**Comment by petrbrzek** [comment]
Should be fixed. Feel free to reopen it.
