### ISSUE TITLE
Avocode crash everytime I open a source file from Sketch

### ISSUE THREAD

**Issue by striky1** [avocode/avocode#1212]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.11.1`

Hi,

i try several times open source file from sketch and everytime after Avocode successfully load 8/8 items (in loadings..) he just say that he is crashed. So, i don't know what i must change to correctly open file.

Regards,

striky..

**Comment by connor-bean** [comment]
Hey @striky1 -

Thanks for the report. Would you be able to send us the original Sketch file to team@avocode.com?

Could you also let us know what OS you're running? 

Please refer to this ticket in your email to team@avocode.com.

Thanks!
Connor, Avocode Support

**Comment by striky1** [comment]
Hi @connor-bean 

nope, i can't. It's secret file from Company under license etc..

I use macOs Sierra v10.12.2.

I hope that it helps.

striky..

**Comment by vojtatranta** [comment]
@striky1 I thought you may use 32bit version of Avocode - that might be responsible for such crashing.

I suppose that other sketch designs work ok, right?

**Comment by striky1** [comment]
Hi,

so, today we are try it again with new file. This one work correctly, but we have still problem with first file. We are reupload this file several times and after third attempt, our graphic designer says that is uploaded. And now, this file works fine. So, you have somewhere problem with uploading files or i don't know what :)

I think, we can close issue, i can't send you file and you don't have error log, so..

Btw. I try update app, but if i click on update, nothing happen. Later, Sierra says security alert about Avocode Helper, so ok, i accept this. In App now i can click on ,,install update" and then? Nothing. App is closed and it's all :)

striky..

**Comment by vojtatranta** [comment]
@striky1 this may be caused by moving `Avocode.app`.

You can download updated build here: https://avocode.com/download

**Comment by striky1** [comment]
@vojtatranta thanks a lot, i go download it.

**Comment by vojtatranta** [comment]
@striky1 and regarding sketch upload issues. 

We are of course aware of bad experience when using Avocode with Sketch and we are right now working on fixing this issue.

So thank you for your patience.

**Comment by striky1** [comment]
@vojtatranta it's ok. Maybe you can add some error codes, etc. which we can send you if app crashed.

Good luck, regards,

striky.
