### ISSUE TITLE
Upload PSD with multiple canvas (artboarts)

### ISSUE THREAD

**Issue by yanotoma** [avocode/avocode#1213]
Hi, 
I'm traying to upload a PSD with multiple canvas (feature from CC 2015, i think). The file size is 65MB. I woul'd like to know if avocode supports this feature in PSD like in Sketch, or maybe is my internet connection.

Thanks

**Comment by vojtatranta** [comment]
@yanotoma so you are trying to say that you are not able to upload this PSD?

**Comment by bolekkerous** [comment]
Hello, @yanotoma !
Unfortunately, we do not support artboards right now, although we plan to support it in the future.

[You can upvote the feature here on our UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9428469-support-photoshop-artboards)

The solution right now is to either split the PSD to multiple files, or just ungroup the artboards and group the screens into groups that you can hide and show inside of Avocode.

Hope it helps!
Best regards,
Bolek, Avocode Team

**Comment by bolekkerous** [comment]
I'll close this issue since it's a duplicate - here's a link to the original issue #374
