### ISSUE TITLE
Problem with layers overlay

### ISSUE THREAD

**Issue by soerson** [avocode/avocode#1214]
Sometimes when I get PSD from designers with multilayers which have overlay different from 'normal' in avocode this overlay shows as 'normal'.

**Comment by connor-bean** [comment]
Hey, @ROBsoer -

Would you be able to send us this PSD to team@avocode.com? Could you also let us know what OS you're running as well as which version of Avocode?

Thanks,
Connor, Avocode Suppor

**Comment by ROBsoer** [comment]
Sorry for delay.
I have sent the PSD to you. 

System info:
Win 10,
Avocode v 2.12.0

**Comment by bolekkerous** [comment]
Hello, Rob!
Thanks for the file, we've received it.

We do support multiple blending modes, however, not all of them.

The blending mode "Divide" you're using in the file is currently not supported. When the layer has a not supported blending mode applied, you can see a warning next to the type of layer at the top of the right panel.

<img width="271" alt="screenshot 2016-12-19 15 55 43" src="https://cloud.githubusercontent.com/assets/16084852/21317763/d1c15738-c606-11e6-9088-01276c2af527.png">

We'll keep this issue opened as a "enhancement" until we support the blending mode "Divide".

Hope it helps at least a little!
Best regards,
Bolek, Avocode Team

**Comment by ROBsoer** [comment]
Thanks for your fast answers.
I have not noticed this label before.

It is possible to see full list of blend modes which are not supported?

**Comment by bolekkerous** [comment]
Here's a list of the blend modes we do support on layers right now:

https://avocode.zendesk.com/hc/en-us/articles/202188451-Which-blending-modes-does-Avocode-support-
