### ISSUE TITLE
Export full image

### ISSUE THREAD

**Issue by fwust** [avocode/avocode#1218]
Is there any possibility to add an option to export a full image. By full image, I mean not just the image with the size of the mask but full sized image ?

**Comment by bolekkerous** [comment]
Hello, @fwust !
Right now, that is not possible, unless the image is nested in smart object from Photoshop or in symbol from Sketch.

We're looking into ways how to enable this possibility in the future, so stay tuned!

In the meanwhile, you can upvote it on our UserVoice and leave a comment there, so we know what to prioritize:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/14576004-export-bitmap-images-2x-3x-4x

Hope it helps a little!
Best regards,
Bolek, Avocode Team

**Comment by rodnem** [comment]
Ok that's a solution...
we will proceed like you suggest, by using symbols to keep the original sizes of the assets – thanks
