### ISSUE TITLE
Opacity warning option

### ISSUE THREAD

**Issue by richardarosenthal** [avocode/avocode#122]
I'm not 100% on the best implementation of this, but something that gives a little warning/notification that the object you have selected has an opacity value would be very helpful.  There have been multiple occasions when the designer I was working with had slightly adjusted the opacity of an object, in a way that was not immediately apparent.  Not only did I miss that the object was meant to be translucent, but it also changed the intended background color.  A simple use of the dropper tool corrects this, but you must first know to use it!

**Comment by petrbrzek** [comment]
This sounds like a great use case for an external extension which we'll support in the future.
