### ISSUE TITLE
App failed on startup

### ISSUE THREAD

**Issue by Cactusx09** [avocode/avocode#1220]
This problem happened to me.
I tried different flags like `-- --dev-tools` and `--dev-tools` but nohing happens, console don't run.
![image](https://cloud.githubusercontent.com/assets/9021479/21356637/1224017a-c6db-11e6-8d48-ab23b3e4dee8.png)

Problem: when i start Avocode it's launch 3 processes in background, but nothing happens.
![image](https://cloud.githubusercontent.com/assets/9021479/21356750/63460cba-c6db-11e6-8867-0b364cbe2dce.png)

**Comment by Cactusx09** [comment]
I tried backup to prev restore point on my OS, problem still yet.

**Comment by vojtatranta** [comment]
Hi @Cactusx09 ,
you have Win 10 64bit I suppose, right?

Does this happen only with `2.12.0`?

**Comment by vojtatranta** [comment]
We made some progress on this issue.

It seems that the file that keeps the window width, height and position is corrupted.

We are releasing `2.12.1` version which may fix it but could you please confirm that if you delete file: `c:\Users\<USER>\AppData\Roaming\Avocode\window-state.json` and restart the app, then the app boots?

**Comment by Cactusx09** [comment]
Hi @vojtatranta,
v2.12.1 fix this bug, thnx

**Comment by vojtatranta** [comment]
@Cactusx09 great! Thank you for testing it!
