### ISSUE TITLE
Generated in style gradient 

### ISSUE THREAD

**Issue by Daweo93** [avocode/avocode#1222]
Generated in style gradient don't have opacity but it should have.

![image](https://cloud.githubusercontent.com/assets/16107111/21390168/bf7b0544-c785-11e6-92b6-3881db3c002d.png)

background-image: linear-gradient(to top, #302024 0%, #320c14 78%, #33060f 100%);

**Comment by renekopcem** [comment]
Thank you for your report! We are tracking this issue and we'll fix it in next release.

**Comment by vojtatranta** [comment]
Should be fixed in `2.13.0`
