### ISSUE TITLE
Poor export image quality

### ISSUE THREAD

**Issue by neonwired** [avocode/avocode#1223]
![avocode](https://cloud.githubusercontent.com/assets/2195203/21424538/7d1d5cba-c811-11e6-8cc1-36f97b44ede6.JPG)

As you can see when comparing the image that should be exported on the right to the actual image, the quality is awful, it's badly losing colour depth.

**Comment by petrbrzek** [comment]
It looks like some sort of rendering issue. Would you be willing to send us the design so we can inspect it? If yes, send it to petr@avocode.com.

**Comment by connor-bean** [comment]
Hey @neonwired - 

Could you send this design to petr@avocode.com? Please reference this ticket in your email.

Thanks,
Connor, Avocode Support

**Comment by varisvitols** [comment]
I can also agree to @neonwired - JPG export quality is not exactly top-notch. Color loss is visible to trained eye quite often. I am forced to get back to Photoshop to get decent jpg exports. This happens on multiple different psd files. I urge development team to look into this issue. I expect all jpg exports to look at least as good as Photoshop's "Save for web" 80% quality. It would be best if it was possible to choose export quality in a similar way it is done in Photoshop.

**Comment by connor-bean** [comment]
Hey @varisvitols -

Can you send us one of the problematic designs to team@avocode.com? Please reference this ticket in your email.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @varisvitols -

Can you send us one of the problematic designs to team@avocode.com? Please reference this ticket in your email.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey @varisvitols and @neonwired  -

Without the problematic designs, we cannot troubleshoot further. Please send the designs to team@avocode.com and reference this ticket in your email. Please comment on this ticket once you've sent it and I will reopen it.

Thanks,
Connor, Avocode Support
