### ISSUE TITLE
Error when trying to create a note

### ISSUE THREAD

**Issue by miguelmich** [avocode/avocode#1224]
![image](https://cloud.githubusercontent.com/assets/662930/21462176/e143349c-c926-11e6-9a06-6e9dd748dfc3.png)

This happened to me today using version 2.12.1

Thanks in advance

**Comment by vojtatranta** [comment]
Hi!

Title says "Error when trying to create a note."

But you are sending a picture of project manager.

Can you please explain exactly what do you mean?

**Comment by miguelmich** [comment]
When I try to create a note it doesn't create the note and when I go back to the project manager I see this error.

**Comment by vojtatranta** [comment]
@miguelmich no error is raised, right?

What about other designs? Do they behave the same?

**Comment by miguelmich** [comment]
No, only that file, I solved that problem deleting the psd file and uploading again

**Comment by vojtatranta** [comment]
Sorry for this issue I have never heard about such problem...

**Comment by miguelmich** [comment]
Well, this happened to me several times, I'm also having problems with the sync function on Linux client but I guess that's another story :)

**Comment by vojtatranta** [comment]
I think that if you send use some of problematic files. We'd tested in on linux too.

However this is first report of this kind.

**Comment by jankuca** [comment]
Can you please provide the complete list of steps which lead to this situation?

Here is how I understand the sequence of events:

1. A design was uploaded using the desktop app (the project manager).
2. The design finished uploading.
3. The design finished processing.
4. You opened the design. – Or did you open the design before the upload finished?
5. You added some notes to the design using the Notes tool.
6. You went back to the project manager. – Did you close the design or just switched tabs? How soon after opening the design did you go back to the manager?
7. The tile of the design showed the error.
