### ISSUE TITLE
Sketch page names aren't updating

### ISSUE THREAD

**Issue by kharrop** [avocode/avocode#1225]
I deleted Sketch screens from avocode and uploaded new ones using the plugin. However, when the sync is complete, the page names revert back to what they were previously in the avocode manager.

**Comment by rychlis** [comment]
thanks for the report, we can replicate the issue. A fix should be deployed in a few days, in the meanwhile one way to workaround this is to delete whole sketch file from Avoocde, which is only possible on the https://manager.avocode.com web manager right now. This way the page will get deleted properly and new sync should create new page with the actual name

**Comment by jakubzitny** [comment]
Closing with respect to #1162.
