### ISSUE TITLE
Variables aren't replaced correctly.

### ISSUE THREAD

**Issue by Daweo93** [avocode/avocode#1227]
Hello,
In latest version of avocode I found bug connected with variables. 
As you can see on screenshot variables aren't replace correctly with data.
It's problem with short forms of color ex. #ccc instead of #cccccc
![image](https://cloud.githubusercontent.com/assets/16107111/21604861/e34ea5f0-d1a5-11e6-9043-1956b9cc5368.png)

**Comment by vojtatranta** [comment]
@Daweo93 thank you for this report.

In order for us to debug it we also need to see the way you defined the variable. Can you send us screenshot of the modal where you defined that variable?

**Comment by Daweo93** [comment]
Sure here is a screenshot of the modal. 
![image](https://cloud.githubusercontent.com/assets/16107111/21605058/e79ef898-d1a6-11e6-98cd-6736ac899dc8.png)

When I change #333 to #333333 everything seems to be fine and variable don't have extra 333 on the end. So I think its issue with short versions.

**Comment by vojtatranta** [comment]
@Daweo93 yes I thought so.

But you can fix it easily - if you go to the settings (CMD+, or via menu) and then to code and for particular language you use you click `Advanced settings` then down there is "Hex shorthand" option to display hex color in short form. That would fix it.

**Comment by vojtatranta** [comment]
GL #2701

**Comment by bolekkerous** [comment]
This should be fixed in the latest 2.12.6 update.

If you still have any problems with variables or replacement rules, please create a new issue.

Thanks!
