### ISSUE TITLE
Ability to customise keyboard shortcuts

### ISSUE THREAD

**Issue by callumacrae** [avocode/avocode#1229]
Hey! This is a feature request, hope that is okay here.

On every other app I use, shift+cmd+] moves a tab to the right, and shift+cmd+[ moves to the left. Most apps did this by default, a couple I had to remap to that.

In Avocode, it's ctrl+tab or ctrl+shift+tab.

It would be really neat if you added the ability to customise keyboard shortcuts!

Alternatively, maybe add this specific keyboard shortcut to avocode? Chrome, iTerm, Slack, many text editors all support this same keyboard shortcut—I'm sure I'm not to wish I could do it in Avocode too!

**Comment by connor-bean** [comment]
Thanks for this @callumacrae.

I have added this use case to our UserVoice forum here:
https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7513957-keyboard-shortcuts-for-moving-the-canvas

Please upvote for that feature in UserVoice.

Thanks!
Connor, Avocode Support
