### ISSUE TITLE
I can't open project on my Windows 8 desktop

### ISSUE THREAD

**Issue by zonov** [avocode/avocode#123]
All works fine on my old Windows 7 computer at home, but every try to open any part of project on Windows 8 are failed with never ending loading process. I can share project to you if you need it.

**Comment by Rad1calDreamer** [comment]
>> with never ending loading process.
what a size of file?

**Comment by zonov** [comment]
Where I can see it. I do not make sketch project by myself. It was created by my friend. He imported project into avocode and then shared it for me.

**Comment by Rad1calDreamer** [comment]
hm..i load psd 28mb and have same problem. in project manager it's show, but when i try open it in app i have 
>with never ending loading process.

**Comment by zonov** [comment]
I have read there https://medium.com/avocode-stories/avocode-1-0-released-481d86e2d06e that in version 1 was added something about GPU acceleration. I remember that because that project didn't open even under Ubuntu that I install to find out my problem connection with OS version. And I know that my on-board video card hasn't official drivers for Windows 8 for sure and maybe for Ubuntu too. 

This is wild guess but I haven't other meaningful explanation.

**Comment by tomashanacek** [comment]
Hi, thank you for reporting the issue, could you share us the problematic design to support@avocode.com?

**Comment by zonov** [comment]
I should to close this issue because of wrong formulation of problem. We find out that problem was caused by my internet provider. I do not know why but problem with opening that design reproduced only in a network in my office. We use here mobile 4G router from http://en.mts.ru/. If I use vpn to sync project into Avocode that all works fine, if I use bare connection that I can't open almost any part of a project. And of course I'll send you that design. It can be usefull in your future tests if you have plans to check my report.
