### ISSUE TITLE
Floating point errors in exported SVGs

### ISSUE THREAD

**Issue by callumacrae** [avocode/avocode#1230]
When exporting SVGs using avocode, I get values like this:

```
d="M561.28 452C549.53 452 538.48 447.42 530.17 439.11C528.61 437.55 528.61 435.02000000000004 530.17 433.46000000000004C531.7299999999999 431.89000000000004 534.27 431.89000000000004 535.8299999999999 433.46000000000004C542.6299999999999 440.26000000000005 551.67 444.00000000000006 561.28 444.00000000000006C581.14 444.00000000000006 597.28 427.8500000000001 597.28 408.00000000000006C597.28 405.7900000000001 599.0799999999999 404.00000000000006 601.28 404.00000000000006C603.49 404.00000000000006 605.28 405.7900000000001 605.28 408.00000000000006C605.28 432.26000000000005 585.55 452.00000000000006 561.28 452.00000000000006 "
```

(eg `433.46000000000004`)

They look like floating point errors to me: would it be possible to get rid of them? It's pretty dramatically increasing the size of exported SVGs.

Looks like it is trying to round to two decimal places, and then writing to string: better to handle the decimal places when writing to string? `.toFixed(2).replace(/(\.0)?0$/, '')` should do the trick (looking at your repos, looks like you're using react + electron?)

<sub>previous code public domain</sub>

**Comment by connor-bean** [comment]
Hey @callumacrae -

Thanks for the report. This is definitely relevant to us and we are going to look into a solution to implement this solution. 

Thanks,
Connor, Avocode Support

**Comment by bolekkerous** [comment]
SVG images should be optimized since 2.13.
