### ISSUE TITLE
Can't connect to my account

### ISSUE THREAD

**Issue by SamyBounouar** [avocode/avocode#1232]
Hi, 
I can't connect to avocode in the desktop app, but i've got no problem to connect through the website. 
I enter email and password and nothing happen.
Can you help me ?

I work behind a corporate proxy, may that's a matter ?

**Comment by connor-bean** [comment]
Hey @SamyBounouar -

If you're behind a corporate proxy, here is a guide to properly set it up in Avocode:

https://avocode.zendesk.com/hc/en-us/articles/203402352-How-to-use-a-proxy-server

Also, this another article may help - those are domains we are using and which may be needed to be whitelisted on your side if you are under restrictive proxy or firewall:

https://avocode.zendesk.com/hc/en-us/articles/205022361-Used-domains-to-whitelist

Please let me know how it goes once you've had a chance to whitelist the domains.

Best regards,
Connor, Avocode Team

**Comment by SamyBounouar** [comment]
Thank you Connor, It works great !
