### ISSUE TITLE
Exporting doesn't apply Photoshop bitmap masks

### ISSUE THREAD

**Issue by Legys** [avocode/avocode#1236]
When i trying to export SVG layers, i got this. 
![image](https://cloud.githubusercontent.com/assets/14238528/21940405/d4ad0cd8-d9cc-11e6-830f-94733a196ef5.png)

[Single Page Website Template PSD - cssauthor.com.zip](https://github.com/avocode/avocode/files/704995/Single.Page.Website.Template.PSD.-.cssauthor.com.zip)

**Comment by rychlis** [comment]
Hey thanks for the report! The export tool doesn't properly apply photoshop bitmap mask at the moment unfortunately. We are currently working on implementing this feature but it might take a month or two

In the meantime if you or your designer can use clipping masks instead if you can

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
