### ISSUE TITLE
Keep project manager tab open when opening designs

### ISSUE THREAD

**Issue by miguelmich** [avocode/avocode#1237]
In the last version (2.12.3) when you open a design the Project Manager tab closes and then you need to:
1. Click "+" button
2. Navigate to the desired project again
3. Open another design
4. Repeat this process if you want to open another design

I liked how it was working in previous versions because that way I keep one project opened and opens multiple designs focusing on my active project :)

**Comment by petrbrzek** [comment]
Thanks for the feedback. We plan to release 2.12.4 on Monday where we revert design opening to the previous behavior.

**Comment by miguelmich** [comment]
Thanks a lot!

**Comment by vojtatranta** [comment]
But until we release it, you can hold ctrl/cmd while double clicking a design to open it on a new tab and you get the same result as before.

**Comment by vojtatranta** [comment]
`2.12.4` is deployed, let us know, whether it fixed this issue, thank you for your patience!

**Comment by glutaminefree** [comment]
In version 2.13.1 on Fedora 24 x86_64 this "bug" return again. I have project with 78 designs, and when I click on one, it opens in same tab. And I need open new tab, open project, and scroll over all of this previews to find what I need. I'm scroll designs and cry T_T

**Comment by vojtatranta** [comment]
We wanted ti unify behavior between the web and the app. That's why we changed it.

If you just want to look on the while design quickly, just select it and hit space and preview window will pop up.

If you want to open a desing on a new tab just doubleclick + holding cmd / ctrl

**Comment by glutaminefree** [comment]
Ok, thanks!

**Comment by vojtatranta** [comment]
And we will be doing major uodates in Project Manager in the comming weeks. For examples subfolders etc. and it should make the experience much better, you wont have to scroll thaht much.

You can noe even use search (ctrl+f) to search fora design regardless the project where it is assigned into.

**Comment by glutaminefree** [comment]
I've got it! Thanks for hints :)
