### ISSUE TITLE
Issue while app was not used.

### ISSUE THREAD

**Issue by lazarkov** [avocode/avocode#1238]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.0`
Avocode UID: 103909
```
TypeError: _jp.at0rxrq is not a function
    at https://manager.avocode.com/sockjs/sock/747/kewtu4dx/jsonp?c=_jp.at0rxrq:1:5
```

**Comment by petrbrzek** [comment]
@lazarkov I've fixed this issue in 2.12.1. So please just update your app and it should be fine.
