### ISSUE TITLE
Breadcrumb doesn't work correctly 

### ISSUE THREAD

**Issue by SotirisValogiannis** [avocode/avocode#1240]
When I have opened a design and click the name of the folder that includes the design, it goes to "All projects" screen instead of the particular project.

Avocode 2.12.4
MacOS Sierra 10.12.1

**Comment by vojtatranta** [comment]
Hi,
This is a known issue. This will be fixed in the next minor release.

**Comment by vojtatranta** [comment]
this is fixed in `2.12.5`

**Comment by vojtatranta** [comment]
Noo, sorry, this will be fixed in `2.13.0` (end of Feb.)

**Comment by vojtatranta** [comment]
Should be fixed in `2.13.0`
