### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MaxLutsenko** [avocode/avocode#1242]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 109201
```
TypeError: _jp.afmhb3n is not a function
    at https://manager.avocode.com/sockjs/sock/804/r3sgh0xg/jsonp?c=_jp.afmhb3n:1:5
```

**Comment by vojtatranta** [comment]
Hi @MaxLutsenko,
please update to the latest version `2.12.4`.

**Comment by connor-bean** [comment]
Hey @MaxLutsenko -

Are you still having this problem in 2.12.4?

Thanks,
Connor, Avocode Support
