### ISSUE TITLE
Not sure how it happened

### ISSUE THREAD

**Issue by asimkco** [avocode/avocode#1243]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.0`
Avocode UID: 100967
```
TypeError: _jp.akcaeer is not a function
    at https://manager.avocode.com/sockjs/sock/606/ko5to1lx/jsonp?c=_jp.akcaeer:1:5
```

**Comment by petrbrzek** [comment]
@asimkco This has been fixed in 2.12.1. Please update the app.
