### ISSUE TITLE
Avocode Crash

### ISSUE THREAD

**Issue by AtomRock** [avocode/avocode#1245]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 46464
```
TypeError: _jp.aj1mmm1 is not a function
    at https://manager.avocode.com/sockjs/sock/503/40e1wzyg/jsonp?c=_jp.aj1mmm1:1:5
```

Left it on and it crashed when I returned

**Comment by vojtatranta** [comment]
This is duplicated.
#1242 tracking will continue there - also please update your app, it should wix this error.
