### ISSUE TITLE
App preferences are not saved

### ISSUE THREAD

**Issue by ybentz** [avocode/avocode#1246]
My company uses Stylus and it's really nice to have the style code written in Stylus on Avocode for easy copy and pasting from your app. Unfortunately (at least on the mac app) every single time I open a design I need to set the settings back to Stylus even though I'm setting it on the app preferences, not just the designs'.

**Comment by vojtatranta** [comment]
Hi @ybentz,
that seems like a bug, template settings are store per design and should not disappear when you log out. You can check you `state.json` on `windows` it is in the `C://Users/<user>/.avocode` on the mac `~/.avocode`. Once you quit the app open `state.json` and search for `design_settings` key in there and check it's content at key `active_template`.

Then open the app and open the design where you set this template language if it won't load it seems like a bug to us.

Other user data are loaded properly? If you restart the app you don't wait for project, designs etc.? For example preferences contents are safe? Your proxy settings, UI Font size etc?

P.S.
We know, it is a bit confusing but that dropdown in Preferences -> Code is just a select of what template language you want to edit. It does not influence your "active" template language. The only place where you can change active template language per design is the dropdown under cog bellow code panel in document view in the right panel.

**Comment by connor-bean** [comment]
Hi @ybentz,
that seems like a bug, template settings are store per design and should not disappear when you log out. You can check you state.json on windows it is in the C://Users/<user>/.avocode on the mac ~/.avocode. Once you quit the app open state.json and search for design_settings key in there and check it's content at key active_template.

Then open the app and open the design where you set this template language if it won't load it seems like a bug to us.

Other user data are loaded properly? If you restart the app you don't wait for project, designs etc.? For example preferences contents are safe? Your proxy settings, UI Font size etc?

P.S.
We know, it is a bit confusing but that dropdown in Preferences -> Code is just a select of what template language you want to edit. It does not influence your "active" template language. The only place where you can change active template language per design is the dropdown under cog bellow code panel in document view in the right panel.

**Comment by connor-bean** [comment]
Hey @ybentz -

Please comment if you're able to answer the questions above.

Thanks,
Connor, Avocode Support

**Comment by ybentz** [comment]
Hey @connor-bean, sorry for the delay.

It seems to work fine now, there's been a few updates to the Avocode app so maybe it got fixed?
Since I'm only using Stylus, is there any way to set that as my default so I won't need to set it up for every single design I work on? That would be very convenient.

Thanks!

**Comment by vojtatranta** [comment]
@ybentz like setting your default template language to stylus? Well, we are planning to sync your settings in the future, so we will add it. But for now, your settings are saved on the hard drive of your machine only (and they should persist even after an update if they disappear, it's a bug)
