### ISSUE TITLE
Error on upload new design

### ISSUE THREAD

**Issue by Alexander-smirnov** [avocode/avocode#1247]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 11918
```
TypeError: _jp.aml5dmf is not a function
    at https://manager.avocode.com/sockjs/sock/596/pwcvislo/jsonp?c=_jp.aml5dmf:1:5
```

**Comment by connor-bean** [comment]
Hello @Alexander-smirnov -

Can you update to 2.12.4 and see if you still get this error?

You can download 2.12.4 here: www.manager.avocode.com/downloads

Thanks,
Connor, Avocode Support
