### ISSUE TITLE
Error keep poping up, win10

### ISSUE THREAD

**Issue by srdjanjovanovic** [avocode/avocode#1252]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.0`
Avocode UID: 103909
```
TypeError: _jp.as3qogs is not a function
    at https://manager.avocode.com/sockjs/sock/471/5h4fnpbu/jsonp?c=_jp.as3qogs:1:5
```

**Comment by connor-bean** [comment]
Hey @srdjanjovanovic -

Can you provide us with more information on how this happened? What were you doing when you received the error?

Did this error start when you updated to 2.12.0 or was it happening before that? Could you try updating to 2.12.4 and see it how it goes?

You can download 2.12.4 here: www.manager.avocode.com/downloads

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Since this is related to old version of Avocode I will close this issue.

@srdjanjovanovic please update and let us know if you have any more issues with Avocode.
