### ISSUE TITLE
Unexpected error while browsing through the avocode files.

### ISSUE THREAD

**Issue by HansGerber** [avocode/avocode#1253]
IMPORTANT: Please try to describe how did it happen.
I opened the project I usually worked on and was browsing through the design files when suddenly the error occured. I can't tell what the trigger could be. The only thing important to mention is that I have not installed the latest update yet. Whenever I tried to install it (pressing "install" on the dialog) it closed the dialog and showed in the top right corner the info that it is downloading the update. While downloading another error just occured. The update never gets downloaded.
-----
App v. `2.11.1`
Avocode UID: 24209
```
TypeError: _jp.amcpvcb is not a function
    at https://manager.avocode.com/sockjs/sock/224/mdeu5tyo/jsonp?c=_jp.amcpvcb:1:5
```

**Comment by vojtatranta** [comment]
Hi,
this should be fixed in `>2.12.0` . So please update your application and reopen when issue persists.
