### ISSUE TITLE
Issue when uploading a design.

### ISSUE THREAD

**Issue by AlexandruDoda** [avocode/avocode#1254]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.0-community-beta.1`
Avocode UID: 651
```
TypeError: _jp.aft2gpa is not a function
    at https://manager.avocode.com/sockjs/sock/748/zfynnlon/jsonp?c=_jp.aft2gpa:1:5
```

**Comment by jakubzitny** [comment]
Hi, you have the old version of our app. Please update to the latest, you can download it from [manager.avocode.com/downloads](https://manager.avocode.com/downloads/).

Let us know if you have any more issues with Avocode.
