### ISSUE TITLE
Account renewal notification is obstructive

### ISSUE THREAD

**Issue by tbirrell** [avocode/avocode#1257]
I am very helpfully notified that I have "A YEAR REMAINING" in the upper right-hand corner of Avocode, however, this information is not really necessary (a month or two, maybe, but not a year), and serves to artificially truncate the open tabs. Please remove it, at least when there is so much time before I need to think about renewing.

![image](https://cloud.githubusercontent.com/assets/17275888/22226631/d806d31a-e18c-11e6-8cdc-51f6f46ac6ad.png)

Ubuntu Gnome 16.04
Avocode 2.12.0

**Comment by connor-bean** [comment]
Hey @tbirrell 

Thanks for the feedback. I can see what you're talking about and will pass it along to our product team.

Thanks,
Connor, Avocode Support

**Comment by vojtatranta** [comment]
This is fixed from `2.12.5`, please update to this version.
