### ISSUE TITLE
during listing down list of old scatches

### ISSUE THREAD

**Issue by EG5h** [avocode/avocode#1258]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.0`
Avocode UID: 16855
```
TypeError: _jp.aay5tx1 is not a function
    at https://manager.avocode.com/sockjs/sock/543/2gboesec/jsonp?c=_jp.aay5tx1:1:5
```

**Comment by vojtatranta** [comment]
Hi, this bug is fixed in `>2.12.0` so please update your app to latest `2.12.4`.

Reopen this issue when problem persists.
