### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vb0iko** [avocode/avocode#1259]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 117815
```
TypeError: _jp.a1gi1f5 is not a function
    at https://manager.avocode.com/sockjs/sock/426/ds00pcoc/jsonp?c=_jp.a1gi1f5:1:5
```

**Comment by vojtatranta** [comment]
Hello,
this bug is fixed in `>2.12.0` update your application or download newest version here: https://avocode.com/download
