### ISSUE TITLE
font-weight isn't been pulled across from design

### ISSUE THREAD

**Issue by leereichardt** [avocode/avocode#126]
The font weights aren't being pulled across from photoshop. Am I doing something wrong, or is this not yet implemented?

**Comment by leereichardt** [comment]
I've just found out that the font I'm trying to use is a Typekit font and the font itself has a single font weight. i.e., Museo Sans 300, Museo Sans 500, Museo Sans 700, etc, etc.  Font here: https://typekit.com/fonts/museo-sans

**Comment by VPenkov** [comment]
Yeah, that's a common issue, not much they can do about it other than scan the file name of the font which is pretty unreliable.

**Comment by lastMove** [comment]
I am having the same problem
Is that possible to rename those fonts in system?

**Comment by VPenkov** [comment]
I don't think so, most fonts aren't open-source.

**Comment by leereichardt** [comment]
This is me being naive, but can you not real the font weight from the font file data? Or is that not something that's part of it?





Lee

—

**Comment by VPenkov** [comment]
Most of the times you can but there are lots of fonts (Bebas, for example) where this isn't an option. One way would be if the font's filename contains "bold", "semibold", "light", "thin" and similar stuff. That would't actually terribly unreliable.

**Comment by marekhrabe** [comment]
In most cases, we cannot do much about this. We can get info like `bold: true`, but some fonts have different levels of "bold" and we don't exactly know that without knowing everything about every font that exists. For now we are parsing font-weight from postscript name of fonts which usually contain strings @VPenkov suggests ("bold", "semibold", "light", "thin") and we are linking them to common css weights for that particular weight (like 600 for bold etc). It is ok for most of fonts, but of course, there are fonts that just use this differently. We cannot do much more to solve this problem

**Comment by safareli** [comment]
or make so that font weight name is commented in css panel so developer could himself write font-weight so that I don't have to open photoshop to check  what weight is used for the text

**Comment by rychlis** [comment]
yes we should at least put the whole font name in comment, ideally make the css mapping configurable. I am reopening this issue

**Comment by leereichardt** [comment]
Has there been any movement on this at all?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Sorry to keep you waiting for such a long time guys. This issue will be finally fixed in the next release of Avocode — `2.12`. We'll remind you when it's ready.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
