### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Gremov** [avocode/avocode#1260]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.10.1`
Source UID: 117964
```
TypeError: _jp.aobeslt is not a function
    at https://manager.avocode.com/sockjs/sock/780/s2pgqt2y/jsonp?c=_jp.aobeslt:1:5
```

**Comment by vojtatranta** [comment]
This bug is fixed in newer version of the app `>2.12.0` please update your application or download newer version of the build at https://avocode.com/download/
