### ISSUE TITLE
Avocode not showing border of an smart object 

### ISSUE THREAD

**Issue by DishanTD** [avocode/avocode#1262]
Hi ,

Avocode not showing border of an masked smart object . please find the attachments. white border is not showing on avocode. 

hope kindly response from you.

Thanks!
![1](https://cloud.githubusercontent.com/assets/6309020/22327021/2734c780-e3db-11e6-825a-599e83abd603.png)

**Comment by connor-bean** [comment]
Hey @DishanTD -

Can you send us the actual design to team@avocode.com so we can properly troubleshoot this? Can you also let us know what OS and Avocode version you're running?

Thanks,
Connor, Avocode Support

**Comment by DishanTD** [comment]
Hi @connor-bean ,

Thank you very much. I send them to avocode team.

Thanks again :)
Dishan

**Comment by connor-bean** [comment]
Hey @DishanTD -

Thanks for passing this along. I have assigned this to our Rendering team and we will follow up here when we have more information.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
@rychlis - GL 2984

**Comment by DishanTD** [comment]
Hi @connor-bean ,

Any update about this ?

Thanks!
Dishan

**Comment by vojtatranta** [comment]
@DishanTD if you export this whole image, the border is still not there?

**Comment by DishanTD** [comment]
Hi @vojtatranta ,

I just checked export image , yes border is showing on export image.

but if i code html , i am unable to check border sizes , etc.. from avocode. :) 

Thanks!
Dishan

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
