### ISSUE TITLE
Application had 'Unknown error' when opening Symbol in Sketch

### ISSUE THREAD

**Issue by markjohnnightingale** [avocode/avocode#1263]
I opened Sketch symbol from within a Sketch document and received Unknown Error. 

Here is the log : 
-----
App v. `2.12.4`
Avocode UID: 65901
```
TypeError: Cannot read property 'forEach' of undefined
    at o (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:15516)
    at e._getImagesToDownload (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:15799)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:9881
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:31:11177
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by connor-bean** [comment]
Hey thanks for the report. We're currently looking into this and will report back here as soon as we have more information.

Thanks for your patience.

**Comment by connor-bean** [comment]
Can you try again? Please let us know if you still receive an error.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
We believe this was fixed. Our CDN provider had problems yesterday and when we notified them of this error, they fixed it. Please comment here if you're still having trouble.

Thanks,
Connor, Avocode Support
