### ISSUE TITLE
Avocode doesn't export images correctly

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#127]
This is how it looks: https://upx.cz/yqny67man5s0is6egkaicrtym9zqfgapveuo89yz?7UeRiLv8j9qFcv-G3157uPfNWv-Di5CO3WsOOyREqb4.png

This is the exported image: https://upx.cz/qj60vb0wahvcs1ae6f8wr9u5mquy2c79cwx7c6ho?header.png

**Comment by Jaspur** [comment]
:+1:

**Comment by Rad1calDreamer** [comment]
+1

**Comment by rychlis** [comment]
This is same as #72 which is now fixed in Avocode 1.1.0.
