### ISSUE TITLE
Feature request: Ability to grab/copy text input on different symbol instances

### ISSUE THREAD

**Issue by chiefeay** [avocode/avocode#1270]
It's nice that we can open all instances of symbols on the page, but it would be nicer **to be able to grab/copy the text input on each of the symbols used on page**. Right now, what is happening is that when you select the symbol on the page, there is no way to grab/copy the text used on that instance and when you double-click to open/view the symbol, the text goes back to the placeholder used on the symbol. 

Here are screenshots on what I explained above:
![symbol on page](https://cloud.githubusercontent.com/assets/25391446/22381984/9f4e0c98-e478-11e6-99ba-30ad760076f3.png)
![symbol opened from page](https://cloud.githubusercontent.com/assets/25391446/22381985/9f4f4590-e478-11e6-9461-6ebc40bcedce.png)

**Comment by bolekkerous** [comment]
This should be already working now - symbols are now expanded into the main artboard so you can copy the overridden text or you can click through into the master symbol.
