### ISSUE TITLE
Don`t know what happend

### ISSUE THREAD

**Issue by Koniksan** [avocode/avocode#1274]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 119169
```
TypeError: _jp.acqdifr is not a function
    at https://manager.avocode.com/sockjs/sock/901/zb2z2dqe/jsonp?c=_jp.acqdifr:1:5
```

**Comment by Koniksan** [comment]
I don`t know who I am , and you want to tel you how does it happend ?

**Comment by jakubzitny** [comment]
Hey @Koniksan, you are using an old version of Avocode. Please update to the latest, you can download it from [manager.avocode.com/downloads](https://manager.avocode.com/downloads/).

I will close this issue, but do not hesitate to let us know if you have any more problems or issues with Avocode. 😉
