### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by chapaez** [avocode/avocode#1275]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.10.1`
Source UID: 53160
```
TypeError: _jp.ayfasbq is not a function
    at https://manager.avocode.com/sockjs/sock/806/kg1wqm4s/jsonp?c=_jp.ayfasbq:1:5
```

**Comment by jakubzitny** [comment]
Hey @chapaez, you are using an old version of Avocode. Please update to the latest, you can download it from [manager.avocode.com/downloads](https://manager.avocode.com/downloads).

I will close this issue, but do not hesitate to let us know if you have any more problems or issues with Avocode. 😉
