### ISSUE TITLE
error ubunut

### ISSUE THREAD

**Issue by deathliger666** [avocode/avocode#1276]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 89532
```
TypeError: _jp.airnh4c is not a function
    at https://manager.avocode.com/sockjs/sock/549/3cyvm3na/jsonp?c=_jp.airnh4c:1:5
```

**Comment by jakubzitny** [comment]
Hey @chapaez, you are using an old version of Avocode. Please update to the latest, you can download it from [manager.avocode.com/downloads](https://manager.avocode.com/downloads).

I will close this issue, but do not hesitate to let us know if you have any more problems or issues with Avocode. 😉
