### ISSUE TITLE
error throw every 5-10 minutes on ubuntu 16.04

### ISSUE THREAD

**Issue by deathliger666** [avocode/avocode#1277]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 89532
```
TypeError: _jp.avz3usz is not a function
    at https://manager.avocode.com/sockjs/sock/075/ty4x3weu/jsonp?c=_jp.avz3usz:1:5
```

**Comment by jakubzitny** [comment]
Hi @deathliger666, as I mentioned already in #1276 you are using old version of Avocode — `2.11.1`. We have fixed this problem in v12. The latest is `2.12.4` and today we will be releasing another one.

You can download `2.12.4` from [manager.avocode.com/downloads](https://manager.avocode.com/downloads/). The direct links for Linux downloads are:
- [64bit](https://media.avocode.com/download/avocode-app/2.12.4/avocode-app-linux-2.12.4.zip)
- [32bit](https://media.avocode.com/download/avocode-app/2.12.4/avocode-app-linux-ia32-2.12.4.zip).


Please confirm that you are able to work with Avocode after you update to the latest version.

Thanks 😉
