### ISSUE TITLE
tried to install 32 bit

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1279]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.5`
Avocode UID: null
```
No stack trace available
```

**Comment by vojtatranta** [comment]
This happened during auto update or did you downloaded the installer from the web?

**Comment by vojtatranta** [comment]
I noticed that we had bad link on the downloads page which led to zip file no installer itself, but I think it won't be this issue, right?

**Comment by crh225** [comment]
I downloaded from website yesterday

**Comment by vojtatranta** [comment]
have you tried to download fresh `2.12.6`?

**Comment by connor-bean** [comment]
Hello @crh225 -

Were you able to try 2.12.6? You can download it here:

www.manager.avocode.com/downloads.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Please comment if you still had any issues in 2.12.6.
