### ISSUE TITLE
Wrong image dimension during export

### ISSUE THREAD

**Issue by michalpopielnicki** [avocode/avocode#128]
While having selection of 171x171px: http://screencloud.net/v/s8bU 

I get image saved with 542x42px - http://screencloud.net/v/esQo

**Comment by rychlis** [comment]
This might be related to #72 - do you use layer mask here? Please send us the problematic PSD to team@avocode.com if possible

**Comment by michalpopielnicki** [comment]
File sent - it's probablu layer mask issue.

**Comment by rychlis** [comment]
Thanks for the file. Yeah it's the layer mask cropping issue, I am closing this ticket as a duplicate and you can follow the status there - #72 

We should release an update this week with a fix
