### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by DmytroLukianov** [avocode/avocode#1280]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 41929
```
TypeError: _jp.akzh12c is not a function
    at https://manager.avocode.com/sockjs/sock/637/gb1e5gs5/jsonp?c=_jp.akzh12c:1:5
```

**Comment by connor-bean** [comment]
Hello @DmytroLukianov -

Can you update to 2.12.5 and see if you still get this error? You can download it here: www.manager.avocode.com/downloads.

Thanks,
Connor, Avocode Support

**Comment by vojtatranta** [comment]
This issue should be fixed in newer version. I'll close this.
