### ISSUE TITLE
can't contact support through this button

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1281]
![image](https://cloud.githubusercontent.com/assets/19475195/22594704/c1c3aa8c-e9e9-11e6-9741-26764b817a7a.png)

im clicking it from this link: https://avocode.zendesk.com/hc/en-us/categories/200401652-Assets-Specs

**Comment by bolekkerous** [comment]
Hey -
thanks for the report.

We're aware that the help centre is quite outdated and we're just in the process of rebuilding it from the ground up.

We should replace it with the new one in upcoming weeks, so this won't be relevant anymore.

Best regards,
Bolek, Avocode Team

**Comment by bolekkerous** [comment]
I just hotfixed it for the time being before we release the new help centre - now it should open your e-mail client mailto.
