### ISSUE TITLE
website typo

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1282]
![image](https://cloud.githubusercontent.com/assets/19475195/22594796/3c6f6f82-e9ea-11e6-84d3-b25457c0ebcb.png)

https://avocode.zendesk.com/hc/en-us/articles/202031261-Code-export-basics-0-41-

**Comment by bolekkerous** [comment]
Hey -
thanks for the report.

Same here - we're aware that the help centre is quite outdated and we're just in the process of rebuilding it from the ground up.

We should replace it with the new one in upcoming weeks, so this won't be relevant anymore.

Best regards,
Bolek, Avocode Team

**Comment by bolekkerous** [comment]
We'll soon switch to new Help Centre ( https://help.avocode.com/ ), where this is fixed.
