### ISSUE TITLE
64 bit windows installer 2/3/2017

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1283]
IMPORTANT: Please try to describe how did it happen.
can't install the program
-----
App v. `2.12.5`
Avocode UID: 121241
```
No stack trace available
```

**Comment by vojtatranta** [comment]
Thank for this report.  This pops up alright after installer screen disapears?

**Comment by crh225** [comment]
yes

**Comment by vojtatranta** [comment]
But the app is installed and it just did not start right?

**Comment by crh225** [comment]
it installed and works. just threw the error.

**Comment by vojtatranta** [comment]
Thats odd, I will leave this open if someone else has similar issue.

**Comment by jakubzitny** [comment]
Hey @crh225, are you still having problems with this, or is it fixed in latest versions of Avocode?

**Comment by crh225** [comment]
latest version has fixed it
