### ISSUE TITLE
 _jp.akk4yji is not a function

### ISSUE THREAD

**Issue by zif002** [avocode/avocode#1288]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.12.0`
Avocode UID: 123747
```
TypeError: _jp.akk4yji is not a function
    at https://manager.avocode.com/sockjs/sock/561/y03af2yp/jsonp?c=_jp.akk4yji:1:5
```

**Comment by vojtatranta** [comment]
please update to `>2.12.0`. If you run Linux, download the newest version here https://avocode.com/download/
