### ISSUE TITLE
403 Error after Syncing

### ISSUE THREAD

**Issue by danielmarquespt** [avocode/avocode#129]
I'm getting an 403 error every time I sync a file with Sketch.

Im on OSX 10.9.5 using Sketch Extension 1.0.3. Im trying to sync using a Designer account.

**Comment by rychlis** [comment]
Hello,

thanks for your report, could you please send us the URL of page that returns 403 to team@avocode.com so we could investigate the issue further?

**Comment by rychlis** [comment]
Hi, we've not heard from you so far so I'm closing the issue for now. Feel free to reopen after you send us the URL, thanks
