### ISSUE TITLE
Sketch sync plugin won't get past loading screen

### ISSUE THREAD

**Issue by Fueldeborah** [avocode/avocode#1291]
Running on Mac 10.12.3
Sketch version 42 
Plugin Version 42
Also appears I don't have a token file in my plugins folder. 
when I try to run the console repeats the same three errors. 
error	16:52:13.766628 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:52:13.766683 -0500	Sketch	NSURLConnection finished with error - code -1003
error	16:52:14.771021 -0500	Sketch	TIC TCP Conn Failed [14577:0x618003b81d40]: 12:8 Err(-65554)

**Comment by Fueldeborah** [comment]
All messages log

error	16:57:42.591193 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:42.591238 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:43.594037 -0500	Sketch	TIC TCP Conn Start [14885:0x6100033911d0]
default	16:57:43.595249 -0500	Sketch	TIC TCP Conn Event [14885:0x6100033911d0]: 3 Err(-65554)
error	16:57:43.595267 -0500	Sketch	TIC TCP Conn Failed [14885:0x6100033911d0]: 12:8 Err(-65554)
default	16:57:43.595278 -0500	Sketch	TIC TCP Conn Cancel [14885:0x6100033911d0]
default	16:57:43.595294 -0500	Sketch	TIC TCP Conn Destroyed [14885:0x6100033911d0]
default	16:57:43.595462 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:43.595478 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:43.595520 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:44.597604 -0500	Sketch	TIC TCP Conn Start [14886:0x618003b81ee0]
default	16:57:44.598900 -0500	Sketch	TIC TCP Conn Event [14886:0x618003b81ee0]: 3 Err(-65554)
error	16:57:44.598913 -0500	Sketch	TIC TCP Conn Failed [14886:0x618003b81ee0]: 12:8 Err(-65554)
default	16:57:44.598924 -0500	Sketch	TIC TCP Conn Cancel [14886:0x618003b81ee0]
default	16:57:44.598937 -0500	Sketch	TIC TCP Conn Destroyed [14886:0x618003b81ee0]
default	16:57:44.599089 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:44.599104 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:44.599145 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:44.828024 -0500	symptomsd	NDFSM: auto bug capture is administratively OFF, ignoring symptom with key: 421890
default	16:57:45.602122 -0500	Sketch	TIC TCP Conn Start [14887:0x618003b81ee0]
default	16:57:45.603535 -0500	Sketch	TIC TCP Conn Event [14887:0x618003b81ee0]: 3 Err(-65554)
error	16:57:45.603553 -0500	Sketch	TIC TCP Conn Failed [14887:0x618003b81ee0]: 12:8 Err(-65554)
default	16:57:45.603566 -0500	Sketch	TIC TCP Conn Cancel [14887:0x618003b81ee0]
default	16:57:45.603580 -0500	Sketch	TIC TCP Conn Destroyed [14887:0x618003b81ee0]
default	16:57:45.603743 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:45.603759 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:45.603799 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:46.606694 -0500	Sketch	TIC TCP Conn Start [14888:0x60000059bad0]
default	16:57:46.607862 -0500	Sketch	TIC TCP Conn Event [14888:0x60000059bad0]: 3 Err(-65554)
error	16:57:46.607876 -0500	Sketch	TIC TCP Conn Failed [14888:0x60000059bad0]: 12:8 Err(-65554)
default	16:57:46.607887 -0500	Sketch	TIC TCP Conn Cancel [14888:0x60000059bad0]
default	16:57:46.607904 -0500	Sketch	TIC TCP Conn Destroyed [14888:0x60000059bad0]
default	16:57:46.608063 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:46.608078 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:46.608127 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:47.611367 -0500	Sketch	TIC TCP Conn Start [14889:0x608001d800d0]
default	16:57:47.613132 -0500	Sketch	TIC TCP Conn Event [14889:0x608001d800d0]: 3 Err(-65554)
error	16:57:47.613147 -0500	Sketch	TIC TCP Conn Failed [14889:0x608001d800d0]: 12:8 Err(-65554)
default	16:57:47.613160 -0500	Sketch	TIC TCP Conn Cancel [14889:0x608001d800d0]
default	16:57:47.613174 -0500	Sketch	TIC TCP Conn Destroyed [14889:0x608001d800d0]
default	16:57:47.613366 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:47.613391 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:47.613442 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:48.616304 -0500	Sketch	TIC TCP Conn Start [14890:0x618003b82220]
default	16:57:48.617825 -0500	Sketch	TIC TCP Conn Event [14890:0x618003b82220]: 3 Err(-65554)
error	16:57:48.617844 -0500	Sketch	TIC TCP Conn Failed [14890:0x618003b82220]: 12:8 Err(-65554)
default	16:57:48.617862 -0500	Sketch	TIC TCP Conn Cancel [14890:0x618003b82220]
default	16:57:48.617879 -0500	Sketch	TIC TCP Conn Destroyed [14890:0x618003b82220]
default	16:57:48.618052 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:48.618068 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:48.618115 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:49.620764 -0500	Sketch	TIC TCP Conn Start [14891:0x600000598bb0]
default	16:57:49.623384 -0500	Sketch	TIC TCP Conn Event [14891:0x600000598bb0]: 3 Err(-65554)
error	16:57:49.623408 -0500	Sketch	TIC TCP Conn Failed [14891:0x600000598bb0]: 12:8 Err(-65554)
default	16:57:49.623421 -0500	Sketch	TIC TCP Conn Cancel [14891:0x600000598bb0]
default	16:57:49.623438 -0500	Sketch	TIC TCP Conn Destroyed [14891:0x600000598bb0]
default	16:57:49.623635 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:49.623742 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:49.623840 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:50.626501 -0500	Sketch	TIC TCP Conn Start [14892:0x600000598bb0]
default	16:57:50.628103 -0500	Sketch	TIC TCP Conn Event [14892:0x600000598bb0]: 3 Err(-65554)
error	16:57:50.628117 -0500	Sketch	TIC TCP Conn Failed [14892:0x600000598bb0]: 12:8 Err(-65554)
default	16:57:50.628129 -0500	Sketch	TIC TCP Conn Cancel [14892:0x600000598bb0]
default	16:57:50.628144 -0500	Sketch	TIC TCP Conn Destroyed [14892:0x600000598bb0]
default	16:57:50.628710 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:50.628728 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:50.628777 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:50.963012 -0500	CommCenter	#watchdog #I Callback Watchdog: checkin 1254
default	16:57:50.963217 -0500	CommCenter	#watchdog #I Server Watchdog: checkin 1254
default	16:57:51.631874 -0500	Sketch	TIC TCP Conn Start [14893:0x610003180d00]
default	16:57:51.635645 -0500	Sketch	TIC TCP Conn Event [14893:0x610003180d00]: 3 Err(-65554)
error	16:57:51.635768 -0500	Sketch	TIC TCP Conn Failed [14893:0x610003180d00]: 12:8 Err(-65554)
default	16:57:51.635863 -0500	Sketch	TIC TCP Conn Cancel [14893:0x610003180d00]
default	16:57:51.635906 -0500	Sketch	TIC TCP Conn Destroyed [14893:0x610003180d00]
default	16:57:51.636205 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:51.636302 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:51.636358 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:52.638949 -0500	Sketch	0x600009c7e4c0 opened /Users/deborahsauve/Library/Keychains/login.keychain-db: 300428 bytes
default	16:57:52.639100 -0500	Sketch	0x600009c7e4c0 closed /Users/deborahsauve/Library/Keychains/login.keychain-db
default	16:57:52.639181 -0500	Sketch	0x600001e76f80 opened /Library/Keychains/System.keychain: 71004 bytes
default	16:57:52.639234 -0500	Sketch	0x600001e76f80 closed /Library/Keychains/System.keychain
default	16:57:52.639610 -0500	Sketch	TIC TCP Conn Start [14894:0x618003b81ee0]
default	16:57:52.640777 -0500	Sketch	TIC TCP Conn Event [14894:0x618003b81ee0]: 3 Err(-65554)
error	16:57:52.640790 -0500	Sketch	TIC TCP Conn Failed [14894:0x618003b81ee0]: 12:8 Err(-65554)
default	16:57:52.640802 -0500	Sketch	TIC TCP Conn Cancel [14894:0x618003b81ee0]
default	16:57:52.640816 -0500	Sketch	TIC TCP Conn Destroyed [14894:0x618003b81ee0]
default	16:57:52.640969 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:52.640984 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:52.641026 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:52.969743 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.972517 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.972735 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.972903 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.973043 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.973177 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.973296 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.973456 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.973589 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.973730 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.973956 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.974212 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.974380 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.974703 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:52.974904 -0500	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	16:57:53.643898 -0500	Sketch	TIC TCP Conn Start [14895:0x608001d80ea0]
default	16:57:53.645298 -0500	Sketch	TIC TCP Conn Event [14895:0x608001d80ea0]: 3 Err(-65554)
error	16:57:53.645312 -0500	Sketch	TIC TCP Conn Failed [14895:0x608001d80ea0]: 12:8 Err(-65554)
default	16:57:53.645324 -0500	Sketch	TIC TCP Conn Cancel [14895:0x608001d80ea0]
default	16:57:53.645356 -0500	Sketch	TIC TCP Conn Destroyed [14895:0x608001d80ea0]
default	16:57:53.645652 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:53.645685 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:53.645758 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:54.648900 -0500	Sketch	TIC TCP Conn Start [14896:0x610003180d00]
default	16:57:54.661402 -0500	Sketch	TIC TCP Conn Event [14896:0x610003180d00]: 3 Err(-65554)
error	16:57:54.661417 -0500	Sketch	TIC TCP Conn Failed [14896:0x610003180d00]: 12:8 Err(-65554)
default	16:57:54.661429 -0500	Sketch	TIC TCP Conn Cancel [14896:0x610003180d00]
default	16:57:54.661451 -0500	Sketch	TIC TCP Conn Destroyed [14896:0x610003180d00]
default	16:57:54.661641 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:54.661656 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:54.661706 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:55.664695 -0500	Sketch	TIC TCP Conn Start [14897:0x60000059b5f0]
default	16:57:55.666094 -0500	Sketch	TIC TCP Conn Event [14897:0x60000059b5f0]: 3 Err(-65554)
error	16:57:55.666114 -0500	Sketch	TIC TCP Conn Failed [14897:0x60000059b5f0]: 12:8 Err(-65554)
default	16:57:55.666126 -0500	Sketch	TIC TCP Conn Cancel [14897:0x60000059b5f0]
default	16:57:55.666142 -0500	Sketch	TIC TCP Conn Destroyed [14897:0x60000059b5f0]
default	16:57:55.666306 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:55.666321 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:55.666362 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:56.668924 -0500	Sketch	TIC TCP Conn Start [14898:0x608001d800d0]
default	16:57:56.670412 -0500	Sketch	TIC TCP Conn Event [14898:0x608001d800d0]: 3 Err(-65554)
error	16:57:56.670425 -0500	Sketch	TIC TCP Conn Failed [14898:0x608001d800d0]: 12:8 Err(-65554)
default	16:57:56.670439 -0500	Sketch	TIC TCP Conn Cancel [14898:0x608001d800d0]
default	16:57:56.670453 -0500	Sketch	TIC TCP Conn Destroyed [14898:0x608001d800d0]
default	16:57:56.670642 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:56.670661 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:56.670713 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:57.673793 -0500	Sketch	TIC TCP Conn Start [14899:0x618003b81380]
default	16:57:57.675417 -0500	Sketch	TIC TCP Conn Event [14899:0x618003b81380]: 3 Err(-65554)
error	16:57:57.675524 -0500	Sketch	TIC TCP Conn Failed [14899:0x618003b81380]: 12:8 Err(-65554)
default	16:57:57.675635 -0500	Sketch	TIC TCP Conn Cancel [14899:0x618003b81380]
default	16:57:57.675674 -0500	Sketch	TIC TCP Conn Destroyed [14899:0x618003b81380]
default	16:57:57.675878 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:57.675895 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:57.675940 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:58.678001 -0500	Sketch	TIC TCP Conn Start [14900:0x60000059bad0]
default	16:57:58.679444 -0500	Sketch	TIC TCP Conn Event [14900:0x60000059bad0]: 3 Err(-65554)
error	16:57:58.679458 -0500	Sketch	TIC TCP Conn Failed [14900:0x60000059bad0]: 12:8 Err(-65554)
default	16:57:58.679470 -0500	Sketch	TIC TCP Conn Cancel [14900:0x60000059bad0]
default	16:57:58.679482 -0500	Sketch	TIC TCP Conn Destroyed [14900:0x60000059bad0]
default	16:57:58.679697 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:58.679711 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:58.679759 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:59.490739 -0500	useractivityd	-- Demoting self.advertisingProcess to nil (was <private>) and trigger pickNewAdvertisement because the previous advertisingProcess had a current activity.
default	16:57:59.532573 -0500	gamed	GKClientProxy: clientForBundleID:
default	16:57:59.532603 -0500	gamed	GKClientProxy: updateIfRecentlyInstalled
default	16:57:59.533097 -0500	gamed	GKClientProxy: clientForBundleID:
default	16:57:59.533128 -0500	gamed	GKClientProxy: updateIfRecentlyInstalled
default	16:57:59.543554 -0500	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	16:57:59.681767 -0500	Sketch	TIC TCP Conn Start [14901:0x618003b81ee0]
default	16:57:59.683579 -0500	Sketch	TIC TCP Conn Event [14901:0x618003b81ee0]: 3 Err(-65554)
error	16:57:59.683600 -0500	Sketch	TIC TCP Conn Failed [14901:0x618003b81ee0]: 12:8 Err(-65554)
default	16:57:59.683612 -0500	Sketch	TIC TCP Conn Cancel [14901:0x618003b81ee0]
default	16:57:59.683626 -0500	Sketch	TIC TCP Conn Destroyed [14901:0x618003b81ee0]
default	16:57:59.683807 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:57:59.683822 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:57:59.683915 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:57:59.980341 -0500	useractivityd	PICKING: 5473F5CC-444D-4628-BBB3-0D9B9A823198/<private> as the current item-to-advertise.
default	16:57:59.980779 -0500	useractivityd	client process changing types to scan for to None
default	16:57:59.983173 -0500	sharingd	Skipping request for state: PoweredOn, shouldStart: YES, scanForCopyPaste: NO, scanForHandoff: NO
default	16:58:00.685666 -0500	Sketch	TIC TCP Conn Start [14902:0x618003b81ee0]
default	16:58:00.687063 -0500	Sketch	TIC TCP Conn Event [14902:0x618003b81ee0]: 3 Err(-65554)
error	16:58:00.687077 -0500	Sketch	TIC TCP Conn Failed [14902:0x618003b81ee0]: 12:8 Err(-65554)
default	16:58:00.687090 -0500	Sketch	TIC TCP Conn Cancel [14902:0x618003b81ee0]
default	16:58:00.687104 -0500	Sketch	TIC TCP Conn Destroyed [14902:0x618003b81ee0]
default	16:58:00.687264 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:58:00.687280 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:58:00.687321 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:58:01.689551 -0500	Sketch	TIC TCP Conn Start [14903:0x618003b81ee0]
default	16:58:01.692360 -0500	Sketch	TIC TCP Conn Event [14903:0x618003b81ee0]: 3 Err(-65554)
error	16:58:01.692376 -0500	Sketch	TIC TCP Conn Failed [14903:0x618003b81ee0]: 12:8 Err(-65554)
default	16:58:01.692393 -0500	Sketch	TIC TCP Conn Cancel [14903:0x618003b81ee0]
default	16:58:01.692409 -0500	Sketch	TIC TCP Conn Destroyed [14903:0x618003b81ee0]
default	16:58:01.692595 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:58:01.692611 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:58:01.692652 -0500	Sketch	NSURLConnection finished with error - code -1003
default	16:58:02.695525 -0500	Sketch	TIC TCP Conn Start [14904:0x6100033911d0]
default	16:58:02.696620 -0500	Sketch	TIC TCP Conn Event [14904:0x6100033911d0]: 3 Err(-65554)
error	16:58:02.696633 -0500	Sketch	TIC TCP Conn Failed [14904:0x6100033911d0]: 12:8 Err(-65554)
default	16:58:02.696645 -0500	Sketch	TIC TCP Conn Cancel [14904:0x6100033911d0]
default	16:58:02.696659 -0500	Sketch	TIC TCP Conn Destroyed [14904:0x6100033911d0]
default	16:58:02.696819 -0500	Sketch	_CFNetworkIsConnectedToInternet returning 1, flagsValid: 1, flags: 0x2
error	16:58:02.696834 -0500	Sketch	HTTP load failed (error code: -1003 [12:8])
error	16:58:02.696875 -0500	Sketch	NSURLConnection finished with error - code -1003

**Comment by Fueldeborah** [comment]
Issue has migrated to laptop, that was not updated.

**Comment by bolekkerous** [comment]
This looks like a DNS problem.

There are 3 possible things that you could try:
1. Try opening up https://sourcelocalhost.com:33162 in browser while the plugin screen is loading (it's where the plugin lives), maybe it will work in the browser if the error is isolated to Sketch. 
2. Try Google DNS if possible
3. Add the DNS entry 127.0.0.1 sourcelocalhost.com to /etc/hosts manually

Here's an article explaining more about the host file:
http://www.imore.com/how-edit-your-macs-hosts-file-and-why-you-would-want

Please let us know the result.

**Comment by bolekkerous** [comment]
I'll close this issue as inactive - please follow the steps above to deal with this DNS issue.

If these doesn't help, please comment here and we'll reopen the issue.
