### ISSUE TITLE
error with open

### ISSUE THREAD

**Issue by zif002** [avocode/avocode#1292]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 69327
```
TypeError: _jp.ansohu2 is not a function
    at https://manager.avocode.com/sockjs/sock/879/lvsmo2u4/jsonp?c=_jp.ansohu2:1:5
```

**Comment by vojtatranta** [comment]
Hello, this is a fixed, pleases update your app or download new binary https://avocode.com/download/
