### ISSUE TITLE
Add folder to project

### ISSUE THREAD

**Issue by igumenov** [avocode/avocode#1293]
When I load the design I have 3 files(990, 768, 320). It would be a good group to a folder...
-Project
--Index page
---index_320
---index_786
---index_990

**Comment by connor-bean** [comment]
Hey @igumenov -

Thanks for this. We are currently working on a better way to organize the files within Avocode so it's good timing that you suggested this structure as a possible solution.

Thanks!
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Subfolders are already implemented in Avocode v3.
