### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by epsimatic** [avocode/avocode#1294]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 107857
```
TypeError: _jp.avnf5ia is not a function
    at https://manager.avocode.com/sockjs/sock/508/evk4i2fb/jsonp?c=_jp.avnf5ia:1:5
```

**Comment by vojtatranta** [comment]
Hello @epsimatic , this is fixed newer releases, please update your app or download binary here: https://avocode.com/download
