### ISSUE TITLE
A ton of issues while exporting to PNG

### ISSUE THREAD

**Issue by impeka** [avocode/avocode#1295]
Whenever we try to export a group of images we get black squares. We also can't always export the full image as the selection ignores bordering details (such as shadows).

These are kind of frustrating because we have to keep going back to our designer and asking for him to send us so sliced up images. Hopefully these screens can help you debug, feel free to ask for which project these are for.
![exporting-issues-1](https://cloud.githubusercontent.com/assets/25851562/23079261/2bafc468-f51a-11e6-9eed-95649028768a.png)
![exporting-issues-2](https://cloud.githubusercontent.com/assets/25851562/23079308/5ce705a0-f51a-11e6-8a63-1263b050138d.png)

Attached some screens below.

**Comment by jankuca** [comment]
Hi, we are sorry to hear about these issues.

Can you specify which version of the Avocode app are you running? Also, would you be willing to send us the problematic PSD/Sketch file to team@avocode.com?

**Comment by impeka** [comment]
Hi Jan,

The version we are using is 2.12.6. I have sent an email to team@avocode.com

Thank you,

[image: Impeka]

Sébastien Sanche

CO-FOUNDER

T. 613.203.5499

E. sebastien.sanche@impeka.com

**Comment by NoowPT** [comment]
Having the same issues. Using the same version

**Comment by vojtatranta** [comment]
Please, can you send us those problematic designs at team@avocode.com? Thanks

**Comment by connor-bean** [comment]
Hey @impeka and @NoowPT -

Can you send these problematic designs to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by bolekkerous** [comment]
We received the designs and added the issues to our bug-tracking system.

We'll close the issue once it is fixed.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team

**Comment by impeka** [comment]
## Votre ticket a été créé. ##


Ticket subject: Re: [avocode/avocode] A ton of issues while exporting to PNG (#1295)


----
Auteur: Bolek 
Date: Wed, 02/07/18 7:49 am
Message:
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn&#x27;t, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/avocode/avocode/issues/1295#issuecomment-363811819



Powered by http://www.livechatinc.com?partner=lc_9388770&utm_source=ticket_footer&utm_medium=referral&utm_campaign=lc_9388770

**Comment by impeka** [comment]
## Votre ticket a été créé. ##


Ticket subject: Re: [avocode/avocode] A ton of issues while exporting to PNG (#1295)


----
Auteur: Bolek 
Date: Wed, 02/07/18 3:49 pm
Message:
Closed #1295.

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/avocode/avocode/issues/1295#event-1462657430



Powered by http://www.livechatinc.com?partner=lc_9388770&utm_source=ticket_footer&utm_medium=referral&utm_campaign=lc_9388770
