### ISSUE TITLE
Error everytime I run Avocode

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1297]
IMPORTANT: Please try to describe how did it happen.
All I do is launch Avocode in windows environment. Im surprised nobody else is getting these errors.
-----
App v. `2.12.6`
Avocode UID: 121241
```
No stack trace available
```

**Comment by vojtatranta** [comment]
So you just start the app and this happens? 

I know that it happened when someone installed the app and on the first boot this error popped up?

**Comment by connor-bean** [comment]
So you just start the app and this happens?

I know that it happened when someone installed the app and on the first boot this error popped up?

**Comment by crh225** [comment]
everytime I start the app on windows
![image](https://cloud.githubusercontent.com/assets/19475195/23413714/30222e68-fd9f-11e6-8240-2e4b5fdea02d.png)

**Comment by crh225** [comment]
uninstalled, reinstalled. error magically goes away.
