### ISSUE TITLE
Sorting files in Project manager by name is a bit wrong

### ISSUE THREAD

**Issue by joviczarko** [avocode/avocode#1298]
Instead of now eg.: 1. home, 10. checkout, 11. contact,  2. about , 3. pricing

It should be: 1. home,  2. about , 3. pricing, ..... ,  10. checkout, 11. contact

The sorting algorithm should be aware of this somehow and to sort properly.

**Comment by vojtatranta** [comment]
Thank you @joviczarko we are aware of this. We will work on Project manager in the comming months.

**Comment by t1gu1** [comment]
Exact, you should **parseFloat the number** if it has and **sort** with it **or** add an option sorting. (Sort by number)

**Comment by bolekkerous** [comment]
This should be already implemented.
