### ISSUE TITLE
word-spacing

### ISSUE THREAD

**Issue by yaroslavert** [avocode/avocode#1299]
not word-spacing and letter-spacing

**Comment by bolekkerous** [comment]
Letter spacing is currently supported only for Sketch, however we're planning to support it for Photoshop as well.

Closing this as duplicate, please follow the #793 issue for more info.

You can also upvote this feature request on our UserVoice:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7024976-show-letter-spacing-in-photoshop-documents

**Comment by bolekkerous** [comment]
Letter-spacing property for Photoshop documents should now be available on the web app (https://app.avocode.com/) for all newly uploaded designs into the web app.

It's coming to the desktop app as well in upcoming update, which should be released in 1-2 weeks.
