### ISSUE TITLE
Cannot delete single color from color picker

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#130]
Title says it all. I have the option to "Clear all", but I cannot remove just one color from my palette.

**Comment by rychlis** [comment]
I've created a uservoice idea as this is a feature request, you can vote there as well https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9004435-ability-to-delete-single-picked-color-from-color-p

I think we should be add this soon as it's not that hard to imlement, we will consider this in our next milestone.

**Comment by rychlis** [comment]
We've just released Avocode 2.4.2 which added this feature - just hover over the color and there is a new option to delete the single color
