### ISSUE TITLE
Request/question: subfolders

### ISSUE THREAD

**Issue by smehlikFilip** [avocode/avocode#1300]
Is it possible to create subfolders in Project folder? It would be really useful in cases you have tons of psds to sort them like: mobile designs, tablet designs, desktop designs. Be it subfolders or just some tags which will allow sorting. Maybe I am just blind and cant see it, if its already there. 
Thanx :)

**Comment by bolekkerous** [comment]
Hey, @smehlikFilip -
it currently is not possible, but it's something we're already working on. You can anticipate some organizational features in the upcoming updates. 🙂

I'll close this issue as duplicate, you can see the progress in the original issue: #1293

**Comment by smehlikFilip** [comment]
Great, thanx. I should read through the issues first before creating new one, sorry.

**Comment by bolekkerous** [comment]
No worries at all. 🙂

You can also use our UserVoice for feature voting:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/11122440-improve-project-files-organization
