### ISSUE TITLE
IMPORTANT: _jp.az0pd3e is not a function

### ISSUE THREAD

**Issue by Fiques** [avocode/avocode#1303]
Please try to describe how did it happen.

-----
App v. `2.11.1`
Avocode UID: 30634
```
TypeError: _jp.az0pd3e is not a function
    at https://manager.avocode.com/sockjs/sock/265/pnqo423l/jsonp?c=_jp.az0pd3e:1:5
```

**Comment by connor-bean** [comment]
Hey @Fiques -

It looks like you're using an old version of Avocode. Can you update to 2.12.6 and let us know if you still get this problem?

You can download it here: www.manager.avocode.com/downloads

Thanks,
Connor, Avocode Support

**Comment by vojtatranta** [comment]
please comment when this occurs again with the newer versions

**Comment by Fiques** [comment]
I don't have any problems with the new version. Thanks
