### ISSUE TITLE
Don't export all layers

### ISSUE THREAD

**Issue by sakralbar** [avocode/avocode#1307]
Hello.
Avocode don't export all layers in selected area.
See screenshots below:
![image](https://cloud.githubusercontent.com/assets/11180735/23507519/86601b44-ff5e-11e6-9c5c-7be5b4f875cb.png)
![image](https://cloud.githubusercontent.com/assets/11180735/23507554/b4d8c46c-ff5e-11e6-855d-8b31c54367e1.png)
There is no circles in the exported image.

Avocode 2.12.6 fof linux.

Here is problem psd-template  https://yadi.sk/i/ONJ96qqT3EtiSY

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
