### ISSUE TITLE
Hotkeys work in dialog windows

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#131]
When I open a dialog (i.e. "Add variable") and type something, the hotkeys for the main window as well.

For example, try pressing "i" and "v" repeatedly while the "Replaced text" field is on focus. Avocode will then toggle between the select and the color picker tools.

**Comment by VPenkov** [comment]
In the current version, the same thing happens when messing with the side panels, i.e. when creating an export rule. So when I want to name an image to "something", I can't, because "S" triggers the slice tool.

**Comment by VPenkov** [comment]
Fixed on Windows. You should test it on Linux and maybe close this.

**Comment by VPenkov** [comment]
Reopened. Still gets bugged when defining export rules and setting a name. When you select two layers and export them, say, merged, try setting "s" as a name.

**Comment by PavelGavlik** [comment]
This should be fixed in 2.2.0. Feel free to reopen this if you run to any problems.
