### ISSUE TITLE
Processing failed when trying to upload a PSD

### ISSUE THREAD

**Issue by McMurphy123** [avocode/avocode#1310]

**Comment by connor-bean** [comment]
Hey @McMurphy123 -

Were you using the Photoshop plugin to upload the PSD? What version of Avocode are you running?

Thanks,
Connor, Avocode Support

**Comment by McMurphy123** [comment]
Photoshop plugins did not use.
Avocode 2.12.6

**Comment by connor-bean** [comment]
Can you try uploading the PSD through the plugin?

You can download it here: www.manager.avocode.com/downloads

Please let us know how it goes once you try to upload using the plugin

**Comment by McMurphy123** [comment]
Sorry, but I don't have a photoshop
