### ISSUE TITLE
No layouts after sync. via sketch plugin

### ISSUE THREAD

**Issue by designglyanec** [avocode/avocode#1311]
![image](https://cloud.githubusercontent.com/assets/26251419/23658172/2692afd4-034a-11e7-8139-642cb206dcc7.png)

I try:
reinstall sketch plugin
reinstall sketch 
sync. on another mac

NOTHING!

**Comment by connor-bean** [comment]
Hello - 

Could you send us one of the problematic designs to team@avocode.com? Could you also let us know what version of Avocode you're running as well as what version of Sketch and Sketch plugin you have?

Another thing that would really help us troubleshoot is to send us the sketch logs as well.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Please comment here if you can send us the problematic designs to team@avocode.com
