### ISSUE TITLE
Beta, open Project

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1312]
Hi guys ! 
its awesome what is now in beta but will be very cool that you open design on new page, not the same

Thx.

**Comment by jakubzitny** [comment]
How about `cmd+click`?

**Comment by vAhyThe** [comment]
@jakubzitny  of course this works.  I mean in default state should behave as app.

**Comment by vojtatranta** [comment]
@vAhyThe we wanted to have it coherent with the desktop app, no surprising behaviour.
