### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by reconstrukt** [avocode/avocode#1315]
-----
App v. `2.11.1`
Avocode UID: 76380
```
TypeError: _jp.agaqcis is not a function
    at https://manager.avocode.com/sockjs/sock/043/3bihtci5/jsonp?c=_jp.agaqcis:1:5
```

**Comment by vojtatranta** [comment]
Hello,
you have an old version of Avocode, please update via autoupdate or download newest build from https://avocode.com/download/
