### ISSUE TITLE
Mouse Position not showing

### ISSUE THREAD

**Issue by whoiskjl** [avocode/avocode#1316]
Mouse position is not being displayed
also the measure tool doesn't display the dimension of select box

![screen shot 2017-03-09 at 10 40 56 am](https://cloud.githubusercontent.com/assets/1874874/23757476/f3120f80-04b4-11e7-9a3e-d8e72d8b2c5b.png)

**Comment by vojtatranta** [comment]
That's on the web, right?

**Comment by bolekkerous** [comment]
This should now be fixed in the web version.

Feel free to let us know in case you encounter this or any issue!
Best regards,
Bolek, Avocode Team
