### ISSUE TITLE
Freezing on Export

### ISSUE THREAD

**Issue by cedarstay** [avocode/avocode#1318]
When attempting to export 2 layers and change from the default png to jpg, once the export is initiated, the application freezes. I am on version 2.12.6 and was able to replicate in the online newer beta version in a chrome browser as well.

**Comment by vojtatranta** [comment]
@cedarstay could you send us URL of the design?

**Comment by jakubzitny** [comment]
Hi @cedarstay, do you still have problems with export in latest version of Avocode?
