### ISSUE TITLE
Can't upload JPG file

### ISSUE THREAD

**Issue by db-portfolio** [avocode/avocode#1320]
![screenshot 2017-03-13 15 16 12](https://cloud.githubusercontent.com/assets/11156404/23877557/14ddf11c-0800-11e7-9b9a-fe5139d67873.png)

**Comment by bolekkerous** [comment]
Hello - 
have you tried reuploading it again, whether it wasn't just some connectivity issue?

If it happens again, could you share the image with us at team@avocode.com?

Thanks!
