### ISSUE TITLE
Open design

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1324]
* **Version**: 2.12.6

* **Native/Web**: Native

* **Platform**:  mac OSX SIerra 10.12.3

When try open design show this

![image](https://cloud.githubusercontent.com/assets/6084353/23947740/640e929c-0980-11e7-9e4b-fb557dd47ef8.png)

**Comment by bolekkerous** [comment]
Hey, @vAhyThe -
could you please send us your Avocode account e-mail and name of the design that fails to open to team@avocode.com?

Thanks!

**Comment by jakubzitny** [comment]
Hi @vAhyThe, do you still have problems with opening the particular design in Avocode?

**Comment by jakubzitny** [comment]
Hi there, this is fixed in latest Avocode `2.15.0`. You can download it from [avocode.com/download](https://avocode.com/download) or use auto-update to install it. Please give it a try and let us know if you have any more issues.
