### ISSUE TITLE
Beta 4 gives unexpected error upon start (error 1/2)

### ISSUE THREAD

**Issue by Vashiru** [avocode/avocode#1325]
IMPORTANT: Please try to describe how did it happen.

When I start Beta 4, I get "An unexpected error has occured" twice at start, with options to dismiss or send report. This is the first one. I had this issue with Beta 1 as well.
-----
App v. `2.13.0-community-beta.4`
Avocode UID: 21082
```
No stack trace available
```

**Comment by Vashiru** [comment]
Also happens on current stable

**Comment by vojtatranta** [comment]
duplicat of #1326
