### ISSUE TITLE
Unexpected error has occured on beta 4 (error 2/2)

### ISSUE THREAD

**Issue by Vashiru** [avocode/avocode#1326]
IMPORTANT: Please try to describe how did it happen.

When I start Beta 4, I get "An unexpected error has occured" twice at start, with options to dismiss or send report. This is the second one. I had this issue with Beta 1 as well.
-----
App v. `2.13.0-community-beta.4`
Avocode UID: 21082
```
No stack trace available
```

**Comment by Vashiru** [comment]
Also happens on current stable

**Comment by vojtatranta** [comment]
@Vashiru in the stsable `2.12.6` too?

**Comment by Vashiru** [comment]
@vojtatranta I have it on the latest 2.12.6 stable as well yes.

Further information (mentioned it scattered across Slack as well but good to list it here):
- Projects won't load before both errors have been cleared
- It's not specific to my machine, developers on my team are also seeing this issue.
- OS X Sierra 10.12.3 on a MacBook Pro (Retina, 15-inch, Mid 2015) for me
- Avocode works fine beyond those errors.

**Comment by vojtatranta** [comment]
@Vashiru we are not able to reproduce it.

Can I kindly ask you to try older versions please? Just start these build and please tell me whic one does not produce error. Thank you soo much!
- https://avocode-media.s3.amazonaws.com/download/avocode-app/2.12.5/avocode-app-mac-2.12.5.zip
- https://avocode-media.s3.amazonaws.com/download/avocode-app/2.12.4/avocode-app-mac-2.12.4.zip
- https://avocode-media.s3.amazonaws.com/download/avocode-app/2.12.2/avocode-app-mac-2.12.2.zip
- https://avocode-media.s3.amazonaws.com/download/avocode-app/2.11.1/avocode-app-mac-2.11.1.zip

**Comment by Vashiru** [comment]
Happens on all of them. As soon as I've dismissed them I get the "Update available" message. Before that only the Avocode logo is visible in the screen

**Comment by vojtatranta** [comment]
@Vashiru huh, that's really strange.

Could you please try `2.9.1`? Thanks! https://avocode-media.s3.amazonaws.com/download/avocode-app/2.9.1/avocode-app-mac-2.9.1.zip

**Comment by Vashiru** [comment]
@vojtatranta Gave it a try, no errors in that version :)

**Comment by vojtatranta** [comment]
Alright,
let me give one last version for you to try out. https://avocode-media.s3.amazonaws.com/download/avocode-app/2.10.1/avocode-app-mac-2.10.1.zip

I am really sorry bothering you with that, if we could reproduce it, it would be great. But unfortunately, we can't :(.

**Comment by Vashiru** [comment]
That one does throw the same 2 errors again. Clicked on send report, but again "no stack trace available".

No problem, happy to help solve the issue. Feel free to send me test versions as you go on solving it and I'll give them a spin.

**Comment by Vashiru** [comment]
Hmm, looks like the issue has been resolved, won't know exactly which version, but on  on 2.13.3 I don't get any errors, nor on 2.13.4. 👍

**Comment by bolekkerous** [comment]
Great, happy to hear that. :)

Thanks for your cooperation, we appreciate it a lot!
