### ISSUE TITLE
Export of embedded document failed

### ISSUE THREAD

**Issue by skaut41** [avocode/avocode#1327]
* **Version**: 2.12.1-w629c591
* **Native/Web**: web
* **Platform**: Ubuntu 14.04 / Chrome 57.0.2987.98 (64-bit)

Hi, I've encounter a bug with exporting an image from embedded document. When I try export image directly from main design file (`.psd`) nothing happens, but when I tried export it from its own file (`.psb` in a new tab) export is fine. Dev Tools show some exceptions though:

* [app.avocode.com-1489682903464.txt](https://github.com/avocode/avocode/files/849951/app.avocode.com-1489682903464.txt)
* [app.avocode.com-1489737228381.txt](https://github.com/avocode/avocode/files/849952/app.avocode.com-1489737228381.txt)

Desktop version can export embedded image from both main `.psd` file and embedded `.psb` file.

**Comment by vojtatranta** [comment]
Taking a look at it now.

**Comment by skaut41** [comment]
Hi, I've just tested it in version 2.13.1, exporting is working fine. Thank you! :+1:
