### ISSUE TITLE
Could not download metadata

### ISSUE THREAD

**Issue by vladimir-shalaev22** [avocode/avocode#1328]
* **Native/Web**: Native

* **Platform**: Linux 64

-----
App v. `2.13.0`
Avocode UID: 132692
```
Error: Could not download metadata (revision=9118813)
    at file:///home/hornet/avocode-2.13.0-linux/resources/app.asar/dist/avocode.min.js:41:24829
```

Hi! I successfully upload my design, but then, when I try to open it, I get an error :(

![issue-1](https://cloud.githubusercontent.com/assets/20970438/24041318/b75bec92-0b47-11e7-9472-ad650c9ac15c.png)
![issue-2](https://cloud.githubusercontent.com/assets/20970438/24041319/b75dba68-0b47-11e7-8547-dcbbed2f4e24.png)

I get the same error even when I open example design

**Comment by vojtatranta** [comment]
Seems like some connection problem - are you not behind some Proxy? Did it work in older versions?

**Comment by vladimir-shalaev22** [comment]
I don't exactly remember version of Avocode, but in November or December 2016 it works fine.
The first error occurred in January this year.
I don't use any Proxy. And I have not problems with internet connection.

**Comment by jakubzitny** [comment]
Hi @vladimir-shalaev22, do you still have problems with this in the latest version of Avocode?

**Comment by vladimir-shalaev22** [comment]
Hi:) I have not tested the latest version yet. I'll try to test today and then report the result14.07.2017, 01:06, "Jakub Žitný" <notifications@github.com>:Hi @vladimir-shalaev22, do you still have problems with this in the latest version of Avocode?

**Comment by vladimir-shalaev22** [comment]
@jakubzitny Tested in the latest version (2.14.6) - everything works perfectly. Close this issue
