### ISSUE TITLE
Failed to install avocode via APT

### ISSUE THREAD

**Issue by skyline94** [avocode/avocode#1329]
* **Version**: 2.13.0

* **Native/Web**: Native

* **Platform**: Ubuntu Linux

Im trying to deal with Avocode installation via apt repository.
After `sudo apt update` I got errors below:
`W:The repository 'http://linux.avocode.com main Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch http://linux.avocode.com/dists/main/all/binary-amd64/Packages  403  Forbidden, E:Some index files failed to download. They have been ignored, or old ones used instead.`

Looks like repo not configured properly. I made all of the steps from "how to" at Avocode site.

**Comment by jakubzitny** [comment]
Hi @skyline94, thanks for reporting this. I am sorry, this is my fault. The repo link in [the documentation](https://help.avocode.com/app-settings/installing-avocode-on-linux) was not correct. Now it's fixed.

Please replace the one you used `http://linux.avocode.com` with `http://linux.avocode.com/apt/`, run `sudo apt update` and let us know if you have any more problems. 🐧 😉

**Comment by skyline94** [comment]
@jakubzitny issue still here :(
`W:The repository 'http://linux.avocode.com/apt main Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch http://linux.avocode.com/apt/dists/main/all/binary-amd64/Packages  403  Forbidden, E:Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by jakubzitny** [comment]
Yeah sorry again 😇 there was another problem on the same line in the `sources.list`. The whole line should be as follows:
```
deb http://linux.avocode.com/apt all main
```

We had the `all` and `main` swapped in the docs. Now it should really be okay. Can you please check again?

**Comment by skyline94** [comment]
@jakubzitny yep, it's ok now) thank you :+1:

**Comment by jakubzitny** [comment]
Thanks a lot @skyline94, sorry for trouble.
