### ISSUE TITLE
Cant find letter-spacing in styles

### ISSUE THREAD

**Issue by maxim1006** [avocode/avocode#1334]
varsion: 2.12.6

native

Windows 7

In styles letter-spacing prop is absent

**Comment by bolekkerous** [comment]
Letter spacing is currently supported only for Sketch, however we're planning to support it for Photoshop as well.

Closing this as duplicate, please follow the #793 issue for more info.

You can also upvote this feature request on our UserVoice:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7024976-show-letter-spacing-in-photoshop-documents

**Comment by bolekkerous** [comment]
Letter-spacing property for Photoshop documents should now be available on the web app (https://app.avocode.com/) for all newly uploaded designs into the web app. 

It's coming to the desktop app as well in upcoming update, which should be released in 1-2 weeks.
