### ISSUE TITLE
App crash for windows-10

### ISSUE THREAD

**Issue by vijayakumarGit** [avocode/avocode#1335]
I try to login after login app would crash it happen all time in windows 10 system kindly fix this issue ASP

App v. `2.11.1`

**Comment by jakubzitny** [comment]
Hi @vijayakumarGit, you're using an old version of Avocode. Please download the latest version `2.13.0` from [manager.avocode.com/downloads](http://manager.avocode.com/downloads/) and let us know if you have any more problems.
