### ISSUE TITLE
Intercom 'id' of undefined

### ISSUE THREAD

**Issue by kolundzija** [avocode/avocode#1338]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.0`
Avocode UID: 16313
```
TypeError: Cannot read property 'id' of undefined
    at p (https://js.intercomcdn.com/frame.82487f3e.js:1:24870)
    at c (https://js.intercomcdn.com/frame.82487f3e.js:5:17723)
    at https://js.intercomcdn.com/frame.82487f3e.js:5:18024
    at Array.map (native)
    at https://js.intercomcdn.com/frame.82487f3e.js:5:18001
    at https://js.intercomcdn.com/frame.82487f3e.js:2:22592
    at https://js.intercomcdn.com/frame.82487f3e.js:2:22028
    at p (https://js.intercomcdn.com/frame.82487f3e.js:2:22797)
    at https://js.intercomcdn.com/frame.82487f3e.js:2:22756
    at Array.map (native)
    at p (https://js.intercomcdn.com/frame.82487f3e.js:2:22731)
    at Array.<anonymous> (https://js.intercomcdn.com/frame.82487f3e.js:18:2332)
    at l (https://js.intercomcdn.com/frame.82487f3e.js:9:14700)
    at https://js.intercomcdn.com/frame.82487f3e.js:18:450
    at https://js.intercomcdn.com/frame.82487f3e.js:17:24948
    at https://js.intercomcdn.com/frame.82487f3e.js:17:31789
    at https://js.intercomcdn.com/frame.82487f3e.js:17:23420
    at https://js.intercomcdn.com/frame.82487f3e.js:17:31432
    at https://js.intercomcdn.com/frame.82487f3e.js:29:14875
    at onUserPresent (https://js.intercomcdn.com/frame.82487f3e.js:5:15445)
    at HTMLDocument.l (https://js.intercomcdn.com/frame.82487f3e.js:18:3285)
    at HTMLDocument.wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by vojtatranta** [comment]
This should be fixed in `2.13.1` releasing today.

**Comment by jakubzitny** [comment]
Hi @kolundzija, we've not been able to fix this problem yet. We're investigating it right now. It is happening to some users but we are not sure why exactly, so any further details you might have could help us.

We hope the fix should be ready in one of the next releases.

**Comment by jakubzitny** [comment]
This should be fixed in latest version of Avocode, so I'll close this thread. Feel free to open a new issue if you have more problems with Avocode 😉

**Comment by laander** [comment]
@jakubzitny Would you mind sharing how you fixed it? 

I'm not using avocode TBH, but we experienced it in our product and I can't for the life of me figure out why it's happening. Maybe related to the Segment integration?
https://github.com/segment-integrations/analytics.js-integration-intercom/issues/24

**Comment by jakubzitny** [comment]
I think @vojtatranta might know better.

**Comment by vojtatranta** [comment]
@laander try catch....

**Comment by laander** [comment]
@vojtatranta But try-catch _what_? It seems like it's an internal error happening inside the Intercom lib, most likely because it's passed some problematic data, no?

**Comment by bitdivision** [comment]
I'd also be very interested in a fix if @vojtatranta has any more details, or if @laander has since fixed it?

**Comment by vojtatranta** [comment]
@bitdivision I wrapped calls to Intercom in try / catch and hoped that error does not happening asynchronously:
```
try {
      if (params) {
        this._window.Intercom(actionType, params)
      } else {
        this._window.Intercom(actionType)
      }
    } catch (err) {
      if (this._track) {
        this._track.trackError(err, {
          captured: true,
        })
      }
    }
```
