### ISSUE TITLE
apt-get update/upgrade from 2.13.0 to 2.13.1

### ISSUE THREAD

**Issue by p-boiko** [avocode/avocode#1339]
* **Version**: 2.13.1

* **Web/Desktop**: Desktop

* **Platform**: Debian GNU/Linux

After successful upgrade from 2.13.0 to 2.13.1 the app still asks to upgrade: [video](http://pavelb.dev.kim/screenshots/avocode_apt_issue.mp4)

**Comment by jakubzitny** [comment]
Hi @p-boiko, thanks for letting us know. This was our fault and it should be fixed now, can you please try upgrading once again? 🐧

**Comment by p-boiko** [comment]
Ahoj @jakubzitny .
Děkuji, teď opravdu aktualizováno :)
