### ISSUE TITLE
Export images

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#134]
Option to export to a subfolder. 

ex: Root project export path : /static/images/

When we export (CTRL-S), adding an option to export to a subfolder will be nice.

ex: http://i.imgur.com/yJ5NVQT.jpg

**Comment by marekhrabe** [comment]
Can you try putting `subfolder/layer-25.png` in the name? It should work just fine :)

**Comment by polikin** [comment]
Sweet, thanks! ;)
