### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by serzh-f** [avocode/avocode#1342]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.13.1`

**Comment by vojtatranta** [comment]
This error corrured when app booted?

Dne 24. 3. 2017 4:44 odp. napsal uživatel "serzh-f" <
notifications@github.com>:

**Comment by serzh-f** [comment]
Hi. No. Error corrured with big .PSD. Many files don't uploading or don't rendering. I love Avocode (for Linux), but now layouts don't uploading fast (size about 30 - 100mb)

**Comment by vojtatranta** [comment]
100MB should not be a problem. It probably depends on the design. Can you send us these problematic designs at team@avocode.com? Thanks!

**Comment by jakubzitny** [comment]
Hi @serzh-f, do you still have problems with uploading PSDs?

**Comment by jakubzitny** [comment]
Hi @serzh-f, do you still have problems with uploading PSDs?
