### ISSUE TITLE
Export Screen Shot feature for the web version

### ISSUE THREAD

**Issue by whoiskjl** [avocode/avocode#1343]
- Avocode 2.13.1-w43ccea4

* **Version**: 

* **Web/Desktop**:

Web

* **Platform**: 

macOS 10.12.3 

Export Screen Shot feature just like desktop app

**Comment by vojtatranta** [comment]
Do you mean cmd+p to expprt screenshot?

**Comment by whoiskjl** [comment]
@vojtatranta no

**Comment by jakubzitny** [comment]
Hi @whoiskjl, this will included in the next patch release of Avocode 🙂

**Comment by jakubzitny** [comment]
Hi, this should be added in latest Avocode `2.16.2`. Please update and let us know if you find any other problems :wink:

**Comment by whoiskjl** [comment]
Thanks for the 2.16.2 update, I always enjoy Avocode.

What I meant was' Export Screen Shot' feature for the web version, though.   
![screensss](https://user-images.githubusercontent.com/1874874/32289132-472f20d2-bf0c-11e7-9f62-dfcbe5378527.png)

Maybe I'm missing something here :)

**Comment by jakubzitny** [comment]
Yes I know, sorry I didn't tell you where you can find it. It's under the preview in top right corner when you deselect all layers (by pressing escape for example).

**Comment by whoiskjl** [comment]
Found it thank you!
