### ISSUE TITLE
Wrong Avocode repository URL in Avocode.

### ISSUE THREAD

**Issue by skyline94** [avocode/avocode#1344]
* **Version**: 2.13.0

* **Web/Desktop**: Desktop

* **Platform**: Ubuntu Linux

Wrong URL to Avocode repository in instructions to update. Recently I met this issue and it was fixed in documentation, but URL still wrong in program itself. #1329 
<...>
**echo deb http://linux.avocode.com main all >> /etc/apt/sources.list**
<...>
Should be `echo deb http://linux.avocode.com/apt all main >> /etc/apt/sources.list`
[http://imgur.com/a/H0Pny](http://imgur.com/a/H0Pny)

**Comment by jakubzitny** [comment]
Hi @skyline94, thanks a lot for noticing, this is my fault (again). I fixed it for the next Avocode release. You'll still see the incorrect line in `2.13.1` and it should be OK after next upgrade.

Thanks again, I'll keep this open untill we release the next version.

**Comment by jakubzitny** [comment]
This should be fixed in Avocode `2.13.2` we've just released. You should see correct URL for the future releases.

Don't hesitate to let us know if you have any other issues with Avocode. 😉
Thanks.
