### ISSUE TITLE
Horizontal scroll with shift+mouse stopped working

### ISSUE THREAD

**Issue by shitpoet** [avocode/avocode#1345]
* **Version**: 2.13.1 

* **Web/Desktop**: Desktop

* **Platform**: Linux 64-bit (Debian 8 Stable)

In version 2.12 i could scroll a document using Shift + mouse, starting from version 2.13.0 it does not work. Now, Ctrl + mouse zooms the document, but Alt + mouse, Shift + mouse, Alt+Shift (and so on) + mouse - all do vertical scroll.

Is it intended behaviour or bug?

I'm using openbox WM if it does matter.

**Comment by vojtatranta** [comment]
We have never intended having an option to use the mouse to scroll horizontally.

For scrolling we have hand tool, which can be activated temporary by holding `space`. To switch to hand tool press `H`.

**Comment by bolekkerous** [comment]
Just to clarify, @shitpoet  - is this issue about shift + drag with mouse or shift + middle mouse button scrolling?

**Comment by shitpoet** [comment]
@bolekkerous shift + mouse wheel 

i used to it cuz shift + mouse wheel for horizontal scroll also works in many other places, such as browsers, many code editors etc

for me switching to "hand" tool just to scrolll horizontally a little is less convinient

also that `shift + wheel` scroll was strictly horizontal, where "hand" tool moves freely - as far as i now, i never used it before! it is useful sometimes to be able to scroll strictly in one axis not affecting another...
