### ISSUE TITLE
Error when not getting online after suspending device

### ISSUE THREAD

**Issue by kure-** [avocode/avocode#1349]
IMPORTANT: Please try to describe how did it happen.
- basically turned laptop on and wifi did not get connected
- the app returned error
- went online again manually and seems to be fine
-----
App v. `2.13.1`
Avocode UID: 393
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by jakubzitny** [comment]
Hi @kure-, thanks for the report. We've already got some details in #1351, so I'm going to close this thread and we'll update you over there. We're looking into this problem.
