### ISSUE TITLE
Export All Rules

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#135]
Enable option too see all rules.

**Comment by marekhrabe** [comment]
Yes, we need this too. It it scheduled for 1.2 (to be released in a month or so)

**Comment by polikin** [comment]
Coool!

**Comment by rychlis** [comment]
This was implemented long time ago, you can export all rules using cmd/ctrl+shift+e or by selecting the whole document (escape key) and pressing Export All Rules in the Export panel
