### ISSUE TITLE
getaddrinfo ENOTFOUND manager.avocode.com

### ISSUE THREAD

**Issue by morcegon** [avocode/avocode#1351]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.1`
Avocode UID: 17209
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by jakubzitny** [comment]
Hi @morcegon, thanks for reporting this. I've seen this error today as well, we're investigating it right now.

Can you please provide us with more info, what OS are you using, what have you been doing before this happened and did it happen more than once?

Thanks.

**Comment by morcegon** [comment]
Hello @jakubzitny !
I'm using Mac OS Sierra.
It's the first time this happen. The Avocode window was in background, I was in using Chrome
