### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by prajwal78** [avocode/avocode#1356]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.2`
Avocode UID: 126390
```
No stack trace available
```

**Comment by petrbrzek** [comment]
Hello, can you describe us what does it happen? Are you able to launch the desktop app now? @prajwal78

**Comment by prajwal78** [comment]
I ain't able to upload 60+ MB to the platform. Throws me error.

**Comment by petrbrzek** [comment]
@prajwal78 so you are not getting the error when you start the app but when you upload a file?
