### ISSUE TITLE
On startup

### ISSUE THREAD

**Issue by jpm1475** [avocode/avocode#1357]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.2`
Avocode UID: 136157
```
No stack trace available
```

**Comment by petrbrzek** [comment]
@jpm1475 Hello, can you describe us what does it happen? Are you able to launch the desktop app now?

**Comment by jakubzitny** [comment]
Hi @jpm1475, do you still have problems starting the latest version of Avocode?
