### ISSUE TITLE
WHen I opened the app

### ISSUE THREAD

**Issue by jpm1475** [avocode/avocode#1359]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.2`
Avocode UID: 136157
```
No stack trace available
```

![image](https://cloud.githubusercontent.com/assets/23405932/24561026/33d1d9a0-1613-11e7-9759-a9b242e2c593.png)

**Comment by petrbrzek** [comment]
Closing as a duplicate #1357.
