### ISSUE TITLE
On Opening of the app

### ISSUE THREAD

**Issue by jpm1475** [avocode/avocode#1360]
IMPORTANT: Please try to describe how did it happen.
Everytime I open the app I get this error:
![image](https://cloud.githubusercontent.com/assets/23405932/24561105/946d1414-1613-11e7-83cf-f99a7020f7d8.png)

I have been trying to synch from sketch and it tells me on the Sketch side that the artboards were synched, however, they are not showing up
-----
App v. `2.13.2`
Avocode UID: 136157
```
No stack trace available
```

**Comment by petrbrzek** [comment]
@jpm1475 are you able to open the desktop app or are you getting the error every time?

**Comment by jpm1475** [comment]
Every time I open the app I get that error. I click through and the app seems to work fine, but why do I get the error?

--
JP McCaffrey

**Comment by petrbrzek** [comment]
I am guessing it might be something with changed data structures in the new version. If you have time, would you be willing to send us your `~/.avocode/state.json` to team@avocode.com and also try following?

- Close the app and uninstall/delete all versions of Avocode you have.
- Backup and remove directory ~/.avocode with all user data.
- Install the latest again.

Let me know if it helped.

**Comment by jakubzitny** [comment]
Hi @jpm1475, do you still have problems starting the latest version of Avocode?
