### ISSUE TITLE
can't upload new files

### ISSUE THREAD

**Issue by odedyar** [avocode/avocode#1363]
* **Version**: 
2.13.2

* **Web/Desktop**:
Desktop

* **Platform**: 
Windows 10

can't upload new psd files anymore

**Comment by vojtatranta** [comment]
Can you please be more specific? What does not work? How do you try to upload new files?

**Comment by odedyar** [comment]
Hi, 

The new file just doesn't upload and it stuck on 0%.

I try drag and drop and also Upload Design button and get the same result.

**Comment by vojtatranta** [comment]
I suppose that this happens with any file you try regardless of size etc. right?

Are you not behind some corporate proxy?

**Comment by odedyar** [comment]
Yes, any file size and no proxy.

It was just fine 4 days ago.

 

Reagrds,

Oded

**Comment by vojtatranta** [comment]
We have no reports about connectivity issues reported so far. I tried to upload a file and it works completely OK.

4 days ago you had `2.13.1` version?

**Comment by odedyar** [comment]
I think I did install a new update a few days ago

**Comment by vojtatranta** [comment]
Are you sure it is not some connection-related problem?

**Comment by odedyar** [comment]
I have this problem already more than 8 hours ago and didn't have any connection related problem

**Comment by vojtatranta** [comment]
I see.

Well it does not seem as a problem on our end. I'll ask our backend guys.

**Comment by odedyar** [comment]
Thanks

**Comment by odedyar** [comment]
Ok, I found the problem. the computer clock was wrong. thanks.

**Comment by jakubzitny** [comment]
Thanks for letting us know @odedyar. Don't hesitate to create new issue if you have any other problems.

**Comment by LitvinenkoEvgeny** [comment]
worked for me, unobvious thing

**Comment by 0xFeelix** [comment]
Thx man
