### ISSUE TITLE
Error load project

### ISSUE THREAD

**Issue by aquelito** [avocode/avocode#1365]
* **Version**:  last version

* **Web/Desktop**: web

* **Platform**:  OSX

I don't have access to my project

**Comment by vojtatranta** [comment]
Please can you be more specific? What happens that you cannot access your project?

**Comment by aquelito** [comment]
Check my screenshot, no more...
![telechargement](https://cloud.githubusercontent.com/assets/940004/24650704/4daf8cc6-192b-11e7-8b59-39ef5764b335.png)

**Comment by aquelito** [comment]
It is ok. I logout and login .........

**Comment by vojtatranta** [comment]
This looks like a faulty sync.

If this occurs just hit Sync button in the top right. Which should resolve it.

Seems like designs were not properly downloaded.

**Comment by aquelito** [comment]
No work on refresh,
No work on reboot
Nothing.
Just logout/login
