### ISSUE TITLE
Horizontal scrolling with mouse wheel not working anymore?

### ISSUE THREAD

**Issue by monti84** [avocode/avocode#1366]
Hey Avocoders,
as I remember it was possible to scroll the document horizontally with shift + mouse wheel. I really missing the feature, can somebody tell me something about this?

-----------------------------
Version: 2.13.2
Web/Desktop: Desktop 
Platform: Win 7 x64

**Comment by vojtatranta** [comment]
We actually haven't known that this is even possible. We could definitely put it back.

But anyway now you can use Handtool just as easily. Just press `H` to switch to the hand tool. Or hold `space` to activate it temporarily.

**Comment by monti84** [comment]
Thanks, that space thing is perfect :)

**Comment by vojtatranta** [comment]
We tried to put all those known shortcuts from other common programs like Photoshop to make it easy to use. So if you hit space when you have selected design in Project Manager a Preview will pop up. etc.

**Comment by dmaok** [comment]
To lock the space, you need to switch focus to the program window. In the case of the Shift button, focus was not required. Could you return this functionality? In all applications, except for Photoshop, the shift is used for horizontal scrolling.
