### ISSUE TITLE
pizdec

### ISSUE THREAD

**Issue by Solomko2** [avocode/avocode#1367]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.0`
Avocode UID: 124843
```
Error: Could not download metadata (revision=9407906)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:41:24829
```

**Comment by vojtatranta** [comment]
Metadata you are trying to download does exist on the server and they are accessible.

Have you managed to open the design at the end?

**Comment by jakubzitny** [comment]
Closing with respect to #1328.
