### ISSUE TITLE
Visual error

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1369]
* **Version**: 
2.13.2

* **Web/Desktop**:
Desktop

* **Platform**: 

Mac os 10.12.4 (16E195)

![image](https://cloud.githubusercontent.com/assets/6084353/24746588/f053dcae-1ab9-11e7-8ba0-f853127c5a80.png)

**Comment by vojtatranta** [comment]
@vAhyThe do you remember whether previous versions were ok?

**Comment by vAhyThe** [comment]
@vojtatranta previous version was ok. This was there like 1 ~ 2 seconds then was normal

**Comment by jakubzitny** [comment]
Hi @vAhyThe, do you still have this problem in the latest version of Avocode, please?
