### ISSUE TITLE
Paid plan PSD upload limit

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#137]
Does the business plan will have an unlimited file size for the psd?

**Comment by rychlis** [comment]
Not at the moment, the 200MB limit is more of a technical limitation. We will definetely review our options though and might make that possible in the future.

Right now you can upload larger designs only using the Photoshop extension.

**Comment by polikin** [comment]
cool!

**Comment by kure-** [comment]
hello,
anything changed since 20feb about uploading larger files? I'm sometimes struggling with designs that are over 200MB and basically can't do anything about it because, you know, the designers are somehow lazy and crazy at the same time. I'm using Adobe Assets in these cases but it would be nice to keep all my projects at one place/application.

thanks for response

Kuře

**Comment by rychlis** [comment]
We've just bumped the limit to 300MB and will monitor the change. We will consider changing the limit further in time

**Comment by rychlis** [comment]
fyi the limit is now 500MB. We're now mostly working on further improvements to make parsing of uploaded psds more reliable and might enable us to make the limit even larger in the future. Is 500mb enaugh to close this issue?

**Comment by kure-** [comment]
yes 500MB might be enough, although i havent used Avocode since May I guess, because of this. I have experienced lately even 700MB of PSDs but thats more of a designers lack of any sense so 500MB is enough.

**Comment by PixelT** [comment]
Did you plan to enlarge the file size limit?
I have psd which have 650mb and can open it in avocode :(

**Comment by tyronem** [comment]
I have a 612 MB file that won't open either.

**Comment by kure-** [comment]
@tyronem I've ended up teaching the designers how to work with PSDs properly and make them clean up the mess when they're done. That's probably the way to go :)

**Comment by salexpro** [comment]
Please, make unlimited upload for paid users or just bigger limit than 500mb. Now I have 560mb psd and i can't work on it with avocode
