### ISSUE TITLE
Vissual error in export JPG

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1372]
* **Version**: 
2.13.3

* **Web/Desktop**:
Dekstop

* **Platform**: 

MAC os 10.12.4 (16E195)

![image](https://cloud.githubusercontent.com/assets/6084353/24798761/05de3d2e-1b98-11e7-9373-841e5dc09eb0.png)

![image](https://cloud.githubusercontent.com/assets/6084353/24798772/1151117c-1b98-11e7-9d75-52a40c2f67d2.png)

**Comment by vojtatranta** [comment]
Could you please try older version whether it happens there too?
https://avocode-media.s3.amazonaws.com/download/avocode-app/2.11.1/avocode-app-mac-2.11.1.zip

I am just curious what's the reason, because it might be Electron.

**Comment by vAhyThe** [comment]
@vojtatranta sure gime me minute

**Comment by vAhyThe** [comment]
@vojtatranta export img is ok but there some wierd visual artefacts

![image](https://cloud.githubusercontent.com/assets/6084353/24799362/16a49632-1b9b-11e7-8084-2fe0991a42a2.png)

**Comment by vojtatranta** [comment]
yeah I know

**Comment by jakubzitny** [comment]
Hi @vAhyThe, is this still happening in latest Avocode, please?

**Comment by vAhyThe** [comment]
for now it looks oke :)

**Comment by jakubzitny** [comment]
Thanks, I am closing it then 😉 Please let us know if you see this (or any other problem) again.
