### ISSUE TITLE
Changed in Default export path

### ISSUE THREAD

**Issue by insomniaOk** [avocode/avocode#1377]
* **Version**:  2.13.4 

* **Web/Desktop**: Desktop

* **Platform**: Linux

The "Default export path" in "App prefernces" have been changed to custom, but after installation of  latest version, it has hanged to default http://joxi.ru/4AkzWXwCOLNJ2q

**Comment by petrbrzek** [comment]
@insomniaOk Thanks for the report. I'm able to reproduce it. It's going to be fixed in the next release.

**Comment by insomniaOk** [comment]
Hello, the problem still haven't been fixed in new version 2.13.5

**Comment by vojtatranta** [comment]
@insomniaOk it will land in `2.13.6`

**Comment by bolekkerous** [comment]
Hey - 
I believe this was fixed quite a while ago.

Please update your app and it should hopefully work.

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
