### ISSUE TITLE
Scss syntax only without Compass or Bourbon

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#138]
Enable option to have scss syntax only (without Bourbon or Compass)

So, the width and height will not be in a mixin.

**Comment by polikin** [comment]
For those who use Libsass + Grunt autoprefixer instead of using Compass or Bourbon

**Comment by joshsmith01** [comment]
+1

**Comment by dongepulango** [comment]
+1 
Also for LESS without LESShat.

**Comment by nikolowry** [comment]
Pleaseeeeeeeeee!!!! +1

**Comment by petrbrzek** [comment]
Yep, we will do it.

**Comment by polikin** [comment]
Coool!

**Comment by rychlis** [comment]
We've just released Avocode 2.3.0 with reworked settings options for selecting mixin libraries. You can now use:

Sass: Compass, Bourbon or none
Less: Less Hat or none
Stylus: nib library or plain Stylus

**Comment by polikin** [comment]
Thanks!
