### ISSUE TITLE
No app in the menu when install from repository

### ISSUE THREAD

**Issue by sakralbar** [avocode/avocode#1380]
* **Version**: 2.13.5

* **Web/Desktop**: Desktop

* **Platform**:  ubuntu gnome 16.04

No app and no icon in the programs menu when install Avocode from repository for linux. Just can start app from terminal by command "avocode".

**Comment by jakubzitny** [comment]
Hi @sakralbar, thanks for the issue. Sadly, this happens on some Linux distros and we're working on making sure it works properly on as many as possible.

As a quick fix I suggest you to open `/opt/Avocode/avocode.desktop.in`, fix the `Exec` and `Icon` paths to point to `/opt/Avocode/avocode` and `/opt/Avocode/avocode.png` respectively, and move it to `/usr/share/applications/`. The icon should appear menu. Let me know if it really does 😉 

In the meantime we'll be looking into Ubuntu Gnome to fix it for future releases.

Thanks.

**Comment by sakralbar** [comment]
Hi @jakubzitny. I changed "exec" and "icon" patch (Exec=/opt/Avocode/avocode Icon=/opt/Avocode/avocode.png) in avocode.desktop.in and copyed it to /usr/share/applications but nothing has changed.

Then I changed /usr/share/applications/avocode.desktop to new "exec" and "icon" patches and now I have Avocode's icon in my programs menu, thanks :)

**Comment by jakubzitny** [comment]
Hi @sakralbar, we've fixed the Desktop file few versions back. I believe everything should work correctly for you in the latest Avocode, is that right? Please open a new issue if you have any more problems 😉
