### ISSUE TITLE
Image assets are not previewing properly

### ISSUE THREAD

**Issue by AtifMohammed** [avocode/avocode#1385]
* **Version**: 2.13.5

* **Web/Desktop**: Desktop

* **Platform**: Ubuntu 16.04

Designs are rendering perfectly fine in the web version, but the desktop version is not loading all the image assets in the screen. Most of the png assets are missing from the rendered output.

**Comment by vojtatranta** [comment]
@AtifMohammed could you send screenshot please?

**Comment by AtifMohammed** [comment]
![screen_2](https://cloud.githubusercontent.com/assets/14360360/24948810/2bde5ece-1f89-11e7-9541-5c116695ad47.jpg)
![screen_1](https://cloud.githubusercontent.com/assets/14360360/24948809/2bdac4da-1f89-11e7-926d-25952b735ab9.jpg)

Both are same screens, one viewed in chrome and other in Linux App. There is an extra blur and missing assets in the linux version.

**Comment by sakralbar** [comment]
Hi! I have a similar problem.
Avocode 2.13.5 do not show frames on top of photos. Both web and native versions.

Ubuntu gnome 16.04

This is a layout with a problem https://manager.avocode.com/view/2d7076a321eb41feae97216eeb489834/ 

![image](https://cloud.githubusercontent.com/assets/11180735/25041902/44c709ce-211c-11e7-83e0-f6342c6562ee.png)
![image](https://cloud.githubusercontent.com/assets/11180735/25041924/7220b2a8-211c-11e7-9dfe-c5d11178cd37.png)
![image](https://cloud.githubusercontent.com/assets/11180735/25041950/c2f32242-211c-11e7-9bf7-e6dcbdfd2e6c.png)
![image](https://cloud.githubusercontent.com/assets/11180735/25041951/cf65fcca-211c-11e7-8140-1e7e99e0c49b.png)

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. 

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
