### ISSUE TITLE
Images are exported incorrectly.

### ISSUE THREAD

**Issue by lk-geimfari** [avocode/avocode#1386]
* **Version**: 2.13.5

* **Web/Desktop**: Desktop

* **Platform**: Linux (Ubuntu 16.04).

I have this image:
![image](https://cloud.githubusercontent.com/assets/15812620/24947754/a3eb5de0-1f70-11e7-97f8-b06c089d25a1.png)

When I try to export an image, this is what happens:
![image](https://cloud.githubusercontent.com/assets/15812620/24947802/c6d528b8-1f70-11e7-83b9-9b6c16f4e066.png)

**Comment by vojtatranta** [comment]
@lk-geimfari could you send us that psd at team@avocode.com? 

What is that arrow? If it is a font it may cause these issues. Or the rotation might be an effect which may cause it.

**Comment by lk-geimfari** [comment]
@vojtatranta It's a sketch file. I'm sorry, i can't send you this file this is the private (commercial) project.

Avocode show this information about image:
![image](https://cloud.githubusercontent.com/assets/15812620/24948423/f307fa08-1f72-11e7-908d-a37b6d93acdb.png)

**Comment by vojtatranta** [comment]
@lk-geimfari understood. But that's kinda hard for us to debug it if we don't have that source file.

Could you open Sketch and tell me which effects are applied to this layer?
