### ISSUE TITLE
Problems with certain mobile connection

### ISSUE THREAD

**Issue by zonov** [avocode/avocode#139]
We are faced with the problem of synchronization of designs created in Sketch on the development machine from Avocode on a mobile connection. Our provider - MTS http://en.mts.ru/. We use 4G mobile router.

Projects are usually not open. The program halts with the message that the project is loading.

The problem is solved only be used to connect to VPN.

I think that maybe this kind of problems are more frequent for all Avocode users. I am far away from thougnt that my case is unique. If your app returned me some kind of notification about network problems instead of eternal loading it can saved me two full days.

**Comment by rychlis** [comment]
We've improved the loading process a lot in Avocode 1.1.0. You are now at least able to see how far you are in the loading process and cancel the load if it takes too long.
