### ISSUE TITLE
Can't open files.

### ISSUE THREAD

**Issue by jcasabona** [avocode/avocode#1390]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.5`
Avocode UID: 57599
```
Error: Could not download metadata (revision=9664442)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:42:5747
```

**Comment by connor-bean** [comment]
Are you behind some sort of proxy by chance?

**Comment by jcasabona** [comment]
I am not and it was working earlier.

Joe Casabona Web Developer
Website : Casabona.Org [http://www.casabona.org/] Learn WordPress: WP in One Month [https://wpinonemonth.com/] Podcast: How I Built It [https://howibuilt.it/]
On Thu, Apr 13, 2017 at 4:25 AM, Connor <notifications@github.com> wrote:
Are you behind some sort of proxy by chance?

**Comment by connor-bean** [comment]
Hey @jcasabona -

Can you try this again? Are you still getting this error?

**Comment by jcasabona** [comment]
Oops - I am not. All’s good.
Joe Casabona Web Developer
Website : Casabona.Org [http://www.casabona.org/] Learn WordPress: WP in One Month [https://wpinonemonth.com/] Podcast: How I Built It [https://howibuilt.it/]
On Thu, Apr 20, 2017 at 9:04 AM, Connor <notifications@github.com> wrote:
Hey @jcasabona [https://github.com/jcasabona] -

Can you try this again? Are you still getting this error?
