### ISSUE TITLE
dont open a design page (psd)

### ISSUE THREAD

**Issue by laion220995** [avocode/avocode#1391]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.3`
Avocode UID: 44420
```
Error: Could not download metadata (revision=9749644)
    at file:///C:/Users/%D0%93%D1%80%D0%B8%D0%BD/AppData/Local/avocode/app-2.13.3/resources/app.asar/dist/avocode.min.js:41:31359
```

**Comment by connor-bean** [comment]
Hello @laion220995 -

Are you behind some sort of proxy by chance?

**Comment by laion220995** [comment]
With the proxy all right, reinstall did not help

**Comment by jakubzitny** [comment]
Hi @laion220995, there should be a bunch of improvements regarding this in the latest Avocode. I will close this issue, please let us know if it's still happening and I'll reopen.
