### ISSUE TITLE
IMPORTANT: Please try to describe how did it happen.

### ISSUE THREAD

**Issue by WebSkating** [avocode/avocode#1393]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.5`
Avocode UID: 126213
```
Error: Could not download metadata (revision=9937233)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:42:5747
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by connor-bean** [comment]
Hello -

Thanks for the report. Can you try again? We were able to download the metadata on our end so we're struggling to replicate this issue. Is your Internet connection ok?
