### ISSUE TITLE
Please add notes list for a project

### ISSUE THREAD

**Issue by Zidar** [avocode/avocode#1394]
* **Version**:  2.13.5 + web

* **Web/Desktop**: Desktop + web

* **Platform**: Windows, any browser apply

Notes tool is convenient, thank you! But...

Typical project contains many files. It's boring and unproductive to open 10-20-30 files and search for notes in each of them.
Please add a page or popup with complete list of notes within a project.

**Comment by connor-bean** [comment]
Thanks for the feedback!

**Comment by jakubzitny** [comment]
Closing with respect to #1373.
