### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by shgkm0423** [avocode/avocode#1397]
* **Version**: 
2.13.5

* **Web/Desktop**:
Desktop

* **Platform**: 
Mac OS sierra / Phoshop 2017(CC)

**Comment by connor-bean** [comment]
Hello - what was the bug?

**Comment by shgkm0423** [comment]
I also sent it in chat, but after uploading PSD "Processed ....." will stop at 80%.
I was told to send PSD data for verification, so I sent it but there is no reply after that.
If you reduce the number of layers, it will be 50% instead of 80%, so the layer may be affecting.
Thank you.

**Comment by jakubzitny** [comment]
Hi @shgkm0423, do you still have problems with uploading the file or other files? I think this issue is similar to #1374, so let's move the conversation there.
