### ISSUE TITLE
error

### ISSUE THREAD

**Issue by khoaanh2212** [avocode/avocode#1399]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.5`
Avocode UID: 22760
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by connor-bean** [comment]
Hello @khoaanh2212 -

Can you explain to us what you were doing when this error happened?

Could you also let us know your Avocode version?

**Comment by khoaanh2212** [comment]
In my place there are two lines of internet,but one of them can not access into avocode,although both of internet line still worked.

**Comment by jakubzitny** [comment]
Hi @khoaanh2212, can you give us more details on the two lines? Are both of them ethernet or Wi-Fi? Is it small home router or a company network? Any further details? Is there any chance one of them is filtering some network requests?

**Comment by khoaanh2212** [comment]
i've just checked avocode.now,It works for both of internet line.Yesterday still had error.
Sorry for that convenience.
And thank you so much.
