### ISSUE TITLE
Aocode Crash

### ISSUE THREAD

**Issue by rajrauther** [avocode/avocode#1400]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.13.5`

While uploading the files Avocode Crashed.

**Comment by connor-bean** [comment]
Did you receive any error message when this happened?

**Comment by rajrauther** [comment]
1c307e55-e88e-4326-b2f6-9ae11451e702

*Raj Rauther. +91 9867299966*
1st Floor, 225, Raghuleela Arcade,
Vishwaroop International Infotech Park,
Sector 30A,  Vashi, Navi Mumbai 400703.
<http://facebook.com/dadsonlogistics>
<http://us.linkedin.com/in/in.linkedin.com>  <http://twitter.com/>

*Statement of Confidentiality*



The contents of this e-mail message and any attachments are confidential
and are intended solely for addressee. The information may also be legally
privileged. This transmission is sent in trust, for the sole purpose of
delivery to the intended recipient. If you have received this transmission
in error, any use, reproduction or dissemination of this transmission is
strictly prohibited. If you are not the intended recipient, please
immediately *notify* the sender by reply e-mail or phone and *delete* this
message and its attachments, if any.

**Comment by jakubzitny** [comment]
Hey @rajrauther, do you still have problems with uploading in latest version of Avocode, please?
