### ISSUE TITLE
css comment name

### ISSUE THREAD

**Issue by bhenav** [avocode/avocode#1401]
* **Version**: 2.13.5

* **Web/Desktop**: Desktop

* **Platform**: windows

![image](https://cloud.githubusercontent.com/assets/14276250/25176634/7bf9e544-2507-11e7-970b-c160cd123e0d.png)

**Comment by jakubzitny** [comment]
Hi @bhenav, thanks for the report. This is a bug and we should definitely fix it, hopefully as soon as possible.

**Comment by vojtatranta** [comment]
thi should be fixed in `2.13.6`
