### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Sharkozp** [avocode/avocode#1403]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 138808
```
Error: ETIMEDOUT
    at /opt/Avocode/resources/app.asar/node_modules/request/request.js:813:19
    at wrapped (/opt/Avocode/resources/app.asar/node_modules/raven-js/src/raven.js:283:29)
```

**Comment by connor-bean** [comment]
Hello - can you tell us more about what you were doing when this happened?

Has it happened again since you first reported it?
