### ISSUE TITLE
Feature Request: Open Symbol in new tab from sidebar

### ISSUE THREAD

**Issue by JayCarney** [avocode/avocode#1408]
* **Version**: 2.13.6

* **Web/Desktop**: Web

* **Platform**: Mac

Would really appreciate the ability to open symbols in a a new tab while viewing a page, either a button next to the "Open Symbol" for "Open Symbol in new tab" or just support for `cmd + click` on the existing button. 

`cmd + double click` on the symbol in-page currently works, just seems to be missing from the right hand sidebar

**Comment by vojtatranta** [comment]
It confused me a bit :)

Because smart objects from Photoshop are opened by default on a new tab. I will unify this and symbols and smart objects will be opened on the new tab.

**Comment by JayCarney** [comment]
Ahh, yes. Sorry I should have specified I was dealing with Sketch files not Photoshop, may have helped a little with the vocabulary

**Comment by vojtatranta** [comment]
I think that if you doublec clicked layer itself it opened a new tab, however I fixed it and tow "Open Symbol" button opens a new tab too.

**Comment by bolekkerous** [comment]
Should be fixed now.
