### ISSUE TITLE
Exporting image

### ISSUE THREAD

**Issue by canberkcakmak** [avocode/avocode#1409]
IMPORTANT: Please try to describe how did the crash happen.
when i press the export image.

App v. `2.13.6`

**Comment by vojtatranta** [comment]
How big was the image? Avocode may got out of memory when exporting huge images...

**Comment by canberkcakmak** [comment]
sorry it is not image it is a shape and 656px * 359px. So it's not big.

**Comment by vojtatranta** [comment]
Hmhm... Would you send us the source file? team@avocode.com? Thanks!

**Comment by jakubzitny** [comment]
Hi @canberkcakmak, do you still have problems with export in latest version of Avocode?

**Comment by jakubzitny** [comment]
Hi @canberkcakmak, do you still have problems with export in latest version of Avocode?
