### ISSUE TITLE
Incorrect display drop-down list

### ISSUE THREAD

**Issue by Solomon2014** [avocode/avocode#1410]
I use Desktop version (release 2.13.6).
My OS is Linux Ubunut 16.04 LTS 64x.
Graphic Gallium 0.4 on AMD PITCAIRN (DRM 2.43.0 / 4.4.0-75-generic, LLVM 3.8.0).

And i have some little bug. Show [this file](https://ufile.io/07slh)
Maybe it's important to you. Thx.

**Comment by connor-bean** [comment]
Hey @Solomon2014 -

Thanks for the report. We are currently tracking this in #1158 so I will close out this duplicate.
