### ISSUE TITLE
Can't access account setting, download invoice, team member setting on website

### ISSUE THREAD

**Issue by chiefeay** [avocode/avocode#1413]
* **Version**: 2.13.5

* **Web/Desktop**: Web

* **Platform**: Chrome

![screen shot 2017-04-26 at 11 28 18 am](https://cloud.githubusercontent.com/assets/25391446/25450524/0dff6f9c-2a74-11e7-8a98-8df32cff6b57.png)

**Comment by vojtatranta** [comment]
We had outage back then, it should be ok.
