### ISSUE TITLE
Couple of small hotkey bugs

### ISSUE THREAD

**Issue by Zidar** [avocode/avocode#1419]
* **Version**: 2.13.6

* **Web/Desktop**: Desktop

* **Platform**: Windows

### Selection frame does not disappear when switching from "selection" to "hand" tool.
How to reproduce:
1. Activate "selection" tool
2. Hover an element. A blue frame will appear
3. Switch to "hand" tool by means of "h" hotkey without moving mouse.
4. Blue frame will resist.
The same issue with "measure" and "slice" tools when switching to "hand".

### Hotkeys do not work till first click on workspace in case when tool is changed by click on toolbar
How to reproduce:
1. Change tool using toolbar.
2. Try to use hotkey to change tool.
After first click on workspace hotkeys work again.

**Comment by vojtatranta** [comment]
Thanks!
Selection frame does not disappear when switching from "selection" to "hand" tool.
- fixed in `2.14.0`

Hotkeys do not work till first click on workspace in case when tool is changed by click on toolbar
- we will take a look at it

**Comment by vojtatranta** [comment]
GL: 3525

**Comment by jakubzitny** [comment]
The second part should have been fixed in few latest versions of Avocode already. Please let us know if you have any more problems 😉
