### ISSUE TITLE
Organize invited people

### ISSUE THREAD

**Issue by kupcza** [avocode/avocode#142]
Don't know why it happened, but system invited myself to my project. So now I have pending icon and I can't revoke it, I can't accept it..

Can you add some button or something to revoke the invitation?

**Comment by rychlis** [comment]
I've removed your invite to yourself. It might have been possible to invite yourself in previous version of web manager but that is now fixed.

Invited project users can be managed by clicking on the + button or manage people item in settings: http://cl.ly/image/1c2P3w2f410u
