### ISSUE TITLE
Bug report (font size)

### ISSUE THREAD

**Issue by Nadezda27** [avocode/avocode#1427]
* **Version**: 2.13.6

* **Web/Desktop**: Desktop

* **Platform**:  Windows

Have noticed wrongly displayed font-size in my .psd file. Actual size is 138,48px.
If you need my.psd file for fixing the bug, please advice where to send.
![untitled](https://cloud.githubusercontent.com/assets/28538579/25837375/42f9475a-3496-11e7-93a7-2c5ac02ca82c.png)

**Comment by bolekkerous** [comment]
Hey, thanks for the report - could you please send us the problematic design to team@avocode.com?

Thanks!

**Comment by bolekkerous** [comment]
This should be already fixed now for quite some time.

Please let us know if you encounter any problem!
