### ISSUE TITLE
"No document open" error on Sketch plugin export

### ISSUE THREAD

**Issue by acreed829** [avocode/avocode#1430]
* **Version**: 

* **Web/Desktop**:

* **Platform**: 

I use the latest version of Avocode & of Sketch also. OS Sierra. On export the Avocode Sketch Plugin make an error. "No document open"
I have reinstalled all the programs  and the Avocode also, and is not taking effect

**Comment by bolekkerous** [comment]
Hey -
this issue is caused by Sketch application name. If your Sketch application is named differently than just "Sketch" (usually something like "Sketch 2" or so), just rename it to Sketch and it should work.

Let us know whether it helps!

**Comment by acreed829** [comment]
Thanks a lot !!!!
