### ISSUE TITLE
Export image as SVG failed.

### ISSUE THREAD

**Issue by blitz156** [avocode/avocode#1433]
v2.13.6 Desktop Ubuntu 14.04.3 LTS

1. click on image rigth btn
2. export as SVG
3. export

P.S. Sometimes worked normal.

![149493450914230](https://cloud.githubusercontent.com/assets/3949492/26104022/490a376e-3a66-11e7-8d57-ef5018d279ed.png)

**Comment by bolekkerous** [comment]
Hey -
thanks for the report and sorry for the inconvenience.

Could you please send us the problematic Sketch file to team@avocode.com?

Thanks!

**Comment by jakubzitny** [comment]
Hi @blitz156, are you using 32-bit or 64-bit Linux, please?

As a temporary workaround, you can disable the Export optimization option in menu `Help -> Troubleshooting` and try exporting again. Please let us know whether this works or not.

**Comment by blitz156** [comment]
@jakubzitny 64-bit Linux.
Disable export optimize not helped.

**Comment by blitz156** [comment]
@bolekkerous done

**Comment by bolekkerous** [comment]
Ok, it looks like the problem is caused by exporting the symbol instance. To export the icon correctly, just double click the symbol and open it in a new tab (or click the open symbol button).

Does that work for you?

**Comment by blitz156** [comment]
@bolekkerous 
**Open in a new tab is work.**

**Comment by vojtatranta** [comment]
We will put there a better notification explaining what is going on. Sorry for that.

**Comment by jakubzitny** [comment]
Hi there, we've improved our SVG exporter in latest Avocode `2.15.0`. You can download it from [avocode.com/download](https://avocode.com/download) or use auto-update to install it. Please give it a try and let us know if this issue still persists or you have any other issues.
