### ISSUE TITLE
Error on lunching application

### ISSUE THREAD

**Issue by suntalig** [avocode/avocode#1436]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 68767
```
No stack trace available
```

**Comment by vojtatranta** [comment]
This is not something we could fix.

What's your os and architecture?

**Comment by jakubzitny** [comment]
Closing with respect to #1360, please give us more information about your environment so we can debug this problem more thoroughly.
