### ISSUE TITLE
Incorrect rulers position

### ISSUE THREAD

**Issue by beliarh** [avocode/avocode#1439]
* **Version**: 2.14.0

* **Web/Desktop**: desktop

* **Platform**: Linut Mint 18.1 Cinnamon 64-bit

Incorrect rulers position (if side panel is close):
![18-05-2017 09-37-45](https://cloud.githubusercontent.com/assets/4661335/26188005/aab3836a-3bad-11e7-811c-768a98aa74f6.jpg)

**Comment by jakubzitny** [comment]
Hi @beliarh, thanks for reporting this. This is a bug, we can reproduce it. We'll try to fix it for one of the next releases.

Feel free to let us know if you have any more problems with Avocode.

**Comment by vojtatranta** [comment]
Fix deployed in `2.14.1` thank you for the report
