### ISSUE TITLE
Code textarea size in accordeon right side

### ISSUE THREAD

**Issue by panntau** [avocode/avocode#144]
Code textarea size in accordeon on the right side is constantly shrinking to small size when i click on different layer or object, it is possible to remember size that it has before changing object in design or stretch to view full content inside textarea?
![image](https://cloud.githubusercontent.com/assets/9363240/6283226/892276b2-b8e1-11e4-8f79-2c7856c51e40.png)

**Comment by rychlis** [comment]
We've just released Avocode 1.1.0 with improved code panel, the size now stays the same when you click on a different layer
