### ISSUE TITLE
Problems with PSD download.

### ISSUE THREAD

**Issue by hog-seruj** [avocode/avocode#1440]
* **Version**:  2.13.6; 2.14

* **Web/Desktop**: Web

* **Platform**: Ubuntu

I can't download PSD in 2 days. I tried 2.13.16 & last version. PSD don't download on web site & desktop APP.

**Comment by connor-bean** [comment]
Hello - 

Are you receiving any error about this? Could you be behind some sort of proxy by chance?

**Comment by bolekkerous** [comment]
Are you still having this problem? Is it about uploading a PSD to Avocode? Does it happen with all designs or just specific ones?
