### ISSUE TITLE
AutoUpdate fails from 2.12.2 to 2.14.0

### ISSUE THREAD

**Issue by Firehavvk** [avocode/avocode#1441]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.12.2`

Application offers to download last update during project opening, after that app crashes offering to restart, report or quit. It is happening every time.

**Comment by jakubzitny** [comment]
Hi @Firehavvk, thanks for letting us know. There might be a problem with auto-update from such an old version of Avocode to the newest one. Can you please tell us what platform do you use and where is `Avocode.app` located in your system? Is it in `/Applications` or somewhere else?

To update to the latest Avocode `2.14.0`, please remove the app from the system and download the latest version manually from [manager.avocode.com/downloads](http://manager.avocode.com/downloads/).

Don't hesitate to let us know if you have any other problems 😉

**Comment by Firehavvk** [comment]
I'm using Windows 10, current application path: C:\Users\%USEDIRECTORY%\AppData\Local\avocode. I think, appcrash can caused by lack of ram. When I killed several resource intensive processes the issue disaapeared.

**Comment by jakubzitny** [comment]
Thanks for the answer, is it 32 or 64-bit Windows?

Can you please confirm that when you download fresh version of Avocode, it runs correctly?

**Comment by Firehavvk** [comment]
64-bit,
Yes, there is no any problem, thank you.

**Comment by jakubzitny** [comment]
Thanks again, I'll close this thread then.
