### ISSUE TITLE
error 18.05.2017

### ISSUE THREAD

**Issue by StadnikovP** [avocode/avocode#1442]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 50888
```
Error: Could not download metadata (revision=10365733)
    at file:///C:/Users/p.stadnikov/AppData/Local/avocode/app-2.13.6/resources/app.asar/dist/avocode.min.js:43:8244
```

**Comment by vojtatranta** [comment]
Please update your app to `2.14.0`, we silenced this error as it is related to the network.
