### ISSUE TITLE
Selecting multiple layers shows only the intersection in the styles.code panel.

### ISSUE THREAD

**Issue by ardkevin84** [avocode/avocode#1443]
* **Version**: 2.14.0
* **Web/Desktop**: Desktop
* **Platform**: Linux\64 (Ubuntu Gnome) 

**Issue:** 
Selecting multiple layers shows *only* the intersection in the styles.code panel. 

**Reproduce:** 
Select 2+ similar items (eg: large text, small text, button text) and view the code in the styles panel. 

**Expected:** 
selectors along the lines of 
```SASS
.base {
  //-- common styles 
}

.large-text {
  //-- unique styles 
}

.small-text {
  //-- unique styles 
}

.button-text {
  //-- unique styles 
}
```
**Actual:** 
I only get the base selector (this is a real snippet from the issue) 
```SASS
// Base style
.layer {
  color: $text-gold;
}
```

**Comment by connor-bean** [comment]
Hello @ardkevin84 -

Thanks for reporting this. It's a feature we used to have but decided to change to the current way of doing it.

We would definitely appreciate it if you could add your use case to UserVoice here: https://avocode.uservoice.com/forums/277080-feature-voting
