### ISSUE TITLE
Sidebar with expandable / collapsible option for project designs

### ISSUE THREAD

**Issue by whoiskjl** [avocode/avocode#1444]
2.14.0

* **Version**: 2.14.0

* **Web/Desktop**: Desktop

* **Platform**: macOS Sierra 10.12.5

A side bar with all the project designs organized with expand / collapse option. It's taking too much time and energy to scroll to navigate designs

**Comment by vojtatranta** [comment]
Like list view you mean?

You'd rather display all projects in a list view than in the grid?

**Comment by vojtatranta** [comment]
In `2.14.2` we will add recenlty opened tab per Project, so you will immediately see which design you've opened last in particular project.

**Comment by whoiskjl** [comment]
![screen shot 2017-05-30 at 12 20 26 pm](https://cloud.githubusercontent.com/assets/1874874/26593680/086795d0-4533-11e7-992b-b74f4cc37b42.png)

I hope this makes much sense :|

**Comment by jakubzitny** [comment]
Hi there, there is a new UI for Sketch files in latest Avocode `2.15.0`. Symbols are displayed in a separate page now, so I think the main issue here is resolved. You can download it from [avocode.com/download](https://avocode.com/download) or use auto-update to install it. Please give it a try and let us know if you have any more issues.
