### ISSUE TITLE
Processing failed errors for many project images

### ISSUE THREAD

**Issue by thomasaw** [avocode/avocode#1446]
* **Version**: 2.14

* **Web/Desktop**: Desktop

* **Platform**: macOS Sierra 10.12.5 (16F73)

I'm getting "Processing failed" errors for many of the thumbnails of the images in my project. The problem doesn't go away after using "Clear Previews" or "Clear Thumbnails" or restarting the app. The problem also doesn't go away after deleting the Avocode caches in ~/Library/Caches/.

The 'Processing failed' error message appears to be more likely for those images that are later in the list of images. If 'Processing failed' occurs when attempting to view the image the "This design failed processing and cannot be opened. You can try to upload a new revision or delete the design.' If the problem persists, please contact us at team@avocode.com." (The stray quote symbol appears in the dialog.)

This problem did not occur for these images when using earlier versions of Avocode.

![screen shot 2017-05-22 at 10 36 24](https://cloud.githubusercontent.com/assets/195083/26289384/96b39a64-3eda-11e7-8c80-4eaa1788f3a8.png)

**Comment by vojtatranta** [comment]
Hi,
this does not seem like a problem with caches... 

These designs are images? Like just jpegs or PNGs or complete PSDs?

Could you send us these designs at team@avocode.com?

**Comment by thomasaw** [comment]
They are PSDs. I'll send mail.

**Comment by vojtatranta** [comment]
Thanks

**Comment by jakubzitny** [comment]
Hi there, we've just released Avocode `2.16.5` with a fix for this. Please update and let us know if you find any other problems 😉
