### ISSUE TITLE
opening psd

### ISSUE THREAD

**Issue by tutmeecom** [avocode/avocode#1447]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 147180
```
Error: Could not download metadata (revision=10856145)
    at file:///C:/Users/Alexey/AppData/Local/avocode/app-2.13.6/resources/app.asar/dist/avocode.min.js:43:8244
```

**Comment by vojtatranta** [comment]
This error should be handled better in `2.14.0` please update your app - Help menu -> Check for update
