### ISSUE TITLE
error

### ISSUE THREAD

**Issue by igumenov** [avocode/avocode#1448]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 7893
```
Error: Could not download metadata (revision=10863301)
    at file:///C:/Users/Igumenov/AppData/Local/avocode/app-2.13.6/resources/app.asar/dist/avocode.min.js:43:8244
```

**Comment by vojtatranta** [comment]
This error is handled better in `2.14` please update Help menu -> Check for updates
