### ISSUE TITLE
Error: Could not download metadata

### ISSUE THREAD

**Issue by vladimirov** [avocode/avocode#1449]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 147157
```
Error: Could not download metadata (revision=10795495)
    at file:///C:/Users/DenisQA/AppData/Local/avocode/app-2.13.6/resources/app.asar/dist/avocode.min.js:43:8244
```

**Comment by vojtatranta** [comment]
This error is handled better in `2.14` please update Help menu -> Check for updates
