### ISSUE TITLE
Crashes on design load

### ISSUE THREAD

**Issue by csdanmarker** [avocode/avocode#145]
I have bee experiencing issues when I try to open a project. It starts to load then crashes. Tried several times and did several restarts.

**Comment by rychlis** [comment]
Hey, what is your OS and app versions? Removing ```.avcd``` in your home folder might help

**Comment by csdanmarker** [comment]
Hello, My OS is Windows 8, I could not locate what version it was though

On Fri, Feb 20, 2015 at 8:54 AM, Tomáš Rychlik <notifications@github.com>
wrote:

> Hey, what is your OS and app versions? Removing .avcd in your home folder
> might help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avocode/avocode/issues/145#issuecomment-75240792>.
>



-- 
Danny E Marker II
Web Developer
49 East Garfield Rd
Aurora, Ohio 44202

Phone: (888) 867 - 8557
Cell:     (330) 824 -4252
Web: Codesummit <http://www.codesummit.com/>

**Comment by csdanmarker** [comment]
Where is the .avcd extension located

On Fri, Feb 20, 2015 at 8:57 AM, Dan Marker <dan.marker@codesummit.com>
wrote:

> Hello, My OS is Windows 8, I could not locate what version it was though
>
> On Fri, Feb 20, 2015 at 8:54 AM, Tomáš Rychlik <notifications@github.com>
> wrote:
>
>> Hey, what is your OS and app versions? Removing .avcd in your home
>> folder might help
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/avocode/avocode/issues/145#issuecomment-75240792>.
>>
>
>
>
> --
> Danny E Marker II
> Web Developer
> 49 East Garfield Rd
> Aurora, Ohio 44202
>
> Phone: (888) 867 - 8557
> Cell:     (330) 824 -4252
> Web: Codesummit <http://www.codesummit.com/>
>



-- 
Danny E Marker II
Web Developer
49 East Garfield Rd
Aurora, Ohio 44202

Phone: (888) 867 - 8557
Cell:     (330) 824 -4252
Web: Codesummit <http://www.codesummit.com/>

**Comment by rychlis** [comment]
We've released Avocode 1.1.0 few hour ago, you can download the lastest version from here: https://madebysource.com/download/avocode-app/exe/

In ```C:\Users\{your username}\.avcd```. The .avcd folder is a hidden file so you need to show hidden files.

Does this issue happen when opening project or document? Do you see a similar dialog as this one? http://screencast.com/t/KVgKivp98CZf

**Comment by SFCMiguel** [comment]
Hello, I'm with this error in windows 8.
http://screencast.com/t/KVgKivp98CZf

I delete the folder .avcd and this continue.

**Comment by rychlis** [comment]
Sorry for the lack of response. Do you still experience this issue with the latest Avocode 2.4.3? If the design have large size it could be caused by #143

**Comment by rychlis** [comment]
I am closing this issue due to no response from @csdanmarker - I'll reopen if you give us some new information 

@SFCMiguel if you can reproduce the error on latest avocode, you can create a new issue or comment in #143, thanks

**Comment by rychlis** [comment]
We just created a x64 build of Avocode which should fix opening larger designs on Windows. You can try it out: https://media.avocode.com/download/avocode-app/2.8.0/avocode-app-windows-x64-2.8.0.exe

Note that this requires you to have a 64bit Windows. We will soon make this the default version of Avocode
