### ISSUE TITLE
Issue after upload and try to open new file. 

### ISSUE THREAD

**Issue by code-yo** [avocode/avocode#1450]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 84930
```
Error: Could not download metadata (revision=10867087)
    at file:///C:/Users/Bogdan/AppData/Local/avocode/app-2.13.6/resources/app.asar/dist/avocode.min.js:43:8244
```

**Comment by vojtatranta** [comment]
This error should be handled better in 2.14.0 please update your app - Help menu -> Check for update
