### ISSUE TITLE
Export image with blending mode Pass through

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#1452]
* **Version**: 2.14.1

* **Web/Desktop**: Desktop

* **Platform**: Mac OS Yosemite

Exporting layers which has some blending mode crash, it is export white image in png and black on jpg. (From sketch)

<img width="265" alt="screen shot 2017-05-24 at 20 37 01" src="https://cloud.githubusercontent.com/assets/12643008/26419683/c9967216-40c0-11e7-82e3-af74509dc56a.png">

**Comment by bolekkerous** [comment]
Hey - 
could you please send us the problematic design and screenshots of the layers you're trying to export to team@avocode.com? It would help us a lot in troubleshooting the issue.

Thanks!

**Comment by jakubzitny** [comment]
Hi @janaobzerova, we're fixing the support for blending modes and similar cases in export. We should be releasing improved version in upcoming months, so we'll update you here.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. 

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
