### ISSUE TITLE
pdf processing failed

### ISSUE THREAD

**Issue by oved-yavine** [avocode/avocode#1453]
2.14.1

* **Version**: 

* **Web/Desktop**:desktop

* **Platform**: windows

PSDprocessing failed. See Rainbow project on my account. if you need the PSD, let me know

**Comment by vojtatranta** [comment]
I assume you tried to reupload the PSD still with no success?

**Comment by oved-yavine** [comment]
True

**Comment by bolekkerous** [comment]
Could you please send us the problematic PSD to team@avocode.com? We should know better what might be the problem with the actual PSD. We should also be able to upload the PSD for you with the PSD plugin.

**Comment by jakubzitny** [comment]
This problem should be fixed now, please re-open if you're still having issues 😉
