### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by glebgorokhov** [avocode/avocode#1454]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.1`
Avocode UID: 111132
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by vojtatranta** [comment]
this looks like DNS could not have been found. I think this is a network issue which should be irregular.
