### ISSUE TITLE
I don't see ending of names for artboards when exporting

### ISSUE THREAD

**Issue by pss234** [avocode/avocode#1455]
* **Version**: 
2.14.1

* **Web/Desktop**:
Desktop

* **Platform**: 
macOS Sierra
10.12.3

![c8b1bc1183](https://cloud.githubusercontent.com/assets/22349579/26553984/cbab2928-4496-11e7-9349-3b5794807c43.jpg)
How should I choose one of four similar files when exporting from Sketch if I don't see ending of name and image is too small to see the difference? Especially if it is long screen for mobile. Why not to show name in few rows.
Or you can add list view. Or export only those artboards which are selected in Sketch (best variant), like in Zeplin.

**Comment by bolekkerous** [comment]
Hey, @pss234 -
we'll be replacing this plugin with a new version without UI, so you can just select the artboards in Sketch and upload these to Avocode. With that, the problem shouldn't exist anymore.

**Comment by connor-bean** [comment]
Hey @pss234 - This is now fixed in version 2.14.3. Please update your app.
