### ISSUE TITLE
Avocode crashes on xubuntu 16.04

### ISSUE THREAD

**Issue by alkirg** [avocode/avocode#1456]
I recently installed trial version of avocode on my xubuntu 16.04. The application starts, I can upload and open psd file, but sometimes, if it's quite big (~35 MB), avocode crashes while opening a psd from project folder. How can I fix it? Here is my system information:
Processor	2x Pentium(R) Dual-Core CPU E6500 @ 2.93GHz
Memory	2051MB
OpenGL Renderer	Mesa DRI Intel(R) G33 x86/MMX/SSE2
Kernel	Linux 4.8.0-52-generic (i686)
Distribution	Ubuntu 16.04.2 LTS
Desktop Environment	XFCE 4

App v. `2.14.1`

**Comment by vojtatranta** [comment]
Hmm, do you have 64bit version of Ubuntu?

**Comment by alkirg** [comment]
Nope. It seems that it's better to upgrade my 32-bit, right?

**Comment by vojtatranta** [comment]
I think `Kernel	Linux 4.8.0-52-generic (i686)` means that you **have** 32bit version of Ubuntu.

32bit is "lower" than 64bit version. One of the differences is that 64bit version OS can address more memory and that's probably the case.

Rendering a design requires a quite big chunk of memory to be allocated and on 32bit OS it cannot be done and therefore Avocode crashes. 

We had similar issues with 32bit version of Windows and we released 64bit version of Avocode last year which resolved lots of troubles.

So please **upgrade** to 64bit OS (your machine must be capable of 64bit) and your Processor should be capable of it: http://ark.intel.com/products/42805/Intel-Pentium-Processor-E6500-2M-Cache-2_93-GHz-1066-FSB
