### ISSUE TITLE
Export images from PSD with mask and transparency

### ISSUE THREAD

**Issue by Voidek** [avocode/avocode#1458]
* **Version**: 2.14.0

* **Web/Desktop**: Desktop

* **Platform**: Linux/Ubuntu

Hi, when I export pictures from the PSP format there are problems. For example: a blue rectangle (overlay), on top of it a mask is a translucent picture. After the export, the image is much darker or lighter  and does not look like a preview or layout. We have to run photoshop and get the picture there. Please fix this or let take pictures without effects.
![im1](https://cloud.githubusercontent.com/assets/10668666/26619976/8054f3d8-45e9-11e7-8bbd-0a485bf29d82.png)
![im3](https://cloud.githubusercontent.com/assets/10668666/26620091/03d92da0-45ea-11e7-93d5-4b3b5acc18ff.png)
![im2](https://cloud.githubusercontent.com/assets/10668666/26619975/8054654e-45e9-11e7-9c6c-dba095258e97.png)

**Comment by bolekkerous** [comment]
Hey, @Voidek -
thanks for the report.

Could you please e-mail us the problematic file to team@avocode.com, so we can investigate the issue properly?

Thanks!

**Comment by Voidek** [comment]
I sent the layout to team@avocode.com. And this problem is in every layout

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. 

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
