### ISSUE TITLE
Photoshop plugin mockup uploading

### ISSUE THREAD

**Issue by salexpro** [avocode/avocode#1459]
Desktop, Mac OS

When I upload a new revision of mockup to existing project trough Photoshop plugin, modified date doesn't update.
Mockup should be the 1st in order.

**Comment by salexpro** [comment]
huh, after update from 1st of june this problem seems to fixed

**Comment by jakubzitny** [comment]
Thanks for the report @salexpro, don't hesitate to open a issue if you have any more problems. 😉
