### ISSUE TITLE
(Photoshop) All layers in the hidden and masked group get ignored by Avocode.

### ISSUE THREAD

**Issue by nibushibu** [avocode/avocode#146]
Mac OSX Yosemite 10.10.2
Photoshop CC 2014.2.2

![artboard 1](https://cloud.githubusercontent.com/assets/399949/6305507/234bfcb2-b96f-11e4-9768-24bddd33b764.png)

**Comment by dubcanada** [comment]
Experienced this today as well.

Avocode 1.1.1
Photoshop CC 2014.2.0

**Comment by rychlis** [comment]
Hello, we've just deployed a fix. You will need to re-sync affected designs using PSD upload or using the latest Avocode Photoshop Extension 2.2.1.

Let me know if you still experience the issue and I will reopen
