### ISSUE TITLE
Large Design files not loading in desktop app

### ISSUE THREAD

**Issue by tedlin182** [avocode/avocode#1460]
* **Version**: 
2.14.1

* **Web/Desktop**:
Desktop App

* **Platform**: 
Mac OS Sierra - 10.12.5

I tried loading up a larger PSD file in the Mac desktop app but comes up blank and is pretty sluggish trying to toggle layers on and off. Might be the size of the file, but we even tried re-uploading the PSD and it's still happening.

Not sure if there's a work around but I'm unable to work off this now. Any suggestions?

**Comment by connor-bean** [comment]
Hello - what is the size of the design? 

You should be able to use the desktop app to upload designs up to 500mb. Larger designs will need to be uploaded through the PS plugin, which you can download here: www.manager.avocode.com/downloads
