### ISSUE TITLE
Cant load

### ISSUE THREAD

**Issue by zachschrock** [avocode/avocode#1461]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.6`
Avocode UID: 50197
```
Error: Could not download metadata (revision=7526877)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:43:8244
```

**Comment by connor-bean** [comment]
Hello -

Thanks for the report. Are you having any network issues or could you be behind a proxy by chance?

Also - when you update to the most current version of Avocode, do you still receive this issue?

**Comment by jakubzitny** [comment]
Closing with respect to #1328.
