### ISSUE TITLE
Designs are not rendered, blank screen with selection borders instead

### ISSUE THREAD

**Issue by BrotherCash** [avocode/avocode#1464]
* **2.14.2**: 

* **Desktop**:

* **Mac OS Sierra 10.12.3**: 

![screenshot at 03 15-11-34](https://cloud.githubusercontent.com/assets/29160406/26752674/fba08d36-486e-11e7-82c0-4d5322b5a04f.png)

**Comment by exdeniz** [comment]
Me too https://github.com/avocode/avocode/issues/1465

**Comment by BrotherCash** [comment]
Mine is not crashing, I just don't see a thing from the very begining but can choose invisible things

**Comment by BrotherCash** [comment]
And, by the way, this happens in newer versions. In older one - 2.12.6 - everything works fine. Seems like smth was changed in gpu acceleration engine or in rendering part.

**Comment by exdeniz** [comment]
Yes, old version work fine

**Comment by petrbrzek** [comment]
Does the web app work for you? https://app.avocode.com

**Comment by exdeniz** [comment]
No, error this:
```
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
m.stripe.network/inner-preview.html#referrer=https%3A%2F%2Fapp.avocode.com%…8ebf-b5d274ed9939&sid=09a74f6b-d69f-46f2-90e2-3df9f91997a9&preview=true&:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
```

**Comment by BrotherCash** [comment]
https://app.avocode.com works fine for me, but it's not so convenient as local app. Anyway, I would like to solve the problem, not to find a replacement or to work in online app.

**Comment by BrotherCash** [comment]
Is there any solution or, maybe, guess?

**Comment by bolekkerous** [comment]
Hey - unfortunately we're not able to reproduce the problem on our machines. Could you please send us some example of a design that you encounter the problem with to team@avocode.com?

Thanks!

**Comment by vojtatranta** [comment]
@BrotherCash could you try this test build? https://upx.cz/it2

We changed one GPU flag in `2.14.2`, it might have caused it.

**Comment by exdeniz** [comment]
@vojtatranta I try this build, this problem not solution.

**Comment by BrotherCash** [comment]
I've tried your build, but nothing changed. Everything the same.
![10-49-09](https://user-images.githubusercontent.com/29160406/26914048-681029aa-4c38-11e7-8b31-fa01258fdd73.png)

**Comment by BrotherCash** [comment]
Problem appeared not exactly in 2.14.2 version, somewhere in 2.13.. branch. I don't remember for sure. I tried and tried every next version but problem reproduced. Then I found as old installer as I could in my computer, installed it and .... voila! I saw my project.

**Comment by BrotherCash** [comment]
Sending my design to your email can be a problem - I'm not designer, I'm frontend developer, so we have big team project with a lot of folders. Our designers export their work to corresponding folder and then developer use that for makeup. I can see design only being logged in as a member of our team and don't have access to sources. Anyway I can say - there are HUNDREDS of designs in our projects and NONE opens in new versions and ALL can be opened in older one. Of course I mean on my computer.

**Comment by BrotherCash** [comment]
I've just tried 2.13.5 version - no luck, I have elements, can see their properties but don't see them.

**Comment by vojtatranta** [comment]
@exdeniz seems like your GPU does not support WebGL, your machine is too old I suppose...

**Comment by vojtatranta** [comment]
@BrotherCash give me a sec. I'll investigate it...

**Comment by vojtatranta** [comment]
@BrotherCash I downgraded Electron to the version which was in `2.12.6` in this build of `2.14.2`.

So could you please try this build? https://upx.cz/it5

**Comment by BrotherCash** [comment]
I think you're right, 'cos your build works correct. Everything is visible and looks as expected.

**Comment by vojtatranta** [comment]
And what machine do you have? Standard macbook or hackintosh or?

**Comment by BrotherCash** [comment]
hackintosh, with old 8600gt graphic card )

**Comment by vojtatranta** [comment]
I thought so....

This is going to be an issue though.... If there is an "unofficial" gup in non-apple device, it can be a problem.

I think I cannot help anyhow, you can try next version, when we upgrade electron again, and see whether it's okay, until then just keep this build. Sorry for that :(

**Comment by BrotherCash** [comment]
Thanks for help. Anyway now I know the reason.
