### ISSUE TITLE
PSD - Red Screen of Death

### ISSUE THREAD

**Issue by AlexandruDoda** [avocode/avocode#1467]
* **Version**: 
Latest 2.14.2

* **Web/Desktop**:
Desktop

* **Platform**: 
macOS

I was opening the PSD and it failed twice.

**Comment by bolekkerous** [comment]
Hey, @AlexandruDoda -
could you please send us the problematic design to team@avocode.com or at Slack?

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. 

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
