### ISSUE TITLE
Could not download metadata

### ISSUE THREAD

**Issue by AmitBhavsarIphone** [avocode/avocode#1469]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.13.3`
Avocode UID: 153028
```
Error: Could not download metadata (revision=11310874)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:41:31359
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by vojtatranta** [comment]
this error is handled better in later version of Avocode, please update to current `2.14.2`

**Comment by AmitBhavsarIphone** [comment]
The Same error occurs in latest version too.

Now the message is "An unexpected error has occurred."

**Comment by vojtatranta** [comment]
I see. I checked the metadatafile and it was not even created meaning that the request did not make it to our server.

You sure you are not behind some proxy? Have you tried open this file on the app.avocode.com?
