### ISSUE TITLE
css hat 2 and avocode show different font size

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#147]
css hat 2.0.5
https://www.dropbox.com/s/2z6b55dnnfd621d/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-02-21%2018.44.43.png?dl=0

avocode 1.1.1
https://www.dropbox.com/s/zlthiugpzlxmpnv/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-02-21%2018.45.15.png?dl=0

design:
https://www.dropbox.com/s/eqzy08pnpe6xmy7/design.psd?dl=0
this element:
https://www.dropbox.com/s/bg909gxtf5rp3tq/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-02-21%2018.46.00.png?dl=0

ps: also would be good if you implement letter-spacing

**Comment by Lukavyi** [comment]
Also, this element has different font-sizes too
https://www.dropbox.com/s/a6y04h3ycg0s1fn/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202015-02-22%2013.17.00.png?dl=0

**Comment by kupcza** [comment]
Got same issue:
avocode: https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/b_99d663.png
css hat: https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/eldyh03p.png
ps: https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/wdy733-7.png

**Comment by kupcza** [comment]
I've noticed, that if designer uses points instead of pixels, Avocode shows wrong size - in points, but shows px units

**Comment by rychlis** [comment]
We've updated both Avocode and CSS Hat a lot since June and this seems to be fixed now. We also offer alternative units like em/rem. I will of course reopen the issue if you can still replicate the problem.
