### ISSUE TITLE
Error Occurred

### ISSUE THREAD

**Issue by Pangaj** [avocode/avocode#1470]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.0`
Avocode UID: 148201
```
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:572:26)
```

**Comment by bolekkerous** [comment]
Hey -
it seems like you're using an outdated version of the app.

Could you please try to update your app? The latest version should be 2.14.2.

To update your app, click the menu in your system bar and select Check for Update.

Let me know whether it helps!

**Comment by jakubzitny** [comment]
This should be fixed in latest version of Avocode.
