### ISSUE TITLE
rp

### ISSUE THREAD

**Issue by StragelX** [avocode/avocode#1475]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.2`
Avocode UID: 118742
```
Error: connect ETIMEDOUT 52.70.75.29:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

**Comment by connor-bean** [comment]
Hello @StragelX thanks for the report.

Are you behind a proxy by chance? What were you doing when this happened?

**Comment by jakubzitny** [comment]
Hi @StragelX, do you still have similar problems in latest version of Avocode, please?

**Comment by StragelX** [comment]
No, as far as i see? no

**Comment by jakubzitny** [comment]
Thanks, I will close this issue then. Let us know if you encounter any other problems with Avocode 😉
