### ISSUE TITLE
Sync rules and variables

### ISSUE THREAD

**Issue by joshsmith01** [avocode/avocode#148]
I would like to synchronize my rules between my computers. I just tried out the 14-day trial and the app seemed pretty complete. I was at work on my laptop working along and then I came home and started working on my imac. When I was exporting css, I was pulling out unvariablized css. Now, it is not a huge undertaking to go and add the rules to replace all the hex codes, but why would I want to?

Also, is there an option for teams to sync up their variables? If there is a team option then surely teams would be required to use the same variables.

**Comment by petrbrzek** [comment]
> Also, is there an option for teams to sync up their variables?

Not now, we discussed this idea in our team and we like that. I see, it's already on [UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7126248-sync-rules-across-multiple-computers-but-also-team), so I close it here.
