### ISSUE TITLE
Cant upload designs

### ISSUE THREAD

**Issue by VinnikovV** [avocode/avocode#1485]
2.14.4

Desktop

Windows 7

Cant upload designs
http://dl4.joxi.net/drive/2017/06/18/0012/3659/798283/83/0cbcf47ee2.jpg

**Comment by VinnikovV** [comment]
Tried again - same http://dl4.joxi.net/drive/2017/06/18/0012/3659/798283/83/df28d8c31d.jpg

**Comment by petrbrzek** [comment]
@VinnikovV can you please try it on app.avocode.com?

**Comment by VinnikovV** [comment]
Hi, i`m already uploaded. It works if upload by 1 file in same time. If upload 3-5 psd in same time - it is crashes

**Comment by jakubzitny** [comment]
Hi @VinnikovV, sorry to keep you waiting so long. So if I understand this correctly, you're having problems only when you upload a bunch of files together. All of the files separatly get uploaded properly, right?

**Comment by VinnikovV** [comment]
Yes it was such problem, don't know if it is resolved already

чт, 13 июля 2017 г. в 21:22, Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment]
Hi @VinnikovV, can you please give this a try in latest Avocode `2.15.0`? Please let us know if the problem still persists.

**Comment by VinnikovV** [comment]
HI, problem was disappeared

2017-09-11 18:31 GMT+03:00 Jakub Žitný <notifications@github.com>:
