### ISSUE TITLE
Failure when opening design on both desktop and web app

### ISSUE THREAD

**Issue by AlbertRAR** [avocode/avocode#1488]
* **Version**: 
2.14.4

* **Web/Desktop**:
Both web and dwsktop

* **Platform**: 
Ubuntu 16.04

![https-github com-avocode-avocode-issues](https://user-images.githubusercontent.com/6898522/27327520-821bf31e-55b7-11e7-939c-d1fe51ce1146.jpg)

**Comment by AlbertRAR** [comment]
BTW, error occurs on uploading only specific design. Do i need to upload in to team@avocode.com ?

**Comment by connor-bean** [comment]
@AlbertRAR yeah could you send us this design to team@avocode.com?

**Comment by AlbertRAR** [comment]
@connor-bean done

**Comment by connor-bean** [comment]
We worked on this via email. We were able to upload it for the user. I will close this out
