### ISSUE TITLE
Quickly toggle 1x/2x output for misc. CSS properties

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#149]
I would love to see something like this in the CSS/LESS etc. output:

![avocode-css-export](https://cloud.githubusercontent.com/assets/5463/6335424/c4e1116a-bb9b-11e4-8730-1a6264542b59.png)

Clicking the **2x** button would then divide the _width_, _height_, _font-size_ and _line-height_ values in two (to signal that this was designed @ 2x).

Initially, I actually thought that this was handled automatically when ticking the **Retina canvas** setting in preferences - can't really see why it isn't...

**Comment by rychlis** [comment]
I think we should definetely add such option soon, here is a related User Voice idea that you can vote for: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7497688-divide-or-multiply-dimensions-based-on-pixel-densi

**Comment by petrbrzek** [comment]
Implemented in 2.12.0.
