### ISSUE TITLE
Can't use Avocode, bottom half is hidden

### ISSUE THREAD

**Issue by kirillDanshin** [avocode/avocode#1490]
* **Version**: 
latest

* **Web/Desktop**:
desktop

* **Platform**: 
latest Mac

![2017-06-20 19 49 41](https://user-images.githubusercontent.com/9026581/27345279-c165c8b2-55f1-11e7-82c2-96165ba8c5f7.png)

unable to use Avocode, bottom part is always under some overlay

**Comment by connor-bean** [comment]
Hello -

Can you specify exactly your OS version and graphics card you have?

**Comment by kirillDanshin** [comment]
@connor-bean 10.12.6. I can say you what exactly graphics card I have later, now I can say it's some amd mobile solution

**Comment by jakubzitny** [comment]
Hi @kirillDanshin, have you been using an older version of Avocode that was working before or is this your first time? Can you try [2.14.0](https://media.avocode.com/download/avocode-app/2.14.0/Avocode-2.14.0.dmg) or [2.13.0](https://media.avocode.com/download/avocode-app/2.13.0/Avocode-2.13.0.dmg) to see if some of them are working?

**Comment by kirillDanshin** [comment]
@jakubzitny yes, this issue persists with any version I had. linux version is working as expected.

**Comment by jakubzitny** [comment]
This is quite unfortunate, could you send us the Mac/Macbook model you're using or the graphics card info, please? You can send it to team@avocode.com if you don't want it public like this. It might help us with debugging the problem.

**Comment by kirillDanshin** [comment]
@jakubzitny basically it's not a Mac/macbook. it's latest VMware Workstation Pro patched to run darwin. it can run anything but Avocode. now I can't export sketch design to avocode, and basically it means that I can't work while still subscribed to avocode. now I should work with sketch 45 that old plugin doesn't support.

**Comment by jakubzitny** [comment]
I thougt so, that explains it 😛 Thanks for the info.

Would you be willing to send me the darwin virtual image (stripped down of personal stuff) so I can try to reproduce the environment? Or some instructions on how to set it up?

We don't really have capacity to support such environments, but I'll try to find some time to try it out 😉

**Comment by jakubzitny** [comment]
Hi @kirillDanshin, how about that environment details/howto? Can you please check out issue #1512 to see if it's similar to what you are experiencing? I guess it's still happening with `2.14.5`, right?

**Comment by shamboo** [comment]
Macbook Pro mid 2010
Intel HD Graphics 288 МБ and NVIDIA GeForce GT 330M

**Comment by jakubzitny** [comment]
Hey @shamboo and @kirillDanshin, we've just released Avocode `2.14.6` with a possible fix for this issue. Let us know if it's still happening to you or if you have any other problem
