### ISSUE TITLE
I just open app after update. MAC OS

### ISSUE THREAD

**Issue by mr-stasyuk** [avocode/avocode#1491]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.4`
Avocode UID: 125155
```
TypeError: Cannot read property 'requestAnimationFrame' of undefined
    at y (https://fast.appcues.com/24524.js:1:21849)
    at r (https://fast.appcues.com/24524.js:1:67995)
    at https://fast.appcues.com/24524.js:1:203321
    at https://fast.appcues.com/24524.js:1:21782
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Hi there, this should be fixed in latest Avocode `2.15.0`. You can download it from [avocode.com/download](https://avocode.com/download) or use auto-update to install it. Please give it a try and let us know if you have any more issues.
