### ISSUE TITLE
It's pulling a wrong font weight from the sketch

### ISSUE THREAD

**Issue by whoiskjl** [avocode/avocode#1492]
2.14.4

* **Version**: 

* **Web/Desktop**:
Desktop

* **Platform**: 
macos 10.12.5

![27349484-6c512078-55c5-11e7-9244-965a1cf7db2d](https://user-images.githubusercontent.com/1874874/27394890-dc1745e8-567b-11e7-951c-3b42c36de602.png)

**Comment by bolekkerous** [comment]
Hey, @whoiskjl -
could you please send us the sample of the problematic design to team@avocode.com?

Thanks!

**Comment by whoiskjl** [comment]
I have sent the file to the email given. Thank you

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. There should also be the full Postscript font name in the style panel available.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
