### ISSUE TITLE
Asset Export Issue

### ISSUE THREAD

**Issue by darshanasen** [avocode/avocode#1494]
* **Version**: 2.14.4

* **Web/Desktop**: Desktop

* **Platform**: Windows 7 64 bit

I'm unable to export certain assets from a PSD. I'm able to select "Export" and download them. However, the file which is exported is very small (3 KB) and when I open it it's just a blank file (despite the attached dimensions on the file being accurate.)

**Comment by connor-bean** [comment]
Would you be able to send us the problematic file to team@avocode.com?

**Comment by jakubzitny** [comment]
Hi @darshanasen, is this happening to all assets or just some? Which format are you exporing to? JPG, PNG or SVG? Is the same happening to all export formats? Are the layers masked by clipping masks by any chance? Thanks for you replies :)

**Comment by ozzyosborne680** [comment]
Hi @jakubzitny 

I have the same issue and mine is due to clipping masks. Don't suppose you know of a fix?

**Comment by jakubzitny** [comment]
Thanks for the info @ozzyosborne680.

Can you give me more details on your thing? Is your design from Sketch? Is the clipping mask empty? Which formats are you exporting to? Is the same happening for all export formats or not?

If it's not a sketch file with empty clipping mask, we'd need to examine you design if you're willing to send it to team@avocode.com.

**Comment by ozzyosborne680** [comment]
Hi @jakubzitny 

Thanks for the reply.

The design is indeed Sketch.
It is happening to all export formats (I couldn't test SVG).
The clipping mask has the image I need to export in it. example structure(s) attached.

![screen shot 2017-06-30 at 09 36 27](https://user-images.githubusercontent.com/6939017/27727739-b3251ff4-5d77-11e7-8b76-f715410323ac.png)

![screen shot 2017-06-30 at 09 40 26](https://user-images.githubusercontent.com/6939017/27727872-2e434dd2-5d78-11e7-8d0b-fe24f1791b8e.png)

Funny thing is it doesn't seem to happen to all masked images however from what I can see the structure is exactly the same between the ones that are working and not. (Maybe it isn't to do with the mask but I'm not sure what else it could be).

Attached structure of one that is working.

![screen shot 2017-06-30 at 09 43 23](https://user-images.githubusercontent.com/6939017/27727996-970017e2-5d78-11e7-8ad2-f0de3638c374.png)

I'd be happy to send over the design for your testing if you think that'll help.

Thanks

**Comment by jakubzitny** [comment]
Thanks, I see. The fact that it is not happening to similarly masked layers is weird. Please send us the sketch file to team@avocode.com, we'll have look at it and we'll try to fix it.

**Comment by vojtatranta** [comment]
@ozzyosborne680 if you want to export an image with clipping mask you have to export both - masked layer and the mask. I think clipping masks work OK. I was resolving similar issue last week and everything was OK.

**Comment by ozzyosborne680** [comment]
Hi @vojtatranta 

Thanks for the advice however exporting the masks was the first thing I tried.
Even selecting every layer in the design results in white spaces where the images should be.

Any other suggestions would be appreciated.

**Comment by jakubzitny** [comment]
Hey guys @ozzyosborne680 and @darshanasen, is there any chance you're having a blending mode applied to the mask layer?

**Comment by ozzyosborne680** [comment]
Hi @jakubzitny 

The groups containing the images and masks have pass through enabled. 
The images themselves don't have anything; And the ones that do seem to work are also done the same way.

Thanks for the continued debugging :)

**Comment by jakubzitny** [comment]
Hi @ozzyosborne680, our rendering team will work on this and similar issues for next couple of weeks/months, we're implementing a new engine that should handle similar cases properly. We'll update you when it's ready.

**Comment by ConduciveMammal** [comment]
I've been suffering with this issue too for months, along with others in my office. It seems to be related to having masks in the same layer group but disabling them has no effect.

However, I found a nice little workaround for the meantime, export the image as Base64 and then paste the code into a [Base64 converter](https://codebeautify.org/base64-to-image-converter) and it'll get you the image you want. It's not a perfect solution but a useable one.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. 

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
