### ISSUE TITLE
Avocode can't export from Sketch after update

### ISSUE THREAD

**Issue by ronaldpushpay** [avocode/avocode#1496]
2.14.4

Desktop

MAC OS Sierra 10.12.5 

After updating to the latest Avocode, I can't export artboards from Sketch anymore. It kept coming up with the message below. Please advise.
![screen shot 2017-06-23 at 3 33 07 pm](https://user-images.githubusercontent.com/29169551/27465722-68d7f1f4-5829-11e7-9401-ef64ec59d622.png)

**Comment by bolekkerous** [comment]
Hey -
have you tried reinstalling the application? It looks like the application might be either somehow renamed or corrupted.

Here's a download link:

https://avocode.com/download

**Comment by jakubzitny** [comment]
Hi @ronaldpushpay, we changed the behaviour of how Avocode opens. It will be included in the next release `2.14.5` which will available today.

**Comment by jakubzitny** [comment]
We've just released `2.14.5`, please update the app and let us know if you have any more problems 😉
