### ISSUE TITLE
UI is frozen while some psd file is downloaded/rendered

### ISSUE THREAD

**Issue by ZuBB** [avocode/avocode#1497]
* **Version**: latest as of today

* **Web/Desktop**: Desctop

* **Platform**: Macos, latest version as of today

STR:
* doble click on some tile to make that page/file (downloaded and) rendered.
* click on '+' button to create new tab

AR: after click nothing happened
ER: downloading/rendering should happen in separate thread

**Comment by bolekkerous** [comment]
Hey - 
I just tried that and it does work for me - showing the new tab takes a little longer than usual, but then you should be able to browse projects and even open another design.

Can you still reproduce that same behaviour?

Could you possibly send us a video or screenshots of the problem?

Thanks!

**Comment by vojtatranta** [comment]
@ZuBB opening a design is quite intense work. We are aware of that app lags during opening of a design but we are not able to do anything with that at the moment.

Saying that, we are working on a fix which should improve rendering much faster!
