### ISSUE TITLE
Typo on "Getting Started" tab

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#150]
There's a small typo on the "Quick overview" section - it's labeled as "Quick overiew":

![quick-overview](https://cloud.githubusercontent.com/assets/5463/6346808/3833f638-bc13-11e4-9a3f-f55708efe176.jpg)

**Comment by petrbrzek** [comment]
Thanks for reporting. We're simplifying the entire section, so it won't be the issue anymore.

**Comment by tomashanacek** [comment]
Fixed in Avocode 2.0.0
