### ISSUE TITLE
upload design process failed

### ISSUE THREAD

**Issue by luckinamargo** [avocode/avocode#1506]
Which version of avocode are you using? 
2.14.4

Are you using the web or desktop version of Avocode?
Desktop

What OS are you using? If you use the web version, which browser are you using? 
Ubuntu 16.04

**Comment by luckinamargo** [comment]
![screenshot from 2017-07-04 13-44-15](https://user-images.githubusercontent.com/22146672/27818226-fbba0b54-60be-11e7-93cd-f112ff68616e.png)

**Comment by jakubzitny** [comment]
Hi @luckinamargo, thanks for reporting your problem. Have you tried uploading different files that worked? Have you tried uploading this once more to see if it still fails? Would you mind sending us the PSD design to team@avocode.com so we can inspect the problem and upload the file for you?

**Comment by luckinamargo** [comment]
Thank you for answer. My designer says it was problem with psd file so I
have uploaded another one :) and you needn't uploaded it manually, thanks

2017-07-04 14:42 GMT+07:00 Jakub Žitný <notifications@github.com>:

**Comment by jakubzitny** [comment]
Thanks for the info. I am going to close this issue then.

Feel free to let us know if you have any more problems with Avocode 😉

**Comment by rihbim** [comment]
But we still have this problem with upload design in Avocode from Sketch

Sketch version 45.1
Avocode 2.14.4
Plugin Avocode 43

**Comment by luckinamargo** [comment]
Thank you!

2017-07-04 22:03 GMT+07:00 rihbim <notifications@github.com>:

**Comment by jakubzitny** [comment]
Can you please create a new issue with more details, please @rihbim? We'll be releasing new patch version `2.14.5` today with some fixed for Sketch uploads. What exactly do you have problem with?
