### ISSUE TITLE
Windows client 1.1.1 missing login fields?

### ISSUE THREAD

**Issue by UXdesignThought** [avocode/avocode#151]
The windows client doesn't seem to have login fields? The Mac client is working fine.

![screenshot](https://cloud.githubusercontent.com/assets/8730261/6599706/b1bbb0c0-c7e1-11e4-8fee-b834919c1d17.PNG)

**Comment by halpermk** [comment]
I am having the same problem with the Windows client and version 1.1.1 - cannot log in. When I click "Login to Avocode" it seems to do nothing until you click "Taking too long? Cancel login."

**Comment by UXdesignThought** [comment]
In the Avocode terminal window, I'm seeing this after a while: "Authenticate error: Error: connect ETIMEDOUT", source: c:\users\...\recources\app\node_modules\avocode\lib\auth.js (6)

**Comment by UXdesignThought** [comment]
Not sure anyone is having this issue, but here's the screenshot of the terminal window

![terminal](https://cloud.githubusercontent.com/assets/8730261/6599717/c68c32f4-c7e1-11e4-8edf-9c8f85bc85e1.PNG)

**Comment by petrbrzek** [comment]
Sorry for this annoying issue. We'll add a proper login form in the next release.

**Comment by tomashanacek** [comment]
Fixed in Avocode 2.0.0
