### ISSUE TITLE
CANT INSTALL SKETCH PLUGIN

### ISSUE THREAD

**Issue by danigalindo** [avocode/avocode#1510]
IMPORTANT: Please try to describe how did it happen.
I wento to menu HELP>REINSTALL SKETCH PLUG IN and got this message " Failed to Resinstall Skectch plus ing, click here to report issue"
-----
App v. `2.14.5`
Avocode UID: 160674
```
Error: Sketch is not installed.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1878166
```

**Comment by jakubzitny** [comment]
Hi @danigalindo, thanks for reporting your problem. Where do you have your Sketch app installed and how is it named? We're looking into `/Applications` and `/Downloads` by default.

Can you please check the access rights and/or run these couple of commands from Terminal with appropriate path to your Sketch app, to help us debug your problem?
```
pluginsPath=`/Applications/Sketch\ asd.app/Contents/Resources/sketchtool/bin/sketchtool show plugins`

echo "$pluginsPath"
ls -ld "$pluginsPath"
ls -l "$pluginsPath"
```

**Comment by jakubzitny** [comment]
Hey @danigalindo, do you happen to have any more info on this? Do you still have problems with installing our plugin, please?

**Comment by jakubzitny** [comment]
Hi @danigalindo, we've released new version of Avocode, can you please try it and see if you can install the plugin?
