### ISSUE TITLE
filed upload

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#1511]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.5`
Avocode UID: 31535
```
Error: ENOENT: no such file or directory, stat '/var/folders/gh/kx_l710j4s35tnp5qlmrvpjc0000gn/T/com.madebysource.avocode/avocode-sync-1499505574116/D988E5EB-2F4E-4526-A6EE-5826131A9ADF/7245F047-6D0C-4285-8570-5442CA5458B5.png'
```

**Comment by jakubzitny** [comment]
Hi @Webdesme, thanks for reporting this. I believe this is a problem with syncing larger/older Sketch files we still have in latest version. We'll be trying to fix this as soon as possible.

**Comment by jakubzitny** [comment]
Hi @Webdesme, we've just release new version of Avocode, please update and let us know if you still have problems with it 😉
