### ISSUE TITLE
Avocode interface from version 12.13 is not working

### ISSUE THREAD

**Issue by shamboo** [avocode/avocode#1512]
Version: 2.14.5
Web/Desktop: Desktop
Platform: macOS 10.12.6

Macbook Pro mid 2010
Intel HD Graphics 288 МБ and NVIDIA GeForce GT 330M

Avocode interface from version 12.13 is not working. Projects are not displayed

![2017-07-09 13 43 07](https://user-images.githubusercontent.com/1628257/27993178-d708cb1e-64ac-11e7-9253-2b4cf8c3e90e.png)
![2017-07-09 13 43 51](https://user-images.githubusercontent.com/1628257/27993177-d7087b1e-64ac-11e7-9702-e7b8669c023a.png)
![2017-07-09 13 43 56](https://user-images.githubusercontent.com/1628257/27993179-d709861c-64ac-11e7-8006-3b3991112d54.png)

**Comment by jakubzitny** [comment]
Hi @shamboo, thanks for letting us know. We have never experienced such a thing so any details on your environment (Mac model, graphics card, ...) will help us with debugging this further. Are you by any chance using hackintosh or macOS inside a virtual machine? Can you check out issue #1490 to see if you're experiencing something similar?

**Comment by shamboo** [comment]
Macbook Pro mid 2010
Intel HD Graphics 288 МБ and NVIDIA GeForce GT 330M

**Comment by jakubzitny** [comment]
Allright, I think we'll be able to release a fix for this in the next version. This is the same as #1490, so I'll close this issue and we'll let you know there when new version is available. It should be no later than Wednesday this week.

**Comment by shamboo** [comment]
fixed!! thank you!
