### ISSUE TITLE
Alpha Image Exports

### ISSUE THREAD

**Issue by morcegon** [avocode/avocode#1516]
* **Version**: 2.15.5

* **Web/Desktop**: Desktop

* **Platform**: MacOS 10.12.5

This:

![screen shot 2017-07-11 at 13 05 20](https://user-images.githubusercontent.com/31614/28077963-a1e9d3cc-6639-11e7-9e4d-f9bf08f73b35.png)

Export result:

![screen shot 2017-07-11 at 13 02 56](https://user-images.githubusercontent.com/31614/28077924-89e46594-6639-11e7-8cab-aa068ed70f5d.png)

**Comment by jakubzitny** [comment]
Hi @morcegon, can you please send us the design to team@avocode.com, so we can further debug this issue?

**Comment by lalondan** [comment]
I'm having the same issues. Was this solved?

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. 

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
