### ISSUE TITLE
PSDs with large layers (like 2880 x 6800 px) often fail to process

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#152]
PSDs with large layers (like 2880 x 6800 px) often fail to process. We need to improve the layers export process

**Comment by VadimZhiltsov** [comment]
Hey, guys. Any news on this issue?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by VadimZhiltsov** [comment]
Great! Thank you, now it's working :)
