### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KMADr** [avocode/avocode#1524]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.14.5`

**Comment by jakubzitny** [comment]
Hi @KMADr, do you mind sharing more info with us? What platform are you using? What happened when you saw this error?

I can see that you are using older version of Avocode. Please update the app to `2.14.6` and let us know if you have any other problems.

**Comment by KMADr** [comment]
i trying to update, but he doesn't want. He write download updating... and all, after nothing happens

**Comment by jakubzitny** [comment]
@KMADr are you on Linux or Windows? Can you try downloading the app again from [avocode.com/download](https://avocode.com/download) ?

**Comment by KMADr** [comment]
i'm using windows, ok i try again reinstall app

**Comment by jakubzitny** [comment]
Is it 32-bit Windows or 64? Do you mind sharing the version as well?

**Comment by KMADr** [comment]
windows 64, i'm reinstalled the app, but the problem didn't disapper, black window when i copy picture. It happens only with one picture, with the rest there are no problems.

**Comment by jakubzitny** [comment]
What picture are you copying? Are you copying `base64` or anything else? Would you mind taking a screenshot or a video of the problem so we know what to fix? Or send us the design you are using to team@avocode.com?

**Comment by KMADr** [comment]
https://manager.avocode.com/view/d40ab37db35e44259ab5c25784a37a69/
png/jpg
stephen colbert don't copy
