### ISSUE TITLE
Does not load Sketch design

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1529]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.6`
Avocode UID: 68767
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by Pavlo-Minkievych** [comment]
Having chosen the option of downloading the entire design, Avocode has been trying to synchronize the design for a long time, it looks like a cyclically moving strip and then it stops this operation and then nothing happens

**Comment by jakubzitny** [comment]
Closing with respect to #1531.
