### ISSUE TITLE
After logging in with incorrect email or pass, can only type 1 letter at a time in email input

### ISSUE THREAD

**Issue by brianedelman** [avocode/avocode#1530]
2.14.6

* **Version**: 

* *Desktop**:

Using OSX 10.12.5

After logging in to the app with incorrect credentials, if I try to edit the email input I can only type 1 character before my cursor is forced back to the password line. To edit the email, I'd have to go through this process for every single letter.

![screen shot 2017-07-14 at 2 19 05 pm](https://user-images.githubusercontent.com/14008969/28225287-24e4eb32-68a0-11e7-928a-5938be3d4f49.png)

**Comment by jakubzitny** [comment]
Hi @brianedelman, thanks for reporting this. It's a bit annoying, I can reproduce it, we will fix it in upcoming release 😉

**Comment by jakubzitny** [comment]
Hi @brianedelman, we've fixed this in the latest Avocode `2.14.7`.

Please let us know if you have any more problems with Avocode 😉
