### ISSUE TITLE
At boot time Sketch design crash occurred

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1531]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.14.6`

**Comment by Pavlo-Minkievych** [comment]
Choosing the download option for the whole design Avocode for a long time trying to synchronize the design looks like this is a cyclically moving bar and then reaching 1% the download stops and information is displayed that the download failed and you need to repeat it. Repeated downloading will bring to the same error.

**Comment by jakubzitny** [comment]
Thanks a lot for the info @Pavlo-Minkievych, we have your file, we're looking into this. I think we can close #1529 and discuss the whole issue here (and in Intercom), it's probably the same problem. Thanks for the file and for helping us with debugging.

**Comment by jakubzitny** [comment]
We've fixed this as well in `2.14.7`, please update and let us know if you have any more problems 😀
