### ISSUE TITLE
avocode crashed when open .psb files

### ISSUE THREAD

**Issue by LitvinenkoEvgeny** [avocode/avocode#1533]
IMPORTANT: Please try to describe how did the crash happen.
Hi, i'm trying to open .psb file which size ~400mb and avocode crashed with error
`
[24187:24221:0717/133232.045107:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

`
App v. `2.14.1`

**Comment by bolekkerous** [comment]
Hey, it looks like you're using an old version of Avocode.

Could you try updating it in the app menu (Check for updates) or if it doesn't work, then download a fresh version from here?

https://manager.avocode.com/downloads/

**Comment by jakubzitny** [comment]
Hi @LitvinenkoEvgeny, when you update the app and it's still happening, please let us know what platform are you using. Is it Windows? Is it 32-bit? I tried PSB upload just now, and it seems to be working, the problem might be in the specific file you are trying to upload. If it's still not working, please send the file to team@avocode.com so we can debug it more thoroughly.

Thanks 😉

**Comment by LitvinenkoEvgeny** [comment]
Hi @jakubzitny here is uname output:
`uname -a
Linux user 4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:29:33 UTC 2017 i686 i686 i686 GNU/Linux`
actually, i'm remove some big layers using photoshop and reduce file size from 400mb to 87 and it works after update

**Comment by jakubzitny** [comment]
Thanks for the info, I'm happy to hear that it kinda works after reducng the file size. Can you still send us the original design, so we can inspect the main problem there?

**Comment by LitvinenkoEvgeny** [comment]
Sorry for so long wait, link to .psb file
http://dropmefiles.com/kItig

**Comment by jakubzitny** [comment]
This should be fixed in latest Avocode 2.20.0. Please update and let us know if you're still having problems 😉
