### ISSUE TITLE
Design failed processing

### ISSUE THREAD

**Issue by easynowbaby** [avocode/avocode#1534]
* **Version**: 2.14.6

* **Web/Desktop**: Desktop

* **Platform**:  iOS

Design failed processing

**Comment by bolekkerous** [comment]
Hey, @easynowbaby -
is the design PSD or Sketch file?

**Comment by easynowbaby** [comment]
@bolekkerous it's a PSD

**Comment by bolekkerous** [comment]
I see - have you tried uploading it through the Photoshop plugin?

If you don't have access to Photoshop plugin, please send us the design to team@avocode.com and we should be able to upload it for you.
