### ISSUE TITLE
Failed to process design

### ISSUE THREAD

**Issue by Arhane** [avocode/avocode#1536]
* **Version**: 
Avocode 2.14.6

* **Web/Desktop**:
Desktop

* **Platform**: 
Linux Ubuntu 17.04
Windows 7

I failed to upload a design.
Then I divided it to pieces. 
Every piece was uploaded successfully except one.
I tried to remove a part with a big image and only then it worked.

[This is the piece that not worked](https://manager.avocode.com/view/181f32ba07b14c4aaf530d753e8f132a/)

[This is the image in the right part of the piece](https://manager.avocode.com/view/ba2eacb2acaa4974aaa3eb6a43d0c64c/)
Probably, the image was an svg but I am not sure of that

**Comment by jakubzitny** [comment]
Amazing report, thanks a lot for the details @Andrew1024 😜 

We'll look into it and come back to you with more info.

**Comment by jakubzitny** [comment]
This should be fixed in latest versions of Avocode so I am going to close this.

Please let us know if you have any other problems 😉
