### ISSUE TITLE
Firefox design bug

### ISSUE THREAD

**Issue by Purecoder** [avocode/avocode#1539]
* **Web**:

* **Firefox version 54.0.1 (32-bit)**: 

On firefox when i open layouts left side slide down and outside.
First : http://imgur.com/D1OesHw
Last : http://imgur.com/xXKwdVl

**Comment by jakubzitny** [comment]
Hi @Purecoder, thanks for the info. Our web version is currently in Beta mode, so we only support Chrome right now. However, we're tuning the last details for supporting other browsers right now and we'll soon release it and let you know.

I'll keep this open so we don't forget about this particular case.

**Comment by Purecoder** [comment]
Yes i know beta version. I seen "this work just chrome and firefox" ! I usually use firefox. So i reported :) No problem. Thank you.

**Comment by bolekkerous** [comment]
Hey, @Purecoder -
does this still happen to you? 

When I tried it now, there is a scrollbar that should be visible, so i'll close this now. :)

If you still can reproduce it, feel free to reopen the issue.
