### ISSUE TITLE
Avocode App tabs - indicate the version number

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#154]
Indicate the revisions/version.

ex: 
![issue-revison-tabs](https://cloud.githubusercontent.com/assets/3017112/6379322/5956e770-bcff-11e4-891b-8624e3bd3f72.jpg)

**Comment by petrbrzek** [comment]
You will see the current design revision in `Info panel`.

![screen shot 2015-04-09 at 21 24 22](https://cloud.githubusercontent.com/assets/879564/7074975/def77ce8-defe-11e4-84d2-d06a4a4f02b9.png)
