### ISSUE TITLE
getaddrinfo EAI_AGAIN manager.avocode.com:443

### ISSUE THREAD

**Issue by potalok88** [avocode/avocode#1542]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.2`
Avocode UID: 31535
```
Error: getaddrinfo EAI_AGAIN manager.avocode.com:443
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

**Comment by connor-bean** [comment]
Hello @potalok88 -

Does this still happen when you update your app to 2.14.8?

**Comment by jakubzitny** [comment]
Hi there, can you please try reproducing this in the latest Avocode `2.15.0`? You can download it from [avocode.com/download](https://avocode.com/download) or use auto-update to install it. Please give it a try and let us know if this issue still persists or you have any other issues.
