### ISSUE TITLE
Import sketch

### ISSUE THREAD

**Issue by teremok1000** [avocode/avocode#1544]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.7`
Avocode UID: 4043
```
Error: ENOENT: no such file or directory, stat '/var/folders/1r/0sgfr1vn7yv_zkh435zr2wy80000gn/T/com.madebysource.avocode/avocode-sync-1500886259909/6656A53E-AB81-4535-BD18-AC033AEFAAA7/9AF003E3-A82D-4995-9BEE-636D9A66B0F9.png'
```

**Comment by jakubzitny** [comment]
Hi @teremok1000, would you mind sharing the Sketch file that got you this error please? You can send it to team@avocode.com. Can you also verify that the Avocode plugin version in your Sketch is 43.7?

**Comment by teremok1000** [comment]
Sorry I can not give away the sketch file it is from the customer, the version is yes 43.7

**Comment by jakubzitny** [comment]
Right, so was this happening to the same file for you in older versions as well? Or is it happening to different Sketch files for you?

I have a tip for you on how to sync the file, if the file has many artboards, try to sync them one by one. Also if it has symbols as well, try ignoring the symbols (use `Sync Without Symbols` menu item) and see if that works. 

It will help us a lot if you try these steps if you have time 😊

**Comment by jakubzitny** [comment]
This is probably similar to #1551, I'll close this and let's continue with the conversation there. We'll be trying to fix this issue till next release.

**Comment by jakubzitny** [comment]
Hi @teremok1000, can you please try updating your plugin from [this link](https://upx.cz/iYd) and see if it helps with syncing your file?

**Comment by teremok1000** [comment]
Hi all ok!!!

**Comment by jakubzitny** [comment]
Thanks a lot.

Please let us know if you have any more problems with Sketch sync or anything else 😉
