### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by tfurukawa3pc** [avocode/avocode#1545]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.7`
Avocode UID: 10439
```
TypeError: o.replace is not a function
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:599078)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:597707
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3018:46
    at List.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2208:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3017:23)
    at seqIterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:322:14)
    at IndexedIterable.toArray (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4260:23)
    at new List (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:2067:62)
    at reify (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:3572:37)
    at List.map (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/immutable/dist/immutable.js:4403:14)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:597682)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:595019
```

**Comment by jakubzitny** [comment]
Hi @tfurukawa3pc, thanks for reporting this. Is this Sketch od PSD upload? Is it happening to you all the time or only for a specific file, you're trying to upload? Would you be willing to share the file with us at team@avocode.com, please?

**Comment by tfurukawa3pc** [comment]
Hi @jakubzitny thank you for your quick message.
This happened with the Sketch upload. I figured out that this bug happened with a specific Artboard in a Sketch file. The Artboad is called 'kosmos_06_detail', which contains quite a lot of picture files and the hight is longer (5080pt) than other Artboards.
I sent the file to team@avocode.com. Hope you guys can figure out what happened.

**Comment by jakubzitny** [comment]
Amazing @tfurukawa3pc, thanks for the file and info, I am looking into it.

**Comment by jakubzitny** [comment]
Hey, so I tried to upload your file using both *CMD+ALT+E* (uploading all artbaords) and also *CMD+E* only on the artboard you mentioned and everything uploaded correctly. Can you please check that the plugin installed in your sketch is `43.7`? and possibly update it from [here](https://manager.avocode.com/download/sketch-plugin-new/mac/)?

I'll try it few more times in the meantime :)

**Comment by tfurukawa3pc** [comment]
Hey, I downloaded the plugin and now upload works! Thanks for checking everything.

I needed to update the Avocode App today. Although, I thought the plugin update was automatically done during the app update, I think it didn't happen.

**Comment by jakubzitny** [comment]
Awesome, thanks for checking that.

Yeah, it should be automatically updated during the app update. I'd like to ask few more questions then. Can you please check the access rights to the sketch plugins folder? Where is your app located? Can you try deleting the plugin in Sketch and run `Reinstall Sketch plugin` from Help -> Troubleshooting menu, please? Does it show any error or just fails silently?

**Comment by tfurukawa3pc** [comment]
Hey,

I revealed the Sketch plugins and deleted 'Avocode.sketchplugin'. Then went to Avocode App and did 'Reinstall Sketch plugin' from Help -> Troubleshooting.

In the Avocode app's notification, it showed 'Plug-in successfully installed', but when I looked at the Sketch plugin folder, there is still no Avocode.sketchplugin installed.

Then I tried to delete 'avocode-token.json' as well and did the same procedure from Avocode App, but the result was the same..

**Comment by jakubzitny** [comment]
I see, one possible cause might be that you have a different Sketch hidden somewhere, or that the access rights are handled incorrectly on our side.

Can you open the Terminal app and run these commands please?
```
loc=`/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool show plugins`
echo $loc

ls -l "$loc"
ls -ld "$loc"
```

The output will be the location of your Sketch plugins folder and the access rights on the folder and inside it as well. It should work if you have Sketch.app in `/Applications`, is that right?

**Comment by tfurukawa3pc** [comment]
I tried the Terminal command and it showed something interesting.

Terminal indicated the plugin folder as here:
/Users/turukawa/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3
And I can still see 'Avocode.sketchplugin' in this folder.

But if I reveal the plugin folder from Sketch it comes here:
/Users/turukawa/Library/Application Support/com.bohemiancoding.sketch3/Plugins
And there is no 'Avocode.sketchplugin'  in this folder.

So it means I have a different Sketch hidden in different folders...

**Comment by jakubzitny** [comment]
I see, this is good find. Maybe it's the problem in Sketch itself, that it reports different plugin locations internally and via command line.

What version of Sketch do you have, please and what version of macOS?

We will certainly add a better detection for the plugin locations for next versions of Avocode.

**Comment by tfurukawa3pc** [comment]
Alright, my Sketch is Version 45.2. And macOS is 10.12.5.
I think Sketch has made a major update at the version 44.1. Probably this major update caused some problems to those plugin/app integration.. Let me know if you find something.
Meanwhile, I am fine that Avocode is working well for the time being ;)

**Comment by jakubzitny** [comment]
I personally also have the same versions of both and I get only one location. I will just improve the location resolver and copy the plugin to both locations if I find them.

Thanks a lot for the cooperation.

I think we can close this issue for now 😉
