### ISSUE TITLE
Add Cache assets

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#155]
Adding a cache will be nice. So, when you open the design for the first time, Avocode load all the assets, but if you close your design, then reopen it (same version), Avocode does not load the assets (image data) again from the cloud. 

It will be more faster.

**Comment by dongepulango** [comment]
+1

**Comment by petrbrzek** [comment]
Actually, it's a bug in image loading #172 . We already cache the assets.

**Comment by petrbrzek** [comment]
Should be fixed. Feel free to reopen it.
