### ISSUE TITLE
Avocode crashes during uploading

### ISSUE THREAD

**Issue by nickvelichkin** [avocode/avocode#1552]
Hi guys,
a new problem here. Recently I've updated the app and sketch plugin and now I just can't upload anything. I've tried to delete a project and start a new one, but it didn't work. 

App v. `2.14.7`

**Comment by jakubzitny** [comment]
Hi @nickvelichkin, thanks for letting us know. We've found out a problem with auto updating in the last version of Sketch and Avocode, some people did not get the last plugin of ours. We're working on improving the auto-updating.

In the meantime, please install the latest version from [here](https://upx.cz/iYd) and let us know if it helps 😉

**Comment by jakubzitny** [comment]
Hi, we've fixed this problem in latest Avocode `2.14.8`, please update the app and let us know if you have other problems or issues :wink:
