### ISSUE TITLE
Sketch not loading

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1553]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.7`
Avocode UID: 68767
```
Error: connect ETIMEDOUT 52.70.75.29:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

**Comment by Pavlo-Minkievych** [comment]
During the download of the sketch design there is an error

**Comment by jakubzitny** [comment]
Hi @Pavlo-Minkievych, thanks for the report. Can you try loading the design in web version at [app.avocode.com](http://app.avocode.com) to see if it works there, please?
