### ISSUE TITLE
Can't sync artboards after update

### ISSUE THREAD

**Issue by n0rule5** [avocode/avocode#1557]
IMPORTANT: Please try to describe how did it happen.

I'm running Sketch 43.2

-----
App v. `2.14.7`
Avocode UID: 35475
```
Error: ENOENT: no such file or directory, stat '/var/folders/_v/_rj2h6wx4595wcr_nh82v50m0000gn/T/com.madebysource.avocode/avocode-sync-1501100145616/6CF1D6B3-C39F-4E50-896A-076765182221/06408627-4D66-4A8D-AEB0-E47168D21B27.png'
```

**Comment by jakubzitny** [comment]
Hi @n0rule5, thanks for letting us know. Can you please try to download [this version](https://upx.cz/iYd) of plugin, double click to update it in Sketch and try again?

**Comment by n0rule5** [comment]
Thanks, that worked!
