### ISSUE TITLE
Error upload

### ISSUE THREAD

**Issue by maximr89** [avocode/avocode#1558]
* **Version**: 2.14.7

* **Web/Desktop**: Desktop

* **Platform**:  Linux

**Comment by jakubzitny** [comment]
Hi @maximr89, what exactly were you uploading and how did it fail? Do you have problems with uploading a specific file or you cannot upload anything at all? Does it fail during uploading or you can see a red tile with "Processing failed" message?

**Comment by maximr89** [comment]
У меня ничего не загружается. Выдает ошибку "Processing failed"

2017-07-27 17:05 GMT+03:00 Jakub Žitný <notifications@github.com>:

**Comment by bolekkerous** [comment]
Hey, @maximr89 - could you please send us the problematic design to team@avocode.com? We should be able to upload it for you. :)

**Comment by maximr89** [comment]
А у меня их несколько, я же не могу их все присылать

2017-07-27 17:12 GMT+03:00 Bolek <notifications@github.com>:
