### ISSUE TITLE
Exporting multiple SVG's at once.

### ISSUE THREAD

**Issue by matvividu** [avocode/avocode#156]
When exporting—PNG's and JPG's can be exported in multiples. In my example I'm exporting 3 shape layers. Individually I can export each one as an SVG without issue, however when I select 3 simultaneously, add a variant of "separately" exporting, and choose SVG, my exported files appear with a ".undefined" extension. 

I've also tried renaming the files before exporting to "color-bar-1" "color-bar-2" and "color-bar-3", hoping the difference in names might be the solution. No luck. I have found no way to export multiple SVG's at the same time.

I've uploaded 2 attachments, one showing the highlighted layers, with SVG desired extensions selected, and one showing the exported files and "undefined" extensions.

![svg-1](https://cloud.githubusercontent.com/assets/11200012/6380626/0409ed9e-bd09-11e4-9001-3793aa0fe4cb.png)
![svg-2](https://cloud.githubusercontent.com/assets/11200012/6380629/0706c8f0-bd09-11e4-96ac-1803d9430894.png)

**Comment by timkelty** [comment]
+1

**Comment by verteb** [comment]
+1

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
