### ISSUE TITLE
I try to reinstall Sketch plugin, but not work!.

### ISSUE THREAD

**Issue by kiennguyen1994** [avocode/avocode#1560]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.7`
Avocode UID: 169085
```
Error: Sketch is not installed.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1881428
```

**Comment by jakubzitny** [comment]
Hi @kiennguyen1994, thanks for letting us know. It seems we have problems detecting the location of your Sketch.app. Where is it located, please, and how is the app bundle named?

We're able to detect Sketch only if it is installed in `/Applications` or `~/Downloads` and only if the app is called `Sketch.app` of `Sketch Beta.app` or `Sketch 2.app` or a different number after that. Please move it to `/Applications` and/or rename it for this to work.
