### ISSUE TITLE
No upload

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#1565]
Hi, today from morning to Moscow time, I found out that the artboards do not load, I've been waiting for two hours, the file in the program has been processed, but the server does not boot, there are no errors that it can be (?   (sketch) 2.14.8

http://www.lavuix.ru/scr/170801093626.png

**Comment by Webdesme** [comment]
Just add that constantly hanging notifications that the layout is loaded, when you click on it nothing happens and the notification does not disappear http://www.lavuix.ru/scr/170801093442.png

**Comment by jakubzitny** [comment]
Hi @Webdesme, thanks for the report. This might be similar to #1564 and #1563, can you have a look there please if it's similar to you?

Can you try opening the designs at [app.avocode.com](http://app.avocode.com)?

Do you get any failed red tiles in project manager or nothing at all? Does the upload progress bar in notifications panel finish to 100% or it just disappears? Is it happening to PSDs as well, or just Sketch files? How about uploading one more time, does it do exactly the same thing? Would you be willing to record a video of what is happening when you upload files?

What OS are you using, please? The other two issues are from Linux, is it your case as well?

**Comment by jakubzitny** [comment]
Also @Webdesme, if you're on Linux, this might be similar to #1363, where the cause of the problem was incorrect computer clock time. Can you check if that's correct?

**Comment by Webdesme** [comment]
I can not upload the video, give a little time I will describe the problem when I try all the boot options and see all possible logs from my side

**Comment by Webdesme** [comment]
1. I do not get red tiles. First, the tile is gray, then the inscription appears in the tile image 22, so it hangs for two hours, yesterday everything was loaded.
Http://www.lavuix.ru/scr/170801130929.png
2. In the application, the notification is hanging that the "1905" layout has been loaded and it does not disappear.
3. Load sketch files. Photoshop layouts are loaded normally
4. I work for macos
I can not send the video, but there will not be anything, just press cmd + e, switch to avocode application, the layout turns, but then the download freezes by 0%

**Comment by Webdesme** [comment]
Also when you click on the button http://www.lavuix.ru/scr/170801131826.png too quickly synchronized although the layout 72

**Comment by Webdesme** [comment]
Can I roll back to 2.14.7?

**Comment by jakubzitny** [comment]
Right, thanks for the info. So the loading stays at 0% all the time, right? Did you check the issue #1363 where fixing or changing the computer clock helped with similar probleml, please?

**Comment by jakubzitny** [comment]
You can download the previous version from [here](https://media.avocode.com/download/avocode-app/2.14.7/Avocode-2.14.7.dmg), but the latest one is much faster and has many fixes for legacy Sketch files.

**Comment by Webdesme** [comment]
With the clock everything is fine, on all devices the same time

**Comment by Webdesme** [comment]
Yes download all the time at 0%

**Comment by jakubzitny** [comment]
Can you try playing around with the computer clock? We had a guy from Kaliningrad, where computer clock was correct, but the system-detected time zone was 1 hour away. He tried setting the clock +1 or -1 hour and everything started working. 😀 Can you try it, please?

Or does the old version work for you?

**Comment by Webdesme** [comment]
The old version is working, the new one has not yet been installed

**Comment by jakubzitny** [comment]
Hi @Webdesme, can you please check if this is still happening in `2.15.0`?

**Comment by Webdesme** [comment]
Hi, everything is fine, sometimes there are errors, but this is already due to the network, was on vacation)

**Comment by jakubzitny** [comment]
Thank you, let us know if you have any more problems with Avocode :wink:
