### ISSUE TITLE
App is not loading on Windows 10

### ISSUE THREAD

**Issue by Treyarch** [avocode/avocode#1566]
* **Version**: 2.14.8

* **Web/Desktop**: Desktop

* **Platform**: Windows 10

App is not loading. It installs fine, I can see the entry in my Application Manager saying it's installed, I can see the process running in my Task Manager but nothing is showing on screen. The app is simply not loading.

**Comment by Treyarch** [comment]
Earlier versions (2.14.6) are not loading either :-(

**Comment by millerf** [comment]
Did you try version 2.13.0?

See here, seems like the same bug:
https://github.com/avocode/avocode/issues/1335

**Comment by bolekkerous** [comment]
Hey - can you see the icon in your start bar as well? It might be possible that the app is somehow minimized or dragged off screen. Could you check whether that might be the case? You can try using Alt + Right click in the Windows toolbar.

**Comment by Treyarch** [comment]
Nope, not working, I've tested the 2.13.0 and same problem. And I do not have the app offscreen, it's not even showing up in my task bar.

I can see the background process but that's all. I get the install screen that says, please wait while the app is installing and once finished the app will launch but it's never launching.

What could be the problem ? It's the first time I get this kind of problem. Is there some dependency I'm missing somehow ?

**Comment by Treyarch** [comment]
Tried rebooting and running as Admin but no luck there.

**Comment by jakubzitny** [comment]
Maybe I found another similar problem in #1116.

Can you try launching the app from the command line with the following command?
```
Avocode.exe -- --dev-tools
```

Or just go to Avocode.exe properties and add `-- --dev-tools` parameters to `target` field like we've tried [here](https://github.com/avocode/avocode/issues/1116#issuecomment-248441230) and run it again. Notice the extra `--` before the `--dev-tools` though.

**Comment by Treyarch** [comment]
Tried it but did not work either. I tried running in Windows 8 compatibility but it does not do anything more.

**Comment by jakubzitny** [comment]
It didn't work, but did you get any messages in the command line?

**Comment by Treyarch** [comment]
No, it seems similar to #1116 I agree - I get the processes but nothing is launching.

**Comment by Treyarch** [comment]
And no, no messages...

**Comment by jakubzitny** [comment]
And did you use Avocode before or it just started happening suddenly after update to `2.14.8`?

**Comment by Treyarch** [comment]
Nope, never used it before, first install !

**Comment by jakubzitny** [comment]
Allright, we need to look into this more thoroughly, however, we usually don't have problems like this with Windows users and if we cannot reproduce it, we don't really know how to fix it. If you try reinstalling your system, you might give it a try.

In the meantime, why don't you try our web version at [app.avocode.com](http://app.avocode.com)? 😛

**Comment by Treyarch** [comment]
Thanks, I can't really reinstall at this time, it would take too much time and I did it not so long ago so maybe next time. The online app seems to work fine for now !

**Comment by jakubzitny** [comment]
Hi @Treyarch, do you still have problems with running Avocode desktop app? Have you tried it for past few versions, please?

**Comment by Treyarch** [comment]
Hi @jakubzitny ,

Sorry, I havent used Avocode on any projects since then, so I cannot really tell but I managed with a workaround with the online web app at the time.

**Comment by jakubzitny** [comment]
Thanks for the info. Hit me up here or our support if you want to give it a try again in the future 😉
