### ISSUE TITLE
Transitory "Importing..." thumbnails do not clear

### ISSUE THREAD

**Issue by jacolson** [avocode/avocode#1569]
Desktop Avocode 2.14.8 on macOS Sierra 10.12.6

On upload of selected artboards from Sketch 46 build 44423, infrequently (3 out of ~20 imports today) these processing thumbnails stay on screen. 

-- Can't delete (menu appears under other nails, and even with careful selection of delete - it does nothing.) 
-- Do not clear out when:
   a) quitting & relaunching app
   b) reinstalling plugin & reimporting/uploading same artboards
-- can't delete from web interface in Chrome

Only thing I found was blowing away entire project, creating new project and reimporting everything ...which, of course, is no solution.

See attached screenshot of stuck thumbnails.

thanks
Jeff

![image](https://user-images.githubusercontent.com/27443258/28899924-5c86fc9a-77a2-11e7-8ba8-40a218fdf42f.png)

**Comment by jacolson** [comment]
Restarted mac and thumbnails cleared out this time. Go con/figure...

**Comment by jakubzitny** [comment]
Hi @jacolson, thanks for reporting this, we know about this problem and it will be fixed for the next major release of Avocode - `2.15.0`.
