### ISSUE TITLE
AvoCode Reinstall Plugin 

### ISSUE THREAD

**Issue by Omaretz** [avocode/avocode#1571]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 170010
```
Error: Sketch is not installed.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1882336
```

**Comment by jakubzitny** [comment]
Hi @Omaretz, thanks for reporting this. Avocode automatically detects `Sketch.app` location when it is located in `/Applications` or `~/Downloads` and it is named `Sketch.app` or `Sketch Beta.app` or `Sketch 2.app` or other numbers. Please move your Sketch to such a location and the installation will work.

If you can't move/rename it that way, please download the latest Sketch plugin from [here](https://manager.avocode.com/download/sketch-plugin-new/mac/) manually.
