### ISSUE TITLE
May it just work?

### ISSUE THREAD

**Issue by nickvelichkin** [avocode/avocode#1572]
Guys, these days avocode is a big waste of time..
I spend like 5-10 mins to make a small changes in sketch and another 20-30 to understand why avocode crushed again. 

P.s. I have last version of app and sketch plugin.

IMPORTANT: Please try to describe how did the crash happen.

App v. `2.14.8`

**Comment by bolekkerous** [comment]
Hey, @nickvelichkin - 
sorry for the inconvenience - we would need some more info to figure out what's going wrong.

Did the app actually crash during the sync? How exactly did it happened? Could you send us the Sketch file where the crash happened to team@avocode.com?

Thanks and sorry for the inconvenience once again.

**Comment by jakubzitny** [comment]
Also is it the same thing you had problems with in #1552 or is it something different? Did anything work in the meantime?

**Comment by nickvelichkin** [comment]
It worked, but only for a few days

**Comment by jakubzitny** [comment]
So what exactly does not work for you? Can you describe what did you try to do and what crashed? If you don't want to write it you can record a video of whatever you're trying to do.

Also, what platform are you on? Is it macOS?

**Comment by connor-bean** [comment]
Hey @nickvelichkin  -

what exactly does not work for you? Can you describe what did you try to do and what crashed? If you don't want to write it you can record a video of whatever you're trying to do.

Also, what platform are you on? Is it macOS?

**Comment by connor-bean** [comment]
Hey @nickvelichkin -

We replied to your email you sent to team@avocode.com. We will close this Github ticket here and continue to work with you in the email thread you started. Thanks!
