### ISSUE TITLE
Sketch Guides

### ISSUE THREAD

**Issue by morcegon** [avocode/avocode#1573]
* **Version**: 2.14.8

* **Web/Desktop**: Desktop

* **Platform**:  OSX

Why generated guides on Skecth dont show on Avocode?

**Comment by jakubzitny** [comment]
Hi @morcegon, if your guides are attached to an artboard in Sketch, they should be available in Avocode. You just have to click the `GUIDES` button on bottom right.

Can you confirm that this works for you, please?

**Comment by morcegon** [comment]
I messed up the name. The guides is ok. The problem is on grid layout. There are a way to show this on Avocode?

**Comment by jakubzitny** [comment]
Right, this is currently not supported in Avocode, but as more and more people are requesting it, we'll probably add it some time soon. We're already tracking this feature request here in #422 and also on our UserVoice. Feel free to vote for the feature [here](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/10188261-support-viewing-sketch-layout-grid-in-avocode-mang) or any other issues you would like to see in Avocode.

Do you use only grids in Sketch, or also custom layouts?

**Comment by morcegon** [comment]
We use custom layouts to support a lot of projects based on Bootstrap or same other 12 colums grid layout. The guides will help to mark up the front end code.

**Comment by jakubzitny** [comment]
Thanks for the info. We'll update you when this feature is available :wink:

**Comment by morcegon** [comment]
Thanks ;)

On Fri, Aug 4, 2017 at 11:55, Jakub Žitný <notifications@github.com> wrote:
Thanks for the info. We'll update you when this feature is available 😉
