### ISSUE TITLE
Color Tool 

### ISSUE THREAD

**Issue by morcegon** [avocode/avocode#1574]
* **Version**: 2.14.8

* **Web/Desktop**: Desktop

* **Platform**:  OSX 10.12.6 (16G29)

The code of color picked in color tool is different from original color:

The color I want:
![screen shot 2017-08-03 at 13 25 57](https://user-images.githubusercontent.com/31614/28932389-b14d2102-784f-11e7-9d64-9338784935d1.png)

CSS Code:
![screen shot 2017-08-03 at 13 26 04](https://user-images.githubusercontent.com/31614/28932403-bc555952-784f-11e7-8d26-9edccced07db.png)

Color picked by color tool:
![screen shot 2017-08-03 at 13 26 42](https://user-images.githubusercontent.com/31614/28932421-c4c78056-784f-11e7-98a1-3a43376914d2.png)

**Comment by jankuca** [comment]
The displayed color on the canvas is actually `#deac20` which is what is copied by the Color Picker Tool. There is probably some blending applied to the layer (such as opacity change, blending mode other than Normal, or a color overlay effect).

If you need to copy the color displayed in the code panel, please do so from there.

**Comment by morcegon** [comment]
There are no blend mode on this layer. 

![screen shot 2017-08-04 at 11 15 46](https://user-images.githubusercontent.com/31614/28972518-5b2e3db2-7906-11e7-9b95-cf84fe180916.png)

We've made this test:
 - Open the design in skecth, the color code is `#e2b522`;
 - Take a print screen from sketch and opened in photoshop. Using the eyedrop tool the result on this color is `#e2b522`;
 - The same print on Illustrator results in `#e2b522`;
 - The print taked on Avocode in Photoshop results in different color code;
 - The color tool in Avocode result in different color code;
 - Selecting the vector on Avocode result in a background color code right, in this case `#e2b522`;
 - In other Mac, the wrong color code is different from mine;

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. It was caused by color profiles, which should be ignored with the new rendering engine.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
