### ISSUE TITLE
When importing embeded document the layout disappears[P

### ISSUE THREAD

**Issue by grantorin** [avocode/avocode#1576]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.14.8`

When importing embeded document 

http://joxi.ru/l2ZYjMDh87Lx1m

**Comment by jakubzitny** [comment]
Hi @grantorin, thanks for reporting this, we'll look into it. Is it Sketch or PSD design? Does the double click to open the embedded designs work? Would you be willing to send us the design to team@avocode.com so we can have a closer look at it?

**Comment by grantorin** [comment]
Hi, jakubzitny. This is PSD design. Yes, the double click opens the document. Sent the design to email. Thanks for the answer.

**Comment by jakubzitny** [comment]
Hi @grantorin, I did not realise this yesterday, but this is not a problem with our processing. It is actually a problem within the app, that it crashed during upload, right?

Can you please try uploading it again? It worked for me, so the error is probably something unrelated to this particular file and it might upload correctly for you too.

**Comment by grantorin** [comment]
Hi, jakubzitny, Thanks, I'll try
