### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by Anenth** [avocode/avocode#1579]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 97759
```
Error: connect ENETUNREACH 52.70.75.29:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

**Comment by jakubzitny** [comment]
Hi @Anenth, thanks for reporting this. When exactly is this happening? Did it happen more than once? It looks like a slow connection to me, are you behind some sort of a proxy server?

**Comment by connor-bean** [comment]
Hi @Anenth, thanks for reporting this. When exactly is this happening? Did it happen more than once? It looks like a slow connection to me, are you behind some sort of a proxy server?

**Comment by connor-bean** [comment]
Please comment if you can provide more information and we will continue troubleshooting
