### ISSUE TITLE
font-family: OpenSans    ??? no space

### ISSUE THREAD

**Issue by teremok1000** [avocode/avocode#158]
http://joxi.ru/9E2p9BeF8eEeAY
more psd bag

**Comment by VPenkov** [comment]
This isn't considered a bug (https://github.com/avocode/avocode/issues/86).

**Comment by petrbrzek** [comment]
This is not a bug. You can use variables to replace it for wheather you want.

![screen shot 2015-04-09 at 21 23 10](https://cloud.githubusercontent.com/assets/879564/7074954/abeabcca-defe-11e4-96b5-ce6da5b4c972.png)
