### ISSUE TITLE
Impossible to reinstall the sketch plugin

### ISSUE THREAD

**Issue by fyneDC** [avocode/avocode#1581]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 86698
```
Error: Sketch is not installed.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1882336
```

**Comment by jakubzitny** [comment]
Hi @fyneDC, where is you Sketch located and how is it named? We're automatically detecting Sketch in Applications an Downloads folder, so if yours is anywhere else it might be a problem.

For now, you can install the latest plugin from [here](https://avocode-media.s3.amazonaws.com/download/sketch-plugin-new/45.2.0/sketch-plugin-new-mac-45.2.0.sketchplugin.zip), but I'd like to see why this fails for you.

**Comment by fyneDC** [comment]
It's ok ! I downloaded the plugin and it works! Thank you

**Comment by jakubzitny** [comment]
@fyneDC Can you please give me some info about your system or the original Sketch location or something like that? I would like to know why this does not worked for you in the first place so we can fix it for other user with the same problem.

**Comment by jakubzitny** [comment]
Closing with respect to #1595.
