### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ozimnadius** [avocode/avocode#1582]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.14.8`

**Comment by jakubzitny** [comment]
Hi @Ozimnadius, thank you for reporting this issue. However, we need more details to be able to prevent it from happening in the future. Did it happen more than once? When exactly did it happen? Also, what platform do you use, please?

**Comment by connor-bean** [comment]
Hi @Ozimnadius, thank you for reporting this issue. However, we need more details to be able to prevent it from happening in the future. Did it happen more than once? When exactly did it happen? Also, what platform do you use, please?

**Comment by Ozimnadius** [comment]
Just once. Windows 8.1.01.09.2017, 11:36, "Connor" <notifications@github.com>:Hi @Ozimnadius, thank you for reporting this issue. However, we need more details to be able to prevent it from happening in the future. Did it happen more than once? When exactly did it happen? Also, what platform do you use, please?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




--

**Comment by jakubzitny** [comment]
This should not be happening in the latest Avocode `2.15.0`, please let us know if this problem still persists.

**Comment by Ozimnadius** [comment]
Avacode when you copy text converts &#10 &#8233. Which leads to the problem on Android http://joxi.ru/Y2LBJYOTn8R9kr  --

**Comment by jakubzitny** [comment]
Can you elaborate please @Ozimnadius? You have problems specifically with `&#10` and `&#8233`? Is it when you copy from text layer or from code panel? What would you expect to have copied?  Is it maybe related to #1653?
