### ISSUE TITLE
SVG exporting artifacts

### ISSUE THREAD

**Issue by darginyegor** [avocode/avocode#1583]
Avocode for Linux v2.14.8
Look what i got exported some layers to svg...
###### (Part of images is blured because of copyright)

What i see in avocode:
![2017-08-16 15-58-50](https://user-images.githubusercontent.com/22341230/29358266-33070e6e-829c-11e7-9fc7-e45930ce0f5a.png)

What was exported:
![logo](https://user-images.githubusercontent.com/22341230/29358278-49c25366-829c-11e7-9e9c-87a7641334c0.png)

**Comment by darginyegor** [comment]
Oops... looks like this happened again:
![2017-08-16 17-23-57](https://user-images.githubusercontent.com/22341230/29361150-0a00aab4-82a8-11e7-989e-6e000b88e961.png)

![icon-draw](https://user-images.githubusercontent.com/22341230/29361146-057b16c8-82a8-11e7-82ee-7ad65d157b4e.png)

**Comment by jakubzitny** [comment]
Hi @darginyegor, we've just release Avocode 2.15 with improved SVG export. Please update the app and let us know if this issue still persists.
