### ISSUE TITLE
Error Sketch is not installes

### ISSUE THREAD

**Issue by Flewr** [avocode/avocode#1584]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 175779
```
Error: Sketch is not installed.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1882336
```

**Comment by connor-bean** [comment]
Hello @Flewr - where is you Sketch located and how is it named? We're automatically detecting Sketch in Applications an Downloads folder, so if yours is anywhere else it might be a problem.

For now, you can install the latest plugin from [here](https://manager.avocode.com/download/sketch-plugin-new/mac/), but I'd like to see why this fails for you.

**Comment by connor-bean** [comment]
Hello @Flewr - where is you Sketch located and how is it named? We're automatically detecting Sketch in Applications an Downloads folder, so if yours is anywhere else it might be a problem.

For now, you can install the latest plugin from [here](https://manager.avocode.com/download/sketch-plugin-new/mac/), but I'd like to see why this fails for you.

**Comment by jakubzitny** [comment]
Closing with respect to #1595.
