### ISSUE TITLE
Sketch artboards sync

### ISSUE THREAD

**Issue by vsiestov** [avocode/avocode#1587]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 7389
```
Error: ETIMEDOUT
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/request/request.js:813:19
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Hi @vsiestov, thanks for letting us know. Have you tried this more than once? Is it happening all the time, or just this one time? Have you managed to upload something to Avocode at all?

**Comment by vsiestov** [comment]
Hi @jakubzitny, Yes, I tried this more the once. It happened every time when I try to sync all artboards at once. After that happened I tried to sync one by one and it also did not work, it started working one by one after reloading the app. Sometimes I had to repeat the same artboard several times because it disappeared after synchronization

**Comment by jakubzitny** [comment]
@vsiestov did you try it with different Sketch files and is it happening to all of them? We've not heard about these kind of problems for a while from users. It use to be happening for large and complicated files. Would you be willing to send us the design to team@avocode.com please? We will try to upload it for you and also find the underlying issue.

**Comment by connor-bean** [comment]
@vsiestov did you try it with different Sketch files and is it happening to all of them? We've not heard about these kind of problems for a while from users. It use to be happening for large and complicated files. Would you be willing to send us the design to team@avocode.com please? We will try to upload it for you and also find the underlying issue.

**Comment by vsiestov** [comment]
I've just sent it to team@avocode.com

**Comment by jakubzitny** [comment]
Thanks for the files @vsiestov, I will close this thread with respect to #1677.
