### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by Faxef** [avocode/avocode#1598]
Good afternoon. When using the Avocode trial version, any .psd layouts are not downloaded either in the Windows application or in the beta version of the web application. All versions and applications are recent.
-----
App v. `2.15.0-beta.1-e3dff64-wfc0c9a6`
Avocode UID: 180143
```
value@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:17:109951
value@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:79:410253
value@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:79:411822
WORKSPACE:ITEM_URI_UPDATE@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:79:408536
r/<@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:48:2199198
e.prototype._invokeCallback@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:79:424855
e.prototype.dispatch@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:79:424670
value@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:48:2198981
value@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:48:2197403
value@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:61:208352
e.prototype.redirectActiveItemToUri@https://cdn.app.avocode.com/dist/v-18e7ddf/js/avocode-web.min.js:61:120630
value@https://cdn.app
```

**Comment by vojtatranta** [comment]
That's firefox I suppose?

**Comment by Faxef** [comment]
Yes

**Comment by vojtatranta** [comment]
@Faxef could you please take a look into network console a see which requests fail?

I just tried Firefox and it works fine :(

In genral. Avocode was developed on Chromium platform which is Webkit. Firefox has different Javascript engine which may cause issues.

Maybe try update you Firefox or use Chrome which is much stable in terms of Javascript execution.

**Comment by Faxef** [comment]
@vojtatranta, here's what happened.
Loading .psd layout using a web application. View a network console.

1.   <a href="http://www.picshare.ru/view/8256778/" target="_blank"><img src="http://www.picshare.ru/uploads/170829/Cl6Zu1zUkL_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a>

There is loading .psd layout through the application on Windows(Avocode 2.14.8).
1) <a href="http://www.picshare.ru/view/8256779/" target="_blank"><img src="http://www.picshare.ru/uploads/170829/7ieMO8vMwR_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a>
2) <a href="http://www.picshare.ru/view/8256777/" target="_blank"><img src="http://www.picshare.ru/uploads/170829/hTMCE50K8M_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a>
3) <a href="http://www.picshare.ru/view/8256780/" target="_blank"><img src="http://www.picshare.ru/uploads/170829/UG1MlsteT4_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a>

Firefox has the latest update. In Chrome the same situation

**Comment by vojtatranta** [comment]
@Faxef so the upload of a design in a browser does not work, right?

And opening a design in desktop app does not work too, right?

**Comment by vojtatranta** [comment]
@Faxef can you please send use how the one of the failed `OPTIONS` requests to `cloudfront.designs.avocode.com` looked like? Just click on it and in the right you'll see request headers and response headers.

Thanks

**Comment by Faxef** [comment]
@vojtatranta yes, that's it

**Comment by Faxef** [comment]
@vojtatranta there is only a request, there is no answer
<a href="http://www.picshare.ru/view/8256809/" target="_blank"><img src="http://www.picshare.ru/uploads/170829/G21o4TxQ68_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a>

**Comment by vojtatranta** [comment]
@Faxef hmmm, this request seem ok.

Is there some error in the console? Is there real reason why this options request failed? Something like "Cross origin request failed"?

**Comment by Faxef** [comment]
@vojtatranta no, there are no such mistakes. Only a very long search for DNS. And that's all.

**Comment by vojtatranta** [comment]
@Faxef strange.... Have you tried upload on Chrome? CHrome displays CORS error nicely in the console.

But firefoxu should not.

Basically `OPTIONS` request takes place when a request is heading to different domain than current one.

If this requests fails browser does not attempt to make a new "proper" POST or GET request due to cross origin policy. 

But header in the Cross origin header is set to `app.avocode.com` and that's correct. It should not work anybody if this does not work for you.

I need more details on that.

**Comment by Faxef** [comment]
@vojtatranta in chrome, a similar problem.
1)<a href="http://www.picshare.ru/view/8256932/" target="_blank"><img src="http://www.picshare.ru/uploads/170829/n78qVaTbzy_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a>

2)<a href="http://www.picshare.ru/view/8256935/" target="_blank"><img src="http://www.picshare.ru/uploads/170829/57mU66B7UT_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a>

**Comment by vojtatranta** [comment]
@Faxef aha, strange. It says that it cannot resolve DNS of `https://cloudfront.designs.avocode.com/`

Strange. Can you try to write `ping cloudfront.designs.avocode.com` into the command line?

I am curious whether the DNS name would be resolved to IP address.

**Comment by Faxef** [comment]
@vojtatranta i just recently pinged this server. Everything was also inaccessible.
But it seems I have found a solution to the problem.
I removed the automatic DNS lookup at computer, and installed them manually (I used Google Public DNS). In a web application, everything works.
And the application on Windows earned too

**Comment by Faxef** [comment]
@vojtatranta thanks for your help in solving the problem, and rapid response!

**Comment by vojtatranta** [comment]
@Faxef you are welcome!

Thank you for patience!
