### ISSUE TITLE
Open new psd - Error occured

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#160]
The first I open a new psd, an error occured.

Workflow:
* Upload the psd on the manager
* open the psd with Avocode app (error)
* Click cancel, then re-open the psd, works

http://recordit.co/oe7esFFKlf (start the video at 1:15)

**Comment by rychlis** [comment]
Hi, this bug should be fixed in Avocode 2.0. Feel free to reopen this issue if the problem persist
