### ISSUE TITLE
Previews not generated when uploading multiple assets

### ISSUE THREAD

**Issue by nblackburn** [avocode/avocode#1605]
* **Version**: 2.14.8
* **Web/Desktop**: Desktop
* **Platform**: Windows (x64)

When uploading multiple assets at the same time, previews no longer seem to generate.

**Comment by bolekkerous** [comment]
Hey, @nblackburn -
is this something you can still reproduce now?

I believe we had a small hiccup in the service that was generating the previews, but it should now be already fixed.

**Comment by nblackburn** [comment]
@bolekkerous Seems fine now, thanks for looking into this for me.
