### ISSUE TITLE
Transparency inside svg shape filled with surrounding color

### ISSUE THREAD

**Issue by verteb** [avocode/avocode#161]
For example this svg : 
![right](https://cloud.githubusercontent.com/assets/635248/6419561/482764be-be8c-11e4-916c-acebbf061b7b.jpg)
Will be exported to svg this way : 
![wrong](https://cloud.githubusercontent.com/assets/635248/6419582/5fb5b77a-be8c-11e4-98db-bc675347176b.jpg)

**Comment by petrbrzek** [comment]
Missing brain in exported SVG is also an issue or not?

**Comment by verteb** [comment]
The missing brain is the issue. Whenever there is transparency inside a vector shape, avocode fills the transparency with the surrounding color on svg export.

**Comment by verteb** [comment]
Our designers use Sketch by the way if it might help...

**Comment by MatthewDaniels** [comment]
Is the brain portion a mask within Sketch? 

ie: is the brain part supposed to be a clipping element?

I ask as I think this is similar to an issue that I am having - just checking in on other issues before posting a new one :)

**Comment by marekhrabe** [comment]
Hi, can you try resync the document and try to export that image again? We implemented boolean operations (that is the thing that makes transparency inside of shapes) a few releases ago. Can you confirm this works for you?
