### ISSUE TITLE
Sketch Plugin Error

### ISSUE THREAD

**Issue by rehakilicspexco** [avocode/avocode#1612]
IMPORTANT: Please try to describe how did it happen.

-----
App v. `2.14.8`
Avocode UID: 184791
```
Error: Sketch is not installed.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1882336
```

**Comment by connor-bean** [comment]
Could you please try opening your desktop app and then reinstalling the Sketch plugin from the Help menu?
​

![image](https://user-images.githubusercontent.com/17878371/30214652-8305a88a-94ad-11e7-84a7-b7036c3d87fa.png)
 

​

​
 

After you click that, a notification should pop-up in the top right corner.
​
Either the installation will be successful, or you should see a failed notification. If it fails, please click on the notification and it should lead you to GitHub. Then please copy and paste the contents of the error report here in the chat. :)
​
And before you try that, please make sure that your Sketch application is named exactly "Sketch", not something like "Sketch_2" and also make sure it is located either in the Applications or Downloads folder.

**Comment by jakubzitny** [comment]
Closing with respect to #1595.
