### ISSUE TITLE
trouble

### ISSUE THREAD

**Issue by lumenio** [avocode/avocode#1614]
* **Version**: 2.15.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 130056
---

```
Error: Sketch is not installed.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3304546
    at <anonymous>
```

**Comment by bolekkerous** [comment]
Hey, @lumenio -
could you please make sure that your Sketch application is called exactly "Sketch", not something like "Sketch_2". And also make sure the Sketch application is located in Applications or Downloads folder.

After you check that, you can go into your desktop application and in the system Help menu go to Troubleshooting > Reinstall Sketch plugin.

It should then fire a notification whether the installation was successful or not.

**Comment by jakubzitny** [comment]
If it's still happening afterwards, there might be another problem which we're already tracking in #1595. So I am closing this issue as duplicate.

If you're still not able to install the plugin after renaming/moving it, please download it directly from [here](https://avocode-media.s3.amazonaws.com/download/sketch-plugin-new/46.2.4/sketch-plugin-new-mac-46.2.4.sketchplugin.zip).
