### ISSUE TITLE
does not correctly display the sketch design

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1615]
does not correctly display the sketch design

**Comment by jakubzitny** [comment]
Thanks @Pavlo-Minkievych, sorry to hear that you have a problem with Sketch designs again. Any further details on this? Would you be willing to send us the design to team@avocode.com?

**Comment by bolekkerous** [comment]
Hey, @Pavlo-Minkievych -
are you still experiencing the problem now?

If so, could you please send us the problematic design to team@avocode.com, so we can investigate on our end?

Thanks and sorry for the inconvenience.
