### ISSUE TITLE
SVG export

### ISSUE THREAD

**Issue by janekh** [avocode/avocode#1617]
* **2.15.1**: 

* **Desktop**:

* **Windows 64bit**: 

After the recent update SVG export is unusable. It adds the Position value of the element to the SVG and 14px x 14px image becomes for example 325px x 496px SVG. It worked correctly in previous version.

**Comment by vojtatranta** [comment]
What do you mean by "Position value"?

**Comment by qbz** [comment]
@janekh can you please attach any file you getting this issue with? Or atleast any screenshot of this bug. Thanks.

**Comment by janekh** [comment]
Here is the example. In design view I have following:
![design](https://user-images.githubusercontent.com/1406171/30360157-6b62eec8-9858-11e7-8ecb-bdfb77040ea3.png)
When I export as SVG I get 
![design - chrome](https://user-images.githubusercontent.com/1406171/30360251-f9cf67cc-9858-11e7-93d2-f46973c123c7.png)
When I export as PNG I get
![testlink](https://user-images.githubusercontent.com/1406171/30360267-097c6364-9859-11e7-920e-a5317e2f0361.png)

The SVG is positioned at the same place as it is in the original design. That's the position I was referring to (In Avocode - right column "Position:" value). The SVG source is here:

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="325" height="496" viewBox="0 0 325 496"><defs><path id="a" d="M317 489.56a2.98 2.98 0 0 0 4.52.32l1.8-1.8a3 3 0 0 0-4.24-4.24l-1.03 1.03"/><path id="b" d="M319.17 488.2a3.03 3.03 0 0 0-4.53-.32l-1.8 1.8a3 3 0 0 0 4.24 4.24l1.03-1.02"/></defs><desc>Generated with Avocode.</desc><g><use fill="#fff" fill-opacity="0" stroke="#a8a8a8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="50" stroke-width="1.5" xlink:href="#a"/><g><use fill="#fff" fill-opacity="0" stroke="#a8a8a8" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="50" stroke-width="1.5" xlink:href="#b"/></g></g></svg>`

Couple of days ago I exported the same SVG and got this
![design - chrome - previous](https://user-images.githubusercontent.com/1406171/30360352-845cfd8c-9859-11e7-91be-72214572ce30.png)

**Comment by jakubzitny** [comment]
Thanks @janekh, this is certainly a bug, we'll fix it for the next release :wink:

**Comment by qbz** [comment]
Thanks for explanation, now I understand what failure you are talking about. But, unfortunately, I still can not reproduce this situation. Can I ask you to send an original design file, or, atleast, any similar design with this behavior? Thanks again.

**Comment by jakubzitny** [comment]
This should be fixed in Avocode 2.15.5, please update the app and let us know if you have any more problems with it :wink:
