### ISSUE TITLE
Missing layers in PSD layouts

### ISSUE THREAD

**Issue by web2easy** [avocode/avocode#1618]
* **2.15.1**

* **Desktop**

* **Windows 10**

Missing layers in PSD layouts, but there is no problem on web version.

Desktop sample:
![2017-09-13_00-36-49](https://user-images.githubusercontent.com/5243967/30349510-e7aaffda-981b-11e7-8833-368814c63aca.png)
Web sample:
![2017-09-13_00-37-20](https://user-images.githubusercontent.com/5243967/30349522-f202dc3c-981b-11e7-8804-497d765bb9ac.png)

**Comment by jakubzitny** [comment]
Hi @web2easy, thanks for reporting this, we'll look into it. Would you be willing to send us the design to team@avocode.com?

**Comment by web2easy** [comment]
With version 2.15.3 there is no problem.
