### ISSUE TITLE
Brakes on the mac

### ISSUE THREAD

**Issue by teremok1000** [avocode/avocode#1622]
Hello very much starts to brake in 5-8 minutes after the program is turned on. mackintosh os sierra, avocode desktop version 2.15.2
problems started about 2 weeks ago

**Comment by teremok1000** [comment]
oh sorry my os el capitan

**Comment by teremok1000** [comment]
install latest version and no lags and problem
please improve your app

**Comment by jakubzitny** [comment]
Hi @teremok1000, thanks for letting us know, however, we need more info on this. What did break after 5-8 minutes? And which version you installed that works OK, `2.15.1`?

**Comment by teremok1000** [comment]
2.14.8 stable and fast work
no 5-8 min, sometimes even immediately lags

**Comment by jakubzitny** [comment]
Is is during syncing Sketch files, or even when just using the app (clicking and opening designs)?

**Comment by teremok1000** [comment]
no open and generation sketch, psd small and large

**Comment by jakubzitny** [comment]
Hi @teremok1000, we've just released Avocode 2.24.0 with the ability to upload Sketch files directly via drag&drop. Can you try uploading them that way and see if it improves your workflow?
