### ISSUE TITLE
Avocode always syncing

### ISSUE THREAD

**Issue by n0rule5** [avocode/avocode#1625]
* **Version**: 2.15.2
* **Sketch plugin version**: 46.2.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 35475
---

Avocode sync button always shows "syncing" (animation is always playing). ¯\_(ツ)_/¯

```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @n0rule5, we've released new version of Avocode yesterday and this has been fixed in it. Please update and let us know if you have any more problems with it 😉
