### ISSUE TITLE
Hard to navigate around a design

### ISSUE THREAD

**Issue by davidkelley** [avocode/avocode#163]
I use a mouse with my laptop, its very difficult to navigate around the designs as there are no scrollbars visible on the screen. I am constantly having to switch to my touchpad to move horizontally around designs.

Perhaps zooming in around the mouse pointer might be beneficial?

**Comment by rychlis** [comment]
Not sure if you know about that, but you can move around the design by holding spacebar, clicking and moving mouse. Is that sufficient?

**Comment by petrbrzek** [comment]
Can we close this one?

**Comment by VaclovasV** [comment]
@rychlis then I first time turned on avocode, window without any scrollbar was confusing too. user is not aware, how long he has to scroll to the end of canvas. 
this was confusing for other team members too (we had design with sliding left sidebar and at first it looked like avocode is rendering sketch files incorrectly)
