### ISSUE TITLE
advertising avocode in svg ?? Really?

### ISSUE THREAD

**Issue by markello-git** [avocode/avocode#1636]
remove this garbage from svg (<desc> Generated with Avocode. </ desc>). The meaning of cleaning code if it has unnecessary lines ?!

* **Version**: 2.15.3

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 8627
---

```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @markello-git, we're sorry, this should not be included in optimized SVG. The fix will be included in the next release.

**Comment by jakubzitny** [comment]
This has been fixed in Avocode 2.15.5, please update the app and let us know if you have any more problems with it :wink:
