### ISSUE TITLE
Scale issue

### ISSUE THREAD

**Issue by Winni-** [avocode/avocode#1639]
* **Version**:  2.15.3

* **Web/Desktop**: Desctop

* **Platform/Browser**: Win10

If i use my mouse wheel to scale design, every time i try to scale down it makes it 20%, i want to back up a little bit, but no, here you have 20%. 
And when i scale with mouse wheel i can have 20 - 45 - **101**, there are some magic numbers!

**Comment by bolekkerous** [comment]
Hey, @Winni- 
I've tried to reproduce the issue on Windows, but I haven't really managed to do that.

Is it possible that you're using some special mouse wheel setting on your computer?

How is your mouse wheel set up in preferences? 

![image](https://user-images.githubusercontent.com/16084852/30808493-9a0b83b6-a1fe-11e7-8706-97b51f2d9248.png)

**Comment by nikitosss** [comment]
I have similar problems with scaling

Version: 2.15.4
Web / Desktop: Desktop
Platform / Browser: Win10 64bit

The mouse scrolling settings are the default 3 lines. If set to 1 line, then scaling works fine, but such settings cause inconvenience when scrolling in text editors =)

**Comment by i-v-k** [comment]
Samr problem

Version: 2.15.5 (problem appeared in 2.15.3)
Web/Desktop: Desktop
Platform: win32 (Win10 64bit)
Avocode UID: 112740

Problem appeared in v2.15.3.
In early releases there were no such problem.
The mouse scrolling settings are the default all the time.

**Comment by monti84** [comment]
Same problem.
https://github.com/avocode/avocode/issues/1659
You can mark my thread as a duplicate.

**Comment by jakubzitny** [comment]
Thanks guys, we'll look into this first thing next week 🙂

**Comment by jakubzitny** [comment]
Hi guys, this problem should finally be fixed in latest Avocode `2.16.2`. Please update and let us know if you find any other problems :wink:

**Comment by i-v-k** [comment]
Thanks!
