### ISSUE TITLE
main bg shows only half, overlay is not visible

### ISSUE THREAD

**Issue by resoursa** [avocode/avocode#164]
1. In psd file the main bg is fullwidth, but in avocode it have only half width.
2. The overlay effect is not visible, but it visible in manager.
![screenshot_030415_112557_am](https://cloud.githubusercontent.com/assets/739188/6480936/a7691a5c-c261-11e4-9bfa-a3b0e2e25569.jpg)
![screenshot_030415_112528_am](https://cloud.githubusercontent.com/assets/739188/6480937/a769ae90-c261-11e4-8d7f-fcce04476854.jpg)

**Comment by kupcza** [comment]
I had same or similar issue. Problem was, that our designer uses older version of PS and when I opened it in CC2014 and uploaded it looked like yours design. But when I saved it, reopened it and reuploaded that design, it worked. Don't know why.

**Comment by resoursa** [comment]
@kupcza unfortunately not working for me. :pensive:

**Comment by kupcza** [comment]
@resoursa are you using layercomps? Sometimes got problems with them while exporting, but I don't know under what circumstances.

**Comment by resoursa** [comment]
@kupcza yeah, my designer using layer comps. :smile: Raw application, i`ts too early pay for it. :disappointed:

**Comment by kupcza** [comment]
@resoursa well, there's nothing wrong with them, but sometimes I have problems with them and I don't know why. I think main problem is that he uses CS6 and I CC2014. Try to switch betweem them. Are all layers in correct place?

**Comment by petrbrzek** [comment]
It's kinda hard to reproduce this. Could you send us the design to team[at]avocode.com? It'd be helpful.

**Comment by petrbrzek** [comment]
Should be fixed with the latest update. Can you confirm that?
