### ISSUE TITLE
Too many pages in Sketch design in Project Manager

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#1641]
Tags written in two lines do not fit and look like separate words, can they somehow be made more compact? 
http://www.lavuix.ru/scr/2017-09-25_17-07-45.png

**Comment by bolekkerous** [comment]
Hey, @Webdesme -
that doesn't look right. Could you please send us the original design to team@avocode.com, so we can try replicate the problem and fix it?

Thanks!

**Comment by Webdesme** [comment]
Hello! File sent to mail

**Comment by jakubzitny** [comment]
This will be fixed in the next release of Avocode next week 🙂

**Comment by jakubzitny** [comment]
Hi, this should be fixed in latest Avocode `2.16.2`. Please update and let us know if you find any other problems :wink:

**Comment by Webdesme** [comment]
I did not expect so many updates in my life) thanks!
