### ISSUE TITLE
Unable to install the sketch plugin.

### ISSUE THREAD

**Issue by SanchitS** [avocode/avocode#1642]
* **Version**: 2.15.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 77101
---

```
Error: Sketch is not installed.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3307686
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @SanchitS, thanks for reporting this. We already know that some users have problems with automatic installation of our Sketch plugin. We're tracking it already in #1595, so I'll close this issue. We'll be trying to fix it soon for everyone.

For now, can you give us more info on where is your Sketch.app located and how is it named? Do you have english localization of your macOS? We're detecting Sketch only in `~/Downloads` and `/Applications` and it has to be named `Sketch.app` or `Sketch 2.app` or a different number, or `Sketch Beta 2.app` or similarly.

**Comment by jakubzitny** [comment]
As a workaround for now, please download the plugin manually from [here](https://avocode-media.s3.amazonaws.com/download/sketch-plugin-new/45.2.0/sketch-plugin-new-mac-45.2.0.sketchplugin.zip).
