### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#1644]
I have one main account and the second one for developers. So on the second account, where the rights are assigned only for some projects http://www.lavuix.ru/scr/2017-09-27_15-07-37.png, an error occurs when logging into the web application http://www.lavuix.ru/scr/2017-09-27_15-09-24.png. Tell me, what could be the problem?

**Comment by Webdesme** [comment]
http://www.lavuix.ru/scr/2017-09-27_15-11-44.png in the application is the same

**Comment by bolekkerous** [comment]
Hey -
this should now be fixed, does it work for you now?

**Comment by Webdesme** [comment]
Thank you! Everything is working!:thumbsup::fire:
