### ISSUE TITLE
Error on app startup with Ghostery

### ISSUE THREAD

**Issue by zatziky** [avocode/avocode#1645]
Everytime I try to enter your app I receive a popup saying an error occured. Without Ghostery plugin the app starts up fine.

![image](https://user-images.githubusercontent.com/2794365/30957750-6ec9a4a0-a43b-11e7-9904-dceda7ea5e37.png)

* **Version**: 2.15.5-web.1-w79e4e52

* **Web/Desktop**: Web

* **Platform**: windows 10.0
* **Browser**: chrome 61.0.3163.100

* **Avocode UID**: 185489
---

```
SyntaxError: Unexpected token var
```

**Comment by jakubzitny** [comment]
Hi @zatziky, thanks for letting us know. We're already tracking this problem in #1616, so I'll close this issue. The fact that it is related to Ghostery might help us with fixing it 😉
