### ISSUE TITLE
How to remove notify update ???

### ISSUE THREAD

**Issue by teremok1000** [avocode/avocode#1646]
![a38a3723ae](https://user-images.githubusercontent.com/5323683/30962847-07a4389e-a454-11e7-9c08-daef290036af.png)

**Comment by vojtatranta** [comment]
Well, you can dismiss it, but it will pop up again. We simply want you to have the app updated.

So my advice is to update the application.

**Comment by teremok1000** [comment]
https://github.com/avocode/avocode/issues/1622#issuecomment-329460392

**Comment by vojtatranta** [comment]
@teremok1000 OK, so you can't use the current app? Can you please provide us with more information on what is wrong?

**Comment by teremok1000** [comment]
I have now 2.14.8
all the above brakes wildly el capitan

**Comment by teremok1000** [comment]
you open the program, it brakes wildly
I'm not the only one, with my mac all okay
the program after 2.14.8 is spoiled

**Comment by vojtatranta** [comment]
@teremok1000 can you be please more specific what does it mean that "program brakes wildly"?

**Comment by teremok1000** [comment]
well, when scroll brakes and with jerks, when we click on the text of the picture and other elements, then the delay in the click is 200-700 milliseconds to display information about the element.
It work 3-8 (approximately) minutes of work and the brakes are amplified 2-3 once


Sorry, i use google translate

**Comment by vojtatranta** [comment]
So it lags all the time, right? Lagging - not being smooth unusable, right? Just by starting the app.

Can you send us a video please? And details about you system.

**Comment by teremok1000** [comment]
video can not be thrown off as all layouts from customers, I have described in detail what is

![3b573e08d4](https://user-images.githubusercontent.com/5323683/30989889-04923526-a4a8-11e7-8e3f-d869614db860.png)

**Comment by teremok1000** [comment]
lags only in the inspector

**Comment by vojtatranta** [comment]
@teremok1000 video would be helpful. Can you create some custom design in photoshop? Or you can just create an empty project and click "Open example design" and it will open example design. Then you could make a video.

**Comment by teremok1000** [comment]
give me a test psd
when there are projects no longer create a test
or any psd give only not the smallest

**Comment by vojtatranta** [comment]
Here's the example design: https://upx.cz/ic0

**Comment by teremok1000** [comment]
https://www.dropbox.com/s/vbgrau82x7mglyc/video1.zip?dl=0

**Comment by teremok1000** [comment]
apple magic mouse scrolling
very slows down, it does not work quickly, in older versions everything was fast and clear

**Comment by vojtatranta** [comment]
@teremok1000 yeah, thank you for the video. We are aware of this and I am working on the fix right now.

By the way, sorry for long-lasting opening of the design, we are working on improving this rapidly.

**Comment by teremok1000** [comment]
can i delete the video? you did not make copies of the video? if did please remove

**Comment by vojtatranta** [comment]
yes, you can

**Comment by evanre** [comment]
Same problem. I use Avocode on two work stations. One of them is old notebook with Manjaro Linux (Arch linux), I can't manually build packages, I just clone app from AUR repo and build it. Everything works fine, but there is two problems:
- AUR repo can stay outdated for a while, so I can't install latest version (now its much better, thanks @jakubzitny).
- At some point it starts to annoying to update it each time you relize a new update (sometime it's every single day). I'm working, and I have no time for updates i current moment!

I'm okay to keep fresh versions. But please, don't remind me about it every 10 minutes!!!

**Comment by jakubzitny** [comment]
Thanks for the feedback @evanre and thanks for using Avocode. I'll see what we can come up with to make this better 🙂

**Comment by evanre** [comment]
@jakubzitny Hi, thanks for keeping AUR repo updated :)

**Comment by jakubzitny** [comment]
We've actually improved this in v3 already. We're only showing a badge in top right corner to keep you updated about the update. Please let us know if it's still bugging you 😉
