### ISSUE TITLE
Desktop App: can't select text in textpreview (top right corner) if toolbar is off (View -> Toolbar)

### ISSUE THREAD

**Issue by i-v-k** [avocode/avocode#1647]
* **Version**: 2.15.5

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 112740
---

Hello! I can't select text in textpreview (top right corner) if toolbar is off (View -> Toolbar)
```
No stack trace available
```

**Comment by i-v-k** [comment]
Duplicates issue 2 of Few UI bugs in 2.15 #1623

**Comment by jakubzitny** [comment]
I'll close this with respect to #1623.
