### ISSUE TITLE
Desktop App: canvas position resets to default after switching design tabs with Tab button

### ISSUE THREAD

**Issue by i-v-k** [avocode/avocode#1648]
* **Version**: 2.15.5

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 112740
---

Hello! 
If I open a few tabs with different design and move canvas in them, after switching tabs with Tab button
canvas position resets to default.
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @i-v-k, this will be fixed in the next release of Avocode.

**Comment by i-v-k** [comment]
Great news, thanks!

**Comment by jakubzitny** [comment]
Hi, this should be fixed in latest Avocode `2.16.2`. Please update and let us know if you find any other problems :wink:

**Comment by i-v-k** [comment]
Thank you!
