### ISSUE TITLE
Desktop App: After changing zoom with mousewheel zoom resets to 20%

### ISSUE THREAD

**Issue by i-v-k** [avocode/avocode#1649]
* **Version**: 2.15.5

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 112740
---

Hello!
If I zoom in with Ctrl + mousewheel and then zoom out, zoom always resets to 20%.
Even from 1000% - one mousewheel scroll and it instantly sets to 20%.
```
No stack trace available
```

**Comment by i-v-k** [comment]
Duplicates "Scale issue #1639" https://github.com/avocode/avocode/issues/1639

**Comment by jakubzitny** [comment]
Thanks @i-v-k, I'll close this as duplicate. We'll try to have a look at this problem 😉
