### ISSUE TITLE
Wrong measurements

### ISSUE THREAD

**Issue by stefanmvc** [avocode/avocode#165]
Sketch: 
![screen shot 2015-03-05 at 19 03 28](https://cloud.githubusercontent.com/assets/3799083/6511048/60a94b28-c36a-11e4-9796-2995ece22bd0.png)

Avocode: 
![screen shot 2015-03-05 at 19 03 35](https://cloud.githubusercontent.com/assets/3799083/6511050/68c923fa-c36a-11e4-8eba-bf979e42331d.png)

Sketch: 
![screen shot 2015-03-05 at 19 07 14](https://cloud.githubusercontent.com/assets/3799083/6511139/e144cd52-c36a-11e4-9883-1bd3123d6d4f.png)

Avocode: 56px

Etc. etc. etc. etc.

Mac OS X 10. 9.
Sketch 3.2.2
Avocode 1.0.1

**Comment by petrbrzek** [comment]
We'll look into it. Thanks for reporting.

**Comment by tomashanacek** [comment]
Fixed in 2.1.0.
Reopen, if the problem still occurs.
