### ISSUE TITLE
Copy and paste error text

### ISSUE THREAD

**Issue by teremok1000** [avocode/avocode#1653]
Hello! make video
https://www.dropbox.com/s/6ibs3zw8qp91x99/bag1.mov?dl=0
please solve the problem

**Comment by teremok1000** [comment]
2.15.5 version

**Comment by jakubzitny** [comment]
This will be fixed in the next release of Avocode next week 🙂

**Comment by jakubzitny** [comment]
Hi, this should be fixed in latest Avocode `2.16.2`. Please update and let us know if you find any other problems :wink:

**Comment by HtmlMak** [comment]
@jakubzitny Is the bug fixed for new layouts? Just opened the old one and nothing has changed

**Comment by jakubzitny** [comment]
It should be fixed for old layouts as well, can you please send us your particular design to team@avocode.com so we can investigate it? There might be another control character that you're expecting to behave like a newline.

**Comment by HtmlMak** [comment]
@jakubzitny sent, hopefully help)

**Comment by jakubzitny** [comment]
Thanks a lot @HtmlMak, I am re-opening your original issue. I forgot about the original line break character from UTF - `\2028`. I will try to fix it as soon as possible 😉
