### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by mr-stasyuk** [avocode/avocode#1655]
* **Version**: 2.15.5
* **Sketch plugin version**: 46.2.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 125155
---

```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by connor-bean** [comment]
Hey @mr-stasyuk 
Can you please provide us with more info, what OS are you using, what have you been doing before this happened and did it happen more than once?

**Comment by connor-bean** [comment]
Can you please provide us with more info, what OS are you using, what have you been doing before this happened and did it happen more than once?

**Comment by jakubzitny** [comment]
Closing with respect to #1656.
