### ISSUE TITLE
ENOTFOUND manager.avocode.com

### ISSUE THREAD

**Issue by haylax** [avocode/avocode#1656]
* **Version**: 2.15.5

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 142829
---

```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by connor-bean** [comment]
Hello @haylax 

Can you please provide us with more info: what have you been doing before this happened and did it happen more than once?

**Comment by jakubzitny** [comment]
This should not be happening anymore in recent releases. Please let us know if you have similar problems again 😉
