### ISSUE TITLE
Auto update still not working

### ISSUE THREAD

**Issue by monti84** [avocode/avocode#1658]
* **Version**: 2.15.5
* **Web/Desktop**: Desktop
* **Platform/Browser**: Windows 7 - 64 bit

Started the app -> Got a message i have an outdated version -> Clicked to download -> Notification popped up which shows "Downloading" -> Notification disappear after some seconds, nothing happens. 
Closed the application, it started all over again.

Downloaded the app manually from avocode.com -> Installed -> Started the app, message comes saying I should use a newer version, providing the same link which i used to download the latest Avocode -> I have restarted the program, i got no more errors or messages, version number is the latest in the application titlebar.

**Comment by vojtatranta** [comment]
Hi,
it takes some time to download new version. Basically everything is running, but if you see notification that update failed then it is for sure that something went wrong.

Anyway in your c:/Users/<your name >/AppData/local/avocode should be an update.log or SquirrelSetup.log. if you email us this file me may find out domething more.

**Comment by jakubzitny** [comment]
Hi @monti84, do you still have problems with updating Avocode app please?

**Comment by monti84** [comment]
Hey, sorry, i have stopped using Avocode.
