### ISSUE TITLE
Ctrl+mouse wheel down always jumps to 20% zoom level

### ISSUE THREAD

**Issue by monti84** [avocode/avocode#1659]
* **Version**: 2.15.5
* **Web/Desktop**: Desktop & Webapp
* **Platform/Browser**: Windows 7 - 64 bit

Ctrl + mouse wheel down keeps jumping to zoom level 20% no matter whats my current level.
Ctrl + mouse wheel up working as expected (20%-40%-80%-160%...etc).

Design scale are untouched, its @1X.

This really annoying bug appears both desktop and web version of Avocode.

**Comment by jakubzitny** [comment]
Thanks @monti84, -> #1639 😉
