### ISSUE TITLE
Avocode App is Not Displaying This Shape Properly

### ISSUE THREAD

**Issue by vitorfernandes** [avocode/avocode#166]
When I load the .psd, I can't see the shapes with this configuration (see below):

![screen shot 2015-03-05 at 4 28 57 pm](https://cloud.githubusercontent.com/assets/11338156/6512722/c473b79e-c354-11e4-886b-93d60c024024.png)

The “selector” shape is not being displayed. :/

**Comment by petrbrzek** [comment]
Thanks for reporting the issue and also sorry for the late reply. Could you share us the problematic design with us? If so, send it to team[at]avocode.com.

**Comment by vitorfernandes** [comment]
Ok, I'm doing it now. Thanks. ;)

**Comment by rychlis** [comment]
This is actually same issue as #253 - we'll keep open just that issue
