### ISSUE TITLE
PSEP character

### ISSUE THREAD

**Issue by cupok** [avocode/avocode#1660]
* **Version**: 2.15.5

 no

* **Web/Desktop**: Desktop

* **Platform/Browser**: Windows 10

 -

When I copy multiline text, '/n' character replace with 'psep' 
![psep](https://user-images.githubusercontent.com/30305555/31315690-025b5898-ac26-11e7-9092-f759633c4ac0.PNG)

**Comment by jakubzitny** [comment]
Hi @cupok, thanks for reporting this. We're already dealing with similar problem in #1653, so I am going to close this thread and let's continue there. We'll try to fix this for one of the upcoming releases and we'll let you know when it's ready.

**Comment by cupok** [comment]
thank you!
