### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sibDesign** [avocode/avocode#1661]
* **Version**: 2.15.5-web.4

* **Web/Desktop**: Web

* **Platform**: windows 10.0
* **Browser**: firefox 56.0

* **Avocode UID**: 196788
---

```
t/r._handleLineMouseUp@https://cdn.app.avocode.com/dist/v-1ade5eb/js/avocode-web.min.js:101:764331
r@https://cdn.app.avocode.com/dist/v-1ade5eb/js/avocode-web.min.js:79:608662

```

**Comment by jakubzitny** [comment]
Hi @sibDesign, we're already tracking this in #1631 and it will be fixed in the upcoming release next week.
