### ISSUE TITLE
Login to profile hangs, showing loading screen

### ISSUE THREAD

**Issue by Math3v** [avocode/avocode#1662]
**Web/Desktop**:
Web

**Platform/Browser**:
Browser

**Avocode e-mail**:
matejminarik.fiit@gmail.com

**Console Output:**
```
creating-effectify: 258.157958984375ms
avocode-web.min.js:79 creating-rendering: 37.5849609375ms
avocode-web.min.js:79 creating-composer: 0.048828125ms
avocode-web.min.js:79 creating-rendering-libs: 302.2099609375ms
```

**Comment by connor-bean** [comment]
Hey @Math3v -

What browser are you using? And does it also fail in the desktop app as well?

**Comment by Math3v** [comment]
Google Chrome is up to date
Version 61.0.3163.100 (Official Build) (64-bit)

And yes, it hangs in the desktop app as well.

**Comment by jakubzitny** [comment]
Could you please send us a screenshot of network tab in Chrome DevTools please after you try logging in?

Also for debugging if the problem is in your account or not, could you please try new registration and logging in as a new user?

**Comment by Math3v** [comment]
New registration seems to be working.

Screenshot:
![screenshot 2017-10-09 11 41 10](https://user-images.githubusercontent.com/3818442/31332501-ec680e7a-ace6-11e7-99ee-45d59618eb78.png)

**Comment by jakubzitny** [comment]
Thanks @Math3v, there seems to be a problem on our backend with your account, sorry. We're investigating it and we'll get back to you as soon as possible.

**Comment by jakubzitny** [comment]
Allright, so the problem was that you were removed from your previous organization. We've created a new one for you and you should be able to use your account now.

Please, let us know if you have any more problems 😉

**Comment by Math3v** [comment]
Works fine now, thanks!
