### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by kuziv-andriy** [avocode/avocode#1665]
* **Version**: 2.15.5

* **Web/Desktop**: Desktop

* **Platform**: win32

* **Avocode UID**: 27409
---

```
Error: connect ETIMEDOUT 52.70.75.29:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by connor-bean** [comment]
Hey @kuziv-andriy - 

Can you tell us more about what you were doing when this happened?

**Comment by kuziv-andriy** [comment]
Hi @connor-bean!

Avocode has crashed after I signed in to Windows 10 after a night of OS hibernating

**Comment by jakubzitny** [comment]
Closing with respect to #1677.
