### ISSUE TITLE
Unprintable characters instead of wrapping lines

### ISSUE THREAD

**Issue by HtmlMak** [avocode/avocode#1666]
* **Version**: 2.15.5

* **Web/Desktop**: Desktop

* **Platform/Browser**: win32

Instead of moving lines from the PSD, now these symbols appear. Until the last update Avocode this was not. Has appeared almost in all projects. If necessary, I can attach the PSD-example.

![ib-1frzdprw 1](https://user-images.githubusercontent.com/9065989/31467177-507e48de-af03-11e7-8cd6-4a7f2e31979a.jpg)

**Comment by jakubzitny** [comment]
Hi @HtmlMak, thanks for letting us know. We already know about it and we'll be trying to fix it for on of the next releases. We're already tracking this problem in #1653 so I am going to close this thread.

**Comment by jakubzitny** [comment]
We've fixed `\2029`s in #1653, this is about `\2028s`, fix should be released next week.
