### ISSUE TITLE
App is opened in a lot of windows on start, instead of one.

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#167]

**Comment by VPenkov** [comment]
If this is a Windows issue, try running the app via Atom.exe instead of the Avocode shortcut. It should still work.

**Comment by petrbrzek** [comment]
We plan to update atom-shell in some of the next release. It should be fine then.

**Comment by marekhrabe** [comment]
Can you still reproduce this issue? We updated a lot of codebase since that time

**Comment by VPenkov** [comment]
No, not since you've created an installer and removed the "Avocode" shortcut from the install dir.
Feel free to close that.
