### ISSUE TITLE
bug on website

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1672]
* **Version**: 2.16.0-web.2

* **Web/Desktop**: Web

* **Platform**: windows 6.1
* **Browser**: chrome 61.0.3163.100

* **Avocode UID**: 121241
---

```
SyntaxError: Unexpected token var
```

**Comment by jakubzitny** [comment]
Hi @crh225, thanks for reporting this. We're already tracking this problem in #1616 and it seems to be related to Ghostery (or similar ad/track-blocking plugin). We'll be trying to fix it in upcoming days, however, you might want to turn it off for Avocode for now, or use our desktop version.

If you don't have Ghostery, please let us know so we can debug it more thoroughly.

I will close this thread with respect to #1616.
