### ISSUE TITLE
No way to set default CSS flavor per project

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#1674]
* **Version**: 2.16.7

* **Web/Desktop**: Desktop

* **Platform/Browser**: macOS

I find it super cumbersome that the setting for which flavor of CSS to use is still only per design. It would be very nice with a default for this on _Project level_, so that all designs (unless specifically overridden on that design) inherit this setting.

**Comment by jakubzitny** [comment]
Hi @greystate, thanks for reporting this. Yeah we already have this request in #1623. We'll look into it and see what we can do 🙂

**Comment by vojtatranta** [comment]
`2.21.0` released
