### ISSUE TITLE
Tabbed panel background

### ISSUE THREAD

**Issue by VladimirHumeniuk** [avocode/avocode#1675]
* **Version**: Avocode 2.16.0
* **Web/Desktop**: Desktop
* **Platform/Browser**: Linux

When add more then 1 row of folders, the background of the tabbed panel does not stretch, and the folder names crawl on design items.

![image](https://user-images.githubusercontent.com/20288162/31721114-27ba6b58-b421-11e7-95d8-355fa6eab92e.png)

**Comment by jakubzitny** [comment]
Hi @VladimirHumeniuk, thanks for reporting this. We already know about this and we're tracking it in #1641. We'll come back to you once it is fixed.
