### ISSUE TITLE
VSCode + avocode

### ISSUE THREAD

**Issue by PixelT** [avocode/avocode#1678]
Do you plan to integrate avocode into visual studio code? similar like in atom now? <3

**Comment by jakubzitny** [comment]
Hey @PixelT, yes we're planning on supporting Code as well although we don't really have a specific date for it yet. 😉 

You can see a list of current and planned integrations for Avocode at [avocode.com/integrations](https://avocode.com/integrations). For now, please vote for the feature on our [UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/31648780-avocode-for-visual-studio-code).

**Comment by vojtatranta** [comment]
I was googling around and find out that this plugin may be something similar of what we need for avocode: https://github.com/masonicboom/vscode-web-browser/blob/master/src/extension.ts

**Comment by bolekkerous** [comment]
Hey - 
we've already released the VScode integration a while ago, you can get it here:

https://avocode.com/integrations/visual-studio-code

Best regards,
Bolek, Avocode Team
