### ISSUE TITLE
LESS CSS without LESSHat

### ISSUE THREAD

**Issue by dongepulango** [avocode/avocode#168]
It would be great if I can get a pure LESS codes without LESSHat mixins. :)

**Comment by petrbrzek** [comment]
Thanks for the suggestion. We can add it as a option to the template settings.

**Comment by PixelT** [comment]
+1 for this same for Sass :)

**Comment by greystate** [comment]
:+1:

**Comment by petrbrzek** [comment]
Added to 2.2.0. Closing.
