### ISSUE TITLE
SVG export issue. Same id in all exports

### ISSUE THREAD

**Issue by robinfrancett** [avocode/avocode#1683]
* **Version**: 2.16.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 135625
---

Hi. I noticed that when I used exported SVG files as inline, only the first SVG would work and the rest didn't show up. So I looked at the code inside the SVG files and noticed that the paths had the same id "a". I changed the id's so that all the files had different ones and then they started working (had to change the xlink:href also). I think the id should be a randomly generated hash or at least the same as the file name. I would greatly appreciate if you would fix this :)
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @robinfrancett, thanks for the info. We're already talking about this problem in #1635, so I am going to close this thread.

We've already implemented this and it will be released with the next version of Avocode in upcoming week(s).
