### ISSUE TITLE
Design does not open

### ISSUE THREAD

**Issue by jeffreyjw** [avocode/avocode#1684]
* **Version**: Web, 2.16.1

* **Web/Desktop**:Web

* **Platform/Browser**:Linux/Chrome

 * **Avocode e-mail**: tools@uxdream.com

Design does not open. I upload the design, and after double-clicking on it it opens in comment mode, but not in inspect mode. It just indefinietly says to "wait a minute"

When opening a design in new tab, the "Loading" sign starts, but never shows the loading progress.

**Comment by jakubzitny** [comment]
Hi @jeffreyjw, thanks for reporting this problem. Can you try manually running Sync or restart the app to see if it fixes itself, please?

**Comment by jeffreyjw** [comment]
Hi @jakubzitny , thank you for quick response :) unfortunately, running "sync" manually does not help, and I cannot restart the app, because I'm using the one on http://avocode.com :) if there is a way to do this, I don't know how

**Comment by jakubzitny** [comment]
Oh I see, my bad. Let me inspect the situation.

**Comment by bolekkerous** [comment]
Hey, @jeffreyjw -
does it happen with all designs or with just specific one? Could you tell us the name of any such design that has the problem?

**Comment by jakubzitny** [comment]
Can you re-check the document now, please? Refresh the page or run the sync manually and try to open it again. We've had some issues with processing the PSD but everything should be OK now.

**Comment by jeffreyjw** [comment]
Unfortunately nothing has changed, tried also with a different browser just in case, but nothing worked.

**Comment by jeffreyjw** [comment]
In case of a question - it is one of the 3 files that were added today, the desktop version (I don't want to publicly name this file :))

**Comment by jakubzitny** [comment]
Yes we have it, thanks, the processing is still failing, our backend team is on it 🙂

**Comment by connor-bean** [comment]
@jeffreyjw -

Can you try re-uploading the design now? Let us know the result

**Comment by jeffreyjw** [comment]
@connor-bean Thanks! Everything works now. Really appreciate the quick response guys, you're the best :)

**Comment by jakubzitny** [comment]
Thanks @jeffreyjw, we're always happy to help. Let us know if you have any more problems 😉
