### ISSUE TITLE
Pay using PayPal

### ISSUE THREAD

**Issue by dongepulango** [avocode/avocode#169]
It would be great if there would be an option to pay the plan using PayPal because I don't have a credit card and it's hard for me to get one. PayPal is very easy to use and I'm more comfortable using it. Thanks

**Comment by petrbrzek** [comment]
I see that you've already posted it on [uservoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7193637-pay-using-paypal). I'll close it here.
