### ISSUE TITLE
Newlines are replaced with Unicode line break characters in copied text

### ISSUE THREAD

**Issue by mziab** [avocode/avocode#1698]
* **Version**: 2.16.1

* **Web/Desktop**: Desktop

* **Platform**: linux

* **Avocode UID**: 111918
---

In older versions of Avocode, newline characters in text were copied as expected from PSD text objects. However, at some point Avocode started converting them to Unicode line break characters (U+2029). Old designs give the same behavior, so I'm sure the designs themselves are not at fault.

The new behavior is an inconvenience in that some browsers display that character as an unexpected symbol (more info [here](https://stackoverflow.com/questions/39603446/why-is-this-symbol-showing-up-on-chrome-and-not-firefox-or-edge)). Moreover, you cannot easily search and replace it after pasting it elsewhere, since it displays as zero-width. Consequently, this is a regression when compared to older versions and a fix or at least an option to change this behavior would be greatly appreciated.

**Comment by bolekkerous** [comment]
Hey, @mziab -
sorry for the inconvenience.

We're already tracking the problem in #1653 - and I believe it's already been fixed in our upcoming release. It should be released sometime next week.

I'll close this issue since it's a duplicate.
