### ISSUE TITLE
Erroneous selection after using right-click menu

### ISSUE THREAD

**Issue by mziab** [avocode/avocode#1699]
* **Version**: 2.16.1

* **Web/Desktop**: Desktop

* **Platform**: linux

* **Avocode UID**: 111918
---

After you use the right-click menu to copy/export an object, the blue selection box appears underneath the dialog window and starts resizing according to the mouse movement, as if a drag event were in progress. It persist even after closing the dialog and only disappears when the left mouse button is pressed anywhere in the design.

This is only a minor regression, but a fix would be appreciated nonetheless. Thank you in advance.

**Comment by jakubzitny** [comment]
Yes we know about this @mziab, thanks for letting us know. We'll be releasing a fix for this soon.

**Comment by jakubzitny** [comment]
Hi, this should be fixed in latest Avocode `2.16.2`. Please update and let us know if you find any other problems :wink:
