### ISSUE TITLE
2x export option?

### ISSUE THREAD

**Issue by dongepulango** [avocode/avocode#170]
It would be great if you can export 2x size image, to be use for retina screens. Upscaling the image and maintaining its quality for icons and other shapes.

**Comment by nikolowry** [comment]
Agreed! Just had to open up my VM to export manually from PS (kind of defeats the whole purpose of avocode)

**Comment by petrbrzek** [comment]
We know about this one, it's the most voted feature on [UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6988511-export-vector-shape-layers-as-2x-and-3x). I close it here.

PS: We've already started working on it. Stay tuned!

**Comment by PixelT** [comment]
@petrbrzek 
When this feature will be ready? :)
