### ISSUE TITLE
Copy text inserts a character (invisible in code visible in windows browser as "psep") 

### ISSUE THREAD

**Issue by ims** [avocode/avocode#1703]
* **Version**: 2.16.1

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 44116
---

Copy text from Avocode. Paste it into source file. Everything looks ok in code editor but in browser on windows there are strange characters (see screenshot attached)

![screenshot_2017-10-26_17 12 50](https://user-images.githubusercontent.com/169465/32093116-7b7b41a0-bafb-11e7-9df3-f08cea47410d.png)

```
No stack trace available
```

**Comment by bolekkerous** [comment]
Hey, @ims  -
sorry for the inconvenience.

We're already tracking the problem in #1653 - and I believe it's already been fixed in our upcoming release. It should be released sometime next week.

I'll close this issue since it's a duplicate.
