### ISSUE TITLE
Able to lock layers

### ISSUE THREAD

**Issue by dongepulango** [avocode/avocode#171]
It would be great if you could lock certain layers of the PSD so you can't accidentally select it. Like for example the background when you are trying to select elements on it.

**Comment by petrbrzek** [comment]
Great suggestion. I've added it to uservoice. You can follow it [here](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7284939-ability-to-lock-layers).

I'm closing this issue for now.
