### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by Glutnix** [avocode/avocode#1710]
* **Version**: 2.16.1
* **Sketch plugin version**: 47.1.0

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 107847
---

```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by jakubzitny** [comment]
Hi @Glutnix, thanks for reporting this. We're already tracking this in #1656 but we have problems reproducing it. Do you have any details on when exactly did this happen? Did it happen more than once?
