### ISSUE TITLE
Images Downloading stuck 

### ISSUE THREAD

**Issue by deeqfinch** [avocode/avocode#172]
a PSD i have 62mb. 
is inifinitely stuck at random image number . 11/121 , 31/121 , 71/121 etc.

retried a lot of times

**Comment by prog666** [comment]
same issue, even on small files, 7mb. I have slow connection, about 300kb/s

**Comment by deeqfinch** [comment]
yes i also just realised (as my internet was slowed at office) . that problem is with multiple files.
why cant we use the app locally. 
please fix... app is unusable

**Comment by prog666** [comment]
i found out that if you try to open another file and then stuck one again it fixes

**Comment by dongepulango** [comment]
same here. even for a file the is only 1mb I get stuck.

**Comment by taher435** [comment]
Same issue with me. It gets stuck on Image data 4/26 forever. Please fix this ASAP. Why can't it have the image data cached on local ?

**Comment by taher435** [comment]
![unexpected_loading_error](https://cloud.githubusercontent.com/assets/875186/6686092/59611530-ccc5-11e4-8050-24ed1164aa87.png)

**Comment by petrbrzek** [comment]
This one is really the pain in the butt. I'm really sorry for that.
We'll fix it in the next release.

**Comment by deeqfinch** [comment]
i have noticed this happens only in slow connections for some reason ( although they are steady and consistent ( i monitor ) ). 
.

**Comment by prog666** [comment]
i waste hours every time i need to open a file, just because there's no caching and it stucks every time, what do i pay 20$ for?

**Comment by deeqfinch** [comment]
any update on this ?????????

**Comment by deeqfinch** [comment]
major update to avocode 2.0.0 and STILL NOTHING ???????
what is this?? ?

**Comment by petrbrzek** [comment]
It should be fixed. Do you have a problem with every design or it's just some specific one?

**Comment by deeqfinch** [comment]
now i have a problem with every design. it simply doesnt upload from the application. runs infinitely.
this is a gem of an application but i cant use it!!! 
my guess is that the SYNC FEATURE is messing this up.
@developers. please understand that there are FUBAR connections in the world (im in India). and this app needs to work accordingly.
right now i open a project ( with 8 designs) . they all start downloading...... infinitely . cant open anything.
im able to upload thru web . but app is fully unusable for now. earlier one was better .
please help !!!

**Comment by deeqfinch** [comment]
What is this ???
App is still unusable.
I have a project with 11 designs . and they all start downloading and it is stuck forever.
The old thing was better.
pleaase make this usable agian?

**Comment by dongepulango** [comment]
I'm sure they are tying their best to fix this issue.

**Comment by deeqfinch** [comment]
the last responside was 14 days ago in the assumption by them that its fixed.
i would like some communciation please.

**Comment by petrbrzek** [comment]
@deeqfinch Really sorry for inconvenience. We worked hard all last week to fix this critical issue. If nothing bad happens, we release an update tomorrow.

**Comment by petrbrzek** [comment]
And it's out. It should be fixed, try it and let us know.

**Comment by prog666** [comment]
will try in the morning, we bought 2 people license few days ago, hope it will not be a waste of money, your app becomes better and better

**Comment by deeqfinch** [comment]
working awesome.  thank God!. thank you
