### ISSUE TITLE
Cannot find module '/opt/avocode/resources/electron.asar/browser/init.js'

### ISSUE THREAD

**Issue by gurmiguel** [avocode/avocode#1722]
* **Version**: 2.16.3
* **Platform/Browser**: Desktop/Fedora 24

gu.rmiguel@gmail.com

Installing the newest version of Avocode, began a problem of it not starting anymore, checked in terminal way of initializing it, and it return the following:
```
module.js:472
    throw err;
    ^

Error: Cannot find module '/opt/avocode/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3
```
It's installed in /opt/avocode, as were the previous versions.

Previous version works just fine.

**Comment by vojtatranta** [comment]
We fixed few troubles when booting the app in the `2.16.4`, can you give it a try? https://avocode.com/download

**Comment by gurmiguel** [comment]
Actually, nothing changed, same error :|

**Comment by jakubzitny** [comment]
Hi @gurmiguel, do you still have problems with this in latest Avocode?

**Comment by gurmiguel** [comment]
Tried here, and the issue has been solved. Thank you very much.
