### ISSUE TITLE
line-height not taken into account when measuring text layers

### ISSUE THREAD

**Issue by yoshi78** [avocode/avocode#1723]
* **Version**: 2.16.3

* **Web/Desktop**: Desktop

* **Platform/Browser**: windows 8.1 x64

Seems like issue #195 is back again. Avocode doesn't respect line-heights when measuring heights / margins for text layers since version 2.16.2.

**Comment by jakubzitny** [comment]
Hi @yoshi78, thanks for reporting this issue. We have this in our internal tracking system and we're working on a fix. We'll let you know once it's ready 😉

**Comment by bolekkerous** [comment]
Hey, @yoshi78  -
we've just released a new version of our internal format, which should be fixing this issue.

Just reopening the design should fix the issue. :)
