### ISSUE TITLE
Error in getting text color.

### ISSUE THREAD

**Issue by dean992008** [avocode/avocode#1724]
* **Version**: 2.16.4

* **Web/Desktop**: Desktop

* **Platform**: linux

* **Avocode UID**: 61323
---

```
No stack trace available
```

http://joxi.ru/v29l9D9f3gkdym

**Comment by jakubzitny** [comment]
Hi @dean992008, thanks for the report. Can you send us the design to team@avocode.com so we can investigate it further? Is there any chance the text color you see is a fill effect on a white text layer?
