### ISSUE TITLE
Download: Unexpected error

### ISSUE THREAD

**Issue by NikitaNO** [avocode/avocode#1726]
* **Version**: 2.16.4

* **Web/Desktop**: Desktop

* **Platform**: linux

* **Avocode UID**: 176027
---

unexpected error after downloading 21/320 files or 12/320 files

```
No stack trace available
```
![image](https://user-images.githubusercontent.com/7610030/32595871-3205ce0c-c53a-11e7-8a81-d1f9a9a520e5.png)

**Comment by jakubzitny** [comment]
Hi @NikitaNO, thanks for the report. Is it happening all the time on the design on just once? Does it happen to different designs? Did you try re-uploading the design one more time?
