### ISSUE TITLE
variables

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1727]
* **Version**: 
the web version

no sketch

* **Web/Desktop**:
Web

* **Platform/Browser**:
Chrome latest

![image](https://user-images.githubusercontent.com/19475195/32629232-1e57ebdc-c55e-11e7-80e7-73e6e2237b67.png)
I tried to create a variable, but it is not displaying as per the user guide.
https://avocode.zendesk.com/hc/en-us/articles/202090592-What-are-variables-and-replace-rules-in-Avocode-

**Comment by vojtatranta** [comment]
Just delete `$` at the beginning of you variable and you should be OK :)

**Comment by crh225** [comment]
![image](https://user-images.githubusercontent.com/19475195/32629301-607abf1c-c55e-11e7-9e0e-db193baf974e.png)

**Comment by vojtatranta** [comment]
This seems like a valid css variable or not?

**Comment by crh225** [comment]
According to the documentation provided by avocode:
![image](https://user-images.githubusercontent.com/19475195/32629367-99ae6f04-c55e-11e7-95ca-8ba6b6682067.png)
I dont see why it wouldnt work.

**Comment by vojtatranta** [comment]
Yes, but this image is dedicated to `SASS` css language. If you switch code template language to SASS (cog button in the lower right corner in the code panel), you would see exactly this.

It seems like guide is not properly updated. But it should be still ok.

**Comment by crh225** [comment]
Cool I wanted SASS!. Thanks! Response time for you guys is crazy!

**Comment by vojtatranta** [comment]
@crh225 I live to serve you! :))

**Comment by vojtatranta** [comment]
And by the way. If you navigate to App preferences (`CMD+,` click your icon in the top right and select `App preferences`) in the Code tab you can customize the code output. There are many interesting options.

**Comment by crh225** [comment]
@vojtatranta, do you think service-workers would make downloading/rendering the designs faster? I leave avocode open for weeks, and while idle, it can perform background syncing to download some of these designs.

**Comment by vojtatranta** [comment]
Yeah, service workers are an option. We are now experimenting with web assembly for rendering the designs. Which is significantly faster and much more accurate.

And we will add an option to locally download some designs of your choosing.



And one more "by the way":

Variables you make are synced across all Avocode instances - any desktop app you boot either on laptop, desktop, fridge... Or even web app at app.avocode.com.

**Comment by crh225** [comment]
Cool, I dont think they use to do that, so before I never invested in using the variables. For my new project I am defiantly going to be using them.

**Comment by vojtatranta** [comment]
Great! Good luck!
