### ISSUE TITLE
Unexpected error (import from sketch)

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#1728]
* **Version**: 2.15.5
* **Sketch plugin version**: 46.2.4

* **Web/Desktop**: Desktop

* **Platform**: darwin

* **Avocode UID**: 16989
---

```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by jakubzitny** [comment]
Hi @janaobzerova, we're already tracking this in #1656, so I'll close this thread. Any details on when is this happening? Does it happen all the time or just once?
