### ISSUE TITLE
Error opening files on my project

### ISSUE THREAD

**Issue by guilhermemarconi** [avocode/avocode#1729]
* **Version**: 2.16.3-web.1
* **Web/Desktop**: Web
* **Platform**: macosx 10.12
* **Browser**: firefox 58.0
* **Avocode UID**: 190370
---

Error opening my files. It happens on every PSD files that I upload. If someone else of my team uploads the files, it works as expected.

```
e.prototype._loadMaskedBy/e.exports<@https://cdn.app.avocode.com/dist/v-e47d424/js/avocode-web.min.js:101:1361114
e.prototype._loadMaskedBy@https://cdn.app.avocode.com/dist/v-e47d424/js/avocode-web.min.js:101:1360343
e.prototype.loadDocumentAssets/l</l</l<@https://cdn.app.avocode.com/dist/v-e47d424/js/avocode-web.min.js:101:1357865
e.exports@https://cdn.app.avocode.com/dist/v-e47d424/js/avocode-web.min.js:28:223434
@https://cdn.app.avocode.com/dist/v-e47d424/js/avocode-web.min.js:28:346317
v@https://cdn.app.avocode.com/dist/v-e47d424/js/avocode-web.min.js:28:346175
m@https://cdn.app.avocode.com/dist/v-e47d424/js/avocode-web.min.js:28:346195
```

**Comment by jakubzitny** [comment]
Hi @guilhermemarconi, thanks for letting us know. We'll have a look at this. Is there any chance your team mates are using a different browser?

**Comment by guilhermemarconi** [comment]
@jakubzitny yeah. I'm using Firefox Developer Edition, and my team mates use Chrome.
I found out that my PSD files opens normally on Avocode Desktop App.

**Comment by jakubzitny** [comment]
Hi @guilhermemarconi, this should be fixed in latest versions of avocode. Let us know if you still have similar (or any other) problems 😉
