### ISSUE TITLE
How to reset layers visibility?

### ISSUE THREAD

**Issue by lucien144** [avocode/avocode#173]
Is there any way how can I reset the layers visibility to default state? Imagine I'm slicing a PSD, hiding some layers to export what I need and when I'm done I wanna reset the PSD to default design state.

Thanks.

**Comment by petrbrzek** [comment]
It's possible in a kinda weird way. (We definitely need to improve it.)

![state](https://cloud.githubusercontent.com/assets/879564/6766128/1181e73e-cffa-11e4-8df9-b80bddec55e2.gif)

1. Press `Alt + S`.
2. Select `Default`
3. Done
