### ISSUE TITLE
JUST CRASH WHEN TRO TO DO EXPORT 

### ISSUE THREAD

**Issue by OdedYaron** [avocode/avocode#1732]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.16.4`
JUST CRASH WHEN TRO TO DO EXPORT

**Comment by jakubzitny** [comment]
So this is the same as #1690, right? Can you please give us details about your OS? Is this happening to all exports or just a specific one? If it's only one, can you send the design to team@avocode.com, please? Does it fail when exporting to PNG, JPG and SVG too? Can you try disabling export optimization in Help menu Troubleshooting -> Export optimization?

**Comment by jakubzitny** [comment]
Please let us know the details on this issue. We'd be happy to fix it and help you, but unfortunately in this case we need more information.
