### ISSUE TITLE
WTF??

### ISSUE THREAD

**Issue by Woody174** [avocode/avocode#1733]
![pic](https://user-images.githubusercontent.com/11013417/32794472-cb0f379c-c98a-11e7-804e-c47a86a5b4db.PNG)

---
* **Version**: 2.16.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 133315
---
```
Error: connect ETIMEDOUT 104.28.4.96:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by jakubzitny** [comment]
Hi @Woody174, thanks for reporting this. We are trying to fix this problem on our backend and we'll come back to you as soon as possible. We're already tracking this problem in #1677 so I am going to close this issue.
