### ISSUE TITLE
2.17 Community Beta Testing

### ISSUE THREAD

**Issue by MattRoskovec** [avocode/avocode#1735]
### 1. Moving a design file from project to project
Try moving a design file from one project to another one. It's only possible to move one file at a time. It's not possible to move Sketch artboards, only whole Sketch files.

### 2. Version slider in the Comment mode
Open a design with multiple versions in the Comment mode. (Here's a tutorial how to upload more design versions to one design: https://help.avocode.com/projects-and-designs/design-upload/add-a-new-design-version)

Next, try going back and forth between design versions. Try commenting on different versions, replying to comments and then moving between versions.

### How to report issues?
If you spot anything unexpected or notice something broken, please report it to us in the comments below.

- Always state your operating system
- Describe the problem
- Attach a screenshot if possible

Thank you, you're awesome. 🙏🏼

**Comment by greystate** [comment]
I just tried the **Move...** functionality – only thing that struck me was that I couldn't create a new project right away in the dialog (it looks very similar to the one you get when uploading a design and you choose which project it goes in, which _does_ allow you to create a new project right away).
 
(I'm on **macOS 10.13.1**)

**Comment by vojtatranta** [comment]
@greystate yeah, we will add it.
