### ISSUE TITLE
Request/Question: how to hide the side panels?

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1736]
* **Version**: 
2.16.5

N/A

* **Web/Desktop**:
Both

* **Platform/Browser**:
Chrome

Is there a way to collapse the two side panels? When we are showing designs to clients, sometimes we have to use projectors, laptops, smaller resolution screens, and it would be nice if half the design is not covered up. We dont have the original sketch files.

![image](https://user-images.githubusercontent.com/19475195/32844387-e4aff652-c9e7-11e7-96d0-af1999d6f325.png)

**Comment by jakubzitny** [comment]
Hi @crh225, you can hide the side panels by pressing `tab`. LEt us know if you have any more questions 😉
