### ISSUE TITLE
avocode stops uploading

### ISSUE THREAD

**Issue by webowski** [avocode/avocode#1738]
* **Version**: 2.16.6

* **Web/Desktop**: Desktop

* **Platform/Browser**: macOS Sierra 10.12.6 (16G1036)

 sanvovanych@gmail.com

when i try to upload a psd, the progress stops at 4% and then happens nothing. The psd is ok, it opens with photoshop

**Comment by jakubzitny** [comment]
Hi @webowski, thanks for reporting this. Does this happen only with one specific file or different ones? Have you tried uploading it via web app at app.avocode.com?

**Comment by webowski** [comment]
Hi. The problem happened only with one file. But it solved by itself, i've tried to repeat it next day and it worked fine. I think there was a problem with my connection. 
so, thanks Jakub

**Comment by jakubzitny** [comment]
Thanks for the info. Let us know if you have any more problems with Avocode 😉
