### ISSUE TITLE
Freezes on export of hidden element

### ISSUE THREAD

**Issue by eligat** [avocode/avocode#1740]
100% reproducible for .sketch or .psd project

---
* **Version**: 2.16.6
* **Sketch plugin version**: 47.1.3
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 214272
---

**Comment by jakubzitny** [comment]
Hi @eligat, thanks for reporting this. I can confirm we are able to reproduce this and we will be trying to fix this as soon as possible.

**Comment by jakubzitny** [comment]
Hi @eligat, we've released 2.17.1 few days back. This should be fixed there.
