### ISSUE TITLE
Cannot Install Avocode Plugin in Sketch

### ISSUE THREAD

**Issue by sparklesam** [avocode/avocode#1742]
---
* **Version**: 2.16.6
* **Sketch plugin version**: undefined
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 217009
---
```
Error: Command failed: "/Applications/Skitch.app/Contents/Resources/sketchtool/bin/sketchtool" show plugins
/bin/sh: /Applications/Skitch.app/Contents/Resources/sketchtool/bin/sketchtool: No such file or directory

    at ChildProcess.exithandler (child_process.js:217:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by jakubzitny** [comment]
Hi @sparklesam, thanks for the report. This is interesting. Do you have Sketch installed? It is somehow misplacing Sketch to Skitch, if you have both of them. Try re-naming Skitch to see if it helps and I'll have a look at why is this happening.

It might be that you have a Beta version of Sketch and we're wrongly detecting "Skitch" as an app that can open Sketch files instead. In this case, renaming Sketch to just `Sketch.app` should definitely help.

**Comment by sparklesam** [comment]
Hi,

The issue has been resolved, somehow the sketch was moved to somewhere
outside Application folder. Thanks a lot for your assistance.

Best,
Samuel

**Comment by jakubzitny** [comment]
Thanks @sparklesam, let us know if you have any more problems with Avocode :wink:
