### ISSUE TITLE
Export and merge 2 layers bug

### ISSUE THREAD

**Issue by filestealer** [avocode/avocode#1745]
* **Version**: 2.16.6

* **Web/Desktop**: Desktop

* **Platform/Browser**: Ubuntu 16.04

andrey@osmushko.com

hello!
When exporting 2 layers, the preview is shown correctly, but the result in PNG is not correct. Merged without opacity.
![2017-11-21 12-28-55](https://user-images.githubusercontent.com/3895412/33058165-8014b0a4-ceb8-11e7-8d6c-f35fa2fe7eba.png)
![2017-11-21 12-29-03](https://user-images.githubusercontent.com/3895412/33058167-804d3cf8-ceb8-11e7-8726-d84e522826fa.png)
![2017-11-21 12-29-12](https://user-images.githubusercontent.com/3895412/33058168-80747fb6-ceb8-11e7-9d1a-744ede1837a7.png)

**Comment by vojtatranta** [comment]
Hi,
thank you for your report.

We are now redoing export to work properly. Which means it would match what you see on the "stage", in the preview and what you export exactly.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. 

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
