### ISSUE TITLE
Document is corrupted

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1746]
* **Version**: 
2.17.0

N/A

* **Web/Desktop**:
Desktop but it is electron so web also??

* **Platform/Browser**:
Windows

![image](https://user-images.githubusercontent.com/19475195/33136408-bca7cdf0-cf6a-11e7-91b7-f5b065db0a6b.png)
Constantly getting this error message in the new release.

**Comment by jakubzitny** [comment]
Hi @crh225, thanks for the report. Is this happening to one specific file or multiple? Did the same document work before? Can you five us more details so we can inspect it? Your avocode e-mail and project/design name that throws this error would help. If you don't want to share it here, please contact team@avocode.com.

**Comment by crh225** [comment]
It is happening to multiple files. the document worked before I downloaded the latest update. But I may have not been on the latest previous update when it worked. when I find more examples, I will send this information over to that email address.  It happened more frequently yesterday that it is happening today. I will reopen if I can reproduce.
