### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rfhfnftd** [avocode/avocode#1748]
---
* **Version**: 2.17.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 215554
---
```
Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:581:26)
```

**Comment by vojtatranta** [comment]
Thank you for your report. That's long-lasting issues on our end.

We are working on fix - redoing the way how assets are downloaded
