### ISSUE TITLE
WTF ??

### ISSUE THREAD

**Issue by Woody174** [avocode/avocode#1751]
---
* **Version**: 2.17.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 133315
---
```
Error: connect ETIMEDOUT 104.28.4.96:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by jakubzitny** [comment]
Hi @Woody174, thanks again for submitting this. We know about this problem already, also we've seen your submit in #1733. However, we'd like to hear more details on this error from you, how often is this happening? When exactly?

I'm closing this with respect to #1677, but please do let us know the details.
