### ISSUE TITLE
Exeption on open page

### ISSUE THREAD

**Issue by irbisadm** [avocode/avocode#1753]
---
* **Version**: 2.17.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 49422
---
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:2019924
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

**Comment by jakubzitny** [comment]
Hi @irbisadm, thanks for reporting this. It's a bug and we'll be trying to fix it as soon as possible.

**Comment by jakubzitny** [comment]
Hi @irbisadm, can you still see this happening in latest version of Avocode, please?

**Comment by jakubzitny** [comment]
I'll close this, let us know if you still have similar (or any) problems 😉
