### ISSUE TITLE
exporting sketch to avocode

### ISSUE THREAD

**Issue by mohamedhamad** [avocode/avocode#1756]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 47.1.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 173393
---
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by jakubzitny** [comment]
Hi @mohamedhamad, we're already tracking this in #1656, so I'll close this thread. Any details on when is this happening? Does it happen all the time or just from time to time?
