### ISSUE TITLE
Serius bug 2.17.1 v. not importing psd.

### ISSUE THREAD

**Issue by vsevset** [avocode/avocode#1762]
* **Version**: 

* **Web/Desktop**:

* **Platform/Browser**:

**Comment by vsevset** [comment]
Desctop/Windows 10/Serius bug 2.17.1 v. not importing psd. http://joxi.ru/nAyp954CXM5jd2

**Comment by jakubzitny** [comment]
Hi @vsevset, we've seen this problem popping up in our support. We're inspecting it and we'll try to fix it as soon as possible.

Can you please give us some details like how often is this happening and what design is it affecting? Is it all design all the time? Did you try the web version, please?

**Comment by jakubzitny** [comment]
This should not be happening anymore in latest Avocode. Please update and let us know if you see anything similar again 😉
