### ISSUE TITLE
error connection

### ISSUE THREAD

**Issue by streeboga** [avocode/avocode#1767]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 220851
---
```
Error: The request timed out
    at file:///home/tesey/soft/Avocode/resources/app.asar/dist/avocode.min.js:1:2154222
    at wrapped (/home/tesey/soft/Avocode/resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by vojtatranta** [comment]
Hi, thank you for this report.

We know about these network issues and we will release a fix as soon as possible.

**Comment by jakubzitny** [comment]
Duplicate in #1781.
