### ISSUE TITLE
Linux | X11 Window Class not registering properly

### ISSUE THREAD

**Issue by nikolowry** [avocode/avocode#177]
I understand you guys took the Atom Text Editor source and modified it to your needs. There is a bug in Atom Shell for Linux on how it registers the window's class to the end-users Window Manager (X11, Wayland, Openbox, i3, bpswm, etc): https://github.com/atom/atom-shell/issues/840.

However when running Atom Text Editor, the Window class/icon/title are properly registered and displayed.  I don't know what they do in their script/build and script/install that correctly addresses the Atom Shell bug.

I can't overwrite the running instance with a custom desktop file and the app displays the title of window as "Atom Shell" and uses a fallback png for the icon (not the "new" refreshed one displayed on the site).

http://goo.gl/T9Gf5U

**Comment by petrbrzek** [comment]
Thanks for reporting. We've planned to update atom-shell for a very long time. We'll get into it in the next release.

**Comment by nikolowry** [comment]
This still exists after 2.0.  Atom Editor does not suffer from this and uses Atom Shell as well. Have you guys thoroughly reviewed and adhered to https://github.com/atom/atom-shell/blob/master/docs/tutorial/application-distribution.md.

Additionally, Linux icons are usually handled by SVG - please package the icon as an SVG as well. It looks horrible and pixelated in my shell.

**Comment by rychlis** [comment]
We've finally released Avocode 2.2.0 which is using a much newer version of Electron, the WM_CLASS is now properly registered as avocode.

I've created a separate issue for the window icon - #293

**Comment by nikolowry** [comment]
Thank you for updating the ticket while closing - I had deleted Avocode and was contemplating canceling my subscription until I saw this.
