### ISSUE TITLE
Error white export

### ISSUE THREAD

**Issue by adrugov** [avocode/avocode#1772]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 47.1.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 94586
---
```
Error: Missing child slot for artboardId=2898DF7C-3BC0-4988-89F5-955DD790EEDC.
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1208228)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1207868)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3546705
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @adrugov, thanks for reporting this error. Can you be more specific about it please? Is it happening to only one specific Sketch file or multiple? Would you be able to send it to us at team@avocode.com?

Anyway, we're preparing much faster, and even better Sketch upload in `2.18`, so I expect this to be fixed there.

**Comment by jakubzitny** [comment]
Hi @adrugov, we've just release Avocode 2.20.0 with improved Sketch plugin. Many issues should be fixed, try re-syncing Sketch files and please let us know if you're still having problems.
