### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by thystruby** [avocode/avocode#1774]
---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 224459
---
```
TypeError: (0 , t._mouseupCancellers[e]) is not a function
    at file:///C:/Users/Nikita/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:2469511
    at wrapped (C:\Users\Nikita\AppData\Local\avocode\app-2.17.1\resources\app.asar\node_modules\raven-js\src\raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Thanks for the report @thystruby, we'll fix this bug as soon as possible.

**Comment by jakubzitny** [comment]
This should be fixed in latest releases of Avocode, please re-open if it occurs again.
