### ISSUE TITLE
Document failed to load error when opening an uploaded psd file

### ISSUE THREAD

**Issue by nurbek-ab** [avocode/avocode#1778]
---
* **Version**: 2.17.1-web.3
* **Web/Desktop**: Web
* **Platform**: linux -1
* **Browser**: firefox 57.0
* **Avocode UID**: 224682
---
```
e.prototype._createCanvases/s@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:101:1447674
e.prototype._createCanvases@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:101:1447786
e.prototype.loadDocumentAssets/l</l</l<@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:101:1445544
e.exports@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:28:225003
@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:28:358898
v@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:28:358756
m@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:28:358776

```

**Comment by jakubzitny** [comment]
Hi @nurbek-ab, thanks for reporting this. Looks like a bug, do you have any more info on when/how is this happening exacly? Is it only with one design or with multiple? Did you try re-uploading it?

**Comment by nurbek-ab** [comment]
It happened with three psd files (they are from the same set of designs). I re-uploaded them but the result is still the same, the opening fails almost in the end of the loading.

**Comment by jakubzitny** [comment]
Would you be willing to send us the file(s) to team@avocode.com so we can investigate this more thoroughly?

**Comment by nurbek-ab** [comment]
The designs don't belong to me. I will probably try to ask the permission from the owner.

**Comment by jakubzitny** [comment]
Did you have a chance to get the permission @nurbek-ab, please?
