### ISSUE TITLE
Re-assign design to another project

### ISSUE THREAD

**Issue by kupcza** [avocode/avocode#178]
Sometimes I realize, that I need to re-assign some design to another project or create new one. But now I have to delete design and reupload it again. I was wondering, if there's possibility to do this or if someone needed this too.

**Comment by petrbrzek** [comment]
Thanks for the suggestion. We want this feature too but don't have time to implement it yet. I create it as an idea on uservoice. You can follow it [here](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7284255-re-assign-design-to-another-project). Closing this now.
