### ISSUE TITLE
Fail to upload

### ISSUE THREAD

**Issue by sundaycrafts** [avocode/avocode#1782]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 47.1.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 229779
---
```
Error: Missing child slot for artboardId=C8D9269B-E1F3-49BE-946A-38D9A8CB16C7.
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1208228)
    at t.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1207868)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3546705
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @sundaycrafts, thanks for reporting this. We're already tracking this in #1772 but we need some details on when this is happening. Is it happening only to a specific file or to all uploads? Is it happening if you upload the same file again? Would you be able/willing to send us the design to team@avocode.com so we can inspect it thoroughly?
