### ISSUE TITLE
can`t open document

### ISSUE THREAD

**Issue by Miskamyasa** [avocode/avocode#1785]
---
* **Version**: 2.17.1-web.3
* **Web/Desktop**: Web
* **Platform**: linux -1
* **Browser**: firefox 57.0
* **Avocode UID**: 22139
---
```
e.prototype._createCanvases/s@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:101:1447674
e.prototype._createCanvases@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:101:1447786
e.prototype.loadDocumentAssets/l</l</l<@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:101:1445544
e.exports@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:28:225003
@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:28:358898
v@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:28:358756
m@https://cdn.app.avocode.com/dist/v-c677600/js/avocode-web.min.js:28:358776

```

**Comment by vojtatranta** [comment]
Hi,
thank you for your report.

It seems you've tried to open a document and this error happened, right?

**Comment by jakubzitny** [comment]
Would you be willing to send us the design to team@avocode.com or share the project/design name in Avocode with us? Is it happening if you re-upload the same file again?

Also, can you try if the same thing is happening in Chrome?

We're already tracking this in #1778, so I am going to close this issue as duplicate. But please do let us know the details 😉

**Comment by jakubzitny** [comment]
Would you be willing to send us the design to team@avocode.com or share the project/design name in Avocode with us? Is it happening if you re-upload the same file again?

Also, can you try if the same thing is happening in Chrome?

We're already tracking this in #1778, so I am going to close this issue as duplicate. But please do let us know the details 😉

**Comment by jakubzitny** [comment]
Any updates @Miskamyasa, please?
