### ISSUE TITLE
Connection problems

### ISSUE THREAD

**Issue by InvictusMorti** [avocode/avocode#1788]
Do not want to open designs, what the problem?? It says "connection problems" but i have the internet connection, due to that i am writting this massage

---
* **Version**: 2.17.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 227841
---
```
Error: Could not download metadata (revision=17853736)
    at file:///C:/Users/me/AppData/Local/avocode/app-2.17.1/resources/app.asar/dist/avocode.min.js:1:1072324
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @InvictusMorti, thanks for reporting this. We're tracking this problem in #1779 already, so I am going to close this issue. We'll be trying to fix this problem in the next release in January.

Can you try opening the design in the web version on app.avocode.com? Is it happening to only one design or to multiple? Did you try to re-upload that particular design?
