### ISSUE TITLE
opening the case 1784 - too many bugs in app 

### ISSUE THREAD

**Issue by navid-farjad** [avocode/avocode#1798]
Hi , the uploaded files (psd files) looks completely different in Avocode. it seems Avocode can not read the photoshop file well.
please take a look at this:

original:
https://drive.google.com/open?id=1B5ETckK2AhxDQLVUYPjX8hIaqLUzoUU9

Avocode:
https://app.avocode.com/view/ab04796be8f44394a0c5f4a059172dca/

Most of our files looks different and has same problem and we can not use the app.
We request refund or extending our service as we paid for last subscriptions for 7 people and we could not use the app

Thank you in advance for your service
Best Regards

**Comment by jakubzitny** [comment]
Thanks for the detailed report @plansurgery, we had a look at this and the main problem here is that we don't support the group vector masks you're using yet.

We're actually finishing our new rendering engine and we'll soon support a lot more features from PS and Sketch, including the specific masks combined with effects.

Once we have it ready, we'd be happy you give one more try, we'll let you know 😉

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. 

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
