### ISSUE TITLE
Holding Space for hand tool doesn't work properly on windows

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#180]
Ok, so this is a part where you seem to have quite a lot of issues.

1) The hand tool's hotkey is supposed to be "S or hold space". Yeah, but the slice tool is also "S." That is, according to the tooltips. According to the "Settings" menu, the hand tool is "H" which works.

2) Most of the times when I pick the Select tool and hold space, it keeps on with selecting my layers instead of temporarily switching to the hand tool. I observe this bug very often on Windows after alt/tabbing a few times.

**Comment by petrbrzek** [comment]
Thanks, we'll look at those.

**Comment by VPenkov** [comment]
Seems to be fixed now

**Comment by VPenkov** [comment]
Nope, the second issue still persists. I'm not sure what causes it, but after prolonged usage, holding space stops working.

**Comment by rychlis** [comment]
Sorry for the lack of response. I can replicate the issue now on my windows machine. Doesn't seem to be happening in Linux and OSX

**Comment by VPenkov** [comment]
7 months later, I'm still struggling to find the logic behind this. I presume some sort of logging could shed some light into this.
I'm pretty much using Avocode all the time so I suppose if you can tell me how to activate debugging, I could assist.

**Comment by vojtatranta** [comment]
this should be fixed in newer versions, please update and comment this issue, if it still persists.
