### ISSUE TITLE
No upload

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#1807]
Hello! Houston we have a problem! Do not load layouts from the sketch ((
It happened after the update.

sketch 48.2
os: sierra
avo: 2.17.2

**Comment by Webdesme** [comment]
found a beta version in the package, it also did not help, you can give a link to the old version, please

**Comment by Webdesme** [comment]
http://www.lavuix.ru/scr/2018-01-10_12-18-44.png The old version loads layouts in an avocode

**Comment by vojtatranta** [comment]
Hello @Webdesme ,
like no layouts from Sketch? 

Could you send us problematic sketch files?

**Comment by Webdesme** [comment]
files are confidential, write your mail

**Comment by jakubzitny** [comment]
Hi @Webdesme, you have very old version of both Sketch and our plugin. We already have automatic update of Sketch plugin versions but it's possible that such an old Sketch does not support it yet. Can you please try downloading the [latest version](https://avocode-media.s3.amazonaws.com/download/sketch-plugin-new/47.1.4/sketch-plugin-new-mac-47.1.4.sketchplugin.zip) and see if it fixes itself?

**Comment by Webdesme** [comment]
Sorry, edited a comment, the latter version is worth sketch 48.2. The plugin was the last 47.1.5, at the moment it costs 43.7, the new plugin does not load from the sketch in avocode

**Comment by jakubzitny** [comment]
So you cannot reinstall it? Try deleting the Avocode plugin 43.7 and then launching Avocode. (Or doubleclick the one downloaded from the link I sent you). You're still getting 43.7?

**Comment by Webdesme** [comment]
I installed the old plug-in myself, I tried to reinstall the new plug-in, but it does not work exactly, then I installed the old plug-in myself to load the layouts. **Put your version of 47.1.4 and it all worked!** 

The plugin itself is reinstalled from the avocode to the version **47.1.5**, аnd it does not work, please consider this

**Comment by jakubzitny** [comment]
Okay I understand now, and how about `47.1.5`, does that one work? What do you mean by loading layouts? When exactly is it failing? Does it fail to "redirect" to Avocode completely?

Can you please open `Console.app`, filter out messages from Sketch, try syncing with the latest plugin and see if any error messages pop up in Console?

**Comment by Webdesme** [comment]
I'll try but a little later)) until everything works, I would not want to experiment)

**Comment by Webdesme** [comment]
I shot a video with the reinstallation of the plugin and messages that the console output
http://www.lavuix.ru/scr/foravo1449.mp4

**Comment by jakubzitny** [comment]
Thanks a lot for the video @Webdesme, I get it now. Can you please check the contents of `~/.avocode/.app_path` file? It's possible that the plugin cannot find Avocode.app. Can you maybe re-install Avocode and restart your computer too?
```
cat ~/.avocode/.app_path ; echo
```

We're investigating the problem further and get back to you with any new info.

**Comment by Webdesme** [comment]
reinstalled everything as you said, even reinstalled the sketch, after each reinstallation restarted mac
http://www.lavuix.ru/scr/2018-01-12_09-40-41.png console
http://www.lavuix.ru/scr/2018-01-12_09-41-10.png terminal
http://www.lavuix.ru/scr/2018-01-12_09-42-05.png version plugin

**Comment by Webdesme** [comment]
tried, wrote  .. ((in the end at the moment it works
