### ISSUE TITLE
App freezing on Rendering image data (Ubuntu 16.04.3 LTS 64-bit )

### ISSUE THREAD

**Issue by AAtamaniuk** [avocode/avocode#1808]
* **Version**: 2.17.2

* **Web/Desktop**: Desktop

* **Platform/Browser**: Ubuntu 16.04.3 LTS 64-bit (GNOME Shell 3.20.4)

App freezing on Rendering image data.

**Comment by bolekkerous** [comment]
Hey, @AAtamaniuk -
does that happen with all designs or with just a specific one?

Could you please send us any example the problematic file to team@avocode.com or in the in-app chat, so we can figure out what's the problem on our end?

Thanks and sorry for the inconvenience.

**Comment by AAtamaniuk** [comment]
> does that happen with all designs or with just a specific one?

With very big .psd files (more than 1000 layers). Windows app and Web version work fine. I cant send files because its sharing restricted by NDA.

**Comment by gabrielms** [comment]
Same happens with me, no problem for small psds, but it freezes on phase "rendering image" for a big psd file.

**Comment by jakubzitny** [comment]
Do you also have Linux @gabrielms? Can you try our web version at https://app.avocode.com?

**Comment by gabrielms** [comment]
Hi @jakubzitny thanks for your quick feedback.

I tried the web version and it's working like a charm, thanks! :)

**Comment by jakubzitny** [comment]
These issues should be improved a lot in recent releases. There is still a small amount of users with older graphics cards / drivers. We'll be improving the performance for them in the next release even more.
