### ISSUE TITLE
Try to Open symbol

### ISSUE THREAD

**Issue by vAhyThe** [avocode/avocode#1809]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 47.1.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 182763
---
```
Error: Could not download metadata (revision=17523635)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1072324
    at <anonymous>
```

**Comment by bolekkerous** [comment]
Hey, @vAhyThe -
do you still have the same problem even when you try to open that symbol now again?

Could you please send us the problematic Sketch file to team@avocode.com or in the in-app chat, so we can figure out what's the problem on our end? Also a screenshot or the name of the problematic symbol would be really helpful.

Thanks and sorry for the inconvenience.

**Comment by jakubzitny** [comment]
Closing with respect to #1779.
