### ISSUE TITLE
Error upload design from Sketch to Avocode

### ISSUE THREAD

**Issue by rihbim** [avocode/avocode#1810]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 47.1.4
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 68767
---
```
Error: Missing artboards in sync data.
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3604083)
    at e.value (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3603018)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3601170
    at <anonymous>
```

**Comment by bolekkerous** [comment]
Hey, @rihbim -
could you please send us the problematic file to team@avocode.com or in the in-app chat, so we can figure out what's the problem on our end?

Thanks and sorry for the inconvenience.

**Comment by jakubzitny** [comment]
Hi @rihbim, we've just release Avocode 2.20.0 with improved Sketch plugin. Many issues should be fixed, try re-syncing Sketch files and please let us know if you're still having problems.
