### ISSUE TITLE
Software is not scaled correctly on HiDPI displays on windows

### ISSUE THREAD

**Issue by ascii-husky** [avocode/avocode#1818]
---
* **Version**: 2.17.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 145380
* **GPU**: Nvidia 1080
---

![avocode](https://user-images.githubusercontent.com/8591856/35029155-ead7923a-fb59-11e7-9829-df42c05afcb1.png)

I also disabled HiDPI Stage Rendering, with no better result. This happened after I changed my GPU from a nvidia 980 to a 1080.

**Comment by vojtatranta** [comment]
What's the resolution of your monitor?

**Comment by ascii-husky** [comment]
3840 × 2160

**Comment by ascii-husky** [comment]
3840 × 2160

**Comment by vojtatranta** [comment]
Aha, I see. Only 4K displays seems to be affected by this bug.
We will fix it in the next release.

**Comment by jakubzitny** [comment]
We've released `2.17.3` yesterday, please update and let us know if you if you have any other problems 😉

**Comment by ascii-husky** [comment]
Fixed, thanks!
