### ISSUE TITLE
Avocode has gone bad

### ISSUE THREAD

**Issue by sebastiandammark** [avocode/avocode#182]
This happens overtime I try to open a PSD.
The PSD's are uploaded through dropbox.

I'm running on the latest version.

![screen shot 2015-03-21 at 23 31 12](https://cloud.githubusercontent.com/assets/1575483/6767128/7785c938-d022-11e4-986c-c3e9b6e657b3.png)

**Comment by Rad1calDreamer** [comment]
sometimes i try reopen and it's help for me

**Comment by sebastiandammark** [comment]
I've tried to download, open, save and them upload them again.  But avocode doesn't even see that the file has changed.

**Comment by aazcast** [comment]
It happens to me too... i attached.. i don't find any solution.
![captura de pantalla 2015-04-07 a las 13 47 35](https://cloud.githubusercontent.com/assets/9424920/7031973/b04d4590-dd2c-11e4-8df6-489a91c147cb.png)

**Comment by Rad1calDreamer** [comment]
wait new verison
![capture image](https://cloud.githubusercontent.com/assets/7055577/7039180/742a4708-ddc6-11e4-93ae-d6c0b4287383.png)

**Comment by Rad1calDreamer** [comment]
and they fix it!

**Comment by aazcast** [comment]
thanks, now wait for the new version.

**Comment by Rad1calDreamer** [comment]
you can dowload it right now =)

**Comment by aazcast** [comment]
yes, thanks i just so the email!! i am happy now...

**Comment by aazcast** [comment]
I update it, and i still having the same issue... any solution?
![captura de pantalla 2015-04-08 a las 11 47 40](https://cloud.githubusercontent.com/assets/9424920/7051389/4101bc34-dde5-11e4-9554-968b278f5b9f.png)

**Comment by tomashanacek** [comment]
Hi, could you share us the problematic design to team[at]avocode.com?
Thank you

**Comment by sebastiandammark** [comment]
Mine fails as well.  You already have the PSD's and a zip of '~/.avcd'

**Comment by aazcast** [comment]
I send the email.. Also i make a video, check it: http://cl.ly/3U180f3O3G0s

**Comment by tomashanacek** [comment]
@sebastiandammark Try rm -rf ~/.avcd (Avocode must be turned off)

**Comment by tomashanacek** [comment]
@aazcast 
https://www.dropbox.com/s/6gmx1mgvvu9cpey/travler.mov?dl=0

Try `rm -rf ~/.avcd` (Avocode must be turned off)

**Comment by aazcast** [comment]
Thanks @tomashanacek it works..

**Comment by sebastiandammark** [comment]
Works here also ...

**Comment by Rad1calDreamer** [comment]
error returns.
