### ISSUE TITLE
Incorect width and height

### ISSUE THREAD

**Issue by uginroot** [avocode/avocode#1821]
![image](https://user-images.githubusercontent.com/2391460/35136028-238a6410-fd0b-11e7-9239-c68fc924136a.png)

---
* **Version**: 2.17.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 251688
---
```
No stack trace available
```

Web version correct.
![image](https://user-images.githubusercontent.com/2391460/35139978-a564c55c-fd1f-11e7-8f62-fdfbb64e1ea6.png)

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
