### ISSUE TITLE
Photoshop layer mask not work

### ISSUE THREAD

**Issue by uginroot** [avocode/avocode#1822]
![image](https://user-images.githubusercontent.com/2391460/35144783-ceefe40a-fd2f-11e7-9ede-edcbc6ba7c9b.png)

![image](https://user-images.githubusercontent.com/2391460/35144805-db0ec8fa-fd2f-11e7-93b4-d66d1dce5e68.png)

---
* **Version**: 2.17.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 251688
---
```
No stack trace available
```

**Comment by trurl-master** [comment]
I believe i have the same issue, it's started not long ago, maybe after 2.17.3 was introduced. Masks fail on all newly uploaded designs, but work in preview and in web version, designs uploaded some time ago also work fine. I am on linux, so it's not platform dependent i think.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
