### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by izakrzewska** [avocode/avocode#1824]
* **Version**: 
latest one

* **Web/Desktop**: both

* **Platform/Browser**: windows10, chrome

 iga_zakrzewska@wp.pl

i cannot upload any file

**Comment by Priler** [comment]
Facing same issue.

**Comment by vojtatranta** [comment]
Upload just says "Upload failed"?

**Comment by Priler** [comment]
![image](https://user-images.githubusercontent.com/11755312/35194668-a073ded8-fed8-11e7-8839-5c5c630a11d4.png)

**Comment by Priler** [comment]
Fixed.

**Comment by jakubzitny** [comment]
How about you @iga1801? We're preparing one small improvement for the next release that should help with this kind of issues.

**Comment by izakrzewska** [comment]
In my case nothing happened. Same issue.

**Comment by vojtatranta** [comment]
`2.19.0` was released, this should be fixed
