### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nikita-velikanin** [avocode/avocode#1825]
---
* **Version**: 2.17.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 22734
---
```
Error: The request timed out
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:2184465
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/node_modules/raven-js/src/raven.js:351:21)
```

**Comment by jakubzitny** [comment]
Hi @nikita-velikanin, thanks for submitting this, we're aware of it already from #1781. Do you have any more info you can provide? Is it happening a lot or just once?
