### ISSUE TITLE
Symbols do not load

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1827]
Avocode-2.18.0

* **Version**: 

 Avocode-2.18.0; plugin version-48.2.0

* **Web/Desktop**:
Desktop

* **Platform/Browser**:
macOS High Sierra-10.13.2

After the update, the function of loading selected characters located on the artboards has stopped working. Removing the new version and installing the plugin later 2.16.4 everything works fine
[screencast 2018-01-22 20-28-57.mp4.zip](https://github.com/avocode/avocode/files/1653157/screencast.2018-01-22.20-28-57.mp4.zip)

**Comment by bolekkerous** [comment]
Hey - 
does this still happen for you all the time?

If so, could you try opening your Terminal (CMD + Space > Terminal) and paste and execute these lines one after another in there? After you do that, please try to sync again

cd ~/.avocode
 rm .plugin_confirm_supressed .exclude_symbols

**Comment by Pavlo-Minkievych** [comment]
thanks problem fixed
