### ISSUE TITLE
Error when Check for Update

### ISSUE THREAD

**Issue by i-v-k** [avocode/avocode#1828]
---
* **Version**: 2.17.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 112740
---
```
No stack trace available
```
When trying to Check for Update, App gets error messsage:
Auto update failed
Check your connection

**Comment by vojtatranta** [comment]
I suppose that it has worked before, right?

**Comment by i-v-k** [comment]
Yes, of course.
I updated regularly.
This is the first time I get an error during update.

**Comment by vojtatranta** [comment]
OK. Strange. We tried it out and everything works as expected.

Could you send us squirrel logs located in `c:/Users/<your name>/AppData/Local/avocode/SquirrelSetup` at team@avocode.com ? 

Thanks

**Comment by i-v-k** [comment]
Logs sent.

**Comment by vojtatranta** [comment]
Which email you use in avocode? Is it gork***nov@g**il.com?

**Comment by i-v-k** [comment]
2018-01-23 19:17 GMT+03:00 Vojtěch Tranta <notifications@github.com>:

**Comment by vojtatranta** [comment]
Aha, I see, that's why I couldn't find it. Give me a sec.

**Comment by vojtatranta** [comment]
Aha, I think I have it. It's Electron issue described here: https://github.com/electron/electron/issues/11351

Unfortunately, we can't fix it in Avocode itself. And it seems that you won't be able to update automatically from this version. We are sorry for that. You'd have to install new version manually. From our website.

**Comment by i-v-k** [comment]
OK, thanx, I'll download the latest version from website.

**Comment by vojtatranta** [comment]
@i-v-k download latest `2.18.2` since this release auto updates should work again.

Sorry for these troubles.

**Comment by i-v-k** [comment]
Yep!
