### ISSUE TITLE
Design load time & crash

### ISSUE THREAD

**Issue by sarates** [avocode/avocode#1829]
Design exported by sketch. It took me 10 mins to download 92% of file and Avocode freeze at 4059 / 4392

Avocode 2.18.0

http://i.prntscr.com/VrjyQavZRbSPml2n6Yt8hQ.png

**Comment by crh225** [comment]
@sarates we have large designs also. Just curious, do all of your files take that long to download?

**Comment by vojtatranta** [comment]
Oh, you've got a design with 4400 bitmaps in it?

**Comment by jakubzitny** [comment]
Hi guys, we'll be releasing much faster rendering engine in 2.19.0. Right now it's available on web and it will be available in desktop app in 2.19.0. Rendering large designs with a lots of layers should be faster and you will not need to "download" all the assets before opening the design. You can try this already on app.avocode.com.

**Comment by crh225** [comment]
Im using 2.19.0 in the web and it takes 30 seconds to render an design with only 250 layers.
![image](https://user-images.githubusercontent.com/19475195/35393126-b2732656-01a9-11e8-993a-fe9d5c696e5b.png)

**Comment by crh225** [comment]
Now looking in the console, it says you may have an eventEmitter memory leak.
![image](https://user-images.githubusercontent.com/19475195/35394065-5734a186-01ac-11e8-8182-4025c8025333.png)

**Comment by vojtatranta** [comment]
`2.19.0` was released, this should be fixed

**Comment by crh225** [comment]
@vojtatranta this is not fixed

**Comment by vojtatranta** [comment]
@crh225 alrighty, can you send that original file?

**Comment by crh225** [comment]
I cannot as I am not a designer put I can send you an example avocode link?

**Comment by vojtatranta** [comment]
@crh225 yes, please send me the privat link (just copy url in the browser of that design) Via. email vojtatranta@avocode.com thanks :)

**Comment by crh225** [comment]
https://app.avocode.com/revisions/19412556/?design=11889465

**Comment by vojtatranta** [comment]
:) ok, thanks

**Comment by vojtatranta** [comment]
Aha, it's a sketch file. That's pitty, we cannot access them. You must send it to us, otherwise I cannot debug it :(

**Comment by crh225** [comment]
@vojtatranta you can close ticket. Our designer is remote, so it is difficult for us to get the sketch file. I will email you once we get the sketch file.

Thank you!

**Comment by vojtatranta** [comment]
@crh225 we changed the way how designs are opened in the `2.19.0` but in order to make it work properly, you'd have to reupload that design to try out.

**Comment by jakubzitny** [comment]
Hi @sarates and @crh225, we've improved design opening/loading time in latest Avocode 2.25.0. Please update and let us know if you have any related problems or ideas for improvements 😉
