### ISSUE TITLE
Select tool selects masks which aren't under the mouse cursor

### ISSUE THREAD

**Issue by BrandonLive** [avocode/avocode#183]
My designer uses masks in Sketch sometimes, and it seems that whenever one is used, Avocode miscalculates its size and position when hit testing the mouse cursor. This makes it impossible to click on and select elements on other parts of the page, as it always selects the mask, even though I'm not clicking anywhere near it.

The workaround is to hide all the masks (sometimes there are several) so that I can click on the elements I want to select. But this is pretty annoying, so I'd love to see this fixed soon.

**Comment by petrbrzek** [comment]
That's sucks. Do you think you can send me that design to petr@avocode.com? I'll look into it and let you know what's wrong.

PS: Sorry for the late response.

**Comment by enzy** [comment]
I can confirm this - Avocode is ignoring layer mask when inspecting via measure tool.

![screenshot](http://msimek.cz/9663496a34.png)

**Comment by enzy** [comment]
How is this still open? It's the major usability issue which bothers me daily.

**Comment by connor-bean** [comment]
Can you send us the problematic design to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by enzy** [comment]
I can't send you the design, it's under NDA, sorry.

But you can create it yourself. Open sketch, place some images, make a mask for them and voila, you have a test file.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
