### ISSUE TITLE
Import of name.psd failed

### ISSUE THREAD

**Issue by vilka-vk** [avocode/avocode#1830]
* **Version**:  2.18.1

* **Web/Desktop**: Desktop

* **Platform/Browser**: MacOS Sierra 10.12.6 (16G1114)

**Comment by jakubzitny** [comment]
Hi @vilka-vk, how exactly is the import failing. Is it happening with one specific PSD or all uploads? Also, what platform are you using please?

**Comment by vilka-vk** [comment]
Yesterday avokod said that imports of error and can be opened design only for commenting. In the web version opened normally. Today already in the desktop version opened successfully. Today there is no import error.
It was only with one design.

P.S. I updated the information in the first comment.

**Comment by jakubzitny** [comment]
Thanks, so if everything is okay I'll close this issue.
