### ISSUE TITLE
Font weight bug

### ISSUE THREAD

**Issue by kuzvac** [avocode/avocode#1834]
* **Version**:  2.18.1

* **Web/Desktop**: Desktop

* **Platform/Browser**: Mac

* **Avocode e-mail**:  kuzvasiliy@gmail.com

1. Previously Avocode show information about what font weights is used for separated fonts inside Info, now it's gone :( http://prntscr.com/i4vxwr
2. Avocode show weird font weight: Avocode http://prntscr.com/i4vzge Chrome 64.0.3282.113  http://prntscr.com/i4w32r

**Comment by vojtatranta** [comment]
Hi @kuzvac ,
could you send us that problematic file at team@avocode.com?

**Comment by kuzvac** [comment]
@vojtatranta yup, sended!

**Comment by jakubzitny** [comment]
Thanks @kuzvac, we've fixed this internally, should be available in the next release.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. There should also be the full Postscript font name in the style panel available.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
