### ISSUE TITLE
Uploading XD file with special characters doesn't work

### ISSUE THREAD

**Issue by desir2web** [avocode/avocode#1835]
---
* **Version**: 2.18.2
* **Sketch plugin version**: 48.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 255176
---
```
Error: Failed to open Adobe XD CC design in 20000ms.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:3819334
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/node_modules/raven-js/src/raven.js:351:21)
```

**Comment by jakubzitny** [comment]
Hi @desir2web, thanks for reporting this issue. Which version of Adobe XD do you have please? Did you try uploading by dragging and dropping a .xd file to Avocode or did you try the XD menu option `Export -> Avocode`?

**Comment by desir2web** [comment]
`Export -> Avocode`, `Browse Files` and drag-n-drop: same result with large file (81mb)
For small file export works fine.

**Comment by desir2web** [comment]
Just a minute ago have the same issue with small file. https://github.com/avocode/avocode/files/1660083/Test.Avocode.XD.xd.zip

**Comment by desir2web** [comment]
Using the latest versions if Avocode and Xd

**Comment by jakubzitny** [comment]
Thanks for the file and info, this is weird though. Avocode is waiting 20s for "response" from XD. If the communication works correctly, the size should not matter. Can you try reseting both XD and Avocode, closing all "other" documents in XD (leave open just the one you want to sync) and just try the `Export -> Avocode` trigger? Are you always getting the 20000ms error?

**Comment by desir2web** [comment]
yep, unfortunately it happens again and again (even after reseting and only with 1 file opened in Xd)

**Comment by jakubzitny** [comment]
Ohh, I think I know what the issue here is, sorry about that. It's the `+` in the filename. Please rename the file and it should work correctly. We will definitely fix this for the next version.

**Comment by desir2web** [comment]
Yeah, you were right. Also import process ignore the art-boards with `+` in the title

**Comment by desir2web** [comment]
But works fine with `—`, `=` and `&`

**Comment by jakubzitny** [comment]
Really? The artboard with + that you sent worked for me actually, after I renamed the file. We ignore some artboard on purpose though, the ones that start with `_` or `-`.

**Comment by desir2web** [comment]
oh, now it works)) but the larger file don't have any + mentions in file name or art-boards name still show the timeout error

**Comment by jakubzitny** [comment]
Would you mind sharing the larger design too? If you don't want it to be public you can send it to team@avocode.com.

**Comment by desir2web** [comment]
Sorry but I can't — NDA

**Comment by jakubzitny** [comment]
How about trying [this one](https://upx.cz/iJL)? It's a 91MB XD file, can you please try if that works for you?

**Comment by desir2web** [comment]
This one works fine, seems like it depends on art-boarts count. In my file there are more then 500+ art-boards :D

**Comment by jakubzitny** [comment]
Allright, we've tested around 200, we'll test more artboards for the next release and hopefully fix your problem.

**Comment by desir2web** [comment]
630 — this is exact current count of art-boards... As an suggestion: set the timeout depending on art-boards count, if it possible to get this info from Xd. Anyway, thank you guys for help.

**Comment by jakubzitny** [comment]
Yes it is, the timeout is only for the initial "connection" to XD, not for actually fetching the data, so I think we should be able to fix this.

Thanks for you help! We'll let you know when the new update is available 😉

**Comment by vojtatranta** [comment]
`2.19.0` was released, this should be fixed
