### ISSUE TITLE
Can't get layer info

### ISSUE THREAD

**Issue by desir2web** [avocode/avocode#1837]
Can't select `the-creative-exchange-398774` layer because of `Rectangle 1` layer, but it should (Rectangle 1 have only border and it will be waisting of time to arrange layers properly every time).
[Test Avocode+XD.xd.zip](https://github.com/avocode/avocode/files/1660083/Test.Avocode.XD.xd.zip)

**Comment by jakubzitny** [comment]
Thanks for the file again, this is also a bug with selecting layers. I can reproduce it. We'll release improved inspection in `2.19.0` and this issue should be fixed there as well.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
