### ISSUE TITLE
da

### ISSUE THREAD

**Issue by xetronium** [avocode/avocode#1839]
Crashing while upload psd file.

App v. `2.18.2`

**Comment by jakubzitny** [comment]
Hi @xetronium, do you have any more info on this? How does it crash? Is it happening to all PSD uploads or just a specific one? Did you try uploading via our web app at app.avocode.com?

**Comment by jakubzitny** [comment]
Hi @xetronium, do you have any more info on this? How does it crash? Is it happening to all PSD uploads or just a specific one? Did you try uploading via our web app at app.avocode.com?

**Comment by jakubzitny** [comment]
Hi @xetronium, we've released `2.19.2` yesterday with improved performance and memory usage. Can you please update and let us know if you still have problem using the app?
