### ISSUE TITLE
Template doesn't open

### ISSUE THREAD

**Issue by PostnikovAlex** [avocode/avocode#1841]
---
* **Version**: 2.18.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 258321
---
```
Error: connect ECONNREFUSED 13.33.244.43:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by jakubzitny** [comment]
Hi @AlexNuclear, thanks for submitting this. We can see some problems with network, we're tracking this already in #1775. How often is this happening, please?

**Comment by PostnikovAlex** [comment]
it happens in at least 30% of the templates i try to open up 


>Пятница,  2 февраля 2018, 11:59 +03:00 от Jakub Žitný <notifications@github.com>:
>
>Hi  @AlexNuclear , thanks for submitting this. We can see some problems with network, we're tracking this already in  #1775 . How often is this happening, please?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Александр Постников

**Comment by jakubzitny** [comment]
Is it during uploading the design or only after it is uploaded when you're trying to open it? Have you tried our web version at http://app.avocode.com?

**Comment by PostnikovAlex** [comment]
after uploading 


>Пятница,  2 февраля 2018, 12:19 +03:00 от Jakub Žitný <notifications@github.com>:
>
>Is it during uploading the design or only after it is uploaded when you're trying to open it? Have you tried our web version at  http://app.avocode.com ?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Александр Постников
