### ISSUE TITLE
Default code settings.

### ISSUE THREAD

**Issue by StasiukYurii** [avocode/avocode#1844]
Can't change default code settings to an preprocessors in global preferences.
Windows 10 app.
![screenshot_1](https://user-images.githubusercontent.com/17325694/35782617-2e2342d4-0a03-11e8-8383-459fab83114e.png)
![screenshot_2](https://user-images.githubusercontent.com/17325694/35782618-2e40fefa-0a03-11e8-9798-d8af620c7131.png)

---
* **Version**: 2.18.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 125155
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Thanks for the report @mr-stasyuk. Actually what you're switching in the Preferences modal is only the settings for specific languages. If you want to change the language in Code panel, you can do it only in the panel.

I know it's painful for you to always change the pre-processor for Web projects if you don't use CSS. Currently you cannot do this in Avocode, but we're aware of this limitation and we're working on improvement.

We're already tracking this in #1623 so I am going to close this issue, but we'll let you know when we release a new version of Avocode where you can set this up properly.
