### ISSUE TITLE
Most text in the app UI is blurry

### ISSUE THREAD

**Issue by BrandonLive** [avocode/avocode#185]
While not as bad as the content rendering issue I opened just before this, I've also noticed that most text in the app is a little blurry. Oddly, a few things stand out as _not_ having this problem, like the "X: 108px Y: 207px" indicator at the bottom of my screen right now which showed up when I used the Slice tool.

I'm not sure if this is another bug with high DPI displays (which seems odd as Chrome handles them fine nowadays) or something else. But it does make the app less pleasant to work with.

**Comment by marekhrabe** [comment]
I think we are not handling various high DPI displays on Windows correctly. I filed that as a bug in our internal bug tracking system and we will fix the bug once have setup where we can test this issue properly. We are currently testing high DPI just on Mac Retina displays (they are @2x) and following common high DPI recommendations, but that might not be enough…
