### ISSUE TITLE
Desktop App not working error webGL not compatible

### ISSUE THREAD

**Issue by ghost** [avocode/avocode#1850]
---
* **Version**: 2.19.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 238665
---
```
No stack trace available
```

**Comment by vojtatranta** [comment]
Hello @dmg-luiz ,
wer are sorry to hear that. Does a webgl unavailable popup show? If so, it seems that your graphics card is unable to support WebGL which is and issue. However, you still can disable WebGL rendering by going to App Preferences and selecting `Disable Monroe rendering engine`

**Comment by ghost** [comment]
thank you! worked for me
