### ISSUE TITLE
Cannot open designs

### ISSUE THREAD

**Issue by Bilverin** [avocode/avocode#1853]
---
* **Version**: 2.19.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 167141
---
```
Stuck at "Rendering Design" and then return to designs page. The same trouble in web app:
http://prntscr.com/ibqq4z
```

**Comment by glutaminefree** [comment]
Same here! Can't open any design.

* **Version**:  2.19.0
* **Web/Desktop**: both
* **Platform/Browser**: Fedora 26 x64 / Firefox 58.0.1 x64

**Comment by vojtatranta** [comment]
Hi @Bilverin and @glutaminefree ,
the designs really never open and no error pops up, right?

You can disable WebGL rendering by going to App Preferences and checking `Disable Monroe rendering engine`

**Comment by Bilverin** [comment]
Large designs just stuck at "Rendering Design..." and that's all. Small files open without problems.
"You can disable WebGL rendering by going to App Preferences and checking Disable Monroe rendering engine" - it's help, thank you.

**Comment by glutaminefree** [comment]
>You can disable WebGL rendering by going to App Preferences and checking Disable Monroe rendering engine

I can't hide any layer in design in this mode. But all layers have 'hided' icon. And designer's guides always visible - it's bad.

**Comment by vojtatranta** [comment]
@glutaminefree aha, it seems that visibility toggle states are broken initially. It seems that it works when you toggle a layer visibility, or no?

Guides do not seem to be visible. Could you send me a screenshot?

**Comment by vojtatranta** [comment]
Aha, groups cannot be hidden. That's a bug.

**Comment by glutaminefree** [comment]
@vojtatranta ![screenshot_20180208_123343](https://user-images.githubusercontent.com/2122419/35965561-5cd1b7c0-0ccc-11e8-9b10-70f50b279f82.png)

Design in this mode rendered with glitches.

**Comment by vojtatranta** [comment]
@glutaminefree These "guides" are not in the app. These are in the design. Could you send me that original file? at vojtatranta@avocode.com?

**Comment by glutaminefree** [comment]
@vojtatranta Yes, I know it. But I can't hide it :(
Right now I need to work. Where can I download 2.18.2 version for while?

**Comment by jakubzitny** [comment]
@glutaminefree: 64-bit Linux [here](https://media.avocode.com/download/avocode-app/2.18.2/avocode-2.18.2-linux.zip) and 32-bit [here](https://media.avocode.com/download/avocode-app/2.18.2/avocode-2.18.2-ia32-linux.zip).

**Comment by glutaminefree** [comment]
@jakubzitny Thanks!

**Comment by vojtatranta** [comment]
@glutaminefree just tried that design and glitches are just layers and can be hidden by clicking on the "eye" symbol (there is a bug that initially this toggle seems to be off, but it works)

**Comment by Catofwanders** [comment]
I have the same problem. And try to install old version, but it autoupdate to 2.19! 
 My comrads work well and it is only in my computer.

**Comment by vojtatranta** [comment]
@Catofwanders our servers should be in the good mood now. Opening of the design should be much better, can you try out in the `2.19.0`?

**Comment by vojtatranta** [comment]
This should be improved in `2.19.1`. There was a memory allocation fault in the rendering. Would you try now? 

@glutaminefree problem with layer visibility is fixed, group layers are not hidable.

Reopen if it's still not OK.
