### ISSUE TITLE
Can't open designs

### ISSUE THREAD

**Issue by ilia-konovalov** [avocode/avocode#1854]
I can't open designs after downloading new version...

---
* **Version**: 2.19.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 266643
---
```
No stack trace available
```

**Comment by vojtatranta** [comment]
Hi @technomas ,
what is it doing?

You can switch of new rendering by going to App Preferences and checking `Disable Monroe rendering engine`

**Comment by ilia-konovalov** [comment]
Disabled. 
Downloading metadata... and nothing

**Comment by ilia-konovalov** [comment]
Where can I download 2.18.2 version?

**Comment by vojtatranta** [comment]
@technomas aha, our servers are now under a heavy load. 

[here's windows 2.18.2 version](https://avocode-media.s3.amazonaws.com/download/avocode-app/2.18.2/Avocode%20Setup%202.18.2.exe)

**Comment by vojtatranta** [comment]
This should be fixed in `2.19.1`
