### ISSUE TITLE
Preview project

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#1858]
I'm at a loss) it's not a complaint, but rather a request, to return the old display or to fill in the project image yourself, for example projects exported from a sketch look like this http://www.lavuix.ru/scr/2018-02-08_15-49-21.png . There are only two characters not talking about the project anything) and it looks strange

**Comment by jakubzitny** [comment]
Hi @Webdesme, we'll update the tile looks in the next release a bit, so it's a bit less strange in such cases. We're also considering to allow users to choose or upload the project thumbnails, we'll see how that works out 😛

**Comment by jakubzitny** [comment]
From this:
<img width="1370" alt="screen_shot_2018-02-08_at_16 19 58" src="https://user-images.githubusercontent.com/3315662/36023341-68392ccc-0d8c-11e8-98cf-7cd5913499d0.png">

To something like this:

<img width="1365" alt="screen_shot_2018-02-08_at_16 27 45" src="https://user-images.githubusercontent.com/3315662/36023347-6fa41cc4-0d8c-11e8-928b-0cba7f16e03d.png">


Would that work?

**Comment by Webdesme** [comment]
it would be cool to download the project image yourself, for example, put the logo of the project, we will wait for the update
