### ISSUE TITLE
SVG exports are really base64 png's

### ISSUE THREAD

**Issue by scottwio** [avocode/avocode#186]
When I try to export a smart object as an SVG in actually produces a svg file with a image element which has base64 png attached to it on the xlink:href= tag. Is this expected behavior can avocode not produce real svg elements?

**Comment by Rad1calDreamer** [comment]
+1

**Comment by paulburgess** [comment]
+1 - I was really confused by this and was asking the designers if they had rasterised the vector elements as the SVGs weren't really scalable - but seeing this I guess Avocode just doesn't produce them

**Comment by tomashanacek** [comment]
Duplicate of #81, moved to user voice https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992611-illustrator-support
