### ISSUE TITLE
Eat RAM more then Photoshop!

### ISSUE THREAD

**Issue by asylbek23** [avocode/avocode#1863]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.19.0`

**Comment by jakubzitny** [comment]
Hi @Asylbek23, sorry to hear that, we're improving the performance issues with every update. What platform do you use, please? Can you work with Avocode at all? How often is this happening?

The app speed depends a bit on the number of projects and designs you have locally. Resetting the app should help, or try using our web version at [app.avocode.com](http://app.avocode.com) to see if it's faster 😉

**Comment by jakubzitny** [comment]
Hi @Asylbek23, we've released `2.19.2` with improved performance and memory usage. Can you please update and let us know if you still have problem using the app?
