### ISSUE TITLE
does not open psd

### ISSUE THREAD

**Issue by diefair** [avocode/avocode#1866]
I've upgraded the version and I can not open psd. how do i go back to the old version?

---
* **Version**: 2.18.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 30187
---
```
No stack trace available
```

**Comment by vojtatranta** [comment]
You are running `2.18.2` as it seems. It is an older version. The newest version released yesterday is `2.19.1`.

Can you be more specific what does not work?
