### ISSUE TITLE
Keyboard shortcuts for moving the canvas.

### ISSUE THREAD

**Issue by Neppord** [avocode/avocode#187]
As a Developer i like to not move my hands from my keyboard more then i need to, and if possible not even from the home-row.

If it is possible to configure the `hjkl`, arrow keys and/or `wasd` to scroll that would be great!.

**Comment by petrbrzek** [comment]
Great idea. I move this idea to UserVoice. You can follow it [here](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7513957-keyboard-shortcuts-for-moving-the-canvas).
