### ISSUE TITLE
Bug - crash

### ISSUE THREAD

**Issue by error32** [avocode/avocode#1871]
---
* **Version**: 2.19.1
* **Sketch plugin version**: 48.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 260465
---
```
Error: getaddrinfo ENOTFOUND manager.avocode.com manager.avocode.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by jakubzitny** [comment]
Hi @error32, we're already tracking this in #1656, so I'll close this thread. Any details on when is this happening? Does it happen all the time or just from time to time?
