### ISSUE TITLE
Connection problem. Still trying...

### ISSUE THREAD

**Issue by richvoronov** [avocode/avocode#1873]
God damn it! This happens every time when I upload a new PSD file! AAAAA!

I'am sure!

---
* **Version**: 2.19.1
* **Desktop (web version is okay)**: Desktop
* **Platform**: darwin
* **Avocode UID**: 262358

OSX latest update!

---
```
Error: Could not download metadata (revision=20286932)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1270956
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @richcrowe, we're aware of this problem from #1779 already, thanks for submitting. Is it only the first time after you upload a file or you cannot open it at all? Can you try it on our web version app.avocode.com?
