### ISSUE TITLE
Desktop app work very slovly

### ISSUE THREAD

**Issue by greencityarcher** [avocode/avocode#1879]
Avocode 2.19.2
Desktop Application on Ubuntu 16.04

Problem is after upgrade to this version desktop app work very slovly. It inhibits all other programs: browser, IDE and other.
I work with PSD Design.
I tryed open my design in web application, but it crashed with message about problem with WebGL

**Comment by vojtatranta** [comment]
Hello @greencityarcher ,
we noticed a problem with RAM consumption and we tried to fix it in `2.19.2` and it was much better.

Does Avocode slows down all other programs even when no designs is opened?

**Comment by jakubzitny** [comment]
Hello @greencityarcher ,
we noticed a problem with RAM consumption and we tried to fix it in 2.19.2 and it was much better.

Does Avocode slows down all other programs even when no designs is opened?

**Comment by jakubzitny** [comment]
Hello @greencityarcher ,
we noticed a problem with RAM consumption and we tried to fix it in 2.19.2 and it was much better.

Does Avocode slows down all other programs even when no designs is opened?

**Comment by greencityarcher** [comment]
Hello! No, if no designs opened, but avocode started, other program work normally. I have updated avocode to new version and now it working much better. I can open 3-4 designes at one time and normally work. Thanks for fix!
