### ISSUE TITLE
Open a project in Windows 8

### ISSUE THREAD

**Issue by SFCMiguel** [avocode/avocode#188]
Hello, in my company we are with this problem in Windows 8, anyone knows a fix to this?

http://screencast.com/t/KVgKivp98CZf

It's only in one project, and in Windows. All the other projects it's opening well and in mac we can access this project.

Thank you

**Comment by petrbrzek** [comment]
We know that huge designs like `15000px x 15000px` are a big problem on Windows. Is this the case?

**Comment by rychlis** [comment]
I'm closing this as there was no response from you for a long time. Feel free to re-open it, but in case the design resolution is large like petr said, this is a duplicate of #143
