### ISSUE TITLE
Failed to open Adobe XD CC design

### ISSUE THREAD

**Issue by mican** [avocode/avocode#1883]
---
* **Version**: 2.19.2
* **Sketch plugin version**: 48.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 374
---
```
Error: Failed to open Adobe XD CC design in 20000ms.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4149091
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:360:21)
```

**Comment by vojtatranta** [comment]
Hi @mican ,
can you please confirm that you have latest Adobe XD installed?

How big is that XD design? Is it hundreds of megabytes?

**Comment by jakubzitny** [comment]
Hi @mican, is the XD file you're uploading on a Dropbox/iCloud/GDrive drive or a similar unusual or remote location?

**Comment by mican** [comment]
Hi guys, sorry for a delay.

It didn't work with XD 3.1.12, but after update to XD 5.0.12.8 it works well.

Thank you.

**Comment by jakubzitny** [comment]
Oh yeah, we support only XD 4+, so that was definitely the problem. Glad to hear that it's resolved now.

Don't hesitate to let us know if you have any more problems ;)
