### ISSUE TITLE
Incorrect display of psd layouts!

### ISSUE THREAD

**Issue by asylbek23** [avocode/avocode#1884]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 268682
---
```
No stack trace available
```

**Comment by vojtatranta** [comment]
hi @Asylbek23 ,
can you send the original PSD file and a screenshot of what's the problem?

Do you have Monroe engine turned on or not?

**Comment by asylbek23** [comment]
​

2018-02-16 21:57 GMT+06:00 Vojtěch Tranta <notifications@github.com>:

**Comment by jakubzitny** [comment]
Hi @Asylbek23 ,
can you send the original PSD file and a screenshot of what's the problem?

Do you have Monroe engine turned on or not?

**Comment by jakubzitny** [comment]
I see you have this problem repeatedly, but please provide us with more info so we can actually improve our rendering and help you if possible. I will close this with respect to #1911.
