### ISSUE TITLE
does not load some artboards and symbols

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1885]
2.19.2

2.19.2

* **Version**: 

48.2.0

* **Web/Desktop**: 
Desktop

* **Platform/Browser**:
macOS High Sierra 10.13.3

it-subscriptions@w3.co

Does not load some artboards and symbols.
When you separate download artboards and symbols creates two different projects and does not get into one as before but loads without errors.
https://monosnap.com/file/OmmINb3nSp0BCyzyPfYXcmCrSjBVXT

**Comment by vojtatranta** [comment]
Hi @Pavlo-Minkievych ,
so, importing from Sketch creates multiple projects? That is really odd.

**Comment by jakubzitny** [comment]
Hi @Pavlo-Minkievych, we've just release Avocode 2.20 with improved Sketch plugin (again). Many issues should be fixed, try re-syncing Sketch files and please let us know if you're still having problems.
