### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DatiQ** [avocode/avocode#1887]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 60839
---
```
Error: Could not download metadata (revision=20460247)
    at file:///C:/Users/datix/AppData/Local/avocode/app-2.19.2/resources/app.asar/dist/avocode.min.js:1:1278805
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @DatiQ, thanks for reporting this. We're already tracking this problem in #1779. Did you try using our web app at app.avocode.com? It might help with this issue.
