### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#1889]
Hi, here I have data diverge. This is a screen from the list of layouts
http://www.lavuix.ru/scr/2018-02-19_12-38-27.png

And this screen from the screen inside the layout
http://www.lavuix.ru/scr/2018-02-19_12-39-16.png

what could it be? and how to fix it?

avocode 2.19.2
macosx

**Comment by renekopcem** [comment]
Hello, I found out that we have an inconsistency in endpoints for designs (returns different values, kind of obvious :)).

Thank you for noticing and feedback. It will be fixed soon.

**Comment by jakubzitny** [comment]
Hi @Webdesme, we've fixed this problem. Let us know if you see it (or anything else) again 😉
