### ISSUE TITLE
Spacing between objects is shown in the wrong place

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#189]
Ok, so, I wanna know the space between two horizontal lines. So I click on one of them, then hold Alt and point at the other one. The space between them is displayed by the measure tool, no issues here.

But the measure tool appears at the horizontal center of the element I've selected. So if I zoom in a lot to the right or left, I may be unable to see it because it's gonna be away from my viewport.

**Comment by petrbrzek** [comment]
Take your point. I created an issue in our internal system.

**Comment by rychlis** [comment]
We've added the measure tool values to the bottom status bar 3 months ago so you can see the values even when the line is out of your viewport.

**Comment by VPenkov** [comment]
The UX problem still persists in that case. This would be merely a workaround.

**Comment by rychlis** [comment]
Well I though the main concern was that you was not able to see the values. I guess I can re-open if the workaround is not satisfying for you

**Comment by VPenkov** [comment]
It's your call, I'm not a decision maker for Avocode. I just pointed out a UX problem.
I've been using Avocode since the betas but I haven't noticed the values in the bottom status bar until you told me, hence my previous reply.
