### ISSUE TITLE
Problem with inspection PSD

### ISSUE THREAD

**Issue by bogfront** [avocode/avocode#1900]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 224263
---
```
Error: Could not download metadata (revision=20761653)
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1278805
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @superboggg, thanks for reporting this. We're already tracking this problem in #1779. Did you try using our web app at app.avocode.com? It might help with this issue.
