### ISSUE TITLE
does not load design

### ISSUE THREAD

**Issue by Pavlo-Minkievych** [avocode/avocode#1907]
---
* **Version**: 2.20.0
* **Sketch plugin version**: 48.2.8
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 68767
---
```
Error: Could not download metadata (revision=20884100)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1315199
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @Pavlo-Minkievych, thanks for the report. We are aware of this already in #1779. We're working on a fix and it'll be hopefully included in 3.0 release in coming weeks.

For now, please try opening the design in our web app.
