### ISSUE TITLE
React Native - Quotes placed around numerical values

### ISSUE THREAD

**Issue by evanalmighty** [avocode/avocode#1909]
* **Version**: 2.20.0

* **Web/Desktop**: The issue is occurring on both.

* **Platform/Browser**: OSX & Chrome

![screen shot 2018-02-27 at 9 52 01 pm](https://user-images.githubusercontent.com/6530121/36769219-7edbb79e-1c08-11e8-8dbd-7fad68f69c5d.png)

When trying to get React native component styles Avocode is placing quotes around numerical values. The value should output as a number like in [this screenshot](https://avocode.com/static/webflow/nachos-ui/images/screen.jpg) from the Nachos UI landing page.

Great application by the way, I've been using it for a few years now!

**Comment by jakubzitny** [comment]
Hi @EvanAlmighty, thanks for letting us know. We'll have a look at it and fix it for one of the upcoming versions.

Please let us know if you have any more requests or problems 😉

**Comment by vojtatranta** [comment]
This will be fixed today.

**Comment by jakubzitny** [comment]
Fixed in 2.22.1.
