### ISSUE TITLE
Color picker bug when windows scale is 150%

### ISSUE THREAD

**Issue by FredRad** [avocode/avocode#191]
Český popis dole ;)
## Dear Avocode developers

I'd like to report a bug I'm experiencing when I scale my Windows 7 to 150% what I use to have all the elements bigger on my laptop screen.

You can set this in Control panel -- Appereance and customization -- Displaying [Ovládací panely -- Vzhled a přizpůsobení  -- Zobrazení].

I'm experiencing the problem with the color picker tool. The color picked doesn't correspond with the color I see when hovering over the element. Simply the color, which is really picked when I click, is from somewhere else than where I currently have the cursor.

Please see the attached images:
![01_scale-settings](https://cloud.githubusercontent.com/assets/11788043/6985460/e1619164-da33-11e4-9a97-d4a43f44d6fb.png)

![02_what-color-i-see-above-the-picker](https://cloud.githubusercontent.com/assets/11788043/6985459/e15fd720-da33-11e4-9c3d-568e98f23206.png)

![03_what-color-it-really-picks](https://cloud.githubusercontent.com/assets/11788043/6985458/e15fd202-da33-11e4-9f71-edffc4412f29.png)

---

Pokud mám zvětšené zobrazení ve Win 7 [Ovládací panely -- Vzhled a přizpůsobení  -- Zobrazení], color picker pickuje barvy odjinud, než kde se nachází kurzor.

**Comment by kojoru** [comment]
I can confirm I'm seeing the same issue on a HiDPI (200% zoom) Windows 8.1 machine
