### ISSUE TITLE
Cant sync my Adobe XD project

### ISSUE THREAD

**Issue by tommypd** [avocode/avocode#1910]
---
* **Version**: 2.20.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 280906
---
```
Error: Failed to open Adobe XD CC design in 20000ms.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4242162
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:360:21)
```
I cant sync any project with Avocode and adobe XD (5.0.12.8) also in adobe xd cant see Avocode in export tab.

**Comment by jakubzitny** [comment]
Hi @tommypd, thanks for reporting this problem. We have similar issues in #1897 and #1891 where this is related to syncing files from Dropbox folders or the path to XD file or the name of it contains some special characters (like `#` for example). 

However, the fact that you can't see the Avocode export tab at all is really weird. Did you have any pre-release version of Adobe XD installed before? Or did you update from XD v3? Can you please check what's inside `/Users/<yourusername>/Library/Application Support/Adobe/Adobe XD CC` folder?

**Comment by jakubzitny** [comment]
Closing with respect to #1897. The fix will be included in one of the upcoming releases.
