### ISSUE TITLE
Incorrect display of psd template

### ISSUE THREAD

**Issue by asylbek23** [avocode/avocode#1911]
Incorrect display of psd template. Some pictures and even texts are not displayed!

I have 2.20.0 version

---
* **Version**: 2.20.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 279619
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @Asylbek23, thanks for letting us know. We need more details on your problem to help you with it though. I just looked at the only file you uploaded to Avocode (in your current account) and everything looks okay to me. Can you send us which layers are rendered incorrectly? Or record a video of the differences between Photoshop and Avocode?

**Comment by jakubzitny** [comment]
Details are in #1919. Closing.
