### ISSUE TITLE
Code settings and designs get reset every time I open Avocode

### ISSUE THREAD

**Issue by i-v-k** [avocode/avocode#1913]
* **Version**: 2.20.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 112740
---
After upgrade to 2.20 every time I open Avocode I have to download my previously rendered designs from server and wait for full render cycle. None of the previously downloaded designs are available offline.
And code settings get reset every time I open Avocode so I have to set them again and again and again...

**Comment by jakubzitny** [comment]
Hi @i-v-k, sorry this is a bug in 2.20. We are fixing it right now and we'll release an update soon, hopefully today.

**Comment by i-v-k** [comment]
OK, looking forward to it, thanks.

**Comment by jakubzitny** [comment]
This should be fixed in Avocode 2.20.1. Please let us know if you have any other problems 😉
