### ISSUE TITLE
Ctrl+Click Onen new tab 

### ISSUE THREAD

**Issue by retyui** [avocode/avocode#1914]
* **Version**: 2.20.0
* **Web/Desktop**: Desktop
* **Platform/Browser**: Linux Mint x64

If I use Ctrl+Click on design preview 
Design open in new tab and  switches to a new tab

But I expected that I would not be switched to a new tab. 

Very uncomfortable when in the search bar you open the desired design in new tabs, 

It is necessary to switch each time after opening the search tab

**Comment by jakubzitny** [comment]
I see, thanks for the input @retyui. We'll think about changing this behaviour.

Don't hesitate to let us know if you have any other problems 😉
