### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by fristyr** [avocode/avocode#1915]
---
* **Version**: 2.20.0-web.2
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 63.0.3239.132
* **Avocode UID**: 279144
---
```
TypeError: Cannot read property 'action' of null
    at https://fast.appcues.com/24524.js:1:200750
    at r (https://cdn.app.avocode.com/dist/v-9f57037/js/avocode-web.min.js:60:21185)
```

**Comment by jakubzitny** [comment]
Hi @fristyr, do you have any details on this? When did it happen, please? Did you see it more than once?

I believe this is a bug in our onboarding library, we're investigating the issue.

**Comment by jakubzitny** [comment]
This should be fixed in next versions of Avocode.

**Comment by vojtatranta** [comment]
`2.21.0` released
