### ISSUE TITLE
avocode crashed while uploading multiple (3) psds

### ISSUE THREAD

**Issue by umesh-velir** [avocode/avocode#1916]
IMPORTANT: Please try to describe how did the crash happen.

App v. `2.20.0`

**Comment by jakubzitny** [comment]
Hi @umesh-velir, does this happen repeatedly? How about syncing these files one by one? Also, what platform are you on please?

**Comment by umesh-velir** [comment]
@jakubzitny wow, it's the quickest response I have ever seen. Thanks for that. It worked on second attempt. I am on windows 7 and I don't think i ever ran into that issue before with neither one by one file nor multiple files at once.

**Comment by jakubzitny** [comment]
Cool, I think it was some unhandled memory problem thats inside Electron on Windows. We see this sometimes but we can't really reproduce it. I'll close this issue then, we have it in our internal tracking system.

Thanks again and let us know if you have any more problems 😉

**Comment by umesh-velir** [comment]
sounds good. awesome application though! thank you!
