### ISSUE TITLE
I see "Document failed to load" for design uploaded at January 20, 2018

### ISSUE THREAD

**Issue by skushnir** [avocode/avocode#1918]
---
* **Version**: 2.20.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 182950
---
```
Error: Could not download metadata (revision=19154134)
    at file:///opt/Avocode/resources/app.asar/dist/avocode.min.js:1:1319631
    at <anonymous>
```

**Comment by Stormplay** [comment]
I have a similar error. And connect ETIMEDOUT 104.18.57.139:443

**Comment by vojtatranta** [comment]
Hi all,
so these designs never open?

Is it possible to open other designs?

**Comment by vojtatranta** [comment]
Aha, so for @skushnir , your design's parsing failed on our servers. We will take a look at it.

For @Stormplay , ETIMEDOUT is quite hard for me to debug. Is it possible to open that design now, or is it still not working?

**Comment by vojtatranta** [comment]
@skushnir I tried to upload that PSD myself to my team an it's OK. Would you try to reupload it? It should be also OK.

**Comment by skushnir** [comment]
https://app.avocode.com/revisions/19154209/?design=11757993 this design isn't loading.

**Comment by jakubzitny** [comment]
Thanks for the details, @skushnir. We can see the problem with this particular design on our backend and we'll try to fix it 😉 

For now I'll close this with respect to issue #1779 where we are tracking this problem already. Please let us know if it happens with other designs or if you have any other problems.

**Comment by jakubzitny** [comment]
Actually @skushnir, your design should work now, can you give it a try?

**Comment by skushnir** [comment]
Yes, it is working. Thanks
