### ISSUE TITLE
How to open or work on sketch file. 

### ISSUE THREAD

**Issue by deepakc147** [avocode/avocode#192]
Hi! I have try to open sketch files. but on the time uploading it show massage as ( in attached images)

![image](https://cloud.githubusercontent.com/assets/4564649/7033024/9212378a-dd94-11e4-8b9b-faf80b37e86e.png)

I also download the "Sketch extension" as it show in massage but after installing this extension it again give me same error.

Please let me know  what to do.

Thanks

**Comment by petrbrzek** [comment]
It's not possible to drag and drop Sketch files to Avocode Web Manager right now, but we're working on it already. 

In the meanwhile, you can use Sketch extension to upload design files. Here is a nice [tutorial](https://avocode.zendesk.com/hc/en-us/articles/202196441-How-to-install-and-use-our-PS-Sketch-plugin-) how to install it.

**Comment by prog666** [comment]
what if u use linux and have no mac and all you have is sketch file?

**Comment by danReynolds** [comment]
+1

**Comment by rychlis** [comment]
Here is a uservoice idea, please vote to help us measure demand for this feature and to recieve any updates https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7139779-open-sketch-files-without-sketch
