### ISSUE TITLE
Fast navigation

### ISSUE THREAD

**Issue by HtmlMak** [avocode/avocode#1920]
Hey, guys!
Is it possible to realize a quick return to the previous menu with the back key on the keyboard or mouse? Simply, I quite often go through projects in search of the desired layout and, I think, it would be convenient.

**Comment by vojtatranta** [comment]
If you are browsing through project during the searching, just hit Escape and you're back where you were.

If you go inside a project, you can use Backspace to get back.

Does it cover all the use-cases?

**Comment by HtmlMak** [comment]
Oh yeah! I did not know, thank you!

**Comment by jakubzitny** [comment]
I think we should also add a "back" shortcut to project manager. I'll leave this open as enhancement.

**Comment by jakubzitny** [comment]
The backspace actually works in whole project manager already.
