### ISSUE TITLE
Artboards from Sketch and XD are uploading twice

### ISSUE THREAD

**Issue by northfacingdan** [avocode/avocode#1921]
Details of what i'm running:

* Avocode Desktop App **2.20.1**
* Avocode Sketch Plugin **48.2.8**
* Operating system **macOS High Sierra 10.13.3**:

When exporting from Sketch or Adobe XD, avocode makes 2 copies of artboards, taking twice as long to upload. For example, if i have 15 artboards in a file, I end up with 30 in avocode.

**Comment by jakubzitny** [comment]
Hi @northfacingdan, thanks for letting us know. We noticed this and we'll try to fix this problem for the next version. Is this happening all the time or only when Avocode is off before you're syncing a design?

**Comment by northfacingdan** [comment]
Hi Jakub, I often have avocode off before syncing, so I can only comment on that scenario. It’s happened to all my files since the start of the year.

**Comment by jakubzitny** [comment]
Yeah, this will be fixed in `2.21` today 😉 (or tomorrow).

**Comment by vojtatranta** [comment]
`2.21.0` released
