### ISSUE TITLE
issue syncing adobe xd file - pls help

### ISSUE THREAD

**Issue by cameronjoyner** [avocode/avocode#1922]
I just downloaded the latest version and was attempting to open an XD file and it would allow me.

---
* **Version**: 2.20.1
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 285664
---
```
Error: Failed to open Adobe XD CC design in 20000ms.
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:4255184
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/raven-js/src/raven.js:360:21)
```

**Comment by jakubzitny** [comment]
Hi @cameronjoyner, thanks for the report. We've seen this problem few times and usually it was related to either old version of XD (we support only v4+) or that you had some prerelease versions in your system. Sometimes also special characters (like `#`) can cause Avocode to fail detecting a sync from XD.

Can you please let us know what version of XD you use, and what file are you trying to sync? Are you using the `Export -> Avocode` option in XD or are you drag'n'dropping XD file to Avocode, please?

**Comment by jakubzitny** [comment]
Closing with respect to #1897. The fix will be included in one of the upcoming releases.
