### ISSUE TITLE
Feature: save style settings

### ISSUE THREAD

**Issue by crh225** [avocode/avocode#1924]
On the web, everytime I switch to scss style settings, close the browser and open a design, it reverts back to css.

![image](https://user-images.githubusercontent.com/19475195/37171317-18cf674e-22d3-11e8-871e-82b569c54b56.png)
It would be nice if it could have a default per project, or just remember my stetting.

**Comment by bolekkerous** [comment]
Hey, @crh225 - from Avocode version 2.21 on, you can select the default language for a project, but you need to select it in the Project settings, changing it in the design actually overrides the project default.

<img width="551" alt="screenshot 2018-03-12 12 13 15" src="https://user-images.githubusercontent.com/16084852/37280671-c2055526-25ee-11e8-8114-f9e697051262.png">
