### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by n1ckfedorov** [avocode/avocode#1936]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 293452
---
```
Error: Could not download metadata (revision=21561978)
    at file:///C:/Users/Nick/AppData/Local/avocode/app-2.21.0/resources/app.asar/dist/avocode.min.js:1:1303374
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @N1ckFedorov, do you have this problem only with only this one specific file, please? What if you try opening the design on our web app (app.avocode.com), does it work? Did you try re-uploading it? I see no problems on our backend with it, so we need more info for debugging.

**Comment by jakubzitny** [comment]
We tried syncing this design ourselves and everything seems to work. This problem might be windows-specific or related to too much memory being consumed by Avocode. Please let us know if the same thing happens after you re-upload, try the web version.

**Comment by n1ckfedorov** [comment]
@jakubzitny Hi. I have this problem only with  one specific psd file..I try open this file on Web app and on Windows (

**Comment by jakubzitny** [comment]
Did you try to re-upload the file?

**Comment by n1ckfedorov** [comment]
@jakubzitny yep/ <a href="https://ibb.co/iv2FZc"><img src="https://thumb.ibb.co/iv2FZc/image.png" alt="image" border="0"></a>

**Comment by bolekkerous** [comment]
Hey, @N1ckFedorov -
would you be able to send us the specific PSD file you're having problem with to team@avocode.com? And you were uploading the files into Avocode by just drag and dropping it in to Avocode, right?

**Comment by jakubzitny** [comment]
I will close this issue due to inactivity.

Please, let us know about your experience with Avocode via Intercom support or at team@avocode.com, @N1ckFedorov. Did you manage to get it working or did you give up?
