### ISSUE TITLE
errror web

### ISSUE THREAD

**Issue by n1ckfedorov** [avocode/avocode#1937]
---
* **Version**: 2.21.0-web.2
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: chrome 65.0.3325.162
* **Avocode UID**: 293452
---
```
Error: Octopus not available
    at https://cdn.app.avocode.com/dist/v-9a463e2/js/avocode-web.min.js:106:1179693
    at r (https://cdn.app.avocode.com/dist/v-9a463e2/js/avocode-web.min.js:106:27833)
    at https://cdn.app.avocode.com/dist/v-9a463e2/js/avocode-web.min.js:89:419638
```

**Comment by jakubzitny** [comment]
Hi again @N1ckFedorov, is this happening for the same design as in #1936?

**Comment by n1ckfedorov** [comment]
@jakubzitny  yep

**Comment by jakubzitny** [comment]
Allright, closing with respect to #1936, let's continue there.
