### ISSUE TITLE
Error when try lunch avocode on Ubuntu

### ISSUE THREAD

**Issue by Silver360** [avocode/avocode#1939]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 247673
---
```
Error: EACCES: permission denied, open '/home/ren/.avocode/userdata/247673/project_thumbnails/76343d6f5d274c61bb1906d65f9ffad4-s=410x673-preview.webp'
```

**Comment by jakubzitny** [comment]
Hi @Silver360, thanks for the report. We are tracking a similar problem in #1926, so I will close this issue. However, do you have any details on this? I can see in our log that it happened more than once, when exactly was it? How did you install Avocode and which Linux distro do you have please?
