### ISSUE TITLE
Avocode 2.0 is buggy

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#194]
I can't select anything.

Windows: 8.1

http://recordit.co/P58GXdicGz

**Comment by petrbrzek** [comment]
We'll fix this asap.

**Comment by petrbrzek** [comment]
We cannot reproduce the problem. Does it happen in every design every time? 
Could you try to remove `.avcd` folder and let us know if that helped?

**Comment by polikin** [comment]
Where I can find the `.avcd` folder?

**Comment by petrbrzek** [comment]
It's in your user profile. You can run `rm -rf ~/.avcd` in terminal.

**Comment by polikin** [comment]
Sweet! Works, thanks! So, for every update we have to delete this folder?

**Comment by petrbrzek** [comment]
Good. We don't know why this happens (we cannot reproduce this problem). It's sad you must run this clunky command. We need to investigate this more.
