### ISSUE TITLE
could not download metadata

### ISSUE THREAD

**Issue by MonochromeDev** [avocode/avocode#1941]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 142186
---
```
Error: Could not download metadata (revision=21561403)
    at file:///C:/Users/%D0%91%D0%BE%D0%B3%D0%B4%D0%B0%D0%BD/AppData/Local/avocode/app-2.21.0/resources/app.asar/dist/avocode.min.js:1:1303374
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @MonochromeDev, thanks for the report. We can see the problem in our logging, we're looking into it and get back to you 😉

**Comment by jakubzitny** [comment]
Actually, this was caused due to our problems with rendering on our backend yesterday. Can you please try to re-upload the file? Everything should work again.
