### ISSUE TITLE
Images displays incorrectly in the Inspect Mode

### ISSUE THREAD

**Issue by angbermu-bold** [avocode/avocode#1945]
There is an issue with Avocode, on the web and in the app with the image rendering of sketch files, in the inspect mode they displayed stretched, while in the comment mode it shows correctly. Please take a look at the following screenshots:

Please take a look at this different
<img width="323" alt="screen shot 2018-03-22 at 5 26 08 pm" src="https://user-images.githubusercontent.com/37674254/37799467-24d4a4b8-2df6-11e8-83cf-10dd05cc453b.png">
<img width="317" alt="screen shot 2018-03-22 at 5 25 57 pm" src="https://user-images.githubusercontent.com/37674254/37799468-24e65ae6-2df6-11e8-8d63-622bfcb8dd2d.png">

---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 139220
---
```
No stack trace available
```

**Comment by connor-bean** [comment]
Hello - could you send us this original Sketch design to team@avocode.com?

Furthermore, I see you're running 2.21.0. Was this design also uploaded using this version or was it uploaded in an older version?

**Comment by angbermu-bold** [comment]
I have sent it to the mentioned email. Also, the designs team confirms this was uploaded it with the 2.21.0 version.

**Comment by jakubzitny** [comment]
Hi @angbermu-bold, this will be fixed in the next release of Avocode.

**Comment by jakubzitny** [comment]
Hi, this problem should be released in latest Avocode 2.22.0. Please update and let us know if it's still happening.
