### ISSUE TITLE
WebGL on desktop app?

### ISSUE THREAD

**Issue by Esteban-Rocha** [avocode/avocode#1946]
---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 297236
---
```
No stack trace available
```

Just started the trial to test some design workflow and see if I can go for a plan, the app is telling me that I do not have webGL enabled, and to enable it from the browser, thing is the app is running as a desktop app and in my chrome webGL is already enabled... for now it lets me work, "kind of" in a so called lite mode but.. well it sucks, i cannot test the app to it's fullest with this issue, any help will be much appreciated

**Comment by Esteban-Rocha** [comment]
Update: testing the app on chrome runs ok but on desktop nope, I do not want a browser app, it makes chrome heavier than it already is, I'll love if some help could be given as I'll want to test it as a desktop

**Comment by jakubzitny** [comment]
Hi thanks for the report. Yeah the desktop app might have problems with WebGL on some hardware. We keep improving our rendering performance and compliance with more and more hw, but for the time being I am afraid you'll need to use browser version for full support.
