### ISSUE TITLE
Could not load a psd file

### ISSUE THREAD

**Issue by GoTbraiN** [avocode/avocode#1949]
---
* **Version**: 2.19.2
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 128443
---
```
Error: Could not download metadata (revision=15053176)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1278805
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @GoTbraiN, thanks for reporting this problem. Did you try to re-upload the file and it failed to open repeatedly? Can you please send the PSD to team@avocode.com so we can inspect this further?

**Comment by jakubzitny** [comment]
Hi @GoTbraiN, thanks for reporting this problem. Did you try to re-upload the file and it failed to open repeatedly? Can you please send the PSD to team@avocode.com so we can inspect this further?

**Comment by GoTbraiN** [comment]
Hello,

I closed the program and opened it again and it worked. I didn’t have any
problem since then.

I can’t send the PSD to you because I don’t have approval from work.

Kind greeting,
George

-- 
George Safta

**Comment by jakubzitny** [comment]
Thanks for the info. Closing then. Let us know if you have any more problems 😉
