### ISSUE TITLE
block line-height is not counted to measure block height

### ISSUE THREAD

**Issue by prog666** [avocode/avocode#195]
Scetch knows about line-height included into block height, avocode shows that there's no padding over and under the text, ex: font-size is 18, line-height is 60, avocode shows that block is 18px height, not 60.

**Comment by prog666** [comment]
size 325px 13px
font-size 14px
line-height 18px
how is this possible?

**Comment by prog666** [comment]
now to count margin from top of text you have to count it that way:
amount of gap avocode says - (amount of lines * lineheight - block height) / 2

**Comment by petrbrzek** [comment]
Yep, we need to change it for Sketch. Now we calculate it differently for Photoshop.

**Comment by prog666** [comment]
![2015-05-08-134159_1918x1053_scrot](https://cloud.githubusercontent.com/assets/6894885/7534927/41589f6c-f588-11e4-922c-fa04d87d3d6e.png)

text has to be in the middle of the block

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by prog666** [comment]
i switched to back-end development already, but thanks anyway.
