### ISSUE TITLE
Important bug with sub-designs (symbols) links aren't reachable.

### ISSUE THREAD

**Issue by sergeybruh** [avocode/avocode#1950]
When I try to open symbol (sub-design file) I got this error 
http://joxi.net/DmBBdk7tN3YlMm
It happens on all links I can't open any sub-design via layers panel 

I guess it my be occurred by following reason:
The "symbols were renamed after they have been created".
In other words names of "symbols" in layers panel (http://joxi.net/LmGBRN7tRW1jer) are different with "symbols" in symbols folder
http://joxi.ru/eAO9yj5h4Olq6m

When I open that design in sketch app everything works file.

Also that bug exist at Avocode at other platforms :
web, linux, windows.

---
* **Version**: 2.21.0
* **Sketch plugin version**: 48.2.8
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 284440
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @sergeybruh, thanks for detailed report. Renaming the symbols in Avocode should not affect this. Where/when do you get this `symbols were renamed after they have been created` message, please? Also, are you sure the symbols are synced via the latest plugin version? Can you try to re-upload the sketch file again, to see if it's still happening?

**Comment by sergeybruh** [comment]
Where/when do you get this symbols were renamed after they have been created message, please? 
--When I do inspecting on the layers panel after double click and also on double click on design area.
No one of symbols used to work.

Also, are you sure the symbols are synced via the latest plugin version?
--I'm not sure about this. And unfortunately don't have opportunity to check it anymore.

 Can you try to re-upload the sketch file again, to see if it's still happening?
--My colleague re-uploaded and everything works fine.

**Comment by jakubzitny** [comment]
Good to hear that, we'll investigate why this might have happened. I will close this issue.
