### ISSUE TITLE
Stuck on "Downloading Metadata"

### ISSUE THREAD

**Issue by gyduxa** [avocode/avocode#1954]
Hello

I have a .PSD file that get's stuck on "Downloading Metadata". The other PSD files open fine.
I have Windows 8.1 and I'm using the desktop version of Avocode 2.21.0.
Screenshot attached.

I already tried to open it several times and it always gets stuck on the same position of the green loading bar.

![avocode-downloading-metadata](https://user-images.githubusercontent.com/5487711/38096441-ce2d8894-336a-11e8-9783-bf50511881a4.jpg)

Thank you

**Comment by bolekkerous** [comment]
Hey,
sorry for the late reply.

Would you be willing to send us an email with the problematic file to team@avocode.com so we can investigate the issue on our end?

And have you tried to reupload the design?

**Comment by gyduxa** [comment]
Reuploading the file like sugested by @bolekkerous worked.
I'm also running new version: 2.23.0.

Thank you
