### ISSUE TITLE
Unable  to open designs offline

### ISSUE THREAD

**Issue by i-v-k** [avocode/avocode#1955]
Guys, once again I was unable to open previously rendered designs offline.
Can you please fix it once and for all?

---
* **Version**: 2.21.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 112740
---
```
No stack trace available
```

**Comment by vojtatranta** [comment]
@i-v-k you are sure that you were trying to open design that was already opened before?

**Comment by i-v-k** [comment]
Yes, absolutely, I opened them yesterday.
Today I was offline and was unable to open them.
Maybe I can send you some logs? Does such a case make record in logs?

**Comment by i-v-k** [comment]
Well, I think I got an idea why this could happen.
I wasn't absolutely offline, I was connected to network but network encountered errors so I wasn't able to open any website. But I still wasn't completely offline in terms of network connection - I was connected, but to a buggy network. 
Maybe I needed to disconnect from that network for Avocode to start working in offline mode.
Do you understand what I mean and what do you think about it - could it be possible?

**Comment by jakubzitny** [comment]
Sorry @i-v-k about the late reply. Yes that could be possible. Did you try disconnecting completely and work in offline like that?

**Comment by i-v-k** [comment]
Yes, if I disconnect completely offline works as it should. I guess you can close this issue.

**Comment by jakubzitny** [comment]
Thanks a lot 🙂 

Don't hesitate to let us know if you have any more problems 😉
