### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by shawyou** [avocode/avocode#1958]
* **Version**: 2.16.3

* **Web/Desktop**: Desktop

* **Platform**: linux

* **Avocode UID**: 135031
---

```
Error: ETIMEDOUT
    at /home/linshaoyou/work/developerTool/Avocode/avocode-2.16.3-linux/resources/app.asar/node_modules/request/request.js:813:19
    at wrapped (/home/linshaoyou/work/developerTool/Avocode/avocode-2.16.3-linux/resources/app.asar/node_modules/raven-js/src/raven.js:314:29)
```

**Comment by jakubzitny** [comment]
Hi @shawyou, thanks for submitting this. We know about this problem already. However, we'd like to hear more details on this error from you, how often is this happening? When exactly?

I'm closing this with respect to #1677, but please do let us know the details.
