### ISSUE TITLE
Mac app open lite version, in Chrome browser open normal version

### ISSUE THREAD

**Issue by jroquejr** [avocode/avocode#1960]
Mac app open lite version, in Chrome browser open normal version.

I do changes to enable WebGL and reboot the SO, but this bug persists

**Comment by vojtatranta** [comment]
Hi,
well that's pretty strange. Desktop app is actually Chromium browser.

Would you try to download chromium and open that design in it?

**Comment by jakubzitny** [comment]
I think this might be happening, our desktop app can sometimes have problems with the rendering that Chrome does not have. Please use the browser version for now @jroqueweb.

**Comment by jroquejr** [comment]
I download and install chromium and now open correctly.
Thanks @vojtatranta and @jakubzitny
