### ISSUE TITLE
While trying to open a project

### ISSUE THREAD

**Issue by NadeemAyesh** [avocode/avocode#1967]
---
* **Version**: 2.22.1
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 245898
---
```
Error: EACCES: permission denied, open '/home/nadeem-ayesh/.avocode/userdata/245898/previews/ddf8f48408bc43489a5d85f078b8a9f2-preview.png'
```

**Comment by jakubzitny** [comment]
Hi @NadeemAyesh, thanks for the report. We are tracking a similar problem in #1926, so I will close this issue. However, do you have any details on this? When exactly did this happen? How did you install Avocode and which Linux distro do you have please?

**Comment by NadeemAyesh** [comment]
Hi, this issue happened when i am trying to open a project in my Avocode
accout, and I have a business account, and i have a linux ubuntu 16.4
platform.
Thank you.

**Comment by jakubzitny** [comment]
Does it happen only for a specific project or all the time? Did it work in the past or has it always been happening? Can you please try quitting the app, deleting `~/.avocode` and launch it and login again?

**Comment by NadeemAyesh** [comment]
thank you so much, "deleting ~/.avocode and launch it and login again"
solved my problem.
