### ISSUE TITLE
Problem with assets export

### ISSUE THREAD

**Issue by Pavel311** [avocode/avocode#1968]
---
* **Version**: 2.22.1
* **Web/Desktop**: Desktop and Web
* **Platform**: Windows 10
* **Avocode UID**: 71768
---

I tried to select and export multiple slices

![1](https://user-images.githubusercontent.com/12411987/38437520-5ac1ec2a-39e0-11e8-8109-41e1ae02a881.png)

In "Export assets" window there are no default variants. "Export" and "Add variant" buttons are inactive.

![2](https://user-images.githubusercontent.com/12411987/38437523-5f73801c-39e0-11e8-9835-f65c804c668e.png)

Export multiple layers selected using "Select" tool works fine.

**Comment by jakubzitny** [comment]
This should be fixed in latest version 2.23.0. Let us know if you have any more problems :wink:
