### ISSUE TITLE
Error always after hibernate computer and lost connection.

### ISSUE THREAD

**Issue by bogusweb** [avocode/avocode#1971]
Error always after hibernate computer and lost connection.

---
* **Version**: 2.22.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 282707
---
```
Error: getaddrinfo ENOENT manager.avocode.com:443
    at Object.exports._errnoException (util.js:1050:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by vojtatranta** [comment]
Hi @bogusweb ,
that's interesting. We have a check that says that this error should not pop up when app is offline, seems like this error is somehow "cached" in the app and pops app after app is already online.

We'll take a look at it

**Comment by jakubzitny** [comment]
Probably related to #1656.

**Comment by bogusweb** [comment]
After update to 2.23 version, this problem disappear ;)
