### ISSUE TITLE
Avocode process PSDs for ages. I can't inspect any of mockup

### ISSUE THREAD

**Issue by sergeybruh** [avocode/avocode#1972]
Avocode process PSDs for ages. I can't inspect any of mockup

---
* **Version**: 2.22.1
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 284440
---
```
No stack trace available
```

**Comment by sergeybruh** [comment]
http://joxi.ru/8Ank8y3Uq3eyXr

**Comment by jakubzitny** [comment]
Hi @sergeybruh, do you still have problems with PSD processing in Avocode, please?

**Comment by jakubzitny** [comment]
This should be improved a lot in latest versions of Avocode, please update and let us know if you still have similar problems 😉
