### ISSUE TITLE
Invisible elements in Podskazka folder

### ISSUE THREAD

**Issue by lexantus** [avocode/avocode#1973]
---
* **Version**: 2.22.0
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 277149
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @lexantus, this should be fixed in latest versions of Avocode, please update and let us know if you have any similar problems 😉
