### ISSUE TITLE
Avocode web interface Chrome, linux

### ISSUE THREAD

**Issue by electrovladyslav** [avocode/avocode#1974]
---
* **Version**: 2.23.0-web
* **Web/Desktop**: Web
* **Platform**: linux -1
* **Browser**: chrome 65.0.3325.146
* **Avocode UID**: 302746
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new _ (https://cdn.app.avocode.com/dist/v-44b3c22/js/avocode-web.min.js:28:505374)
    at Rendering (https://cdn.app.avocode.com/dist/v-44b3c22/js/2.avocode-web.min.js:1:81831)
    at https://cdn.app.avocode.com/dist/v-44b3c22/js/avocode-web.min.js:65:21921
    at new Promise (<anonymous>)
    at https://cdn.app.avocode.com/dist/v-44b3c22/js/avocode-web.min.js:65:21481
```

**Comment by jakubzitny** [comment]
Hi @shiwamavg, thanks for the report. We're already tracking this in #1867 so I am going to close this.

Is this happening to all designs you're trying to open and all the time?

The thing is that our new rendering consumes a bit more memory for designs. We'll be releasing more optimized rendering in the next Avocode version. However, if you do not have a lot of memory, you'll need to have less designs open at the same time.
