### ISSUE TITLE
EPERM on Windows

### ISSUE THREAD

**Issue by mentoripro** [avocode/avocode#1977]
---
* **Version**: 2.23.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 309477
---
```
Error: EPERM: operation not permitted, open 'C:\Users\Админ\.avocode\userdata\309477\documents\e39e57e6ffe746308e49e345496d5540\images\http-cloudfront.designs.avocode.com-2018-4-f8cb4e3f00fc45e3aee37890194d738d-11982.png'
```

**Comment by jakubzitny** [comment]
Hi @Kuzhimov, thanks for reporting this. Can you try quitting the app, removing `C:\Users\Админ\.avocode` folder and try again, please?

We're tracking a similar problem in #1926, so I will close this issue.
