### ISSUE TITLE
sketch plugin crashes sketch when syncing some of designs

### ISSUE THREAD

**Issue by prog666** [avocode/avocode#198]
some of them are ok, some always crash

**Comment by zonov** [comment]
Confirm. We have the same problems.

**Comment by tomashanacek** [comment]
Hi, thank you for reporting the issue. Could you share us the problematic design to team[at]avocode.com?

**Comment by zonov** [comment]
Sure. I have send it right now.

**Comment by prog666** [comment]
I did ask our designer to send it

**Comment by rychlis** [comment]
We've released sketch extension 2.0.2 which should fix the issue, feel free to re-open if you still have the problem

**Comment by prog666** [comment]
thx, will try now
