### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by AllenVork** [avocode/avocode#1982]
---
* **Version**: 2.23.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 135031
---
```
Error: EPERM: operation not permitted, open 'C:\Users\zhangruofan\.avocode\userdata\135031\documents\8b97818c90d743bbb5ed4b30f27c97e7\images\http-sketch.designs.avocode.com-3d3b9085b52c4664adb94611b8d8f070-cbdca56a20ee1a1c6724df2cdf9c867a2f22287b.png'
```

**Comment by jakubzitny** [comment]
Hi @AllenVork, thanks for reporting this. Can you try quitting the app, removing C:\Users\ zhangruofan\.avocode folder and try again, please?

We're tracking a similar problem in #1926, so I will close this issue.
