### ISSUE TITLE
Different color code between Sketch and Avocode 

### ISSUE THREAD

**Issue by mahish** [avocode/avocode#1984]
* **Version**:  2.24.0

* **Sketch version**: 49.3.0 (the file uploaded via drag&drop)

* **Web/Desktop**: both

* **Platform/Browser**: MacOS 10.13.4, Firefox 59.0.2, Chrome 65.0.3325.181

* **Avocode e-mail**: jiri.maha@avast.com

So we are having color code issue with Sketch files. I have set the Sketch document to use sRGB profile. However Im still getting (slightly) different color codes in Avocode from those I have in my Sketch. The most anoying thing about is that it makes the variable feature useless. (2.24.0 as well as 2.23.0)

* from `#3385CC` to `#3284cc`
* from `#F5A623` to `#f5a523`

<img width="486" alt="image" src="https://user-images.githubusercontent.com/3687943/38931035-27fa51b6-4312-11e8-9367-d180a2de36e5.png">
<img width="733" alt="image" src="https://user-images.githubusercontent.com/3687943/38931048-33c5b0e4-4312-11e8-8ef9-b0477dca6fdd.png">

You can download the test Sketch file here: https://www.dropbox.com/s/ncksy54wc2pwzdb/color-profile-3.sketch?dl=0

**Comment by jakubzitny** [comment]
Thanks a lot for the details @mahish, we'll have one more look at this.

**Comment by jakubzitny** [comment]
Allright, so we've found a possible improvement for color profiles on our backend. We hope to have this fixed soon 😉

**Comment by jakubzitny** [comment]
Hi @mahish, this should be fixed in latest update. Let us know if you still have problems with it 🙂
