### ISSUE TITLE
I tried sync XD update several times. It's not working.

### ISSUE THREAD

**Issue by JakeMars** [avocode/avocode#1986]
---
* **Version**: 2.24.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 316067
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @JakeMars, thanks for letting us know. Can you be more specific please? What is not working? The app does not accept `.xd.` file to upload? Or you upload it successfully and you have problems with opening?

I can see in our backend that most of your designs are deleted, but all of them have been successfully processed. That would suggest that you have problems with opening them, right? Did you try our web version at https://app.avocode.com to see if you get a better experience? OR can you record a video of what exactly is happening to you so we can help you get it working?

**Comment by JakeMars** [comment]
Hi @jakubzitny, thank you for the quick reply! 

Pardon me for this post, it seems I misunderstood syncing XD when it's saved in Avocode app/webapp.

I tried it again, works perfect!
Sync - app to webapp
Update version - XD file (re-upload)

Thanks!

**Comment by jakubzitny** [comment]
Glad to hear that, so we can close this right? 🙂 

Do not hesitate to let us know if you have any more issues or something is not clear 😉
