### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xuyangqiao** [avocode/avocode#1987]
---
* **Version**: 2.24.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 315569
---
```
Error: EPERM: operation not permitted, open 'C:\Users\28308\.avocode\userdata\315569\documents\d0369ee8db314ea8b2350b1365888f74\images\http-cloudfront.designs.avocode.com-2018-4-7aa79c0b74f04d76925a2f09099734fa-1080.png'
```

**Comment by jakubzitny** [comment]
Hi @xuyangqiao, thanks for reporting this. Can you try quitting the app, removing C:\Users\ 28308\.avocode folder and try again, please?

We're tracking a similar problem in #1926, so I will close this issue.
