### ISSUE TITLE
sometimes i need to export images to different folders

### ISSUE THREAD

**Issue by prog666** [avocode/avocode#199]
how can i choose export folder for different files?

**Comment by petrbrzek** [comment]
It's possible but not very user friendly. Go to settings, choose your project and change the export path.  
![avocode_-_2_0_0](https://cloud.githubusercontent.com/assets/879564/7179871/85cd5762-e43c-11e4-88da-5e2aea9ada9e.png)

## Suggested improvements

- Add `CMD+SHIFT+S` shortcut to invoke the Save As dialog...
- Add option to settings "Open Save As Dialog when Savings"

What do you think @prog666?

**Comment by prog666** [comment]
it'd be simpler if when you hit quick export it would let you modify the path, and if you dont it exports the same way it did

**Comment by PavelGavlik** [comment]
2.1.0 will have new File > Export As... (Cmd+Shift+S) feature which lets you set export path regardless of project's default export path. Does this solve your problem?

**Comment by prog666** [comment]
yes, thanks a lot!
