### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by geenino** [avocode/avocode#1991]
---
* **Version**: 2.24.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 183871
---
```
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1120:19)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by jakubzitny** [comment]
Hi @geenino, do you have any details on this, please? Is it happening often or just this one time?

**Comment by geenino** [comment]
Hi,
Sorry for late reply. yes, most of the time on few projects on avocode. but i dont know why this is happen.

**Comment by connor-bean** [comment]
Hey can you elaborate on this? What were you doing when this happened? 

Are you using a VPN by chance? Or do you have any restrictive firewalls/proxies? 

Any additional information you could provide would help us troubleshoot as we are currently unable to reproduce this problem.

**Comment by geenino** [comment]
Hi,
i was try to open files on avocode desktop app on mac. its stop on 90% then this error came.
I dont use vpn. i dont have any special firewall. usual highserria 10.13.4 protection.

This problem came only some project when we try to open. if we open other projects are ok. but our designer say, same kind sketch file they upload for all projects. we also dont know, what is the difference.

I cant replicate the same error now. sorry.
Thank you

**Comment by connor-bean** [comment]
Thanks for the additional information.

Would it be possible to send us one of these Sketch files (the actual design) that you opened and this error happened?

If so, can you send it to team@avocode.com and mention this Github ticket in the message?

Or, if you can't send us the design, can you let us know the name of the design and the name of the project the design is in?

**Comment by geenino** [comment]
HI, 
sorry, I cant send design. I will give the details. project name Mofami. Design name 08.1.Mo fami_MESSAGERIE-Connecté.

Thank you.

**Comment by connor-bean** [comment]
We just successfully uploaded this design on our end and did not have any errors. We tried both the plugin (latest Sketch app and latest Avocode app) as well as the web app drag and drop method. Both succeeded just fine.

However, we will be releasing v3.0 very soon which will include some improvements to the upload process. Once we release 3.0, please update to that version and try uploading the design again.

Please let us know of any other questions!

**Comment by geenino** [comment]
Thnak you so much
