### ISSUE TITLE
not downloading

### ISSUE THREAD

**Issue by whoiskjl** [avocode/avocode#1994]
---
* **Version**: 2.24.0
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 28374
---
```
Error: Could not download metadata (revision=21344808)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1625300
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @whoiskjl , how often do you have this problem please? Did you try re-uploading the file? Uploading it only by drag&dropping the file over Avocode app could be better. I just tried uploading it like that and opening and everything seems to be working. Please let me know if it works for you.

**Comment by whoiskjl** [comment]
I haven't been having this issue. Currently I can't replicate

**Comment by jakubzitny** [comment]
Thanks, I'll close this issue then. Let us know if you have any more problems 😉
