### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by teremok1000** [avocode/avocode#1995]
I will have huge problems if you do not decide as soon as possible !!!!

video http://dl4.joxi.net/drive/2018/04/23/0000/0909/29581/81/972929e738.mov

**Comment by jakubzitny** [comment]
Hi @teremok1000, I checked these designs on our backend and they seem to be processed normally so I have a feeling there might be a problem when the app is downloading the assets.

Can you please try our web version at [app.avocode.com](http://app.avocode.com) to see if that works for you?

**Comment by teremok1000** [comment]
Hi! Yes it was loaded, but I can not work there! I necessarily need a dextop version !!!!! Can you solve the problem right now?

**Comment by teremok1000** [comment]
I will lose my job if you do not solve the problem! This is very serious for me!

**Comment by jakubzitny** [comment]
Glad to hear the web works. I am afraid this will not be easy to solve _right now_.

What's the matter with using the web if the task you're doing is so urgent? Our web version should currently be almost identical to our desktop version, is there anything specific you are miss on the web?

**Comment by teremok1000** [comment]
I've added a bunch of applescript scripts for avocode that speed up my work, now nothing will work

**Comment by jakubzitny** [comment]
I see. Would you mind sharing them to us, so we can see if there is another way to speed up whatever you need to do? You can share it to jakubzitny@avocode.com if you want it privately.

**Comment by teremok1000** [comment]
no, unfortunately I can not share them, they were written to order to fix some flaws in the program and speed up my work, I will work through the web version and very much hope that soon you will correct everything, thank you in advance very much forward

**Comment by vojtatranta** [comment]
@teremok1000 could you send us at least a private link to that design? Thanks

**Comment by jakubzitny** [comment]
We've got it actually..

Next week we're planning to release a major 3.0 version of Avocode with improved design loading. I believe this problem should be fixed there, however, we'll look into it a bit more.

**Comment by teremok1000** [comment]
thank!

**Comment by vojtatranta** [comment]
@teremok1000 nevermind, I got it.

It seems OK to us, we reimported it and it looks ok. Have you tried to reimport this file?

**Comment by teremok1000** [comment]
yes, reimport 3 times and error

**Comment by teremok1000** [comment]
and old files that have already been imported adobexd also now do not open

**Comment by jakubzitny** [comment]
What's the status of this problem @teremok1000, please? We've recently released some improvements/fixes regarding design opening and rendering. Is this issue still occuring?

**Comment by teremok1000** [comment]
no all ok!

**Comment by jakubzitny** [comment]
Thanks for the info, closing then.
