### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xuyangqiao** [avocode/avocode#1997]
---
* **Version**: 2.24.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 129478
---
```
Error: EPERM: operation not permitted, open 'C:\Users\28308\.avocode\userdata\129478\documents\77889ff4bf4d4c7b9e65c39baf89fa1f\images\http-sketch.designs.avocode.com-3330dce8d1f745fb9edd49560ab43064-dc064c4b18ad7f5c539db7265591bfb96be5a524.png'
```

**Comment by jakubzitny** [comment]
Hi @xuyangqiao, thanks for reporting this. Can you try quitting the app, removing C:\Users\ 28308\.avocode folder and try again, please?

We're tracking a similar problem in #1926, so I will close this issue.
