### ISSUE TITLE
Blend mode

### ISSUE THREAD

**Issue by Rad1calDreamer** [avocode/avocode#200]
Did it support blend mode?
disign in Photoshop
![_ 2](https://cloud.githubusercontent.com/assets/7055577/7085812/27b5d158-df83-11e4-9f8f-5ba2f0aa6e82.jpg)
and in avocode
![_](https://cloud.githubusercontent.com/assets/7055577/7085817/2d837702-df83-11e4-8ff7-29efbda991ad.png)

**Comment by petrbrzek** [comment]
Yes, Avocode supports blending modes. Can you send me that design to petr@avocode.com? I'll look into it and let you know what's wrong.

**Comment by Rad1calDreamer** [comment]
sent

**Comment by petrbrzek** [comment]
Ok I checked your design and the problem is gradient masks. We cannot interpret it yet. 

![screen shot 2015-04-16 at 23 59 19](https://cloud.githubusercontent.com/assets/879564/7192376/1944057e-e495-11e4-91a6-05590934701f.png)

**Comment by Rad1calDreamer** [comment]
ok.
