### ISSUE TITLE
Donwload timeout

### ISSUE THREAD

**Issue by hxss** [avocode/avocode#2001]
I'm trying to download design pages but receives errors or timeouts at every second page.

---
* **Version**: 2.24.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 312611
---
```
Error: The request timed out
    at file:///opt/avocode/resources/app.asar/dist/avocode.min.js:1:2624180
    at wrapped (/opt/avocode/resources/app.asar/node_modules/raven-js/src/raven.js:360:21)
```

**Comment by jakubzitny** [comment]
Hi @hxss, thanks for submitting this, we're aware of it already from #1781. Do you have any more info you can provide? Is it happening a lot or just once?
