### ISSUE TITLE
Designer guides disappear

### ISSUE THREAD

**Issue by bogusweb** [avocode/avocode#2005]
* **Version**: Last version

* **Web/Desktop**: Desktop and Web

* **Platform/Browser**: Linux and chrome

Guides disapear and dont work if u changing mode to inspect->comment->inspect.

Bug track:
1. Open PSD file in inspect mode
2. Turn on guides
3. Switch to comment mode
4. Switch to inspect mode
5. Pouf, guides disappear

**Comment by vojtatranta** [comment]
hi @bogusweb ,
I just trie to reproduce it, but no luck.

It seems it works already.

**Comment by jankuca** [comment]
Oh, I was fixing this about a month ago. The bug fix should be included in the last couple of releases.

**Comment by bogusweb** [comment]
@jankuca bug doesnt exist in 3.2.0 version :)!
