### ISSUE TITLE
Problem to upload sketch to avocode

### ISSUE THREAD

**Issue by rihbim** [avocode/avocode#2006]
---
* **Version**: 2.22.1
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 207654
---
```
Error: ENOSPC: no space left on device, write
```

**Comment by bolekkerous** [comment]
Hey, @rihbim -
from the error description it looks like you don't have enough space on your hard drive, could you please check whether you have enough space and reupload again after that?

**Comment by rihbim** [comment]
yes, it was not enough space on my drive

thanks for answer

2018-04-27 18:02 GMT+03:00 Bolek <notifications@github.com>:
