### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Tarik-Fanarik** [avocode/avocode#2008]
---
* **Version**: 2.24.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 223459
---
```
TypeError: (r || []).map is not a function
    at file:///C:/Users/andru/AppData/Local/avocode/app-2.24.0/resources/app.asar/dist/avocode.min.js:1:3559274
    at file:///C:/Users/andru/AppData/Local/avocode/app-2.24.0/resources/app.asar/dist/avocode.min.js:1:2421100
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @Tarik-Fanarik, thanks for reporting this. We're working on a fix and we're tracking the same problem in #2007 so I'll close this thread.
