### ISSUE TITLE
Popup error while using

### ISSUE THREAD

**Issue by dalik** [avocode/avocode#2009]
Just happened in background while using avocode. 

---
* **Version**: 2.24.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 315574
---
```
TypeError: (r || []).map is not a function
    at file:///C:/Users/dalibor.slavik/AppData/Local/avocode/app-2.24.0/resources/app.asar/dist/avocode.min.js:1:3559274
    at file:///C:/Users/dalibor.slavik/AppData/Local/avocode/app-2.24.0/resources/app.asar/dist/avocode.min.js:1:2421100
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @dalik, thanks for reporting this. We're working on a fix and we're tracking the same problem in #2007 so I'll close this thread.
