### ISSUE TITLE
Avocode not updating current Sync on App

### ISSUE THREAD

**Issue by nckjrvs** [avocode/avocode#201]
I've synced some new changes, and the app does not want to sync with the new design.

**Comment by petrbrzek** [comment]
That's weird. Did you try to Sync changes manually?
![avocode_-_2_0_0_and_avocode_not_updating_current_sync_on_app_ _issue__201_ _avocode_avocode](https://cloud.githubusercontent.com/assets/879564/7179663/8318d4c6-e43a-11e4-81ac-d8131fa6d282.png)

**Comment by stevebrown** [comment]
@nckjrvs @petrbrzek 
I'm seeing a similar issue with Avocode 2.0.0 where the sync spinners just keep spinning and there is no progress. This seems to happen to designs that are updated more often than new designs that are just synced for the first time.

See the screen cast to see what I'm seeing. http://quick.as/XGBwcp0R0

**Comment by petrbrzek** [comment]
Please try it with the new version 2.1.0 and let us know.

Reopen, if the problem still occurs.
