### ISSUE TITLE
Rounded rectangle from Xd format without border-radius property

### ISSUE THREAD

**Issue by Q-ian** [avocode/avocode#2013]
* **Version**: 2.25.2

* **Web/Desktop**: web

* **Platform/Browser**: Browser

 qianyi397@gmail.com

Hello, I`ve uploaded several Xd files to the web version. All of the rounded rectangles seems to be all right, but without border-radius property in the styles panel....  fix it, please

**Comment by petrbrzek** [comment]
Hi @Q-ian, this issue is going to be fixed in the next release.

**Comment by jakubzitny** [comment]
Hi @Q-ian, this problem should be fixed in latest Avocode 2.26.0, please update and let us know if you have any more problems 😉
