### ISSUE TITLE
Syncing hidden layers/groups in Sketch

### ISSUE THREAD

**Issue by n0rule5** [avocode/avocode#2015]
When syncing any Sketch design with hidden layers/groups, making that group visible in Avocode shows the text layers skewed (looks vertically stretched). The problem appears on both desktop and web app.

---
* **Version**: 2.25.2
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 35475
---
```
No stack trace available
```

**Comment by bolekkerous** [comment]
Hey, @n0rule5 -
would you be able to send us any example design with such problematic behavior to team@avocode.com please?

Thanks!

**Comment by jakubzitny** [comment]
Hi @n0rule5, this is a known issue that we're addressing right now. When you upload the Sketch file by Drag&Dropping them over Avocode (instead of syncing via plugin) everything should be OK. We're fixing it just now for the plugin as well and it'll be part of our 3.0 release next week (hopefully).

**Comment by n0rule5** [comment]
Thanks. I'll wait for the fix in the plugin as dragging and dropping the file will create a new "instance" of it. I have many links in specs to different designs and I'd rather not have to update every link manually. 😄

**Comment by jakubzitny** [comment]
You can drag+drop on top of Sketch group in Avocode. Or if you want to update only a few / one specific artboard, you can cmd+x and cmd+v the artboard to a new Sketch file and drag+drop it over the Sketch group in Avocode. Artboards with same name should be updated as new revisions. Do that as a temporary solution if you need. Plugin fix is on its way 😉

**Comment by n0rule5** [comment]
Oic, thanks for the tips!

**Comment by jakubzitny** [comment]
This should be fixed in our latest release Avocode 3.0, please update 😉
