### ISSUE TITLE
Custom image fill missing

### ISSUE THREAD

**Issue by n0rule5** [avocode/avocode#2019]
Shapes with a custom image fill don't sync over and become blank/transparent.

---
* **Version**: 2.26.0
* **Sketch plugin version**: 49.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 35475
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @n0rule5, thanks for reporting this. This is a problem with designs from Sketch v50. We're preparing a fixed version that will be released early next week and should address all similar problems.

**Comment by jakubzitny** [comment]
Hi, we've just released Avocode 2.26.1, problems related to Sketch v50 should be fixed. Please update and let us know if you have any more problems 😉
