### ISSUE TITLE
"2 years trial remaining" on avocode 2

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#202]
https://www.dropbox.com/s/8jflqy5ak2u2yd2/Screenshot%202015-04-14%2014.35.40.png?dl=0

**Comment by VPenkov** [comment]
Yeah, it's not really a trial if you've paid for it. Maybe it should say "X days remaining" if X is less than a month.

**Comment by petrbrzek** [comment]
That's bug, we'll fix it in the next release. (next week)

**Comment by rychlis** [comment]
We've been able to fix this on server-side so it should no longer appear
