### ISSUE TITLE
Application crash requires sync on all projects

### ISSUE THREAD

**Issue by mexdevs** [avocode/avocode#203]
I have had several instances now where the application will crash and when I re-open it all projects need to be synched again. This means all my local changes are lost. Should those not be persisted even if application crashes?

**Comment by petrbrzek** [comment]
Definitely bug. I have to discuss this with @tomashanacek.

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
