### ISSUE TITLE
keep crashing

### ISSUE THREAD

**Issue by yaronshlomo** [avocode/avocode#2032]
---
* **Version**: 2.26.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 276607
---
```
Error: EACCES: permission denied, open '/home/yarons/.avocode/userdata/276607/previews/b6aa69a1fb9a43e9875a0023a4de6850-9cb127bb-3aee-4a6f-af34-a619c7a5003e-preview.png'
```

**Comment by yaronshlomo** [comment]
crashing all the time

**Comment by jakubzitny** [comment]
Hi @yaronshlomo, thanks for reporting this. We're aware this is happening sometimes, we're tracking the problem in #1926.

The following should help:
- quit Avocode
- delete `~/.avocode` directory
- open Avocode and login again..

Please let me know if it helped.
