### ISSUE TITLE
 Copy to clipboard

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#2033]
Hello! Make a copy of the layout name in the clipboard http://www.lavuix.ru/scr/2018-05-21_11-10-22.png. Inside it is realized

**Comment by jakubzitny** [comment]
Hi @Webdesme, thanks for suggestion. We'll add this to Avocode 3.0, which is currently set to be released next week 😉

**Comment by Webdesme** [comment]
it's cool) thanks

**Comment by vojtatranta** [comment]
This was added in `3.0.0`
