### ISSUE TITLE
fgghgfhgh

### ISSUE THREAD

**Issue by ivanostapiuk** [avocode/avocode#2040]
---
* **Version**: 2.26.4
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 338600
---
```
Error: EACCES: permission denied, open '/home/ivan/.avocode/userdata/338600/thumbnails/5adc004af24e48fd8e5539365cda8dcc-s=260x364-preview.webp'
```

**Comment by jakubzitny** [comment]
Hi @vanya2906, thanks for reporting this. We're aware this is happening sometimes, we're tracking the problem in #1926 already.

The following should help:
- quit Avocode
- delete `~/.avocode` directory
- open Avocode and login again..

Please let me know if it helps.
