### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by lastkindness** [avocode/avocode#2046]
---
* **Version**: 2.17.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 344748
---
```
Error: 140243905630784:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:../../vendor/node/deps/openssl/openssl/ssl/s3_pkt.c:535:

```

**Comment by connor-bean** [comment]
Hey @lastkindness it looks like you're running an old version of Avocode. Can you update to our most recent version and try again?

If you cannot auto-update in the app, you can download it from www.avocode.com/download.

Please let us know if you still receive this error after updating your app.
