### ISSUE TITLE
Error: Could not download metadata

### ISSUE THREAD

**Issue by nanastya** [avocode/avocode#2048]
---
* **Version**: 2.17.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 171942
---
```
Error: Could not download metadata (revision=24749967)
    at file:///C:/Users/Odessa/AppData/Local/avocode/app-2.17.2/resources/app.asar/dist/avocode.min.js:1:1129304
    at <anonymous>
```

**Comment by connor-bean** [comment]
Hey @nanastya 

Thanks for the report. Can you update your app to our latest version? 2.17.2 is quite old.

If you cannot use the automatic update feature in the app, you can download the newest version from here: www.avocode.com/download

Please let us know if you receive this error again once you're running our latest version.
