### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by anjan-raji** [avocode/avocode#2049]
---
* **Version**: 2.26.4
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 68767
---
```
TypeError: n._mouseupCancellers.get(...) is not a function
    at r (file:///C:/Users/RWS-ANJAN/AppData/Local/avocode/app-2.26.4/resources/app.asar/dist/avocode.min.js:1:3112385)
    at wrapped (C:\Users\RWS-ANJAN\AppData\Local\avocode\app-2.26.4\resources\app.asar\node_modules\raven-js\src\raven.js:360:21)
```

**Comment by vojtatranta** [comment]
Hi @anjan-raji ,
this seems like a bug, however we have not encountered it.

Can you reproduce it?

**Comment by jakubzitny** [comment]
I expected this to be already fixed in latest release (#1774). It is clearly happening and should not be. Can you please provide more info, where/how did this happen and how often do you see it?

**Comment by jakubzitny** [comment]
This should (really) be fixed in latest release of Avocode, please re-open if it occurs again.

**Comment by anjan-raji** [comment]
Thank you 👍
