### ISSUE TITLE
Message that Avocode has gone bad on login to 2.0.0 app

### ISSUE THREAD

**Issue by stevebrown** [avocode/avocode#205]
I've been having trouble with Avocode 2.0.0 for the last few days. I have been having sync issues where projects will not update in the Avocode app.  In trying to fix this, I removed the Avocode app (using App Zapper). The app, prefs, application support folder and cache were removed. I reinstalled the app. I launched the app and the app remembered my credentials and the projects were still having sync issues. I thought that by logging out and logging back in I could possibly fix the issue. When logging in with my credentials, I receive the message that "Your Avocode has gone bad. An unexpected error occurred. Click here to report this issue."

At this point, I was stuck at the login screen. I closed the app, and reopened. When the app opened, I was logged in with my credentials but the same syncing problem was present where trying to sync design displayed the indeterminate progress bar or the indeterminate progress spinner. 

At this point, Avocode is basically useless since designs won't update.

**Comment by petrbrzek** [comment]
Thanks a lot for putting your effort into bug reporting. 
There is an ugly way to reset Avocode to default state. 

1. Close Avocode app
2. Go to the terminal
3. Run `rm -rf ~/.avcd` 
4. Launch again Avocode app

Let me know if that helps.

**Comment by stevebrown** [comment]
Thanks, Petr,  This seems to have removed the endless sync condition.  Will this command work on Windows and Linux too?  I have 4 other developers will the same issue and one is on Linux and the other Windows.

**Comment by petrbrzek** [comment]
It works on Linux but not on Windows. On Windows you have to go to your user profile and delete `.avcd` folder manually.
