### ISSUE TITLE
The Korean font is shown as question marks.

### ISSUE THREAD

**Issue by syoki** [avocode/avocode#2050]
like this; 
> font-family: ??????;

It did not happen in previous versions.

---
* **Version**: 3.0.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 21407
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @syoki, thanks for the report. I can see the problem in your designs, we're investigating the issue with our backend and we'll get back with more info. For now you can use the postscript name from the styles panel.

**Comment by jakubzitny** [comment]
There is a problem with us parsing the missing fonts you uploaded. For `NanumBarunGothic` we incorrectly parsed `??????` name. We'll try to fix this as soon as possible.

**Comment by jakubzitny** [comment]
Closing with respect to #2053.
