### ISSUE TITLE
Problems with korean texts

### ISSUE THREAD

**Issue by sun-runners** [avocode/avocode#2053]
It did not happen in previous version.

We cannot wait too much...

Please update...

email: ceo@idist.ai

You can see my project.

Current Avocode (Bad)

<img width="647" alt="2018-06-14 9 43 40" src="https://user-images.githubusercontent.com/8358038/41412785-0b6196f4-701c-11e8-9f57-3514602d84c9.png">

Previous Avocode (Good)

<img width="789" alt="2018-06-14 9 44 52" src="https://user-images.githubusercontent.com/8358038/41412835-36c36c28-701c-11e8-93a9-d12c55082e86.png">

**Comment by bolekkerous** [comment]
Hello @KimSunWook -
if a font is missing, there should be a warning in the layer panel (and a notification when you open the design) that the fonts are missing and that you would need to add them in order for the design to be rendered correctly.

This is how the notification looks:

<img width="257" alt="screenshot 2018-06-14 15 39 40" src="https://user-images.githubusercontent.com/16084852/41415574-2cc86e9a-6fe9-11e8-9d06-632b9d4557a8.png">


After you upload the font (ttf or otf) into Avocode, you'll get a notification that the design was rerendered with the fonts added. Also these fonts will be saved for your team so you don't need to upload them for another design again.

**Comment by bolekkerous** [comment]
However if you still have any problems with the design after you upload the fonts (perhaps if they are not displayed correctly or it still asks you to upload the fonts again even after you get the notification that the design was re-rendered), please let us know and we'll investigate further.

**Comment by sun-runners** [comment]
it is not working still now....

**Comment by sun-runners** [comment]
Why this is not working since new update??

Jeplin is working well as previous version of avocode.

Why korean text is breaking??

**Comment by sun-runners** [comment]
I also upload korean font but not working.

Did you test with korean text???

**Comment by bolekkerous** [comment]
Hey @KimSunWook -
this problem should now be resolved, just try to reupload the design and it should work correctly.

Unfortunately the font naming conventions do not always work correctly with Korean fonts, so if you stumble upon any similar issue in the future, first try to upload the fonts into Avocode (.ttf or .otf), and if that does not work, contact us so we can investigate what exactly is the issue and fix it.
