### ISSUE TITLE
Out of memory at ImageData creation

### ISSUE THREAD

**Issue by jonytrees** [avocode/avocode#2054]
---
* **Version**: 3.0.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 344112
---
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at injectDataToMemory (C:\Users\e.yanushkevich\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\@avocode\stage\dist\utils\rendering.js:1:5431)
    at Object.injectBitmapAsync (C:\Users\e.yanushkevich\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\@avocode\stage\dist\utils\rendering.js:1:5279)
    at C:\Users\e.yanushkevich\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\@avocode\stage\dist\artboards\artboard.js:1:2930
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @jonytrees, thanks for reporting this 😉 

I can see that you uploaded several files over the last few days and I am not sure which one do you have a problem with. If you open very large designs on a computer with not enough memory, you can see this particular error, especially on Windows. We're already tracking the same problem it in #1567.

I tried uploading your last file and everything works correctly. Is it happening only for one file or often?Can you specify your hardware resources, please?

**Comment by jakubzitny** [comment]
Hi @jonytrees, thanks again for reporting this 😉

I can see that you uploaded several files over the last few days and I am not sure which one do you have a problem with. If you open very large designs on a computer with not enough memory, you can see this particular error, especially on Windows. We're already tracking the same problem it in #1567.

I tried uploading your last file and everything works correctly. Is it happening only for one file or often?Can you specify your hardware resources, please?

**Comment by jakubzitny** [comment]
Closing with respect to #1567.
