### ISSUE TITLE
All text is offset +1xy (pixels) when imported from Adobe XD

### ISSUE THREAD

**Issue by nuggettyone** [avocode/avocode#2057]
![avocode___text_offset_issues](https://user-images.githubusercontent.com/31147118/41513592-261d54ba-72e2-11e8-9597-67ee3be16371.gif)

* **Version**: 3.0.0 Windows

* **Web/Desktop**: Desktop

* **Platform/Browser**: Windows 10 Pro, Version 1709, OS Build 16299.492

* **Description**
All text is offset by +1xy (pixels) when imported from Adobe XD (Windows, Version 8.0.22.11, Creative Cloud Sync 3.0.3.6).

* **Steps to reproduce**
1. In Avocode Project manager, double-click on the project in All Projects tab
2. In Project designs tab, double-click on the design file
3. In All designs, double-click on any design with text

* **Expected result**
Text position should be accurate in Avocode - that is, it should match what's shown in Adobe XD.

* **Actual result**
Text position is offset by +1xy (in pixels). 

Obviously I can't precisely position Avocode's Pixel Checker for a perfect alignment. But the animated GIF should show the text offset pretty clearly. Additionally, I have offset (in Adobe XD), the text "Not watched" "Start date", and "1 Nov 2017" by -1xy in order to get them to look alright in Avocode.  Not exactly an ideal solution. ;)

**Comment by jakubzitny** [comment]
Hi @nuggettyone, thanks a lot for precise report. We'll look into this and get back to you.

**Comment by bolekkerous** [comment]
Hey @nuggettyone ,
just wanted to let you know that this problem should be fixed now. Please reupload the problematic design itself (or just upload it as a new version) and it should be displayed correctly. :)
​
Hope everything works now!
