### ISSUE TITLE
Artboard cut off on preview

### ISSUE THREAD

**Issue by igormorozov** [avocode/avocode#2064]
It will be great if I can see full artboard preview on thumbnail page. Right now for example if my artboard has wide width I can see only right side of artboard. 

Preview: https://cl.ly/0f130J2E3W2y
Full view: https://cl.ly/1Z3O1E3t1x0T

---
* **Version**: 3.0.0
* **Sketch plugin version**: 50.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 316360
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @igormorozov, thanks for suggesting this. We will think about changing the behaviour, however, it would also mean drawbacks in other cases.

You can use a `space` key to display a "quick-look" preview of a design without the need to open it. Do you know about it? Would that help in your case?

**Comment by jakubzitny** [comment]
Hi @igormorozov, thanks for suggesting this. We will think about changing the behaviour, however, it would also mean drawbacks in other cases.

You can use a space key to display a "quick-look" preview of a design without the need to open it. Do you know about it? Would that help in your case?

**Comment by jakubzitny** [comment]
I'll close this thread due to inactivity. We'll keep the existing behaviour for now, please use our "quick look" option by pressing `space` in project manager for now 😉
