### ISSUE TITLE
All select dropdowns are absolutely black on linux

### ISSUE THREAD

**Issue by Pavel311** [avocode/avocode#2067]
![screenshot_20180626_112920](https://user-images.githubusercontent.com/12411987/41899348-ea8320a2-7934-11e8-9aff-03839a2390b9.png)

Bug appears only in desktop app on Linux. Tested on Linux Mint 18.3 KDE and Linux Mint 18.2 Cinnamon. Both computers has AMD graphics cards with default GPU drivers, if it matters.

---
* **Version**: 3.1.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 71768
---
```
No stack trace available
```

**Comment by renekopcem** [comment]
Please, could you try Avocode on the web (app.avocode.com) or could you try run app with these commands https://github.com/avocode/avocode/issues/1158#issuecomment-315116735? It looks like issue with gpu driver.

**Comment by Pavel311** [comment]
I think it's amd driver specific issue. May be that's because of old gpus HD7790 and HD7660D. Also I tested desktop app with nvidia gtx1060 gpu, it works fine.

In web app issue doesn't appear.

--ignore-gpu-blacklist command helped:) Thanks!
