### ISSUE TITLE
App constantly crashes

### ISSUE THREAD

**Issue by DenisStetsenko** [avocode/avocode#2068]
---
* **Version**: 3.1.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
---

Each time I open Avocode it crashes. I tried to restart my mac and reinstall the app, but nothing helps.

Any advice would be appreciated!

**Comment by bolekkerous** [comment]
Hey @DenisStetsenko,
we're just trying to figure out the problem.

Would you be able to specify which version of MacOS are you using?

**Comment by jakubzitny** [comment]
I believe this is the same problem as in #2066. Can you please try running the app via this command from Terminal
```
open -a /Applications/Avocode.app --args -- --dev-tools
```

an send us the screenshot of the console? (Also exact version of macOS and your processor would help.)

**Comment by DenisStetsenko** [comment]
@bolekkerous , 
> Would you be able to specify which version of MacOS are you using?

sure , I'm on 10.13.5 macOS High Sierra

@jakubzitny , 

> an send us the screenshot of the console?

http://take.ms/WRIri

**Comment by DenisStetsenko** [comment]
@jakubzitny , let me know if it helped or if I can do something else to help you discover an issue.

**Comment by vojtatranta** [comment]
@DenisStetsenko there's nothing strange in the logs.

But we have one idea what it might have caused. Would you try this build, please? https://upx.cz/5Zn

Please, tell us whether it works or not. Thanks!

**Comment by DenisStetsenko** [comment]
@vojtatranta , works just fine. No crashes at all.

**Comment by vojtatranta** [comment]
@DenisStetsenko great! Thanks for trying it!

We will release a fixed version tomorrow.

**Comment by vojtatranta** [comment]
@DenisStetsenko and one other question. 

Could you send us how to crash looked like? We wonder whether crashed code in the application or the whole application process.

**Comment by DenisStetsenko** [comment]
@vojtatranta , I don't know how to replicate it now, since it works fine now. 
Basically, after I launched an app - it becomes unresponsive, then a white screen appears with a popup to post feedback into GitHub / Quit / Relaunch.
That's all.

**Comment by vojtatranta** [comment]
@DenisStetsenko I see, did it looked like this? https://downloads.intercomcdn.com/i/o/64707712/72b3e05ea1cfa3b0224d4914/image.png

**Comment by DenisStetsenko** [comment]
@vojtatranta , exactly!

**Comment by vojtatranta** [comment]
Aha, so the whole app crashed. 

Thank you, we know where the problem is. 

The built I sent you cannot be auto-updated, you have to use fixed stable version once we release it tomorrow.

**Comment by DenisStetsenko** [comment]
@vojtatranta , sure, looking forward. Glad to help!

**Comment by vojtatranta** [comment]
@DenisStetsenko we released a fixed version: https://avocode.com/download

**Comment by DenisStetsenko** [comment]
@vojtatranta seems to be working fine. thanks for letting me know!
