### ISSUE TITLE
Crashing project open

### ISSUE THREAD

**Issue by santirisco** [avocode/avocode#2070]
Avocode is crashing on project open all times

Yes, I tryd to update and there are'nt available updates

---
* **Version**: 3.1.0
* **Web/Desktop**: Desktop
* **Platform**: win32
---
```
{}
```

**Comment by vojtatranta** [comment]
Hi,
this is a known issue. We apologize for these troubles and we will release a fix tomorrow.

Meanwhile, you can visit avocode.com/download and there is version 3.0.0 which should work just OK.

**Comment by jakubzitny** [comment]
This is fixed in Avocode 3.1.1.
