### ISSUE TITLE
Avocode can't open Photoshop file since this week

### ISSUE THREAD

**Issue by bfulop** [avocode/avocode#2071]
Hello,

I have this huge, very complicated Photoshop file with many hundreds of layers:
_link removed_

I used to be (last week) able to open it with the web app in Chrome, Firefox, Safari and the desktop app (v. 3.0).

Right now, the only client that can open this file is Safari. All the other browsers and the desktop app stall at about 50% into the loading and the CPU keeps running at almost 100%.

---
* **Version**: 3.1.1
* **Sketch plugin version**: 50.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 247785
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @bfulop, thanks for reporting this, we'll investigate the issue here and get back.

**Comment by bfulop** [comment]
Thanks!

I tried opening the same file with a virtual PC from Paperspace.com and it worked! (Chrome Canary)
It takes a long time, but finally it does open. 

My daily machine is a 2015 Macbook (not the "pro" but with Core M CPU) maybe it's not powerful enough? I didn't have this problem though one week ago...

(edit: it's much hotter this week than the last and maybe my Macbook is throttling the CPU?)

**Comment by bfulop** [comment]
I have tried again this morning and now the same Macbook, same configuration could open the file! 

I had to wait for a couple of minutes but finally it did succeed. My totally unscientific theory is that my Macbook was already running too hot last time I tried opening this file and since it doesn't have any fans and active cooling at all (nor our office! 😅), the CPU was throttled way down. So even after waiting for 12 minutes last time the file would not open.

I close this issues now (and remove the link to the design file in question in the original comment).

**Comment by jakubzitny** [comment]
Hi, thanks lot for thorough details. We've tested the file and had no problems with it. These kind of problems are usually connected to the cpu and memory resources, not just cpu actually. Our rendering engine uses certain amount of memory when displaying designs, and also our app (Electron) takes something. If there is a lot of other apps running (like Slack, Skype, Spotify, lot of Chrome tabs) and also multiple tabs in Avocode, you might run into such issues. So what you mentioned makes sense.

We know about this and we're working hard on improving performance even more, so stay tuned for more updates 😉

**Comment by bfulop** [comment]
Yes in fact I do notice the performance improvements! 

Toggling a layer visibility used to take around 5-7 seconds now it's around 1 second.💯 So all these improvements you're making are welcome and much appreciated by those who have to work with these monstrous Photoshop files and underpowered machines!

For this reason I prefer to use  Chrome Canary to take advantage of the JavaScript engine improvements as soon as possible.
