### ISSUE TITLE
Avocode 2.0 has two taskbar icons on Windows

### ISSUE THREAD

**Issue by BrandonLive** [avocode/avocode#208]
For some reason, since I moved to 2.0, Avocode now creates two taskbar entries.

Steps to reproduce:
1) Launch atom.exe (guys, please rename this, it's really confusing).
2) Right-click the taskbar icon for the window and select "pin to taskbar".
3) Exit the app.
4) Click the pinned taskbar icon.

Result:
Two taskbar entries (with different icons!), which somehow both activate the same window (though the latter doesn't actually contain the Avocode window(s) when hovering).
Also, the extra entry is always flashing like it wants attention, for no reason.

Expected:
Only the original (pinned) taskbar entry is present.

**Comment by VPenkov** [comment]
What version of Windows are you using? It's working properly for me on 8.1.
It used to be like that when I ran Avocode via the shortcut instead of atom.exe.

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, we now have an installer that will create a proper Desktop shortcut.

**Comment by BrandonLive** [comment]
This still repros for me. Somehow your window isn't "glomming" with the pinned shortcut, even though it's the one created by your installer.

This is really strange as your window should be getting an auto-generated AppUserModelId from the process path, which should match the auto-generated one from the shortcut. The only reason for this bug would be if you're explicitly setting an AppUserModelId on your shortcut or your window (or both) which causes them to be different.
