### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by velihankara** [avocode/avocode#2081]
---
* **Version**: 3.1.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 304671
---
```
Error: EPERM: operation not permitted, open 'C:\Users\Erhan\.avocode\userdata\304671\documents\714687e578314a7eaea3ea45259d37e4\images\http-avocode-sketch-parser.s3.amazonaws.com-6c125578af8b40f59966e2d73edb76c5-images-f115b99a6ebacf0659f4a448b16ceb6e41db8776.png'
```

**Comment by jakubzitny** [comment]
Hi @velihankara, thanks for reporting this. We're aware this is happening sometimes, we're tracking the problem in #1926 already.

The following should help:

- quit Avocode
- delete `C:\Users\Erhan\.avocode` directory
- open Avocode and login again..

Please let me know if it helps.
