### ISSUE TITLE
Problem naming convention exporting to android

### ISSUE THREAD

**Issue by holandaeric** [avocode/avocode#2085]
* **Version**: 3.1.1

* **Web/Desktop**: Web and desktop

* **Platform/Browser**: Windows

* **Avocode e-mail**: ehv@cesar.org.br

I am using a naming convention for assets like "ic_home", but when I am exporting it (in web and desktop) is changing to "ic-home". This kind of naming "-" is not supported by android, so I have to renaming one by one before export. 

* **For next version**: Would be very nice if we could set up the android folders "drawable_..." as a prefix when exporting assets :))))

**Thanks!!!**

**Comment by jakubzitny** [comment]
Hi @holandaeric, thanks a lot for these comments. We definitely have to change the underscore to dash behaviour. As for the second request, we already know about it and we're planning to support it, however for now we've had more urgent features to address. Please vote for the feature on [our UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/33166837-export-images-to-approprite-folder).

**Comment by jakubzitny** [comment]
Hi @holandaeric, the naming conventions are improved in latest version of Avocode `3.3.1`. For the future we'll be also adding the scaled Android drawables to appropriate folders.

I'll close this issue for now, we can track the drawables on [our UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/33166837-export-images-to-approprite-folder).
