### ISSUE TITLE
Extra paddings around elements

### ISSUE THREAD

**Issue by insomniaOk** [avocode/avocode#2092]
* **Version**: 3.2.0

* **Web/Desktop**: desktop

* **Platform/Browser**: Linux

 nda@nodasoft.com

In last 2 or 3 Avocode versions in psd files on hover you can see extra paddings around elements which make css sizes (width, hight) incorrect. Also it is impossible to measure the sizes between elements. You can see that on the screenshot http://joxi.ru/krDqvaeSEgoxDm

**Comment by jankuca** [comment]
Hello, we were addressing this issue recently.

We invalidated cached renderings for you. Can you please try reopening the designs to see if it works correctly now? If not, reuploading the designs should fix the issue for you.

Please, let us know in any case if this is of any help.

**Comment by insomniaOk** [comment]
Thank you! It works
