### ISSUE TITLE
Graphic symbols 'exploding' 

### ISSUE THREAD

**Issue by ghost** [avocode/avocode#2094]
* **Version**: 3.2.0

50.0.0

* **Web/Desktop**: Both

* **Platform/Browser**: Mac, Chrome

 deb@fuelmultimedia.ca

When loading files from Sketch to Avocode, vector images and symbols are 'exploding' or moving from their intended location.  This has happened on multiple projects and Sketch files.  Below is a screenshot:

<img width="827" alt="screen shot 2018-07-23 at 8 37 28 am" src="https://user-images.githubusercontent.com/25755105/43076877-a9892c34-8e53-11e8-85fd-1305d5b9fabd.png">

**Comment by jakubzitny** [comment]
Hi @Fueldeborah, thanks for the report. We'll look into it and get back to you as soon as we have some info.

**Comment by qbz** [comment]
Hello, thanks for the report, can I ask you for any example file to investigate it? Thanks in advance.

**Comment by ghost** [comment]
https://drive.google.com/file/d/1Pqa3t_BzwefZzwJGHOvgm5cUbRpkOjzw/view?usp=sharing

**Comment by jakubzitny** [comment]
Thanks @Fueldeborah, we're looking into it.

**Comment by qbz** [comment]
Fixed. You will see changes as soon as we publish it on production.

**Comment by ghost** [comment]
Do you have a timeline on when this will be published?

**Comment by qbz** [comment]
I guess it will be released in approx. 2 weeks.

**Comment by jakubzitny** [comment]
Hi @Fueldeborah, a fix for this should already be available, if you try to re-upload your designs they should be rendered correctly.

Please let us know if you have any more problems 😉
