### ISSUE TITLE
error

### ISSUE THREAD

**Issue by velihankara** [avocode/avocode#2096]
---
* **Version**: 3.2.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 304671
---
```
Error: EPERM: operation not permitted, open 'C:\Users\Erhan\.avocode\userdata\304671\documents\e1c18d9a88be48e8b86cae492b4a20ce\images\http-avocode-sketch-parser.s3.amazonaws.com-b76e2d29157448319c9d39a4b26d7d99-images-da301576061184bf3d1fe6078fd91a8860cb3c2b.png'
```

**Comment by jakubzitny** [comment]
Hi @velihankara, thanks for reporting this again, we saw your problem in #2081 already. We're aware this is happening sometimes, we're tracking the problem in #1926.

The following should help, did you try it before?

- quit Avocode
- delete `C:\Users\Erhan\.avocode` directory
- open Avocode and login again..

Please let me know if it helps, if not we can figure out something else. Also, how often is this happening to you?

**Comment by jakubzitny** [comment]
I'll close this issue as we're already tracking it in #1926.
