### ISSUE TITLE
Bug with opacity for grouped layers

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#210]
First and very important issue - it's a bug with opacity for grouped layers. 
When designer added an opacity (in Photoshop), e.g. 90%, for the group of layers, Avocode renders this layers incorrectly. 
Avocode applies the opacity for each of layers in the group separately, so we get messed image. 
But Photoshop renders layers in the group different way in 2 steps: render the grouped image first and then adds an opacity for the resulting image.

Please, see the screenshots here: http://www.evernote.com/l/AAkJdoVwJoBDt5D7AfIx-jR1QAG7i2u-0Mw/

**Comment by rychlis** [comment]
Related to #210

**Comment by marekhrabe** [comment]
We are currently tracking this issue in our internal bug tracking system and working on a solution. We will keep you posted once we complete that…

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
