### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by drfateev** [avocode/avocode#2101]
Can't log in

My version 3.3.1

---
* **Version**: 3.3.1
* **Sketch plugin version**: 50.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 141772
---
```
No stack trace available
```

**Comment by bolekkerous** [comment]
Hello there,
it looks like we there are some server issues on our end which are causing this, we're currently investigating it. I'll let you know once we know more.

Best regards,
Bolek, Avocode Team

**Comment by nozpheratu** [comment]
I can't login either.

**Comment by petrbrzek** [comment]
You can see the status of resolving these server issues here https://avocode.statuspage.io/

**Comment by petrbrzek** [comment]
Problem resolved. It should work just fine.
