### ISSUE TITLE
Allow svg export of type layers (especially for icon fonts)

### ISSUE THREAD

**Issue by timkelty** [avocode/avocode#211]
Often times our designers will use an icon font (e.g. http://www.elegantthemes.com/blog/resources/elegant-icon-font) in their PSDs.

However, I need them as SVGs. It would be great if I could export a type layer as SVG, with the actual vector data.
Otherwise I have to download the font and do the conversion myself, which is a pain.

**Comment by petrbrzek** [comment]
Thanks for feature request. I put it on [UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7741200-allow-svg-export-of-type-layers-especially-for-ic).
