### ISSUE TITLE
today crash

### ISSUE THREAD

**Issue by WiseEagle** [avocode/avocode#2110]
---
* **Version**: 3.3.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 313317
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\wisee\AppData\Local\avocode\app-3.3.2\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\wisee\AppData\Local\avocode\app-3.3.2\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:4:15938)
    at C:\Users\wisee\AppData\Local\avocode\app-3.3.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1078
    at Promise (<anonymous>)
    at C:\Users\wisee\AppData\Local\avocode\app-3.3.2\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:637
    at <anonymous>
```

**Comment by jakubzitny** [comment]
Hi @WiseEagle, thanks for the report. We're already tracking this in #1867 so I am going to close this.

Is this happening to all designs you're trying to open and all the time?

Can you please try our web app at [app.avocode.com](https://app.avocode.com) to see if the same problem occurs?

**Comment by WiseEagle** [comment]
i open avocode on two devices. Maybe it's a problem. because I'm doing the preparation for the project and see all needed pages for work.

**Comment by jakubzitny** [comment]
Do you mean you tried to open two instances of Avocode? Or do you have two separate machines you're using with Avocode at the same time?

Actually, this problem can happen if you have too many tabs/designs open at the same time in Avocode for a long time and you're system does not have a lot of memory (e.g. 8GB). Could this be your case?

**Comment by WiseEagle** [comment]
Yes of course. It's my problem i have 4gb ram on my notebook. where i prepare project. Ok i change my station on PC. Good luck! And thanx.

**Comment by jakubzitny** [comment]
Maybe try having only one design open in Avocode at the same time, possibly the design should be as small as possible and then it should be usable. Thanks for the info, let us know if you need anything else 😉
