### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by Webdesme** [avocode/avocode#2114]
http://www.lavuix.ru/scr/2018-08-10_14-41-10.png why is that
this happens often
I can throw in the mail the source

**Comment by jakubzitny** [comment]
Please, do send the source or a public link to the design in Avocode to team@avocode.com. It's a rendering problem, we'll look into it.

**Comment by jakubzitny** [comment]
We found the design/problem actually, we're already working on a fix in our rendering engine.

**Comment by jakubzitny** [comment]
This should be fixed in the latest version of Avocode, please update and let us know if you still have similar issues @Webdesme 😉
