### ISSUE TITLE
Wrong design rendering

### ISSUE THREAD

**Issue by sarates** [avocode/avocode#2117]
After some of updates avocode have issue with design rendering. In most of case design is not the same as in sketch. Some elements are not visible, some has wrong position. Please fix this.

---
* **Version**: 3.3.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 53626
---
```
No stack trace available
```

**Comment by qbz** [comment]
Hello, thank you for a feedback, can you please share any example design that is broken in Avocode or atleast screenshots of the problem? Thanks in advance.

**Comment by sarates** [comment]
Yes, I already sent screenshots to team@avocode.com

**Comment by bolekkerous** [comment]
@sarates Unfortunately we can't see anything on that email mentioning this issue, could you perhaps tell us from which email did you send the email?

**Comment by sarates** [comment]
@bolekkerous t.stetsyuk@relevant.software

**Comment by jakubzitny** [comment]
I believe our support team followed up via e-mail, let's continue over there, I'll close this issue.
