### ISSUE TITLE
Chinese Character Fail to Display

### ISSUE THREAD

**Issue by iamrobert** [avocode/avocode#2118]
* **Version 3.3.2**: 

* **Desktop**:

* **Windows 10**:

AVOCODE doesn't recognize Microsoft Chinese Traditional system fonts.

Microsoft JingHei is the system font
https://docs.microsoft.com/en-us/typography/font-list/microsoft-jhenghei

looks like this:

![alt text](https://i.imgur.com/b6a00mG.jpg)

looks fine in XD:
![alt text](https://i.imgur.com/zfidrlU.png)

**Problem**
a) Cannot upload file as its a .ttc
![alt text](https://i.imgur.com/giHIqq2.png)

Shouldn't it work with system fonts?

**Comment by jakubzitny** [comment]
Hi @iamrobert, thanks for reporting this problem. We're not currently able to upload TTC font collections from Avocode. However, you can contact our support directly in the app (bottom right corner) and they'll be happy to add these fonts to your team in Avocode. All newly uploaded designs will be rendered correctly for you.

You can also share the font collection file to team@avocode.com or here on GH.

We'll be adding support for TTC font uploads in Avocode `3.5.0` which is planned to be released in upcoming weeks.

**Comment by iamrobert** [comment]
Thanks - I sent via message: 
https://we.tl/k8LU8Sjnrl

I did conversion as well:
https://www.files-conversion.com/font/ttc

The strange issue as well is that:

Microsoft Jing Hei and Microsoft Jing Hei Ui are the same file - but avocode only recognizes Jing Hei.

**Comment by bolekkerous** [comment]
Hey @iamrobert, so the font files should now be uploaded and once you reupload the design into Avocode, you should see the design with correct fonts.

However we are now aware that there is one more issue with asian fonts which we're already working on. It concerns breaking paragraphs into lines properly, which currently does not work correctly with some asian fonts. We will shortly start testing a fix on our staging environment, so it hopefully should not take long before we release the fix publicly.

I'll close this GitHub issue about JingHei font support and let you know on the Intercom chat and email once we also fix this related paragraph issue.
