### ISSUE TITLE
Crashing when working with app.

### ISSUE THREAD

**Issue by ptoseklukas** [avocode/avocode#2119]
---
* **Version**: 3.3.2
* **Web/Desktop**: Desktop
* **Platform**: win32
---
```
{}
```

I don't have any crash log or status message. 

Thanks

**Comment by jakubzitny** [comment]
Hi @Ptosek, thanks for reporting this. How often is this happening and when exactly did it happen when working with the app, please?

**Comment by jakubzitny** [comment]
Hi @Ptosek, thanks for reporting this. How often is this happening and when exactly did it happen when working with the app, please?

**Comment by ptoseklukas** [comment]
Hello, 

happen very randomly. When i import PSD and switching layers then it crashing but not every time. In sketch it crash too, but not too much. 

@jakubzitny

**Comment by jakubzitny** [comment]
I see, I'll try to prepare a special build for you with improved logging/debugging and with some attempts we think might fix the problem. If you try it, it might help us with finding the real problem here.

**Comment by jakubzitny** [comment]
Alright, here it is: https://we.tl/xDf8dHBpKI.

Can you please use this version and record a video again? The console should be automatically displayed with available logs, if it crashes, please send us the crashlog (that'll open on GitHub).

**Comment by ptoseklukas** [comment]
Thanks, i will try it.

čt 16. 8. 2018 v 10:44 odesílatel Jakub Žitný <notifications@github.com>
napsal:

**Comment by jakubzitny** [comment]
Any news @Ptosek, please?

**Comment by ptoseklukas** [comment]
Hello, I am using this version and still no crash. When it crash it I will
send crash report.


čt 23. 8. 2018 v 13:25 odesílatel Jakub Žitný <notifications@github.com>
napsal:

**Comment by jakubzitny** [comment]
Glad to hear that, we'll include these fixes in the next release of Avocode. 🙂

**Comment by jakubzitny** [comment]
Any specific details you can give us for the recent crashes @Ptosek, please? I understand that it has not been happening for a while, until yesterday? Is there any chance you had the app open for a long time, while OS was in sleep mode and this happened after wake?

**Comment by ptoseklukas** [comment]
Hello, i dont know exactly, but same project are without any problem but some project drop every 5 minutes. For example i am trying export group of layers and crash. 

> Is there any chance you had the app open for a long time, while OS was in sleep mode and this happened after wake?

Absolutely not, this also happens after 5 minutes of program startup and OS never go to sleep.

**Comment by ptoseklukas** [comment]
Some new crash with log

---
* **Version**: 3.4.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 331903
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\ptosek\AppData\Local\avocode\app-3.4.1\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at createUnsafeArrayBuffer (buffer.js:43:12)
    at createUnsafeBuffer (buffer.js:37:25)
    at Function.Buffer.allocUnsafeSlow (buffer.js:162:10)
    at FSReqWrap.readFileAfterStat [as oncomplete] (fs.js:391:27)
```

**Comment by jakubzitny** [comment]
Thanks @Ptosek, this is a bit different error. We see it on computers with not a lot of cpu/mem resources or some graphics hws/drivers that have problems with WebGL.

Did I mention that you can use our web app at [app.avocode.com](https://app.avocode.com)? Have you tried it, did you have any similar problems with it, please?

**Comment by jakubzitny** [comment]
Hi @Ptosek, we've added some improvements to our desktop app so this should not be happening as much as before. We're also working in even better performance and stability for `3.6.0` which should eliminate this completely. Can you please update and let us know if this issue still persists?

I'll also close this with respect to #2076 where we have the same issue.

**Comment by ptoseklukas** [comment]
Hello,

i try it and them i send feedback.

Ptosek

st 12. 9. 2018 v 16:56 odesílatel Jakub Žitný <notifications@github.com>
napsal:
