### ISSUE TITLE
Incorrect shortcut tooltip

### ISSUE THREAD

**Issue by iryan2** [avocode/avocode#212]
If you hover over the hand tool, the tooltip indicates that the shortcut is 'S'. However, that's the shortcut for the splice tool. The shortcut for the hand tool is 'H', please correct the tooltip messaging.

Thanks!

**Comment by VPenkov** [comment]
Already reported https://github.com/avocode/avocode/issues/180

**Comment by tomashanacek** [comment]
Duplicate of #180
