### ISSUE TITLE
Uhh… Not sure what happened

### ISSUE THREAD

**Issue by JWhiteUX** [avocode/avocode#2123]
Macbook locked up, cycled, and I got this message  

---
* **Version**: 3.4.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
---
```
{}
```

**Comment by jakubzitny** [comment]
Hi @JWhiteUX, thanks for the report. We've already seen this problem in similar scenarios, we'll be trying to address this behaviour in upcoming releases.

We're already tracking it in #2119 and #2076 so I'll close this thread.

How often is this happening, did you see it more than once?
