### ISSUE TITLE
Fonts not syncing with design file

### ISSUE THREAD

**Issue by northfacingdan** [avocode/avocode#2127]
Fonts are not syncing from sketch. The last few files i have synced directly from Sketch have done so without the fonts. See here for example: https://app.avocode.com/projects/666266 

---
* **Version**: 3.4.1
* **Sketch plugin version**: 51.0.0
* **Web/Desktop**: Desktop
* **Platform**: Mac, but other developers who access files have the same issue. 
* **Avocode UID**: 8605

**Comment by jakubzitny** [comment]
Hi @northfacingdan, you have to upload the missing fonts to Avocode separately, especially when you upload a design with special fonts that are not public.

1. After you open uploaded design in Avocode, you should see a notification that is requesting the font upload.

![screenshot 2018-08-23 at 13 17 50](https://user-images.githubusercontent.com/3315662/44522517-12e55900-a6d7-11e8-9c92-700f5dde780a.png)

2. When you click on it (or go to `File -> Upload Fonts` menu), you will see which fonts are missing. You can drag and drop the font files from your system, for now they need to be in `TTF` or `OTF` format. If these font files are in a location where your system stores fonts, Avocode desktop app will detect the font files automatically and you can just click on `Continue` and Avocode will upload the fonts to your team's storage and they will be available for you in the future.

3. After a while, you'll see a notification that the design was re-rendered with the new fonts and you can re-open it.


Everything should be alright at this point. If it's not, please let us know. If your fonts are only in collection format (`TTC`) you can send it to us here, via Intercom (in bottom right corner of the app) or via team@avocode.com and we'll upload them for you.
