### ISSUE TITLE
Cannot open Smart Objects

### ISSUE THREAD

**Issue by timkelty** [avocode/avocode#213]
Recently in Avocode, I was able to double click a Smart Object and open a new tab to see it's contents. That no longer seems possible, which makes it fairly useless for us.

Is this the same issue with PS described here?: https://github.com/avocode/avocode/issues/91

**Comment by petrbrzek** [comment]
We released an update today 2.1.0. Try it and let us know if that helps.

**Comment by timkelty** [comment]
I'm still unable to open Smart Objects with 2.1.0.

**Comment by tomashanacek** [comment]
Hi, could you share us the problematic design to team[at]avocode.com? Thank you.

**Comment by timkelty** [comment]
Sent!

**Comment by timkelty** [comment]
Any progress here?

**Comment by marekhrabe** [comment]
Hi Tim, I'm working on this last two or three days. The solution is not ready yet, but I'm getting closer to reason why it's not working. I'll let you know as soon as possible. Thanks for your patience

**Comment by timkelty** [comment]
Thanks!

**Comment by timkelty** [comment]
Unrelated, but there are another couple bugs/PSD discrepancies I have noticed from Avocode with that mockup:

- "PRODUCTS → Quick View / Comparison” contents and folders are all empty, but they aren’t in the PSD
- In “PRODUCTS → Quickview: In the PSD a drop shadow is added the the layer folder. In Avocode, that results in the text receiving a text shadow when it shouldn’t.
- "NAV // ABOUT → Ad-1 → New Products 2015" is empty in Avocode, but has contents in PSD

**Comment by chrisbcn** [comment]
Bumping this - I'm on 2.4.2 and I still can't double click to open smart objects. This was really useful and now I have to go through all the designs and ungroup the smart objects and put them back into the psds so that my devs can extract.

**Comment by timkelty** [comment]
Yeah - unfortunately this made me ditch Avocode altogether :(. Would like to try again in the future, if it gets fixed.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
