### ISSUE TITLE
Black screen in Ubuntu Budgie

### ISSUE THREAD

**Issue by octoxan** [avocode/avocode#2135]
* **Version**: 3.4.1
* **Web/Desktop**: Desktop
* **Platform/Browser**: Ubuntu Budgie 18.04, 17.10, 17.04 (all same issue)

When starting the Avocode app, after seeing the small square launcher, the main app opens and is just a black screen. Tested on four computers. Also can't close it without xkill. Close button does nothing.

**Comment by jakubzitny** [comment]
Hi @octoxan, thanks for reporting this and thanks for trying it on different computers/OSs. We're tracking a similar behaviour in #2109. We have problems reproducing this issue on our computers so we'd need as much info from you as possible.

One of the workarounds we've been able to come up with is following
- first launch freezes up, and you need to force quit (pkill/xkill)
- second launch gives a crash report, and a restart option
- restart works (via restart button), i need to log in again and everything works

Can you please try if this helps you?


If not, we'd be curious what's hiding in the app console. You can turn it on by pressing `alt` and going to `Help -> Troubleshooting -> Open Dev Tools` menu. Or you can start the app from CLI with this command:
```
/path/to/avocode -- --dev-tools
```

We'd like to see the screenshots of whatever you can see in the log.


Thanks a lot for help, we hope to resolve this asap. In the mean time you should be able to use our web app in Chrome/Chromium at [app.avocode.com](https://app.avocode.com).

**Comment by jakubzitny** [comment]
Hi @octoxan, thanks for reporting this and thanks for trying it on different computers/OSs. We're tracking a similar behaviour in #2109. We have problems reproducing this issue on our computers so we'd need as much info from you as possible.

One of the workarounds we've been able to come up with is following
- first launch freezes up, and you need to force quit (pkill/xkill)
- second launch gives a crash report, and a restart option
- restart works (via restart button), i need to log in again and everything works

Can you please try if this helps you?


If not, we'd be curious what's hiding in the app console. You can turn it on by pressing `alt` and going to `Help -> Troubleshooting -> Open Dev Tools` menu. Or you can start the app from CLI with this command:
```
/path/to/avocode -- --dev-tools
```

We'd like to see the screenshots of whatever you can see in the log.


Thanks a lot for help, we hope to resolve this asap. In the mean time you should be able to use our web app in Chrome/Chromium at [app.avocode.com](https://app.avocode.com).

**Comment by jakubzitny** [comment]
Closing with respect to #2109.
