### ISSUE TITLE
operation not permitted

### ISSUE THREAD

**Issue by syoki** [avocode/avocode#2137]
* **Version**: 3.4.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 21407
---
```
Error: EPERM: operation not permitted, open 'C:\Users\user\.avocode\userdata\21407\documents\e3d514e0165640478f461fb7cf2d70fc\images\http-avocode-sketch-parser.s3.amazonaws.com-c765f048da6446b0b623e1bcf606f275-images-9a55acfed912eea92afdd32cec65ceccb1ec6f1e.png'
```

**Comment by jakubzitny** [comment]
Hi @syoki, thanks for reporting this, we're already tracking the same problem in #1926.

The following should help, can you please try it?

- quit Avocode
- delete `C:\Users\user\.avocode` directory
- open Avocode and login again..

Please let me know if it helps, if not we can figure out something else. Also, how often is this happening to you?
