### ISSUE TITLE
Stopped unExpectedly

### ISSUE THREAD

**Issue by rahul26021999** [avocode/avocode#2139]
---
* **Version**: 3.4.1
* **Web/Desktop**: Desktop
* **Platform**: win32
---
```
{}
```

**Comment by jakubzitny** [comment]
Hi @rahul26021999, thanks for the report. We've already seen this problem on Windows, we'll be trying to address this behaviour in upcoming release next week.

We're already tracking it in #2119 and #2076 so I'll close this thread.

How often is this happening, did you see it more than once?
