### ISSUE TITLE
Avocode 2.0.0 doesn't sync

### ISSUE THREAD

**Issue by jfrick35** [avocode/avocode#214]
I keep getting a continuous downloading spinner when I try to sync on Avocode 2.0.0 but the updates are showing up in the Avocode Manager and the photoshop plugin has finished syncing.

**Comment by wkorku** [comment]
Have the same situation, don't see a project uploaded in web interface on my local Avocode app

**Comment by petrbrzek** [comment]
We released an update today 2.1.0. Try it and let us know if that helps.

**Comment by Zabavsky** [comment]
![screen shot 2015-09-29 at 11 16 54](https://cloud.githubusercontent.com/assets/11479816/10158572/a6d6c6a0-669b-11e5-8158-ca0e3b909247.png)

the same problem..((

**Comment by rychlis** [comment]
@Zabavsky this might have myriad of reasons and is most probably not related with the OP's problem, better contact us at team@avocode.com to resolve this individually
