### ISSUE TITLE
EACCES during single-instancing

### ISSUE THREAD

**Issue by leoparddemin** [avocode/avocode#2141]
---
* **Version**: 3.4.1
* **Web/Desktop**: Desktop
* **Platform**: linux
---
```
{"errno":-13,"code":"EACCES","syscall":"open","path":"/home/demin/.avocode/single-instance.json"}
```

**Comment by jakubzitny** [comment]
Thanks for the report @leoparddemin. When exactly did this happen? Is it happening repeatedly? 

We're using the `~/.avocode` directory to store some internal state and design data of the app. Can you make sure there are proper access rights to it? Avocode should be allowed to `rwx`. You can correct it by running the following command if it's not right:

```bash
chmod -R u+rwx /home/demin/.avocode
```

There might be some other issue with this, which linux distro are you using please?

**Comment by jakubzitny** [comment]
Thanks for the report @leoparddemin. When exactly did this happen? Is it happening repeatedly? 

We're using the `~/.avocode` directory to store some internal state and design data of the app. Can you make sure there are proper access rights to it? Avocode should be allowed to `rwx`. You can correct it by running the following command if it's not right:

```bash
chmod -R u+rwx /home/demin/.avocode
```

There might be some other issue with this, which linux distro are you using please?

**Comment by jakubzitny** [comment]
Changing the rights or removing the `~/.avocode` should help with this issue. I'll close this due to inactivity. Please let us know if you still have problems with it.
