### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by liuqiong92** [avocode/avocode#2142]
---
* **Version**: 2.17.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 412551
---
```
Error: The request timed out
    at file:///C:/Users/liuqiong/AppData/Local/avocode/app-2.17.3/resources/app.asar/dist/avocode.min.js:1:2190729
    at wrapped (C:\Users\liuqiong\AppData\Local\avocode\app-2.17.3\resources\app.asar\node_modules\@avocode\stage\node_modules\raven-js\src\raven.js:351:21)
```

**Comment by jakubzitny** [comment]
Thanks for the report @liuqiong92, when exactly did this happen please? What were you trying to do? I see you're using very very old version of Avocode. Can you update please?

If autoupdates don't work for you, please download the latest installer from [avocode.com/download](http://avocode.com/download).
