### ISSUE TITLE
No layers

### ISSUE THREAD

**Issue by polkom21** [avocode/avocode#2145]
Hello. I have a problem because in the moment i lost layers and there are not loaded now. What is wrong?

![image](https://user-images.githubusercontent.com/3143164/45446061-401c9a00-b6cc-11e8-8026-650c27c66ef3.png)

---
* **Version**: 3.5.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 414143
---
```
No stack trace available
```

**Comment by jakubzitny** [comment]
Hi @polkom21, sorry for this bug, we already know about it. If you change the width of the panel, the layers will appear and then they should be visible at all times, we'll fix this asap though.

**Comment by polkom21** [comment]
Thanks for tips with width of the panel. At the moment this method resolve my problem.

**Comment by jakubzitny** [comment]
Hi @polkom21, we've just released `3.5.1` and this problem is fixed.

Let us know if you have any more problems 😉
