### ISSUE TITLE
Problem with exporting svg

### ISSUE THREAD

**Issue by polkom21** [avocode/avocode#2147]
Hi!
I have a problem with export graphic as svg. Why avocode save it as bitmap in svg element? In photoshop I don't have problem with it. Graphic are saved as svg element without parse it before.

![image](https://user-images.githubusercontent.com/3143164/45561813-ebeaf480-b848-11e8-93b8-f08bd88be319.png)

---
* **Version**: 3.5.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 414143
---
```
No stack trace available
```

**Comment by bolekkerous** [comment]
Hey @polkom21,
is it possible that this object was imported into the PSD from Illustrator?

**Comment by polkom21** [comment]
@bolekkerous yes, this icon was imported into the PSD from Illustrator.

**Comment by bolekkerous** [comment]
I see, unfortunately, we do not support such workflow with imported SVG or Illustrator files into PSD at the moment, however, we are looking into ways how we could support it.

**Comment by jakubzitny** [comment]
We're actually tracking this in #967 already.
