### ISSUE TITLE
Exporting Shape layers as SVG is broken

### ISSUE THREAD

**Issue by dubstrike** [avocode/avocode#215]
Tried using Avocode for the only feature that would be interesting for me, and it turns out to be broken...

![svg export](http://imgur.com/8suEjRF.png)

**Comment by dubstrike** [comment]
Turns out that this designer's PSD was broken and it works on my own PSDs. 

Just great. I'll have to export this crap by hand.

**Comment by tomashanacek** [comment]
Hi, thank you for reporting the issue. Could you share us the problematic design to team[at]avocode.com?

**Comment by dubstrike** [comment]
@tomashanacek I've sent the PSD over. It's happening on OS X 10.10.3. The PSD was downloaded from Google Drive via their app and added to Avocode.

When I saved the PSD as new, exporting worked properly.

**Comment by PavelGavlik** [comment]
This should be added in 2.2.0. Feel free to reopen this if you run to any problems.

**Comment by ShavidzeT** [comment]
Desktop application on Ubuntu works great and in my case problem is theme I'm unable to export svg, but I think it is not software's bug, problem is in PSD ))))
