### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by shelegin** [avocode/avocode#2157]
---
* **Version**: 3.5.1-web
* **Web/Desktop**: Web
* **Platform**: windows 6.1
* **Browser**: yandex 18.9.0.3409
* **Avocode UID**: 423081
---
```
No stack trace available
```

**Comment by bolekkerous** [comment]
Hello @shelegin,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

**Comment by jakubzitny** [comment]
Hello @shelegin,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?
