### ISSUE TITLE
Wrong default project

### ISSUE THREAD

**Issue by kupcza** [avocode/avocode#216]
While uploading PSD via Avocode app, it sets wrong default project. While I open some projet and drag & drop file into it, I assume, that this project will be set as default :-(.

**Comment by kupcza** [comment]
Also when I drag'n'drop file onto specific design, I thoudht it should became it's revision as default. This is not happening right now.

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
