### ISSUE TITLE
while browsing

### ISSUE THREAD

**Issue by peter-gabra** [avocode/avocode#2160]
---
* **Version**: 3.5.1
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 356474
---
```
Error: EPERM: operation not permitted, open 'C:\Users\Rubix\.avocode\userdata\356474\documents\0b57f1b84a884068ba6a059fd7fa3e8c\images\http-avocode-sketch-parser.s3.amazonaws.com-233e2993de48480685cfdc42bd018e7d-images-604132c07a2b7d4f14e063e80d5453f3cee5e869.png'
```

**Comment by bolekkerous** [comment]
Hello @peter-gabra ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by jakubzitny** [comment]
This happens from time to time, we already know about it. Removing `.avocode` directory should help. We're tracking it in #1926 so I'll close this thread.
