### ISSUE TITLE
Errow when update new mac os mojave

### ISSUE THREAD

**Issue by hoanvokim** [avocode/avocode#2161]
---
* **Version**: 3.5.1
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 423877
---
```
TypeError: Cannot read property 'localeCompare' of undefined
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/system-font-families/dist/main.js:197:36
    at Array.sort (native)
    at Array.sort (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/core-js/modules/es6.array.sort.js:21:15)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/system-font-families/dist/main.js:196:78
    at <anonymous>
```

**Comment by crashmajstr** [comment]
Hello @hoanvokim ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by jakubzitny** [comment]
Hello @hoanvokim ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
