### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Designbystr** [avocode/avocode#2162]
49.3

* **Version**: 

 3.1.1 

 desktop
* **Web/Desktop**:

* **Platform/Browser**: OS X El Capitan 

 tolga@designbystructure.com 
but please if you need to contact me use: eleonora@designbystructure.com

My desktop app crashing

**Comment by crashmajstr** [comment]
Hello @Designbystr ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Does this error pop up everytime you try to open the app/design?

**Comment by Designbystr** [comment]
Hello Josef,

I tried yesterday and it worked.

Thanks for coming back to me!

Eleonora

Il giorno mer 3 ott 2018 alle ore 09:41 Josef Kettner <
notifications@github.com> ha scritto:

**Comment by crashmajstr** [comment]
Always happy to help, feel free to let us know in case of any questions, issues or feedback in the future! :)
