### ISSUE TITLE
Crashing on Web

### ISSUE THREAD

**Issue by kebbbnnn** [avocode/avocode#2164]
---
* **Version**: 3.5.2-web
* **Web/Desktop**: Web
* **Platform**: windows 6.1
* **Browser**: firefox 62.0
* **Avocode UID**: 426166
---
```
too much recursion
escape/<@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:58:4341
escape@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:58:4307
l@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:58:350867
e@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:58:351111
e.exports@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:58:350950
e.exports@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:604032
_reconcilerUpdateChildren@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:592733
_updateChildren@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:593670
updateChildren@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:593568
_updateDOMChildren@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:585074
updateComponent@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:583280
receiveComponent@https://cdn
```

**Comment by crashmajstr** [comment]
Hello @kebbbnnn ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Does this error pop up everytime you try to open the app/design?

**Comment by kebbbnnn** [comment]
hi i'm sorry for the late response. the error happens when I try to highlight an object. then the browser freezes and showing this on the top part of the browser
![screenshot_16](https://user-images.githubusercontent.com/4963227/46517973-98e2eb00-c8a4-11e8-9da9-a6e9e726e98c.png) and the error dialog. An yes this happens almost everytime I highlight an object

**Comment by crashmajstr** [comment]
Hi, thanks for the provided info. We are already aware of this bug, it's caused by our rendering system which will be replaced for a newer one in the upcoming months. So for now, please, use the desktop app. Sorry for the inconvenience. 
Best, Josef
