### ISSUE TITLE
font & line-height & box height issue

### ISSUE THREAD

**Issue by kty0529** [avocode/avocode#2166]
* **Version**: 3.5.2

* **Sketch plugin version**: 49.3

* **Web/Desktop**: Both

* **Platform/Browser**: Windows 10 / Google Chrome latest version

* **Avocode e-mail**: kty0529@gmail.com

Hi there,
I am a developer working on Avocode.
Create problems with the use of Avocode.

The value when creating by sketch and the value made automatically from avocode are different.

The setting is as follows.

---

**1. Sketch**
font-size: 16px;
line-height: 16px;
layer-height: 16px;

The result of Avocode
font-size: 16px;
line-height: 16px;
layer-height: 20px; (It is changed randomly for each element.)

**2. Sketch**
font-size: 42px;
line-height: 55px;
layer-height: 55px;

The result of Avocode
font-size: 42px;
line-height: 55px;
layer-height: 61px; (I do not know why the height is getting high)

**3. Sketch**
After entering the content, when entering a new line
abc
def

The result of Avocode
abc

def

A line break is entered again in the middle.

---

Please reply as to how to handle it when such a bug occurs.
In doing work, such problems often occur, but each time you speak with the designer another problem arises again to re-upload the original file.

Please advise about the solution.

I am sorry for my English being awkward.

* I attach attached files of images that I am not accustomed to using github and have attached an imgur album link.
https://imgur.com/a/1R5U5sG

thnkyou.

**Comment by crashmajstr** [comment]
Hi @kty0529 
I am sorry for the inconvenience. Please, can you send me the problematic design (or at least the problematic part)? We'll troubleshoot it on our end and let you know about the solution asap. 
Thank you.
Best,
Josef

**Comment by kty0529** [comment]
Hi, @crashmajstr 
Thank you for your response.
You can download the sketch file where the problem occurs through the following link.
https://drive.google.com/open?id=1KUK1J3cC553Fir6JBz5D4-8g0iovxIrs

If you need my Avocode account, send me an email and I will give you the account information.
I will help you if you can help me fix the bug.

Thank.

**Comment by crashmajstr** [comment]
thanks @kty0529 I'll look into it and let you know about the solution asap.

**Comment by crashmajstr** [comment]
Hi @kty0529 
I could reproduce the box height issue and I've just raised a ticket for our dev team. So I hope we'll be able to fix it soon.

But the second issue with 

> 3.
> Sketch
> After entering the content, when entering a new line
> abc
> def
> 
> The result of Avocode
> abc
> 
> def

I couldn't reproduce. Please, can you send me file, where you've experienced this bug? 
Thanks

**Comment by kty0529** [comment]
Hi, @crashmajstr 
Quick response Thanks.
Share the sketch file for the extra line breaks.
https://drive.google.com/open?id=1jYYft22qoCx9ia_Pe3wxLDgHxhMs_N8U

I'll be waiting for the good news.
Thank you.

**Comment by crashmajstr** [comment]
@kty0529 I can't reproduce that line break error even with your file... https://www.dropbox.com/s/jssocvv2sabezw3/Screenshot%202018-10-09%2017.22.47.png?dl=0

Do you have the latest avocode app (v3.5.2)?

**Comment by kty0529** [comment]
@crashmajstr 
Yes, I have latest avocode app (v3.5.2)

I'm sorry. Let me know the other part where the error occurs.
That part is resolved by re-uploading the sketch file, but the other part is not resolved.

[Imgur](https://i.imgur.com/K5tdIeo.png)

**Comment by kty0529** [comment]
You can find it in the file **2.ceoHistory_(1)tab2012_(1)pc**

**Comment by crashmajstr** [comment]
@kty0529 yeah, you're right I can see that one too. So, ok problems found, issues raised. I'll let you once it's fixed.

**Comment by kty0529** [comment]
Thank you very much.
The quick response is also very grateful.

I'm looking forward to the good news.

**Comment by crashmajstr** [comment]
Hi @kty0529 
I am forwarding a question from our dev team regarding the line break issue. Is possible that you have these texts in the designs pasted from windows? (e.g. somebody from windows sends them to you etc.)
Thank you!

**Comment by kty0529** [comment]
@crashmajstr 

I did not understand the question because my English was not good.
If the answer is correct, please help me.

The sketch file I uploaded on Mac OS is working through Avocode on Windows 10.
But when I asked the designer for a query from Avocode, he said the same thing happened.

In addition, if you copy the text of the element that Enter once more through Avocode, the enter normally enters once.

I hope it helps.
Thank you.

**Comment by crashmajstr** [comment]
Hello, I just want to inform you that the problem you had  has been fixed please, re-upload your design.
Best,
Josef
