### ISSUE TITLE
regexp too big

### ISSUE THREAD

**Issue by thielpeter** [avocode/avocode#2168]
---
* **Version**: 3.5.2-web
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: firefox 62.0
* **Avocode UID**: 5231
---
```
regexp too big
escape@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:58:4307
l@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:58:350867
e@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:58:351111
e.exports@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:58:350950
e.exports@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:604032
_reconcilerUpdateChildren@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:592733
_updateChildren@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:593670
updateChildren@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:593568
_updateDOMChildren@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:585074
updateComponent@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:583280
receiveComponent@https://cdn.app.avocode.com/dist/v-6f37dab/js/avocode-web.min.js:75:582833
receiveComponent@https
```

**Comment by crashmajstr** [comment]
Hello @thielpeter  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by thielpeter** [comment]
Hey @crashmajstr ,
the bug occured when I tried to open a design. The system seemed to load the layers, I clicked around and nothing did happen, then the error popped up. I think the system was not ready but I tried to use it. The Problem occured with different designs.

**Comment by crashmajstr** [comment]
So can you reproduce this error everytime you open a design? Please, can you send me a screencast of that? Thank you @thielpeter

**Comment by crashmajstr** [comment]
So can you reproduce this error everytime you open a design? Please, can you send me a screencast of that? Thank you @thielpeter
