### ISSUE TITLE
has crash

### ISSUE THREAD

**Issue by kty0529** [avocode/avocode#2175]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
---
```
{ preventDefault: [Function: preventDefault],
  sender:
   WebContents {
     webContents: [Circular],
     history:
      [ 'file:///C:/Users/kty-HP/AppData/Local/avocode/app-3.5.5/resources/app.asar/desktop-index.html?appDataDirname=C%3A%5CUsers%5Ckty-HP%5C.avocode' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events:
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        '-did-get-response-details': [Function],
        '-did-get-redirect-request': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Array],
        'did-navigate': [Function],
        destroyed: [Function],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-u
```
---
```
["app-finished-launching","app-crash-reporter-starting","app-crash-reporter-started","appready","appopenlisteners-replacing","appopenlisteners-replaced","appsplash-creating","appsplash-created","createwindow-starting","createwindow-browser-window-preparing","createwindow-browser-window-prepared","createwindow-crash-listener","createwindow-state-manage","createwindow-load-url","createwindow-dom-ready-listener","createwindow-finishing","ipc--calling-methog--setTitle","mainwindow-dom-ready","mainwindow-destroying-splash","mainwindow-showing","mainwindow-shown","mainwindow-maximizing","mainwindow-opening-init-urls","mainwindow-opening-init-files","mainwindow-initializing-menu-bar","ipc--setting-menu-bar-visibility"]
```

This version has been updated to 3.5.5, so it seems that there are some minor bugs.
I am also experiencing the problem of opening three tabs of other issues.

Rather than a specific tab problem, it was a file that opened well before the update, and it happened mostly when you turned on the Avocode and quickly turned on three tabs.
But this also happened randomly.

Now Avocode itself has stopped and has been completely terminated.
Request you to check.

Always appreciate.
Thank you.

**Comment by petrbrzek** [comment]
Thanks for reporting this bug. Did you have any opened design in those tabs? Also, did you remember whether you had guides enabled?

**Comment by crashmajstr** [comment]
Thanks for reporting this bug @kty0529 . Did you have any opened design in those tabs? Also, did you remember whether you had guides enabled?

**Comment by kty0529** [comment]
@petrbrzek @crashmajstr 

The answer was late.
I personally had a bad problem and the answer was late.
I am so sorry.

The Designer's Guide was on, and it seemed to recreate the situation where several tests resulted in errors.

Reproducing the problem occurred as follows.

1. Designer Guide is turned on
Hold down the Control key and double-click the file to open it with a new tab.
If you open multiple files in the file list at this time, the program stops while each step is loading and an error report appears.

However, no problem occurred when opening a new file after all one file was loaded.

2. You have turned off all of the Designer's Guide and My Guide
If you do not finish loading the tab while holding down the control key, several tabs open without problems and loading is complete.

Hope this helps you resolve the bug.
Thank you.

**Comment by kty0529** [comment]
Dismiss all warnings when multiple tabs are opened before the end of a single tab, and look at the end of the loaded tab.

Please be a reference.

[Imgur](https://i.imgur.com/grdYJQs.png)

**Comment by kty0529** [comment]
If you turn off the designer's guide and my guide, no matter how many taps you open, it works fine.

[Imgur](https://i.imgur.com/lS96TK0.png)

**Comment by kty0529** [comment]
If you open the tab with the designer guide turned off and then turn on the designer guide again, an error will occur.

---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 239989
---
```
Invariant Violation: Minified React error #136; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=136&args[]=Ruler for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (C:\Users\kty-HP\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\reactProdInvariant.js:31:15)
    at ReactCompositeComponentWrapper.updateComponent (C:\Users\kty-HP\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:584:219)
    at ReactCompositeComponentWrapper.receiveComponent (C:\Users\kty-HP\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactCompositeComponent.js:547:10)
    at Object.receiveComponent (C:\Users\kty-HP\AppData\Local\avocode\app-3.5.5\resources\app.asar\node_modules\react-dom\lib\ReactReconciler.js:125:22)
    at Object.updateChildren (C:\Users\kty-HP\AppData\Local\avocode\app-3.5.5\re
```

**Comment by crashmajstr** [comment]
@kty0529 Hi thanks for the provided info. We'll release a fix for this issue later today.

**Comment by kty0529** [comment]
@crashmajstr Thank you very much!
