### ISSUE TITLE
oops

### ISSUE THREAD

**Issue by shectermen** [avocode/avocode#2176]
---
* **Version**: 3.5.3
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 692
---
```
Invariant Violation: Cannot call hover after drop.
    at invariant (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/invariant/invariant.js:42:15)
    at DragDropManager.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/dnd-core/lib/actions/dragDrop.js:111:26)
    at Object.hover (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/dnd-core/lib/DragDropManager.js:92:33)
    at HTML5Backend.handleTopDragEnter (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/react-dnd-html5-backend/lib/HTML5Backend.js:519:18)
    at wrapped (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/stage/node_modules/raven-js/src/raven.js:375:21)
```

**Comment by crashmajstr** [comment]
Hello @shectermen  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by shectermen** [comment]
the program was just open and worked as a background

**Comment by crashmajstr** [comment]
@shectermen so it was only a one time issue or does it happen all the time?

**Comment by shectermen** [comment]
one time, i think program try get autoupdate and filed

**Comment by crashmajstr** [comment]
ok, I'll close this issue and let us know if it happens again in the future. Thank you for your time

**Comment by crashmajstr** [comment]
Last question @shectermen did you manage to get the app updated to 3.5.5 or not?

**Comment by shectermen** [comment]
nope

**Comment by crashmajstr** [comment]
So, please, try to download a new app from here https://avocode.com/download and let me know if it works ok. Thank you

**Comment by crashmajstr** [comment]
So, please, try to download a new app from here https://avocode.com/download and let me know if it works ok. Thank you @shectermen

**Comment by shectermen** [comment]
downloaded the new version and the error disappeared, but now I can't hide and export the layers

**Comment by crashmajstr** [comment]
thanks @shectermen, probably you have a little label "Lite mode" when you are in the inspect mode, right? In the last update, we enabled to all users Monroe rendering option (in the app preferences). So, if you were using the old rendering engine (that means you have disabled Monroe), just disable it again. 
Learn more about Lite mode problems here:  https://help.avocode.com/app-settings/lite-mode-in-avocode
Let me know if that helped.

**Comment by shectermen** [comment]
yes, Monro didnt work on mac os 10.13.2

**Comment by crashmajstr** [comment]
@shectermen true, so go to the app preferences and disable it :)

**Comment by shectermen** [comment]
thanx
