### ISSUE TITLE
Avocode line-height is wrong

### ISSUE THREAD

**Issue by ihorml** [avocode/avocode#219]
This is a screen from photoshop: https://www.dropbox.com/s/a801vkj7hhi2zbn/Screenshot%202015-04-27%2013.53.22.png?dl=0

This screen from Avocode: https://www.dropbox.com/s/tev70wprkldm1d2/Screenshot%202015-04-27%2013.54.23.png?dl=0 (it shows that line-height is 24px but it's wrong )

**Comment by tomashanacek** [comment]
Hi, thank you for reporting the issue. Could you share us the problematic design to team[at]avocode.com?

**Comment by tomashanacek** [comment]
Fixed in 2.1.0.
Reopen, if the problem still occurs.
