### ISSUE TITLE
Error Avocode

### ISSUE THREAD

**Issue by MeatCrash** [avocode/avocode#2192]
---
* **Version**: 3.5.5
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 429246
---
```
No stack trace available
```

**Comment by crashmajstr** [comment]
Hello @MeatCrash  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by MeatCrash** [comment]
Yes! That's the way. There was an error loading the layout, which was already in the project, and more it did not open, had to delete the layout file and fill again. After that, everything worked

**Comment by crashmajstr** [comment]
ok, please, let me know if you experience this issue again.
