### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wpc1403s2** [avocode/avocode#2196]
---
* **Version**: 3.5.6
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 439612
---
```
No stack trace available
```

**Comment by crashmajstr** [comment]
Hi @wpc1403s2  , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by crashmajstr** [comment]
Hi @wpc1403s2 , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.
