### ISSUE TITLE
sketch plugin (2.0.4) not syncing the last page

### ISSUE THREAD

**Issue by christophevouillamoz** [avocode/avocode#220]
I upload/sync my sketch design via the latest sketch plugin and it works properly expect the last page of my document which will not be uploaded/synced at all. I tried it a second time but does not change anything. It will neither appear on the web nor in the my mac app (also latest version, 2.0.0).

**Comment by tomashanacek** [comment]
Hi, thank you for reporting the issue. Could you share us the problematic design to team[at]avocode.com?

**Comment by rychlis** [comment]
We've released version 2.0.6 which should fix this issue
