### ISSUE TITLE
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation

### ISSUE THREAD

**Issue by yastrebovb** [avocode/avocode#2201]
---
* **Version**: 3.5.6
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 441804
---
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at Object.cropTransparentPixels (C:\Users\User\AppData\Local\avocode\app-3.5.6\resources\app.asar\node_modules\@avocode\stage\dist\utils\canvas.js:1:2073)
    at C:\Users\User\AppData\Local\avocode\app-3.5.6\resources\app.asar\node_modules\@avocode\stage\dist\entities\export\export-builder.js:1:4239
```

**Comment by crashmajstr** [comment]
Hi @yastrebovb  , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by crashmajstr** [comment]
Hi @yastrebovb  , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.

**Comment by crashmajstr** [comment]
Hi @yastrebovb , thanks for reporting this problem. Can you please send us the link the project or design where this is happening? We'll investigate the problem.

In the meantime, you can try reloading or re-uploading the design to see if the problem still occurs.
