### ISSUE TITLE
Reported via the error message in the app

### ISSUE THREAD

**Issue by Platman** [avocode/avocode#2206]
---
* **Version**: 3.6.0-web.2
* **Web/Desktop**: Web
* **Platform**: macosx 10.13.6
* **Browser**: chrome 69.0.3497.100
* **Avocode UID**: 393321
---
```
Error: The design or the revision is not available.
    at e.value (https://cdn.app.avocode.com/dist/v-1560f71/js/avocode-web.min.js:58:937473)
    at e.<anonymous> (https://cdn.app.avocode.com/dist/v-1560f71/js/avocode-web.min.js:156:1344378)
    at S (https://cdn.app.avocode.com/dist/v-1560f71/js/avocode-web.min.js:58:347965)
    at Generator._invoke (https://cdn.app.avocode.com/dist/v-1560f71/js/avocode-web.min.js:58:347730)
    at Generator.e.(anonymous function) [as next] (https://cdn.app.avocode.com/dist/v-1560f71/js/avocode-web.min.js:58:348144)
    at r (https://cdn.app.avocode.com/dist/v-1560f71/js/avocode-web.min.js:156:1338252)
    at https://cdn.app.avocode.com/dist/v-1560f71/js/avocode-web.min.js:156:1338346
```

**Comment by crashmajstr** [comment]
Hello @Platman   ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by crashmajstr** [comment]
Hi, just wanna inform you that we’ve just released the new version of Avocode 3.6.1 which could fix this issue. 
Please, update your desktop app, if you use the web app the new version is already there.
Let me know if the problem still persists or not. Thank you

**Comment by Platman** [comment]
Hi @crashmajstr - this error occurred when I received an email alert that a design was updated.  I clicked a link and thus was trying to open a specific design in the webapp, not the desktop app.  I have not installed the desktop app as I'm mostly a consumer / commenter on designs, not an individual contributor.

**Comment by Platman** [comment]
I'll note I've received this same error from multiple designs in our account, fairly regularly.  I can usually bypass the issue by going to our account and clicking on the designs individually, but I'd appreciate the convenience of going directly to updated designs via email alert.

**Comment by crashmajstr** [comment]
@Platman Thanks for reporting this, I'll take a look and try to reproduce this problem on my end. May I ask you for a screencast, just to make sure that I get it correctly, please?

**Comment by crashmajstr** [comment]
@Platman can you please, send me links to the design files you have a problem with? If it's not with every file it's weird.

**Comment by crashmajstr** [comment]
@Platman can you please, send me links to the design files you have a problem with? If it's not with every file it's weird.

**Comment by Platman** [comment]
Here's one example: https://urldefense.proofpoint.com/v2/url?u=https-3A__app.avocode.com_view_cb029803a9c14edda6e30c9eb43a335d_&d=DwMFaQ&c=dPoBOqv_VR_8FJ9u6wUbpK3qzw_-m_ilvytUimbgu0s&r=kJs4TDPUQPdj134DV6WiM0Z3eyDqiy_PQoBvdiqUhYc&m=xxD7zVUeT7tfl_nLWMv1PrpCNJHS-X7m9o22wqBQRas&s=aZb1Js_YHNpTbL29WHdHKR-Mw-90ns0Oz57D_CXyPvI&e=

**Comment by Platman** [comment]
Note - the previous link obviously goes through my employers' spam / phishing filters.  Here's where it redirects to: https://app.avocode.com/view/cb029803a9c14edda6e30c9eb43a335d/33663879/comments/

**Comment by crashmajstr** [comment]
Hello @Platman sorry for the delayed answer, I accidentally missed your response. Please, can you tell me if the problem still persists in the new version?
Thank you

**Comment by crashmajstr** [comment]
Hello @Platman sorry for the delayed answer, I accidentally missed your response. Please, can you tell me if the problem still persists in the new version?
Thank you
