### ISSUE TITLE
Sketch - An unexpected error has occured

### ISSUE THREAD

**Issue by jaznz** [avocode/avocode#221]
Describe your problem here…

Getting error (see screenshot when trying to open Interact2 project. Have updated Sketch plugin, Avocode etc today.

![image](https://cloud.githubusercontent.com/assets/365232/7383659/845726c0-ee77-11e4-8182-9b814e158c88.png)

```
TypeError: Cannot read property 'imageName' of undefined
  at /Users/Jasmine/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:5:14
  at /Users/Jasmine/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:4:452
  at /Users/Jasmine/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:4:452
  at /Users/Jasmine/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:4:452
  at g.module.exports.g._getImagesToLoad (/Users/Jasmine/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:5:135)
  at new g (/Users/Jasmine/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/assets-loader.js:1:431)
  at /Users/Jasmine/Downloads/Avocode.app/Contents/Resources/app/node_modules/avocode/lib/user.js:29:411
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)

```

**Comment by Demak** [comment]
Hi, I have the same-looking error in 3 of 5 sketch artboards in project I am working on, can you please tell me how to get that error message so I could report it?

**Comment by tomashanacek** [comment]
Hi, thank you for reporting the issue. Could you share us the problematic design to team[at]avocode.com?

**Comment by paragramm** [comment]
Have the same issue. Sent you my file with the same error.

**Comment by rychlis** [comment]
We've just released a server side fix that resolves this issue. Your designs will be re-synced automatically
