### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ThomasMullagaliev** [avocode/avocode#2229]
---
* **Version**: 3.6.2-web.2
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: yandex 18.9.1.954
* **Avocode UID**: 442964
---
```
No stack trace available
```

**Comment by crashmajstr** [comment]
Hello @ThomasMullagaliev  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by crashmajstr** [comment]
Hello @ThomasMullagaliev ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
