### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by FredUA** [avocode/avocode#2234]
---
* **Version**: 3.6.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 282611
---
```
Error: EACCES: permission denied, open '/home/user/.avocode/userdata/282611/previews/0d35a2ffc3d94795a698525eeb57b189-077f7717-2a68-43af-98d9-d7009a192fcd-preview.png'
```

**Comment by crashmajstr** [comment]
Hello @FredUA  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by FredUA** [comment]
Hi! I have uninstalled/installed my app and now it works fine. Thanks!

вт, 30 жовт. 2018 о 10:49 Josef Kettner <notifications@github.com> пише:

**Comment by crashmajstr** [comment]
Ok, thanks for letting me know!
