### ISSUE TITLE
Link to new design from email breaks

### ISSUE THREAD

**Issue by orvn** [avocode/avocode#2237]
When someone uploads a new design and I get an email notification about it, I click the `Open in Avocode` button . This takes me to the Avocode web app, but it breaks and asks me to send a report.

Tested in the latest Chrome and the latest Firefox.

Below is a GIF animation of the issue occurring. [This URL](https://app.avocode.com/view/cf294b980d634de6a6d19172f1e091fa/) is used in the example.

![avocode-deeplink-error](https://user-images.githubusercontent.com/3689720/47732086-d33d6f00-dc3b-11e8-809a-dd15f0cd8d19.gif)

---
* **Version**: 3.6.2-web.3
* **Web/Desktop**: Web
* **Platform**: macosx 10.14
* **Browser**: firefox 63.0
* **Avocode UID**: 390110
---
```
The design or the revision is not available.
value@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:58:940249
e/<@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:156:1344480
S@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:58:350769
b/a._invoke</<@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:58:350536
C/</e[t]@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:58:350945
r@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:156:1338379
r/<@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:156:1338473
a@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:75:429933
P/<@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:75:430055
l@https://cdn.app.avocode.com/dist/v-eb2049f/js/avocode-web.min.js:44:880189

```

**Comment by crashmajstr** [comment]
Hi @orvn , thank you for reporting this. This is an issue we already know about and the fix should be out tomorrow :)  
Best,
Josef
