### ISSUE TITLE
Links from email to desktop app

### ISSUE THREAD

**Issue by orvn** [avocode/avocode#2238]
Is there a feature in the roadmap to deep link into the desktop application?

I'm on MacOS and when I click an Avocode link in email, it opens in a new tab (web app). I would like it to open the Avocode app. Like if it downloaded a file with a special MIME type and all that file did was pass the link URI to the Avocode desktop app.

**Comment by crashmajstr** [comment]
Hi @orvn , actually that's not possible at the moment, but if you would like to see this feature in Avocode, please create a feature request on our UserVoice, so other users can vote for your idea too. You'll also get notified when the status of the feature request changes. The more votes your idea has, the more likely we'll prioritize it:
​
https://avocode.uservoice.com/forums/277080-feature-voting 

For now, you can just take the URL from email and paste it into the search in the desktop app and find the desired file faster.

Does that help?

**Comment by orvn** [comment]
Yes thanks. You're right, this is a feature request, not an issue.
