### ISSUE TITLE
App do nothing while uploading and saving new design

### ISSUE THREAD

**Issue by kupcza** [avocode/avocode#224]
While drag'n'drop file into app, after setting project, design name and clicking on Save it looks normal. But After 100% upload it does nothing.
https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/7eyoz1_b.png

I have to upload it  again. In project manager it appears on bottom  as pending design. But when I click on this, it opes new tab as prev pic.
https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/cy31f8-t.png

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
