### ISSUE TITLE
strange error

### ISSUE THREAD

**Issue by truemoroz** [avocode/avocode#2241]
---
* **Version**: 3.6.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 111132
---
```
RangeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation
    at Object.cropTransparentPixels (C:\Users\Versta\AppData\Local\avocode\app-3.6.2\resources\app.asar\node_modules\@avocode\stage\dist\utils\canvas.js:1:2186)
    at C:\Users\Versta\AppData\Local\avocode\app-3.6.2\resources\app.asar\node_modules\@avocode\stage\dist\entities\export\export-builder.js:1:4352
```

**Comment by crashmajstr** [comment]
Hello @truemoroz  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by crashmajstr** [comment]
Hello @truemoroz ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
