### ISSUE TITLE
error

### ISSUE THREAD

**Issue by WARFALAMEY** [avocode/avocode#2242]
---
* **Version**: 3.6.2
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 451591
---
```
No stack trace available
```

**Comment by crashmajstr** [comment]
Hello @WARFALAMEY ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by crashmajstr** [comment]
Hello @WARFALAMEY ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
