### ISSUE TITLE
I can't open regular psd files

### ISSUE THREAD

**Issue by shavidzet** [avocode/avocode#2245]
These files worked just fine, but now, it shows errors
<img src="https://i.imgur.com/zyyaYVi.png" />
and if I'll wait more than 10 min, it opens psd but missing some functionality.

Is there any way to debug avocode runtime software? I think it would help us to find problems quickly

---
* **Version**: 3.6.2
* **Sketch plugin version**: 51.2.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 103862
---
```
No stack trace available
```

**Comment by shavidzet** [comment]
Same problem in web client

**Comment by vojtatranta** [comment]
HI @ShavidzeT ,
can you send me a private link to that design? Thanks.

**Comment by shavidzet** [comment]
@vojtatranta Hi,
I hope you are from Avocode team, but I'm not sure yet. 😄 
Please provide me your email.

**Comment by vojtatranta** [comment]
@ShavidzeT sure, yeah, sorry :)) vojtatranta@avocode.com

**Comment by shavidzet** [comment]
@vojtatranta great, thank you.
I shared with you my dropbox mockup.

**Comment by vojtatranta** [comment]
@ShavidzeT aha, cool. I wanted a link to avocode like: `https://app.avocode.com/revision/123?design=333` just link to the app please.

**Comment by shavidzet** [comment]
How can I get a link, I can't find even in docs.

**Comment by vojtatranta** [comment]
@ShavidzeT just try to open that design in the web application :). Sorry, maybe I was not clear.

**Comment by vojtatranta** [comment]
@ShavidzeT I managed to open that design in the app. So I think reupload will work just OK, but I would like to look at why your design failed and for that I need that link.

**Comment by shavidzet** [comment]
@vojtatranta here it is: https://app.avocode.com/revisions/9419712/?design=6270244

**Comment by vojtatranta** [comment]
@ShavidzeT aha, no processing of that design started on the server, strange, there might be something wrong with the plugin.
I tried drag'n'drop importing of that PSD and it worked OK. Would you try it too?

**Comment by shavidzet** [comment]
Hey, yeah, reuploading works, but I want to avoid this process.
How can I enable/disable plugins? I'll test one-by-one

**Comment by vojtatranta** [comment]
@ShavidzeT sorry, I need this to be sorted out.

You uploaded the PSD for the first time with the plugin directly from Photoshop, right?  If so, just use Drag and Drop to the application to bypass Photoshop plugin.

I you imported the PSD right into the Avocode app via drag and drop, than there is such bug and we will look at it as soon as possible.

But surely, import should work all the time. It is definitely a bug that it did not work now.

**Comment by shavidzet** [comment]
@vojtatranta For the first time I uploaded mockups with drag & drop, without photoshop.

and now I imported same file with same way(directly drag&drop), but new uploaded files work, but old don't

**Comment by vojtatranta** [comment]
Aha, I see. We will definitely look at it as soon as possible and we will come back to you.

Thank you for your report and sorry for the complications.

**Comment by rychlis** [comment]
Hello, after investigation we found an issue that could prevent you from opening some PSDs uploaded in the first half of 2017 and before. There is now a fix deployed to our backend which should resolve the issue.

You should be able to open the design now, definitely let us know if you are still having any issues.

Thanks for the report and I want to say I'm especially sorry about this issue as it's affecting our oldest (and most loyal) customers! We will make sure to monitor the process of design opening better to prevent similar issues in the future.
