### ISSUE TITLE
error

### ISSUE THREAD

**Issue by exp-jinson** [avocode/avocode#2246]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 48.2.8
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 174597
---
```
Error: getaddrinfo ENOTFOUND preview-production.avcd.cz preview-production.avcd.cz:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by crashmajstr** [comment]
Hello @exp-jinson ,
thank you for reporting this. I believe that this issue is caused by your outdated app. Please, update your app and let me know if the problem still persists.
Best,
Josef
