### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Alimjanov-Ibragim** [avocode/avocode#2247]
---
* **Version**: 2.17.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 216707
---
```
Error: getaddrinfo ENOTFOUND preview-production.avcd.cz preview-production.avcd.cz:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by crashmajstr** [comment]
Hello @Alimjanov-Ibragim  ,
thank you for reporting this. I believe that this issue is caused by your outdated app. Please, update your app and let me know if the problem still persists.
Best,
Josef
