### ISSUE TITLE
project2

### ISSUE THREAD

**Issue by vallis2** [avocode/avocode#2248]
---
* **Version**: 3.6.3-web
* **Web/Desktop**: Web
* **Platform**: windows 6.1
* **Browser**: yandex 18.9.1.954
* **Avocode UID**: 455867
---
```
No stack trace available
```

**Comment by crashmajstr** [comment]
Hello @vallis2  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by crashmajstr** [comment]
Hello @vallis2 ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
