### ISSUE TITLE
ивыиы

### ISSUE THREAD

**Issue by admin22222** [avocode/avocode#2250]
---
* **Version**: 3.6.3-web
* **Web/Desktop**: Web
* **Platform**: windows 10.0
* **Browser**: yandex 18.9.1.954
* **Avocode UID**: 450118
---
```
No stack trace available
```

**Comment by admin22222** [comment]
ыви

**Comment by admin22222** [comment]
ывм

**Comment by crashmajstr** [comment]
Hello @admin22222 ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by crashmajstr** [comment]
Hello @admin22222 ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?
