### ISSUE TITLE
Application froze for a while during opening a PSD

### ISSUE THREAD

**Issue by Kout** [avocode/avocode#2253]
---
* **Version**: 3.6.0
* **Web/Desktop**: Desktop
* **Platform**: linux
* **Avocode UID**: 54597
---
```
RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out of range. Received 33206
    at Object.fs.fchmod (fs.js:1070:11)
    at Object.fchmod (/opt/Avocode/resources/app.asar/node_modules/graceful-fs/polyfills.js:237:17)
    at mode (/opt/Avocode/resources/app.asar/node_modules/vinyl-fs/lib/fileOperations.js:132:10)
    at onStat (/opt/Avocode/resources/app.asar/node_modules/vinyl-fs/lib/fileOperations.js:125:14)
    at /opt/Avocode/resources/app.asar/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:183:5)
```

**Comment by crashmajstr** [comment]
Hello @Kout  ,
would you be able to describe when exactly did this error happen? Do you remember what were you doing when the error popped out?

Were you trying to open a specific design? If so, does the error pop up everytime you try to open the same design?

**Comment by Kout** [comment]
Hi,

I think it is minor error, I just followed the dialogue which popped up.
Anyway, the PSD was old, from 2015, so I’d say it was some kind of
compatibility issue. I was able to stop frozen loading and get back to
projects overview. On the second trial, Avocode finished the loading
process, however loading some layers failed. I got back to project overview
and the third and last try was successful then. I was able to get to all
layers.

Have this helped you?

Tomáš

pá 9. 11. 2018 v 9:58 odesílatel Josef Kettner <notifications@github.com>
napsal:

**Comment by crashmajstr** [comment]
Thank you for letting us know. Please, can you send me a link to that design file? We'll take a closer look at it. Thank you and sorry for the inconvenience.

Since it looks like that it's working I'll close this issue.
Also, don't hesitate to contact us anytime in the future.
Best,
Josef

**Comment by Kout** [comment]
It was absolutely fine, didn’t caused any troubles to me.

Here is the file:
https://app.avocode.com/view/810e8f7f970644d48c55a1775fc58074/_/comments

Regards,

Tomáš

pá 9. 11. 2018 v 12:17 odesílatel Josef Kettner <notifications@github.com>
napsal:
