### ISSUE TITLE
Import fonts from typekit

### ISSUE THREAD

**Issue by lubomirblazekcz** [avocode/avocode#2257]
* **Version**: 3.6.3
* **Web/Desktop**: Desktop
* **Platform/Browser**: Windows

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/34679989-allow-syncing-with-adobe-typekit-fonts 
https://help.avocode.com/inspect-get-assets-and-specs/import-missing-fonts-to-to-designs-in-avocode

As described above, fonts from typekit should automatically import to Avocode, but that does not work for me. I have design from Adobe XD and all fonts synced via Adobe Creative Cloud, but fonts are still marked as missing. Font name is URW Form.

**Comment by jakubzitny** [comment]
Hi @evromalarkey, thanks for reaching out to us. When you click on the missing font button/alert, you should see a "Font upload" modal where you can drag and drop files, or choose the fonts in your system. In Desktop app, most of the fonts in system should be automatically found and checked (with a green checkbox) for upload. However, you still need to upload them (by submitting the fonts for upload and agreeing to license terms..). Did you do this or did the font modal miss your Typekit fonts?

Can you please send us a screenshot of the font upload modal you see? Also, there is a possibility that some system or typekit fonts do not get found in system. This can happen in special installations, or when our font detector fails to find the fonts in the locations that are used the most. In that case, you have to find the font manually in the system and drag&drop it into the modal.

Thanks 😉

**Comment by lubomirblazekcz** [comment]
[font upload modal](https://user-images.githubusercontent.com/6872956/48341844-75168000-e66e-11e8-89d6-4adb7fd7a94f.png)

The modal miss my typekit fonts, they are synced though. The fonts are not located in C:\Windows\Fonts but are displayed in [windows settings](https://user-images.githubusercontent.com/6872956/48341962-c4f54700-e66e-11e8-97f7-f563b21f702d.png)

I can't upload them manually since they are adobe licenced fonts, so they can not be downloaded as ttf.

**Comment by jakubzitny** [comment]
I see, thanks. Avocode failed to find the font files locally then. Do you have a latest/regular Adobe Creative Cloud installation in your system? Also, what Windows version do you use, please?

Can you please try syncing another Typekit font if you have time? This would help us detect if this is a font-related problem or a system problem.

We usually search for Typekit fonts on Windows in your home directory under
```
AppData\Roaming\Adobe\CoreSync\plugins\livetype\r\
```

Can you please check manually if the fonts are located there?

If so, this could really just be a font-specific problem where we fail to detect the proper postscript name of the font.

Thanks again.

**Comment by lubomirblazekcz** [comment]
Yes I found the fonts in the appdata location thanks, I renamed them to ttf and imported them manually.
They were named - 36647,36648,36650,36651,36653,36656,36658

I have latest version of Creative Cloud 4.7.0.400 and Windows version is 10, build 1809

**Comment by jakubzitny** [comment]
Thanks a lot. Can you please send me your Avocode email so I can re-check on our backend why the detection failed in the first place?

**Comment by lubomirblazekcz** [comment]
yep -> lubomir.blazek@newlogic.cz
