### ISSUE TITLE
Error: Could not download metadata (revision=34575333)

### ISSUE THREAD

**Issue by yasserzakaria** [avocode/avocode#2258]
---
* **Version**: 2.17.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 125302
---
```
Error: Could not download metadata (revision=34575333)
    at file:///C:/Users/yasse/AppData/Local/avocode/app-2.17.2/resources/app.asar/dist/avocode.min.js:1:1129304
    at <anonymous>
```

**Comment by crashmajstr** [comment]
Hello @yasserzakaria ,
thank you for reaching out. This error could be caused by your outdated app, please, update your app and let me know if it works ok.
Thank you.
Best,
Josef
