### ISSUE TITLE
Pixel checker not working

### ISSUE THREAD

**Issue by lubomirblazekcz** [avocode/avocode#2261]
* **Version**: 3.6.3
* **Web/Desktop**: Desktop
* **Platform/Browser**: Windows 10

It's XD imported design, link - https://app.avocode.com/view/038c5aabb64646d1a69d5aed1ef75545

![obrazek](https://user-images.githubusercontent.com/6872956/48398121-288b7d00-e720-11e8-96d0-bd7f7534b57c.png)

**Comment by crashmajstr** [comment]
Hello @evromalarkey again, please, can you send me a link to that design? We'll take a look what's wrong. I am sorry for the inconvenience.

**Comment by lubomirblazekcz** [comment]
np, link is above

**Comment by crashmajstr** [comment]
@evromalarkey sorry didn't notice... Thank you

**Comment by crashmajstr** [comment]
@evromalarkey I am sorry for the inconvenience, but right now we can't reproduce your error which is strange. We'll do some further investigation in the future and let you know, once we find anything.

**Comment by lubomirblazekcz** [comment]
Ha, fixed it. I've deleted previews via Troubleshooting -> Clear Previews

It probably was just corrupted preview image.

**Comment by crashmajstr** [comment]
oh, great @evromalarkey thanks for letting us know. At least we know how to fix it.

**Comment by lubomirblazekcz** [comment]
You will probably hate me, but I just found another issue with pixel checker / preview images 😃

Font in preview image is different than original (different font and letter spacing). Should I open a new issue on this?

**Comment by crashmajstr** [comment]
@evromalarkey in the same design, the homepage?

**Comment by lubomirblazekcz** [comment]
Yes, on homepage and all other artboards.

**Comment by crashmajstr** [comment]
Hmm that's weird because it works ok on my end. Can you send me a screenshot please of that problem?

**Comment by lubomirblazekcz** [comment]
![obrazek](https://user-images.githubusercontent.com/6872956/48425730-b178d780-e765-11e8-8623-c8ed7ff75d50.png)

Font is different, I tried it on different device and it has the same issue

**Comment by crashmajstr** [comment]
Hello @evromalarkey we've investigated it and found some bugs, thanks to you. What should help you regarding this issue is to re-upload the file again. Since you already have these fonts in Avocode it should work ok. Please, let me know.
