### ISSUE TITLE
I get an "Export Failed" message while trying to export an asset from the desktop app!

### ISSUE THREAD

**Issue by mo-mansour** [avocode/avocode#2263]
---
* **Version**: 3.6.3
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 460891
---
```
No stack trace available
```

**Comment by crashmajstr** [comment]
Hello @mo-mansour I heard you already discussed this bug with Maks so I'll close this issue.
Let us know if you have any problems in the future.
