### ISSUE TITLE
мерцает монитор

### ISSUE THREAD

**Issue by Vyachx** [avocode/avocode#2264]
---
* **Version**: 3.4.1
* **Web/Desktop**: Desktop
* **Platform**: linux
---
```
{}
```

**Comment by crashmajstr** [comment]
Hi @Vyachx ,
I am sorry for the inconvenience, but I can see that you have an outdated app, please, can you update your app and let me know if the problem still persists?
Thank you

**Comment by crashmajstr** [comment]
Hi @Vyachx ,
I am sorry for the inconvenience, but I can see that you have an outdated app, please, can you update your app and let me know if the problem still persists?
Thank you
