### ISSUE TITLE
Group layer styles are applied to all child layers

### ISSUE THREAD

**Issue by rychlis** [avocode/avocode#227]
This will need a lot of work in the rendering department. For example shadow effect is rendered incorrectly

![66ea3346-dcb2-11e5-9ea1-3d6376542281](https://cloud.githubusercontent.com/assets/1819747/13427936/8041c1b2-dfb7-11e5-8972-c8dde4873431.png)

**Comment by rychlis** [comment]
Related to #210

**Comment by RobertLang** [comment]
Any news on this issue? This is really a big issue because our designers can never be sure that layouts are correctly displayed in Avocode

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by Wiredframe** [comment]
Any updates on this CRITICAL bug please?

**Comment by n0rule5** [comment]
Seriously, this is still happening in Sketch files. I hate to admit it, but some developers are continually confused by it.

**Comment by bolekkerous** [comment]
This should be fixed in 2.11+.

Please open a new issue if you still experience any problems with this.

**Comment by bolekkerous** [comment]
Hey - 
we’ve already released a new version - 2.19 - which I believe should fix this issue.

Please update your app and it should hopefully work.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
