### ISSUE TITLE
Paragraph spacing from Adobe XD not preserved

### ISSUE THREAD

**Issue by mhlozek** [avocode/avocode#2272]
Avocode 3.6.4 (desktop, windows)

See attached screenshots. 
Text formatted with paragraph spacing property is not correctly rendered in Avocode.

![adobe-xd](https://user-images.githubusercontent.com/2743172/49116136-fdb33400-f29c-11e8-9a5b-91566282611b.png)
![avocode](https://user-images.githubusercontent.com/2743172/49116137-fdb33400-f29c-11e8-8298-02381f877d4d.png)

**Comment by crashmajstr** [comment]
Hello @mhlozek , thank you for reporting this. Please, can you send a link to this design? I'll take a look and forward it to our dev team for further investigation and fixing. 
I am sorry for the inconvenience.

**Comment by mhlozek** [comment]
Here is the link to Adobe XD source file:
https://1drv.ms/u/s!AlWfyeLZDhoRlapo1zH_pZ0ruQqnNw

**Comment by crashmajstr** [comment]
Thank you, I'll hand it out to our dev and let you know once it's fixed. 
I am sorry for the inconvenience.

**Comment by crashmajstr** [comment]
Hello, I just want to inform you that the problem you had has been fixe please, re-upload your design.
Best,
Josef
