### ISSUE TITLE
App crashes on layer select or toggling visibility of the layer

### ISSUE THREAD

**Issue by AlbertRAR** [avocode/avocode#2273]
---
* **Version**: 3.6.5
* **Web/Desktop**: Desktop
* **Platform**: linux
---
```
{ preventDefault: [Function: preventDefault],
  sender:
   WebContents {
     webContents: [Circular],
     history:
      [ 'file:///opt/Avocode/resources/app.asar/desktop-index.html?appDataDirname=%2Fhome%2Falbert%2F.avocode' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events:
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        '-did-get-response-details': [Function],
        '-did-get-redirect-request': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Array],
        'did-navigate': [Function],
        destroyed: [Function],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        crashed: [Fu
```
---
```
["app-finished-launching","app-crash-reporter-starting","app-crash-reporter-started","appready","appopenlisteners-replacing","appopenlisteners-replaced","appsplash-creating","appsplash-created","createwindow-starting","createwindow-browser-window-preparing","createwindow-browser-window-prepared","createwindow-crash-listener","createwindow-state-manage","createwindow-load-url","createwindow-dom-ready-listener","createwindow-finishing","ipc--calling-methog--setTitle","mainwindow-dom-ready","mainwindow-destroying-splash","mainwindow-showing","mainwindow-shown","mainwindow-opening-init-urls","mainwindow-opening-init-files","mainwindow-initializing-menu-bar","ipc--setting-menu-bar-visibility"]
```

**Comment by AlbertRAR** [comment]
It seems a memory leak issue...

**Comment by crashmajstr** [comment]
Hello. Could you describe exactly how this error happened? Were you trying to open a specific design? If so, does this error occur every time you try to open that design? 
Please, let me know and we'll try to fix the issue as soon as possible.

**Comment by AlbertRAR** [comment]
Hello,
Yes, when I try to open a specific design. Yes, every time. I even tried to split it into several parts but is still freezes or crases. Same happens in the web app.

**Comment by crashmajstr** [comment]
@AlbertRAR please, can you send me a link to that design? I'll take a look and try to troubleshoot it on my end.
I am sorry for the inconvenience.

**Comment by AlbertRAR** [comment]
Please provide me an email so I can share a design privately to you.

**Comment by crashmajstr** [comment]
josefkettner@avocode.com

**Comment by AlbertRAR** [comment]
done

**Comment by crashmajstr** [comment]
Hello @AlbertRAR , it definitely looks like a memory leak issue. I've tried to upload this file and it worked for me, but the file is huge in the web app it was impossible to open it, but I managed to open it in the desktop app. 

Then I tried to work with the file, except the slowness I didn't encounter any issue, but I can imagine that other computers can. 

I am sorry for the inconvenience, but my only suggestion is to maybe split it more, the problem is that the file contains huge bitmaps which mainly causes these problems.

**Comment by AlbertRAR** [comment]
I already split it into several blocks but still, have issues even in a more powerful pc than my laptop.  This is especially noticeable when I switch the visibility of the layer that is embedded.
Anyway, thank you for the time you spent. I will try to split the design even more.

**Comment by crashmajstr** [comment]
Thanks for letting me know @AlbertRAR I am still not happy how it went... I'll try to investigate a bit more on Monday on some Linux PC and we'll see. 
When you manage to split the file please, feel free to send me links from Avocode (share) to my email and I'll take a look at it as well. 
I am sorry for the inconvenience. Have a nice weekend,
Josef
