### ISSUE TITLE
Blur + Shadow causes transparent rectangle

### ISSUE THREAD

**Issue by Fire3galaxy** [avocode/avocode#2276]
Version 3.6.6 
Desktop
Ubuntu 18.04.1
daniel.handojo@zii.aero

When opening an Adobe XD file that has an element with both shadow and blur, the following occurs. The issue does not occur with shadow only or blur only.
![image](https://user-images.githubusercontent.com/5578991/50018504-63cdd580-ff84-11e8-815f-0e37d30d2aa1.png)

**Comment by crashmajstr** [comment]
Hello, thank you for reaching out. I am sorry for the inconvenience. Please, can you send me a link to this Avocode design? I'll take a look and try to troubleshoot it on my end.
Thank you,
Josef

**Comment by crashmajstr** [comment]
Hello again, I tried to reproduce this and you are right. I am sorry for the inconvenience. I've raised an issue for our dev team. 
I'll inform you once it gets fixed.

**Comment by Fire3galaxy** [comment]
Thanks!

**Comment by Fire3galaxy** [comment]
Refreshing the above, and happy new years :+1:

**Comment by crashmajstr** [comment]
Thanks, noted, still under development.

**Comment by crashmajstr** [comment]
Hello @Fire3galaxy just wanted to inform you that this issue has been fixed.
Have a nice day!
Josef
