### ISSUE TITLE
Ubuntu 18.10 do not show fill opacity on png

### ISSUE THREAD

**Issue by utrumo** [avocode/avocode#2281]
* **Version**: 
Version: 3.6.7

* **Web/Desktop**:
Desktop

* **Platform/Browser**:
Ubuntu 18.10

pvvnxdementor5@gmail.com

I have an png with opacity on my layout.
Avacode does not show it in css.

**Comment by utrumo** [comment]
[do not show fill opacity](https://ibb.co/SyGymb6)
[fill opacity 60% in photoshop](https://ibb.co/nzHfwp6)
Please save images, on this image hosting its will be removed in a month.

**Comment by crashmajstr** [comment]
Hello @dementor5, thank you for reaching out. I am sorry for the inconvenience. 
Please, would you mind sending me a link to this file in Avocode (avocode share link)? 
I'll take a look what went wrong.
Thanks

**Comment by crashmajstr** [comment]
Hello @dementor5, thank you for reaching out. I am sorry for the inconvenience.
Please, would you mind sending me a link to this file in Avocode (avocode share link)?
I'll take a look what went wrong.
Thanks

**Comment by utrumo** [comment]
Hellow, @crashmajstr!
There is a link, but only preview (comment and prototype does not work now):
https://app.avocode.com/view/ffb8edd5137a491ca834181549eaf465/_/preview

**Comment by crashmajstr** [comment]
Hey, thanks for sending this over I'll take a look and let you know.

**Comment by crashmajstr** [comment]
Ok, I've instigated the file, actually, there is no opacity usage in your file. You just used the fill option and added a 60% of fill, that's something we can't display in the CSS. If you use the opacity option it will appear in the CSS correctly.

<img width="329" alt="screenshot 2019-01-17 10 46 36" src="https://user-images.githubusercontent.com/18406167/51309655-307bdc00-1a45-11e9-8462-f069ea906f13.png">

Let me know if that helps. 
Best,
Josef

**Comment by utrumo** [comment]
@crashmajstr, i know that is not opacity, it's fill. I wrote about it in the second message.

You could specify in the app that fill is used and in css you can't correct to repeat it, but you have can try to use opacity with some values. Now avacode tells nothing about it at all.

I considered avacode as photoshop alternative, but to work without it is impossible. Yet avacode cannot replace photoshop because does not show some important values, like fill or can't export images without shadow, if in design it has.

**Comment by crashmajstr** [comment]
Actually, when you use the fill function it isn't a valid CSS property like opacity is, in photoshop it behaves like a normal image so if you want to see the correct value of opacity you should use the opacity.

Regarding the export of images without additional effects, that something we want to implement in the future, please if you can, you can upvote this feature on our UserVoice here: 
https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/10285095-layer-effects-needs-to-be-turn-off-and-turn-on-lik

And hopefully, we'll release it soon :)

**Comment by utrumo** [comment]
Thanks, I voted for it.

The model was drawn by the designer, I received it as is. I have no opportunity to look that something went wrong because the application of it simply does not show. :(

**Comment by crashmajstr** [comment]
I understand it's ok I've just tried to explain it to you a bit better :) So next time you can advise your designer better.
Let me know if you have any other questions, comments or concerns in the future.
