### ISSUE TITLE
Remember pixel checker opacity settings

### ISSUE THREAD

**Issue by mhlozek** [avocode/avocode#2284]
When I close and open pixel checker window I have to set opacity again and again.
Could you add feature to save this settings?

**Comment by crashmajstr** [comment]
Hello @mhlozek thanks for reaching out. 
It sounds like a reasonable request. If you would like to see this feature in Avocode, please create a feature request on our UserVoice, so other users can vote for this idea as well. We will also notify you when the status of the feature request changes. The more votes your idea has, the more likely we'll prioritize it:

https://avocode.uservoice.com/forums/277080-feature-voting
