### ISSUE TITLE
Bad position of image

### ISSUE THREAD

**Issue by mhlozek** [avocode/avocode#2285]
Avocode 3.6.7 (Windows, desktop)

Image in imported XD file is positioned incorrectly 
(see attached image with "forklift" - in Adobe XD is forklift visible, in Avocode is cropped)
![bug-avocode](https://user-images.githubusercontent.com/2743172/50638227-45dd0a80-0f5d-11e9-97e0-d432c497ef07.png)
![bug-xd](https://user-images.githubusercontent.com/2743172/50638228-45dd0a80-0f5d-11e9-9aba-f75365ea8820.png)

XD source file is available on https://1drv.ms/u/s!AlWfyeLZDhoRla4D8LLwMxnj4ndulQ

**Comment by crashmajstr** [comment]
Hello @mhlozek, thank you for reporting this and I am sorry for the inconvenience. I reproduced this error on my end too so, I raised an issue for our dev team for further investigation. 
I'll keep you updated regarding the fix.
Best,
Josef

**Comment by crashmajstr** [comment]
Hey there. I just wanted to follow up on this and let you know that the problem you reported should be fixed now. You need to upload the design to Avocode again in order to see the improvements.
