### ISSUE TITLE
вылетает

### ISSUE THREAD

**Issue by artem67801** [avocode/avocode#2286]
---
* **Version**: 3.0.0
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 500373
---
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new ArrayBuffer (C:\Users\arti2\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\core-js\modules\_typed-buffer.js:247:14)
    at Rendering (C:\Users\arti2\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\@avocode\rendering-emscripten\rendering-asm.js:1:23650)
    at C:\Users\arti2\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:1122
    at Promise (<anonymous>)
    at C:\Users\arti2\AppData\Local\avocode\app-3.0.0\resources\app.asar\node_modules\@avocode\stage\dist\rendering.js:1:637
    at <anonymous>
```

**Comment by crashmajstr** [comment]
Hello @artem67801 , thank you for reporting this.
I am sorry that you had a problem with our program, but I can see that you have an outdated version. Please, try to upgrade it and let me know if the problem appears again.  

https://avocode.com/download

**Comment by artem67801** [comment]
I have 32 bit windows

07 січня 2019, 10:10:44, від "Josef Kettner" <notifications@github.com>:

Hello @artem67801 , thank you for reporting this.
I am sorry that you had a problem with our program, but I can see that you have an outdated version. Please, try to upgrade it and let me know if the problem appears again.

https://avocode.com/download

**Comment by crashmajstr** [comment]
Ah, ok I understand, please keep in mind that we no longer support this version anymore.
If you use the 32-bit windows you can use the up to date web app at app.avocode.com

Have a nice day,
Josef

**Comment by artem67801** [comment]
I have 4 GB of RAM, and the browser hangs, what else would you advise?

8 січня 2019, 12:07:04, від "Josef Kettner" <notifications@github.com>:

Ah, ok I understand, please keep in mind that we no longer support this version anymore.
If you use the 32-bit windows you can use the up to date web app at app.avocode.com

Have a nice day,
Josef
