### ISSUE TITLE
Update Notice

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#229]
I saw you released 2.1.0. I got no email notification for that, and I can't find the changelog anywhere.

Also, on madebysource.com it states that Avocode is currently on version 1.1.1.

**Comment by petrbrzek** [comment]
- Avocode version on MadeBySource fixed
- Working on the changelog right now

**Comment by petrbrzek** [comment]
Also there is an article about the new version. https://medium.com/avocode-stories/avocode-2-1-0-with-new-pricing-slack-integration-notes-and-more-5b3a7d3ecfbe

**Comment by tomashanacek** [comment]
http://changelog.avocode.com/
