### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by olkhovikmi** [avocode/avocode#2293]
---
* **Version**: 2.18.2
* **Web/Desktop**: Desktop
* **Platform**: win32
* **Avocode UID**: 513588
---
```
Error: getaddrinfo ENOTFOUND preview-production.avcd.cz preview-production.avcd.cz:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

**Comment by crashmajstr** [comment]
Hello @olkhovikmi , thank you for reaching out. I am sorry for the inconvenience, but it looks like you have an outdated version of Avocode. Can you please update to the latest if the problem is the same? You can download the latest version at https://avocode.com/download
Thank you.
Best,
Josef
