### ISSUE TITLE
Export Image error

### ISSUE THREAD

**Issue by mandeep-pixel2html** [avocode/avocode#2299]
* **Version**: 3.6.10

* **Web/Desktop**: Both

* **Avocode e-mail**: mandeep@pixel2html.com

When I export an image having text in SVG format. I get the Image but without text. I'm sharing the [gif](http://recordit.co/oI6gQXLjNF) related to this issue. Please check and let me know If I did something wrong, Otherwise, Please take care of this issue asap. 

Thanks
Mandeep

**Comment by crashmajstr** [comment]
Hello @mandeep-pixel2html thank you for reaching out. 
Unfortunately, we currently don't support export of text layers into SVG, but it's something we want to add in the future. 
So, it's not an issue but more of a feature request which you can upvote here:
https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7741200-allow-svg-export-of-type-layers-especially-for-ic
Best,
Josef
