### ISSUE TITLE
Fail to open file

### ISSUE THREAD

**Issue by alex-misch** [avocode/avocode#2309]
---
* **Version**: 2.17.1
* **Sketch plugin version**: 51.0.0
* **Web/Desktop**: Desktop
* **Platform**: darwin
* **Avocode UID**: 602865
---
```
Error: Could not download metadata (revision=46375831)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:1:1072324
    at <anonymous>
```

**Comment by crashmajstr** [comment]
Hello @alex-misch  it looks like that you have an outdated version of our app. Please, download the latest one at avocode.com/download and let me know if the error still happens.
Best,
Josef
