### ISSUE TITLE
Uppercase fonts for .xd file

### ISSUE THREAD

**Issue by morcegon** [avocode/avocode#2315]
* **Version**: 4.4.2

* **Web/Desktop**: Desktop

* **Platform/Browser**:

* **Avocode e-mail**: renan@raessolucoes.com.br

The some uppercased fonts in my .xd file aren't uppercase in Avocode.

These are in XD file
![Screenshot from 2020-02-28 09-08-44](https://user-images.githubusercontent.com/31614/75547586-fb90d580-5a09-11ea-80f5-ce80fb6159f9.png)

These are in Avocode
![Screenshot from 2020-02-28 09-08-52](https://user-images.githubusercontent.com/31614/75547612-0e0b0f00-5a0a-11ea-9432-616229436949.png)

**Comment by jakubzitny** [comment]
We're addressing this via our support..
