### ISSUE TITLE
Add fast search in app.

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#233]
I'd like just to press cmd+f and type document name to open any document in new tab fast.

**Comment by magiclin99** [comment]
Our team really really really needs 'search' function.
We have 70+ PSD files.
You can imaging that how much time we spent on finding a PSD q_q

**Comment by magiclin99** [comment]
cool!! the search function was added in latest version.

**Comment by vojtatranta** [comment]
So it is implemented.
Thank you for your input.
