### ISSUE TITLE
Accepted invite but on a wrong account

### ISSUE THREAD

**Issue by neiloox** [avocode/avocode#236]
I get an email of inviting to team on the account A, and I click the "ACCEPT INVITE" link.
But if my browser is already login the account B before I clicking the link, account B will be join to that team, not account A.
It should verify the login account and the invited account are matched or not, and must not join a wrong account into the team.

Please check this issue. 
Thank you.

**Comment by rychlis** [comment]
We should definitely not auto-accepts invites when you are logged in, it's now in our internal task list for the web manager. Thanks for the report

**Comment by jakubzitny** [comment]
Irrelevant as of http://app.avocode.com.
