### ISSUE TITLE
Resize slices

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#240]
I just tried to use the slice tool. It seems pretty useful but I can't find out how to resize my slize. Any tips on that? Is such a thing implemented?

**Comment by dongepulango** [comment]
+1 on this

**Comment by rychlis** [comment]
This is not implemented at this moment, slice tool would definitely need some improvements including resizing. Here is an [uservoice idea](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7846377-be-able-to-resize-slices-created-in-avocode), I'm closing this issue as feature requests should be in uservoice only
