### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by liviathi** [avocode/avocode#245]
Describe your problem here…

-----

```
RangeError: Maximum call stack size exceeded


```

**Comment by petrbrzek** [comment]
We need more info. How did it happen?

**Comment by petrbrzek** [comment]
@liviathi Ping.

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
