### ISSUE TITLE
Sketch pages can't be deleted

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#249]
There is no option to delete a Sketch page and the CMD+DEL doesn't work

**Comment by BrandonLive** [comment]
My designer has encountered this problem. In her case, she deletes pages from the project in Sketch and then uses Avocode's Sync plug-in, but the deleted pages remain (which has led to a lot of clutter of old and new versions of things mixed together).

**Comment by petergeller** [comment]
Can you please fix that task, because i have the same problem and because of a wrong sync update project files from sketch are now displayed in the wrong project.

**Comment by marekhrabe** [comment]
Until this is implemented, you can always contact support on support@avocode.com and we can perform the task in our admin. Also, we are slightly changing how we handle Sketch documents and this might not be an issue in some time. We will keep you posted here

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
