### ISSUE TITLE
Values are really low-res when i make them bigger

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#25]
- Description: Consider using svg for icons and valuesfont but it should be "Gotham medium"
- Steps to reproduce:
- Expected result:
- Actual result:
- OS and app versions: Avocode 0.5.0, OS X

![screenshot](https://upx.cz/bacab9apo7gsn6px5tbrpi9qj3xh0n34spsshpmx)

**Comment by tomashanacek** [comment]
Fixed in Avocode 1.0
