### ISSUE TITLE
App drag and drop, pre-filled name cut-off

### ISSUE THREAD

**Issue by matthojo** [avocode/avocode#250]
**Reproducibility:** High
**Description:** When importing a file by dragging on the app window, the suggested 'design name' is incorrectly filled if the name has a `.` in it. E.g `01. some name.psd` 
**Steps to reproduce:**
1. Drag `.psd` which has a name with a `.` in it over Avocode
2. Design Name is pre-filled with contents before first `.`
**Expected result:** The name should be everything before the last `.`.
**Actual result:** The name is everything before the first `.`.
**OS and app versions:**
* Mac OS X 10.10
* Avocode 2.1.0

I think a (JS) regex like `([^\/]+)(?=\.\w+$)` should capture everything before extension.

**Comment by jankuca** [comment]
Thanks for reporting. It is going to be fixed in the next release.

**Comment by rychlis** [comment]
This should be fixed in Avocode 2.2.0, feel free to re-open the issue if you encounter this again in the latest version.
