### ISSUE TITLE
Bad rendering of psd clipping mask of layers with different sizes

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#253]
Web (PSD): ![screenshot 2015-05-15 14 58 09](https://cloud.githubusercontent.com/assets/1819747/10692907/e4cbb590-7994-11e5-924c-2211e4594f22.png)
App: ![capture image](https://cloud.githubusercontent.com/assets/1819747/10692908/ea47af74-7994-11e5-9c7a-6a343ba1b136.png)

**Comment by rychlis** [comment]
This seems to be related to rendering clipping mask of layers with different sizes. We can still reproduce this in latest version (2.3.2).

**Comment by n0rule5** [comment]
Is this issue (and #432) actively being worked on? I have a lot of layers that uses clipping masks and they're rendered incorrectly or completely missing from the layers panel. I'm using version 2.4.5

**Comment by blorenz** [comment]
Clipping masks are still an issue and a PITA with Avocode.

**Comment by n0rule5** [comment]
I would consider this bug major/critical and yet it's still not fixed. The clipped layers are converted so badly, at best the clipped layers are shifted around and randomly cut off, and at worst it renders other layers inside the mask. Here's an example: The grey background for the title is clipped to the white box with rounded corners, but gets shifted when converted into Avocode for inspection.

![image](https://cloud.githubusercontent.com/assets/1464003/12952835/f69c1b5a-cfe5-11e5-87f8-4fa7e8f46110.png)
![image](https://cloud.githubusercontent.com/assets/1464003/12952862/0b507a6e-cfe6-11e5-93e8-0ef066d1acb3.png)

**Comment by blorenz** [comment]
Can we get this issue opened, @rychlis? There is significant difference in an actual PSD that uses clipping masks to what Avocode outputs to the point that Avocode is only useful in very limited capacity.

**Comment by rychlis** [comment]
yes in fact we've just released Avocode 2.6.0 that should fix this issue
