### ISSUE TITLE
Wrong border-color

### ISSUE THREAD

**Issue by Rad1calDreamer** [avocode/avocode#259]
![capture image](https://cloud.githubusercontent.com/assets/7055577/7722689/36c61b80-feeb-11e4-918a-1c1161aae4da.png)

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
