### ISSUE TITLE
TooIbar icons are gone

### ISSUE THREAD

**Issue by enzy** [avocode/avocode#264]
![20150522-151318](https://cloud.githubusercontent.com/assets/809888/7771101/36c314ca-0095-11e5-8a1b-e87f6fb0d663.png)

**Comment by rychlis** [comment]
Does it still hapen in 2.2.0?

**Comment by enzy** [comment]
Yes

**Comment by rychlis** [comment]
What is your Windows version? Did the icons never work on your machine or did it work well previously?

**Comment by enzy** [comment]
Windows 8.1 Pro x64, eng

They worked in some previous version, but don't remember which one exactly.

**Comment by rychlis** [comment]
Could you send me a new screenshot with 2.2.0 please? It might help to remove .avcd folder from your home folder (it will be a hidden folder)

**Comment by enzy** [comment]
Removed .avcd folder but no change:
![image](https://cloud.githubusercontent.com/assets/809888/8133615/b7d72e94-1129-11e5-8982-6469bbe1f614.png)

**Comment by petrbrzek** [comment]
Mega weird shit. I think it'll be better to come to your HQ to debug it. :)

**Comment by enzy** [comment]
Any change to debug it by myself in the meantime? Like DevTools enabled build or smth...

**Comment by enzy** [comment]
After installing 2.2.1 over existing installation, icons are back!

**Comment by rychlis** [comment]
OK, interesting, I think the icon files were not properly installed before. I will close the issue then, we will definetely re-open it if someone experiences this issue again.

**Comment by enzy** [comment]
https://code.visualstudio.com/Docs/supporting/FAQ#_icons-are-missing
