### ISSUE TITLE
Sketch: Upload progress doesn't indicate real progress

### ISSUE THREAD

**Issue by enzy** [avocode/avocode#272]
When uploading a big design, upload stuck at 100% for about 20 minutes, before it finish.

**Comment by marekhrabe** [comment]
We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs including this one. We will notice you when the new version is released.

**Comment by enzy** [comment]
Great! It's a major issue for us (designers spent hours uploading with locked workspace - unable to work)

**Comment by marekhrabe** [comment]
I feel the pain too. I hope you will like our new plugin. We will keep you posted about its release

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
