### ISSUE TITLE
blending issue with Sketch

### ISSUE THREAD

**Issue by ericpringels** [avocode/avocode#277]
Seems there is a bug with "multiply" blending mode (Sketch 3.3.2 and avocode 2.1.0)
![capture d ecran 2015-06-04 a 15 15 31](https://cloud.githubusercontent.com/assets/7203126/7985994/10408810-0ad5-11e5-981e-3a3f0edd1dfe.png)
in avocode web
![capture d ecran 2015-06-04 a 16 13 13](https://cloud.githubusercontent.com/assets/7203126/7985998/138f8d2c-0ad5-11e5-90b8-597b554818f7.png)
in avocode mac app
![capture d ecran 2015-06-04 a 16 17 30](https://cloud.githubusercontent.com/assets/7203126/7986018/3cc2321c-0ad5-11e5-9fe9-0d8be2910dcd.png)
in sketch app

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
