### ISSUE TITLE
Avocode crash

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#28]
- Reproducibility: Always
- Description: I don't know why, but my Avocode crash everytime. error: Your avocode has gone bad
- Steps to reproduce:
- Expected result:
- Actual result:
- OS and app versions: Avocode 0.5.0, OS X 10.9.4

**Comment by petrbrzek** [comment]
Does this issue still occur with current version of Avocode?

**Comment by martijneerens** [comment]
I have the same issue: Everytime I open a design in the Mac App (1.0.0) on OSX 10.10.1 the loading screen keeps showing indefinitely and i get the 'your avocode has gone bad' error notification.

OS and app versions: Mac App (1.0.0) on OSX 10.10.1
