### ISSUE TITLE
SVG Output should include XML declaration

### ISSUE THREAD

**Issue by MatthewDaniels** [avocode/avocode#289]
We use a gulp task to convert SVG to base64 encoded icons within CSS (as well as convert to PNG for fallback).

SVGO and SVGMIN both require to have the XML definition at the top of the SVG (` <?xml version="1.0" encoding="utf-8"?> `). Any chance we could get the XML definition included in the SVG for export (or an option in preferences to turn it on and off?):

**Comment by petrbrzek** [comment]
I think we could add it as an option to Settings. What do you think @patrikholcak?

**Comment by MatthewDaniels** [comment]
Great! Thanks for the quick responses!

**Comment by patrikholcak** [comment]
I’ll look into it.

**Comment by patrikholcak** [comment]
Added in 2.3.0
