### ISSUE TITLE
Issue with background-gradient

### ISSUE THREAD

**Issue by ihorml** [avocode/avocode#290]
Hey guys. Generated styles for element on psd wrong. 

This is how it looks on PSD - https://www.dropbox.com/s/d33s4auoqo50wgz/Screenshot%202015-06-11%2013.14.07.png?dl=0

And this is generated style on Avocode - https://www.dropbox.com/s/rpc1mm8d9qf0pt2/Screenshot%202015-06-11%2013.14.43.png?dl=0

Should I send you PSD to test it and fix this issue?

**Comment by rychlis** [comment]
Hi, please send us the PSD to team@avocode.com, that would be great :)

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by NiB18** [comment]
Hi, I'm using Avocode 2.11.01 and gradient generated code still seem to be wrong. Let me know if you need more details and I can supply.

Thanks for support!

**Comment by connor-bean** [comment]
Hey @NiB18  -

Would you be able to send us the PSD to team@avocode.com and reference this Github issue in your email? 

Thanks!
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.12, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please comment on it if you’re still experiencing this problem in Version 2.12.

Thanks!
Connor, Avocode Support
