### ISSUE TITLE
Can't open pages/artboards in new tabs

### ISSUE THREAD

**Issue by BrandonLive** [avocode/avocode#295]
I'd find it a lot easier to work with the app if I could CTRL+Click or right-click -> Open in New Tab on pages and/or artboards from the Project Manager view. Instead, I currently have to open new tabs and navigate through the Project Manager (which is quite cumbersome) to get to each thing I want to open.

**Comment by jakubzitny** [comment]
This should be already possible with CMD on a Mac and Ctrl on Windows and Linux. Works in both Desktop app and web (where it opens new browser tab).
