### ISSUE TITLE
Avocode 2.2 Mac 10.10.1 - Your Avocode has gone bad

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#296]
Every mouse click throw this error.

**Comment by petrbrzek** [comment]
We definitely need more information. Does it happen all the time or only in opened design? Did you try to remove `.avcd` folder?

**Comment by polikin** [comment]
It happen all the time. I will try to remove the `.avcd` folder.

**Comment by rychlis** [comment]
Did removing .avcd help? Can I close this issue?

**Comment by polikin** [comment]
sorry. I didn't try yet. I'll try it tomorrow and I let you know.

**Comment by rychlis** [comment]
I am closing this issue, re-report it in case you can reproduce it in latest version
