### ISSUE TITLE
Please consider bringing back designer accounts

### ISSUE THREAD

**Issue by tgines** [avocode/avocode#297]
One of my designers is not a coder in any sense and doesn't need access to many of the features of avocode. I still have to pay for her account just to upload designs to a folder. Could we bring back the designer accounts and just limit some of the functionality of the desktop app for those users? I find it wasteful for her to have the paid account.

**Comment by helloiamvu** [comment]
I totally get you point. We might bring back this user type in the future. I've created an Uservoice Feature Request for this. Feel free to up-vote it: http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/8461420-add-lite-users-to-avocode
