### ISSUE TITLE
Avocode crashes when opening certain PSD files

### ISSUE THREAD

**Issue by rafalenden** [avocode/avocode#30]
- Reproducibility: Rare
- Description: Avocode crashes when opening certain PSDs
- Steps to reproduce:
  1. Sync PSD file in Photoshop (14.2.1 x64 CC)
  2. Open that file in Avocode 0.5.0
  3. Avocode crashes: http://prntscr.com/4jiz8z
- Expected result:
- Actual result:
- OS and app versions: Avocode 0.5.0, OS X

**Comment by petrbrzek** [comment]
We tested it today and it works. Closing this issue.
