### ISSUE TITLE
SVG Exporting Canvas Size

### ISSUE THREAD

**Issue by MatthewDaniels** [avocode/avocode#303]
When exporting SVG - either individual elements or grouped - if a path has a stroke-width that pushes part of the stroke outside the viewbox then cropping of the element occurs.

To reproduce, create a circle 25px x 25px in your favourite image manipulation tool (Sketch or Photoshop), add a 2 pixel stroke. When you export it, the viewBox attribute will be : "0 0 25 25" which will cause 1px on each side to be cropped. The viewBox attribute should adjust to "-1 -1 27 27" - which is the viewable area.

**This will get cropped:**
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Avocode 2.1.0 - http://avocode.com -->
<svg height="25" width="25" xmlns:xlink="http://www.w3.org/1999/xlink"  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 25 25">
    <circle cx="12.5" cy="12.5" r="12.5" stroke-width="2" stroke="#ffffff" fill-opacity="0.2" fill="#000000" fill-rule="evenodd"/>
    <path stroke-linejoin="miter" stroke-linecap="round" stroke-width="3" stroke="#ffffff" fill="none" fill-rule="evenodd" d="M 12.5 8.5 L 12.5 16.5" />
    <path stroke-linejoin="miter" stroke-linecap="round" stroke-width="3" stroke="#ffffff" fill="none" fill-rule="evenodd" d="M 16.5 12.52 L 8.5 12.52" />
</svg>
```
Simply updating the viewBox of the above will fix the issue.

Not sure if we are setting it up incorrectly or not, but it would be really nice to not have to manually adjust the viewBox (or import the SVG into illustrator to fix).

**Comment by marekhrabe** [comment]
I can reproduce the issue myself and we will fix the problem in next updates. Thanks for reporting

**Comment by MatthewDaniels** [comment]
Great! Thanks for the quick responses! Look forward to the update... :)

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
