### ISSUE TITLE
Deleted sketch artboards display incorrectly on the web

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#304]
When we delete an artboard in Sketch and sync with Avocode with the Sketch plugin, the artboard is still available in Avocode and there does not appear to be a way of deleting it.

**Comment by dariusb** [comment]
We have the same problem. How we can remove single artboard, not whole project, in Avocode?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
