### ISSUE TITLE
Avocode Plugin is not working for the new Photoshop version!

### ISSUE THREAD

**Issue by vitorfernandes** [avocode/avocode#307]

**Comment by marekhrabe** [comment]
I'm building and testing the plugin right now. It should be released soon

**Comment by rychlis** [comment]
Avocode Photoshop Extension 2.2.0 has been released, you can download it here https://manager.avocode.com/downloads/

**Comment by vitorfernandes** [comment]
awesome!

**Comment by vitorfernandes** [comment]
the only thing you need to do is change this:

![screen shot 2015-06-19 at 10 40 49 am](https://cloud.githubusercontent.com/assets/11338156/8254539/b953fb58-166f-11e5-8946-f51660d3bc7a.png)


It's 2015 right now. :P

:)
