### ISSUE TITLE
I can't open my synced design

### ISSUE THREAD

**Issue by vitorfernandes** [avocode/avocode#308]
One of my files is been processed indefinitely. And I can't open it. How I can solve it?

![screen shot 2015-06-18 at 11 34 56 am](https://cloud.githubusercontent.com/assets/11338156/8233763/5deb9ed6-15ae-11e5-886f-cf6d9bd24a4e.png)

**Comment by rychlis** [comment]
It looks like this design was not uploaded completely by the Photoshop extension. You will need to upload the design again if that is possible.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
