### ISSUE TITLE
App freezes for 1-3 mins when returned from long inactivity

### ISSUE THREAD

**Issue by enzy** [avocode/avocode#310]
![screen](http://msimek.cz/b35241dfe2.png)

When a freeze (like timeout or heavy background work) is away the app works fine again.

Win 8.1 x64, Avocode 2.2.1

**Comment by enzy** [comment]
Still happening in the 2.3.2 version

**Comment by benceg** [comment]
I can confirm this is still happening in Avocode 2.4.2, running on both Windows 8.1 and Windows 10.

Sometimes the crash notice is not displayed, but the app locks for approximately 1 minute. This can be after even 30 seconds of inactivity after alt-tabbing into an IDE.

Machine's a high-spec Asus RoG G750JZ, if that helps to solve the issue.

**Comment by vojtatranta** [comment]
this should be fixed in newer version, please update
