### ISSUE TITLE
Avocode generates a wrong name for the font, including the Google Font link

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#312]
As you can see on the first screenshot (see the attached file 'screenshot-1.png'), it says 'PTSans' while it is 'PT Sans Narrow'. Also, I made a second screenshot - of Google Fonts page - with 'PT Sans' family to demonstrate that 'PTSans' and 'PT Sans Narrow' are looking absolutely different (see the file 'screenshot-2.png').

P.S.: Besides, if one wants to use Avocode`s quick-link to Google Fonts, he get to page with the wrong font - 'PT Sans' instead of 'PT Sans Narrow'.

https://avocode.zendesk.com/attachments/token/ESOGfoQQFWdQluh8EBAlWaydY/?name=screenshot-1.png

https://avocode.zendesk.com/attachments/token/706vYDZyGGtNNJXHwuW6CPQAW/?name=screenshot-2.png

**Comment by markst** [comment]
+1. The font weight is not catered for. 
i.e I'm using Avenir typeface in Sketch, with 'Light' weight:
![image](https://cloud.githubusercontent.com/assets/274318/8547023/d7aba1a8-24b3-11e5-9ca9-b4827ab77cca.png)

whilst Avocode generates without the weight:
![image](https://cloud.githubusercontent.com/assets/274318/8547030/e3ff5b3e-24b3-11e5-9ed9-1ee62f5ea9eb.png)

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
