### ISSUE TITLE
Crushreport.

### ISSUE THREAD

**Issue by AlexeyMihaylov** [avocode/avocode#316]
Describe your problem here…

-----

```
TypeError: Cannot read property 'guide' of undefined
  at t.handleRulerMouseDown_ (/home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/@avocode/guides/lib/rulers.js:1:7175)
  at HTMLDivElement.<anonymous> (/home/alexey/Рабочий стол/Avocode/resources/app.asar/node_modules/@avocode/guides/lib/rulers.js:1:252)

```

**Comment by AlexeyMihaylov** [comment]
And I think I can reconstruct how this error occured :)

**Comment by petrbrzek** [comment]
@AlexeyMihaylov Please! I'm thrilled to hear it. :)

**Comment by AlexeyMihaylov** [comment]
Here: https://youtu.be/sfPUdw6IjFo

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
