### ISSUE TITLE
'Copy <p> <br>' on Linux doesn`t work.

### ISSUE THREAD

**Issue by AlexeyMihaylov** [avocode/avocode#317]
When I select paragraph and choose "Copy p br", it copies only p (without br) - see the screenshot.
If you want me to, I can send you the psd-file this error occures.
![screenshot](https://cloud.githubusercontent.com/assets/12910943/8288048/48ecf176-191c-11e5-9a79-17fff09e9b96.png)

**Comment by rychlis** [comment]
The <br> will only be there if you have newlines in the text. It looks like this paragraph doesn't have any newlines, it's just text wrapping.
