### ISSUE TITLE
Font family detection

### ISSUE THREAD

**Issue by vahidebr** [avocode/avocode#32]
- Reproducibility: Always
- Description: Avocode couldn't recognise the font family of a layer. Example: it just detects the "Gotham" font but it should be "Gotham medium"
- Steps to reproduce:
- Expected result:
- Actual result:
- OS and app versions: Avocode 0.5.0, OS X

![screen shot 2014-09-05 at 11 13 36 am](https://cloud.githubusercontent.com/assets/7588167/4159120/f97bd542-3499-11e4-8402-b88f3cd33ecb.png)

**Comment by lucien144** [comment]
@patrikholcak I think this is still actual, or more likely there's a bug. I have a PSD where I have these fonts: http://d.pr/i/13bjP but the code inspector gives me only 2 fonts: ```font-family: HelveticaNeueLTCom; font-weight: 400;``` and ```font-family: HelveticaNeueLTCom;```, where ```font-family: HelveticaNeueLTCom; font-weight: 400;``` is Roman face and the other is all remaining which is bug...

I would still consider to implement #19 so users can avoid this bug by switching font naming convention in Avocode's preferences.
