### ISSUE TITLE
Sketch 3.3.2 crashes syncing a file with Sync Plugin 2.0.6

### ISSUE THREAD

**Issue by mochabcha** [avocode/avocode#344]
My coder instincts tell me that the problem has to be related to my file.  My designer instincts tell me "I want this working right now!"  I'm a little conflicted right now.  However, having **no backup method to get this sketch file uploaded to Avocode** is really putting me out right now so I would appreciate:

**first a way to get my file uploaded to my account** and 
secondly, a way to get this problem solved so I can work faster.

**I want to get a Business account but** then this happened and now I'm thinking twice.  This product is perfect supporting our new Sketch workflow but **I need support** to come with this subscription if there's going to be problems like this to deal with.

**Comment by mochabcha** [comment]
Is there someone I can send my file to that can manually upload it to my account?

**Comment by rychlis** [comment]
Hey, yes please send the file to team@avocode.com and we will help you out

**Comment by mochabcha** [comment]
Awesome, thank you.

**Comment by mochabcha** [comment]
I sent that file your way, please be on the lookout for it.

**Comment by mochabcha** [comment]
wait….I”m running into a problem with the plugin in which I can’t upload one of my sketch designs….have I hit some kind of account limit?  I’ve uploaded a sketch file of this size twice before….but am I at my account’s size limit?

**Comment by rychlis** [comment]
It might help to:
1. In sketch menu open Plugins -> Reveal Plugins Folder...
2. Remove `avocode.token` file

Also please send us `avocode-node.log` and `avocode.log` files from this folder to team@avocode.com

Thanks

**Comment by mochabcha** [comment]
Ok I'm currently traveling. I keep my sketch plugins folder synchronized
via Google drive so i'll send you links to those files and remove the token
file but I can't test it until I get to a computer tonight.

https://drive.google.com/open?id=0B_x0w7hahgJHRV9RQnhKdkx1aWM

https://drive.google.com/open?id=0B_x0w7hahgJHYnhZbnhISTJaZGc

**Comment by SorbieCo** [comment]
Same issue - Sketch 3.3.2 with Avocode plugin 2.0.6

Crashes Sketch every time the Avocode sync starts (performing step 1 of 3). 

Tried removing the token file, I had to re-authorize the account through the Acocode site like a new install but crashing still occurs same as before. Sketch file is 72.1 MB. 

Please let me know if you have any other information or suggestions. 

Cheers, 

Eric

**Comment by mochabcha** [comment]
Yea, exact problem.  I've done all those things and gotten no where.  I'm still waiting on the team to maybe upload my file manually because they've also disabled the ability to upload directly via sketch....although this functionality is precisely why I'm paying for this service.

**Comment by rychlis** [comment]
@mochabcha for some reason, gmail marked your email as spam and I've only found the message now. I've sent you an email reply

@SorbieCo could you please send us the sketch file to team@avocode.com as well? Thanks!

**Comment by mochabcha** [comment]
Its shared with both teams now, team@madebysource.com and team@avocode.com <mailto:team@avocode.com>

**Comment by SorbieCo** [comment]
OK, I've sent you guys an email with a link to the Sketch file. 

Let me know if you need anything else in the meantime. 

Cheers and thanks for your help on this!

Eric

**Comment by mochabcha** [comment]
I've sent the invitation link to team@avocode.com; I'm just waiting on them to accept it.  Its already available to Source.

**Comment by rychlis** [comment]
We have access to both sketch files now, thanks. We're going to investigate what happens and try to fix it tomorrow (Monday).

**Comment by mochabcha** [comment]
Thank you so much.  Please upload it into my account as soon as you can though.  Even if you don’t figure the problem completely, I need my contractors to access those assets.

**Comment by rychlis** [comment]
I've sent an email to both of you with links to synced design. I was able to sync both design (on MB Air Mid 2011) so I've requested more information in the email from you as well in order to be able to replicate the issue. It seems like these are two different problems though.

@mochabcha's design is 800MB in size which is very large, it looks like the plugin uses a lot of resources (especially RAM) in the process which should be improved by us. The computer was unusable most of the time when syncing which is not good. It would also help to add an option to sync just selected artboards which is something we would like to implement soon

@SorbieCo is probably a different issue as the file is not that large (78MB) and the sync worked for me without issues, I've requested more information and log files in the email

**Comment by mochabcha** [comment]
The link I was sent goes to a 404 and I can't find any new designs. Are you
sure it completed without fail? You said the link was to assign a design to
a project, however the plugin asks this question before upload. I assume
you're using a different method...but then I would ask, "where do you find
unassigned designs?"

I also agree on all points about plugin functionality regarding file
processing. I work with big files. It would be useful if the plugin handled
it's own file processing without completely disabling Sketch with a modal
dialog.

**Comment by SorbieCo** [comment]
I have sent back all relevant information via email as stated. 

Also, I'm purposefully testing this out with a small project. My project files also tend to be in the GB range and 75+ pages just so you know. I'm not planning on moving projects like that over until a successful workflow is established. 

Cheers, 

Eric

**Comment by mochabcha** [comment]
I would like to give an update on this issue. The team uploaded the file to my account, however the fonts were all wrong as they did not have access to the original fonts. It's understandable I should have included the fonts that were in the original project however I'll probably also submit this is a feature request: font replacement.I still have no idea why some things don't upload and some things don't open. 

So if there's any more information I can provide or that you can provide I'll be glad to help.

**Comment by mochabcha** [comment]
Ok i have an update here.  I successfully got that file to upload.  I had to update the design with new colors and fonts and things.  In addition, I also removed these dev notes layers that I put all over the place and I removed all the slices I put in that design.  After that, it uploaded just fine.

3 Hypotheses:

1.  Slices or Nested Slices might be incompatible in some way with Avocode.  This one I feel has the most legitimacy.
2.  There was a bad font file somewhere, however this is kinda loose because one was a google font and the other was Museo.
3.  Something about the dev notes layers was causing a problem.  I also believe this one to be a shaky hypothesis because the layers were just highly duplicated symbols.

If you need anything else from me to explore these avenues, just let me know.

**Comment by mochabcha** [comment]
I've got other Sketch files now that crash Sketch every time I try to synchronize to Avocode with that plugin.  I have no idea what the problem is and I cannot justify this workflow.  I've lost trust in this system and I haven't the time to keep chasing down bugs.  This thing isn't ready for a Sketch integration and really shouldn't be advertised that way.

**Comment by marekhrabe** [comment]
We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs and crashes. We will let you know when the new version is released. I'll keep just one issue open about this problem: #464
