### ISSUE TITLE
Can't open synced files

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#354]
Designer tried so sync file and internet connection was lost. 
Now, he sees project as synced, but I can't open it. 
Then trying to open, i get message: http://prntscr.com/7tnqbt
Tried even avocode reinstall.

New projects works well (but now i have to reimport all variables and etc)

It's a pity, because we bought several accounts of avocode.

**Comment by rychlis** [comment]
I can see you use Sketch only, in that case this was probably an issue with the extension that should be fixed by resyncing the document. Or do you still have this issue with some designs? In that case please share the design name with us at team@avocode.com

Thanks and sorry for the delayed answer

**Comment by VaclovasV** [comment]
Hi Tomáš,
Thank you for you answer ☺ Nice to see some feedback from project creators.
I‘m front-end developer, so I can‘t answer your question fully, but I send your anwer to our designer.
But I remember, that he re-synced all files, but i was not able to view them. Then, we deleted project and created another one.

Another issue is that variables are not global per project, but global per file or they are disappearing randomly (I‘m on vocation, so there was no time to investigate this).
Every time I have to re-create variables.

Regards,

Vaclovas Vičius
Front-End Developer

Devbridge Group
www.Devbridge.com<http://www.devbridge.com/>

**Comment by rychlis** [comment]
Variables are not synced across computers/teams so that might be one of the reasons they disappeared for you? We have issue #148 for that

**Comment by VaclovasV** [comment]
@rychlis I'm using same pc whole time, I'm not sure, then this happens, after resync or something else, but they are disappearing from time to time.

**Comment by bolekkerous** [comment]
If there is an internet connection problem during the sync of the Sketch file, it may happen that the file in Avocode ends corrupted and there it's not possible to open it.

Resyncing the file should help in these cases.

As for variables - they are now project wide and stored locally, so they should not be disappearing. They might disappear only if you reinstall Avocode or delete the local .avocode directory where the variables are stored.

I'll close this issue and you can monitor the progress of syncing variables across teams either in issue #482 or on our [UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7126248-sync-rules-and-variables-across-multiple-computers).
