### ISSUE TITLE
Color bug

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#357]
I found a bug with color in the same psd, give you screen.

1. http://i.imgur.com/UDmJFeg.png 
2. http://storage1.static.itmages.com/i/15/0720/h_1437376527_9836731_5571fdc616.png

in Adobe Cloud, Photoshop: #675e59 
In Avocode: #675f59

**Comment by marekhrabe** [comment]
We need a PSD to test the case

**Comment by marekhrabe** [comment]
When I inspected the layer in Photoshop, it told me that font color is #675f59 which is the same as in Avocode:

<img width="637" alt="screen shot 2015-10-23 at 17 01 04" src="https://cloud.githubusercontent.com/assets/156676/10696372/b12b89e6-79a7-11e5-8733-218ec0994ca0.png">

<img width="621" alt="screen shot 2015-10-23 at 16 58 45" src="https://cloud.githubusercontent.com/assets/156676/10696325/648cf7aa-79a7-11e5-82cf-18bcc961361a.png">
