### ISSUE TITLE
I can't install in both W7 & W8

### ISSUE THREAD

**Issue by dilhansarica** [avocode/avocode#359]
![image](https://cloud.githubusercontent.com/assets/3726151/8828225/55df81b4-3091-11e5-9e25-934c0bc5a462.png)

**Comment by rychlis** [comment]
Hi, could you please open the setup log and send it to us on team@avocode.com ?

**Comment by rychlis** [comment]
It looks like we didn't get any email from you and it's not really possible to know what happened without the logs (could be not enough free space, bad permissions, not properly downloaded exe, ...). I am closing the issue and will of course re-open if you provide more info.
