### ISSUE TITLE
Add compress options for exporting images

### ISSUE THREAD

**Issue by AlexeyMihaylov** [avocode/avocode#360]
Hello,

Can you create in Avocode an option that will allow user to optimize jpg- or png-files on-the-fly when exporting them from psd? For exaple, I can choose "export png" or "export optimized png".
Also, this option can have two suboptions: lossy or loseless optimizing.

Thanks.

**Comment by petrbrzek** [comment]
Yes we'll add those options in the future.I created uservoice idea for it https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/8987803-add-compress-options-for-exporting-images. Closing this now.
