### ISSUE TITLE
Can't open a sketch file by Avocode

### ISSUE THREAD

**Issue by CuongSky** [avocode/avocode#362]
Hi team,
Please help me to fix this issue as soon as possible.
![image](https://cloud.githubusercontent.com/assets/3079135/8894831/7fb87c38-33ee-11e5-96ac-f0927762916e.png)
Thank you.
Best regards,
Cuong

**Comment by rychlis** [comment]
Hey, please update to the latest version 2.3.2 and let me know if you still experience the issue: https://manager.avocode.com/downloads/

**Comment by rychlis** [comment]
I am closing this issue as it should be fixed by upgrading to the latest version. Let me know if you still experience this issue on the latest (2.4.1 now) and I will re-open
