### ISSUE TITLE
avocode not syncing 2.3.2

### ISSUE THREAD

**Issue by DishanTD** [avocode/avocode#363]
Hi Team,

Project not syncing. it's showing downloading.but i tried few hours.it's not complete.
can any one help me.

Thanks!

**Comment by rychlis** [comment]
Hey, when exactly does it happen, when you open the App or when you open a project? A screenshot would be helpful.

Could you share your account email and project name with us on team@avocode.com so we can investigate this further?

**Comment by rychlis** [comment]
This was probably caused by syncing with Sketch Extension 2.2.0 which often didn't export arboards correctly. You will need to re-sync with Sketch Extension 2.2.1

**Comment by DishanTD** [comment]
I am really appreciate your reply and help.I will try and let you know.

Thank you very much.

**Comment by DishanTD** [comment]
Thank you very much !!!
It's working now.. 

really really thanks for the help.
