### ISSUE TITLE
Issue when opening a sketch file

### ISSUE THREAD

**Issue by srprasanna** [avocode/avocode#365]
Describe your problem here…

---

```
TypeError: Cannot read property 'imageName' of undefined
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2540
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2460
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2460
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2460
  at t.module.exports.t._getImagesToLoad (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2673)
  at new t (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:515)
  at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:20178
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

**Comment by rychlis** [comment]
Hi, could you try to update your Avocode app to the latest version (2.3.2) https://manager.avocode.com/downloads/

If it doesn't help, please send the design name, your account name and the sketch file (if possible) to team@avocode.com

**Comment by rychlis** [comment]
It should help to re-sync the design completely using the extension as it was not properly uploaded. It looks like the upload was interrupted by the designer.

I will keep thie issue open until we add a better handling of similar errors to let you know when the design is not synced properly

**Comment by rychlis** [comment]
OK re-sync only will not help, one of the artboards will always fail with this error, even after re-sync. We will investigate this further and try to fix it asap

**Comment by bolekkerous** [comment]
This problem should not be happening with the latest versions of Sketch plugin and Avocode app.

You can always download the latest versions here:

https://manager.avocode.com/downloads/

I'll close this issue - if you still encounter the problem, or any other, please create a new issue.
