### ISSUE TITLE
kernel_task memory overuse with Avocode

### ISSUE THREAD

**Issue by MichalCerny** [avocode/avocode#370]
Hey guys. First of all thanks for great product. Anyway I have really huge problem. When I'm using avocode after few hours my 15" macbook pro (2014) will run out of his 16GB memory because of kernel_task, when I force quit avocode than kernel_task going lower about ~6GB of memory. Here is some screenshot before and after. It's avocode really linked with problem with kernel_task and running out of memory? What can I do with it?

<img width="778" alt="screen shot 2015-07-29 at 13 44 53" src="https://cloud.githubusercontent.com/assets/1162414/8956669/779a0984-35f8-11e5-9188-a12e11a67ec8.png">

<img width="771" alt="screen shot 2015-07-29 at 13 45 10" src="https://cloud.githubusercontent.com/assets/1162414/8956670/779af506-35f8-11e5-988f-ab5e1d4f9a52.png">

**Comment by MichalCerny** [comment]
No one? Still happening :-1:
![screen shot 2015-08-07 at 10 11 19](https://cloud.githubusercontent.com/assets/1162414/9131540/c7aaf320-3cec-11e5-8af9-d38e02371c2f.png)
![screen shot 2015-08-07 at 10 11 29](https://cloud.githubusercontent.com/assets/1162414/9131539/c7a60e0a-3cec-11e5-9c4f-cee6183c7ea9.png)

**Comment by MichalCerny** [comment]
After 3 hours again :) 
![screen shot 2015-08-07 at 12 47 21](https://cloud.githubusercontent.com/assets/1162414/9134337/7ee96dc6-3d03-11e5-86b8-014584e3c5db.png)
![screen shot 2015-08-07 at 12 47 31](https://cloud.githubusercontent.com/assets/1162414/9134336/7ee91b64-3d03-11e5-9239-cb99a6b46d92.png)

**Comment by petrbrzek** [comment]
Hi, we know about your problem. Sorry for not replying earlier. Does this memory leak happen when the app is in idle or you actively use it?

**Comment by MichalCerny** [comment]
I'm actively using it so it's really annoying, sometime I need to restart computer because whole system freeze and I can't even force quit any app. When I'm not working with avocode I quit app because it's doing in idle time too. Tried el capitan and its doing same thing after I installed avocode :-1:

**Comment by hrvojester** [comment]
It is happening to me too.

**Comment by martin-kolar** [comment]
+1

**Comment by rockstox** [comment]
+1

**Comment by nathanmarks** [comment]
+1 I just got avocode and it's causing my machine to freeze up repeatedly due to this.

**Comment by marcelfahle** [comment]
+1

**Comment by vladshap** [comment]
+1

**Comment by KTala9** [comment]
+1

**Comment by safareli** [comment]
+1

**Comment by drugoi** [comment]
+1
El Capitan, 8 GB

**Comment by lilianarosa** [comment]
+1

This happens immediately when I have a couple of files open at the same time.

MacBook Pro, 2.8 GHz, 16 GB, Yosemite.

**Comment by petrbrzek** [comment]
Hi guys, I have some good news for you. After some investigation, I was able to fix the issue by updating Electron. Yet we still have to solve some technical issues like building the app but I hope the next release will contain the fix.

**Comment by rychlis** [comment]
We've launched Avocode 2.4.4 beta which should fix this issue, you can download the build from here:

Linux ia32 - https://manager.avocode.com/download/app-beta/linux-ia32/
​Linux x64 - https://manager.avocode.com/download/app-beta/linux/
​Mac - https://manager.avocode.com/download/app-beta/mac/
​Windows - https://manager.avocode.com/download/app-beta/windows/

This will remain in beta for now, if everything goes fine we will enable auto-update to 2.4.4 globally

**Comment by dmitrylebedev** [comment]
- ~0.5 GB http://take.ms/TJ150

**Comment by rychlis** [comment]
Avocode 2.4.5 is now live with the fix. Let us know if you still experience the same issue and we will re-open the issue

https://manager.avocode.com/downloads/
