### ISSUE TITLE
Bourbon include size

### ISSUE THREAD

**Issue by AlexanderPlaksenko** [avocode/avocode#373]
Hi, Avocode set comma between width&height  @include size(966px, 37px); http://joxi.ru/MAjRq45Fl9lzAe

But in Bourbon docs http://bourbon.io/docs/#size comma not need.
http://joxi.ru/Vm6koPYflJpq2Z

Please, fix this, tnx!

**Comment by victorwbuzz** [comment]
+1

**Comment by petrbrzek** [comment]
Will be fixed in next release. See #424
