### ISSUE TITLE
Thousands of update alerts while computer was idle (Ubuntu 14.04)

### ISSUE THREAD

**Issue by corsairdnb** [avocode/avocode#377]
This window appears every few minutes
![screenshot-from-2015-08-07-12-51-13](https://cloud.githubusercontent.com/assets/4211598/9133342/9b81eefe-3d03-11e5-9cd8-6c2d2c4f8605.jpg)

Last time when I locked off my computer there were enormous count of these ones.

**Comment by rychlis** [comment]
The new version actually fixed this issue, we've replaced these notification alerts with an in-app notification that displays just once. Sorry for the spammy update alerts!
