### ISSUE TITLE
Add ability to scale sizing

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#379]
For example, designer makes 2x psd, where it is for 1200px screens, but actual size of file is 2400px. I need to divide all sizing by 2. You should provide some shortcut for it.

**Comment by rychlis** [comment]
We should definitely implement such feature, this was already requested in #149 and there is an Uservoice idea as well: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7497688-divide-or-multiply-dimensions-based-on-pixel-densi
