### ISSUE TITLE
Crash when working with multiple layers to Base64

### ISSUE THREAD

**Issue by studio625** [avocode/avocode#38]
Intermittent issue...seems to happen only after Avocode has been open for a while.

I've had it happen under these circumstances:
- Just toggling the visibility of layers, trying to find the right item
- Selecting multiple layers, then saving as an image file/copying to Base64
- Just came back from a break and waking up from sleep mode crashed Avocode

It might be something in my PSD, since I didn't have this issue on the last site I built. Here it is if you want to test with it:
https://www.dropbox.com/s/fc15qaymq8sk60p/ce-core-mockup-v5.psd?dl=0

**Comment by tomashanacek** [comment]
Fixed.
