### ISSUE TITLE
Cannot add new revision of whole Sketch file

### ISSUE THREAD

**Issue by enzy** [avocode/avocode#383]
When multiple changes across pages has been made, there is no way to mark it as a new revision...

![screenshot 2015-08-10 17 20 42](https://cloud.githubusercontent.com/assets/809888/9175190/91e0c414-3f84-11e5-90b4-950118c460e5.png)

@spooner2802 can provide more info if needed

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
