### ISSUE TITLE
32 bit binaries for Linux?

### ISSUE THREAD

**Issue by stdex** [avocode/avocode#389]
Ubuntu 14.04 x86

Download avocode-app-linux-2.4.1.zip and extract to /opt/Avocode/

Try to run with:
>homepc@homepc-P52Jc:/opt/Avocode$ ./avocode
>bash: ./avocode: cannot execute binary file: Exec format error

It's thats why 64bit binaries or what? Where I can get binaries for x86 or sources for build?

**Comment by rychlis** [comment]
Hi, we only build 64bit binaries for Linux. If there is enough demand we might start doing 32 bit builds as well, here is an [uservoice idea](http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7645281-32bit-linux-build) you can vote for

**Comment by stdex** [comment]
OMG... It's so unpleasant news.

**Comment by rychlis** [comment]
I will try to build 32 bit binary in the next release, stay tuned :)

**Comment by petrbrzek** [comment]
There is x86 version for linux now.
