### ISSUE TITLE
filterRes attribute on exported SVG

### ISSUE THREAD

**Issue by JackuB** [avocode/avocode#39]
I found that when Avocode exports SVG with filter, it misses the `filterRes` attribute.

It's apparent on high-res displays.

![avocode_svg](https://cloud.githubusercontent.com/assets/1788727/4241419/b5b38490-39f3-11e4-8a00-4416d84b4c95.png)

(v.0.5.0 / OS X Mavericks)

**Comment by petrbrzek** [comment]
How would you apply this attribute? I see you used `filterRes="2000"`. Is this value supported by something?

From MDN
> Take care when assigning a non-default value to this attribute. Too small of a value may result in unwanted pixelation in the result. Too large of a value may result in slow processing and large memory usage.

**Comment by JackuB** [comment]
2000 was just number that worked best for that specific image.

Anyway, I had to manually remove filter from logo as it was still causing issues (mostly on iOS Safari).

**Comment by petrbrzek** [comment]
Can we improve anything related to this, or can I close the issue?

**Comment by JackuB** [comment]
I've tried exporting same SVG file in current version of Avocode (1.1.1) - exported without filter and sharp on retina.
Closing.
