### ISSUE TITLE
cant open psd

### ISSUE THREAD

**Issue by prog666** [avocode/avocode#394]

**Comment by rychlis** [comment]
Hey could you give us at least *some* specific information? What exactly were you doing and what happened? A screenshot would be great. Thanks

**Comment by prog666** [comment]
it've been few months already.. your team uploaded psd for me, so it's fine.

**Comment by rychlis** [comment]
Ok, thanks :)

**Comment by prog666** [comment]
I dont have this psd already, i thought you'll give me an email to send psd for investigation
