### ISSUE TITLE
Layers with rotation transforms

### ISSUE THREAD

**Issue by markst** [avocode/avocode#395]
![image](https://cloud.githubusercontent.com/assets/274318/9384582/557f5e00-4749-11e5-8449-ce9e39211d8d.png)

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
