### ISSUE TITLE
Sketch plugin not working

### ISSUE THREAD

**Issue by stanthecaddy** [avocode/avocode#396]
Once the plugin sync's the file (which seems to work fine), the Avocode manager browser window that it opens at the end shows a 'page not found' error. As a result the sync seems to break down entirely

**Comment by chazchumley** [comment]
17 days and no response from SUPPORT!  WTF.  Fix your damn plugin or refund us money for your product

**Comment by rychlis** [comment]
For some users the domain avcd.io doesn't work. It seems like there is an issue with the ISP.

The domain avcd.io is used as a shortcut to manager.avocode.com, but we have disabled the domain anyways as the link is quite long anyway. This should fix this issue, sorry for the late reply

**Comment by chazchumley** [comment]
Thank you.  That fixed everything.

**Comment by stanthecaddy** [comment]
+1, that fixed the issue!

On Mon, Sep 7, 2015 at 9:55 AM, Chaz Chumley <notifications@github.com>
wrote:

> Thank you. That fixed everything.
>
> On Mon, Sep 7, 2015 at 6:16 AM, Tomáš Rychlik <notifications@github.com>
> wrote:
>
> > For some users the domain avcd.io doesn't work. It seems like there is
> an
> > issue with the ISP.
> >
> > The domain avcd.io is used as a shortcut to manager.avocode.com, but we
> > have disabled the domain anyways as the link is quite long anyway. This
> > should fix this issue, sorry for the late reply
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/avocode/avocode/issues/396#issuecomment-138259986>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avocode/avocode/issues/396#issuecomment-138305194>.
>



-- 
-Vishal
