### ISSUE TITLE
Cannot delete a pending design

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#397]
I cancelled the uploading of a PSD file and Avocode crashed.
Now I have a "1 Pending design" bar with no option to discard the file.

**Comment by petrbrzek** [comment]
Can you delete pending design like this?

<img width="324" alt="avocode_-__dev_mode_" src="https://cloud.githubusercontent.com/assets/879564/10718314/30b59412-7b70-11e5-8575-d8a5d92afc6b.png">

**Comment by rychlis** [comment]
We've added an option to delete not assigned designs in avocode 2.5 - you can always cancel designs in the pending designs bottom bar
