### ISSUE TITLE
Incorrectly calculating size in css

### ISSUE THREAD

**Issue by Lukavyi** [avocode/avocode#40]
Reproducibility: always
Description:
Expected result: 18x18
Actual result: 17x17
OS and app versions: mac os yosemite/beta 0.5
https://www.dropbox.com/s/4zgaz0fz7cp7u43/%D0%97%D0%BD%D1%96%D0%BC%D0%BE%D0%BA%20%D0%B5%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%202014-09-20%2019.38.54.png?dl=0

**Comment by petrbrzek** [comment]
Actually it's correct. One type of size is for bitmap and the other is for CSS which can include borders and shadows.
