### ISSUE TITLE
Avocode's font-size is really small

### ISSUE THREAD

**Issue by rasy-js** [avocode/avocode#403]
css code is very small, it is not visible

**Comment by petrbrzek** [comment]
Can you provide a screenshot to describe the problem?

**Comment by AlexanderKri** [comment]
default font-size = small

**Comment by whizark** [comment]
I also feel that Avocode's font-size is really small.
I use wide screen and tweak display / font settings (Ubuntu) but Avocode doesn't respect system font setting.
It would be nice if we can configure UI font family & font size on Preferences menu.
(Multi-byte characters are broken with Default font family.)

**Comment by petrbrzek** [comment]
Thanks for clarifying.

> It would be nice if we could configure UI font family & font size on Preferences menu.

We are already working on this one. I'll let know when this will be ready to ship.

**Comment by rwrobe** [comment]
Hey guys, for the record the font size in my version is enormous, to the point where I 
![screenshot from 2016-04-20 11 05 51](https://cloud.githubusercontent.com/assets/5480192/14669138/ddfe412a-06e7-11e6-9115-568544e6e64e.png)
can't access menus

**Comment by connor-bean** [comment]
Hello, Rob -

What version of Avocode are you using?

Thanks,
Connor

**Comment by rwrobe** [comment]
2.6.0

**Comment by connor-bean** [comment]
And what OS/version? 

If you uninstall Avocode and then reinstall it, does it fix the problem?

Thanks,
Connor

**Comment by rwrobe** [comment]
Running elementaryOS on a HiDPI screen. Didn't "install" anything per se, just copied the unzipped folder to /opt/ and ran it there.

**Comment by bolekkerous** [comment]
It should now be possible to modify the UI text size in the general settings and also the font size of the code panel in code panel settings.

I'll close this issue - if you still experience any problems regarding this, please create a new issue.
