### ISSUE TITLE
Sketch crashes when trying to sync

### ISSUE THREAD

**Issue by danielortiz** [avocode/avocode#405]
Everytime I try to sync a sketch file I have, sketch simply close. I tried syncing the welcome sketch page and it worked flawless, I thought it could be due to the file size (which is only 16mb), and I removed all art boards but one, saved and tried again, it didn't work either. 

OS X 10.10.4
Avocode extension 2.1.1.
Sketch 3.3.3

**Comment by marekhrabe** [comment]
We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs and crashes. We will let you know when the new version is released.

**Comment by rychlis** [comment]
Does this issue still happen in sketch extension 2.1.4 and Sketch 3.4.1?

**Comment by bolekkerous** [comment]
This shouldn't happen anymore with the latest Sketch plugin.

You can always download the latest version here:

https://manager.avocode.com/downloads/

If you still experience this problem or any other, please create a new issue with it.
