### ISSUE TITLE
Can't access avocode website/manager

### ISSUE THREAD

**Issue by luisfontes** [avocode/avocode#406]
Hi,

I wand to reactivate my avocode subscription. But for three weeks already I can't even access the avocode website (avocode.com) and the manager (manager.avocode.com):

![image](https://cloud.githubusercontent.com/assets/5988029/9502456/c6ac205a-4c07-11e5-9e43-ab31a34b83f9.png)

My colleague tried also and got the same broken page. I've tried refreshing and in different networks (work/home) and same thing.

**Comment by petrbrzek** [comment]
Could you try to configure your network settings to use Google DNS? https://developers.google.com/speed/public-dns/

**Comment by luisfontes** [comment]
Hi, I've made that and it worked. Everything seems fine now. Thanks.
