### ISSUE TITLE
Plugin Crashes Sketch during "Exporting Metadata"

### ISSUE THREAD

**Issue by thejohnnylee** [avocode/avocode#407]
I'm having the same issue as #405. 

The file I'm trying to sync a file to Avocode is 8.8mb and crashed during the "Exporting Metadata" process of the plugin.

I tried syncing the Welcome to Sketch template as well, which worked. I've also tried uninstalling/reinstalling the plugin.

OS X 10.10.2
Sync to Avocode 2.1.1.
Sketch 3.3.3

**Comment by marekhrabe** [comment]
We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs including this one. We will let you know when the new version is released.

**Comment by rychlis** [comment]
Does this issue still happen in sketch extension 2.1.4 and Sketch 3.4.1?

**Comment by bolekkerous** [comment]
This shouldn't happen anymore with the latest Sketch plugin.

You can always download the latest version here:

https://manager.avocode.com/downloads/

If you still experience this problem or any other, please create a new issue with it.
