### ISSUE TITLE
Dunno wtf

### ISSUE THREAD

**Issue by dariusb** [avocode/avocode#410]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.3.2
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/dariusbisikirskas/Library/Containers/com.bohemiancoding.sketch3/Data/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by chazchumley** [comment]
WOW - WTF IS RIGHT  9 days and no one has addressed this issue?

**Comment by marekhrabe** [comment]
Sorry to respond late. We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs including this one. We will notice you when the new version is released. I will leave just one issue about this topic open: #472
