### ISSUE TITLE
Created Variables disappear when logged out and logged in

### ISSUE THREAD

**Issue by gayankt** [avocode/avocode#415]
If you created several variables and logged out. The avocode do not keep those variables when I logged in. This will waste time on creating variables again and again.
and it is better to share those variables with team members too.

**Comment by petrbrzek** [comment]
Agree, it's really frustrating to define variables again and again. We'll look into it and I'll let you know when the fix will be ready.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by itsjustmath** [comment]
Still an issue for me 😞

**Comment by bolekkerous** [comment]
Variables are now project wide and stored locally, so they should not be disappearing after logging out. They might disappear only if you reinstall Avocode or delete the local .avocode directory where the variables are stored.

I'll close this issue and you can monitor the progress of syncing variables across teams either in issue #482 or on our [UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7126248-sync-rules-and-variables-across-multiple-computers).
