### ISSUE TITLE
Slice tool can't crop smaller images

### ISSUE THREAD

**Issue by gayankt** [avocode/avocode#419]
I cannot slice very small images
small piece of a image eg: 1px image

**Comment by petrbrzek** [comment]
Thanks for reporting this bug. I've tested it and it's not possible to crop selection smaller than 6x6 px. The next release will fix it.

**Comment by gayankt** [comment]
thanks @petrbrzek

**Comment by petrbrzek** [comment]
We've launched Avocode 2.4.4 beta which should fix this issue, you can download the build from here:

​Mac - https://manager.avocode.com/download/app-beta/mac/

Linux ia32 - https://manager.avocode.com/download/app-beta/linux-ia32/
​Linux x64 - https://manager.avocode.com/download/app-beta/linux/
​Windows - https://manager.avocode.com/download/app-beta/windows/

This will remain in beta for now, if everything goes fine we will enable auto-update to 2.4.4 globally

**Comment by rychlis** [comment]
Avocode 2.4.5 is now live with the fix. Let us know if you still experience the same issue and we will re-open the issue
