### ISSUE TITLE
Feedback: slow sync, ui&other improvements

### ISSUE THREAD

**Issue by LeZuse** [avocode/avocode#42]
Feel free to separate into individual issues:
[CZE]
1. Při synchronizaci ve photoshopu - avocode plugin zatíží procesor na 100%. Macbook Pro i5, 8GB RAM.

2. Pomalá synchronizace - asi záleží na připojení, ale zdržuje to v práci

3. Okno kde se generuje css,less... by mohlo být větší.
    Né vždy chci kopirovat vše nebo chci vidět vše co to vygenerovalo (malá výška i šířka okna).

4. Chybí scrollbar, nevím kde se přesně v návrhu nacházím při scrollování.

5. Když mám návrh v zoomu např. 65% vždy méně než 100% a mám vybraný
    layer (layer 186x65), který popisuje šířku i výšku tak je to nečitelné.

6. Chybí mi generování obrázku v base64 do html, css.

7. Mohlo by to umět generovat css pozice v obrázku (do jednoho obrázku se uloží více motivu activ, hover atd.).
    viz. http://www.spritecow.com/

**Comment by petrbrzek** [comment]
Presunuto na gitlab. Zaviram.
