### ISSUE TITLE
Grid View

### ISSUE THREAD

**Issue by bvrudney** [avocode/avocode#422]
How do I see the grid system avocode used in sketch?  Is there a way to layer a grid on top?

**Comment by marekhrabe** [comment]
We are not currently pulling that data from Sketch, but we add it. There is a feature request for that on Uservoice, you can vote here: http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/10188261-support-viewing-sketch-layout-grid-in-avocode-mang

**Comment by jakubzitny** [comment]
Hi @bvrudney, we've just released Avocode `3.4.0` with support for grids and layouts from Sketch. Please update the app or [download the latest version](https://avocode.com/download).
