### ISSUE TITLE
Black Screen on load Design

### ISSUE THREAD

**Issue by xenongattz** [avocode/avocode#423]
Just got this when load:
![2015-09-01 20-39-02 avocode - 2 3 2-ea60620](https://cloud.githubusercontent.com/assets/6165014/9611674/a2ba63aa-50e9-11e5-9b25-e8f4da167738.png)

**Comment by jankuca** [comment]
Does this happen every time you open the design? Can you try logging out, restarting the app and logging back in? You can also try reuploading the design. If that does not help, please share the problematic file at team[at]avocode.com.

**Comment by xenongattz** [comment]
When I divided PSD into 3 parts then it works! So maybe problem with amount of operating memory.

**Comment by rychlis** [comment]
Is it possible to share the problematic PSD (before you divided it) with us at team@avocode.com please? Or just let us know what was the name of the PSD and we should be able to get it with your permission

**Comment by makewebme** [comment]
This PSD is here: http://xenongattz.makeweb.me/projects/apm_dent/!psd%26ai%26sources/arm_dent_index_1920.psd

Size about 70 MB.

I have 4Gb memory on my Mac.

**Comment by makewebme** [comment]
@rychlis This PSD is here: http://xenongattz.makeweb.me/projects/apm_dent/!psd%26ai%26sources/arm_dent_index_1920.psd

Size about 70 MB.

I have 4Gb memory on my Mac.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
