### ISSUE TITLE
Bourbon size mixin error

### ISSUE THREAD

**Issue by filipemerker** [avocode/avocode#424]
There is an error into the Bourbon sass mixin library generator.
It generates this
```sass
@include size(305px, 400px);
```
When it must be 
```sass
@include size(305px 400px); /*without the comma*/
```
For the record, follows the gulp trown error:
```terminal
{ message: 'assets/scss/partials/_home.scss\n  249:18  mixin size only takes 1 arguments; given 2',
  column: 18,
  line: 249,
  file: '/www/.../assets/scss/partials/_home.scss',
  status: 1,
  messageFormatted: '\u001b[4massets/scss/partials/_home.scss\u001b[24m\n\u001b[90m  249:18\u001b[39m  mixin size only takes 1 arguments; given 2',
  name: 'Error',
  stack: 'Error: assets/scss/partials/_home.scss\n  249:18  mixin size only takes 1 arguments; given 2\n    at options.error (/www/.../node_modules/gulp-sass/node_modules/node-sass/lib/index.js:276:32)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }

```

**Comment by victorwbuzz** [comment]
+1

**Comment by AlexanderPlaksenko** [comment]
https://github.com/avocode/avocode/issues/373

**Comment by filipemerker** [comment]
Com'on guys, this is an easy one that really bothers me and every Bourbon user ever!

**Comment by petrbrzek** [comment]
@filipemerker Will be fixed in the next release.

**Comment by petrbrzek** [comment]
We've launched Avocode 2.4.4 beta which should fix this issue, you can download the build from here:

​Mac - https://manager.avocode.com/download/app-beta/mac/

Linux ia32 - https://manager.avocode.com/download/app-beta/linux-ia32/
​Linux x64 - https://manager.avocode.com/download/app-beta/linux/
​Windows - https://manager.avocode.com/download/app-beta/windows/

This will remain in beta for now, if everything goes fine we will enable auto-update to 2.4.4 globally

**Comment by rychlis** [comment]
Avocode 2.4.5 is now live with the fix. Let us know if you still experience the same issue and we will re-open the issue

**Comment by filipemerker** [comment]
Fixed.
