### ISSUE TITLE
Different render in assets, photoshop and avacode

### ISSUE THREAD

**Issue by drupaldevel** [avocode/avocode#432]
http://i.imgur.com/O00V1SS.png

**Comment by rychlis** [comment]
Could you please share the PSD (you can put just relevat layers to a new psd) with us at team@avocode.com? Are you using clipping mask here?

Thanks and sorry for the late reply

**Comment by rychlis** [comment]
This issue should be fixed since around Avocode 2.6 (February 2016), I am closing the issue. Let me know if you are still able to reproduce the problem in the latest Avocode.
