### ISSUE TITLE
Bug PSD Unable to Open in Avocode

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#44]
All of my design files for this particular project cause the 'Your Avocode 
has gone bad' error and doesn't open.

I'm presuming the issue is consistent so i'll send you one of the PSD's to 
look at.

https://docs.google.com/file/d/0B22hOtXcPEfwNWNXbWhmMUZFMm8/edit?usp=drive_web

**Comment by petrbrzek** [comment]
@michaelone Could you provide us your problematic PSD? 

@jonathanolsen Try to remove .avcd folder inside your home folder.
