### ISSUE TITLE
Connection error after uploading design

### ISSUE THREAD

**Issue by kitin** [avocode/avocode#445]
Looks like uploading complete successful, but after it, on pressing "Save and open", there is an error "Saving failed. Please check your internet connection and try again". It's happens at home and at work (different connections).
Other projects (uploaded by other users) have no problems.

**Comment by DylanOpet** [comment]
Having these issues as well and it's been rather frustrating :cry:

**Comment by arashmidos** [comment]
+1 same issue

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
