### ISSUE TITLE
Option to create global variables

### ISSUE THREAD

**Issue by itsjustmath** [avocode/avocode#458]
Its really cumbersome to have to constantly re-input my color variables for each design.

**Comment by petrbrzek** [comment]
Variables are now project-wide. If I understand it correctly you would like to define global variables across all projects. It that correct?

**Comment by itsjustmath** [comment]
Yessir. What build version is it live on? I'm on `2.4.3-3630f5a`

**Comment by petrbrzek** [comment]
You are up to date.

**Comment by crh225** [comment]
I dont see it apply project wide and according to the website it says:
![image](https://cloud.githubusercontent.com/assets/19475195/22594637/8f0325d2-e9e9-11e6-902f-962e2e7ab03d.png)

**Comment by bolekkerous** [comment]
@crh225 Variables are now in fact project-wide. We're just working on updating the whole help center and once it is ready, it should be communicated correctly there.

**Comment by bolekkerous** [comment]
Hey - 
variables should be applied project-wide already for some time and synced among the team members and machines.

We're planning to also add variable import into Avocode in the future.
