### ISSUE TITLE
Disable export option or warn user when exporting rasterised layer as SVG

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#459]
When right clicking on a layer name, there's no option to export it to SVG, yet there is an option to add an "export rule" to force SVG export.

Same issue when right clicking the layer itself.

The expected behavior would be to either implement Illustrator support or hide the SVG export option where not applicable. 
Otherwise people (me included) are wondering why exporting to SVG produces a base64-encoded PNG, and answering that needed quite a bit of research.

**Comment by petrbrzek** [comment]
We could disable the option or warn you at least when trying to export rasterised layer as SVG.

**Comment by VPenkov** [comment]
Disabling it seems like a logical thing to do but then you will get support requests why it only exists sometimes.
Warning the user would be too verbose.

I'd suggest the latter with a dialog window that communicates the lack of Adobe Illustrator support but maybe add a "do not show this again" checkbox.

**Comment by bolekkerous** [comment]
Exporting SVG from layers that we do not have the data to correctly export is now disabled in the export modal as well as in the context menu.

To export vector smart objects from Illustrator, we'd need to support the Illustrator file format first.

If you want us to do that, please upvote it on our [UserVoice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992611-illustrator-support).
