### ISSUE TITLE
Issues with Clipping Masks having a Stroke

### ISSUE THREAD

**Issue by gayankt** [avocode/avocode#462]
We have a PSD which has a clipping mask with a stroke (as a border)
But on Avocode it doesn't show the stroke.
But on preview dashbord it shows.

![2015-10-06_0933](https://cloud.githubusercontent.com/assets/654973/10299943/0738fca8-6c0e-11e5-8cc6-37fe549a7224.png)
![2015-10-06_0931](https://cloud.githubusercontent.com/assets/654973/10299944/09ab8406-6c0e-11e5-90fc-ab9c70e251a9.png)
![2015-10-06_0930](https://cloud.githubusercontent.com/assets/654973/10299975/3d96ca50-6c0e-11e5-9aa3-799fa2457585.png)

**Comment by lukyer** [comment]
same problem here

**Comment by rychlis** [comment]
Thanks for the report, it's a known bug. Unfortunately to support this we would need to render the stroke in the app which is not an easy task and will take a while. We're currently investigating how to implement at least simple effects to start off

**Comment by gayankt** [comment]
Thanks @rychlis ,
When do you think that you can fix this issue, because we have get stuck on several projects due to this issue and it is better if you can provide a fix soon.

It is better if you can add this effects to be turn on and off, because we can add the gradients or strokes by css and just crop the image only, otherwise both image and effects are cropped into one image so no point of having css.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
