### ISSUE TITLE
get an exception , i don't know why.

### ISSUE THREAD

**Issue by sevenler** [avocode/avocode#464]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.3.3
```
Error: API: Could not fetch user designs
    at /Users/Johnny/…/avocode-exporter/lib/exporter.js:1:3672
    at /Users/Johnny/…/avocode-exporter/node_modules/async/lib/async.js:522:46
    at /Users/Johnny/…/avocode-exporter/node_modules/async/lib/async.js:251:17
    at /Users/Johnny/…/avocode-exporter/node_modules/async/lib/async.js:148:21
    at /Users/Johnny/…/avocode-exporter/node_modules/async/lib/async.js:248:21
    at /Users/Johnny/…/avocode-exporter/node_modules/async/lib/async.js:612:34
    at /Users/Johnny/…/avocode-exporter/node_modules/async/lib/async.js:513:25
    at Request._callback (/Users/Johnny/…/avocode-exporter/lib/api.js:1:1273)
    at self.callback (/Users/Johnny/…/avocode-exporter/node_modules/request/request.js:197:22)
    at Request.EventEmitter.emit (events.js:95:17)
```

**Comment by marekhrabe** [comment]
Can you try to open your Sketch, select from top menu `Plugins > Reveal Plugins folder`, delete `avocode.token` file from that folder and then try to sync again? It should ask you to log in again and that might fix the issue. 

We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs including this one. We will notice you when the new version is released.

**Comment by rychlis** [comment]
There is a beta version of the new extension you can try right now, see this guide to install and let me know if there are any problems: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by rychlis** [comment]
I am closing this issue as it's from old version of Sketch & plugin. Feel free to create a new issue if you still experience this
