### ISSUE TITLE
No way to download original uploaded psd file

### ISSUE THREAD

**Issue by glebtv** [avocode/avocode#466]
Avocode currently has no option to download original PSD file

**Comment by rychlis** [comment]
That would be a good feature. We use uservoice for feature request, feel free to vote for the [idea](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/8025009-add-option-to-download-psd) to follow any statu updates. I will keep this issue open until this is implemented.

Also in case you need the PSD urgently (for example if you removed it locally by accident), contact us at team@avocode.com and we should be able to retrieve the PSD for you

**Comment by petrbrzek** [comment]
This feature landed in 2.10.0.
