### ISSUE TITLE
Wrong naming when exporting layer groups in Avocode

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#467]
![avocode-sketch-exporting-1](https://cloud.githubusercontent.com/assets/156676/10692808/32d16240-7994-11e5-8e41-d4ef2dec09a6.png)

**Comment by marekhrabe** [comment]
Thanks for the suggestion, we added that into our internal bug tracking system

**Comment by bolekkerous** [comment]
Exported group name is now by default used as the file name for the exported image.
