### ISSUE TITLE
Convert file from Sketch to avocode. Got "processing failed" when open it from Avocode

### ISSUE THREAD

**Issue by shic** [avocode/avocode#476]
![ww2015101610 42 40 am](https://cloud.githubusercontent.com/assets/4471626/10537548/d6adb348-73f2-11e5-8c24-1c25a30d4d43.png)

I am using the latest  avocode plugin and latest avocode version. When I Convert file from Sketch to avocode, Sketch told me convert and upload succeeded. But when I try to sync it from Avocode, I got  "processing failed". Do you have any suggestion?

**Comment by marekhrabe** [comment]
There was probably an error in Sketch extension and some of files didn't get uploaded. Can you try to sync once again? 

We are working on a new major release of Sketch extension for some time now. It fixes a lot of bugs including this one. We will notice you when the new version is released.

**Comment by rychlis** [comment]
We're closing this issue as the re-sync should fix this, let us know if you still experience any issue
