### ISSUE TITLE
Avocode generates a wrong border-radius from a Sketch design

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#478]
I have a Sketch export with a rectangle that has a topleft and topright border-radius of 5 pixels, however your generated CSS is `border-radius: 5px 0 0 5px`, which corresponds to topleft and bottomleft. Expected would be `border-radius: 5px 5px 0 0`. It seems there might be a quarter turn involved somewhere?

**Comment by marekhrabe** [comment]
You are right, I made tests for that and we are getting corner radii in different order from Photoshop and Sketch. We will fix that and made them the same. Thanks for your report

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
