### ISSUE TITLE
Canvas setting for retina disappears

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#479]
I work on a MacBook Pro 15" with Retina Display connected to a non-retina Cinema Display.

The Preferences screen usually has a *Retina canvas* setting for telling Avocode that the design is in retina resolution, so it can be shown at a better zoom-level. _("If enabled, the document will be downscaled to see more detail")_

That setting seems to just disappear once in a while, and thus the design is super zoomed on the external screen.

**Update**: I can get the preference back if I launch Avocode _before_ connecting the external display. It even remembers my prefence to have it checked.

It probably would be better to disable the preference (dimming it or similar) and adding a description as to why it has been disabled.

**Comment by petrbrzek** [comment]
> It probably would be better to disable the preference (dimming it or similar) and adding a description as to why it has been disabled.

:+1: Agree. We'll change this in upcoming release.

**Comment by greystate** [comment]
:100: :)

**Comment by petrbrzek** [comment]
We've launched Avocode 2.4.4 beta which should fix this issue, you can download the build from here:

​Mac - https://manager.avocode.com/download/app-beta/mac/

Linux ia32 - https://manager.avocode.com/download/app-beta/linux-ia32/
​Linux x64 - https://manager.avocode.com/download/app-beta/linux/
​Windows - https://manager.avocode.com/download/app-beta/windows/

This will remain in beta for now, if everything goes fine we will enable auto-update to 2.4.4 globally

**Comment by greystate** [comment]
Hi @petrbrzek - the 2.4.4 beta seems to have fixed this issue. Thanks!
