### ISSUE TITLE
Make variables global per project and prevent them from disappearing then project is synced

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#482]
I'm not sure why, but assigned color and etc variables disappear after some time (I'm not sure why this is happening, maybe they fall after resync or something), very irritaning issue.
And if variables are assigned it would be better to sync them between accounts.

**Comment by jankuca** [comment]
Good point, thank you. We are planning to implement variable and export rule syncing.

You can upvote the idea on User Voice and follow the progress there: http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7126248-sync-rules-and-variables-across-multiple-computers

**Comment by itsjustmath** [comment]
+1

**Comment by jakubzitny** [comment]
This has been implemented in Avocode `2.16.0`.
