### ISSUE TITLE
Show who updated each file last and when

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#483]
This is very important when working in big teams.

People want to know, who made changes to a design and when. Now we can only see similar information for ALL projects in the notification tab and they are "per project", not "per file".

It would be awesome to see last 5 changes for a file when we are in it (file is open). Date and user name should be enough.

**Comment by jankuca** [comment]
Thank you for your suggestion. We will discuss this possibility in the team.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - where this feature was added. 

When you click on a project or a design, you should see a sidebar with activity feed on the right side.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
