### ISSUE TITLE
My last problem with Typo in Avocode..

### ISSUE THREAD

**Issue by MantouxSolutions** [avocode/avocode#485]
Hey guys,

i really love Avocode. What i am going to say is complaining on a very high level.
Thank you very much for the "line height" update! The last thing, which would be really important for me (and i think for other users as well) is letter spacing.

Now i´ve red that it´s impossible right now. I am currently working with PS Letter Spacing Units and calculating them down to em. Wouldnt that be a good option for PS Users to see letter spacing from -200 to +200 calculated in em (-0.002 em to 0.2 em) right in Avocode?

Thank you so much for this great tool!

**Comment by jankuca** [comment]
Thank you, we are very happy you like Avocode. Letter spacing support is currently supported for Sketch documents while Photoshop support is planned as well.

You can upvote the User Voice idea here: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7024976-show-letter-spacing-in-photoshop-documents

**Comment by bolekkerous** [comment]
Closing this as duplicate, because the other issue #793 has more comments.

**Comment by bolekkerous** [comment]
Letter-spacing property for Photoshop documents should now be available on the web app (https://app.avocode.com/) for all newly uploaded designs into the web app.

It's coming to the desktop app as well in upcoming update, which should be released in 1-2 weeks.
