### ISSUE TITLE
"Arguments to path.resolve must be strings"

### ISSUE THREAD

**Issue by tomrantala** [avocode/avocode#490]
Trying to sync from Sketch 3.4 to Avocode:

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/tom/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by urikelman** [comment]
This is a HUGE bug that needs to be fixed ASAP. I have developers waiting for designs to be uploaded!

**Comment by darthsenior** [comment]
Same problem here.

**Comment by NewMediaStudio** [comment]
Same here.

**Comment by marekhrabe** [comment]
We just released a new version of extension that supports Sketch 3.4. Download here https://manager.avocode.com/downloads/
