### ISSUE TITLE
Doesn't download artboards.

### ISSUE THREAD

**Issue by squadnik** [avocode/avocode#494]
Hi I'm testing your app intensively and now I created new a account and added new project.
I exported project from Sketch successfully but Avocode app can't finish syncing. It shows "downloading" on all artboards and nothing more. I've tried to log out / log in and downloading app again but it didn't help.
This is how it behaves:
http://d.pr/v/qhZ7

I have no internet connection problems.

**Comment by squadnik** [comment]
Also tried different via mobile internet connection.

**Comment by rychlis** [comment]
looks like the hotfixed sketch extension for newly released Sketch 3.4 doesn't upload artboard metadata correctly which results in this problem, we'll release a fixed extension asap, sorry

**Comment by squadnik** [comment]
No problem ;) I shouldn't update Sketch so quickly. I became tester accidentally :D

**Comment by Soaha** [comment]
I'm waiting for a fix! My designer has already updated Sketch....

**Comment by rychlis** [comment]
Sketch extension 2.1.3 with the fix has been released, sorry for the inconvenience!

**Comment by squadnik** [comment]
Thanks guys! You are incredibly fast! Now I'm convinced to switch to business plan :)
