### ISSUE TITLE
Avocode Error

### ISSUE THREAD

**Issue by yamaks** [avocode/avocode#504]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.4.3-3630f5a
Source UID: undefined
```
TypeError: Cannot read property 'token' of null
    at /home/my/Рабочий стол/Avocode/resources/app.asar/node_modules/@avocode/core/lib/auth.js:1:1614
    at /home/my/Рабочий стол/Avocode/resources/app.asar/node_modules/season/lib/cson.js:180:53
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report. Can you please elaborate more on how did this happen?

**Comment by jakubzitny** [comment]
We have already found the problem causing this error. Next release of Avocode will contain the fix, we will let you know when it's available.

**Comment by petrbrzek** [comment]
We've launched Avocode 2.4.4 beta which should fix this issue, you can download the build from here:

​Mac - https://manager.avocode.com/download/app-beta/mac/

Linux ia32 - https://manager.avocode.com/download/app-beta/linux-ia32/
​Linux x64 - https://manager.avocode.com/download/app-beta/linux/
​Windows - https://manager.avocode.com/download/app-beta/windows/

This will remain in beta for now, if everything goes fine we will enable auto-update to 2.4.4 globally

**Comment by rychlis** [comment]
Avocode 2.4.5 is now live with the fix. Let us know if you still experience the same issue and we will re-open the issue
