### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by ivanprotsko** [avocode/avocode#508]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/prots/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jankuca** [comment]
Thanks for the report. This bug has been addressed and fixed last week. As I see, you have already updated and ran into a different issue (#509); very unfortunate, sorry about that. Please, give us some time to investigate the new issue and get back to you when we have an update.
