### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ivanprotsko** [avocode/avocode#509]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.4 running in Sketch 3.4
```
Error: Sketchtool failed to export pages (25438CDB-AE84-4479-82E0-B0BFCDEEC306)
    at /Users/prots/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/prots/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment]
Hi it would be great if you could send us the sketch file to team@avocode.com and we'll investigate what happened closely and try to export it for you. It seems that Sketchtool failed to export page preview image, which is a problem on Sketch side but we will try to figure out a workaround

**Comment by petrbrzek** [comment]
Closing this one and moving discussion to #513.
