### ISSUE TITLE
Text Shadow doesn't work!

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#51]
All the text-shadow's are not working in CSS Hat and Avocode I end up with something like this:

text-shadow: 0 0 4.9px 0.1px rgba(254, 252, 222, 0.75);

All browsers cross it out i think it has too many values. No matter what text shadow i do it's always wrong from the applications....

**Comment by petrbrzek** [comment]
Fixed in dev release. We'll publish it soon.
