### ISSUE TITLE
Error - Are you ever going to fix this????

### ISSUE THREAD

**Issue by chazchumley** [avocode/avocode#510]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.4 running in Sketch 3.4
```
Error: Sketchtool failed to export pages (3B9C169B-C4F2-47E9-8AAF-975272DB8E39)
    at /Users/cchumley/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/cchumley/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jankuca** [comment]
Hello, thank you for sending in the report. This exact error is not a know issue at all. It was actually first reported today. You might have been getting a different error during last week (related to the newly released Sketch update) but that was already addressed and should not appear again.

We are going to investigate this particular error and hopefully fix it quite soon. Thanks again.

**Comment by rychlis** [comment]
Hi also if you could send us the sketch file to team@avocode.com we'll investigate what happened closely and try to export it for you. It seems that Sketchtool failed to export page preview image, which is a problem on Sketch side but we will try to figure out a workaround
