### ISSUE TITLE
Avocode sketch plugins not working 

### ISSUE THREAD

**Issue by ahmadmansee** [avocode/avocode#512]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4 

I am trying to export to avocode plugins but it's not working , are there any problem with my files ?
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/ahmad.mansee/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment]
Please upgrade to Sketch plugin 2.1.4, you're using an old version that doesn't support Sketch 3.4: https://manager.avocode.com/downloads/#plugins

The plugin should let you know when there is a new version automatically on launch, did it not happen?

**Comment by ahmadmansee** [comment]
i have no idea how to upload the plugins and no it didn't happened could you please provide a link or tutorial on how to update the plugins ?

**Comment by rychlis** [comment]
Just download the sketch extension for mac and install it

**Comment by rychlis** [comment]
Sorry for the terse answer, have you been able to upgrade the extension? Here's a direct link to the latest extension: https://manager.avocode.com/download/sketch-plugin/dmg/

**Comment by rychlis** [comment]
I am closing this issue as it's for an old version of plugin, let me know if you have any questions and feel free to report any new problems
