### ISSUE TITLE
Sketchtool failed to export pages

### ISSUE THREAD

**Issue by shiienurm** [avocode/avocode#513]
Tried to "Sync As New Design" and this happened.

---

Sketch Exporter 2.1.4 running in Sketch 3.4

```
Error: Sketchtool failed to export pages (43328398-519D-49F2-BB53-06FB12372E09)
    at /Users/stefan/…/Avocode/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/stefan/…/Avocode/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by petrbrzek** [comment]
Hi it would be great if you could send us the sketch file to team@avocode.com and we'll investigate what happened closely and try to export it for you. It seems that Sketchtool failed to export page preview image, which is a problem on Sketch side but we will try to figure out a workaround.

**Comment by rychlis** [comment]
So far we've been able to reproduce this problem with documents that contained:
- huge canvas background layer used to emulate a different canvas background color 
- huge grid layers used to create a custom grid
- generally any huge layer, huge in this context usually means >10000px in width or height

Removing such layers would make the Sketchtool work.

We are also working on a new major release of Sketch extension for some time. It fixes a lot of bugs and doesn't use Sketchtool anymore so it would not have this problem. We will let you know when the new version is released.

**Comment by rychlis** [comment]
OK we have just released first beta version of the new extension. See this guide to install and let me know if there are any problems: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by rychlis** [comment]
We've released a second version, see changelog https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#300-prerelease2

This one got update checking so you will be notified about any new beta releases

**Comment by tomrantala** [comment]
@rychlis FYI: The new plugin doesn't allow me to select anything. Here's screen capture https://gfycat.com/LightheartedPoshFox

**Comment by rychlis** [comment]
@tomrantala I've created a new issue for that problem, could you send us your OSX version here please? https://github.com/avocode/avocode/issues/549

**Comment by bolekkerous** [comment]
This shouldn't happen anymore with the latest Sketch plugin.

You can always download the latest version here:

https://manager.avocode.com/downloads/

If you still experience this problem or any other, please create a new issue with it.
