### ISSUE TITLE
Sketch Plugin for Avocado - There was an unexpected error

### ISSUE THREAD

**Issue by davidpong** [avocode/avocode#517]
IMPORTANT: Please try to describe how did it happen.

Getting this error message when trying to Sync a Sketch to Avocode using a plugin from Avocode.

Are there any domains or links that should be whitelisted so this doesn't happen? 

All of the domains listed at the site below have been whitelisted already:
https://avocode.zendesk.com/hc/en-us/articles/205022361-Used-domains-to-whitelist

Are there anymore work arounds you have in mind?

<img width="431" alt="screen shot 2015-11-05 at 5 27 52 pm" src="https://cloud.githubusercontent.com/assets/1155099/10986918/1d68ad60-83e3-11e5-8a08-4f7649602c63.png">

-----
Sketch Exporter 2.1.4 running in Sketch 3.4.1
```
Error: ENOENT, no such file or directory '/Users/administrator/…/avocode.token'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at main (/Users/administrator/…/avocode-exporter/lib/main.js:1:3056)
    at Object.<anonymous> (/Users/administrator/…/avocode-exporter/lib/main.js:1:3473)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

Thanks.

**Comment by onecrazydiamond** [comment]
Having the same issue. Project on hold!

**Comment by jakubzitny** [comment]
Hi guys, thanks for your reports. We are sorry you have these issues with the sync. We are working on a new major release of Sketch extension for some time. It fixes a lot of bugs including this one and we will let you know when the new version is released. It will be soon.

This issue is the same as #464, closing this one.

**Comment by onecrazydiamond** [comment]
Hi, thanks for your reply. I appreciate the update, but this is putting our
project on hold until it's resolved.

**Comment by rychlis** [comment]
There is a beta version of the new extension you can try right now, see this guide to install and let me know if there are any problems: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by onecrazydiamond** [comment]
Thanks, however, zip file fails to extract.

**Comment by rychlis** [comment]
@onecrazydiamond could you give us some more information? How exactly does it fail? A screenshot would be best. And please send us the info to team@avocode.com as it's not part of this issue, thanks
