### ISSUE TITLE
Sketch plugin: not able to chose a project

### ISSUE THREAD

**Issue by JorindeReijnierse** [avocode/avocode#520]
My colleague is trying to upload a design with sketch (she uses the most recent version of both sketch and the avocode plugin). Everything goes well until the moment where you have to select a project. She's logged in but there are no projects in the list and she also can't create a new project.

**Comment by JorindeReijnierse** [comment]
We got it to work after a couple of restarts.

**Comment by rychlis** [comment]
The project loading can take a while as the web app is not really efficient. Good to hear you were able to make it work, sorry for any inconvenience
