### ISSUE TITLE
Avocode crashing when opening PSD

### ISSUE THREAD

**Issue by Chrisriis** [avocode/avocode#522]
This has happened a lot after I upgraded to El Capitan. After updating to 2.4.5, it has happened twice in a row. It loads and says e.g. 10/10, then my Mac freezes completely and I've to do a hard reboot.

**Comment by jakubzitny** [comment]
Hi, thanks for the report. Does this happen with the same PSD or with different ones? If it's the same, can you please send it to team@avocode.com? We'll try to look at the problem and come back with more info.

**Comment by Chrisriis** [comment]
Hello. This has happened to different PSDs. I will test further when I wake up and send you one it's happened to.

**Comment by Chrisriis** [comment]
I have sent a PSD to team@avocode.com now :)

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
