### ISSUE TITLE
Stucked at Assign to project screen

### ISSUE THREAD

**Issue by enzy** [avocode/avocode#526]
Error in console:
```
Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
```

**Comment by vojtatranta** [comment]
Thank you for you report. We will look into our logs for details.
Can you please describe what were you trying to do when this error occured?

**Comment by enzy** [comment]
Uploaded a new design from the Sketch and tried to assign it into project.

**Comment by vojtatranta** [comment]
Thanks. Could you send us this sketch file to team@avocode.com?
It would help us with debugging. This file might be way to big or badly formatted.

**Comment by enzy** [comment]
No I can't, sorry.

**Comment by vojtatranta** [comment]
Alright, I understand, we will put it into our internal issue tracker and we will get to it asap.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
