### ISSUE TITLE
avocode:// protocol not working

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#528]
We are trying out the Avocode product. When viewing comments on a design, we noticed an "Open in Avocode App" button in the upper right. However, when clicking it my browser (Firefox 42.0 on OS X 10.10.5 Yosemite) doesn't seem to understand the protocol.

Expected behavior: Avocode app opens screen

Actual behavior: Firefox displays "The address wasn't understood" with a URL of "avocode://revision-22c9e0b430434b6e9932c4c366f20b0b"

**Comment by jakubzitny** [comment]
This issue has been fixed in [Avocode 2.5.0](http://changelog.avcd.cz/2-5-0-redefined-ui/).
