### ISSUE TITLE
Switch revision

### ISSUE THREAD

**Issue by nblackburn** [avocode/avocode#532]
The ability to switch the revision from the desktop application would be most helpful.

**Comment by vojtatranta** [comment]
Thank you for your interest!
Such feature was already requested [through user voice](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/9053821-as-a-user-i-want-to-view-notes-and-revisions-in-av).

We are currently working on it.
Therefore I close this issue as duplicated.
