### ISSUE TITLE
Can't login to avocode & upload is also not working

### ISSUE THREAD

**Issue by JorindeReijnierse** [avocode/avocode#533]
When I try to login on the website I get a blank page. My colleagues have the same problem and they also can't upload a design via the sketch plugin. After uploading/syncing they end up at a blank page as well.

**Comment by vojtatranta** [comment]
Thank you for your report!
Have you tried new version of Avocode Sketch extension?
Can you please try it at let us know, whether it solved your issues?
Installation notes are here: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by JorindeReijnierse** [comment]
Yes we have the new plugin. But thats not the problem. The problem is the page online where it redirects to after uploading when you have to chose a project. Also login in online without the plugin is not working. https://manager.avocode.com/  shows a blank page.

**Comment by vojtatranta** [comment]
OK. I tried to log in at manager.avocode.com and everything worked as expected.
I assume that you use some normal browsers eg. Firefox or Chrome, right?

**Comment by JorindeReijnierse** [comment]
yes, I tried to login in firefox and chrome on windows but it doesnt work, I get a blank page. My colleague is using chrome on mac and she also gets a blank page. We're not on the same wifi (we work in different locations) so that can't be the problem.

**Comment by vojtatranta** [comment]
In which location do you work? We still cannot reproduce it.

**Comment by JorindeReijnierse** [comment]
We both work in the netherlands (castricum & the hague). Sometimes after a couple of refreshes I get this: (screenshot) 

![screen shot 11-24-15 at 10 37 am](https://cloud.githubusercontent.com/assets/10044471/11363018/84551280-9297-11e5-8768-d5aed5deddd9.PNG)

**Comment by vojtatranta** [comment]
It seems like problem with our CDN provider. We will try to sort it out ASAP.

**Comment by rychlis** [comment]
Could you look into the Console tab and send us a screenshot as well please? Is it a ERR_SPDY_PROTOCOL_ERROR?

**Comment by JorindeReijnierse** [comment]
here's a screenshot:
![screen shot 11-24-15 at 10 48 am](https://cloud.githubusercontent.com/assets/10044471/11363249/ecb89972-9298-11e5-8f57-5b18b49674ef.PNG)

**Comment by JorindeReijnierse** [comment]
that one was firefox,
this one is chrome: 

![screen shot 11-24-15 at 10 49 am](https://cloud.githubusercontent.com/assets/10044471/11363271/1e95f4e4-9299-11e5-9c6a-6c11cf5380bd.PNG)

**Comment by rychlis** [comment]
Thanks a lot. We've reported the issue to our CDN77 provider. Are you on OSX or Windows?

**Comment by dariusb** [comment]
I'm on OSX and https://manager.avocode.com is not accessible for a whole morning. My colleague managed to get somewhat unstyled version of a page, same as in Jorinde's screenshot, but i my browser can't load even that.

**Comment by rychlis** [comment]
Also can you say where in which country are you located? To figure out if it's a problem with a single CDN datacenter (they've got many datacenters across the globe)

**Comment by JorindeReijnierse** [comment]
I'm on Windows. My colleague is experiencing the same problems and she's using chrome on OSX. We're both in the Netherlands

**Comment by dariusb** [comment]
We're from Lithuania

**Comment by rychlis** [comment]
Could you run `traceroute 1485451178.rsc.cdn77.org` please? It would help the provider figure out what's the issue.

**Comment by rychlis** [comment]
Please also try tu run `dig 1485451178.rsc.cdn77.org` and `dig 1.rsc.cdn77.org +trace`. You can send the output here or to team@avocode.com, thanks a lot

**Comment by JorindeReijnierse** [comment]
![screen shot 11-24-15 at 11 33 am](https://cloud.githubusercontent.com/assets/10044471/11364214/32478380-929f-11e5-8a60-2cd5da807f0c.PNG)

**Comment by rychlis** [comment]
Thanks a lot @JorindeReijnierse!
Could you also send us `dig 1485451178.rsc.cdn77.org` and `dig 1.rsc.cdn77.org +trace` dig is not installed on Windows but [can be downloaded](http://www.danesparza.net/2011/05/using-the-dig-dns-tool-on-windows-7/), or it might be easier to ask your colleague to run the command on OSX (it's installed there, just run it in Terminal app)

Thanks a lot

**Comment by JorindeReijnierse** [comment]
I installed it on windows

![screen shot 11-24-15 at 11 47 am](https://cloud.githubusercontent.com/assets/10044471/11364525/39413710-92a1-11e5-8e58-447ec64c5faf.PNG)

**Comment by JorindeReijnierse** [comment]
It seems to be working again!

**Comment by dariusb** [comment]
yup, can confirm this too!

**Comment by rychlis** [comment]
Yhes the CDN provider has fixed the issue, thanks a lot for cooperation
