### ISSUE TITLE
Company name change not reflected in url

### ISSUE THREAD

**Issue by nblackburn** [avocode/avocode#536]
I noticed upon changing the company name, the URL is not changed to reflect that.

**Comment by vojtatranta** [comment]
Thank you for your report!
Do you mean URL in manager.avocode.com?

**Comment by nblackburn** [comment]
Yes, that is correct

**Comment by vojtatranta** [comment]
All right, we take a look at it!
Thanks

**Comment by nblackburn** [comment]
Great, thanks!

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
