### ISSUE TITLE
Toggling layer on/off resets the screen position

### ISSUE THREAD

**Issue by lucien144** [avocode/avocode#537]
This is so annoying http://d.pr/i/icPS

Avocode 2.4.5 on Mac

**Comment by vojtatranta** [comment]
Thank you for your report.
We will put it in our TODO list.

**Comment by Lukavyi** [comment]
Had this bug for a loooong time.

**Comment by bolekkerous** [comment]
This should be already fixed.

If you still encounter this or any other problem, please create a new issue.
