### ISSUE TITLE
it happened when I tried to sync. 

### ISSUE THREAD

**Issue by iAlborz** [avocode/avocode#540]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.4.2
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/iAlborz/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report. We know about this problem, it's been mentioned already in #502, #500 and several others. Let's continue the discussion at #500, I'll close this issue.

I see you have old version 2.1.1 of the Sketch extension. 
Recently we have released new beta version with lot of bugs fixed. Please follow [this guide](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md) to install it. 

If you still have the problem in the future please share the design with us at team@avocode.com, if possible, and ping us at #500.
