### ISSUE TITLE
Sketch character spacing

### ISSUE THREAD

**Issue by bolekkerous** [avocode/avocode#547]
character spacing parameter not showing although it should be

"I just created a fresh test file to see if it was just my particular file I was working with, but I can’t see character spacing show up for this new file either."

![screen shot 2015-11-19 at 13 49 30](https://cloud.githubusercontent.com/assets/16084852/11476649/376cd6aa-9784-11e5-8116-c4ae5bd91d3c.png)

**Comment by jakubzitny** [comment]
This issue has been fixed in [Avocode 2.5.0](http://changelog.avocode.com/2-5-0/).
