### ISSUE TITLE
The new sketch plugin doesn't allow me to select anything on Yosemite

### ISSUE THREAD

**Issue by rychlis** [avocode/avocode#549]
The new plugin doesn't allow me to select anything. Here's screen capture ![capture](http://fat.gfycat.com/LightheartedPoshFox.gif)

created from this comment by @tomrantala: https://github.com/avocode/avocode/issues/513#issuecomment-161318133

**Comment by rychlis** [comment]
@tomrantala what is your OSX version? There seems to be some issue with builtin Safari browser on some machines, we are not able to reproduce this problem so far.

**Comment by tomrantala** [comment]
@rychlis Yosemite 10.10.5 (14F27)

**Comment by rychlis** [comment]
Thanks, we so far registered 3 people with this problem and they were all on Yosemite so it might be related. We're investigating this further

**Comment by tomrantala** [comment]
Ok thanks for the info. I'll update my OS and report again :)

**Comment by rychlis** [comment]
OK we can now reproduce the issue on OS X 10.10.5. A quick workaround:
1. Move your mouse where you want to click
2. Hold ctrl and click, a context menu will appear
3. Release ctrl key and click outside of the context menu but still on the same object you wanted to click

There is something off with the Safari version, hopefully we will find a fix :)

**Comment by rychlis** [comment]
Another possible (and probably more easy) workaround is to open the plugin in your browser (Safari) here: http://127.0.0.1:33162/panel/

Note that the window with plugin must be opened simultaneously for the whole time

**Comment by tomrantala** [comment]
@rychlis I updated my OS to El Capitan and the plugin works now :)

**Comment by marco-uccellini** [comment]
I am using Yosemite and used the workaround - the export worked but the artboards all changed in the Sketch file I was using. For example a certain group of artwork got placed on **every** artboard in the same place. Each canvas was affected and I had to revert back to a backup version of the Sketch file. However the updated versions of each canvas were all added correctly to Avocode.

**Comment by petergeller** [comment]
I have the same issue, i'm on Yosemite 10.10.5,
Chrome 48.0.2564.97 (64-bit)
Version 3.5.1 (25234)

Workaround works to me so far.

Avocode Sync 3.1 seems to be the new plugin under plugins pulldown in sketch,
how can i remove the "Sync to avocode" part which doesn't seem to work anymore, seems to be from an older plugin?

**Comment by clairetaylor** [comment]
I have the same issue. 
Yosemite 10.10.5

I also have the same issue where the old plugin is still in the plugins menu.

**Comment by gabrielagb** [comment]
I'm having the issue as well on Yosemite 10.10.5

**Comment by enguerrandvidor** [comment]
Same issue..

**Comment by marekhrabe** [comment]
Fixed in latest version. Download here: https://avocode-media.s3.amazonaws.com/download/sketch-plugin-beta/3.2.0/sketch-plugin-beta-mac-3.2.0.dmg
