### ISSUE TITLE
When trying to log into the the Windows app I get a CSRF error.

### ISSUE THREAD

**Issue by debiesven** [avocode/avocode#550]
When I try to login on the Windows app I get the following error: "Connection error when requesting CSRF token. Please, check your connection.". I also tried to login using "Login using browser", but this isn't working too.

I get the same error when I try to reset my password: "Connection error when requesting CSRF token. Please, check your connection.".

using Windows 7.

**Comment by rychlis** [comment]
As per our email communication, [using a proxy server](https://avocode.zendesk.com/hc/en-us/articles/203402352-How-to-use-a-proxy-server) fixed this
