### ISSUE TITLE
UI Bug on New Photoshop Update

### ISSUE THREAD

**Issue by vitorfernandes** [avocode/avocode#551]
Check it out:

![screen shot 2015-12-03 at 5 43 58 pm](https://cloud.githubusercontent.com/assets/11338156/11573514/835edd16-99e5-11e5-8b9f-4245a11f8631.png)

**Comment by marekhrabe** [comment]
Can you tell us details about your versions of System nad Photoshop? It doesn't happen on any of our systems and we cannot reproduce it. And despite looking ugly, does the extension sync?

**Comment by vitorfernandes** [comment]
Here:

![screen shot 2015-12-09 at 3 35 20 pm](https://cloud.githubusercontent.com/assets/11338156/11694745/8bc780a8-9e8a-11e5-9797-749718541416.png)
![screen shot 2015-12-09 at 3 35 30 pm](https://cloud.githubusercontent.com/assets/11338156/11694746/8bccbfdc-9e8a-11e5-9a9b-086313978a22.png)


It happened when I updated to the previous version (photoshop).

**Comment by vitorfernandes** [comment]
I found the issue, the problem happens when I set a darker color, as you can see:

![screen shot 2016-01-07 at 6 20 32 pm](https://cloud.githubusercontent.com/assets/11338156/12183120/9e7eacd8-b56b-11e5-9a75-5bc04ae8a120.png)
![screen shot 2016-01-07 at 6 20 43 pm](https://cloud.githubusercontent.com/assets/11338156/12183123/a26035b0-b56b-11e5-9995-98924114b481.png)

It not happens when the default color is setup:

![screen shot 2016-01-07 at 6 20 39 pm](https://cloud.githubusercontent.com/assets/11338156/12183132/afc8f714-b56b-11e5-9e01-1d2a35d48915.png)
![screen shot 2016-01-07 at 6 20 41 pm](https://cloud.githubusercontent.com/assets/11338156/12183134/b14fba00-b56b-11e5-889f-9135df0316c4.png)

**Comment by vitorfernandes** [comment]
@marekhrabe please, fix this! :)

**Comment by jakubzitny** [comment]
Hi @vitorfernandes, we've just released Avocode `3.4.0` with completely redesigned Photoshop plugin. Please update the app or [download the latest version](https://avocode.com/download). When you launch it, your PS plugin will be automatically updated to the latest version.

You can learn more about the newest Photoshop plugin in our [help center](http://help.avocode.com/projects-and-designs/design-upload/how-to-sync-psd-designs-to-avocode-via-photoshop-plugin).
