### ISSUE TITLE
Syncing more than 6 artboards "Burns CPU", Crashes Sketch. Console output included. Files attached. (Sketch Plugin 2.1.5 / OSX 10.11.1)

### ISSUE THREAD

**Issue by mochabcha** [avocode/avocode#553]
This is what console says:

    12/5/15 11:46:44.000 AM kernel[0]: process Sketch[738] thread 12211 caught burning CPU! It used more than 50% CPU (Actual recent usage: 73%) over 180 seconds. thread lifetime cpu usage 91.819019 seconds, (62.048892 user, 29.770127 system) ledger info: balance: 90000692882 credit: 90000692882 debit: 0 limit: 90000000000 (50%) period: 180000000000 time since last refill (ns): 122662458607 
    12/5/15 11:46:48.674 AM spindump[571]: Saved cpu_resource.diag report for Sketch version 3.4.3 (16044) to /Library/Logs/DiagnosticReports/Sketch_2015-12-05-114648_Chans-MacBook-Pro.cpu_resource.diag
    12/5/15 11:46:55.000 AM kernel[0]: low swap: suspending pid 738 (Sketch)

I get a dialog telling me I have no more application memory. Sketch is "(paused)", keeps pausing when I hit Resume.  I split the file into multiple files trying to single out the issue, I find that it does this for anything above 6 artboards for this file.  It hasn't done this with other files as I've been syncing other files this week.

So it's a file specific memory issue.  I now have the file split into 3 parts and they've all uploaded into the system.  The account email address is hello@ingenuity.cc.

It would be amazing if we could get this taken care of as quickly as we can.  I'm paying for the business plan here and I don't exactly expect a rebuild of the plugin...but tell me what the problem is and I'll work around it.  I'd think someone knows enough about the plugin to understand where it breaks.  

Help me not break the plugin and I'll be ok. I hate spending weekend hours trying to deal with bugs.  I'd rather just be aware of them and work around them.

**Comment by vojtatranta** [comment]
Thank you for your report.
Have you tried to use our newest version of Sketch extension?
You can download it here https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md.

**Comment by mochabcha** [comment]
I have 13 projects in my account.  This version doesn't allow me to select which one it's syncing to nor does it allow me to create a new one.  At least make it find the newest project so I can make a project manually and pair it like that.  I can't use this.

And now the old plugin doesn't seem to be working anymore.  I have to uninstall this.

**Comment by marekhrabe** [comment]
Hi, does your problems with selecting projects still happen? We have made significant improvements in this area and it should work smoothly in latest [Sketch Extension 3.2](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update)

**Comment by mochabcha** [comment]
Everything does work significantly better in Avocode now with the new
version. I've stopped using the old version in fact.
