### ISSUE TITLE
Bounded box assets from sketch to avocode

### ISSUE THREAD

**Issue by ryan-wong** [avocode/avocode#555]
The designer tried https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md 
instructions to enable the bounded boxes from sketch and it worked the first time. The next day she changed the sketch files a bit and synced to avocode. However all bounded box disappeared. She tried to remove project, re-add project, uninstall plugin/ reinstall plugin and no luck getting back the bounded boxes. If we can't fix this issue, we will need to go back to using zeplin. The designer has her sketch file opened but modal saying no document open appears. Any solution?
<img width="761" alt="screen shot 2015-12-07 at 2 35 49 pm" src="https://cloud.githubusercontent.com/assets/1930520/11637940/5cf5ac94-9cf2-11e5-8fdc-10328408e8ab.png">

**Comment by rychlis** [comment]
This modal might happen if you used the old extension in the same Sketch session. Restarting Sketch will fix that.

From our email communication we figure out that bounding boxs = slices. We don't export Slices from Sketch so far but will definetely do that in the future. Here's a [feature voting](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/11019489-export-slices-from-sketch) idea you can vote for
