### ISSUE TITLE
other sizes while maintaining image

### ISSUE THREAD

**Issue by volgin-vladimir** [avocode/avocode#556]
Now Avocode Have three dimensions when I'm saving an image:
-1
-0.5
0.25

I offer other sizes:
-0.5x for small displays
-1 original size
-2x for Retina displays

Thank you.

**Comment by petrbrzek** [comment]
We're already working on this feature. You can track this feature here https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6988511-export-vector-shape-layers-as-2x-and-3x.

**Comment by volgin-vladimir** [comment]
Thank you.

**Comment by volgin-vladimir** [comment]
I also would like to be the creation of sprites from the context menu, as "save in sprite". What do you think about it?
