### ISSUE TITLE
Avocode wont notify that update has started

### ISSUE THREAD

**Issue by hakimCZE** [avocode/avocode#557]
When i manualy select Avocode to update, nothing happen for the eye of the user, even that update has started.

**Comment by jankuca** [comment]
Thank you for mentioning this. The update mechanism is going to get updated and will reliably present its progress. We'll let you know when this lands in a stable release.

**Comment by bolekkerous** [comment]
Right now the process should be more transparent:

When there is a new update ready, you should get a pop-up about it. When you choose to download it, the app will download the necessary files in the background and once it is finished, you will get prompt to run the update installation. 

The process should be quite seamless.

Also, when you hit the "Check for update" option, you will see what's happening.

I'll close this issue - if you have any other suggestions or problems, please create a new one.
