### ISSUE TITLE
Avocode wont open after updating

### ISSUE THREAD

**Issue by hakimCZE** [avocode/avocode#558]
After updating Avocode (Mac OS El Captain) from version (2.3.*) to version 2.4.5, application quits (probably to restart) but wont start back. After this, application wont start.
![screen shot 2015-12-09 at 13 12 57](https://cloud.githubusercontent.com/assets/1033729/11685110/eae43edc-9e76-11e5-99ef-f47742cdd770.png)

**Comment by petrbrzek** [comment]
Thanks for reporting the issue. I haven't seen this type of bug yet, weird. I'll test it tomorrow to see if I get the same result. Did you try a new installation? Does it work?

**Comment by hakimCZE** [comment]
Pomohlo stahnout si aktualni verzi a preplacnout s ni predchozi.
