### ISSUE TITLE
Slice tool has no way to correct slice. 

### ISSUE THREAD

**Issue by hakimCZE** [avocode/avocode#559]
On Mac version 2.4.5, slice tool is very inaccurate, with no way to correct the slice selection.

**Comment by jakubzitny** [comment]
Thanks for the report. Can you please share more details about this issue? The best would be, if possible, sharing the design with us at team@avocode.com. You can also attach a screenshot of the inacurrate slices.

**Comment by hakimCZE** [comment]
Hope this video will help
[avocode-slice.mp4.zip](https://github.com/avocode/avocode/files/57954/avocode-slice.mp4.zip)

**Comment by jankuca** [comment]
The slice tool needs to be improved to be a fully usable feature of Avocode. We know about this issue and have is on the roadmap in relatively near future. We'll get back to you with further updates.

**Comment by rodnem** [comment]
Arggg it kills me on mac
There's no way to edit a slice

**Comment by petrbrzek** [comment]
It's editable from 2.8.x. I'm closing it now.
