### ISSUE TITLE
Syncing seems broken with new version of Sketch

### ISSUE THREAD

**Issue by ajilderda** [avocode/avocode#562]
I'm having issues with Sketch Exporter 2.1.5 on  Sketch 3.4.4. Crashes after step 1 is finished

**Comment by marekhrabe** [comment]
Please try our beta and let us know if it worked for you https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by bomberstudios** [comment]
Sorry about that, that's totally our fault. We'll be releasing an updated 3.4.4 later today that fixes the issue.

**Comment by ajilderda** [comment]
Thanks Marek & Ale, it worked! Don't know if it was the Sketch update or the Avocode Sync Beta (which looks & works great! Great improvement!).

Best regards,
Andre

Btw. sorry for the short bug report! I had to leave for a meeting. :)

**Comment by rychlis** [comment]
Great to hear that and thanks a lot @bomberstudios for the comment :)
