### ISSUE TITLE
Already set variables not being subbed in

### ISSUE THREAD

**Issue by HugoDF** [avocode/avocode#571]
I annotated an artboard of a project with some variables, when I opened another artboard, these variables weren't being recognised.

They correctly replaced the values when I re-saved them.

**Comment by jakubzitny** [comment]
Hi, thanks for sharing this issue with us. We are planing to improve variable saving and syncing in the future. Currently there are some small bugs and variables are lost after logout.

In upcoming release Avocode will be able to save the variables between logouts and logins. Later, we will also add other improvements. Feel free to vote for `Sync rules and variables across multiple computers but also teams` at UserVoice.

This is related to #145 and #418.

**Comment by jakubzitny** [comment]
Hi, thanks for sharing the issue with us. Currently, there are some bugs here and variables are not being saved after logouts. We are planing several enhancements to variable saving and syncing.

In the upcoming release, Avocode should be able to save variables between logouts and logins. Later we are planning to support sync. Feel free to vote for [this issue at UserVoice](http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7126248-sync-rules-and-variables-across-multiple-computers).

This is related to #148 and #415.

**Comment by bolekkerous** [comment]
Variables are now project-wide and should be locally kept even after logging in and out.

If you experience any issue with that, please create a new issue.
