### ISSUE TITLE
[Linux] TypeError: matchFont is not a function

### ISSUE THREAD

**Issue by zedtux** [avocode/avocode#574]
I'm starting Avocode, logging in and then it crash.

I'm running a Debian GNU/Linux stretch/sid 64-bit
 
-----
App v.2.4.5
Source UID: undefined
```
TypeError: matchFont is not a function
  at /home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/document.js:1:4560
  at /home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/lodash/index.js:2275:27
  at /home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/lodash/index.js:3073:15
  at baseForOwn (/home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/lodash/index.js:2046:14)
  at /home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/lodash/index.js:3043:18
  at baseMap (/home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/lodash/index.js:2274:7)
  at Function.map (/home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/lodash/index.js:6710:14)
  at e._processFonts (/home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/document.js:1:4497)
  at new e (/home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/document.js:1:4028)
  at /home/zedtux/Downloads/Avocode-linux-x64/resources/app.asar/node_modules/@avocode/core/lib/user.js:1:21649
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

**Comment by zedtux** [comment]
Actually, I have couple of issues with avocode at different steps until I run it as root user.
I can upload a PSD, and use it but it crash sometimes.

**Comment by vojtatranta** [comment]
Thank you for your report.
Sorry for delayed answer.
Sharing the PSD with us at team@avocode.com would be great, thank you.
We have not yet encountered with such problem.
You say that if you run Avocode as normal user you get these errors? Not as root?

**Comment by zedtux** [comment]
> You say that if you run Avocode as normal user you get these errors? Not as root?

Yes ! There are couple of errors (I have reported only one) when running the app with my system user. Using `sudo` is fixing the issue and I'm able to use Avocode.

I don't think sharing the PSD is really helpful as when running as root all is working fine, but if you really want it, I could do it.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by zedtux** [comment]
Thank you @connor-bean for this update. Nice. However my trial period is over since a long time, I have to re-create an account.

**Comment by connor-bean** [comment]
Hey @zedtux -

I just extended your trial for another month. Please email me at team@avocode.com if you have any problems logging in.

Thanks!
Connor, Avocode Support

**Comment by zedtux** [comment]
Awesome @connor-bean :) I'll try it soon.

**Comment by zedtux** [comment]
@connor-bean it's working fine! Good job.
