### ISSUE TITLE
Windows 7 install fail + Portable version fail

### ISSUE THREAD

**Issue by alexander812** [avocode/avocode#577]
I tried to use avocode on my windows 7 SP1 6.1.7601 build 7601, but installation stops with error (no any usefull information in error description), I tried portable version, it's opened but crushed when I tried to open project. Tried app-beta-windows-2.4.4.exe, the same result.

Please help.

**Comment by vojtatranta** [comment]
Thank you for your report.
Have you tried version 2.4.5 where we update Electron core of the app?
You can download it here: http://avocode.com/download/

**Comment by rychlis** [comment]
Also the 2.5.2 fixed a lot of installer errors so I am closing this issue. If you still have any issues with 2.5.2, feel free to report a new issue :)
