### ISSUE TITLE
oops

### ISSUE THREAD

**Issue by euegenep** [avocode/avocode#581]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.4
```
Error: Sketchtool failed to export pages (A1948C6E-4D4A-416C-87EF-E5B4033BE97F)
    at /Users/mac/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/mac/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by vojtatranta** [comment]
Thank you for your report.
I see that you are using older version of Avocode Sketch Extension, you may try to use version 3B, more info here: https://github.com/avocode/avocode/issues/568
