### ISSUE TITLE
Potřebuji poradit...

### ISSUE THREAD

**Issue by dominiksefl** [avocode/avocode#583]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.4
```
Error: Sketchtool failed to export pages (FB680856-685A-47A2-A0DA-6113690A5E06)
    at /Users/dominiksefl/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/dominiksefl/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by vojtatranta** [comment]
This is known issue, you should use newer version of export.
You can take a look here, where you cant find solution https://github.com/avocode/avocode/issues/561
Closing as duplicated.

**Comment by dominiksefl** [comment]
Dobře, děkuji.
