### ISSUE TITLE
Failure to upload file to Avocode

### ISSUE THREAD

**Issue by melcassio** [avocode/avocode#584]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.4
```
Error: Sketchtool failed to export pages (99864DBF-918A-4522-9624-56F86DA10D7E)
    at /Users/mcassio/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/mcassio/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by vojtatranta** [comment]
That's known issue with newer version of Sketch.
Here is solution to you problem https://github.com/avocode/avocode/issues/561.
Closing as duplicated.
