### ISSUE TITLE
Sync to Avocode fails – even after restart of Mac and Sketch

### ISSUE THREAD

**Issue by MarkLopresto** [avocode/avocode#585]
IMPORTANT: Please try to describe how did it happen.

After export of first artboard – which happens to be the largest – is successful, once arriving to second, dialog box shows and export ceases. 

Reboot Mac and Sketch. No other dock applications running.

I will try again later today, possible sync issue with Avocode cloud host? 

-----
Sketch Exporter 2.1.5 running in Sketch 3.4.4
```
Error: Sketchtool failed to export pages (64A23107-84B1-4830-A806-8AFCA798FA70)
    at /Users/markus/…/avocode-exporter/lib/image-exporter.js:1:935
    at /Users/markus/…/avocode-exporter/lib/image-exporter.js:1:484
    at Object.oncomplete (fs.js:107:15)
```

**Comment by MarkLopresto** [comment]
I think I am seeing a newer plug-in available. I will download latest update and try again.

**Comment by vojtatranta** [comment]
Thank you for your report!
Yes, I would recommend you to do same thing.
We also would like you to write us whether it worked or not, so that we could close this issue.

**Comment by MarkLopresto** [comment]
New extension works well. You now have the ability to individually select artboards, or select all. Syncing seems faster. 

I would recommend that you create the project first via the web application, or the native application and sync up. You may have to restart Sketch and Avocode's pre-release plug-in to see your project in the dropdown of the plug-ins dashboard. Otherwise your files may not appear on the web or in the app. The Avocode team is working on this now. 

If you do not see your files after syncing with the pre-release plug in. Send them an email and they will get your files in the correct location. 

You can close this issue now.

**Comment by vojtatranta** [comment]
Thank you for your attention to our project.
You are welcome to ask anything later on.

**Comment by MarkLopresto** [comment]
Great! Thank you for your instant support and building an exceptional tool.

On Tue, Jan 5, 2016 at 9:25 AM vojtatranta <notifications@github.com> wrote:

> Thank you for your attention to our project.
> You are welcome to ask anything later on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avocode/avocode/issues/585#issuecomment-169014812>.
>
-- 
Check my availability and book a meeting with me at vyte.in/spyderhausdesign

Thank You!
Mark Lopresto
SpyderHausDesign.com
(512) 931-4622
