### ISSUE TITLE
App installed won't run

### ISSUE THREAD

**Issue by ciprianparaschiv** [avocode/avocode#586]
After a clean install of this app I'm getting the attached errors. Can anyone help us with this ?
![screen shot 2016-01-05 at 13 39 09](https://cloud.githubusercontent.com/assets/14816997/12114367/d849faf0-b3b1-11e5-93b6-10867dd4187e.png)
![screen shot 2016-01-05 at 13 39 21](https://cloud.githubusercontent.com/assets/14816997/12114379/0059f3ba-b3b2-11e5-8a23-7f4c860a1331.png)

**Comment by vojtatranta** [comment]
You may have corrupted zip file of the App or it might have been wrongly extracted.
Can you please try to download file zip again a try installing in? 
Download link: http://avocode.com/download

**Comment by ciprianparaschiv** [comment]
Hi there,

Thanks for your quick reply, but I'm getting the same error. Weird ! Any other suggestion ?

Cheers,
Ciprian

**Comment by vojtatranta** [comment]
Happy to help.
We have not yet encountered such issue, so I tried to google some it and found [this](https://discuss.atom.io/t/dont-work-with-mac-osx-10-9-2/6019/3).
So - do you use standard unpacking utility to unpack app zip? Or you have some other software such as iZip or Unarchiver?

**Comment by ciprianparaschiv** [comment]
I'm using the Unarchiver.

**Comment by ciprianparaschiv** [comment]
I managed to fix it. It was because of the unarchiver software.

Have a great day !

**Comment by vojtatranta** [comment]
Oh, that's great. It is a flaw of Electron, unfortunately there is not much we can do about it.
So we apologize for that, we will report it to Github's Electron.
You are welcome to ask anything if you need.

We will close this issue once we have .dmg installer for OS X.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
