### ISSUE TITLE
Some font-weights are missing.

### ISSUE THREAD

**Issue by lucien144** [avocode/avocode#587]
Any chance to check this?
https://github.com/avocode/avocode/issues/32#issuecomment-169349040

**Comment by jankuca** [comment]
Hello, thanks for your input. We'll discuss this further in the team and let you know.
Cheers! —Jan

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
