### ISSUE TITLE
Project manger not showing designs (v2.5beta)

### ISSUE THREAD

**Issue by lucien144** [avocode/avocode#589]
Sometimes the project manager does not show designs or if does, then less than it should.

http://d.pr/i/15D5x

Refresh button does not help.

**Comment by jankuca** [comment]
Thanks for your report and for testing the beta version of 2.5. We are looking into this.

**Comment by rychlis** [comment]
I think this should be fixed in 2.5.2. Let us know if you can still experience the issue
