### ISSUE TITLE
Page shown in menu but not in project overview

### ISSUE THREAD

**Issue by martinhalik** [avocode/avocode#591]
Here is only one homepage general -
<img width="1030" alt="screen shot 2016-01-12 at 09 09 05" src="https://cloud.githubusercontent.com/assets/4222361/12258110/5c55c5ae-b90c-11e5-8eb9-fd68365e028d.png">

and here are 2 of them - 
<img width="930" alt="screen shot 2016-01-12 at 09 09 14" src="https://cloud.githubusercontent.com/assets/4222361/12258111/5c56e8f8-b90c-11e5-8e44-98125617f577.png">

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
