### ISSUE TITLE
[Linux] Avocode desktop file and app icon

### ISSUE THREAD

**Issue by romanlex** [avocode/avocode#593]
In Aur Avocode doesn't have desktop file and app icon :(

**Comment by vojtatranta** [comment]
Thank you for your report.
Extracted .zip with avocode properly? Have you used ubuntu's default unarchiver?

**Comment by romanlex** [comment]
I'm install avocode from AUR in Manjaro linux dist.
In .zip with avocode .desktop file also missing. I could do it myself, but I can't also find the application icon.

**Comment by rychlis** [comment]
We did pack PNG icon into the zip before, but it seems like this is broken since 2.4.4 build. We will definitely put the icon back there in the next release.

In the meanwhile I've uploaded the icon here: https://media.avocode.com/download/avocode-app-icon.png

**Comment by stdex** [comment]
Also would be nice to append add_menu.sh script.

**Comment by rychlis** [comment]
The PNG icon is now back in the latest Avocode 2.5.2, it's packed as `avocode.png` in the app directory

**Comment by romanlex** [comment]
@rychlis update please Avocode to last actual version in AUR :)
