### ISSUE TITLE
Edit export name deletes slice. 

### ISSUE THREAD

**Issue by ardkevin84** [avocode/avocode#600]
Sorry, I'm stuck on Windows so I can't get a stack trace :( but: 
Editing my png export name deletes the selected slice. 
#### steps to reproduce
1. using the slice tool, draw a slice. 
2. with the slice selected, right-click and select save as png 
3. enter some text for the png name, then press backspace. 
#### expected behavior

The text in the png name box will be edited 
#### actual behavior

The slice still has focus, so the backspace key deletes it.

**Comment by jankuca** [comment]
Hello, thanks for the report. You are right, I can reproduce this. We'll look into it.

For now, please use the Export panel on the right to rename the slice and choose the format:

![screen shot 2016-01-19 at 8 01 53 pm](https://cloud.githubusercontent.com/assets/367262/12428884/80841058-bee7-11e5-900d-1377aa08efcc.png) ![screen shot 2016-01-19 at 8 00 27 pm](https://cloud.githubusercontent.com/assets/367262/12428870/734dfe9e-bee7-11e5-957e-e122f3113d47.png)

**Comment by bolekkerous** [comment]
This should not happen anymore with the latest version of the app.

You can always download the latest version here:

https://manager.avocode.com/downloads/

If you still experience this problem or any other problem, please create a new issue or comment here.
