### ISSUE TITLE
[suggestion] multiple scss variables

### ISSUE THREAD

**Issue by CosticaPuntaru** [avocode/avocode#602]
in a project you usually have ~50 or more global variables.
it will be nice to copy paste scss from file and paste it in some importer, and extract variables from there.
manually adding every variable is annoying 

and a import/export variables functionality will be nice

**Comment by jankuca** [comment]
Hello. Thanks for the suggestion. We will be focusing on improving variable as well as export rule management in the coming months.

[You can upvote this feature request on UserVoice](http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/11136447-import-variables). There is also [a request for variable syncing](http://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7126248-sync-rules-and-variables-across-multiple-computers) if you'd be interested in that as well.

You can follow the progress of these features there.

**Comment by bolekkerous** [comment]
This is something we're thinking about - I'll close this issue and you can follow the progress on another issue #1134 (there are more comments).
