### ISSUE TITLE
Sketch Sync Plugin: "unexpected error"

### ISSUE THREAD

**Issue by robjohns1** [avocode/avocode#603]
I've been trying all morning to sync a sketch document to Avocode but keep receiving an error message: 

Error: Command failed: 2016-01-22 13:25:22.339 sketchtool[52888:430758] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
2016-01-22 13:25:22.339 sketchtool[52888:430758] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
Failed to open document sketchFile.sketch
((null) MSDocumentDomain:11)

Been trying to report this issue but the page is taking too long to load (unicorn). 

Any help would be appreciated.

**Comment by vojtatranta** [comment]
Hi, thanks for your report.
Do you know which version of Avocode Sketch Extension do you use?

**Comment by rychlis** [comment]
What version of Sketch and Sketch extension are you using?

You can also try Avocode Sketch Extension 3 which is in beta currently, it should not be affected by this issue: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by robjohns1** [comment]
ISketch Version 3.5 (25232) 
Sketch Beta Version 3.5 (25229)

Thanks for the new plugin. I've been testing it on both Sketch & Beta. So far It's been stuck at a 50% loading bar for for over 30 mins. Tried restarting both sketch and sketch beta and running the Avocode beta extension, but the same thing happens. Any tips? 


![screen shot 2016-01-26 at 9 41 39 am](https://cloud.githubusercontent.com/assets/16843627/12587336/23d9aea6-c411-11e5-849f-6a9551060247.png)

**Comment by pablorcgjn** [comment]
The same BUG

Error: Command failed: 2016-01-26 19:27:21.785 sketchtool[1475:1906642] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
2016-01-26 19:27:21.786 sketchtool[1475:1906642] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked

**Comment by pablorcgjn** [comment]
Sketch 3.5
Avocode Version 2.5.2

**Comment by CyrusDG** [comment]
Any update on this? I'm not able to sync now

**Comment by pablorcgjn** [comment]
:(((( Nothing

**Comment by rychlis** [comment]
Hi, Sketch 3.5 was released just few hours ago and broke our plugin unfortunately. We're working on a fix that should be ready today.

If you need to use Avocode before that download Sketch 3.4.4 for now: http://download.sketchapp.com/sketch-3.4.4.zip

**Comment by CyrusDG** [comment]
Unfortunately my sketch files now will only work with Sketch 3.5. I'll have
to wait for a fix, I guess.

Unless anyone knows a way to get a Sketch 3.5 file to work with 3.4.4

**Comment by michaelbina** [comment]
I'm having the same problem.  Wondering if you guys think this is gonna a be a quick or if I should look into downgrading to 3.4.4 for now.

Anyone know where I can get a 3.4.4 download link?

**Comment by CyrusDG** [comment]
It was mentioned in one of the recent comments @michaelbina.  Here it is again

**Comment by michaelbina** [comment]
Missed that.  Thanks :-)

**Comment by rychlis** [comment]
@CyrusDG
> Unfortunately my sketch files now will only work with Sketch 3.5. I'll have to wait for a fix, I guess.

There is a possible workaround:
0. Make a backup of the latest document in case you made changes since updating Sketch to 3.5
1. Open the document in the new Sketch 3.5
2. In upper menu select File -> Revert To -> Browse All Versions...
3. Select the document from 3.4.x and click on Restore button
4. Close Sketch 3.5 (don't save the document!) and you will be able to open the document in Sketch 3.4.4 now

**Comment by al1zoin** [comment]
That option did not work for me since I've made a lot of changes in my mock-up since updating to Sketch 3.5.1. Will need for you to come up with a plugin fix in order to be able to further use Avocode. It's bad since we are using it for business purposes... But, I get it that you've been taken unaware.

Will patiently wait for a solution! Thanks.

**Comment by rychlis** [comment]
We have released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

We're working on updating the older Sketch Plugin 2.1.5 however there has been some further new issues with Sketch 3.5 that affects just the older 2.1.5 plugin. You should be able to use the beta version fine though.

Follow #609 for more updates about older Sketch plugin, I am closing this issue as a duplicate, thanks for the report

**Comment by robjohns1** [comment]
The error message has gone away and the Artboard seems to be successfully syncing within the Sketch 
3.0 extension in Sketch Beta. That said, the artboard isn't actually syncing in the Avocode app, even after  restarting the app and refreshing multiple times over the past 15 minutes.

**Comment by rychlis** [comment]
@robjohns1 could you please give us an email at team@avocode.com so we can look into your account and find out what's wrong individually? Thanks
