### ISSUE TITLE
Can't start Avocode app on Linux Fedora

### ISSUE THREAD

**Issue by msilberg** [avocode/avocode#604]
When I'm trying to open Avocode app I get the following:
```
./Avocode 
[23906:0125/010603:ERROR:browser_main_loop.cc(171)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[23960:0125/010603:INFO:renderer_main.cc(200)] Renderer process started
[23906:0125/010604:ERROR:cert_verify_proc_openssl.cc(231)] X509 Verification error unable to get local issuer certificate : 20 : 2 : 4
```
I'm even able to see its processes:
```
ps aux | grep Avocode
mike     23906  1.1  0.7 2056364 92212 pts/2   Sl+  01:06   0:00 /home/mike/Soft/System/Avocode-linux-x64/Avocode
mike     23909  0.0  0.2 449020 26652 pts/2    S+   01:06   0:00 /home/mike/Soft/System/Avocode-linux-x64/Avocode --type=zygote --no-sandbox
mike     23950  0.1  0.4 563028 53352 pts/2    Sl+  01:06   0:00 /home/mike/Soft/System/Avocode-linux-x64/Avocode --type=gpu-process --channel=23906.0.1660970759 --no-sandbox --supports-dual-gpus=false --gpu-driver-bug-workarounds=1,12,15,42 --disable-accelerated-video-decode --gpu-vendor-id=0x8086 --gpu-device-id=0x0166 --gpu-driver-vendor --gpu-driver-version
mike     23960  0.2  0.5 1117904 71548 pts/2   Sl+  01:06   0:00 /home/mike/Soft/System/Avocode-linux-x64/Avocode --type=renderer --force-device-scale-factor=1 --js-flags=--harmony --no-sandbox --enable-deferred-image-decoding --lang=en-US --node-integration=true --subpixel-font-scaling=false --enable-pinch-virtual-viewport --enable-delegated-renderer --num-raster-threads=2 --disable-accelerated-video-decode --channel=23906.1.399899954
```
But there's no any visible window or at least icon of the app.

**Comment by vojtatranta** [comment]
Hi,
we are sorry that you have this issue.
It is our fault. There is a problem with certificates that we use for Avocode binaries.
We are currently releasing fix for this error.
Meanwhile, this should help: ```$ ./Avocode --ignore-certificate-errors```

**Comment by rychlis** [comment]
Some more information - this [bug](https://github.com/atom/electron/issues/1680) was fixed in electron v0.29.2 but we use an older version unfortunately. We're now in process of upgrading to a more fresh version that will fix this issue

**Comment by msilberg** [comment]
Thanks for the quick response. The workaround you've offered did work for me.

**Comment by vojtatranta** [comment]
As @rychlis said. We have to update Electron, which is Avocode's core engine. We are planning to release such updated during February.
Thanks for your patience.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
