### ISSUE TITLE
Error SYNC Avocode

### ISSUE THREAD

**Issue by pablorcgjn** [avocode/avocode#610]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5
```
Error: Error: Command failed: 2016-01-26 20:10:01.410 sketchtool[1666:2110475] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by bolekkerous** [comment]
Hi,
Sketch 3.5 was released just few hours ago and broke our plugin unfortunately. We're working on a fix that should be ready later today.

If you need to use Avocode before that download Sketch 3.4.4 for now: http://download.sketchapp.com/sketch-3.4.4.zip

If there is a problem with sketch file versions, you can either use the revert-to option in Sketch or check this artilcle about hidden folder with previous Sketch revisions:
https://medium.com/sketch-app-sources/how-to-recover-50-go-or-even-more-by-deleting-sketch-caches-files-e5829dba20e1#.ktu3bcz81

You can follow the status in the issue #609, I am closing this issue as duplicate. Thanks for your report.

**Comment by rychlis** [comment]
We have just released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

We're working on updating the older Sketch Plugin 2 however there has been some further issues with Sketch 3.5 unfortunately. You should be able to use the beta version fine though

**Comment by pablorcgjn** [comment]
Continues to fail, but less this update. At least I uploaded some designs

**Comment by bolekkerous** [comment]
Hello!
Could you please contact us with what exactly fails at team@avocode.com?

Thank you and sorry for the inconvenience.

**Comment by pablorcgjn** [comment]
Ok! Thanks!
