### ISSUE TITLE
Image width & height

### ISSUE THREAD

**Issue by polikin** [avocode/avocode#62]
Adding the possibilty to export or not the width and height of an image.

**Comment by petrbrzek** [comment]
Do you mean width and height attributes in get code modal window?

**Comment by polikin** [comment]
Get code window (Code for asset)

**Comment by petrbrzek** [comment]
Yeah, we can add options to settings. I'm adding it to our roadmap.

**Comment by polikin** [comment]
Thanks!

**Comment by rychlis** [comment]
This is now implemented

**Comment by polikin** [comment]
perfect!
