### ISSUE TITLE
Trying to upload file to Avocode

### ISSUE THREAD

**Issue by melcassio** [avocode/avocode#631]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-01-27 08:06:32.059 sketchtool[87870:352081] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by rychlis** [comment]
We have just released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

We're working on updating the older Sketch Exporter 2 however there has been some other issues with Sketch 3.5 unfortunately, but you should be able to use the beta version fine
