### ISSUE TITLE
Updated Sketch (3.5.1) has Sync Fail

### ISSUE THREAD

**Issue by mountainCLYDE** [avocode/avocode#633]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-01-27 07:49:58.560 sketchtool[967:71425] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by rychlis** [comment]
We have just released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

We're working on updating the older Sketch Plugin 2 however there has been some further issues with Sketch 3.5 unfortunately. You should be able to use the beta version fine though

Follow #609 for more updates about older Sketch plugin, I am closing this issue as a duplicate, thanks for the report
