### ISSUE TITLE
Export Sketch via Plugin

### ISSUE THREAD

**Issue by tekdope** [avocode/avocode#639]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-01-27 10:31:11.244 sketchtool[11840:11102114] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by bolekkerous** [comment]
Hello!
We have already released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

I am closing this issue as a duplicate, if there would be a problem with the new extension, please follow up on #609

Thank you and sorry for the inconvenience.
