### ISSUE TITLE
Exporting to avocode error

### ISSUE THREAD

**Issue by tanogalego** [avocode/avocode#640]
IMPORTANT: Please try to describe how did it happen.
Any idea around this?
-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
TypeError: Cannot read property 'width' of undefined
    at /Users/automative/…/avocode-exporter/lib/exporter.js:1:7873
    at /Users/automative/…/avocode-exporter/node_modules/image-size/lib/index.js:88:25
    at /Users/automative/…/avocode-exporter/node_modules/image-size/lib/index.js:41:23
    at Object.oncomplete (fs.js:107:15)
```

**Comment by bolekkerous** [comment]
Hello!
We have already released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

I am closing this issue as a duplicate, if there would be a problem with the new extension, please follow up on #609

Thank you and sorry for the inconvenience.
