### ISSUE TITLE
Sync to avocode does nothing.

### ISSUE THREAD

**Issue by shriiimp** [avocode/avocode#641]
With Sketch 3.4 (15575) and plugin 2.1.5. I've tried everything (uninstalling both, re-installing, rebooting, manual install, dmg install, empty, small, big documents...) and nothing happens when I click on Sync to Avocode. And the .log file stays empty.

**Comment by bolekkerous** [comment]
Hello!
We have already released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

I am closing this issue as a duplicate, if there would be a problem with the new extension, please follow up on #609

Thank you and sorry for the inconvenience.
