### ISSUE TITLE
New Bug Syncing With Sketch

### ISSUE THREAD

**Issue by nathanwinkel** [avocode/avocode#644]
Updated both Sketch to the most current version and also downloaded the most current version of the Sketch plugin from the Avocade website. 

Sync starts and then after 3/3 at uploading layers it crashes. 

N

Here is the text.

Error: Command failed: 2016-01-27 23:27:58.163 sketchtool[2424:827797] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
2016-01-27 23:27:58.163 sketchtool[2424:827797] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
Failed to open document file:///Users/nathanwinkel/Dropbox%20(LaunchPad%20Central)/Design/V2%20Webapp/Master%20UX%20and%20Visual/Activity%20Feed.sketch
((null) MSDocumentDomain:11)

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-01-27 23:23:50.880 sketchtool[2403:802266] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by bolekkerous** [comment]
Hello!
We have already released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

I am closing this issue as a duplicate, if there would be a problem with the new extension, please follow up on #609

Thank you and sorry for the inconvenience.
