### ISSUE TITLE
I cant export my design to Avocode

### ISSUE THREAD

**Issue by CasperHach** [avocode/avocode#649]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-01-28 14:07:48.950 sketchtool[732:480299] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by rychlis** [comment]
We have released Sketch Extension 3.0.0-prerelease4 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

We're working on updating the older Sketch Plugin 2 however there has been some further issues with Sketch 3.5 unfortunately. You should be able to use the beta version fine though

Follow #609 for more updates about older Sketch plugin, I am closing this issue as a duplicate, thanks for the report and sorry for the inconvenience

**Comment by CasperHach** [comment]
Unfortunately that did not help :(

![skaermbillede 2016-01-29 kl 11 45 38](https://cloud.githubusercontent.com/assets/16938178/12673577/d96541fe-c67d-11e5-85b5-572108e74e22.png)

**Comment by rychlis** [comment]
I don't think you are running the new extension, this is an error from the old one
