### ISSUE TITLE
Windows: The PS plugin refuses to update the design

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#65]
When I press "Update" after syncing, the plugin didn't do anything and I had to submit the design as a new page and delete the old one.

**Comment by petrbrzek** [comment]
Is this still a problem with the current release?

**Comment by VPenkov** [comment]
Cannot confirm due to another issue (https://github.com/avocode/avocode/issues/91)

**Comment by lucien144** [comment]
It seems to be fine now, but I've run into another issue -> #95

**Comment by petrbrzek** [comment]
Feel free to reopen this issue. I'm going to close it now.
