### ISSUE TITLE
can't import from sketch

### ISSUE THREAD

**Issue by stepjan** [avocode/avocode#665]
with prelease version is quite better, but still broken...

Open sketch, run avocode plugin, select page, select project test, click sync artboard, everything looks fine, but my project is still empty...

https://manager.avocode.com/organization-projects/48803/petr-sykora/test-3z0km2/

![snimek obrazovky 2016-01-29 v 13 35 52](https://cloud.githubusercontent.com/assets/7867702/12675868/ad4b3686-c68d-11e5-8952-0109da6c56de.png)

In console of popup page is:

[Error] Failed to load resource: Could not connect to the server. (ping, line 0)
[Error] Failed to load resource: Could not connect to the server. (ping, line 0)
[Error] Failed to load resource: Could not connect to the server. (ping, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Error] Failed to load resource: the server responded with a status of 400 (BAD REQUEST) (login, line 0)
[Warning] Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of ProjectSelector. See https://fb.me/react-warning-keys for more information. (main.js, line 44676)
[Warning] Warning: Failed propType: Required prop `options` was not specified in `Select`. Check the render method of `ProjectSelector`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid child context `selectedProject` of type `number` supplied to `App`, expected `string`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid context `selectedProject` of type `number` supplied to `ProjectSelector`, expected `string`. Check the render method of `footer`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid child context `selectedProject` of type `number` supplied to `App`, expected `string`. (main.js, line 44676, x16)
[Warning] Warning: Failed Context Types: Invalid context `selectedProject` of type `number` supplied to `ProjectSelector`, expected `string`. Check the render method of `footer`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid child context `selectedProject` of type `number` supplied to `App`, expected `string`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid context `selectedProject` of type `number` supplied to `ProjectSelector`, expected `string`. Check the render method of `footer`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid child context `selectedProject` of type `number` supplied to `App`, expected `string`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid context `selectedProject` of type `number` supplied to `ProjectSelector`, expected `string`. Check the render method of `footer`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid child context `selectedProject` of type `number` supplied to `App`, expected `string`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid context `selectedProject` of type `number` supplied to `ProjectSelector`, expected `string`. Check the render method of `footer`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid child context `selectedProject` of type `number` supplied to `App`, expected `string`. (main.js, line 44676, x16)
[Warning] Warning: Failed Context Types: Invalid context `selectedProject` of type `number` supplied to `ProjectSelector`, expected `string`. Check the render method of `footer`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid child context `selectedProject` of type `number` supplied to `App`, expected `string`. (main.js, line 44676)
[Warning] Warning: Failed Context Types: Invalid context `selectedProject` of type `number` supplied to `ProjectSelector`, expected `string`. Check the render method of `footer`. (main.js, line 44676)

**Comment by bolekkerous** [comment]
Hello!
We have released stable version of new extension, where this should be fixed.

Could you please try it with that one? You can download it here:
https://manager.avocode.com/downloads/#plugins

Let me know whether it helps!

**Comment by stepjan** [comment]
I installed 3.1 beta, some bugs was fixed (sync to a new project etc.), but my design is still empty...

in console of the sync window was maybe it helps
`
Failed to load resource: Could not connect to the server http://127.0.0.1:33162/_panels/ping?callback=init&random=0.10630658804439008
`

**Comment by bolekkerous** [comment]
Hello!
Could you please hit us up at team@avocode.com with the e-mail of your account, so I can check whether the designs were actually uploaded to Avocode or not?

We're sorry for the inconvenience. 
Thanks!

**Comment by bolekkerous** [comment]
This bug should be fixed by the Sketch extension version 3.0.0+, if you encounter this problem again with those versions, just let us know and we'll reopen this issue.

**Comment by stepjan** [comment]
bohužel...

3.1. beta - nejnovejsi co sem si mohl stahnout z https://manager.avocode.com/downloads/#plugins
vse se tvari ze probehlo ok, ale vsechny me projekty jsou stale prazdne...  viz https://manager.avocode.com/organization-projects/48803/petr-sykora/

![snimek obrazovky 2016-02-02 v 11 59 00](https://cloud.githubusercontent.com/assets/7867702/12747474/7b9283f0-c9a4-11e5-859a-3c0ebbb1e307.png)
![snimek obrazovky 2016-02-02 v 11 56 27](https://cloud.githubusercontent.com/assets/7867702/12747475/7ba2d084-c9a4-11e5-87bb-73b8f70de9c7.png)

**Comment by bolekkerous** [comment]
Dobrý den,
pokud je Vaše e-mail adresa js@seznam.cz, podívejte se tam prosím na naši odpověď, která by měla vyřešit tento problém. Design byl uploadnutý, ale neni přiřazen k projektu, v e-mailu máte link na přiřazení. Tato chyba by se při syncování nových designů novou verzí neměla opakovat, tady pravděpodobně přetrvává proto, že byl design dříve syncnut předchozí verzí. Pokud se bug bude opakovat i při jiných designech syncnutých rovnou verzí 3.1, dejte nám prosím vědět.

Dejte nám prosím vědět, jestli Vám řešení v e-mailu pomohlo.

**Comment by stepjan** [comment]
na emailu js@seznam.cz zadnou zpravu nemam :(

diky P

**Comment by bolekkerous** [comment]
Kliknutím na tento link byste měl být schopen přiřadit design k vybranému projektu: https://manager.avocode.com/view/8a823acb4b8b4deca3fb4679427208ea/assign/

**Comment by stepjan** [comment]
funguje, děkuju
