### ISSUE TITLE
Issue when uploading sketch file since Sketch3.5

### ISSUE THREAD

**Issue by rodnem** [avocode/avocode#668]
Argggg - I'm in hurry

Error: Command failed: 2016-01-29 16:28:02.308 sketchtool[20821:1297395] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-01-29 16:28:02.309 sketchtool[20821:1297395] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/fred/Documents/%E2%86%92%E2%86%92%20PROJECTS/%E2%86%92%E2%86%92%E2%86%92%20On%20the%20fly/Etesia/2015_Refonte_site_sous_drupal/3-design/etesia-2016.sketch
((null) MSDocumentDomain:11)

**Comment by rychlis** [comment]
We have released Sketch Extension 3.0.0 beta with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

We're working on updating the older Sketch Plugin 2 however there has been some further issues with Sketch 3.5 unfortunately. You should be able to use the beta version fine though. Please report any issues with the new plugin as a new issue

Follow #609 for more updates about older Sketch plugin, I am closing this issue as a duplicate, thanks for the report and sorry for the inconvenience

**Comment by rodnem** [comment]
ok thanks, I 'll give it a try right now
