### ISSUE TITLE
Windows: initial opening of the file is slow

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#67]
When I open a file for the first time, it is very slow. Currently 10min and counting with a 30mbps connection for a 15MB PSD.
What I consider a probable cause is that it has to download some files, however the "Loading....." notification doesn't let me know when I am going to be able to open the file.

So either this is a bug with opening a file or needs a more descriptive text, maybe a progress bar or something similar. All in all, I've only been able to open a PSD once, no idea how I did it.

**Comment by petrbrzek** [comment]
Is this still a problem with the current release?

**Comment by VPenkov** [comment]
Cannot confirm due to another issue (https://github.com/avocode/avocode/issues/91)

**Comment by petrbrzek** [comment]
#91 fixed. Do you still have problem with this?

**Comment by Helstein** [comment]
I also have the same problem. Trying to open large .psd file (21MB, around 1.6k layers) and it gets stuck on loading screen. Process Explorer doesn't show any CPU or IO activity.

**Comment by tomashanacek** [comment]
Hi, could you share us the problematic design to team[at]avocode.com?

**Comment by tomashanacek** [comment]
Fixed in next release (coming early next week).
