### ISSUE TITLE
Error export in avocode

### ISSUE THREAD

**Issue by sergei3456** [avocode/avocode#672]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-01-30 14:02:06.305 sketchtool[10011:853175] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by rychlis** [comment]
We have released Sketch Extension 3.1.0 with Sketch 3.5 support. Please download the latest version from here https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
