### ISSUE TITLE
#feature - setting REM base size per project

### ISSUE THREAD

**Issue by kupcza** [avocode/avocode#673]
I was thinking, that it would be great, if I can set rem font base sze per project, because I have several with different font size and every time I have to change it in settings.

**Comment by vojtatranta** [comment]
There is a suggested feature at uservoice, you can vote for such improvement there: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6988424-settings-for-units-px-em-rem

And it is also duplicated with #77

**Comment by kupcza** [comment]
Well, yes, it's implemented, but as I said - make it per project, now it is global setting. I have 5 projects, where I need REM units, but each project has different base size. So now I have to change this value every time.

**Comment by vojtatranta** [comment]
Yes we also know about that, there will be an option to set base font size per every design.

**Comment by kupcza** [comment]
Ok, awesome (y)
