### ISSUE TITLE
Issue with Sketch plugin

### ISSUE THREAD

**Issue by starodumov** [avocode/avocode#678]
I have just installed sketch plugin 2.1.5 and after it 3.1.0, but sketch still shows me this notification http://prntscr.com/9xjmth. Apparently, new version has not installed properly. Now I can`t export layouts.

-----
Sketch Exporter 2.1.1 running in Sketch 3.5.1
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/alexanderstarodumov/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by rychlis** [comment]
Do you have `Avocode Sync 3.1` in the plugins menu? It looks like this:
![sketch-menu](https://cloud.githubusercontent.com/assets/1819747/12714117/03ae1da8-c8d3-11e5-98ea-88a2cea1bf7a.png)

You can try installing it manually by copying the Avocode sketchplugin file from the DMG to the Plugins folder - Sketch menu Plugins -> Manage Plugins and in the window click the Settings icon in bottom left corner and select Show Plugins Folder...

Let me know if that helped

**Comment by starodumov** [comment]
Thank you very much! I haven`t seen it in menu
