### ISSUE TITLE
no click events in sketch plugin beta

### ISSUE THREAD

**Issue by Kilian** [avocode/avocode#679]
After attempting to install the new sketch plugin beta to support sketch 3.5 (took us a while to figure out that we just have to wait a long time) it seems the avocode plugin screen doesn't accept any click events; I can scroll up and down, rightclick to open the devtools, but I can't seem to click on anything. There is no log generated for this.

Sometimes I can succeed in selecting an artboard by frantically clicking both left and right, but then I still can not click on the dropdown to select the folder or the sync button.

**Comment by rychlis** [comment]
Hi this might be the same as #549 - there is a bug in the native Safari browser on some Yosemite versions, you can try this [workaround](https://github.com/avocode/avocode/issues/549#issuecomment-161592860) - let me know if it helps!

**Comment by Kilian** [comment]
It is, and the workaround helped. I'll close this!
