### ISSUE TITLE
Windows: Hand tool is glitchy

### ISSUE THREAD

**Issue by VPenkov** [avocode/avocode#68]
The hand tool doesn't work very smoothly. 
Sometimes it doesn't register the mouseout event when I'm holding space.

**Comment by petrbrzek** [comment]
Is this still a problem with the current release?

**Comment by VPenkov** [comment]
Yeah, same issue. Just hold space and try to move quickly over the viewport.

**Comment by petrbrzek** [comment]
Do you think it's possible to create a little video that will demonstrate this issue? Just for the sake of clarity. Thanks :)

**Comment by VPenkov** [comment]
Yeah, here it is.
http://youtu.be/pzImAmaCT2Q
Basically, when I drag the hand tool over the edge of the screen (and sometimes over the side panels), it fails to detect that I've released my mouse button.

**Comment by marekhrabe** [comment]
Oh, now we got it - thanks for the great example :) 

We will probably change the drag behavior to use the [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API), so we have more control over mouse events. Thanks a lot again :+1:

**Comment by marekhrabe** [comment]
That was simple. Fixed in new version :)

**Comment by VPenkov** [comment]
Hand tool is still glitchy.
1) Try holding space and left click somewhere to begin dragging
2) Hover over the edge of a panel
The result would be that your mouse cursor will change and remain to a "horizontal resize" style.

This is normally not much of an issue but try hovering over the "Code" widget. The CSS there will be selected and you won't be able to proceed dragging without deselecting it first.

**Comment by marekhrabe** [comment]
I can't seem to reproduce the part where cursor stays in resize state, but we'll try to later.

Code panel had this bug from start (although it is not related to hand tool). We will soon release new Avocode app with Code panel that has different implementation of selection that "fixes" the problem. 

New selection works by lines and you drag&drop to select more lines or use <kbd>shift</kbd> or <kbd>cmd/ctrl</kbd> and click to make selections of more lines

![](https://csshat.r.worldssl.net/images/plugin/code.gif)

**Comment by VPenkov** [comment]
Try releasing the mouse button while it's on the edge. You should be able to reproduce it then.

**Comment by VPenkov** [comment]
This issue is no longer relevant.
It's continued here https://github.com/avocode/avocode/issues/180
