### ISSUE TITLE
Cannot decode object of class

### ISSUE THREAD

**Issue by kennethknudsen** [avocode/avocode#680]
used the plugin to update and it gives me this error:

Error: Command failed: 2016-02-01 11:54:14.445 sketchtool[3628:530103] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
2016-02-01 11:54:14.446 sketchtool[3628:530103] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
Failed to open document file:///Users/kennethknudsen/Library/Mobile%20Documents/WUGMZZ5K46~com~bohemiancoding~sketch/Documents/careers.sketch
((null) MSDocumentDomain:11)

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-02-01 11:54:14.445 sketchtool[3628:530103] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by rychlis** [comment]
We have released Sketch Extension 3.1.0 with Sketch 3.5 support. Please download the latest version from here https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update and let me know if it helps
