### ISSUE TITLE
Issues uploading to Avocode using Sketch 3.5

### ISSUE THREAD

**Issue by melcassio** [avocode/avocode#681]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-02-01 09:54:06.068 sketchtool[50287:2147952] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by rychlis** [comment]
Hi, it should help to upgrade to Avocode Sketch 3, see https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
