### ISSUE TITLE
oooops

### ISSUE THREAD

**Issue by lvs-shunsukeshimada** [avocode/avocode#682]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-02-02 12:16:10.798 sketchtool[43833:8356683] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by vojtatranta** [comment]
You have really old version of Avocode Sketch Extension.
Unfortunately it does not work with newest Sketch.
Update instructions are here:  https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by vojtatranta** [comment]
Let us know whether it worked or not. Thanks.

**Comment by marekhrabe** [comment]
I will close this for now, please let us know if you have further problems.
