### ISSUE TITLE
Significant CPU and Memory usage by Avocode 2.5.2 Client.

### ISSUE THREAD

**Issue by stevebrown** [avocode/avocode#687]
Since upgrading to 2.5.2, performance of the Avocode client is very poor. It is currently using significant CPU load (+100%) and CPU time and consuming more memory than any other program on my system at close to 1Gb of RAM. The result is that the programs responsiveness is very poor where mouse clicks are not responded to for a few seconds. This might have to do with the initial sync performance after initially launching the program. After about 5 minutes, the CPU load returns to a more reasonable load and the app becomes responsive again.

What is needed is much better indication in the Avocode UI that there is a sync happening and what is being synchronized. We basically have to launch the app, wait five minutes for the sync to finish and then we can use the program.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
