### ISSUE TITLE
"unexpected error"

### ISSUE THREAD

**Issue by bobclough** [avocode/avocode#688]
Received error message below.  Sync Version 2.1.5 on Sketch 3.5.1

Also prompted with upgrade to new version of plugin when I start plugin.  Best I can tell that this is the most up-to-date version of plugin without considering your new 3x beta that I don't want to try yet ...

Removed personal info on file name and changed to XXXXXXX

Message pops after starting synch and getting through upload segment (I think).  Update fails.

Error: Command failed: 2016-02-02 11:54:17.064 sketchtool[1596:721330] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-02-02 11:54:17.064 sketchtool[1596:721330] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/XXXXXXXXXXXXXXX/WebApp%20Redesign/Invite%20and%20Poll%20Reply%20Pages.sketch
((null) MSDocumentDomain:11)

**Comment by bolekkerous** [comment]
Hello!
It looks like you are still using the old extenstion without support for Sketch 3.5.

The beta version supports Sketch 3.5, you can download it here https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

It should be working just fine.

**Comment by bobclough** [comment]
Installed your beta new version.  Started it from PlugIn menu in Sketch, greeted with login page, provided credentials, clicked on Log in, nothing happens.  (I checked credentials on general website and logged in/out with no issues with that account/password.)

**Comment by bobclough** [comment]
Removed and Reinstalled Sketch and is NOT Apple Store version.  That process now got me past the Avocode log in screen, displays artboards for selection, but does NOT allow me to select anything.  Singular selection or Select All does nothing.  In fact, all options in that Modal won't allow me to log out via account menu, select a different project, and "Sync Artboards" is not active.

**Comment by bolekkerous** [comment]
Could you please tell us which version of OSX are you using? We've noticed this issue only on Yosemite and upgrading it should fix it - see more here #549 

If you can't interact with the Sketch extension, there are few possible fixes:

1. Move your mouse where you want to click
2. Hold ctrl and click, a context menu will appear
3. Release ctrl key and click outside of the context menu but still on the same object you wanted to click

Another possible (and probably more easy) workaround is to open the plugin in Sketch first (as you would normally) and then open this location in your browser (e.g. Safari): http://127.0.0.1:33162/panel/ 

Hope it helps!

**Comment by marekhrabe** [comment]
Interaction bugs in Yosemite are fixed by version 3.2 - now available. Download here: https://avocode-media.s3.amazonaws.com/download/sketch-plugin-beta/3.2.0/sketch-plugin-beta-mac-3.2.0.dmg
