### ISSUE TITLE
error using Avocode

### ISSUE THREAD

**Issue by nckjrvs** [avocode/avocode#689]
IMPORTANT: Please try to describe how did it happen.

I emailed yesterday about not being able to upload Sketch to Avocode. you guys sent me a link for the new version, but it's still not allowing me to upload. :/ 

-----
Sketch Exporter 2.1.1 running in Sketch 3.5.1
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/nickjarvis/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by bolekkerous** [comment]
Hello!
It looks like you are still using the old extenstion.

Are you sure you installed the extension? It should be shown in Sketch as Avocode Sync 3.1. Do you see it there?

**Comment by marekhrabe** [comment]
I will close this for now, please let us know if you have further problems.
