### ISSUE TITLE
SVG export wrong

### ISSUE THREAD

**Issue by romanlex** [avocode/avocode#690]
For me svg export doesn't work properly (
I tried export this icon
![screenshot_2016-02-03_08-06-11](https://cloud.githubusercontent.com/assets/3369304/12773494/3bffbbf0-ca4d-11e5-9e7b-af9a5606ae40.png)
And output icon is
![screenshot_2016-02-03_08-05-55](https://cloud.githubusercontent.com/assets/3369304/12773499/46b557d0-ca4d-11e5-93c5-c7940f7329db.png)
Linux

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
