### ISSUE TITLE
Provide a way to open designs in multiple tabs from the Project Manager page

### ISSUE THREAD

**Issue by bdpartridge** [avocode/avocode#695]
On the developer side of the application (desktop app), the most frustrating thing about the experience right now is that I have no way, unless it's something completely non-obvious, to open designs in multiple tabs from the project manager page while leaving it open (i.e., every design I open replaces the project manager page).  I just want that page to stay open while I open multiple designs in separate tabs.

For large projects, it can be an extreme chore to open multiple related designs for quick back-and-forth viewing.  At least the previous version of Avocode would remember the last highlighted design in the project manager when opening it in a new tab.  Now, even that doesn't work in the latest version (2.5.2).

Please do something about this in the next release.

**Comment by jakubzitny** [comment]
Hi, thanks for the feedback. Sorry we're getting back to you this late. This is good idea, we will definitely address this soon, hopefully in one of the next two releases.

**Comment by bolekkerous** [comment]
Hey - 
I belive this should work for a while already.

I you want to open multiple designs in new tabs, please use the CMD/CTRL + doubleclick to do that.

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
