### ISSUE TITLE
Error when uploading a file in the project

### ISSUE THREAD

**Issue by MazheM** [avocode/avocode#696]
Tried to upload 7 small files(about 20 MB each) in the project. One of them caused the error(file size 16 MB).
After pressing Try again, the file is uploaded normally.
-----
App v.2.5.2
Source UID: 123869
```
Error: incorrect header check
  at Zlib._handle.onerror (zlib.js:345:17)

```

**Comment by petrbrzek** [comment]
This error should be now fixed with the latest Avocode 2.5.3. Please try it and let us know.
