### ISSUE TITLE
Avocode crash

### ISSUE THREAD

**Issue by ak1987** [avocode/avocode#706]
IMPORTANT: Please try to describe how did it happen.

I was trying to upload PSD and Avocode crashed at 95%. But i still can open this PSD with some errors in layout.

I can send you PSD if you need it.

-----
App v.2.5.2
Source UID: 49114
```
TypeError: Cannot read property 'progress' of undefined
  at C:\Users\ak\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\user.js:1:13019
  at C:\Users\ak\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:766
  at C:\Users\ak\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:7834
  at C:\Users\ak\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\@avocode\core\lib\api.js:1:8424
  at C:\Users\ak\AppData\Local\avocode\app-2.5.2\resources\app.asar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:104:5
  at FSReqWrap.oncomplete (fs.js:77:15)

```

**Comment by petrbrzek** [comment]
Thanks for reporting the issue. Can you send me the PSD to petr[at]avocode.com?

**Comment by vojtatranta** [comment]
This issue is related to #507

**Comment by rychlis** [comment]
This should be fixed in the latest version. We'll definetely re-open the issue if you can still reproduce it with latest Avocode or just report such problem as new issue
