### ISSUE TITLE
Error during export

### ISSUE THREAD

**Issue by annabotsvine** [avocode/avocode#707]
IMPORTANT: Please try to describe how did it happen.

---

Sketch Exporter 2.1.5 running in Sketch 3.5.1

```
Error: Error: Command failed: 2016-02-06 00:35:00.479 sketchtool[3556:1372918] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-02-06 00:35:00.480 sketchtool[3556:1372918] Error: caught exception whilst decoding (version 76):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/anna/Dropbox%20(ANGI%20studio)/Greenchoice/Productenportfolio/VD/20160205-Greenchoice-producten.sketch
((null) MSDocumentDomain:11)


    at /Users/anna/…/avocode-exporter/lib/image-exporter.js:1:873
    at ChildProcess.exithandler (child_process.js:651:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

**Comment by vojtatranta** [comment]
Hi, thank you for your report.
It seems that you have old version of Avocode Sketch Extension but current version of Sketch. There are troubles with new Sketch so we recommend you tu upgrade your Avocode Sketch Extension.
Please follow instruction here: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by vojtatranta** [comment]
And let us know whether it worked, thanks.

**Comment by annabotsvine** [comment]
Hi there,

I have upgraded it already, degraded and upgrade it again. I even upgraded the whole OS. Nothing works. 

My colleague also tried to sync on his computer. He gets the same error. Basically we finished up with developer opening the Sketch file on the Mac. Considering that we pay 80 euro a month for Avocode I find it really not okay. I wasted two hours trying to make it work. And this is not first time it's happening. I'm really very disappointed. Do you have some kind of test process in place before you actually release? And when are you planning to have a fix for this?

Met vriendelijke groet,
Anna Botsvine

Verstuurd vanaf mobiel
06 48933107

**Comment by bolekkerous** [comment]
Hey, Anna -
we deeply apologize for all the trouble and for our late reply.

As far as I checked, this shouldn't happen anymore with the latest Sketch plugin.

You can download the latest version here:
https://manager.avocode.com/downloads/

We're also already working on the ability to upload Sketch files directly to Avocode (same as it is now possible with PSD).

If you still experience this problem or any other, please create a new issue with it.
