### ISSUE TITLE
Error while opening Sketch artboard

### ISSUE THREAD

**Issue by shiienurm** [avocode/avocode#712]
IMPORTANT: Please try to describe how did it happen.

---

App v.2.5.3
Source UID: 66138

```
TypeError: Cannot read property 'imageName' of undefined
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2540
    at t.module.exports.t._getImagesToLoad (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:2673)
    at new t (/Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/assets-loader.js:1:515)
    at /Applications/Avocode.app/Contents/Resources/app.asar/node_modules/@avocode/core/lib/user.js:1:26595
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)
```

**Comment by shiienurm** [comment]
The issue appears when I have Sketch slices on the same artboard.

**Comment by jankuca** [comment]
Hi, can you share to sketch file in question with us at team[at]avocode.com? Also, which version of the Sketch extension are you using?

**Comment by shiienurm** [comment]
@jankuca Can't share the file but the issue appears only when I have slices on the artboard. My extension version is 3.1.0

**Comment by bolekkerous** [comment]
This problem should not be happening with the latest versions of Sketch plugin and Avocode app.

You can always download the latest versions here:

https://manager.avocode.com/downloads/

I'll close this issue - if you still encounter the problem, or any other, please create a new issue.
