### ISSUE TITLE
Sketch Exporter 2.1.1 running in Sketch 3.5.1

### ISSUE THREAD

**Issue by tlgklnc** [avocode/avocode#713]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.5.1
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/tolga/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by vojtatranta** [comment]
Thank you for your report.
It seems that you have really old Avocode Sketch Extension along with new version of Sketch.
This may cause the troubles.
You can try to upgrade to a newer version of Avocode Sketch extension.
Instructions are here: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md
Please let us know whether it worked.
Thanks
