### ISSUE TITLE
Error uploading

### ISSUE THREAD

**Issue by ehigz** [avocode/avocode#714]
IMPORTANT: Please try to describe how did it happen.

Uploading new project, got an error upon reaching 95%.  Not sure if upload will continue.... 

-----
App v.2.5.3
Source UID: 19006
```
Error: invalid stored block lengths
  at Zlib._handle.onerror (zlib.js:345:17)

```

**Comment by petrbrzek** [comment]
Thanks for reporting the issue. This error is not supposed to happen in 2.5.3. Do you think you could send me your `.avcd` folder (as a zip) to petr@avocode.com, so I can debug it more?
