### ISSUE TITLE
Hidden layers revealed when synching with Sketch plugin beta 3.1.0.

### ISSUE THREAD

**Issue by al1zoin** [avocode/avocode#718]
Following the issues created by my latest migration to Sketch 3.5.1with the 2.1.5 plugin (not working anymore, Error: Command failed: ...), I've tried the beta 3.1.0 version as recommended.

It works well for me (though not for my partner who's also using Sketch 3.5.1), but it seems like each time I synch my work, even a single artboard, all the layers that were hidden (masked) are instantly showing up! I end up having to dig into each artboard to manually re-hide all the layers that I don't want to see. For a couple days I've been wondering what was causing this and I think it is your plugin.

**Comment by vojtatranta** [comment]
Thank you for your report.
We have not encountered such problem yet. We will investigate it.

**Comment by vojtatranta** [comment]
We are releasing a fix today. It will be present in v 3.2.0.

**Comment by al1zoin** [comment]
All right, thanks for that info!

**Comment by al1zoin** [comment]
Will you give me an update once the new fix is issued?

**Comment by marekhrabe** [comment]
Hi, we have released Sketch Extension 3.2 with fixed bug about hidden layers. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
