### ISSUE TITLE
export error

### ISSUE THREAD

**Issue by LifeLive** [avocode/avocode#719]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-02-09 09:14:49.959 sketchtool[856:20480] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by vojtatranta** [comment]
Thank you for your report.
This is duplicated issue, we recommend you to upgrade to newer version of Avocode Sketch extension.
More info is here: #707
