### ISSUE TITLE
White space when exporting Layer Masks 

### ISSUE THREAD

**Issue by leereichardt** [avocode/avocode#72]
Avocode doesn't seem understand layer masks. I have a PSD with an image and rectangle and I can't seem to export the image from avocode with correctly. 

The exported image has white space at the bottom (full size of the image) when this should be cut off by the layer mask.

**Comment by petrbrzek** [comment]
Moved to user voice: https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6992685-layer-masks

**Comment by rychlis** [comment]
Actually Avocode supports layer masks so this is not really a feature request. There is an issue with cropping the image when exporting which will be fixed soon

**Comment by rychlis** [comment]
The cropping issue is now fixed in Avocode 1.1.0
