### ISSUE TITLE
UI scaling on HDPI screens 

### ISSUE THREAD

**Issue by thecotne** [avocode/avocode#721]
i have DELL XPS 13 with QHD+ display (something like a retina from apple) and fedora 23
so UI need to scale 200% to appear in normal size but in avocode it does not scale

![screenshot from 2016-01-16 19-40-13](https://cloud.githubusercontent.com/assets/1606993/12910452/54e743d2-cf24-11e5-9f1c-4f436aba1146.png)

**Comment by vojtatranta** [comment]
Thank you for your report. We already have in on the gitlab and it should be fixed soon.

**Comment by VitaliyMakarets** [comment]
+1

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
