### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by thecotne** [avocode/avocode#722]
in text layer properties unicode text is displayed with squares

this text for example "ქართული წარწერა"
i guess it is problem with default font

![screenshot from 2016-01-16 19-46-49](https://cloud.githubusercontent.com/assets/1606993/12910513/cec783f6-cf24-11e5-9da3-7f9caa681e21.png)

**Comment by vojtatranta** [comment]
Hi, thank you for your report.
We are trying to use default system fonts as much as possible.
We will test this.
Can you please send us this design with such symbols at team@avocode.com?
Thanks

**Comment by thecotne** [comment]
no i can't send this design just copy paste my example text to psd "ქართული წარწერა"

**Comment by vojtatranta** [comment]
Allright, thanks

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
