### ISSUE TITLE
Large File Error?

### ISSUE THREAD

**Issue by keryilmaz** [avocode/avocode#724]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-02-09 16:03:47.921 sketchtool[19804:15630870] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by vojtatranta** [comment]
Hi, thank you for this report.
It seems that you have old version of Avocode Sketch extension we recommend you to try newer version. Here are instructions: #707

**Comment by vojtatranta** [comment]
Let us know whether it worked.

**Comment by keryilmaz** [comment]
Hey, yeah solved it thanks, great product by the way.

On Tue, Feb 9, 2016 at 4:01 PM, vojtatranta <notifications@github.com>
wrote:

> Hi, thank you for this report.
> It seems that you have old version of Avocode Sketch extension we
> recommend you to try newer version. Here are instructions: #707
> <https://github.com/avocode/avocode/issues/707>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/avocode/avocode/issues/724#issuecomment-181875133>.
>



-- 
Kaan Eryilmaz
Design Lead @ Hipo
http://hipolabs.com
@hipolabs
