### ISSUE TITLE
"No document open" in Avocode Sync 3.1 and Sketch 3.5.1

### ISSUE THREAD

**Issue by growmotion** [avocode/avocode#727]
Hi,

I'm having an issue with the Avocode Sync since the plugin update.. Updated to Avocode Sync 3.1 and every time I want to sync a design the plugin keeps saying "No document open" (see screen). I really don't know what I can do more,...

Who can help me?

![schermafbeelding 2016-02-09 om 15 01 18](https://cloud.githubusercontent.com/assets/17143050/12918227/4aa1a2fe-cf3e-11e5-8a30-ff3eb0acb5ab.png)

**Comment by growmotion** [comment]
Now installed version 3.5.2 of Sketch, still the same problem.. @marekhrabe

**Comment by rychlis** [comment]
Hi please try to update to Avocode Sync 3.2.0 https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

If it doesn't help, please send us the sketch-panels.log, see [Reporting Bugs](https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#reporting-bugs)

**Comment by sweedbes** [comment]
Sketch: 3.5.1
Avocode: 2.5.4
Plugin: Avocode Sync 3.2.0

Error: http://take.ms/ykKCj

**Comment by bolekkerous** [comment]
This should not happen anymore with the latest version of the Sketch plugin.

You can always download the latest version here:
https://manager.avocode.com/downloads/

One possible reason this might happen even with the latest version of Sketch plugin is when your Sketch application is named differently than "Sketch". The most frequent names are something like "Sketch 2" or so. Renaming it to just "Sketch" should help.

If you still experience this problem or any other problem, please create a new issue or comment here.
