### ISSUE TITLE
Sketch 3.5.1 with Avocode Sync 3.1 update cannot Sync Artboard

### ISSUE THREAD

**Issue by isaacparker** [avocode/avocode#728]
Just recently updated to the Sync 3.1 non-beta and nothing on the interface is clickable to complete the Sync. See the grayed out Sync Artboards button in the image below. It is not active so I can't complete the sync. Please help.

![screen shot 2016-02-09 at 10 53 40 am](https://cloud.githubusercontent.com/assets/7864684/12921473/7ddf0abc-cf1b-11e5-904c-f1af41cb2b7e.png)

**Comment by rychlis** [comment]
This is a known issue on Yosemite, there are two possible workarounds in issue 549: https://github.com/avocode/avocode/issues/549#issuecomment-161592860

We'll fix this in the next release very soon, thanks for the report. I am closing this issue and will update on the problem in #549

**Comment by marekhrabe** [comment]
Fixed in latest version. Download here: https://avocode-media.s3.amazonaws.com/download/sketch-plugin-beta/3.2.0/sketch-plugin-beta-mac-3.2.0.dmg
