### ISSUE TITLE
Why I didn't see old project?

### ISSUE THREAD

**Issue by romanlex** [avocode/avocode#729]
I paid for my account 9$ in month, in price I see "Unlimited designs"
I'm web developer and use Avocode only to view the layouts from Photoshop or Scetch.
Why I no longer see the old layouts, which were available to me at the invitation of the team? Let the designer have not paid for your account, but my work does not stop.

**Comment by rychlis** [comment]
We don't remove access to any projects if you are a subscribed user, could you please give us an email to team@avocode.com so we can find out what happened individualy? Thanks
