### ISSUE TITLE
Only Atom launches on Windows

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#73]
So i was trying out Avocode and I don't see the desktop app loading on Windows. The only thing i see that loads is Atom (I've attached a .gif). Am i suppose to see Avocode inside Atom? Do i need to install an atom extension?

https://avocode.zendesk.com/attachments/token/HJJxBjzc0XlNkG0OjSwwgZzJb/?name=Atom-Avocode.gif

**Comment by petrbrzek** [comment]
Cool, thanks for provided solution. I'm closing this issue now.
