### ISSUE TITLE
Trying to sync sketch to Avocode error

### ISSUE THREAD

**Issue by iamlinzee** [avocode/avocode#734]
IMPORTANT: Please try to describe how did it happen.

I try to sync to avocode and I get this error:

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-10 12:17:10.815 sketchtool[4916:2733686] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by marekhrabe** [comment]
Hi, we have released Sketch Extension 3.2 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
