### ISSUE TITLE
Files don't sync (Avocode 2.5.4 & Sketch Plugin 3.2.0)

### ISSUE THREAD

**Issue by urikelman** [avocode/avocode#735]
After trying to sync a Sketch file to Avocode, it tells me it was a successful sync. When I go to that project, it shows that the folder is empty. 

<img width="872" alt="screenshot 2016-02-10 14 10 52" src="https://cloud.githubusercontent.com/assets/13421101/12963631/92e9ff1c-d000-11e5-806f-7bec69fec557.png">

**Comment by bolekkerous** [comment]
Hello!
We're sorry for the inconvenience.

Hit us up at team@avocode.com and I'll send you a link to assign those designs to your project. There was a bug in the previous version of extension, which uploaded the design to Avocode but did not assign it to a project. It should not happen with the new version anymore. This designs were probably synced initially with the older version, so the problem persisted.

**Comment by marekhrabe** [comment]
I will close this as designs are successfully synced and they will be assigned to correct projects via our support, so they are visible for the app.
