### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by numeric-step** [avocode/avocode#736]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-11 08:46:49.398 sketchtool[6048:1837201] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by marekhrabe** [comment]
Hi, we have released Sketch Extension 3.2 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
