### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by Djamshid** [avocode/avocode#741]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5
```
Error: Error: Command failed: 2016-02-12 11:49:01.343 sketchtool[8385:1732082] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by marekhrabe** [comment]
Hi, we have released Sketch Extension 3.2 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update

**Comment by Djamshid** [comment]
thank you! It works very well

**Comment by marekhrabe** [comment]
Glad to hear that :)
