### ISSUE TITLE
Importing a sketch file

### ISSUE THREAD

**Issue by alistairtweedie** [avocode/avocode#743]
I'm actually not too sure how this happened. Installed the Sketch plugin using the dmg. Gave permissions for avocode to allow sketch to use. This bug report appeared during Step 1
-----
Sketch Exporter 2.1.5 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-13 23:26:42.064 sketchtool[933:25050] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by petrbrzek** [comment]
Hi, we have released Sketch Extension 3.2 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
