### ISSUE TITLE
ERROR! Cannot upload stuff to Avocode for 1 week

### ISSUE THREAD

**Issue by annashine** [avocode/avocode#744]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.4 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-14 12:02:49.776 sketchtool[3808:660126] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by petrbrzek** [comment]
Hi, we have released Sketch Extension 3.2 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
