### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by stdex** [avocode/avocode#747]
[lp_PGS_1.psd.zip](https://github.com/avocode/avocode/files/131136/lp_PGS_1.psd.zip)

**Comment by jankuca** [comment]
Hello, it seems this file is corrupted. I am not even able to open it in Photoshop manually.

![screen shot 2016-02-16 at 11 29 19 am](https://cloud.githubusercontent.com/assets/367262/13073723/8b8e4fda-d4a0-11e5-9735-aa70d3780baf.png)
