### ISSUE TITLE
Error Sketch plugin

### ISSUE THREAD

**Issue by lehatyt** [avocode/avocode#748]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-16 11:56:33.197 sketchtool[2387:460862] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by petrbrzek** [comment]
Hi, we have released Sketch Extension 3.2 with Sketch 3.5 support. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
