### ISSUE TITLE
strange window with chrome dev tools in desktop app

### ISSUE THREAD

**Issue by erezLieberman** [avocode/avocode#749]
when I try to open avocode its open a strange window with chrome dev tools inside(???!!!)
i try to remove avocode and install again but nothing help :(
I'm used Linux 64 bit
![desctop screenshot](https://cloud.githubusercontent.com/assets/3277260/13083673/ba8925c4-d4de-11e5-92ca-104f24463989.png)

**Comment by vojtatranta** [comment]
Hi, thank you for your report.
Which version of app do you use?

**Comment by erezLieberman** [comment]
avocode-app-linux-2.5.4

**Comment by vojtatranta** [comment]
Can you show use console output?
I tried to open the latest version of Avocode in Linux and dev tools remained closed.
It might be possible that there is some error which prevents Avocode from booting.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
