### ISSUE TITLE
Project Export Path opens a Open Dialog on Mac

### ISSUE THREAD

**Issue by mattelen** [avocode/avocode#75]
When I setup a project and the project export path, when I click the 3 dots button, it open what appears to be an Open Dialog, instead of a Save Dialog. The downside to this is that I can't create new folders for my exports from my projects, as there is no button for that, and I must do that in Finder. This is annoying because my first point of contact with the project is with Avocode, and it would just be easier to setup folders and structures within it.

This was in Avocode V0.7.1

**Comment by tomashanacek** [comment]
Fixed in next release.
