### ISSUE TITLE
Loading sketch to avocode issue

### ISSUE THREAD

**Issue by sebalagos90** [avocode/avocode#750]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.1
```
Error: Error: Command failed: 2016-02-16 15:37:14.402 sketchtool[1387:110517] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by vojtatranta** [comment]
You are using an older version of the Sketch extension. The issue does not occur in the latest version which is a complete rework. Please download the latest version from https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md#installation--update
