### ISSUE TITLE
Error on sync with Avocade

### ISSUE THREAD

**Issue by IgorCova** [avocode/avocode#751]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-16 23:36:59.331 sketchtool[1203:155922] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by bolekkerous** [comment]
Hello!
Please download the latest version of Sketch extension with Sketch 3.5+ support. https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

It should fix the problem.
