### ISSUE TITLE
UPLOADING FILES

### ISSUE THREAD

**Issue by cnvcz** [avocode/avocode#756]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.5.2
Source UID: 119922
```
Error: invalid stored block lengths
    at Zlib._handle.onerror (zlib.js:345:17)
```

**Comment by petrbrzek** [comment]
Please update to the latest Avocode version (2.5.4). If you still have this problem in the new app, feel free to report it as a new issue.
