### ISSUE TITLE
Text is really tiny on Debian Jessie with high-dpi screen.

### ISSUE THREAD

**Issue by DDR0** [avocode/avocode#759]
The fonts are reeeeeally tiny by default, and my glasses aren't that good. (The drop-down menu text is OK, though.)

![t57 palette 2](https://cloud.githubusercontent.com/assets/862627/13202452/a19ec9f4-d850-11e5-92d5-2de74148fc1c.png)

**Comment by vojtatranta** [comment]
Thank you for this tip.
You will be able to set you own font size of the UI pretty soon.

**Comment by bolekkerous** [comment]
It should now be possible to modify the UI text size in the general settings and also the font size of the code panel in code panel settings.

I'll close this issue - if you still experience any problems regarding this, please create a new issue or comment here.
