### ISSUE TITLE
Export vector shape layers as @2x and @3x

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#760]
Hello,
Do we have ability to export x2 assets? I need to export x2 images for retina screens and i can't see any possibility to do this.
Maybe you could help with this?
This is critical for our team.
Thank you!

**Comment by ginmot** [comment]
+1

**Comment by linasmatakas** [comment]
+

**Comment by mantas-kunsmanas** [comment]
+1

**Comment by kestas-devbridge** [comment]
+1

**Comment by pauliusg** [comment]
+1

**Comment by valiooo** [comment]
+1

**Comment by andrius1** [comment]
+1

**Comment by miezis** [comment]
+1

**Comment by kokssuo** [comment]
+1

**Comment by mindaugas-salkus** [comment]
+1

**Comment by bolekkerous** [comment]
Hello!
Avocode currently does not have that feature, but we're already working on it and it is almost done. We'll be beta-testing it soon and we should release it in a few weeks.

You can check this post on our Facebook for a little preview. :)
https://www.facebook.com/avocode/videos/vb.1663528397218669/1683476075223901/?type=2&theater

Meanwhile, as a workaround I'd suggest to sync a @2x design into Avocode and export @0.5x images.

**Comment by rychlis** [comment]
Also see and vote for https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/6988511-export-vector-shape-layers-as-2x-and-3x

I'll keep the issue open until we implement this

**Comment by connor-bean** [comment]
We've finally released 2.8 that features exporting vectors at 2x, 3x, and 4x!!!

Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
