### ISSUE TITLE
Sync failed

### ISSUE THREAD

**Issue by bbbjr2013** [avocode/avocode#761]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-22 21:12:30.548 sketchtool[14281:2690362] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by vojtatranta** [comment]
You are running a very old version of Avocode Sketch Exporter with the new version of Sketch. 
Update instructions are here: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md
