### ISSUE TITLE
Upload from sketch finished but project stays empty

### ISSUE THREAD

**Issue by JorindeReijnierse** [avocode/avocode#762]
My colleague is using the latest version of the sketch plugin (3.2). We upload a design, uploading it worked without any errors. But when I go to the project folder in avocode program or online it stays empty. We tried creating a new project and uploading to that but that also doesn't work. There's no error message after uploading from sketch which I can show you. It finished as usual with the green checkmark.

**Comment by JorindeReijnierse** [comment]
We solved the problem by making a new sketch file with the same designs and upload this files to a new project on avocode. But still it's a weird bug..

**Comment by vojtatranta** [comment]
Thank you for this report.
That is really weird.
Can you please let us know if it happenned again?
Thanks.
