### ISSUE TITLE
Variables not persisting

### ISSUE THREAD

**Issue by JayCarney** [avocode/avocode#764]
Having issues with variables created for colours disappearing after force closing the app, and it also appears to happen when adding new art boards from sketch to existing projects

**Comment by jakubzitny** [comment]
Hi, thanks for the report. Can you please give us more info on this? What version of the app are you using?

**Comment by JayCarney** [comment]
Running Avocode 2.6.0 on OSX 10.11.3. Avocode sync 3.2 in Sketch (was on the prerelease version until today for the sketch fix)

I've tried recreating the issue on an existing project with no luck, but this definitely happens to me on a regular basses, but replicating seems to be an issue (surprise). It may be tied to a project being "new", the next time we add a design to Avocode I'll try replicate.

To give you an idea, I usually end up having the app open as a new design is added by our designer, open in the app, and open all the layouts, go through and create new colour variables and it's fine for the day, but within a couple days the variables are no longer there (sometimes it may be tied to new layouts being added, but somtimes I just open the app in the morning and my variables are gone)

Sorry I con't seem to find a reliable way to replicate.

**Comment by greystate** [comment]
I'm seeing this issue as well. Suddenly they're just all gone (which is very frustrating) - I've tried to see if I could somehow make backups of the settings, but they're tucked away far into a JSON blob, so wasn't as easy...

I also tend to keep Avocode open while updating designs via the Sketch plugin. This time, I'm 100% sure I didn't update anything between creating some color variables and some replacements and their sudden disappearance :(

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
