### ISSUE TITLE
show the full file name when hover cursor

### ISSUE THREAD

**Issue by Mo-** [avocode/avocode#765]

**Comment by jakubzitny** [comment]
Hi, thank you for the feature request.

I've moved it to our [Uservoice](https://avocode.uservoice.com/forums/277080-feature-voting). Feel free to vote for [this](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/12471507-show-the-full-name-of-a-design-on-hover) and also other features you might find useful.

**Comment by petrbrzek** [comment]
We added tooltips to places where it's desired to see the whole name.
