### ISSUE TITLE
Artboards Export fails

### ISSUE THREAD

**Issue by Bionik6** [avocode/avocode#766]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.5.2
```
Error: Error: Command failed: 2016-02-25 11:33:31.505 sketchtool[2725:135448] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by jakubzitny** [comment]
Hi, we have a new version of Sketch plugin, please install it from [manager.avocode.com/downloads](https://manager.avocode.com/downloads/). The new Sketch plugin 3 is compatible with Sketch 3.5 you are using.

If you have any problems, feel free to create new issue. Thank you :)
