### ISSUE TITLE
UI/IX - Add menu item "Recent files"

### ISSUE THREAD

**Issue by akulov** [avocode/avocode#767]
Hi,
Please, add menu item "File > Recent files"

**Comment by jakubzitny** [comment]
Hi, thanks for the idea. Please vote for it on [this Uservoice thread](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/12485682-add-menu-file-recent-files).

**Comment by petrbrzek** [comment]
This feature landed in 2.10.0. Closing now.
