### ISSUE TITLE
Unable to upload files from Sketch after deleting project from Avocode

### ISSUE THREAD

**Issue by Travo100** [avocode/avocode#769]
Hello there, 

I recently uploaded files from a sketch project I was working on, and then after deleting the project from Avocode I am no longer able to reupload my files with the Sketch plugin. I am able to make brand new projects and upload these files to Avocode w/o issue.

I have done the following with no luck: 
Uninstall and reinstall Sketch,
Uninstall and reinstall the Avocode upload plugin,
Rename the Sketch file and make a new project in Avocode,
Restarted my computer. 

I am using Sketch 3.5.2, Avocode 2.6.0, and using a Macbook Pro Running El Capitan 10.11.3. 

Thank you for your insight.

**Comment by vojtatranta** [comment]
Thank you for your report.
You write that you reinstalled Avocode upload plugin but I do not see which version of the plugin do you use.
Is it really latest one? Have you updated it according to this tutorial? https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by Travo100** [comment]
I downloaded the beta-mac-3.2.0 version of the plugin. After waiting around 24 hours I was able to upload the files again. However, I did notice that they did not have the little avocode logo on the bottom of them anymore, as before I saw the logo and was unable to re upload them.

**Comment by jakubzitny** [comment]
Hi, can you please update us on how the sync between Sketch and Avocode works for you?

Thanks.

**Comment by Travo100** [comment]
I'll open up Sketch and click on Plugins menu and then click on the Avocode Sync 3.2 plugin. After that I will select my artboards and click Sync Artboards to a current project or make a new project and upload the artboards there. After that I go into Avocode and verify the files are there and can start working on my web front end. 

That is my flow. Let me know if you need anymore details.

**Comment by bolekkerous** [comment]
This should not happen anymore with the latest version of the Sketch plugin.

You can always download the latest version here:
https://manager.avocode.com/downloads/

If you still experience this problem or any other problem, please create a new issue or comment here.
