### ISSUE TITLE
Can not upload PSD size of 174 megabytes

### ISSUE THREAD

**Issue by dshm** [avocode/avocode#771]
Can not upload PSD size of 174 megabytes.Gives an error message.

**Comment by vojtatranta** [comment]
Hi, thank you for your report.
Can you paste that error message here? And can you share with us that problematic PSD at team@avocode.com?
Thanks

**Comment by dshm** [comment]
I sent you a letter.

**Comment by jakubzitny** [comment]
Hey, this is a known problem with large layers, mostly with smartobjects in PSD files. We are working on better smartobjects integration right now, so it should be solved in upcoming releases.
