### ISSUE TITLE
Error on upload

### ISSUE THREAD

**Issue by irbisadm** [avocode/avocode#772]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 148135
```
Error: ENOENT: no such file or directory, lstat '/Users/irbisadm/.avcd/userdata/148135/documents/0da213423bf5403f84cc9310e3f17eca/images/resources.tar.gz'
    at Error (native)
```

**Comment by vojtatranta** [comment]
Thank you for your report.
What did you try to do? You just tried to upload a design?

**Comment by irbisadm** [comment]
Just upload 7 files at once

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
