### ISSUE TITLE
Images with clipping mask in hidden group do not display (PSD)

### ISSUE THREAD

**Issue by p4veI** [avocode/avocode#780]
Images included in designs in the desktop application are not visible in the interface, or at least this seems to be the issue since most of included images is displayed, however our graphic designer suggests the ones that may have been cut by clipping masks are the ones not visible.

Is this a known issue?

**Comment by jakubzitny** [comment]
Hi, yeah, displaying clipping masks correctly is not entirely supported right now. We are currently working on an enhanced rendering and it has high priority, so you should see it in upcoming release.

Can you look at #462 if it's similar to what you are experiencing?

**Comment by p4veI** [comment]
Not entirely, we have a PSD uploaded which contains clipped images, but they don't have stroke (as far as I know), instead of not displaying the stroke the images are not visible at all... 

I'm attaching a couple of screenshots to demonstrate, screenshot that contains cover images in the first image is how it looks in photoshop or in google drive where the PSD was uploaded, in Avocode we see it like in the second image.

![screen shot 2016-03-03 at 15 21 41](https://cloud.githubusercontent.com/assets/5863272/13497093/e55e11e8-e153-11e5-99e9-a3e4ab28c13b.png)
![screen shot 2016-03-03 at 15 22 21](https://cloud.githubusercontent.com/assets/5863272/13497094/e55fc04c-e153-11e5-943e-1f1c7de5eb42.png)

**Comment by jakubzitny** [comment]
Thanks, yeah I realized it and updated my answer — what version of Avocode are you using please?

**Comment by p4veI** [comment]
I'm using version 2.6.0 so I believe the latest available.

**Comment by jakubzitny** [comment]
That's intersting. Can you please send us the PSD file to team@avocode.com? We will try to investigate the problem.

**Comment by p4veI** [comment]
I've submitted an example PSD file to you, hope the issue will be easily replicated.

**Comment by rychlis** [comment]
I've tested the PSD at it actually works fine. After more research I was able to replicate it in case when the clipping mask is in a **not visible** group.

We'll investigate further why does it happen, in the meanwhile a possible workaround is to split the PSD in more files to keep the groups/layers visible.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by xamedow** [comment]
Still having issue with clipping masks in this mockup
Avocode 2.8.1
![2016-06-21 16 05 19](https://cloud.githubusercontent.com/assets/2815775/16230550/a56a4b1a-37ca-11e6-9f47-c707fb01c89d.png)
Photoshop
![2016-06-21 16 08 11](https://cloud.githubusercontent.com/assets/2815775/16230564/bbdd4276-37ca-11e6-9da1-059622835a53.png)

**Comment by bolekkerous** [comment]
Hey, @xamedow -
Are you still experiencing this problem even with the latest version of Avocode?

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
