### ISSUE TITLE
i have a new strange trouble

### ISSUE THREAD

**Issue by shectermen** [avocode/avocode#782]
found to export the problem, if the layer is called a non-English language (I'm from Russia), the picture is exported without a name, just with the extension, and in linux and mac perceive these as hidden files

**Comment by jakubzitny** [comment]
So, we've tried this and have found similar behavior on various non-English characters. I am putting this into our internal bug tracking system and we will try to address this issue in upcoming releases.

Also it would help if you could mention which version of Avocode you are using and whether it's Linux or Mac. You mentioned both, have you tried it on both?

It doesn't seem to be happening if you rename a particular export asset before exporting in Avocode. So as temporary workaround, please rename the assets before exporting in Avocode.

**Comment by shectermen** [comment]
Now we are doing and rename layers, but it is not always convenient, I work with the latest version avaсode on Linux Mint and Mac OS Maverick, and it is a problem for all versions

**Comment by jakubzitny** [comment]
I see, thanks for additional info. We will try to fix this as soon as possible. :wink:

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
