### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dusblinov** [avocode/avocode#785]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.6.1
```
Error: Error: Command failed: 2016-03-05 22:00:18.135 sketchtool[65825:1289615] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles)

**Comment by jakubzitny** [comment]
Hi, you're using an old version of our Sketch plugin. We have a new version now, please install it from [manager.avocode.com/downloads](http://manager.avocode.com/downloads/). The new Sketch plugin 3 is compatible with Sketch 3.6.1 you are using.

Let us know if you have any problems. Thank you :)
