### ISSUE TITLE
Close error alert with esc key

### ISSUE THREAD

**Issue by Cactucs** [avocode/avocode#790]
When an error occur and the alert window show up, `esc` key opens browser with issue submission.

**Comment by jakubzitny** [comment]
Thanks for this report as well. You're on Linux right?

It's probably a system thing we're not handling correctly. We'll let you know when this is fixed.

**Comment by Cactucs** [comment]
Yes, linux.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
