### ISSUE TITLE
Allow to copy only value from generated css

### ISSUE THREAD

**Issue by Cactucs** [avocode/avocode#792]
Sometimes it would be useful to be able to copy only value from code in avocode. (Eg. by clicking on the value, clicking on property name would copy whole line)

**Comment by jankuca** [comment]
Hi, thanks for the input. We are already considering this improvement.

**Comment by bolekkerous** [comment]
You should now be able to copy values either from style panel, or by just selecting the part you want to copy in the code panel.

If you have any other enhancement suggestions or problems, please create a new issue.
