### ISSUE TITLE
Missing lateral-spacing (VA) in text layers in PSD

### ISSUE THREAD

**Issue by z4kk** [avocode/avocode#793]
Our designer always use 'VA' attribute paragraph properties in text layers.
Seems in Avocode no way to see this value and export it to 'lateral-spacing' property.

**Comment by jankuca** [comment]
Thanks for your feedback. We currently provide letter spacing info for Sketch documents only. Photoshop support should be added shortly.

**Comment by exdeniz** [comment]
Please add support PS, very important.

**Comment by Souvel** [comment]
Really need))

**Comment by skyline94** [comment]
Is there any news about letter-spacing support?

**Comment by cupok** [comment]
Please add support PS, very important.

**Comment by vojtatranta** [comment]
It has been added at app.avocode.com (you might need refresh to get latest version)

But you have to reupload your psd again to see the values.

It is comming soon to the desktop app (cca. 2 weeks)

**Comment by nkaliev** [comment]
@vojtatranta omg its good news! finally! thank you, avocode team.
