### ISSUE TITLE
Couldn't sync files via new and old Sketch plugin

### ISSUE THREAD

**Issue by letika** [avocode/avocode#795]
```
Error: Command failed: 2016-03-15 15:19:43.101 sketchtool[3134:2254141] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
2016-03-15 15:19:43.102 sketchtool[3134:2254141] Error: caught exception whilst decoding (version 78):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer) for key (layerStyles); the class may be defined in source code or a library that is not linked
Failed to open document file:///ABC_Android.sketch
((null) MSDocumentDomain:11)
```

**Comment by jakubzitny** [comment]
Hi, thanks for the report. Can you please elaborate more on what happened and how?

I looks like you are using an old version of our Sketch plugin. Can you please make sure you're using the latest version `3.3` available from [manager.avocode.com/downloads](https://manager.avocode.com/downloads/)? Can you also let us know the exact version of Sketch you are using, please? You're under Windows, right?

**Comment by yarrowgirl** [comment]
Hello, I too have experienced this problem. I am using the most up to date sketch plugin, and the most up to date version of both sketch and avocode. I have received the same error message. First it asks me to download the most recent plugin for sketch (already did and installed it) then i get this error after i try to sync:
Error: Command failed: 2016-03-15 11:34:30.028 sketchtool[19473:412024] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
2016-03-15 11:34:30.028 sketchtool[19473:412024] Error: caught exception whilst decoding (version 78):*** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSharedStyleContainer)
Failed to open document file:///Users/gheller/Desktop/tool.sketch
((null) MSDocumentDomain:11)

**Comment by jakubzitny** [comment]
@yarrowgirl Could it be possible that the installation/update of new plugin went wrong and you're still using the old version despite having installed the new one? Can you share with us the screenshot of running Sketch plugin please?

**Comment by jakubzitny** [comment]
If you find that the old Sketch plugin is still present, please delete it in menu `Plugins -> Manage plugins...`.

**Comment by letika** [comment]
I've deleted old Plugin and installed new one - it doesn't work. When i click to Sync to avocode - nothing happens.
I use Sketch Version 3.6.1 (26313) and I am on Mac.

It's really pity that you removed ability to upload sketch file directly to Avocode though application - I couldn't update file for developers :(

**Comment by yarrowgirl** [comment]
![image](https://cloud.githubusercontent.com/assets/17852741/13784960/cb9dde84-eaa7-11e5-9d46-aab94999dab8.png)

**Comment by jakubzitny** [comment]
Did you @letika (also @yarrowgirl ) try to relaunch Sketch? After (re)installing Sketch plugin it is sometimes needed. It's mentioned in [Known bugs](https://github.com/avocode/avocode/blob/master/sketch-plugin.md#known-bugs).

Another problem might be with using Sketch from Mac App Store, but that one is not available for a while now.

Also @letika we have not removed the ability to upload Sketch file directly. We've never had it in the first place, however, we will be working on it soon. It's one of the most requested features, feel free to vote for it (and also others) on [our UserVoice forum](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7041131-allow-uploading-sketch-files-in-the-project-manage).

**Comment by jakubzitny** [comment]
@letika I just realized, you're most certainly using the old version. The new one does not have the `Sync to avocode` button. Please disable also the `Legacy plugins` in `Manage plugins..` menu, restart the app and start over again.

@yarrowgirl you too, disable the `Legacy Plugins` as well.

**Comment by letika** [comment]
<img width="782" alt="screen shot 2016-03-15 at 6 32 55 pm" src="https://cloud.githubusercontent.com/assets/10288702/13785531/9ff7fcf8-eadc-11e5-8d64-21e5744b2bb8.png">
<img width="1065" alt="screen shot 2016-03-15 at 6 32 23 pm" src="https://cloud.githubusercontent.com/assets/10288702/13785532/a0144606-eadc-11e5-889e-fcb5a00ccc84.png">
<img width="443" alt="screen shot 2016-03-15 at 6 33 40 pm" src="https://cloud.githubusercontent.com/assets/10288702/13785539/a580eea0-eadc-11e5-8d6b-44f0664a3a96.png">
<img width="364" alt="screen shot 2016-03-15 at 6 33 52 pm" src="https://cloud.githubusercontent.com/assets/10288702/13785552/af31a2f0-eadc-11e5-83c5-71e351c5f941.png">

**Comment by letika** [comment]
Sketch is not from AppStore.
I've restarted Sketch and Mac :) It doesn't work

**Comment by jakubzitny** [comment]
@letika I understand that you have installed the new extension. The problem is that you still have the old one somewhere. It is our fault, because the installator should delete the old one, however, it is still there.

The menu should look like this:
![slack-imgs com](https://cloud.githubusercontent.com/assets/3315662/13785702/d40bf1a0-ead4-11e5-8d54-93228e6839e9.png)

Did you try to disable `Legacy plugins`?

**Comment by letika** [comment]
OMG!
Thank you very much :) 
I have both of them on my plugins list. New one works, everything is great! But I have no idea how to remove old :)

<img width="416" alt="screen shot 2016-03-15 at 6 42 44 pm" src="https://cloud.githubusercontent.com/assets/10288702/13785882/f666cbb8-eadd-11e5-866a-ef492c643a30.png">

**Comment by yarrowgirl** [comment]
It worked for me as well! Thank you so much for your assistance!

**Comment by jakubzitny** [comment]
The old one should be already deleted if you're using the new one ;)

Glad I helped. Let us know if you have any more problems.
