### ISSUE TITLE
Avocode plugin for Sketch hangs on startup

### ISSUE THREAD

**Issue by pertsevin** [avocode/avocode#797]
I use Avocode plugin (3.3.0) from Sketch (3.6.1) on OS X El Capitan (10.11.3). When I open the plugin from Sketch menu I get the Avocode window that is empty and nothing happens.

`avocode-node.log` contains the following:

`[error]: Error: ENOENT, open '/Users/user/Library/Application Support/com.bohemiancoding.sketch3/Plugins/avocode.token'
[info]: User authorized`

`avocode.log` is empty.

![avocode_plugin](https://cloud.githubusercontent.com/assets/7408156/13806568/7af4f348-eb6d-11e5-9f6c-a7f8ef887560.jpg)

**Comment by connor-bean** [comment]
Downloading and installing Sketch from official site should hopefully fix the problem. Sketch is leaving App Store anyway: http://blog.sketchapp.com/post/134322691555/leaving-the-mac-app-store

You can download Sketch here: http://sketchapp.com/static/download/sketch.zip

If it is not the problem, please try it again with the latest beta extension, you can download it here: https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by connor-bean** [comment]
Please email team@avocode.com if it still does not work. Thanks!

**Comment by pertsevin** [comment]
Thanks. This solution helped.
