### ISSUE TITLE
My Avocode App is not displaying shadow Fx values

### ISSUE THREAD

**Issue by vitorfernandes** [avocode/avocode#798]
I'm selecting the bg on this card:
![screen shot 2016-03-16 at 10 39 38 am](https://cloud.githubusercontent.com/assets/11338156/13814025/70f811e0-eb63-11e5-96ca-6355d4749b3e.png)

Check the code out:
![screen shot 2016-03-16 at 10 39 46 am](https://cloud.githubusercontent.com/assets/11338156/13814032/7375f84c-eb63-11e5-90b9-38897303eddc.png)

This is the layer structure:
![screen shot 2016-03-16 at 10 40 23 am](https://cloud.githubusercontent.com/assets/11338156/13814051/923c113a-eb63-11e5-8fe8-944bb54fcd15.png)

All the developers here at the company are having the same issue. So, I think it can be a major bug, since an style is not being displayed as code.

**Comment by vojtatranta** [comment]
Hi,
thank you for your report.

They should be working if they are as a vector. If you have troubles with this particular .psd you can share it with us at team@avocode.com and we would take a look.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
