### ISSUE TITLE
SVG edges are cut on export

### ISSUE THREAD

**Issue by maxim1006** [avocode/avocode#801]
There is an issue when exporting svg. The output SVG edges are cut.

Example of the SVG that was generated by Avocode

`<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 24 24">
    <path stroke-linejoin="miter" stroke-linecap="butt" stroke-width="2" stroke="#848e9f" fill="none" fill-rule="evenodd" d="M 12 0 C 18.63 0 24 5.37 24 12 C 24 18.63 18.63 24 12 24 C 5.37 24 0 18.63 0 12 C 0 5.37 5.37 0 12 0 Z"/>
    <path fill="#848e9f" fill-rule="evenodd" d="M 17.99 12.95 C 17.99 12.95 13 12.95 13 12.95 C 13 12.95 13 17.99 13 17.99 C 13 17.99 11 17.99 11 17.99 C 11 17.99 11 12.95 11 12.95 C 11 12.95 6.01 12.95 6.01 12.95 C 6.01 12.95 6.01 10.96 6.01 10.96 C 6.01 10.96 11 10.96 11 10.96 C 11 10.96 11 6.01 11 6.01 C 11 6.01 13 6.01 13 6.01 C 13 6.01 13 10.96 13 10.96 C 13 10.96 17.99 10.96 17.99 10.96 C 17.99 10.96 17.99 12.95 17.99 12.95 Z"/>`
</svg>

Thanks.

**Comment by connor-bean** [comment]
Can you send us the PSD file to team@avocode.com?

Thanks!
Connor, Avocode Support

**Comment by maxim1006** [comment]
Sending psd


>Вторник, 22 марта 2016, 12:40 +03:00 от Connor <notifications@github.com>:
>
>Can you send us the PSD file to  team@avocode.com ?
>Thanks!
>Connor, Avocode Support
>—
>You are receiving this because you authored the thread.
>Reply to this email directly or  view it on GitHub


С уважением,
Max Maximov
maxim1006@list.ru

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
