### ISSUE TITLE
Artbords failed to sync

### ISSUE THREAD

**Issue by leonidpotapov** [avocode/avocode#803]
Hello. 

Sketch 3.6.1 
Avocode 3.3

I can't sync my artbords, but if I delete 2 text layers I will able to sync it. 
What's wrong?
Video: https://youtu.be/6DnVzAdHJdY

Also I attached:
My sketch-panels
[sketch-panels.log.txt](https://github.com/avocode/avocode/files/184728/sketch-panels.log.txt)

**Comment by jakubzitny** [comment]
Hi, thanks for the report. Can you please send us the Sketch design to team@avocode.com?
We will try to investigate what's causing the problem.

Thank you.

**Comment by leonidpotapov** [comment]
Ok. I'm already send it

**Comment by leonidpotapov** [comment]
Also I've checked the previous projects that been synced and now one of artboards in 1 project also can't be synced.
Finally it looks like something was changed at avocode plugin and now it can't be able to sync by some undefined reason

**Comment by leonidpotapov** [comment]
Today we test “design_full.sketch” on the test iMac. And the all 12 artboards was successfully synced.

But! Without fonts that used in original!
This mac haven’t installed Pragmatica, Gotham Pro and Roboto fonts. And Sketch modified all missing fonts from original file “design_full.sketch” with replacement to Helvetica/ Helvetica Neue. After this all artboards quickly sync with account.

After installing all those fonts and opening not modified version of “design_full.sketch” - all 12 artboards can’t be able to sync. 

Perhaps the problem with sync is in fonts

**Comment by rychlis** [comment]
Hi we have released Sketch Plugin 3.4.0 that should fix this completely. Update [here](https://github.com/avocode/avocode/blob/master/sketch-plugin.md#installation--update)
