### ISSUE TITLE
Error downloading 

### ISSUE THREAD

**Issue by ninjamonkno1** [avocode/avocode#806]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 27874
```
Error: ENOENT: no such file or directory, lstat '/Users/darrenstuart/.avcd/userdata/27874/documents/f92a68dd906a40aead66cd5695ffddb6/images/resources.tar.gz'
  at Error (native)

```

**Comment by vojtatranta** [comment]
Hi, thank you for this report, can you please tell us what exactly were you trying to do? Thanks.

**Comment by ninjamonkno1** [comment]
I was trying to download a PSD from within the app. Turns out your site was down at the same time, the site loaded slowly and with no css or images so looks like it might have been an issue with your hosting.

All other sites worked fine and there were no issues with my internet connection. 

Cheers

Darren

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
