### ISSUE TITLE
Layers effects Photoshop СС2015

### ISSUE THREAD

**Issue by sunnyexe** [avocode/avocode#807]
New  layers effects created in Photoshop СС2015 disappeared after being loaded into avocode. Such as a double stroke or a double shadow.

![avocode](https://cloud.githubusercontent.com/assets/16691221/14041561/e5a473b2-f293-11e5-9888-2329942e1cdb.jpg)

![layer](https://cloud.githubusercontent.com/assets/16691221/14041660/f7fe11de-f294-11e5-8f7f-1c1640698c93.jpg)

**Comment by bolekkerous** [comment]
We actually aren't supporting CC2015 multiple effects yet. However, we're already working on our own rendering, which should add this functionality.

Hopefully we can manage to implement it in April.

**Comment by bolekkerous** [comment]
Hey - 
we’ve just released a new version - 2.19 - which I believe should fix this issue. 

Please update your app and it should hopefully work. If it doesn't, please try to reupload the design as well.

You can check our changelog for the full release notes:

https://avocode.com/changelog

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
