### ISSUE TITLE
Can't download sketch-file

### ISSUE THREAD

**Issue by daryasysoeva** [avocode/avocode#809]
#806 I have a notification "download was successfully done", but the project is still empty :(

**Comment by bolekkerous** [comment]
Hello!
Could you please hit us up at team@avocode.com with the e-mail you are using with Avocode?

Thanks!

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
