### ISSUE TITLE
Sketch plugin: LOADING button and nothing. Can't login.

### ISSUE THREAD

**Issue by ekurennyy** [avocode/avocode#811]
Hi all.
I've purchased Sketch (Version 3.6.1 (26313))
I also have Avocode account and Avocode Sketch plugin (latest version from official site which is 3.3.0)
I'm opening Sketch, design in it and trying to sync this with Avocode.
I'm clicking on Plugins > Avocode Sync 3.3. and see the window with "Please login so we know where to sync your designs". And "LOGIN" button.
When I click on "LOGIN" btn it just changed text from LOGIN to LOADING and nothing else happens.
Web Inspector says me this:
[Error] Failed to load resource: Could not connect to the server. (ping, line 0)
http://127.0.0.1:33162/_panels/ping?callback=init&random=0.04119438864290714
3 times.

Can you help me with this or tell what can I send you and how for resolving this issue?..
Thank you for your time.

![01](https://cloud.githubusercontent.com/assets/372402/14257702/a6953b54-faa7-11e5-9d90-25186b00b944.png)
![02](https://cloud.githubusercontent.com/assets/372402/14257703/a695b976-faa7-11e5-979e-0b13586d6be5.png)

**Comment by connor-bean** [comment]
Hey, Eugene -

Did you download Sketch from the App Store or did you download it from their website? We've seen similar problems in the past from users who downloaded Sketch from the App Store.

If you downloaded it from there, please try re-installing it after downloading from their website:
http://sketchapp.com/static/download/sketch.zip

Thanks,
Connor, Avocode Team

**Comment by ekurennyy** [comment]
Hi, Connor
Thank you for the fast answer.
Yes, I installed latest version from their site (not form App Store).
And I already tried to reinstall Sketch and Avocode plugin, restart application after installing plugin too...
I also cleaned up Library  folders (Caches, Application Support) from any Sketch and Avocode files for making a really fresh install.
Maybe somewhere in my system can be stored configuration files from old Sketch which didn't allow me to login now?..

**Comment by connor-bean** [comment]
Could you send us the problematic design to team@avocode.com?

**Comment by ekurennyy** [comment]
Hm... I think it's not design issue because I just tested plugin with design from Sketh's templates (File > New From Template > Welcome to Sketch) and with just a rectangle shape.
Both with fresh start of the Sketch application.

**Comment by connor-bean** [comment]
Ok thanks for the response!

Would it be possible for you to send us the log files from Sketch? 

Here is a guide on how to get log files (it is the last paragraph) - https://github.com/avocode/avocode/blob/master/sketch-plugin.md#reporting-bugs

If there is no sketch-panels.log it means the extension did not launch properly, please try opening the Console App -> All Messages and look for any errors when you launch the extension.

Connor, Avocode Team

**Comment by ekurennyy** [comment]
Done. Thank you, Connor.

**Comment by connor-bean** [comment]
Not a problem. My apologies for any confusion.

Did this solve the issue? 

Connor

**Comment by rychlis** [comment]
the issue is caused by a networking error - you are not able to connect to Firebase server (exact URL is `https://auth.firebase.com/auth/anonymous?transport=json&firebase=source`). I've sent you an email with more info

**Comment by ekurennyy** [comment]
You're right. It works with enabled VPN for me.
Looks like I have and issue not with Avocode, but with network somewhere.
Thank you!
