### ISSUE TITLE
Error if close all tabs

### ISSUE THREAD

**Issue by devillom** [avocode/avocode#817]
If open design and close all tabs
![2016-04-07_04-06-02](https://cloud.githubusercontent.com/assets/3521940/14334431/3d2755f0-fc76-11e5-977a-99120aa78aad.png)

**Comment by vojtatranta** [comment]
Thank you for your report and for testing Avocode Beta. I am going to take look right now.

**Comment by vojtatranta** [comment]
So I tried it out and there was a bug when closing design in the phase when you no longer have a document open.
And we fixed it. In the next release of beta it will be fixed, thank you so much for this report.

**Comment by vojtatranta** [comment]
gitlab MR !328
