### ISSUE TITLE
Export jpg

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#818]
Avocode beta 2.8.0-beta 1

I had only blank white image after saving layers as .jpeg

![screen shot 2016-04-08 at 14 11 36](https://cloud.githubusercontent.com/assets/12643008/14383220/e979cef0-fd93-11e5-9572-732c88e45e99.png)

![screen shot 2016-04-08 at 14 11 46](https://cloud.githubusercontent.com/assets/12643008/14383222/eb7aa03a-fd93-11e5-826c-4f143d26de8e.png)

**Comment by vojtatranta** [comment]
Hi,
thank you for this report. We know about issues in export and we are currently finishing newer version of whole export module. Should be ready in 2.8.0.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
