### ISSUE TITLE
Not uploading new artboards

### ISSUE THREAD

**Issue by BrendanMiller** [avocode/avocode#820]
I don't know what is going on but I'm really not thrilled with this. After days of convincing my team to pay to ugprade avocode, they're not seeing screens that I'm uploading.  The project is now quite a bit behind. Am I doing something wrong?
- I highlight artboards in Sketch, plugins -> avocode.
- In the new Avocode window I select the screens I want synced, hit sync
- It loads for 20 seconds or so
- Success sound
- Now in Avocode it says "35 designs" at the top of the screen, but we only count 27. Developer is wondering where the screens are - I'm wondering where the screens are, no one is happy.

Since we paid for this product we're kind of expecting a lot more from it than this

**Comment by connor-bean** [comment]
Hey, Brendan -

Can you email team@avocode.com and tell us what email address is tied to your Avocode account?

Thanks,
Connor, Avocode Team

**Comment by connor-bean** [comment]
Can you also send us the logs from Sketch and one of the designs you uploaded but your team cannot see?

Here is a guide on how to get the Sketch logs (it is the reporting bugs article): https://github.com/avocode/avocode/blob/master/sketch-extension-beta.md

**Comment by bolekkerous** [comment]
Hey -
we deeply apologize for the inconvenience. This should not happen anymore (already for some time) with the latest version of the Sketch plugin.

You can always download the latest version here:
https://manager.avocode.com/downloads/

If you still experience this problem or any other problem, please create a new issue or comment here.
