### ISSUE TITLE
Not opening Document on thumbnail click

### ISSUE THREAD

**Issue by naazim** [avocode/avocode#822]
Only for certain files, clicking on thumbnail have no effect and does not open the tab with the layers and details. Kindly help with this.
![capture](https://cloud.githubusercontent.com/assets/7804899/14420885/21f2fd7e-ffec-11e5-9078-32f325669a11.JPG)
P.S: This does not happen for all files. Only specific mocks.

**Comment by jakubzitny** [comment]
Hi, thanks for your report. Can you please share with us which version of Avocode you are using and how did you upload the files that you have problem opening? Could you try to reset Avocode app and try opening the same file again? Is it still happening?

**Comment by naazim** [comment]
Hi Jakub,
I'm using version 2.6.0 of Avocode. The files were uploaded by my
counterpart. So I'm not sure about how they uploaded. However, i confirmed
with them about the issue, and seems like they are able to access the files
and I'm the only one not able to open these. Could you please help me with
instructions on resetting avocode?

Thanks
Naazim

**Comment by connor-bean** [comment]
Hello, Naazim -

What email address do you use with your Avocode account?

Thanks,
Connor, Avocode Team

**Comment by bolekkerous** [comment]
Hello!
Could you please send us the original sketch file to team@avocode.com so we can test it? I'm afraid we can't really pinpoint the problem without the original design.

Also, have you tried pressing space to preview and then enter to open the design? Does it open the design? You can try to press enter in the manager right away, it should work too.

Let us know!

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
