### ISSUE TITLE
Copy text vs. copy css

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#825]
In "old" Avocode, if I was on text layer and I had selected css code, after pressed cmd + c, atribues on code pannel were copy. In new avocode it is copy text instead of css.

![screen shot 2016-04-12 at 14 09 49](https://cloud.githubusercontent.com/assets/12643008/14459441/4a390c70-00b8-11e6-8e20-16b44cd67ff0.png)

**Comment by renekopcem** [comment]
Hello Jana,

this is fixed in recent build. Thank you for reporting this bug.

Roman
