### ISSUE TITLE
Sketch 3.7.0

### ISSUE THREAD

**Issue by marco-uccellini** [avocode/avocode#829]
Hi,

Currently running 3.3.0 avocode sketch plugin with Sketch version 3.6.1.

Before I update my version of Sketch can I check if the avocode sketch plugin is compatible with the latest version of Sketch 3.7.0.

Thanks

Marco

**Comment by jakubzitny** [comment]
Hi, yesterday we've released updated version of the Sketch plugin — [3.4.0](https://github.com/avocode/avocode/blob/master/sketch-plugin.md#340-april-14-2016). Most of the usual stuff works fine, however, there might be some issues with Symbol support.

We'd be happy if you gave it a try and let us know about any problems.

Thanks.

**Comment by marco-uccellini** [comment]
Thanks - I'll go ahead and update and let you know of any issues.

**Comment by jakubzitny** [comment]
I'll close this issue then. Feel free to let us know here, in a new issue or at team@avocode.com ;)
