### ISSUE TITLE
Error on Sync to Avocode

### ISSUE THREAD

**Issue by floriandotorg** [avocode/avocode#831]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.7.1
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/florian/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

Sketch 3.7.1, newest Avocode

**Comment by bolekkerous** [comment]
Hello, Florian!
It looks like you are still using the old Sketch plugin. Are you sure you are using the latest one?

Could you please try to uninstall the Avocode plugin completely from your Sketch and install the new one?

You can download it here:
https://github.com/avocode/avocode/blob/master/sketch-plugin.md#installation--update

Let me know whether it helps!

**Comment by floriandotorg** [comment]
Hi,

thanks for the swift reply.

I did that, interestingly what happened is:

![bildschirmfoto 2016-04-19 um 14 05 50](https://cloud.githubusercontent.com/assets/6143734/14638500/ed78cac2-0637-11e6-8842-9354451890a3.png)

![bildschirmfoto 2016-04-19 um 14 05 57](https://cloud.githubusercontent.com/assets/6143734/14638507/f063122e-0637-11e6-9d08-170fec1f90e3.png)

![bildschirmfoto 2016-04-19 um 14 06 03](https://cloud.githubusercontent.com/assets/6143734/14638519/f399d608-0637-11e6-99ae-570cfb38f6d8.png)

![bildschirmfoto 2016-04-19 um 14 07 39](https://cloud.githubusercontent.com/assets/6143734/14638575/197b136e-0638-11e6-9e47-7a42f5705947.png)

Something is odd with this version ..

**Comment by bolekkerous** [comment]
The "Sync to Avocode" is old version of Avocode. The new one is called "Avocode Sync 3.4". What happens when you click "Avocode Sync 3.4"?

**Comment by floriandotorg** [comment]
Ahh, I see. Interestingly the old version wasn't event installed anymore, but anyway it works now. Thanks!

**Comment by bolekkerous** [comment]
Glad to hear it helped and works now. Sorry for the confusion. :-)

Best regards,
Bolek, Avocode Team
