### ISSUE TITLE
Linux slow

### ISSUE THREAD

**Issue by Sendoushi** [avocode/avocode#832]
I've been trying Avocode on my computers. Still in trial and almost ending. It works flawlessly no Mac and let me congrat for the idea but I can't go on and pay for this solution because of the Linux version.

Linux version is slow, pretty hard to use rulers and guides for example.

**Comment by jakubzitny** [comment]
Hi, thanks for your report. We're currently rewriting large parts of the app to work better on all platforms, including rulers and guides. The new version will be available in coming weeks.

We'll keep you updated. Thanks for reaching out ;)

**Comment by Sendoushi** [comment]
Cool. If you need more devs... :)

**Comment by jakubzitny** [comment]
Actually we do need more devs :D Right now we are looking for a JS/React developer for a part-time collaboration. We are open for more serious positions as well. Drop us a line at petr@avocode.com.

**Comment by Sendoushi** [comment]
Nice. Already "dropped a line" thanks.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by anorudes** [comment]
+1, very slow on ubuntu 14.04

**Comment by jakubzitny** [comment]
@anorudes which version of Avocode are you using?
