### ISSUE TITLE
Issues on retina MBP from Sketch sync

### ISSUE THREAD

**Issue by EightDJ** [avocode/avocode#833]
Hey guys,

We're evaluating using Avocode as our main tool for collaboration between our design teams and developers. At the moment the biggest complaint we have is that files synced from Sketch don't scale up properly on a retina display. Text / graphics are all using vectors and shouldn't have a problem with scaling, however, when opening a Sketch file in Avocode, the file appears at half the size but says it is zoomed to 100%.

If the "Retina canvas" option is disabled, the image appears at the correct size for 100% zoom, however it is totally pixelated. Likewise, zooming to 200% with "Retina canvas" enabled also produces the correct size, but is still blurry.

![image](https://cloud.githubusercontent.com/assets/4405822/14742080/b4ae611a-089a-11e6-804a-9e5a52185107.png)

It's difficult to see in the thumbnail, but the text for the rulers is displayed in high-definition, where as the design text is pixelated.

Is there any progress on fixing this or a workaround of some kind?

**Comment by EightDJ** [comment]
Can I please have some feedback on this?

**Comment by connor-bean** [comment]
Hello -

Our apologies on the very delayed response here. 

We are currently working on improving the rendering and we have added your ticket into our internal tracking system. Our only workaround at this point in time is to have your designer create a design in @2x, which will then work better in the Avocode app.

Once again, we definitely apologize for the poor communication.

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
