### ISSUE TITLE
Old username shows up in profile drop-down

### ISSUE THREAD

**Issue by ChristineSchatz** [avocode/avocode#834]
Reproducibility: I don't know if this is possible, as I'm using version 2.6.0, and the issue was created when using the previous version, but still persists

Description: I accidentally typed in my password as my username when I signed myself into the Avocode application. I then modified my username, but my password still shows up in the upper right hand corner (the user profile area), even after closing and restarting the application. It's not a huge deal but concerned about someone seeing my password. What is causing my old username to keep showing up?

Steps to reproduce:
Expected result:
Actual result:

OS and app versions: Avocode 2.6.0, desktop application

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
