### ISSUE TITLE
Add desktop file to linux package

### ISSUE THREAD

**Issue by jsvgoncalves** [avocode/avocode#835]
Would be cool to have a `avocode.desktop` file prebundled in the linux package, i.e.:

```
[Desktop Entry]
Name=Avocode
# $HOME/lib or whatever other path for the binary
Exec=$HOME/lib/Avocode-linux-x64/Avocode
Icon=$HOME/lib/Avocode-linux-64/avocode.png
Type=Application
Categories=GTK;GNOME;Utility;
```

And possibly some script to install it based on the linux distro, e.g.:

```
$ cp avocode.desktop /usr/share/applications/
```

Or specifically for ubuntu:

```
$ desktop-file-install avocode.desktop
```

**Comment by jakubzitny** [comment]
Thanks João, we'll definitely add it in coming releases ;)

**Comment by jakubzitny** [comment]
We've added apt repository a while ago so I'll close this issue.

Ubuntu and other Debian-like distros should be able to install Avocode easily with Desktop file as well. Detailed info on how to add the repository, install and update is at [help.avocode.com](https://help.avocode.com/app-settings/installing-avocode-on-linux). We also have a [repo in AUR](https://aur.archlinux.org/packages/avocode/) for Arch Linux and Avocode zip downloads for other Linux systems include Desktop file as well.
