### ISSUE TITLE
Show/hide layer not always works

### ISSUE THREAD

**Issue by trurl-master** [avocode/avocode#838]
I've found the following scenario when it happens:
- start avocode
- open first mockup (psd) → "eye" works
- open second one in parallel → "eye" doesn't work

App v.2.8.0-beta.2

**Comment by vojtatranta** [comment]
Hi, thank you for this report.
We actually noticed this bug by ourselves the same day you report it and we fixed it.
It will be alright in 2.8.0 as well as in the next beta.

**Comment by connor-bean** [comment]
Hey, @trurl-master -

What OS are you running?

Thanks,
Connor, Avocode Support

**Comment by trurl-master** [comment]
Sorry for late response, Ubuntu 16.04 if it still matters

**Comment by jakubzitny** [comment]
@trurl-master Can you check if it's still happening in Avocode `2.8.1`? You can download the update at [avocode.com/download](http://avocode.com/download/).

**Comment by trurl-master** [comment]
Looks good.

**Comment by jakubzitny** [comment]
Awesome, thanks for quick response. I'll close this issue then. Feel free to let us know if you have any more problems with Avocode ;)
