### ISSUE TITLE
Text layers can mess up the CSS syntax highlighting

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#840]
When a text layer has multiple lines of text  (e.g. a vertical navigation menu) the generated CSS comment messes with the syntax highlighting:

<img width="310" alt="avocode_text_layer_css" src="https://cloud.githubusercontent.com/assets/5463/14811944/185abf30-0b9b-11e6-9d2d-1964cb7815a0.png">

**Note:** Screenshot from Version 2.8.0-beta.2 - previous versions messed up the rest of the CSS, so this is an improvement, though still not perfect :-)

**Comment by vojtatranta** [comment]
Thank you for this report.
It will be fixed, it's a small bug.

**Comment by connor-bean** [comment]
Hey, @greystate -

What OS are you running?

Thanks,
Connor, Avocode Support

**Comment by greystate** [comment]
@connor-bean I'm on "latest" Mac OS X, 10.11.5, I guess

**Comment by petrbrzek** [comment]
@vojtatranta Is this one fixed?

**Comment by greystate** [comment]
I'm not able to verify this at the moment, since my Mac is at the repair shop currently — so working from a loaner Mac that's slow as a snail, as well as on an earlier OS version :-) So haven't even tried installing Avocode on it.

Should have my own back in a couple of days though, and I'll let you know.

**Comment by greystate** [comment]
Got my Mac back, and checked — so far, I haven't been able to reproduce this in **2.8.0-beta.6** so that's great  🙌

**Comment by bolekkerous** [comment]
This should be fixed.

Do let us know in case you encounter this problem again.
