### ISSUE TITLE
Processing stuck at 95%

### ISSUE THREAD

**Issue by hiliz007** [avocode/avocode#843]
version 2.6.0

on processing it gets stuck with some heavier PSDs

**Comment by connor-bean** [comment]
We currently have some issues with huge bitmap images in PSD's (most of the times shutterstock images nested in a smart objects - usually with layers that are over 20mpix). Could this be the case? 

I'd recommend to use the Photoshop plugin to sync the design until we fix this issue. You can also ask your designer to resize the resolution of those images or rasterize them. If you do not have access to Photoshop, you can always send the design to us at team@avocode.com and we'll upload it for you as soon as possible.

We're already working on our own rendering, which should fix the problem.

Let me know!
Thanks,
Connor, Avocode Team

**Comment by rychlis** [comment]
For how long exactly does it get stuck? Will it unstuck when you restart Avocode App?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
