### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by MattGelfand** [avocode/avocode#844]
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.1 running in Sketch 3.7.2
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/matt.gelfand/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by bolekkerous** [comment]
Hello, Matt!
It looks like you are using an old version of Sketch plugin. You can download the latest here: https://github.com/avocode/avocode/blob/master/sketch-plugin.md

If you do have the latest installed, make sure you are using the right one. The latest one is called Avocode Sync 3.4 in the Sketch Plugin dropdown menu.

Let me know whether it helps!
Best regards,
Bolek, Avocode Team
