### ISSUE TITLE
Symbols in pages imported from Sketch are read by Avocode as images

### ISSUE THREAD

**Issue by MBoomworks** [avocode/avocode#845]
The only way around this is to detach each symbol from its master everywhere it appears in Sketch before uploading. It would be much more helpful if symbols were able to be read without detaching them, in case of changes to design files being required. 

Tested just importing a symbol on its own from the Symbols page - imports layers etc but doesn't show any user selection of items, the item's details and its distance from other elements around it. 

Running Avocode 2.6.0 and Sketch 3.7.2, Mac

**Comment by verteb** [comment]
Same thing here with sketch ! Same versions as MBoomworks. So right now we are left with no vector smart objects using photoshop or flat symbols using sketch. Please fix this as soon as possible, this is a deal breaker for us...

**Comment by connor-bean** [comment]
Hello and thanks for the reports. Can you send the problematic designs to team@avocode.com so we can troubleshoot further? 

Thanks,
Connor, Avocode Team

**Comment by connor-bean** [comment]
Hello, thanks for the report. 

As of now, Sketch symbols are being read as images. We should be adding better support for this in our next plugin version. Hopefully we will be getting to this new version in the upcoming months. 

Thanks,
Connor, Avocode Team

**Comment by MBoomworks** [comment]
Hey Connor,

Thanks for getting back to me – did you still need to see the design files as per the email before this one?

Cheers,
Magda
=================================

Magda Bytnerowicz
Digital Design Creative

Boomworks Pty Ltd
Empowering design

tel: +61 2 9557 9710
www.boomworks.com.au<http://www.boomworks.com.au/>

**Comment by n0rule5** [comment]
The next plugin version _should_ or _will_ fix this? And _hopefully_ it's months away?

Symbols is one of the most powerful and time-saving features in Sketch. All of my existing files (over 100 artboards) are littered with symbols. Going into each file, detaching all of the symbols, and completely ruining how my files are setup is not a reasonable option.

**Comment by connor-bean** [comment]
Hey, MBoomworks -

No need to send a design file for this as we are aware of the problem. 

Thanks for following up, though!
Connor, Avocode Team

**Comment by connor-bean** [comment]
Hey, n0rule5 -

We are going to try to start looking into possible solutions this upcoming week. However, we do not have any of it scoped out so we cannot give you a firm date on when we'll know more or when we plan to have a new solution. We would like to have something for you in the upcoming few months, but we can't commit to a date at this point in time. 

Please email us at team@avocode.com if you have any other problems.

Thanks,
Connor, Avocode Team

**Comment by rBunin** [comment]
Looking forward to see that fix. It's really limits the use of the product!

**Comment by marisnaylor** [comment]
Agreed! Can't wait!

**Comment by whoiskjl** [comment]
I can't wait for the fix. My workflow is suffering tremendously :D

**Comment by KUSDAVIE** [comment]
Any updates?

**Comment by michaelkodim** [comment]
any updates on this? this is really bad for our workflow guys ... :(

**Comment by privatemonkey** [comment]
Hi, we're just evaluating Avocode for our workflow and this is definitly a breaking issue with our dependence on symbols.

**Comment by matiunin** [comment]
Ok it's great news!

**Comment by connor-bean** [comment]
Hey, thanks for checking in on this. We definitely appreciate the urgency surrounding this and we plan on having a solution for you in the upcoming few weeks.

Please let us know of any other questions!

**Comment by Kilian** [comment]
As we're using more and more sketch symbols in our designs this is becoming a rather large impediment for us too!

**Comment by ewydler** [comment]
Please fix this! Like many of us her,e we depend on symbols to keep consistency across our art-boards. Having to detach everything is time consuming and not scalable for making changes.

**Comment by morcegon** [comment]
Same in here :(

**Comment by whoiskjl** [comment]
I don't want to be that impatient child, but this needs to be addressed soon.

**Comment by petrbrzek** [comment]
We have a working solution for symbols. The next release will include support for it.

**Comment by MBoomworks** [comment]
Awesome news @petrbrzek 

Thank you.

**Comment by ewydler** [comment]
Finally! Thank you

**Comment by whoiskjl** [comment]
yes

**Comment by privatemonkey** [comment]
Nice - I will give it another try

**Comment by petrbrzek** [comment]
We released 2.10.1 yesterday with the support of Sketch symbols. You can now open symbol in the same fashion as smart objects. Let me know if it's working for you. 

![symbols](https://cloud.githubusercontent.com/assets/879564/18268506/5a57b702-7424-11e6-91ac-96ad1ecc4730.gif)

**Comment by MBoomworks** [comment]
Thanks for working on this Petr! Unfortunately we're not quite there - maybe it's just my team, but when we double click on symbols, we get the following error:
![screen shot 2016-09-07 at 9 31 34 am](https://cloud.githubusercontent.com/assets/18690038/18462197/8bdbd660-79c3-11e6-8630-ca19781bd5a2.png)
This occurs with old files that were there before this fix as well as a new one I just uploaded to test, hoping it was a legacy thing.

Any ideas as to how to fix this?

Cheers!

**Comment by bolekkerous** [comment]
Hey there!
Make sure you have the symbols synced from Sketch. They are shown as separate artboards in Sketch plugin. Without them, the application doesn't have the data to open the symbol. Once you sync the symbols to Avocode, it should open just fine.

Hope it helps!
Bolek, Avocode Team

**Comment by MBoomworks** [comment]
Ah, derp. Got it. Thanks!

**Comment by thvi** [comment]
Hi,

Sketch Symbols don't work on Avocode for Windows :( https://drive.google.com/file/d/0B7zCpk0Wxgb1NTA2ZmVqXy1nNk0/view

Cheers!

**Comment by bolekkerous** [comment]
Hi, @thvi -
from the screenshot it looks like you're using really old version of Avocode.

Please download the latest one here:

https://avocode.com/download.html

**Comment by thvi** [comment]
Great! Thanks!



Cordialement,
Thierry Vilaysith <http://anglapar.fr/>  |  Blog
<http://anglapar.fr/blog/retours-d-experience.php>
06 26 22 52 38
Linkedin <http://www.linkedin.com/in/thierryvilaysith>, Twitter
<https://twitter.com/thvi>, Behance
<http://www.behance.net/thierryvilaysith> & Youtube
<https://www.youtube.com/channel/UC1q3msBtvqF620UEaDaosbA>.
