### ISSUE TITLE
Avocode Sync Plugin in Sketch doesn't  work

### ISSUE THREAD

**Issue by katjabruhn** [avocode/avocode#846]
I want to sync my sketch file with avocode, but it doesn't work. I don't know the cause. After starting the plugin in, the avocode windows opens, but nothing more happens after that. 
What can I do?

It's the latest version of Avocade and the plugin.

**Comment by connor-bean** [comment]
Hello!

Could you send us a screenshot of the error?. And we also need log files from Sketch. Here is a guide on how to get log files - https://github.com/avocode/avocode/blob/master/sketch-plugin.md#reporting-bugs

Another thing that would really help us is if you could upload the problematic design for us so we can see what exactly causes the problem.

We also need to know what version of Sketch and OSX you are using, could you please provide us with that information so we can address the problem properly?

Could you send this all to team@avocode.com?

Thank you,
Connor, Avocode Team

**Comment by rychlis** [comment]
The issue was fixed by removing `avocode-token.json` from the Plugin folder. The extension should handle such case better I'll keep the issue open until we fix that

**Comment by billcbanks** [comment]
Is this still an issue? I sync with the plugin and all screens turn up white in Avocode. Elements/layers are there, but invisible.
![avocode_2_8_4](https://cloud.githubusercontent.com/assets/111444/17025084/f550e2f8-4f1f-11e6-97fe-bb806a62693a.png)

**Comment by roxannekrumm** [comment]
Hi, I'm having the same issue above with the elements being there, but being invisible.
I have updated my OSX, sketch, and avocode.
What could be the issue?
<img width="256" alt="screen shot 2016-07-26 at 11 43 05 am" src="https://cloud.githubusercontent.com/assets/20665910/17144780/f4f94fde-5325-11e6-85f5-78e21848da3d.png">

**Comment by rychlis** [comment]
@roxannekrumm @billcbanks your issue is not related to the original one. Are you sure you updated the Sketch Plugin to 3.8, restarted Sketch and re-synced the affected designs? If you did that hit us on team@avocode.com and specify which designs have this issue so we can check it out.

**Comment by singlow** [comment]
I am having this issue now. Designs synced from Sketch before my designer updated were working fine, but any designes synced today are broken.

**Comment by singlow** [comment]
OK so designer updated sketch but not the Avocode  plugin. That seems to have solved it.

**Comment by bolekkerous** [comment]
This should not happen anymore with the latest version of the Sketch plugin.

You can always download the latest version here:
https://manager.avocode.com/downloads/

If you still experience this problem or any other problem, please create a new issue or comment here.
