### ISSUE TITLE
Missing data from Sketch design

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#848]
I'm getting this problem a lot lately, where stuff is just missing in Avocode - e.g.:

![comparison](https://cloud.githubusercontent.com/assets/5463/14886979/f85ff622-0d53-11e6-9e25-196bb176c7e4.jpg)

(Left side is the Sketch design, right side Avocode's interpretation)

As you can see, Avocode gets the textlayer correct (text is there, CSS color is correct) but the text is not visible in Avocode.
Likewise, the white border on the **Email** input field is missing - but I can select it and get the correct CSS style (`border: 8px solid #fff;`)

Both of the missing elements here are elements that have been copied in Sketch, but looking at the file there are no differences between them (in Sketch).

**Comment by bolekkerous** [comment]
Hello!
Thanks for the report!

Could you please tell us what version of Avocode are you using? And what version of Sketch plugin? And version of OSX?

Also, could you please send us any example of the problematic design to team@avocode.com? It would help us a lot in pinpointing the problem.

Best regards,
Bolek, Avocode Team

**Comment by greystate** [comment]
Hi,

The screenshot was from **Avocode 2.8.0-beta3**, and **Sketch 3.7.2 (28276),** using **Avocode Sync 3.4** - I'm on **OS X El Capitan, 10.11.4**

**Note:** I've just tried opening the design in Avocode 2.6.0 which *doesn't* have this issue...

Thanks,
Chriztian

**Comment by greystate** [comment]
Alright, I've sent a reduced design (deleted pages that wasn't part of the design with the issue) to team@avocode.com

/Chriztian

**Comment by greystate** [comment]
Just confirming this is fixed for me in 2.8.0-beta.4

👍

**Comment by greystate** [comment]
And then again... seeing a variation of it in another artboard; Avocode shows the correct CSS color value while it's black on the canvas...

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
