### ISSUE TITLE
Slide tool removing

### ISSUE THREAD

**Issue by PixelT** [avocode/avocode#849]
Hi

I know you are have in plan work with the totally new slice tool, but why you deleted the current version?
You can stay with this tool and upgrade it (new version of slice) with next avocode version?

**Comment by vojtatranta** [comment]
Hi,
slice tool is removed only in Beta releases. 
Unfortunately, refining other parts of Avocode made original slice tool obsolete in too many ways and it was unusable.
But in the next Beta (probably next week) you will have new version already!
In next major 2.8.0 (not Beta) you will get brand you slice tool.
