### ISSUE TITLE
An error occurs when opening uploaded PSD file

### ISSUE THREAD

**Issue by seerocode** [avocode/avocode#851]
MY PSD file uploads successfully on the desktop Windows app and when I click to open it, it starts loading the metadata and then I get this message:

![image](https://cloud.githubusercontent.com/assets/10480484/14943006/378c9612-0f9c-11e6-8e5b-cf7a68ef0432.png)

I've tried it a few times and I'm running 2.6.0.

**Comment by connor-bean** [comment]
Hello!

Thanks for the report. Could you send us the problematic design to team@avocode.com?

Please also include the OSX you're using and if you use Sketch or not.

Thanks!
Connor, Avocode Team

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
