### ISSUE TITLE
Decay between elements and informations

### ISSUE THREAD

**Issue by rodnem** [avocode/avocode#852]
Hi!
I have a big decay in synced symbols.
http://cl.ly/1N0u0k2R3q3A

I've synced several times to control my uploads but it seems that I've got this issue only in symbols

Avocode 2.6.0 / Avocode Skecth plug 3.4 / Skecth 3.7.2 /

**Comment by bolekkerous** [comment]
Hello!
Could you please share the problematic design with us at team@avocode.com?

Thanks!
Bolek, Avocode Team

**Comment by rodnem** [comment]
Ok, I will put #852 as subject of my mail

**Comment by connor-bean** [comment]
Thanks!

**Comment by connor-bean** [comment]
This issue looks to be the same as #842 so we will be tracking in ticket #842 instead. I will close this out and we will follow it there.

Thanks!
Connor, Avocode Team
