### ISSUE TITLE
Sketch plugin - missing text in beta

### ISSUE THREAD

**Issue by janaobzerova** [avocode/avocode#853]
Printscreen from Avocode 2.6.0 and Avocode 2.8.0-beta3

But I do not have original sketch file...

<img width="470" alt="screen shot 2016-05-03 at 12 06 39" src="https://cloud.githubusercontent.com/assets/12643008/14980284/d8d8c25c-1127-11e6-909f-80a4a734a5b3.png">
<img width="470" alt="screen shot 2016-05-03 at 12 06 33" src="https://cloud.githubusercontent.com/assets/12643008/14980285/d8f9fec2-1127-11e6-9a4c-31364f52dae5.png">

**Comment by connor-bean** [comment]
Hey, Jana -

Thanks for sending this!

Would you be able to send us the sketch log file to team@avocode.com? This link will show you how get the log:

https://github.com/avocode/avocode/blob/master/sketch-plugin.md#reporting-bugs

Thanks,
Connor, Avocode Team

**Comment by bolekkerous** [comment]
Hello again!
This looks similar to #848 - I'll close this issue and you can track the progress on the other one.

If you could somehow get the original sketch file and send it to us, it would be greatly appreciated.

Best regards,
Bolek, Avocode Team
