### ISSUE TITLE
Enhancement suggestion: Project manager list view

### ISSUE THREAD

**Issue by MBoomworks** [avocode/avocode#854]
Would be nice to view designs inside a project as a list, thumbnail left hand side and **full file name** visible - currently the grid view truncates longer file names which can make complex projects with many variations on pages difficult to navigate

**Comment by jakubzitny** [comment]
Hi @MBoomworks, a list view in project-manager is now available in latest version of Avocode. Please update and let us know what you think 😉

**Comment by bolekkerous** [comment]
List view was added in Avocode 2.26.3. 

Let us know in case you encounter any issues with it!
