### ISSUE TITLE
Selecting layers in hidden group

### ISSUE THREAD

**Issue by kupcza** [avocode/avocode#858]
Avocode 2.8.0 beta.3

I got design with some hidden layers, but when using select tool, it selects hidden ones. All layers are in hidden group, but still can select them. 

![Selecting hidden layers]
(https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/autqeuo6.png)

**Comment by connor-bean** [comment]
Hey, @kupcza -

What OS are you running?

Thanks,
Connor, Avocode Support

**Comment by petrbrzek** [comment]
I think it has been fixed. Can you confirm that @kupcza? I'm closing it for now.
