### ISSUE TITLE
Bad font-family

### ISSUE THREAD

**Issue by prokopsimek** [avocode/avocode#86]
Avocode generates font "PlayfairDisplay"

```css
    font-family: "PlayfairDisplay";
```

But this font-family is with one blank space:
```css
    font-family: "Playfair Display";
```

(Google font)

**Comment by petrbrzek** [comment]
We've added variables where you can substitute values. This issue is perfect use-case for it. Closing this one. 

PS: Variables will be available in the next release.

**Comment by prokopsimek** [comment]
Thx, man! :-)
Dne 5.1.2015 20:39 "Petr Brzek" <notifications@github.com> napsal(a):

**Comment by Rad1calDreamer** [comment]
"Roboto Condensed" detected like "Roboto"
