### ISSUE TITLE
Avocode 2.8.0-beta.4 with Moom

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#862]
I use [Moom](https://manytricks.com/moom/) for managing windowsizes & -positions — usually I just make Avocode fill the screen (not the same as OS X "Fullscreen").

The 2.8.0-beta.4 no longer remembers this, so when launched, it starts in the default position.

(Moom is v3.2.5)

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
