### ISSUE TITLE
I tried to Sync a new design in Avovode through Avocode Plugin and occurred an unexpected error.

### ISSUE THREAD

**Issue by dantasjadson** [avocode/avocode#864]
![screen shot 2016-05-13 at 09 05 38](https://cloud.githubusercontent.com/assets/1027401/15247476/e664de9a-18ea-11e6-9c98-74c391735e72.png)
IMPORTANT: Please try to describe how did it happen.

-----
Sketch Exporter 2.1.5 running in Sketch 3.7.2
```
Error: Error: Command failed: 2016-05-13 09:00:07.654 sketchtool[63980:4886541] Error: caught exception whilst suppressing update events: *** -[MSUnarchiver decodeObjectForKey:]: cannot decode object of class (MSImmutableSymbolInstance) for key (NS.object.2)

**Comment by jakubzitny** [comment]
Hey @dantasjadson, thanks for the report.

I've noticed that you're using an old version of our Sketch plugin. Please install the newest one as described in [this tutorial](https://github.com/avocode/avocode/blob/master/sketch-plugin.md). Make sure you click on `Avocode Sync` to run the new version. Once you run it, the old one should be automatically removed.

Let us know if you have any more problems ;)
