### ISSUE TITLE
Guides are broken

### ISSUE THREAD

**Issue by Legys** [avocode/avocode#865]
Look at this
![u7xqzhv-zde](https://cloud.githubusercontent.com/assets/14238528/15272669/35451ca6-1a89-11e6-818e-d11245d6628f.jpg)
![rlxlmar2xek](https://cloud.githubusercontent.com/assets/14238528/15272670/3d3e7eb6-1a89-11e6-8e8e-11cbda5b6356.jpg)
and now look at Photoshop
![bcruzxzgo6o](https://cloud.githubusercontent.com/assets/14238528/15272673/4faef3e6-1a89-11e6-8a32-eb1c7b324c0b.jpg)
I'm testing about 5-6 different psd templates.

**Comment by Legys** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/14238528/15272741/d250ed52-1a8b-11e6-9f02-8052baf59ba8.png)

**Comment by rychlis** [comment]
Hello, there was an issue when processing PSDs which resulted in guides locations exported in wrong unit. We have just deployed a fix for this issue

We will try to fix this retrospectively for existing documents, in the meanwhile you can fix this by re-uploading the document. Thanks for your report!

**Comment by Legys** [comment]
Hello. I'm trying to re-upload about 5-6 attempts.
And testing about 10 different PSDs. Another people doesn't have this problem with the same PSD.

15.05.2016, 23:50, "Tomáš Rychlik" <notifications@github.com>:

**Comment by Legys** [comment]
so, where is problem solving?
you just close the ticket.

**Comment by jakubzitny** [comment]
Hey @Legys. As @rychlis already wrote, we currently don't have a quick solution for existing designs. The best way for you to fix this is to upload the PSDs "from the scratch" again. We looked into out database and it looks like you have not tried this. So please, try it.

If you still have problem with it, we can manualy re-process the designs for you.

**Comment by Legys** [comment]
i don't understand how i can do this.
Just save PSD in photoshop? all units in pixels and other people work with this PSDs

**Comment by jakubzitny** [comment]
Just treat is as new design you would be adding to Avocode. Save the PSD as a new file (Save as) and Sync that to Avocode again. Then you'll have a new link to the design in Avocode and you can send it to everyone.

Let us know how it works out for you ;)

**Comment by Legys** [comment]
thank you. it works.
Waiting for fix, cuz speed of workflow is suffered.
i'm happy now.

**Comment by jakubzitny** [comment]
Glad to hear that ;)

Fell free to create new issue if you have any more problems with Avocode.
