### ISSUE TITLE
Newest sketch-plugin-mac-3.5.0 doesn't work

### ISSUE THREAD

**Issue by slacku** [avocode/avocode#873]
Hi,
I just installed newest sketch-plugin-mac-3.5.0 and it doesn't work. When When I am launching plugin in Sketch it is loading all the time. Please, let me know where I can find older version.

It is the second, same situation when your new plugin doesn't work.

![zrzut ekranu 2016-05-18 o 15 53 30](https://cloud.githubusercontent.com/assets/16917963/15361338/4b15f61a-1d11-11e6-91f8-7d431a5fdfa0.png)

**Comment by bolekkerous** [comment]
Hi, we're sorry for the inconvenience.

Could you please try to go to the plugins folder (plugin dropdown in Sketch - manage plugins - right clicks and show plugin folder) then close Sketch entirely and delete the avocode-token.json file (next to sketch-panels.log)?

It should solve the problem.

Let me know whether it helps!
Best regards,
Bolek, Avocode Team

**Comment by slacku** [comment]
Hello!
Thank you very much for your fast reply. Your advice helped me, thanks! :)

Serdecznie pozdrawiam,
Eryk Ulewicz

2016-05-18 20:09 GMT+02:00 Bolek <notifications@github.com>:
