### ISSUE TITLE
Color palettes

### ISSUE THREAD

**Issue by PixelT** [avocode/avocode#874]
1. List of colors, which are using in open project / psd (this same way as fonts are listed)
2. Possibility to select & easy copy all exist color values

2a. (Optionally) Automatically create variable names for each color ( http://chir.ag/projects/name-that-color/ or http://html-color-codes.info/color-names/ etc )

**Comment by jakubzitny** [comment]
Hey @PixelT, thanks for sugeestions. 

As a matter of fact, we have these features planned for near future. You can vote for this and also other features on our [UserVoice forum](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7575030-automatically-generate-the-color-palette-from-the).

**Comment by PixelT** [comment]
By the way - the list of all existed font-size in psd, will be also nice to see +1

**Comment by bolekkerous** [comment]
This should be already implemented.
