### ISSUE TITLE
Gigantic text in top menu on Linux

### ISSUE THREAD

**Issue by JirkaVebr** [avocode/avocode#875]
Hi,

This is what it looks like:
![screenshot from 2016-05-20 14-47-08](https://cloud.githubusercontent.com/assets/361072/15429830/9957c8e6-1e9a-11e6-8a18-cd296137deca.png)
![screenshot from 2016-05-20 14-47-11](https://cloud.githubusercontent.com/assets/361072/15429829/995722ce-1e9a-11e6-9e09-a78e0eff35e7.png)

All other menu items open a similarly unusable dialog.

I'm running a freshly downloaded Avocode 2.6.0 on Arch Linux 4.5.4.1 with Cinnamon on a high dpi screen but I don't believe there's anything wrong with my system's scaling as other Electron apps render just fine.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
