### ISSUE TITLE
Syncing and site problems

### ISSUE THREAD

**Issue by Matheus-Cardoso** [avocode/avocode#878]
My team is facing some problems while trying to sync some repositories in the Avocode app (linux and mac OS), and the site seems to load only its basic html. I'm facing problems to update the application cause the site is broken, and it seems to me that this is an internal error. We have an active account.
![avocode_error](https://cloud.githubusercontent.com/assets/6153768/15478916/c784f54e-20f3-11e6-8e3a-6ffc966b7b2b.png)
![erro2](https://cloud.githubusercontent.com/assets/6153768/15478917/c8ea91fa-20f3-11e6-8e57-5d398acbd4be.png)

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen it if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
