### ISSUE TITLE
Sketch Artboard Sync Not Working

### ISSUE THREAD

**Issue by gilljarvis** [avocode/avocode#879]
Having problems syncing Sketch artboards to Avocode - instead of the regular pop-up appearing an empty safari browser appears...any ideas why??

**Comment by bolekkerous** [comment]
Hello!
We're currently investigating the issue, it looks like it happens only on OSX 10.10.5 - Yosemite. Could you please confirm whether you are using the same version of OSX?

Thanks and sorry for the inconvenience!
Best regards,
Bolek, Avocode Team

**Comment by gilljarvis** [comment]
Hi! Thank you for the speedy reply.

Yes, I am using Yosemite 10.10.5 ... any ideas on when it will be resolved?

**Comment by filipamarta** [comment]
I'm having the same problem and I'm using Yosemite 10.10.5.

**Comment by connor-bean** [comment]
Hello, 

We were able to come up with workaround for the time being. Please use this link once you see the "about: blank" page:

http://media.avocode.com/sketch/loader.html?url=http://127.0.0.1:33162

We apologize for any frustration this is causing. 

Thanks,
Connor, Avocode Support

**Comment by rychlis** [comment]
We've released Sketch 3.6.0 that should fix this issue, you can get it from here https://github.com/avocode/avocode/blob/master/sketch-plugin.md
