### ISSUE TITLE
Unzip not working

### ISSUE THREAD

**Issue by helloiamvu** [avocode/avocode#88]
I am getting the following error when I try to unzip the acovode beta file

! C:\Users\rdunn\Desktop\avocode-beta-0.8.0 (1).zip: Cannot create data\resources\app\node_modules\avocode\node_modules\octopus-svg\node_modules\request\node_modules\form-data\node_modules\combined-stream\node_modules\delayed-stream\test\integration\test-delayed-stream-auto-pause.js

Total path and file name length must not exceed 260 characters

The system cannot find the path specified.

**Comment by marekhrabe** [comment]
this will be fixed until launch (we will probably have user-friendly installer instead of a zip)

hotfix for now might be to try to unzip directly to C:\, so the paths are shorter

**Comment by patrikholcak** [comment]
Should be fixed in Avocode 1.0
