### ISSUE TITLE
Avocode 2.8.0-beta.5 - color overlay problem

### ISSUE THREAD

**Issue by kupcza** [avocode/avocode#882]
[https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/q2sehbfv.png](https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/q2sehbfv.png)

I was testing color overlay and object was rendered with its original color not with color overlay. Don't know if it's bug or feature.

In 2.6.0 it's rendered correctly
[https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/ta_mis4b.png](https://dl.dropboxusercontent.com/spa/7umqxezjfny1dx9/ta_mis4b.png)

**Comment by vojtatranta** [comment]
Hi.
Thank you for your report we appreciate it.
We know that  we have few bugs when rendering .psds.

**Comment by connor-bean** [comment]
Hey, @kupcza -

What OS are you running?

Thanks,
Connor, Avocode Support

**Comment by petrbrzek** [comment]
I think this one is fixed in 2.8.2. Can you please confirm that @kupcza? I'm closing it now.
