### ISSUE TITLE
View on Avocode.com button in Notes & Discuss goes to 404

### ISSUE THREAD

**Issue by mattelen** [avocode/avocode#884]
When I click on the "View on Avocode.com" button in the Leave Notes & Discuss panel, it loads a 404 page in my browser - it loads https://manager.avocode.com/{revisionID}/comments/, while it appears what its meant to load is https://manager.avocode.com/view/{designID}/{revisionID}/comments/

This is on Mac OS X El Capitan running Avocode 2.80-beta.5

Thanks

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at [manager.avocode.com](https://avocode.com/download/). I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
