### ISSUE TITLE
beta.5 opens with "Welcome to Avocode" dialog

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#885]
The 2.8.0-beta.5 briefly shows a welcome screen that looks like a "first run" screen:

![avocode-launch](https://cloud.githubusercontent.com/assets/5463/15599795/0b87f7ec-23e6-11e6-97ed-fadbe369d968.jpg)

The Team name it suggests isn't the name of my team either (so I worry what happens if I accidentally click the **Continue** button?)

The dialog disappears when Avocode has finished booting though,and everything seems to work as expected.

(I'm on OS X 10.11.5)

**Comment by vojtatranta** [comment]
You are seeing it all the time? Again and again?

**Comment by greystate** [comment]
Yes - everytime I launch it.

**Comment by vojtatranta** [comment]
I see, that is really odd. We know that there is a bug when syncing onboarding state with the servers. But we haven't yet encountered such thing that you are seeing it again and again.
We also know that there's an issue when you quit app right after you finish onboarding, because of server request has not been finished so that we don't know whether you finished or not.

What about sidebars with video that pop out on project manager and in document view. Do they pop up again and again?

**Comment by vojtatranta** [comment]
Ou! You haven't go through this pages, right? You have not clicked "continue" so far, right? Oh than it is OK, you must go through this.
Maybe we should add condition so that this would not show to users that already have ever used Avocode differently. Thanks!!! Fixing it right now!

**Comment by greystate** [comment]
Correct - haven't clicked the Continue button :)

Let me know if you need me to provide more information.

**Comment by vojtatranta** [comment]
So as I said, you basically have to go through this and the worst thing is that it will just rename your project and team.
We are really sorry for this bug. Actually, it is completely my fault. Sorry for that.

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at [manager.avocode.com](https://avocode.com/download/). I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by greystate** [comment]
This has regressed (for me) in Avocode 2.9.1 (OS X El Capitan 10.11.5) - only this time it *doesn't* disappear by itself, forcing me to go through naming my team again *and* create a "My First Project", as if I'm a brand new user. I was seriously nervous about my existing 10 projects, if they'd disappeared... :-(

Additionally, I get the "Let's upload a design" sidebar "tutorial"...

**Comment by petrbrzek** [comment]
@greystate Is this still happening?

**Comment by greystate** [comment]
@petrbrzek No, didn't get it this time around :) Great!
