### ISSUE TITLE
Individual units

### ISSUE THREAD

**Issue by nemishkor** [avocode/avocode#887]
It's just question or advice if it does not exist. Can i setup Avocode for use "em" units for font-size and "px" for height and width? Many people used "em" and "rem' for responsive design, but not for height and width. Thank

**Comment by connor-bean** [comment]
Hello,

This is not currently a feature, but we have added it to our internal list of ideas to look into further in the future. Thanks for providing us with this feature request. 

Connor, Avocode Support

**Comment by vojtatranta** [comment]
We completely removed EMs as we were not able to tell exact value since EMs are affected by any parent element `font-size`. We now only allow users to display `REMs` which are reliable and can be applied on the font-size as well as on dimensions.
