### ISSUE TITLE
Avocode beta just freezes after update

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#890]
I got avocode beta, downloaded it and couldn't use it, because of issue: 
https://github.com/avocode/avocode/issues/886

After some time, I checked application one more time. Avocode updated and now, I cant see anything, application starts and just freezes.
http://prntscr.com/baxds7

**Comment by connor-bean** [comment]
Thanks for the report. We added your comments to our internal tracking database and will keep you updated in #883 so I will close this ticket out. Please refer to #883 for updates.

**Comment by VaclovasV** [comment]
Everything is ok with logging in, but after application is opened, i can see projects, but after clicking on them, application freezes all the time. This is not related with logging in...

**Comment by connor-bean** [comment]
Which Avocode Beta are you trying to run?

We released 2.8.6 last night, so if you haven't downloaded it yet, try that to see if it's fixed.

https://manager.avocode.com/download/app-beta/mac/

https://manager.avocode.com/download/app-beta/windows/

https://manager.avocode.com/download/app-beta/linux-ia32/

https://manager.avocode.com/download/app-beta/linux/

**Comment by VaclovasV** [comment]
@connor-bean see my attached screenshot 
http://prntscr.com/bay0pe
I'm already using 2.8.6

**Comment by VaclovasV** [comment]
@connor-bean ant this is how my avocode is behaving when opening random project:
http://prntscr.com/bay13g

**Comment by vojtatranta** [comment]
Hi @VaclovasV,
thank for your time.
Are you opening project or design?
We know that there are troubles with Windows with big designs that cause app crash.

**Comment by VaclovasV** [comment]
@vojtatranta this happens opening both

**Comment by vojtatranta** [comment]
Aha, you just click a project (just a project in Project Manager, not design) and app crashes?
That is really odd. We never encountered such thing. I understand that app crashes while opening a large design. That is because we use 32bits version of Electron and not 64bits (coming in next weeks).
But I see no reason to crash while just opening a folder (project) in Project Manager.

**Comment by VaclovasV** [comment]
It is not crashing, it just freezes. And it is not odd, we are using avocode in our team and this issue exists for each team member. We are thinking about moving to zeplin, not because of features, but it is simply - impossible to work.
My machine is quite good - ssd hard, i7, 8gb of ram. So, I have nothing to blame, except avocode.

**Comment by vojtatranta** [comment]
@VaclovasV I am really sorry to hear this. You still may use 2.6.0 which is current stable. Or do you experience same troubles there?

Of course you should blame Avocode, it is our job to make your work more comfortable.

Basically - this is Beta we expect there to be some bugs.

I examined your screenshots again (many thanks for them) and "freeze" after start is just booting of the app. This is, of course, a Bad User Experience - we are about to put there an animation so that users won't get a feeling that there is something wrong. In this moment whole app renders and that causes this delay.

Much more serious is the issue of freezing after opening a Project. Can you tell me how many project do you have? Are there like hundreds of them?
Is it more like lagging that freezing? After a while app goes on? Or do you have to reboot it?

**Comment by VaclovasV** [comment]
Maybe it would be enough to provide my account email on avocode?
Yes, it is normal to have bugs in beta, but why company releases beta version and asks to test it with public email notification, if even start page of application is not working (https://github.com/avocode/avocode/issues/886)? Where is the point? 

And this is not loading screen, because real loading screen is shown at the start, and something is written, but after some time, application just freezes (and if you are lucky and application will not freeze after opening it, it will freeze opening project in avocode). 

We are paying 129$ per month and now, this stuff is not even working.

**Comment by connor-bean** [comment]
Hey, Vaclovas -

We sent you an email to your Avocode address. Please let us know if you have any questions. 

Thanks,
Connor, Avocode Support

**Comment by VaclovasV** [comment]
@connor-bean - I've been on vacation, so were not able to respond quickly - sorry for that.
I wrote email to team@avocode.com with screencasts. Now, seems like this issue is gone (I am able to open project window, maybe my account was broken or something?), other issues persist, so I recorded them and sent to your team.
Maybe this will help.

**Comment by vojtatranta** [comment]
@VaclovasV Hi again!
First of all, we would like to thank you again. Your report helped us discover lots of bugs we would not discover easily.
We just released a new version of Avocode - `2.9.0` which should improve performance even more! So just click `Check for update` button in `Help` menu of Avocode and get this update along with Activity feed and notes tool - you can finally comment, respond and close issues right in the app!

We also had problems with Sketch - again.
Sketch developers are awesome, but their API for creating plugins is very unstable and nearly every release of Sketch breaks our plugin.
So we noticed that some of the desings on your account are broken - there are one or two "empty" revisions. If you update your Avocode Sketch plugin and upload those designs again these designs should be fixed.

Please let us know, whether the performance of Avocode has improved or not. We really appreciate it!

**Comment by VaclovasV** [comment]
Thank you from all our team :) Very good job!
Now, it explains everything, about plugin issues, because designers had issues with it.
Keep up good work, awesome!
Will be waiting for global variables in project and other improvements :)

**Comment by vojtatranta** [comment]
@VaclovasV so do you see the improvement in performance of Avocode?

You are welcome!

**Comment by VaclovasV** [comment]
@vojtatranta, yes we already saw performance improvement in earlier versions (I wrote email to your team), now - it is even faster :) Thx!

**Comment by vojtatranta** [comment]
I know you emailed us, but I wanted to know whether `2.9.0` brought improvement too. And it did.

I love to hear it!

Syncing of projects settings across user is also coming soon.

**Comment by vojtatranta** [comment]
@VaclovasV And one more thing about performance.

We know about two bigger bottlenecks in the app. So expect Avocode to be faster in the next releases too. We would be glad if you informed use about any performance improvement or drop.
