### ISSUE TITLE
Avocode 2.8.0-beta.5 - Can't export Layer Group as 2x

### ISSUE THREAD

**Issue by markst** [avocode/avocode#895]
Good work finally adding 2x & 3x support.

I'm able to export shapes (vector layers) as 2&3x, however I can't export a group of vector layers.

![image](https://cloud.githubusercontent.com/assets/274318/15716131/04e3b084-2819-11e6-8bda-985d186946f6.png)

![image](https://cloud.githubusercontent.com/assets/274318/15716093/d9ada96a-2818-11e6-946f-9e1240e8ca44.png)

**Comment by jankuca** [comment]
Hello, thanks for the report! We know about this issue and are working on making this work. Group layers need special treatment in cases when they have layer effects applied on them. We can definitely handle the simple case you are describing.

**Comment by markst** [comment]
Appears to be resolved now.
