### ISSUE TITLE
Incorrect width and height in export window (2.8.0-beta.6)

### ISSUE THREAD

**Issue by limiterCore** [avocode/avocode#899]
Here is a wrong image dimensions when I try to export it. Look to the right: width: 40px; height: 40px;
But in export window it show us: 41 x 41px

In fact the size of exported image is 40x40 (expected)

OS X. 
![screenshot 2016-06-02 20 23 20](https://cloud.githubusercontent.com/assets/2869059/15750615/a1eb398c-2900-11e6-91fe-5dcfad9db3c0.png)

**Comment by jakubzitny** [comment]
Hey @limiterCore, thanks for the issue, we overlooked this completely. It will be fixed for the final release.

**Comment by connor-bean** [comment]
Hey @limiterCore -

Would you be able to send us the problematic design to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support

**Comment by jakubzitny** [comment]
This is still not fixed in `2.8.0`, it will hopefully get into next patch release. I will reopen this just so we don't forget.

**Comment by limiterCore** [comment]
The problem is still here. I don't think this is a big problem, anyway.
I'll try to send you this sketch file (I don't have it for now).
