### ISSUE TITLE
Sketch Plugin 3.7.0

### ISSUE THREAD

**Issue by marco-uccellini** [avocode/avocode#905]
Just tried this updated plugin with  Safari, and artboards can't be selected :(

I discovered a workaround though, if you select by **clicking the mouse in combination with the CMD key on the keyboard.**, it works :)

The same is also true for the SYNC button.

However happy to say everything did sync :)

**Comment by bolekkerous** [comment]
Hey, Marco -
does this still happen even with the latest version of Sketch plugin?

**Comment by marco-uccellini** [comment]
Hi
Sorry I can't test this for you as I'm not currently using Avocode, as the project I was using it for came to an end awhile ago now.

**Comment by bolekkerous** [comment]
I'll close this issue then, if you happen to use Avocode later on and still have the problem or if anyone else has the same problem, please comment here or create a new issue.
