### ISSUE TITLE
Canvas not showing anything - Avocode 2.8.0 - beta 6

### ISSUE THREAD

**Issue by xar** [avocode/avocode#906]
Sometimes when i switch between windows canvas fail to render design. I can click on elements but i don't see anything. Then i need to repoen window.
![screen shot 2016-06-07 at 21 02 47](https://cloud.githubusercontent.com/assets/184865/15871190/980b836c-2cf3-11e6-9dd2-3dc7fc7e9621.png)

**Comment by vojtatranta** [comment]
@xar Hi,
thank you for this report.
We have not encountered such problem so far. We know that if you close pane stage disappears but nothing like this.
Have you tried for example to pan around the stage? It has not reappeared?

**Comment by connor-bean** [comment]
Hey!

We have released the newest version of the Avocode app, version 2.8, which we expect to fix this problem. Please download it at https://avocode.com/download/. I am going to close this ticket but please reopen if you’re still experiencing this problem in Version 2.8.

Thanks!
Connor, Avocode Support
