### ISSUE TITLE
Sketch plugin loading and nothing more

### ISSUE THREAD

**Issue by squadnik** [avocode/avocode#908]
After starting a Sketch plugin I can see only loading screen and nothing more happens.
Tried to reinstall plugin.
![avocode-loading](https://cloud.githubusercontent.com/assets/15327259/15923829/606e2fc6-2e2f-11e6-897a-f107df978656.jpg)

**Comment by squadnik** [comment]
Sketch is also up-to-date.

**Comment by connor-bean** [comment]
Thanks for the report.

Could you send us the log files from Sketch to team@avocode.com. Here is a guide on how to get log files - https://github.com/avocode/avocode/blob/master/sketch-plugin.md#reporting-bugs

Another thing that would really help us is if you could include the problematic design in your email to team@avocode.com so we can see what exactly causes the problem.

We also need to know what version OSX you are using, could you please provide us with that information so we can address the problem properly?

**Comment by bolekkerous** [comment]
This looks like issue #846

Could you please try to go to the plugins folder (plugin dropdown in Sketch - manage plugins - right click and show plugin folder), then close Sketch completely and delete the avocode-token.json file (next to sketch-panels.log)?

It should solve the problem.

**Comment by squadnik** [comment]
Thank you!
