### ISSUE TITLE
error on double click to open image

### ISSUE THREAD

**Issue by marioloncarek** [avocode/avocode#911]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.6.0
Source UID: 113145
```
TypeError: Cannot read property 'then' of undefined
    at e.requestRevisionDownload 
```

**Comment by connor-bean** [comment]
Hey thanks for the report.

Could you download our latest Beta and see if this fixes the problem?

Please Download Avocode Beta 2.8-Beta.6 Here:

Mac OS X 
https://manager.avocode.com/download/app-beta/mac/

Windows 
https://manager.avocode.com/download/app-beta/windows/

Linux ia32 
https://manager.avocode.com/download/app-beta/linux-ia32/

Linux x64
https://manager.avocode.com/download/app-beta/linux/

If it doesn't fix this problem, could you provide us with screenshots or a screencast of what you're seeing when you experience this error?

Thanks!
Connor, Avocode Support

**Comment by marioloncarek** [comment]
The bug has been fixed with new version, thanks!
