### ISSUE TITLE
Avocode 2.8.0 layers selection issue

### ISSUE THREAD

**Issue by xamedow** [avocode/avocode#913]
When I try to select particular layer, it always selects background layer instead. Layer did get selected, when has been found and clicked on layers tab.

**Comment by vojtatranta** [comment]
Hi!
Can you send that that design at team@avocode.com?
The hitmaps of clicking are smart, you really have to click that layer. But we will examine it, if you could send us that particular .PSD file.

**Comment by xamedow** [comment]
Hi, just send the desing to you. The problem reveals, when I toogle on any of the hidden groups. Probably its because of cyrrilic group names. On the same mock, but with latin group names, everything works just fine.

**Comment by vojtatranta** [comment]
@xamedow seems odd that latin characters fix it.
I would say that if you get a PSD where all the groups are displayed then it works - you would still be able to hide groups you don't want to be displayed.
We will fix this in the next release.

**Comment by xamedow** [comment]
So, to temporary fix this, i should set all groups visible in mockup with Photoshop, save it and reupload it in Avocode?

**Comment by limiterCore** [comment]
Interested too. It is a big trouble for me.

**Comment by vojtatranta** [comment]
@xamedow Yes exactly.
@limiterCore Do the same - temporary fix it using photoshop - show those layer groups and reupload. This week 2.8.1 should land which will fix it.

**Comment by joshsmith01** [comment]
I can't select text either.

**Comment by rodnem** [comment]
Same bug here ... with sketch upload
it's very annoying when it's large file

**Comment by gzaban** [comment]
Same bug here

**Comment by vojtatranta** [comment]
Hi all,
bug should have been fixed in latest update `2.8.1` - auto update, or download [here](https://avocode.com/download/).

Please confirm it if you can.

By the way if you have 64 bit Windows (which you probably all do) please download [Avocode Windows x64 build](https://manager.avocode.com/download/avocode-app/windows-x64/)!

**Comment by xamedow** [comment]
Its ok for my mockup now, thanks.

**Comment by limiterCore** [comment]
I've checked on my mockup: fixed
