### ISSUE TITLE
Box code font size is larger

### ISSUE THREAD

**Issue by victor-castro** [avocode/avocode#914]
A version before 2.8.0, the box code font size was a little smaller and better than this version. Could you change it again like the old version?

Best regards

**Comment by jakubzitny** [comment]
Hi @victor-castro, thanks for rasing an issue. You mean the size of the text in code panel, right?

Can you please provide us with more details on this? What OS are you using? Could you mabye attach a screenshot of what are you seeing?

We actually started using `Hack` font in code panel in version `2.7.0` and it really is a little bigger than the one before. Is `2.7.0` the version you've used before the latest update or did you have something older? We generally have positive feedback for this change. 

If you feel this is important for your workflow, we might consider adding an option to change the font size from Preferences.

**Comment by victor-castro** [comment]
Hi, thanks for your reply! Sometimes, some informations with this font size show incomplete for us. I really would prefer when the font size was smaller.
I guess adding an option to configure the font size on Preferences is a good idea and make us free to configure like we think is better to us.

Best regards
![print](https://cloud.githubusercontent.com/assets/8093262/16162126/cef0554a-34a7-11e6-9afa-2251dd4b7ade.jpg)

**Comment by jakubzitny** [comment]
I've added this to our internal TODO list. We'll inform you here when we implement it.

By the way, do you know about the option to click on a line in Code Panel and it will get copied?
You can configure this in the `Code` section of `Preferences`.

<img width="284" alt="screen shot 2016-06-18 at 13 20 39" src="https://cloud.githubusercontent.com/assets/3315662/16170578/8d935c90-3557-11e6-87b0-8f3dbeac04d7.png">

**Comment by vojtatranta** [comment]
you can now set any font size of code panel in Preferences - Code
