### ISSUE TITLE
Problem in Export Assets Window when Export path is long

### ISSUE THREAD

**Issue by sergiocarracedo** [avocode/avocode#918]
I found a bug in 2.8.0 that appers when the export path is long. The variant items overflow window, and i can't click in the remove button, neither the change export path button

![avocode_bug](https://cloud.githubusercontent.com/assets/1263666/16050601/9a99be6e-325c-11e6-8d46-2e3305545933.png)

**Comment by jakubzitny** [comment]
Hi @sergiocarracedo, thanks for reporting this.
We completely forgot to handle this case, my bad.

Will be fixed for next release.

**Comment by sergiocarracedo** [comment]
No problem ;)

**Comment by jakubzitny** [comment]
Hey, we've just released [Avocode 2.8.1](http://avocode.com/download/) which solves this issue. Please, check it out and let us know if you have any more problems with it.

Thanks ;)
