### ISSUE TITLE
Export is not working correctly

### ISSUE THREAD

**Issue by edDimensi** [avocode/avocode#919]
I don't know english, I will try to explain in pictures.
1. Avocode 2.6, export layer
![image](https://cloud.githubusercontent.com/assets/11390039/16062653/50331e38-329d-11e6-9eae-636c05511e60.png)
if i export in 2.6, 
I'll get a picture
![layer-23](https://cloud.githubusercontent.com/assets/11390039/16062689/7f591d8e-329d-11e6-83d8-524e7d9b3c54.jpg)
if i export in photoshop, i take some like result.
NOW
if i export in avocode 2.8
![export2 8](https://cloud.githubusercontent.com/assets/11390039/16062731/cd421c94-329d-11e6-882f-f3399a934ccc.jpg)
I have white area in image. In photoshop if i select layer.
![image](https://cloud.githubusercontent.com/assets/11390039/16062752/f6cb25ce-329d-11e6-882d-4d5854807a48.png)
And anyway, photoshop export what i see, with out white area...
I hope, you understand me.

**Comment by vojtatranta** [comment]
Hi,
thank you for this report.
Can you send us this problematic psd at team@avocode.com?
We will take a closer look.
By the way - if you have white spaces around a layer and cannot get rid of them. You can still use Slice tool to crop layer the way you want it to be.

**Comment by edDimensi** [comment]
I don't want crope, i want normal export) I back to 2.6 avocode and wait better times)

**Comment by jakubzitny** [comment]
Hi @edDimensi, thanks for sending us the design. We're investigating this issue, it looks like a problem with clipping mask. We'll post more info when we have it.

If you want to go back for now, you can [download 2.6 here](https://media.avocode.com/download/avocode-app/2.6.0/avocode-app-mac-2.6.0.zip) .

**Comment by akifuygun** [comment]
i am having so many problems exporting images.
most of them reported already.
most bugged version i've ever seen. :(

**Comment by renekopcem** [comment]
Hi @akifuygun, sorry to hear that. Could you send us the source file (sketch or psd) to team@avocode.com? We're investigating this issue, it looks like a problem with clipping mask. We'll post more info when we have it.

Thank you!

**Comment by petrbrzek** [comment]
@edDimensi Can you please try it in 2.8.2 and let us know? Thanks a lot.

**Comment by edDimensi** [comment]
@petrbrzek ok i try...

**Comment by edDimensi** [comment]
@petrbrzek, exports began to work better, but still not good enough, as in version 2.6.
I pay $ 9 a month for such a crude product. : '(
I live in Russia and $ 9 at the moment is quite a large sum for a solo coder. Photoshop + lightroom Package costs less than 1 your product is $ 9 with a lot of errors. It's horrible :(
Like Avocode, but he is too raw!

**Comment by vojtatranta** [comment]
@edDimensi please be more specific about "still not good enough".
We cannot fix any bugs if we don't know exactly what is wrong.

Sorry for those troubles, we are trying to improve Avocode as fast as we can. There is minor update practically every week.

**Comment by edDimensi** [comment]
@vojtatranta omg... i'm sorry! Export now work good! It's my mistake...
![image](https://cloud.githubusercontent.com/assets/11390039/16399715/c312df48-3cdd-11e6-812f-eda09010301b.png)
It's new font or bug?

**Comment by vojtatranta** [comment]
@edDimensi what do you mean by a "bug"?
This is stylus code and we added a bit different font.

**Comment by edDimensi** [comment]
Ugly font.

**Comment by vojtatranta** [comment]
highlighting is a bit broken, we are going to fix it soon
