### ISSUE TITLE
Hangs on "Downloading metadata" for specific layouts

### ISSUE THREAD

**Issue by JayCarney** [avocode/avocode#920]
Only seems to be an issue since upgrading to 2.8.0 (OSX 10.11.3)

Some layouts which I was able to access are now just stuck on the "Downloading metadata" screen when I attempt to open them. Not sure how to replicate, as there doesn't seem to be anything obviously different about the layouts that will not open, is an issue across multiple projects (including a new layout that was uploaded this morning using the Avocode Sync for Sketch plugin 3.7.0)

Resyncing individual layouts seems to fix it, just not sure what caused the issue in the first place, and there appears to be no way to tell it needs to be resynced without attempting to open it inside the Avocode app

**Comment by jakubzitny** [comment]
Hi @JayCarney, in `2.8.0` there is new handling of downloading and syncing in the app. There still might be some small bugs we didn't catch during testing.

Is there a chance some of these problems fixed themselves without resyncinc/reuploading designs to Avocode? If not, if there are designs that are stuck and reset of the app doesn't help, we'd be interesed in these. Can you please contact us at team@avocode.com, send us your Avocode email and the problematic project/design names? We'll look into it on the backend side.

Thanks.

**Comment by JayCarney** [comment]
Hi @jakubzitny this morning I tried to open the layouts that had been a problem for the last two days and they seem to be working fine now.

Thanks for the quick response
