### ISSUE TITLE
avocode website: install page

### ISSUE THREAD

**Issue by AliveDD** [avocode/avocode#921]
Your install page have images which are not optimized for retina screens :(

<img width="1440" alt="screen shot 2016-06-15 at 13 42 12" src="https://cloud.githubusercontent.com/assets/5255027/16077100/d6a4f13e-3307-11e6-8c1c-50ad11e37bb2.png">

**Comment by jakubzitny** [comment]
Thanks for the issue, we'll fix it :)

**Comment by vojtatranta** [comment]
we don't use this page anymore, so this issue will be closed
