### ISSUE TITLE
Emails sent by the "Invite a designer" form are detected as promotions/ spam

### ISSUE THREAD

**Issue by nbiton** [avocode/avocode#93]
I made two attempts to use this feature- sending to a corporate email address which is using exchange, and sending to gmail inbox.
My inbox in the corporate address has never received the invitation email.
The gmail inbox routed the invitation email to the "promotions" tab.

**Comment by rychlis** [comment]
We've changed the sender address to hello@avocode.com which seems to helped a bit, gmail usually puts invites to the Updates category at least for me.

Not receiving the email in your corporate inbox could problem on your side as well, we didn't encounter similar issues. All emails are sent by mandrill.com service and uses DKIM and SPF. The sender address change might have solved it as well. Feel free to contact us at team@avocode.com with more information about your corporate inbox to solve that issue individually.

I don't think there is much more we can do so I'm closing the issue.
