### ISSUE TITLE
Error msg info

### ISSUE THREAD

**Issue by akulov** [avocode/avocode#930]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.0
Source UID: 47722
```
TypeError: Cannot read property 'length' of undefined
    at writeFd (fs.js:1320:45)
    at fs.js:1311:7
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by vojtatranta** [comment]
Hi,
please can you tell us how did it happen? Thanks.

**Comment by akulov** [comment]
I do anything. :)
17 Июн 2016 г. 12:20 пользователь "vojtatranta" <notifications@github.com>
написал:

**Comment by vojtatranta** [comment]
So you app is practically unusable, right?
Have you tried 2.8.1? You can download it here: https://avocode.com/download

**Comment by connor-bean** [comment]
Hello @akulov -

Did downloading the newest version fix this? 

Thanks!
Connor, Avocode Support

**Comment by akulov** [comment]
Yes. Thanks.
7 Июл 2016 г. 16:36 пользователь "Connor" <notifications@github.com>
написал:

**Comment by connor-bean** [comment]
Great! I will close this out as the newest version has fixed this issue.

Please let us know of any other questions.

Thanks,
Connor, Avocode Support
