### ISSUE TITLE
Import double

### ISSUE THREAD

**Issue by t1gu1** [avocode/avocode#933]
When I import a **psd** in Avocode, the download start **two** times when i **drag and drop** it.
I work on **Linux.**

Thanks

**Comment by jakubzitny** [comment]
Hey @t1gu1, thanks for the report. 

This bug should have been fixed in Avocode `2.8.1`. Have you updated to the latest version or you have `2.8.0.`?

**Comment by petrbrzek** [comment]
Yep, this has been fixed in 2.8.1. Closing this one.
