### ISSUE TITLE
Endless "Loading metadata ..."

### ISSUE THREAD

**Issue by Rebnev** [avocode/avocode#937]
windows 10, 2.8.1, after update. Sketch design works well, but PS have endless loading, and after what avocode show me white screen

**Comment by petrbrzek** [comment]
Do you have the 64 bit version of Avocode? You can download it [here](http://media.avocode.com/download/avocode-app/2.8.1/avocode-app-windows-x64-2.8.1.exe).

**Comment by Rebnev** [comment]
Yea, I've got x64 version.
I'm trying to complete remove avocode, to clean install, but avacode dont logout and I see my projects.
Windows uninstall not working for me, remove from AppData too.
Very strange.

**Comment by JakubKontra** [comment]
+1 Endless "Loading metadata ..."

**Comment by JakubKontra** [comment]
Seems to be fixed after uninstall and re-download.

**Comment by DigTheDoug** [comment]
I have this issue as well, on OSX El Capitan 10.11.5. Avocode v 2.8.4. Tried reinstalling, same issue. I'm guessing it's a size related issue as other PSDs open without issue.
![screen shot 2016-07-13 at 8 57 12 am](https://cloud.githubusercontent.com/assets/1428256/16804100/12354574-48d8-11e6-880b-c06e9eda20dd.png)
![screen shot 2016-07-13 at 8 56 07 am](https://cloud.githubusercontent.com/assets/1428256/16804099/12320846-48d8-11e6-8fcb-77e62d4cf462.png)
