### ISSUE TITLE
uploading failed

### ISSUE THREAD

**Issue by Mo-** [avocode/avocode#938]
uploading files immediately throws an error (failed).
It is repeated in the program and on the website.
the error does not depend on the selected file - I checked on designs that previously worked fine.

**Comment by trurl-master** [comment]
Having the same issue, none of the psd's that were previously uploaded fine can be uploaded now.
2.6.0 / 2.8.1 / website

**Comment by connor-bean** [comment]
Hello!

We currently have some issues with huge bitmap images in PSD's (most of the times shutterstock images nested in a smart objects - usually with layers that are over 20mpix). Could this be the case? 

I'd recommend to use the Photoshop plugin to sync the design until we fix this issue. You can also ask your designer to resize the resolution of those images or rasterize them. If you do not have access to Photoshop, you can always send the design to us at team@avocode.com and we'll upload it for you as soon as possible.

We're already working on an improved version of rendering, which should fix the problem.

Let me know!
Thanks,
Connor, Avocode Team

**Comment by trurl-master** [comment]
I think it's not the case, even small mockups (~1mb) without any large scale graphic layers immediately fail.
*presuming it's the same issue as @Mo- has

**Comment by reme3d2y** [comment]
Having the same issue.

The problem is not in PDS's, I think.
Yesterday I was able to upload mockup after several attempts and several hours :) It was also around this time.
Today I have the same problems.

Fix this problem, please :pray:

**Comment by Mo-** [comment]
Empty psd failed too.

**Comment by limiterCore** [comment]
Can not upload any file, too. In 2.8.1 and 2.6.0 also. Hope you'll fix it soon

**Comment by trurl-master** [comment]
Guess: those who have problems are from Russia, yesterday Amazon services were blocked.
I'm able to upload currently.

**Comment by jakubzitny** [comment]
That makes sense @trurl-master. Sorry for the trouble..

How about the other guys: @limiterCore, @Mo-, @reme3d2y? Can you confirm that it's working now?

Thanks.

**Comment by limiterCore** [comment]
Yes, it's working now

**Comment by Mo-** [comment]
It's ok now.

**Comment by reme3d2y** [comment]
This morning it was ok.
