### ISSUE TITLE
The invitation link from the email leads to a 403

### ISSUE THREAD

**Issue by nbiton** [avocode/avocode#94]
I used the "Invite a designer" form to send an invitation to my gmail address.
Clicking the invitation link in the email I received leads to a 403/forbidden page.
(Window 7-Chrome)

**Comment by PavelGavlik** [comment]
Current production version has a bug, that causes 403 showing if the recipient hasn't logged in yet. Workaround is that he signs up first and the invite will be waiting in Notifications section.

We will deploy new version with bugfix in few days.

**Comment by PavelGavlik** [comment]
Feel free to reopen this if you run into any other problems.
