### ISSUE TITLE
loading stops by 95%

### ISSUE THREAD

**Issue by oxananana** [avocode/avocode#941]
windows 7, 64bit, last update 2.8.1. new psd can't upload until the end
![avocode](https://cloud.githubusercontent.com/assets/20109333/16302309/1326a2f0-3953-11e6-9705-53dec25d9f74.png)

**Comment by oxananana** [comment]
it's ok if restart the programm

**Comment by 25RBazookas** [comment]
@oxananana @jakubzitny  It's oke if you restart the program, but the issue isn't resolved. It stops at 95% and it should work without a restart.
