### ISSUE TITLE
ENOENT: resources.tar.gz in upload

### ISSUE THREAD

**Issue by liakwee-mirum** [avocode/avocode#946]
IMPORTANT: Please try to describe how did it happen.
This happens when uploading PSD into avocode.

-----
App v.2.8.2
Source UID: 15500
```
Error: ENOENT: no such file or directory, open '/Users/lilee/.avocode/userdata/15500/documents/606e5f5dde86411ab2866b7d5907d0d2/images/resources.tar.gz'
    at Error (native)
```

**Comment by jakubzitny** [comment]
Hey @liakwee-mirum, thanks for letting us know. From time to time we get this bug and we're not really sure about all the cases when it is happening. It has something to do with local cache of your Avocode data. Would you be willing to send us the file `resources.tar.gz`? It would help us to further investigate this special case.

And to fix this problem you can just remove the `userdata` directory and `state.json` file in your `~/.avocode`. Avocode will download all your files againg and the problem should be resolved.

Let us know if you have any more problems ;)

Thanks.

**Comment by jakubzitny** [comment]
Hey @liakwee-mirum, can you please re-check if the requested file is really missing frou your filesystem?
`/Users/lilee/.avocode/userdata/15500/documents/606e5f5dde86411ab2866b7d5907d0d2/images/resources.tar.gz`

**Comment by liakwee-mirum** [comment]
Hi @jakubzitny, 

I've tried your previous recommendation to delete the userdata folder and so far, i did not get the error again.

Thanks for you help

**Comment by jakubzitny** [comment]
@liakwee-mirum thanks for the info, we're glad it's (kinda) solved for you.

I'll reopen this issue though, because this is still happening to some users and we need to resolve it to 100% satisfaction :)

PS: you can unsubscribe from notifications on the right if you don't want to be bothered by further activity here.

**Comment by petrbrzek** [comment]
This issue was tough but I hope it's been fixed. Please let us know if you'll have any more trouble with this. Closing now.

**Comment by ahmadmansee1987** [comment]
i have a problem after uploading specific file from sketch to Avocode and try to open it an error message will appear says "An error occurred"
