### ISSUE TITLE
error occured

### ISSUE THREAD

**Issue by op1000** [avocode/avocode#948]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.2
Source UID: 73649
```
Error: ENOENT: no such file or directory, open '/Users/obigo/.avocode/userdata/73649/documents/b1c8d5b311564f96b8b47a928a35c3c2/images/resources.tar.gz'
    at Error (native)
```

**Comment by connor-bean** [comment]
Hey, @op1000 -

We are aware of this bug. We will close this ticket and track it in #946.

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Hey @op1000, can you please re-check if the files are really missing on your filesystem?
It'd be one of :
```
/Users/obigo/.avocode/userdata/73649/documents/b1c8d5b311564f96b8b47a928a35c3c2/images/resources.tar.gz

/Users/obigo/.avocode/userdata/73649/documents/738db11000fe46b9be463e995783a0d5/images/resources.tar.gz
```
