### ISSUE TITLE
OS X: Infinite loading PSD

### ISSUE THREAD

**Issue by lucien144** [avocode/avocode#95]
When I try to open the PSD, the Avocode keeps saying "Loading...". After one hour without any success... PM and I'll send you the public link if needed.

**Comment by petrbrzek** [comment]
We're going to release a new version of Avocode this week. Let's wait and if the problem remains we'll check it.

**Comment by lucien144** [comment]
FYI. I just tried to open the PSD in Parfait (CC) and I'm getting message, that the PSD has too many layers. So this might be the same case...

**Comment by kamil-webchefs** [comment]
The same here. Ubuntu kept on showing "Loading..." and after hour or so crashed.

**Comment by patrikholcak** [comment]
We released Avocode 1.0 today. Could you please download it and see if it works now? Thanks!

**Comment by lucien144** [comment]
No problem, I'll let you know.

Version 1.0? Wow, hope it won't be too buggy. Fingers crossed.

**Comment by blorenz** [comment]
Experiencing this error on 1.0.  I uploaded my designs via the website. I try to open in Avocode and I get an error that my Avocode has gone bad.

**Comment by petrbrzek** [comment]
Try to remove `.avcd/storage` folder in your user profile path. Let me know if that works.

**Comment by blorenz** [comment]
I didn't have a .avcd/storage so I invoked `rm -rf .avcd` which resolved my issue. Not ideal, but is working after reauthorization.

**Comment by lucien144** [comment]
New version, .avcd cleared, new PSD uploaded and still happening to me. I can send you the link to the design if needed.

**Comment by petrbrzek** [comment]
Yes, that would be great. You can share us that design via Avocode to support@avocode.com.

**Comment by lucien144** [comment]
I've already sent it to Vu :)

**Comment by Rad1calDreamer** [comment]
same problem on win7 =(
psd 27mb loading and loading and loading
