### ISSUE TITLE
.psd import error

### ISSUE THREAD

**Issue by tarasholub** [avocode/avocode#950]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.2
Source UID: 74861
```
Error: ENOENT: no such file or directory, open '/Users/tarasholub/.avocode/userdata/74861/documents/ebe52e21f6ef4ce9a40f02ce23bfdcdb/images/resources.tar.gz'
    at Error (native)
```

**Comment by connor-bean** [comment]
Hey @tarasholub -

We are aware of this bug. We will close this ticket and track it in #946.

Thanks,
Connor, Avocode Support

**Comment by jakubzitny** [comment]
Hey @tarasholub, can you please re-check if the requested file is actually missing from your filesystem?
`/Users/tarasholub/.avocode/userdata/74861/documents/ebe52e21f6ef4ce9a40f02ce23bfdcdb/images/resources.tar.gz`
