### ISSUE TITLE
Can't reorder tabs on OSX app

### ISSUE THREAD

**Issue by ybentz** [avocode/avocode#952]
Starting about 2 versions ago, I can't reorder tabs on the OSX app.
Small issue but pretty annoying.

**Comment by mark-reason** [comment]
Same on Windows

**Comment by connor-bean** [comment]
Hello @ybentz -

Please add this to our UserVoice forum and upvote it. It would also help us if you add your user case to the comment thread once you have created the suggestion ticket. 

You can find the UserVoice forum [here](https://avocode.uservoice.com/forums/277080-feature-voting).

Thanks!
Connor, Avocode Support
