### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jardicc** [avocode/avocode#954]
IMPORTANT: Please try to describe how did it happen.
I went to lunch

-----
App v.2.8.2
Source UID: 17594
```
Error: ENOENT: no such file or directory, open 'C:\Users\bereza\.avocode\userdata\17594\documents\7d2d0ca61fea44e1935cfffd653a38a2\images\resources.tar.gz'
    at Error (native)
```

**Comment by jakubzitny** [comment]
Hey @jardicc, thanks for the report. It looks like this is happening quite a lot in `2.8.2`. We're going to release next patch version next week and this problem should be handled better. However, we'd be happy to get more information form you about this. We now have suspicion this might be happening when the app is "idle", can you confirm that you found this error after your PC was asleep or similar?

We're already tracking it in #946 so I will close this issue, let's continue there.

**Comment by jakubzitny** [comment]
One more thing, can you please re-check whether the requested file exists on four filesystem?
`C:\Users\bereza\.avocode\userdata\17594\documents\7d2d0ca61fea44e1935cfffd653a38a2\images\resources.tar.gz`

**Comment by jardicc** [comment]
Jo, počítat byl v nečinosti. Tahle hláška se ukázala, když jsem se vrátil z oběda. Ten soubor už asi neexistuje.

**Comment by jakubzitny** [comment]
@jardicc díky. Mohl bys ještě prosím zkontrolovat jestli fakt neexistuje?

**Comment by jardicc** [comment]
Zadal jsem tu url do okna "spustit" a nic s tím nenalezeno. Ale nevím jeslti to není nějaký dočasný soubor, který něco může smazat. Mezi bugem a kontrolou uplynuly asi 3 hodiny

**Comment by jakubzitny** [comment]
Díky moc, to nám stačí :)
