### ISSUE TITLE
An unexpected error has occured

### ISSUE THREAD

**Issue by silvadori** [avocode/avocode#955]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.2
Source UID: 1827
```
Error: ENOENT: no such file or directory, open '/Users/younes/.avocode/userdata/1827/documents/1ae5424731da4d6bb67d6db557f70787/images/resources.tar.gz'
    at Error (native)
```

**Comment by jakubzitny** [comment]
Hey @silvadori, thanks for the report. We already know about this problem and we're trying to fix it. However, we're still not sure about all the cases it is happening.

Would you be willing to check for the existence of the requested file? It would really help us with diagnosing the problem.

`/Users/younes/.avocode/userdata/1827/documents/1ae5424731da4d6bb67d6db557f70787/images/resources.tar.gz`


We're already tracking this in #946 so I will close this thread, let's continue the conversation there.
