### ISSUE TITLE
I cannot sync sketch artboards into avocode // cannot open avocode-token.json

### ISSUE THREAD

**Issue by pulni** [avocode/avocode#956]
Whenever i try to sync Artboards i receive the following error.
See Screenshot
![160606_quote_view_desktop_2_0_v3_ed_sketch](https://cloud.githubusercontent.com/assets/3426/16495186/9957a6aa-3eec-11e6-8cfe-d21e2f61a18c.png)

When i look into the `sketch-panels.log` i see the following error

````
NO_PROXY: undefined
{ [Error: ENOENT, open '/Users/czacharias/Library/Application Support/com.bohemiancoding.sketch3/Plugins/avocode-token.json']
  errno: -2,
  code: 'ENOENT',
  path: '/Users/czacharias/Library/Application Support/com.bohemiancoding.sketch3/Plugins/avocode-token.json' }
user not logged in
```

The `avocode-token.json` is there including the right content and it is readable:

![avocode-token_json](https://cloud.githubusercontent.com/assets/3426/16495363/5fc33660-3eed-11e6-8c62-5ca0a125ebd6.png)

I also attached the `sketch-panels.log`
(removed)

**Comment by rychlis** [comment]
The ENOENT issue happened once and is no longer a problem. It seems like there is an issue with the artboard when you are syncing it, but the error is not contained in the log. Could you please try opening the OSX "Console" App, select "All Messages" in the left pane and look for any errors when you are syncing? It would be better if you could send it to team@avocode.com as it can contain sensitive data about your Avocode account

As you have posted the sketch-panels.log publicly here it could be read by anyone on the Internet, the log contains the token as well :( To be sure I've revoked all your tokens contained in the log, you will need to re-login in the extension.

**Comment by rychlis** [comment]
It's probably some issue with a some layer in the sketch file you are trying to sync, if you could send us the file to team@avocode.com it would help us find the problem more quickly.

Thanks!

**Comment by connor-bean** [comment]
Please reopen if the problem persists.
