### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alex1278** [avocode/avocode#957]
IMPORTANT: Please try to describe how did it happen.
While New PSD files were been uploaded.
-----
App v.2.8.2
Source UID: 75632
```
Error: ENOENT: no such file or directory, open 'C:\Users\most_wanted\.avocode\userdata\75632\documents\b883ae90cc5b45f8bb3ef39ab1156d44\images\resources.tar.gz'
    at Error (native)
```

**Comment by jakubzitny** [comment]
Hey @alex1278, thanks for the report. We already know about this problem and we're trying to fix it. However, we're still not sure about all the cases when it is happening. Can you please elaborate more on how did you get this error?

Would you be also willing to check for the existence of the requested file? It would really help us with diagnosing the problem:

`C:\Users\most_wanted\.avocode\userdata\75632\documents\b883ae90cc5b45f8bb3ef39ab1156d44\images\resources.tar.gz`

We're already tracking this in #946 so I will close this thread, let's continue the conversation there.
