### ISSUE TITLE
Sidebar should display fontface names properly besides telling font-weight: 100

### ISSUE THREAD

**Issue by zsitro** [avocode/avocode#958]
Many of us using fontface variables like this:

```
$fontSansBold: prelobold, $fontArial;
$fontSansLight: prelolight, $fontArial;
$fontSansRegular: prelomedium, $fontArial;
$fontSansExtralight: preloextralight, $fontArial;
```

But if you display the text properties as such (in the sidebar):

```
font-family: OpenSans;
font-weight: 400;
```

It's a pain to pair the more meaningful names like Bold, Semibold, Extralight, etc (can be up to 4-6 variations sometimes) with font-weight: 100|200|300|500|.. etc.

In Adobe Extract it was solved amazingly by displaying these real names.

**Comment by rosivanov** [comment]
+1 must have feature

**Comment by bolekkerous** [comment]
Hey - 
I believe this should work already for a while.

There should also be the full Postscript font name in the style panel available as well as in the info panel where you see all fonts and weights used in the design.

If you still encounter this or any other issue, please reopen or create a new issue.

Best regards,
Bolek, Avocode Team
