### ISSUE TITLE
win 10, black window! 

### ISSUE THREAD

**Issue by retyui** [avocode/avocode#959]
when you start avocode, I see it 
![Image of Yaktocat](http://cs633118.vk.me/v633118414/37a96/aHeVrYFePt4.jpg)

**Comment by vojtatranta** [comment]
Hi,
thank you for this report.
Do you have a 64bit version of Windows or 32?

**Comment by retyui** [comment]
64bit! 
how to look log аavocode?

**Comment by vojtatranta** [comment]
Well this boot up is Electron work, it should pop-up an error message as far as I know.
What about older versions did they work properly?

**Comment by retyui** [comment]
I upgrade to win2.8.4x64, the # problem persists (((
[](https://pp.vk.me/c633118/v633118414/37c1e/MfM41XLGl2g.jpg)

**Comment by vojtatranta** [comment]
@retyui I see, what about older version of Avocode they booted correctly?

**Comment by retyui** [comment]
an older version (2.6) I removed poslnost, cleaned the registry and temporary folders,
you can link that would download the old version

**Comment by vojtatranta** [comment]
We have not had such report. We know about crashes of Avocode when opening a larger design but that concerns on 32bit version.
Avocode 2.6.0 for Window can be downloaded here: https://avocode-media.s3.amazonaws.com/download/avocode-app/2.6.0/avocode-app-windows-2.6.0.exe

**Comment by retyui** [comment]
2.8.4x32 - same problem(

2.6 no problem!

**Comment by petrbrzek** [comment]
@retyui Could you please try this version https://upx.cz/v1vy322sygp39sugcl13k8be20sjfou9uy76n64c. We disabled GPU rasterization so that might help. Please let us know.

**Comment by retyui** [comment]
@petrbrzek Result:
![](https://pp.vk.me/c633118/v633118414/37c56/qIMtJMgD4Ho.jpg)

**Comment by petrbrzek** [comment]
@retyui Oh, one more thing. 

1. Please try to right click on Avocode icon
2. Click on Properties
3. Leave only `Avocode.exe` in Target text field
4. Add flags `Avocode.exe --disable-gpu --dev-tools`
5. Try to launch Avocode

<img width="477" alt="windows" src="https://cloud.githubusercontent.com/assets/879564/16581977/86fa4738-42ac-11e6-9c4b-8500f7e27369.png">

**Comment by retyui** [comment]
@petrbrzek  
is ok)
![](https://pp.vk.me/c633118/v633118414/37c72/7pcvAuH0rMs.jpg)

**Comment by petrbrzek** [comment]
@retyui Ok, it looks like a bug in Electron https://github.com/electron/electron/issues/4380. What is your graphics card?

**Comment by retyui** [comment]
@petrbrzek 
NVIDIA GeForce GT 630M,  [more info -> ](https://www.dropbox.com/s/q4aok44so0rxjaa/DxDiag.txt?dl=0)
