### ISSUE TITLE
Regular Expressions in Replace variable stopped working

### ISSUE THREAD

**Issue by greystate** [avocode/avocode#964]
I'm using **Avocode 2.8.4** on **OS X 10.11.5** and I have an issue with "replace" variables:

I have one that looks like this:

<img width="401" alt="avocode-replace" src="https://cloud.githubusercontent.com/assets/5463/16620451/c47ffef4-4392-11e6-83c8-071ec2a4fa56.png">

So input is: `font-size: (\d+)px;` and the replacement is: `.font-size($1);`, e.g. to convert `font-size: 30px;` into `.font-size(30);` (I'm using LESS, so I have a mixin called `.font-size()` to generate th font-size rules).

This has stopped working - replacements with exact matches and no RegEx rules seem to work fine.

**Comment by petrbrzek** [comment]
@greystate Thanks for the report. I can reproduce it so it should be fixed in next release.

**Comment by petrbrzek** [comment]
Fixed in 2.9.0.

**Comment by greystate** [comment]
Beta 2.12.0-community-beta.1 has resurfaced this exact issue 😿 

@petrbrzek
