### ISSUE TITLE
Unable to upload Sketch Files. see images attached

### ISSUE THREAD

**Issue by nckjrvs** [avocode/avocode#965]
IMPORTANT: Please try to describe how did it happen.

When trying to upload a Sketch file, it tells me that there's a new update available, however, I am on the most current version of Sketch and Avocode. I have sent screenshots of what I am getting when I try to upload. 

![screen shot 2016-07-06 at 10 44 00 am](https://cloud.githubusercontent.com/assets/8484063/16626547/a5d4c880-4366-11e6-9bb1-c1bec3d9d843.png)
![screen shot 2016-07-06 at 10 44 18 am](https://cloud.githubusercontent.com/assets/8484063/16626546/a5d47ee8-4366-11e6-8d70-8f855fd47445.png)

-----
Sketch Exporter 2.1.1 running in Sketch 3.8.3
```
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /Users/nickjarvis/…/avocode-exporter/lib/image-exporter.js:1:297
    at Object.oncomplete (fs.js:107:15)
```

**Comment by jakubzitny** [comment]
Hey @nckjrvs , you're using an old version of Avocode Sketch plugin. Please install the newest one from [manager.avocode.com](https://manager.avocode.com/download/sketch-plugin/mac/). Note that after you install the new one, you have to launch it from Plugins menu by clicking on `Avocode Sync 3.7`. The old one will be uninstalled automatically.

Feel free to let us know if you have any more problems with Avocode.
