### ISSUE TITLE
Avocode Sync Error

### ISSUE THREAD

**Issue by ddotx** [avocode/avocode#969]
IMPORTANT: Please try to describe how did it happen.

-----
App v.2.8.4
Source UID: 16320
```
TypeError: Cannot read property 'get' of undefined
    at e._loadRevisionData (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:9:31241)
    at file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:9:30329
    at Immediate._onImmediate (file:///Applications/Avocode.app/Contents/Resources/app.asar/dist/avocode.min.js:13:17516)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by connor-bean** [comment]
Hey @ddotx 

Can you give us more information as to what you were doing when you received this error?

Thanks,
Connor, Avocode Support

**Comment by ddotx** [comment]
During syncing the artwork

-- 
Dome Jantaphat
Sent with Airmail

On July 11, 2016 at 6:51:28 PM, Connor (notifications@github.com) wrote:

Hey @ddotx <https://github.com/ddotx>

Can you give us more information as to what you were doing when you
received this error?

Thanks,
Connor, Avocode Support

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/avocode/avocode/issues/969#issuecomment-231712998>, or mute
the thread
<https://github.com/notifications/unsubscribe/ALY_6n6UeJr5QufZaUEVmzfmLZzEjlIdks5qUi5AgaJpZM4JIxXx>
.

**Comment by connor-bean** [comment]
@ddotx - could you send us the problematic design to team@avocode.com?

**Comment by ddotx** [comment]
Cannot, It gone

**Comment by connor-bean** [comment]
Please reopen if you experience this again with a new design. Thanks!
