### ISSUE TITLE
Sketch sync problem

### ISSUE THREAD

**Issue by shiienurm** [avocode/avocode#97]
Sketch crashes and not finishing up my sync. It currently appears only with one specific project file. Also tried to create another file and reinstalled sync plugin, but still the same problem.

**Comment by tomashanacek** [comment]
Hi, could you please send us the problematic Sketch file to team[at]avocode.com so we can see why this happens? Thanks!

**Comment by tekdope** [comment]
I have the same problem with any Sketch file I try to upload. Reinstalled Sketch, Sketch plugin and try with old an new files. Nothing sync up.

**Comment by tomashanacek** [comment]
Hi, could you please send us the problematic Sketch file to team[at]avocode.com so we can see why this happens? Thanks!

**Comment by shiienurm** [comment]
I tried the same file on different computers and still not working. Huge problem for me!

**Comment by sethgitner** [comment]
same problem here -- it was working fine -- then i changes some things and it no longer uploads --

**Comment by tomashanacek** [comment]
Hi, new version of Sketch plugin is available: https://manager.avocode.com/downloads/

**Comment by tomashanacek** [comment]
Hi, is this still a problem with the current version?

**Comment by shiienurm** [comment]
Works fine now.

**Comment by MatthijsZw** [comment]
Still problems!
