### ISSUE TITLE
Sass variables per project, not per file

### ISSUE THREAD

**Issue by VaclovasV** [avocode/avocode#972]
Now, we have to set variables per file, not per project, this consumes lots of time.
+ variables should be synced between all team mambers (like in Zeplin)

It would be great to just paste variables into text box. Our team implemented sass variable scrapping from file and this is not very hard to implement. Would be huge lifesaver for our team. 

This will help to achieve other things, like generate project color palette from variables and etc.
Thank you!

**Comment by connor-bean** [comment]
Hey @VaclovasV 

Thanks for the suggestion. I will ask that you upvote it on our UserVoice forum [here](https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/7126248-sync-rules-and-variables-across-multiple-computers).

We use UserVoice to plan and prioritize future sprints with new features in them, so please add your user case to the comments thread after you upvote it.

Please let me know of any other questions or suggestions!

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
I am going to close this ticket here as we are already tracking it in UserVoice.
