### ISSUE TITLE
Incorrect behavior then pressing tab

### ISSUE THREAD

**Issue by DmitrySinclair** [avocode/avocode#974]
Then tab is pressed, and left/right panels visibility is changed, design shifts to the left or right by amount of the left bar width. 
I think it would be better if it remains in the same place.

**Comment by connor-bean** [comment]
Hey @DmitrySinclair -

Thanks for suggesting this. Please let us know of anything else would make Avocode better or feel free to look through our UserVoice forum [here](https://avocode.uservoice.com/forums/277080-feature-voting).

We use UserVoice to plan future "new feature" sprints, so please upvote for anything you see there that you think would be a great addition. Also, feel free to add your own suggestions too.

Thanks!
Connor, Avocode Support

**Comment by vojtatranta** [comment]
This is scheduled to be fixed in `2.14.0`

**Comment by vojtatranta** [comment]
Deployed!
