### ISSUE TITLE
Avocode can't be opened anymore after update process was canceled

### ISSUE THREAD

**Issue by petergeller** [avocode/avocode#975]
I also grabbed and installed avocode again from https://manager.avocode.com/downloads/
But after adding it to programs it's still not able to open.

OS X El Capitan 10.11.5 latest Avocode version.

**Comment by petrbrzek** [comment]
@petergeller I'm sorry for not responding earlier. It looks like you have been using 2.6.0 version and the migration mechanism failed (maybe). Do you think you could try to open Avocode from terminal like this `open -a Avocode.app  --args -- --dev-tools`? If you see any errors please send them here.

**Comment by connor-bean** [comment]
Hey @petergeller -

Did Petr's comment fix the problem you were seeing?

Thanks,
Connor, Avocode Support

**Comment by connor-bean** [comment]
I am going to close this out. Please reopen if the problem persists.

Thanks,
Connor, Avocode Support
