### ISSUE TITLE
White screen and freezing when opening PSD.

### ISSUE THREAD

**Issue by DigTheDoug** [avocode/avocode#976]
When opening a PSD from a project, it shows 'loading metadata' for a period of time before then turning completely white and freezing. Force quitting afterwards is the only way to exit.

OSX El Capitan 10.11.5. Avocode v 2.8.4. Tried reinstalling, same issue. The PSD in question is only 54 MB, it's not very large.

![screen shot 2016-07-13 at 8 56 07 am](https://cloud.githubusercontent.com/assets/1428256/16878731/b65d7366-4a7b-11e6-99b8-9ab2d9590fcc.png)
![screen shot 2016-07-13 at 8 57 12 am](https://cloud.githubusercontent.com/assets/1428256/16878730/b6584d8c-4a7b-11e6-87bc-e8398f76a5f9.png)

This looks similar to the closed issue https://github.com/avocode/avocode/issues/937#issuecomment-232347100, but the resolutions there have no effect.

**Comment by petrbrzek** [comment]
@DigTheDoug thanks for the report. Would it be possible to send me the design? I'd debug it and try to fix it. If you can, send it to me at petr@avocode.com.

**Comment by connor-bean** [comment]
I am closing this out due to inactivity. Please reopen if you have the chance to send us the design.

**Comment by DigTheDoug** [comment]
Thanks, I did send the PSD to Petr on Tuesday, I just didn't add another comment stating that. You can still keep this closed if it's taken offline now, but I haven't heard any response or confirmation back from the email yet.

**Comment by petrbrzek** [comment]
@DigTheDoug

**Comment by petrbrzek** [comment]
@DigTheDoug I'm able to reproduce the issue.

**Comment by DigTheDoug** [comment]
Hi, any update on this? Have you had a chance to find any workaround or root cause that we could remove from the PSD in order to make it usable for my team?

Thanks

**Comment by vojtatranta** [comment]
This was typical for 32bit versions of Avocode, we now ship 64bit version which should resolve such issues. Please download this version from https://avocode.com/download
