### ISSUE TITLE
Layer effects on groups applied to all child layers

### ISSUE THREAD

**Issue by Wiredframe** [avocode/avocode#977]
Instead of just applying the 

WRONG (Avocode view):
![bildschirmfoto 2016-07-16 um 10 42 45](https://cloud.githubusercontent.com/assets/13737875/16893750/10af0ca0-4b42-11e6-8d7c-03ac9648d8bf.png)

RIGHT (Photoshop):
![bildschirmfoto 2016-07-16 um 10 42 49](https://cloud.githubusercontent.com/assets/13737875/16893751/10b06ad2-4b42-11e6-92c3-ec9746759f9d.png)

**Comment by connor-bean** [comment]
Hey, thanks for the report. We are aware of this bug and we are tracking it in #227 so I will close this ticket and you can follow it there instead.
