### ISSUE TITLE
Processing takes too much time

### ISSUE THREAD

**Issue by emilsgulbis** [avocode/avocode#98]
Just downloaded latest app version, and tried to use upload, but..

![screen shot 2015-01-21 at 12 46 46 pm](https://cloud.githubusercontent.com/assets/3534160/5834992/f575c388-a16b-11e4-99cb-e1c7dbc94da5.png)

Is estimated time is real, or just constant string? 
For me now, it took more than 6 times more time than expected and still processing.

**Comment by helloiamvu** [comment]
That was a bug on our servers and the queue got stuck. The files are now being processed and should be ready soon.

**Comment by emilsgulbis** [comment]
Thumb up! Cool!

**Comment by emilsgulbis** [comment]
And again.. 20 minutes for 1.7 MB file
![screen shot 2015-02-02 at 12 12 57 pm](https://cloud.githubusercontent.com/assets/3534160/5998865/deb016b8-aad4-11e4-80d6-1a63847418d5.png)
