### ISSUE TITLE
Team management

### ISSUE THREAD

**Issue by nsickness** [avocode/avocode#980]
Can you please add "unselect all" button in User permissions popup? Now we have more than 200 projects and if I want to select only couple of projects to be visible for person I need to uncheck almost all of them.

Thank You!

**Comment by bolekkerous** [comment]
Hey - 
I believe that this should not be applicable with the new account settings, it should be unselected by default so you can select just the projects you want them in.

Hope it helps!
Best regards,
Bolek, Avocode Team
