### ISSUE TITLE
Not visible image

### ISSUE THREAD

**Issue by yesleestudio** [avocode/avocode#984]
I uploaded at sketch plugin v 3.8.
but Image is not visible. What's problem?

<img width="1391" alt="2016-07-21 5 07 08" src="https://cloud.githubusercontent.com/assets/15510661/17015603/f4a6d038-4f65-11e6-9f77-f22941b24441.png">

**Comment by connor-bean** [comment]
Hey @yesleestudio -
We've just released Sketch plugin 3.8 which supports Sketch version 3.9.

Get it now! 👉 https://github.com/avocode/avocode/blob/master/sketch-plugin.md

Let us know if you have any problems with the newer version!

Thanks,
Connor, Avocode Support
