### ISSUE TITLE
Error: the document is corrupted

### ISSUE THREAD

**Issue by pju-** [avocode/avocode#988]
Hello,

when working with a rather large Sketch file (many layers/20mpx) with two artboards, I get the following error when trying to open a synced design in Avocode:

```
The document is corrupted.
Some layers are missing their image data. These are marked in the layers panel.
It is unlikely that there is a way to fix the document other than uploading a new revision.
```

I get that same error in both the latest Windows and OSX versions.
In sketch-panels.log I could not find any glaring errors so far.

Sometimes a design will upload correctly after a few tries, but then stop working after trying to sync the second design.

Do you have any idea what could cause this?
How can I help you debug this, do you need the sketch file, my account info or anything else?

Thanks,
p

**Comment by connor-bean** [comment]
Hey @pju- 

Could you send us the sketch logs and the actual design to team@avocode.com?

Thanks,
Connor, Avocode Support

**Comment by pju-** [comment]
Hm, this is really strange. I was having the same troubles with two files. After waiting for a few days and updating Sketch to the newest version, one file has no more troubles at all. The other file still showed the same error, but after re-synching it's gone.

I will still send you the file so you can see if it's of interest to you and whether anything shows up in the logs.

**Comment by connor-bean** [comment]
I will close this out since it worked. Please reopen if you experience this again, though.

Thanks!
Connor, Avocode Support
