### ISSUE TITLE
Bug with template loading

### ISSUE THREAD

**Issue by sanchahous** [avocode/avocode#989]
When try to open template, I see the next picture Downloading image data... That's it. Internet work perfect and I don't have problem with it. So some problem from your side I think.
Add picture also
![123](https://cloud.githubusercontent.com/assets/6237875/17101122/6f47d1ee-527b-11e6-83ad-1951a859339f.jpg)
i see this picture for at least 20 minutes. But there one or two images...

**Comment by connor-bean** [comment]
Hello @sanchahous -

We currently have some issues with huge bitmap images in PSD's (most of the times shutterstock images nested in a smart objects - usually with layers that are over 20mpix). Could this be the case? 

I'd recommend to use the Photoshop plugin to sync the design until we fix this issue. You can also ask your designer to resize the resolution of those images or rasterize them. If you do not have access to Photoshop, you can always send the design to us at team@avocode.com and we'll upload it for you as soon as possible.

We're already working on an improved version of rendering, which should fix the problem.

Let me know!
Thanks,
Connor, Avocode Team

**Comment by sanchahous** [comment]
I think this can be the problem there are one large image. Waiting for fix, thx)

**Comment by vojtatranta** [comment]
It should work in newer versions, please upate! And comment, if it still persists.
