### ISSUE TITLE
Uncaught TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by enzy** [avocode/avocode#99]
Cannot open project file (keeps loading...) because of this error:

```
[13008:0121/165649:INFO:CONSOLE(7)] "Uncaught TypeError: Cannot read property 'title' of undefined", source: c:\Programs\Avocode\resources\app\node_modules\avocode-octopus\lib\main.js (7)
```

OS: Win 8.1 x64
Avocode: 1.0

**Comment by petrbrzek** [comment]
Could you share us the problematic design to support@avocode.com. (ideally through Avocode manager)

**Comment by enzy** [comment]
Just shared a sample one.

**Comment by petrbrzek** [comment]
I've tested it on mac and windows and it works. 

1. Try to close Avocode app and delete .avcd folder from your user profile. 
2. Let me know if that works
3. Profit!

**Comment by enzy** [comment]
Deletion of .avcd folder helped, thanks!
