### ISSUE TITLE
Photoshop extension font color too bright (white on white)

### ISSUE THREAD

**Issue by erikvandewiel** [avocode/avocode#991]
![screen shot 2016-07-25 at 15 00 04](https://cloud.githubusercontent.com/assets/20322281/17102564/8420068c-527a-11e6-92f9-437813105e87.png)
Minor bug/improvement: when using the light photoshop background, the extension text isn't readable. Text and background are both too light.

**Comment by jakubzitny** [comment]
Closing with respect to #551. We're preparing a new plugin for next Avocode release. Stay tuned 😉
