### ISSUE TITLE
Get Code for Variables

### ISSUE THREAD

**Issue by retyui** [avocode/avocode#992]
Почему бы не сделать также и импорт переменных? 
2.8.4x64 win

**Comment by connor-bean** [comment]
Здравствуйте!

Мы в настоящее время не поддерживаем эту функцию, но планируем в будущем.

Пожалуйста, добавьте ваш случай использования в комментарии здесь:

https://avocode.uservoice.com/forums/277080-feature-voting/suggestions/11136447-import-variables

Так как это опубликовано на UserVoice, мы закрываем этот билет и будем отслеживать его там.

С уважением
